#+TITLE:  [笔记]﻿七堂极简物理课
#+AUTHOR: Yang Yingchao
#+DATE:   2024-04-16
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:  align nodlcheck oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+LANGUAGE: en
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :tag1:tag2:note:ireader:



#+BEGIN_QUOTE
一个没有“浪费”过时间的人终将一事无成。
#+END_QUOTE


#+BEGIN_QUOTE
广义相对论”，这是他的杰作。伟大的苏联物理学家列夫·朗道（Lev Landau）称之为“最美的理论”。
#+END_QUOTE


#+BEGIN_QUOTE
引力场不“弥漫”于空间，因为它本身就是空间。这就是广义相对论的思想。
#+END_QUOTE


#+BEGIN_QUOTE
空间不再是一种有别于物质的东西，而是构成世界的“物质”成分之一，一种可以波动、弯曲、变形的实体。
#+END_QUOTE


#+BEGIN_QUOTE
太阳会使其周围的空间发生弯曲，所以地球并不是在某种神秘力量的牵引下绕着太阳旋转，而是在一个倾斜的空间中行进，就好像弹珠在漏斗中滚动一样：漏斗中心并不会产生什么神秘的“力量”，是弯曲的漏斗壁使弹珠滚动的。所以无论是行星绕着太阳转，还是物体下落，都是因为空间发生了弯曲。
#+END_QUOTE


#+BEGIN_QUOTE
任何一个弯曲空间的特征都可以用一个数学量来描述，如今我们称之为“黎曼曲率”，用大写的“R”来表示。
#+END_QUOTE


#+BEGIN_QUOTE
空间在有物质的地方会发生弯曲。
#+END_QUOTE


#+BEGIN_QUOTE
空间不可能一直保持静止，它一定是在不断膨胀的。
#+END_QUOTE


#+BEGIN_QUOTE
恒星会因能量耗尽,无法支撑其自身
#+END_QUOTE


#+BEGIN_QUOTE
恒星会因能量耗尽,无法支撑其自身重量而坍塌,
#+END_QUOTE


#+BEGIN_QUOTE
恒星会因能量耗尽,无法支撑其自身重量而坍塌,使空间扭曲,那是什么在支撑宇宙空间的膨胀? 什么时候宇宙会开始收缩?宇宙收缩时,人类会变成什么样?会受到哪些影响?
#+END_QUOTE


#+BEGIN_QUOTE
我认为，我们这个物种不会延续很久。我们似乎没有乌龟的那种本事，能够几亿年来一直保持着原来的样子，那可是人类存在时间的好几百倍。我们属于一个短命的物种，所有的表亲都已经全部灭绝。而且我们一直在破坏。我们已经造成气候和环境的恶化，恐怕自己也难逃恶果。对地球来说，这只是一个无关紧要的小挫折，但我认为，人类将很难安然无恙地渡过这个难关。更糟的是，公众舆论和政治观点倾向于把头深埋在沙子里，无视我们正在面临的危险。在地球上，我们也许是唯一知道我们的个体必将死亡的物种，我害怕在不久的将来我们也会成为唯一一个眼睁睁看着自己末日到来的物种，或至少是见证自己文明灭亡的物种。
#+END_QUOTE
