#+TITLE:  [笔记]间客
#+AUTHOR: Yang Yingchao
#+DATE:   2024-04-16
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:  align nodlcheck oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+LANGUAGE: en
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :tag1:tag2:note:ireader:



#+BEGIN_QUOTE
用 DVC 不重要，关键是要用好，说她喷 DVC 喷多了，就像是说她拿钞票烧着点香烟一样没品
#+END_QUOTE


#+BEGIN_QUOTE
眼与眼的对视，其实只是为了肉与肉的摩擦，体液与体液间的交换。”
#+END_QUOTE


#+BEGIN_QUOTE
长久的安静，餐厅远处的钢琴正在流淌着音符，间或有几声银制刀叉触碰在瓷面上的声音响起。在这片沉默之中，许乐低着头等待着对方的回答，没有注意到张小萌在长久的沉默之后，正用一种负疚而哀怨的眼光看着他
#+END_QUOTE


#+BEGIN_QUOTE
怕死要来，不怕死也要来……怕死不怕死，我都带着诚意扑面而来
#+END_QUOTE


#+BEGIN_QUOTE
，一朵新年的礼花在天边绽开，映着这两个年轻人的身影，显得无比寂寞。
#+END_QUOTE


#+BEGIN_QUOTE
真的是比烟花还要寂寞了。
#+END_QUOTE


#+BEGIN_QUOTE
当你开始旅程时偏移正确方向一公分，当你结束旅程的时候，你会发现自己已经远离了目的地一千公里
#+END_QUOTE


#+BEGIN_QUOTE
看来自古以来都是同样，敌人，永远是内部的最为残酷。
#+END_QUOTE


#+BEGIN_QUOTE
往年远观可以赏之为奇山妙石，如今近处，才发现那是艰涩山路，并不好过
#+END_QUOTE


#+BEGIN_QUOTE
“我总以为，宇宙中的一切，总应该是有规律可循，或者说是有道理可讲
#+END_QUOTE


#+BEGIN_QUOTE
珀色的烈酒还放在黑白纹石桌面上，葡萄发酵蒸馏混着数年地窖里的光阴，在半空的杯中逐渐渗漫，钻入人们的鼻中，虽然不如酒馆外面那个橡木桶喷放的稀释香精清晰，但像是有生命力一般，感染力十足。
#+END_QUOTE


#+BEGIN_QUOTE
这大概便是联邦社会的写照？不能飞或不想飞的才能留下，那些敢在大人物头顶拉屎的家伙，只有离开。
#+END_QUOTE


#+BEGIN_QUOTE
在首都特区宪章广场边上，居然藏着如此大的一家私人会所，举头望去便是历史，空气中呼吸的便是权力，四周布设简洁之中隐藏着奢华到极致的绚烂意味，虽不如林园有山水相伴，开阔清丽，但从贵重感觉上，却早已攀到了极致。
#+END_QUOTE


#+BEGIN_QUOTE
青石为路，古意从微湿的石缝里渗了出来，在四周老式工艺的粉墙上一润，配着温暖的脚下生风，硬生生在这寒冷的首都冬天里，把流风坡会所变成了春秋季的园林
#+END_QUOTE


#+BEGIN_QUOTE
人们在做某件大事之前，总是习惯性地要用很多精神上的事情，来提升自己的勇气或是信心，许
#+END_QUOTE


#+BEGIN_QUOTE
皇帝从来没有消失，他只不过换了几身衣服。 ——
#+END_QUOTE


#+BEGIN_QUOTE
时光如流水，早已将他心上那些少年时的酸楚心痛痕迹冲洗的淡然，只是就像西林名产醋腌茄子一样，被水冲过的皮本身没有什么味道，内里却依然酸的让人想要流眼泪
#+END_QUOTE


#+BEGIN_QUOTE
怀念是一行潦草的诗
#+END_QUOTE


#+BEGIN_QUOTE
靠牺牲他人而获取的未来，只能是全无未来的一种无聊重复。”
#+END_QUOTE


#+BEGIN_QUOTE
在某些特定时刻，总是需要做出一定的妥协和让步，而这种妥协与让步往往比大踏步前进更需要智慧和勇气。”
#+END_QUOTE


#+BEGIN_QUOTE
我将来的墓志铭会写：一个都不原谅，所以你们也不用原谅我。
#+END_QUOTE


#+BEGIN_QUOTE
，垃圾是从来不会自己走进垃圾箱的。”
#+END_QUOTE


#+BEGIN_QUOTE
：人死并不如灯灭，灯有光明，照不见的地方是黑暗。做错了事情，就必须付出代价。”
#+END_QUOTE


#+BEGIN_QUOTE
信息不对称是联邦社会不公平的根源，我们想做的，就是敞开这些信息，由联邦普通公民进行最有效最直
#+END_QUOTE


#+BEGIN_QUOTE
。 要知道真实的世界里，从来没有小说中那样的奇遇，小概率事件必然有其内部的原因，富人的后代是富人，传奇的身边是传奇，白手起家，傻小子遇明师的故事，终究只能是故事
#+END_QUOTE


#+BEGIN_QUOTE
即将来临的一天，比过去的一年更加悠长。
#+END_QUOTE


#+BEGIN_QUOTE
一个都不原谅，你们也不用原谅我
#+END_QUOTE


#+BEGIN_QUOTE
一个社会的落后先是精英的落后，而精英的落后最显著的标志是他们经常指责人民的落后。
#+END_QUOTE
