#+TITLE:  [笔记]失控·东西文库
#+AUTHOR: Yang Yingchao
#+DATE:   2024-04-16
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:  align nodlcheck oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+LANGUAGE: en
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :tag1:tag2:note:ireader:



#+BEGIN_QUOTE
机械”与“生命”这两个词的含义在不断延展，直到某一天，所有结构复杂的东西都被看作是机器，而所有能够自维持的机器都被看作是有生命的。
#+END_QUOTE


#+BEGIN_QUOTE
这是一个白痴的选举大厅，由白痴选举白痴，其产生的效果却极为惊人。这是民主制度的真髓，是彻底的分布式管理。
#+END_QUOTE


#+BEGIN_QUOTE
如今根据雷诺兹的算法，群体被看作是一种自适应的技巧，适用于任何分布式的活系统，无论是有机的还是人造的。
#+END_QUOTE


#+BEGIN_QUOTE
但要遵循算法中植入的几条简单规则：不要撞上其他的蝙蝠，跟上自己旁边的蝙蝠，离队不要太远。当这些“算法蝙蝠”在屏幕上运行起来时，就如同真的蝙蝠一样成群结队而行了。 群体规律是由克雷格·雷诺兹〔
#+END_QUOTE


#+BEGIN_QUOTE
但要遵循算法中植入的几条简单规则：不要撞上其他的蝙蝠，跟上自己旁边的蝙蝠，离队不要太远。当这些“算法蝙蝠”在屏幕上运行起来时，就如同真的蝙蝠一样成群结队而行了。 群体规律是由克雷格·雷诺兹〔10〕发现的。
#+END_QUOTE


#+BEGIN_QUOTE
“蜂群思维”的神奇在于，没有一只蜜蜂在控制它，但是有一只看不见的手，一只从大量愚钝的成员中涌现出来的手，控制着整个群体。它的神奇还在于，量变引起质变。
#+END_QUOTE


#+BEGIN_QUOTE
“蜂群思维”的神奇在于，没有一只蜜蜂在控制它，但是有一只看不见的手，一只从大量愚钝的成员中涌现出来的手，控制着整个群体。它的神奇还在于，量变引起质变。要想从单个虫子的机体过渡到集群机体，只需要增加虫子的数量，使大量的虫子聚集在一起，使它们能够相互交流。等到某一阶段，当复杂度达到某一程度时，“集群”就会从“虫子”中涌现出来。
#+END_QUOTE


#+BEGIN_QUOTE
这里有一个关于活系统的普遍规律：低层级的存在无法推断出高层级的复杂性。不管是计算机还是大脑，也不管是哪一种方法——数学、物理或哲学——如果不实际地运行它，就无法揭示融于个体部分的涌现模式。
#+END_QUOTE
