#+TITLE:  [笔记]MacTalk·人生元编程
#+AUTHOR: Yang Yingchao
#+DATE:   2024-04-16
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:  align nodlcheck oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+LANGUAGE: en
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :tag1:tag2:note:ireader:



#+BEGIN_QUOTE
写作即思考。写作其实就代表思考，你需要言之有物，需要架构需要梳理，要有开端有结尾有结论有主题，特别神奇的是你构思了一篇文章，写完后发现文章像具备了生命一样生长出了很多奇异的果实，它们就在那些文字中间微微颤动，闪烁着独特的光泽，仿佛被岁月冲刷过的鹅卵石一样，而这一切你可能完全没有想到过，而且不可复制。
#+END_QUOTE


#+BEGIN_QUOTE
人长大总是伴随着痛苦，现实变得越来越现实，那些无限可能都变成了没有可能或很小可能，这东西是很残酷的。当年我进入洪恩软件的时候，大概 24 岁，洪恩的总
#+END_QUOTE


#+BEGIN_QUOTE
人长大总是伴随着痛苦，现实变得越来越现实，那些无限可能都变成了没有可能或很小可能，这东西是很残酷的。
#+END_QUOTE


#+BEGIN_QUOTE
这时候你就会慢慢认识到，想取得什么样的成就，或者想成为什么样的人，除了通过长期艰苦的练习和有意识的提升，资质、环境、勇气、运气等同样重要。
#+END_QUOTE


#+BEGIN_QUOTE
其实都在，它们就藏在某个角落默默的等着，一旦你准备重新上路，它们就会跳出来，指引你前行。所以最重要的是你还想做事，而不是混世。
#+END_QUOTE


#+BEGIN_QUOTE
是把目前正在做的事情做好，如果你把不感兴趣的事情都做好了，一旦你找到自己的方向，那你得做得多好啊。
#+END_QUOTE


#+BEGIN_QUOTE
其实都在，它们就藏在某个角落默默的等着，一旦你准备重新上路，它们就会跳出来，指引你前行。所以最重要的是你还想做事，而不是混世。有人说不知道自己想做什么，那么最好的办法就是把目前正在做的事情做好，如果你把不感兴趣的事情都做好了，一旦你找到自己的方向，那你得做得多好啊。
#+END_QUOTE


#+BEGIN_QUOTE
其实都在，它们就藏在某个角落默默的等着，一旦你准备重新上路，它们就会跳出来，指引你
#+END_QUOTE


#+BEGIN_QUOTE
其实都在，它们就藏在某个角落默默的等着，一旦你准备重新上路，它们就会跳出来，指引你前行。所以最重要的是你还想做事，而不是混世
#+END_QUOTE


#+BEGIN_QUOTE
是把目前正在做的事情做好，如果你把不感兴趣的事情都做好了，一旦你找到自己的方向，那你得做得多好啊。
#+END_QUOTE


#+BEGIN_QUOTE
有人说不知道自己想做什么，那么最好的办法就是把目前正在做的事情做好，如果你把不感兴趣的事情都做好了，一旦你找到自己的方向，那你得做得多好啊。
#+END_QUOTE


#+BEGIN_QUOTE
到了 40 岁，该明白的都明白了，不明白的估计你也不想去明白了，所以就不惑了。但现实的情况是，如果你一直在思考、读书、实践，做自己认为对的事情，到了 40 岁，你会发现不是不惑，而是有了更多的惑。这种未知的恐惧可能会伴随我们的一生
#+END_QUOTE
