#+TITLE:  [笔记]不可不知的历史系列
#+AUTHOR: Yang Yingchao
#+DATE:   2024-04-16
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:  align nodlcheck oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+LANGUAGE: en
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :tag1:tag2:note:ireader:



#+BEGIN_QUOTE
你们是世上的光，城造在山上是不能隐藏的。”
#+END_QUOTE


#+BEGIN_QUOTE
你们是世上的光，城造在山上是不能隐藏的。”清教徒相信他们是被上帝选中的选民，是人类世界的领导者。他们此行的目的就是要建立一座闪耀上帝之光的山巅之城。
#+END_QUOTE


#+BEGIN_QUOTE
历史学家克罗齐有一句名言“一切历史都是当代史”，历史解释是为当代人服务的，所以无论何种解释都有其合理性，也自有其偏颇之处。历史从不是给人以答案，它只是过往的回响，为人们理解当下提供更多的选项。 第二章 革命时代（1775—1820）：独立战争与建立联邦 刚刚独立的美国是一个松散的邦联，中央政府衰弱到连债务都还不起，社会内部各阶层之间矛盾丛生。
#+END_QUOTE


#+BEGIN_QUOTE
历史学家克罗齐有一句名言“一切历史都是当代史”，历史解释是为当代人服务的，所以无论何种解释都有其合理性，也自有其偏颇之处。历史从不是给人以答案，它只是过往的回响，为人们理解当下提供更多的选项。
#+END_QUOTE


#+BEGIN_QUOTE
我们认为这些真理是不言而喻的：人人生而平等，造物者赋予他们若干不可剥夺的权利，其中包括生命权、自由权和追求幸福的权利。”
#+END_QUOTE


#+BEGIN_QUOTE
宪法原文由序言和 7 条正文组成，规定美国由原来的邦联制改为实行联邦制政体，建立总统制民主共和国，立法、行政、司法三权分立、相互制衡。立法权属于美国国会，行政权属于美国总统，司法权属于美国联邦最高法院。对于国会、总统、最高法院的产生与组成，宪法中都做出了明确的规定。
#+END_QUOTE


#+BEGIN_QUOTE
为了让这种行为合理化，美国国内渐渐出现了一种“天定命运”的理论。约翰·奥沙利文是杂志《民主评论》的编辑，他在 1845 年创造了这个词。这个特别的词汇表达了一种信念，即美国优越的制度和文化赋予美国人将其文明传播到整个北美大陆的权利乃至责任，这符合上帝的旨意。
#+END_QUOTE


#+BEGIN_QUOTE
年幼的卡内基先后曾在纺织厂、锅炉房中担任童工，艰辛劳动之余，晚上参加夜校学习。在学习中他掌握的会计知识，可能对其一生起到了重要作用。14 岁时，卡内基成为一名送电报的小报童。但他并未局限于手头的电报分发工作，而是利用这一机会牢记了匹兹堡这个工业中心城市中每家公司的名称和特点，同时也了解到了这些公司的经济和业务状况。18 岁时，他被宾夕法尼亚铁路公司的一个主管看中，成为其私人电报员和秘书。6年后，他便当上了这家公司西部管理区的主任。在这里，他进一步掌握了现代大型企业的管理方法，并开始进行投资。
#+END_QUOTE


#+BEGIN_QUOTE
卡内基大量聘用专业技术人才及管理人才，他的一句名言广为人知：“如果把我的厂房设备、材料全部烧毁，但只要保住我的全班人马，几年以后，我仍将是一个钢铁大王。”对于优秀员工，卡内基采用将公司股权分给他们的方式，既作为奖励，又能将他们的切身利益与公司发展牢牢结合在一起，使其同样成为公司的一部分。
#+END_QUOTE


#+BEGIN_QUOTE
伊甸”在苏美尔语中是荒原的意思。《
#+END_QUOTE


#+BEGIN_QUOTE
1982 年 3 月 23 日，在一篇演说中，里根总统宣布美国将建立一张“天网”，对袭击美国的导弹进行拦截，建立全方位的反弹道导弹综合主体防御系统。该计划表面上以防御为主，其实是针对苏联的一项战略，该战略既可以确立对苏联的核军事优势，又能够把与苏联的军备竞赛引向太空，达到“以压促变”分流苏联经济的目的。同时，它还有利于推动美国高科技发展的目标。为了应对美国的“星球大战计划”，苏联投入了大量的资金，经济发展因此受到严重损害。
#+END_QUOTE


#+BEGIN_QUOTE
赫鲁晓夫时期的改革不仅层次浅，而且非常盲目，非常随意，没有经过严密的论证，这也是其改革虽然顺应潮流，但是改革没有成效的重要原因。如何评价赫鲁晓夫的改革，也许正如著名的抽象派艺术家涅伊兹韦斯内给他设计的墓碑一样：黑白各半。
#+END_QUOTE


#+BEGIN_QUOTE
苏联的僵化保守与勃列日涅夫的个性也有密切的关系，仅从其对勋章的热爱就可以看出来。勃列日涅夫的照片，能够迅速给人留下各种深刻印象的就是衣服上琳琅满目的勋章。在他去世之后的送葬队伍里面，竟然有 44 个人是专门给他捧着各种勋章的。除了“英雄母亲”的勋章之外，他获得了苏联境内所有可能获得的勋章，同时还有外国领导人送给他的各种勋章。爱慕荣誉之人，焉能脚踏实地做好事情
#+END_QUOTE


#+BEGIN_QUOTE
苏联的僵化保守与勃列日涅夫的个性也有密切的关系，仅从其对勋章的热爱就可以看出来。勃列日涅夫的照片，能够迅速给人留下各种深刻印象的就是衣服上琳琅满目的勋章。在他去世之后的送葬队伍里面，竟然有 44 个人是专门给他捧着各种勋章的。除了“英雄母亲”的勋章之外，他获得了苏联境内所有可能获得的勋章，同时还有外国领导人送给他的各种勋章。爱慕荣誉之人，焉能脚踏实地做好事情呢？
#+END_QUOTE


#+BEGIN_QUOTE
戈尔巴乔夫在政治上信奉绝对哲学，坚信“绝对的自由”“绝对的公开”与“绝对的多元化”，刺激人们开始疯狂地揭露社会的阴暗面，从而走上了自己打到自己、自己瓦解自己的道路。最终，苏联经济搞穷了，政治搞乱了，人心涣散了，国家解体
#+END_QUOTE


#+BEGIN_QUOTE
1985 年，玻利维亚的通货膨胀率已经高达 24000%，经济负增长竟然达到了 12%的惊人数字，但是仅仅几个星期之内，在使用此方法之后，通货膨胀率已经下降到两位数字。
#+END_QUOTE


#+BEGIN_QUOTE
在三岛由纪夫之后的昭和岁月中，日本文坛依旧有着不少璀璨之星，比
#+END_QUOTE
