#+TITLE:  [笔记]水浒传
#+AUTHOR: Yang Yingchao
#+DATE:   2024-04-16
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:  align nodlcheck oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+LANGUAGE: en
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :tag1:tag2:note:ireader:



#+BEGIN_QUOTE
四十二年，改了九个年号。自天圣元年
#+END_QUOTE


#+BEGIN_QUOTE
遥山叠翠，远水澄清。奇花绽锦绣铺林，嫩柳舞金丝拂地。风和日暖，时过野店山村；路直沙平，夜宿邮亭驿馆。罗衣荡漾红尘内，骏马驱驰紫陌中。
#+END_QUOTE


#+BEGIN_QUOTE
草铺横野六七里，笛弄晚风三四声。 归来饱饭黄昏后，不脱蓑衣卧月明。
#+END_QUOTE


#+BEGIN_QUOTE
绛帻鸡人报晓筹，尚衣方进翠云裘。 九天阊阖开宫殿，万国衣冠拜冕旒。 日色才临仙掌动，香烟欲傍衮龙浮。 朝罢须裁五色诏，佩声归到凤池头。
#+END_QUOTE


#+BEGIN_QUOTE
试看书林隐处，几多俊逸儒流。虚名薄利不关愁，裁冰及剪雪，谈笑看吴钩。评议前王并后帝，分真伪占据中州，七雄扰扰乱春秋。兴亡如脆柳，身世类虚舟。见成名无数，图名无数，更有那逃名无数。霎时新月下长川，江湖变桑田古路。讶求鱼缘木，拟穷猿择木，恐伤弓远之曲木。不如且覆掌中杯，再听取新声曲度。
#+END_QUOTE


#+BEGIN_QUOTE
纷纷五代乱离间，一旦云开复见天。 草木百年新雨露，车书万里旧江山。 寻常巷陌陈罗绮，几处楼台奏管弦。 人乐太平无事日，莺花无限日高眠。
#+END_QUOTE


#+BEGIN_QUOTE
一个名儒，姓邵，讳尧夫，道号康节先生所作。
#+END_QUOTE


#+BEGIN_QUOTE
万姓熙熙化育中，三登之世乐无穷！ 岂知礼乐笙镛治，变作兵戈剑戟丛。 水浒寨中屯节侠，梁山泊内聚英雄。 细推治乱兴亡教，尽属阴阳造化功! 第
#+END_QUOTE


#+BEGIN_QUOTE
万姓熙熙化育中，三登之世乐无穷！ 岂知礼乐笙镛治，变作兵戈剑戟丛。 水浒寨中屯节侠，梁山泊内聚英雄。 细推治乱兴亡教，尽属阴阳造化功! 第
#+END_QUOTE


#+BEGIN_QUOTE
万姓熙熙化育中，三登之世乐无穷！ 岂知礼乐笙镛治，变作兵戈剑戟丛。 水浒寨中屯节侠，梁山泊内聚英雄。 细推治乱兴亡教，尽属阴阳造化功! 第
#+END_QUOTE


#+BEGIN_QUOTE
万姓熙熙化育中，三登之世乐无穷！ 岂知礼乐笙镛治，变作兵戈剑戟丛。 水浒寨中屯节侠，梁山泊内聚英雄。 细推治乱兴亡教，尽属阴阳造化功!
#+END_QUOTE


#+BEGIN_QUOTE
矛锤弓弩铳，鞭锏剑链挝， 斧
#+END_QUOTE


#+BEGIN_QUOTE
矛锤弓弩铳，鞭锏剑链挝， 斧钺并戈戟，牌棒与枪杈。
#+END_QUOTE


#+BEGIN_QUOTE
窗外日光弹指过，席间花影坐前移。 一杯未进笙歌送，阶下辰牌又报时。
#+END_QUOTE


#+BEGIN_QUOTE
叫杀羊置酒相待，晚间收拾客房安歇。次日，又备酒食
#+END_QUOTE


#+BEGIN_QUOTE
员外上了马，两个并马行程，于路说些旧话，投七宝村来。不多时，早到庄前下马。赵员外携住
#+END_QUOTE


#+BEGIN_QUOTE
在世为人保七旬，何劳日夜弄精神？ 世事到头终有尽，浮花过眼总非真。 贫穷富贵天之命，事业功名隙里尘。 得便宜处休欢喜，远在儿孙近在身。
#+END_QUOTE


#+BEGIN_QUOTE
头上青天只恁欺，害人性命霸人妻。 须知奸恶千般计，要使英雄一命危。 忠义萦心由秉赋，贪嗔转念是慈悲。 林冲合是灾星退，却笑高俅枉作为。 话说
#+END_QUOTE


#+BEGIN_QUOTE
头上青天只恁欺，害人性命霸人妻。 须知奸恶千般计，要使英雄一命危。 忠义萦心由秉赋，贪嗔转念是慈悲。 林冲合是灾星退，却笑高俅枉作为。
#+END_QUOTE


#+BEGIN_QUOTE
可怜豪杰，等闲来赴鬼门关；惜哉英雄，到此翻为槐国梦。万里黄泉无旅店，三魂今夜落谁家？ 毕竟看林冲性命如何？且听下回分解。
#+END_QUOTE


#+BEGIN_QUOTE
可怜豪杰，等闲来赴鬼门关；惜哉英雄，到此翻为槐国梦。万里黄泉无旅店，三魂今夜落谁家？
#+END_QUOTE


#+BEGIN_QUOTE
《鹧鸪天》： 千古高风聚义亭，英雄豪杰尽堪惊。智深不救林冲死，柴进焉能擅大名。 人猛烈，马狰狞，相逢较艺论专精。展开缚虎屠龙手，来战移山跨海人。
#+END_QUOTE


#+BEGIN_QUOTE
林冲火烟堆里，争些断送了余生；风雪途中，几被伤残性命。直使宛子城中屯甲马，梁山泊上列旌旗。
#+END_QUOTE


#+BEGIN_QUOTE
图。 若非风雪沽村酒，定被焚烧化朽枯。 自谓冥中施计毒，谁知暗里有神扶！ 最怜万死逃生地，真是瑰奇伟丈夫。
#+END_QUOTE


#+BEGIN_QUOTE
天理昭昭不可诬，莫将奸恶作良图。 若非风雪沽村酒，定被焚烧化朽枯。 自谓冥中施计毒，谁知暗里有神扶！ 最怜万死逃生地，真是瑰奇伟丈夫。 话说当日林冲正闲走间，忽然背后人叫，回头看时，却认得是酒生儿李小二。当初在东京时，多得林冲看顾。这李小二先前在东京时，不合偷了店主人家财，被捉住了，要送官司问罪，却得
#+END_QUOTE


#+BEGIN_QUOTE
天理昭昭不可诬，莫将奸恶作良图。 若非风雪沽村酒，定被焚烧化朽枯。 自谓冥中施计毒，谁知暗里有神扶！ 最怜
#+END_QUOTE


#+BEGIN_QUOTE
天理昭昭不可诬，莫将奸恶作良图。 若非风雪沽村酒，定被焚烧化朽枯。 自谓冥中施计毒，谁知暗里有神扶！ 最怜万死逃生地，真是瑰奇伟丈夫。
#+END_QUOTE


#+BEGIN_QUOTE
“仗义是林冲，为人最朴忠。 江湖驰闻望，慷慨聚英雄。 身世悲浮梗，功名类转蓬。 他年若得志，威镇泰山东!”
#+END_QUOTE


#+BEGIN_QUOTE
因。 落草固缘屠国士，卖刀岂可杀平人？ 东京已降天蓬帅，北地生成黑煞神。 豹子头逢青面兽，同归水浒乱乾坤。
#+END_QUOTE


#+BEGIN_QUOTE
天罡地煞下凡尘，托化生身各有因。 落草固缘屠国士，卖刀岂可杀平人？ 东京已降天蓬帅，北地生成黑煞神。 豹子头逢青面兽，同归水浒乱乾坤。
#+END_QUOTE


#+BEGIN_QUOTE
得罪幽燕作配戎，当场比试较英雄。 棋逢敌手难藏幸，将遇良才怎用功！ 鹊画弓弯欺满月，点钢枪刺耀霜风。 直饶射虎穿杨手，尽在输赢胜负中。
#+END_QUOTE


#+BEGIN_QUOTE
弓开如满月，箭去似流星。
#+END_QUOTE


#+BEGIN_QUOTE
武松在路上行了几日，来到阳谷县地面。此去离县治还远。当日晌午时分，走得肚中饥渴，望见前面有一个酒店，挑着一面招旗在门前，上头写着五个字道：“三碗不过冈。”武松入到里面坐下，把梢棒倚了，叫道：“主人家，快把酒来吃。” 只见店主人把三只碗、一双箸、一碟热菜，放在武松面前，满满筛一碗酒来。武松拿起碗，一饮而尽，叫道：“这酒好生有气力！主人家，有饱肚的买些吃酒。”酒家道：“只有熟牛肉。”武松道：“好的切二三斤来吃酒。”店家去里面切出二斤熟牛肉，做一大盘子将来，放在武松面前，随即再筛一碗酒。武松吃了道：“好酒!”又筛下一碗，恰好吃了三碗酒，再也不来筛。 武松敲着桌子叫道：“主人家，怎的不来筛酒?”酒家道：“客官要肉便添来。”武松道：“我也要酒，也再切些肉来。”酒家道：“肉便切来，添与客官吃，酒却不添了。”武松道：“却又作怪。”便问主人家道：“你如何不肯卖酒与我吃?”酒家道：“客官，你须见我门前招旗，上面明明写道‘三碗不过冈’。”
#+END_QUOTE


#+BEGIN_QUOTE
武松道：“怎地唤做‘三碗不过冈’?”酒家道：“俺家的酒，虽是村酒，却比老酒的滋味。但凡客人来我店中吃了三碗的，便醉了，过不得前面的山冈去。因此唤做‘三碗不过冈’。若是过往客人到此，只吃三碗，更不再问。”武松笑道：“原来恁地。我却吃了三碗，如何不醉?”酒家道：“我这酒叫做‘透瓶香’，又唤做‘出门倒’。初入口时，醇好吃，少刻时便倒。”武松道：“休要胡说。没地不还你钱？再筛三碗来我吃!” 酒家见武松全然不动，又筛三碗。武松吃道：“端的好酒！主人家，我吃一碗，还你一碗钱，只顾筛来。”酒家道：“客官休只管要饮，这酒端的要醉倒人，没药医。”武松道：“休得胡鸟说！便是你使蒙汗药在里面，我也有鼻子。”
#+END_QUOTE


#+BEGIN_QUOTE
店家被他发话不过，一连又筛了三碗。武松道：“肉便再把二斤来吃。”酒家又切了二斤熟牛肉，再筛了三碗酒。武松吃得口滑，只顾要吃，去身边取出些碎银子，叫道：“主人家，你且来看我银子，还你酒肉钱够么?”酒家看了道：“有余，还有些贴钱与你。”武松道：“不要你贴钱，只将酒来筛。”酒家道：“客官，你要吃酒时，还有五六碗酒哩，只怕你吃不的了。”武松道：“就有五六碗多时，你尽数筛将来。”酒家道：“你这条长汉，倘或醉倒了时，怎扶的你住?”武松答道：“要你扶的不算好汉。”酒家那里肯将酒来筛。武松焦躁道：“我又不白吃你的，休要引老爹性发，通教你屋里粉碎，把你这鸟店子倒翻转来!”酒家道：“这厮醉了，休惹他!”再筛了六碗酒与武松吃了。前后共吃了十八碗。绰了梢棒，立起身
#+END_QUOTE


#+BEGIN_QUOTE
道：“我却又不曾醉。”走出门前来，笑道：“却不说‘三碗不过冈’!”手提梢棒便走。 酒家赶出来叫道：“客官那里去?”武松立住了，问道：“叫我做甚么？我又不少你酒钱，唤我怎地?”酒家叫道：“我是好意。你且回来我家看官司榜文。”武松道：“甚么榜文?”酒家道：“如今前面景阳冈上，有只吊睛白额大虫，晚了出来伤人，坏了三二十条大汉性命。官司如今杖限打猎捕户，擒捉发落。冈子路口两边人民，都有榜文。可教往来客人，结伙成队，于巳、午、未三个时辰过冈。其余寅、卯、申、酉、戌、亥六个时辰，不许过冈。更兼单身客人，不许过冈，务要等伴结伙而过。这早晚正是未末申初时分，我见你走都不问人，枉送了自家性命。不如就我此间歇了，
#+END_QUOTE


#+BEGIN_QUOTE
店家被他发话不过，一连又筛了三碗。武松道：“肉便再把二斤来吃。”酒家又切了二斤熟牛肉，再筛了三碗酒。武松吃得口滑，只顾要吃，去身边取出些碎银子，叫道：“主人家，你且来看我银子，还你酒肉钱够么?”酒家看了道：“有余，还有些贴钱与你。”武松道：“不要你贴钱，只将酒来筛。”酒家道：“客官，你要吃酒时，还有五六碗酒哩，只怕你吃不的了。”武松道：“就有五六碗多时，你尽数筛将来。”酒家道：“你这条长汉，倘或醉倒了时，怎扶的你住?”武松答道：“要你扶的不算好汉。”酒家那里肯将酒来筛。武松焦躁道：“我又不白吃你的，休要引老爹性发，通教你屋里粉碎，把你这鸟店子倒翻转来!”酒家道：“这厮醉了，休惹他!”再筛了六碗酒与武松吃了。前后共吃了十八碗。绰了梢棒，立起身来道：“我却又不曾醉。”走出门前来，笑道：“却不说‘三碗不过冈’!”手提梢棒便走。 酒家赶出来叫道：“客官那里去?”武松立住了，问道：“叫我做甚么？我又不少你酒钱，唤我怎地?”酒家叫道：“我是好意。你且回来我家看官司榜文。”武松道：“甚么榜文?”酒家道：“如今前面景阳冈上，有只吊睛白额大虫，晚了出来伤人，坏了三二十条大汉性命。官司如今杖限打猎捕户，擒捉发落。冈子路口两边人民，都有榜文。可教往来客人，结伙成队，于巳、午、未三个时辰过冈。其余寅、卯、申、酉、戌、亥六个时辰，不许过冈。更兼单身客人，不许过冈，务要等伴结伙而过。这早晚正是未末申初时分，我见你走都不问人，枉送了自家性命。不如就我此间歇了，
#+END_QUOTE


#+BEGIN_QUOTE
等明日慢慢凑的三二十人，一齐好过冈子。” 武松听了，笑道：“我是清河县人氏，这条景阳冈上少也走过了一二十遭，几时见说有大虫？你休说这般鸟话来吓我！便有大虫，我也不怕。”酒家道：“我是好意救你！你不信我时，进来看官司榜文。”武松道：“你鸟子声！便真个有虎，老爷也不怕。你留我在家里歇，莫不半夜三更要谋我财，害我性命，却把鸟大虫唬吓我?”酒家道：“你看么！我是一片好心，反做恶意，倒落得你恁地说。你不信我时，请尊便自行。”
#+END_QUOTE


#+BEGIN_QUOTE
那酒店里主人摇着头，自进店里去了。 这武松提了梢棒，大着步自过景阳冈来。约行了四五里路，来到冈子下，见一大树，刮去了皮，一片白，上写两行字。武松也颇识几字，抬头看时，上面写道：“近因景阳冈大虫伤人，但有过往客商，可于巳、午、未三个时辰，结伙成队过冈。请勿自误。”武松看了，笑道：“这是酒家诡诈，惊吓那等客人，便去那厮家里宿歇。我却怕甚么鸟!”横拖着梢棒，便上冈子来。那时已有申牌时分，这轮红日，厌厌地相傍下山。武松乘着酒兴，只管走上冈子来。 走不到半里多路，见一个败落的山神庙。行到庙前，见这庙门上贴着一张印信榜文，武松住了脚读时，上面写道：
#+END_QUOTE


#+BEGIN_QUOTE
“阳谷县示：为这景阳冈上新有一只大虫，近来伤害人命，见今杖限各乡里正并猎户人等，打捕未获。如有过往客商人等，可于巳、午、未三个时辰，结伴过冈。其余时分及单身客人，不许过冈，恐被伤害性命不便。各宜知悉。” 武松读了印信榜文，方知端的有虎。欲待发步再回酒店里来，寻思道：“我回去时，须吃他耻笑，不是好汉，难以转去。”存想了一回，说道：“怕甚么鸟！且只顾上去，看怎地!” 武松正走，看看酒涌上来，便把毡笠儿背在脊梁上，将梢棒绾在肋下，一步步上那冈子来。回头看这日色时，渐渐地坠下去了。此时正是十月间天气，日短夜长，容易得晚。武松自言自说道：“那得甚么大虫！人自怕了，不敢上山。”
#+END_QUOTE


#+BEGIN_QUOTE
武松走了一直，酒力发作，焦热起来，一只手提着梢棒，一只手把胸膛前袒开，踉踉跄跄，直奔过乱树林来。见一块光挞挞大青石，把那梢棒倚在一边，放翻身体。却待要睡，只见发起一阵狂风来。看那风时，但见： 无形无影透人怀，四季能吹万物开。 就树撮将黄叶去，入山推出白云来。 原来但凡世上云生从龙，风生从虎。那一阵风过处，只听得乱树背后扑地一声响，跳出一只吊睛白额大虫来。武松见了，叫声：“呵呀!”从青石上翻将下来，便拿那条梢棒在手里，闪在青石边。 那个大虫又饥又渴，把两只爪在地下
#+END_QUOTE


#+BEGIN_QUOTE
武松走了一直，酒力发作，焦热起来，一只手提着梢棒，一只手把胸膛前袒开，踉踉跄跄，直奔过乱树林来。见一块光挞挞大青石，把那梢棒倚在一边，放翻身体。却待要睡，只见发起一阵狂风来。
#+END_QUOTE


#+BEGIN_QUOTE
那一阵风过处，只听得乱树背后扑地一声响，跳出一只吊睛白额大虫来。武松见了，叫声：“呵呀!”从青石上翻将下来，便拿那条梢棒在手里，闪在青石边。 那个大虫又饥又渴，把两只爪在地下略按一按，和身望上一扑，从半空里撺将下来。
#+END_QUOTE


#+BEGIN_QUOTE
武松被那一惊，酒都做冷汗出了。说时迟，那时快。武松见大虫扑来，只一闪，闪在大虫背后。那大虫背后看人最难，便把前爪搭在地下，把腰胯一掀，掀将起来。武松只一躲，躲在一边。大虫见掀他不着，吼一声，却似半天里起个霹雳，振得那山冈也动；把这铁棒也似虎尾倒竖起来，只一剪，武松却又闪在一边。 原来那大虫拿人，只是一扑，一掀，一剪，三般提不着时，气性先自没了一半。那大虫又剪不着，再吼了一声，一兜兜将回来。武松见那大虫复翻身回来，双手轮起梢棒，尽平生气力，只一棒，从半空劈将下来。只听得一声响，簌簌地将那树连枝带叶劈脸打将下来。定睛看时，一棒劈不着大虫。原来慌了，正打在枯树上，把那条梢棒折做两截，只
#+END_QUOTE


#+BEGIN_QUOTE
拿得一半在手里。 那大虫咆哮，性发起来，翻身又只一扑，扑将来。武松又只一跳，却退了十步远，那大虫却好把两只前爪搭在武松面前。武松将半截棒丢在一边，两只手就势把大虫顶花皮肐地揪住，一按按将下来。那只大虫急要挣扎，早没了气力，被武松尽气力纳定，那里肯放半点儿松宽。武松把只脚望大虫面门上、眼睛里只顾乱踢。 那大虫咆哮起来，把身底下扒起两堆黄泥，做了一个土坑。武松把那大虫嘴直按下黄泥坑里去，那大虫吃武松奈何得没了些气力。武松把左手紧紧地揪住顶花皮，偷出右手来，提起铁锤般大小拳头，尽平生之力，只顾打。打得五七十拳。那大虫眼里、口里、鼻子里、耳朵里都迸出鲜血来。那武松尽平昔神
#+END_QUOTE


#+BEGIN_QUOTE
一堆，却似躺着一个锦布袋。
#+END_QUOTE


#+BEGIN_QUOTE
威，仗胸中武艺，半歇儿把大虫打做一堆，却似躺着一个锦布袋。
#+END_QUOTE


#+BEGIN_QUOTE
当下景阳冈上那只猛虎，被武松没顿饭之间，一顿拳脚，打得那大虫动弹不得，使得口里兀自气喘。武松放了手，
#+END_QUOTE


#+BEGIN_QUOTE
松树边寻那打折的棒橛，拿在手里，只怕大虫不死，把棒橛又打了一回。那大虫气都没了。武松再寻思道：“我就地拖得这死大虫下冈子去。”就血泊里双手来提时，那里提得动！原来使尽了气力，手脚都疏软了，动弹不得。
#+END_QUOTE


#+BEGIN_QUOTE
松树边寻那打折的棒橛，拿在手里，只怕大虫不死，把棒橛又打了一回。那大虫气都没了。武松再寻思道：“我就地拖得这死大虫下冈子去。”就血泊里双手来提时，那里提得动！原来使尽了气力，手脚都疏软了，动弹不得。
#+END_QUOTE


#+BEGIN_QUOTE
来松树边寻那打折的棒橛，拿在手里，只怕大虫不死，把棒橛又打了一回。那大虫气都没了。武松再寻思道：“我就地拖得这死大虫下冈子去。”就血泊里双手来提时，那里提得动！原来使尽了气力，手脚都疏软了，动弹不得。
#+END_QUOTE


#+BEGIN_QUOTE
武松再来青石坐了半歇，寻思道：“天色看看黑了，倘或又跳出一只大虫来时，我却怎地斗得他过？且挣扎下冈子去，明早却来理会。”就石头边寻了毡笠儿，转过乱树林边，一步步捱下冈子来。
#+END_QUOTE


#+BEGIN_QUOTE
6.景阳冈
#+END_QUOTE


#+BEGIN_QUOTE
徘徊。 偶逢巡逻遭羁缚，遂使英雄困草莱。 卤莽
#+END_QUOTE


#+BEGIN_QUOTE
勇悍刘唐命运乖，灵官殿里夜徘徊。 偶逢巡逻遭羁缚，遂使英雄困草莱。 卤莽
#+END_QUOTE


#+BEGIN_QUOTE
勇悍刘唐命运乖，灵官殿里夜徘徊。 偶逢巡逻遭羁缚，遂使英雄困草莱。 卤莽雷横应堕计，仁慈晁盖独怜才。 生辰纲贡诸珍贝，总被斯人送将来。
#+END_QUOTE


#+BEGIN_QUOTE
六韬三略究来精。胸中藏战将，腹内隐雄兵。 谋略敢欺诸葛亮，陈平岂敌才能。略施小计鬼神惊。名称吴学究，人号智多星。
#+END_QUOTE


#+BEGIN_QUOTE
万卷经书曾读过，平生机巧心灵。六韬三略究来精。胸中藏战将，腹内隐雄兵。 谋略敢欺诸葛亮，陈平岂敌才能。略施小计鬼神惊。名称吴学究，人号智多星。
#+END_QUOTE


#+BEGIN_QUOTE
欲向生辰邀众宝，特扳三阮协神机。 一时豪侠欺黄屋，七宿光芒动紫微。 众守梁山同聚义，几多金帛尽
#+END_QUOTE


#+BEGIN_QUOTE
俘归。
#+END_QUOTE


#+BEGIN_QUOTE
英雄聚会本无期，水浒山涯任指挥。 欲向生辰邀众宝，特扳三阮协神机。 一时豪侠欺黄屋，七宿光芒动紫微。 众守梁山同聚义，几多金帛尽
#+END_QUOTE


#+BEGIN_QUOTE
罡星起义在山东，杀曜纵横水浒中。可是七星成聚会，却于四海显英雄。 人似虎，马如龙，黄泥冈上巧施功。满驮金贝归山寨，懊恨中书老相公。
#+END_QUOTE


#+BEGIN_QUOTE
“赤日炎炎似火烧，野田禾稻半枯焦。 农夫心内如汤煮，楼上王孙把扇摇。”
#+END_QUOTE


#+BEGIN_QUOTE
豪杰英雄聚义间，罡星煞曜降尘寰。 王伦奸诈遭诛戮，晁盖仁明主将班。 魂逐断云寒冉冉，恨随流水夜潺潺。 林冲火并真高谊，凛凛清风
#+END_QUOTE


#+BEGIN_QUOTE
豪杰英雄聚义间，罡星煞曜降尘寰。 王伦奸诈遭诛戮，晁盖仁明主将班。 魂逐断云寒冉冉，恨随流水夜潺潺。 林冲火并真高谊，凛凛清风不可攀！
#+END_QUOTE


#+BEGIN_QUOTE
古人交谊断黄金，心若同时谊亦深。 水浒请看忠义士，死生能守岁寒心。
#+END_QUOTE


#+BEGIN_QUOTE
水浒英锋不可当，黄安捕捉太诪张。 战船人马俱亏折，更把何颜见故乡？
#+END_QUOTE


#+BEGIN_QUOTE
呼延灼 天英星小
#+END_QUOTE


#+BEGIN_QUOTE
呼延灼
#+END_QUOTE


#+BEGIN_QUOTE
张青 地壮星母夜叉
#+END_QUOTE


#+BEGIN_QUOTE
张青
#+END_QUOTE
