#+TITLE:  [笔记]西游记
#+AUTHOR: Yang Yingchao
#+DATE:   2024-04-16
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:  align nodlcheck oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+LANGUAGE: en
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :tag1:tag2:note:ireader:



#+BEGIN_QUOTE
守护山洞，奈何没件兵器。久闻贤邻享乐瑶宫贝阙，必有
#+END_QUOTE



#+BEGIN_QUOTE
混沌未分天地乱，茫茫渺渺无人见。 自从盘古破鸿蒙，开辟从兹清浊辨。 覆载群生仰至仁，发明万物皆成善。 欲知造化会元功，须看《西游释厄传》。
#+END_QUOTE


#+BEGIN_QUOTE
子时得阳气，而丑则鸡鸣；寅不通光，而卯则日出；辰时食后，而巳则挨排；日午天中，而未则西蹉；申时晡而日落酉;戌黄昏而人定亥。
#+END_QUOTE


#+BEGIN_QUOTE
天地还没有分开的时候,一片混沌,茫茫渺渺,一个人也看不见。
#+END_QUOTE


#+BEGIN_QUOTE
天地还没有分开的时候,一片混沌,茫茫渺渺,一个人也看不见。自从盘古开天辟地以后,
#+END_QUOTE


#+BEGIN_QUOTE
天地还没有分开的时候,一片混沌,茫茫渺渺,一个人也看不见。自从盘古开天辟地以后,天地就形成了。
#+END_QUOTE


#+BEGIN_QUOTE
势镇汪洋，威宁瑶海。势
#+END_QUOTE


#+BEGIN_QUOTE
势镇汪洋，威宁瑶海。势
#+END_QUOTE


#+BEGIN_QUOTE
势镇汪洋，威宁瑶海。势
#+END_QUOTE


#+BEGIN_QUOTE
镇汪洋，潮涌银山鱼入穴；威宁瑶海，波翻雪浪蜃离渊。水火方隅高积土，东海之处耸崇巅。丹崖怪石，削壁奇峰。丹崖上，彩凤双鸣；削壁前，麒麟独卧。峰头时听锦鸡鸣，石窟每观龙出入。林中有寿鹿仙狐，树上有灵禽玄鹤。瑶草奇花不谢，青松翠柏长春。仙桃常结果，修竹每留云。一条涧壑藤萝密，四面原堤草色新。正是百川会处擎天柱，万劫无移大地根。
#+END_QUOTE


#+BEGIN_QUOTE
镇汪洋，潮涌银山鱼入穴；威宁瑶海，波翻雪浪蜃离渊。水火方隅高积土，东海之处耸崇巅。丹崖怪石，削壁奇峰。丹崖上，彩凤双鸣；削壁前，麒麟独卧。峰头时听锦鸡鸣，石窟每观龙出入。林中有寿鹿仙狐，树上有灵禽玄鹤。瑶草奇花不谢，青松翠柏长春。仙桃常结果，修竹每留云。一条涧壑藤萝密，四面原堤草色新。正是百川会处擎天柱，万劫无移大地根。
#+END_QUOTE


#+BEGIN_QUOTE
镇汪洋，潮涌银山鱼入穴；威宁瑶海，波翻雪浪蜃离渊。水火方隅高积土，东海之处耸崇巅。丹崖怪石，削壁奇峰。丹崖上，彩凤双鸣；削壁前，麒麟独卧。峰头时听锦鸡鸣，石窟每观龙出入。林中有寿鹿仙狐，树上有灵禽玄鹤。瑶草奇花不谢，青松翠柏长春。仙桃常结果，修竹每留云。一条涧壑藤萝密，四面原堤草色新。正是百川会处擎天柱，万劫无移大地根。
#+END_QUOTE


#+BEGIN_QUOTE
势镇汪洋，威宁瑶海。
#+END_QUOTE


#+BEGIN_QUOTE
势镇汪洋，威宁瑶海。势镇汪洋，潮涌银山鱼入穴；威宁瑶海，波翻雪浪蜃离渊。
#+END_QUOTE


#+BEGIN_QUOTE
势镇汪洋，威宁瑶海。势镇汪洋，潮涌银山鱼入穴；威宁瑶海，波翻雪浪蜃离渊。水火方隅高积土，东海之处耸崇巅。丹崖怪石，削壁奇峰。丹崖上，彩凤双鸣；削壁前，麒麟独卧。峰头时听锦鸡鸣，石窟每观龙出入。林中有寿鹿仙狐，树上有灵禽玄鹤。瑶草奇花不谢，青松翠柏长春。仙桃常结果，修竹每留云。一条涧壑藤萝密，四面原堤草色新。正是百川会处擎天柱，万劫无移大地根。
#+END_QUOTE


#+BEGIN_QUOTE
跳树攀枝，采花觅果；抛弹子，邷么儿；跑沙窝，砌宝塔；赶蜻蜓，扑蜡；参老天，拜菩萨；扯葛藤，编草帓；捉虱子，咬又掐；理毛衣，剔指甲；挨的挨，擦的擦；推的推，压的
#+END_QUOTE


#+BEGIN_QUOTE
弹子，邷么儿；跑沙窝，砌宝塔；赶蜻蜓，扑蜡；参老天，拜菩萨；扯葛藤，编草帓；捉虱子，咬又掐；理毛衣，剔指甲；挨的挨，擦的擦；推的推，压的压；扯
#+END_QUOTE


#+BEGIN_QUOTE
跳树攀枝，采花觅果；抛弹子，邷么儿；跑沙窝，砌宝塔；赶蜻蜓，扑蜡；参老天，拜菩萨；扯葛藤，编草帓；捉虱子，咬又掐；理毛衣，剔指甲；挨的挨，擦的擦；推的推，压的压；扯
#+END_QUOTE


#+BEGIN_QUOTE
跳树攀枝，采花觅果；抛弹子，邷么儿；跑沙窝，砌宝塔；赶蜻蜓，扑蜡；参老天，拜菩萨；扯葛藤，编草帓；捉虱子，咬又掐；理毛衣，剔指甲；挨的挨，擦的擦；推的推，压的压；扯的扯，拉的拉，青松林下任他顽，绿水涧边随洗濯。
#+END_QUOTE
