#+TITLE:  [笔记]曾国藩传
#+AUTHOR: Yang Yingchao
#+DATE:   2024-04-16
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:  align nodlcheck oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+LANGUAGE: en
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :tag1:zengguofan:note:ireader:



#+BEGIN_QUOTE
倔强二字，却不可少。功业文章，皆须有此二字贯注其中，否则柔靡不能成一事。
#+END_QUOTE


#+BEGIN_QUOTE
作为一个笨人，曾国藩发现下笨功夫有下笨功夫的好处。 第一，笨拙的人没有智力资本，因此比别人更虚心，更肯付出。第二，笨拙
的人从小接受挫折教育多，总是失败，因此“逆商”也就是逆境商数比较高，抗打击能力特别强。第三，笨拙的人不懂取巧，不走捷径，
遇到问题只知硬钻过去，因此做事不留死角
#+END_QUOTE


#+BEGIN_QUOTE
曾国藩的人生哲学是“尚拙”。既然天性钝拙，那么曾国藩就充分发挥钝拙的长处。他一生做事从来不绕弯子，不走捷径，总是按最笨拙、
最踏实的方式去做。涓滴积累，水滴石穿，追求的是扎实彻底，一步一个脚印。他做人讲究“拙诚”，人以伪来，我以诚往，不玩心眼。
他带兵讲究“结硬寨、打呆仗”(35)，从不凭奇谋诡计，只凭坚忍踏实，死磕到底。这种方式正如“重剑无锋”，表面上看起来迟钝，实际
上锋利。就好比郭靖的降龙十八掌，表面上简单笨拙，实际上却大气厚重，所向披靡。这是曾国藩一生成功的秘诀，也是他常向别人谈
及的道理。
#+END_QUOTE


#+BEGIN_QUOTE
凡人作一事，便须全副精神注在此一事，首尾不懈，不可见异思迁，做这样想那样，坐这山望那山。人而无恒，终身一无所成
#+END_QUOTE


#+BEGIN_QUOTE
以强悍的蛮劲打通此关。他以练习书法为喻，说明人在困难、倦怠、麻木面前应该如何做：“（写字写到）手愈拙，字愈丑，意兴愈低，所谓困也。困时切莫间断，熬过此关，便可少进。再进再困，再熬再奋，自有亨通精进之日。不特习字，凡事皆有极困难之时，打得通的，便是好汉。”
#+END_QUOTE


#+BEGIN_QUOTE
他用三十天戒了烟，然后用三十年，来戒掉其他更难戒的毛病。在一次又一次的反复磨炼中，曾国藩的气质性格渐渐发生着变化。他做
事越来越有恒心有毅力，待人接物越来越宽厚、周到、真诚，朋友一天比一天多。他的品质越来越纯粹，站得越来越高，看得越来越远。
#+END_QUOTE


#+BEGIN_QUOTE
曾国藩一生成功的第一个要诀，就是立志高远。这一志向，驱动他一生不在小诱惑、小目标面前止步。促使他在多大的困难面前都不苟且、不退缩
#+END_QUOTE


#+BEGIN_QUOTE
在日记当中，他给自己立下十二条做人的规矩和课程的标准：
#+END_QUOTE


#+BEGIN_QUOTE
习俗染人，所谓与鲍鱼处，亦与之俱化也。
#+END_QUOTE


#+BEGIN_QUOTE
天下事有所激有所逼而成者居多。
#+END_QUOTE


#+BEGIN_QUOTE
对于有志者来说，挫辱是最大的动力，打击是最好的帮助。咬紧牙关，把挫辱活生生吞下，就成了滋养自己意志和决心的营养。这构成
了曾国藩生命经验中最核心的部分。
#+END_QUOTE


#+BEGIN_QUOTE
天下事无所为而成者极少，有所贪有所利而成者居其半，有所激有所逼而成者居其半。

百端拂逆之时……亦只有逆来顺受之法。“所谓‘好汉打脱牙和血吞’……真处逆境之良法也
#+END_QUOTE


#+BEGIN_QUOTE
湘军的战斗力来自曾国藩的“反思”习惯。 我在这句话里所说的“反思”，用的字面意思，也就是反向思考。曾国藩在创建湘军的时候，并没有首先去想“湘军怎么才有战斗力”，而是先来分析“绿营兵为什么没有战斗力”。这是一个很重要的切入点。其实很多时候做事不需要你有什么超天才的想法。你只要好好总结一下别人都犯了哪些错误，然后你反着来，你可能就成功了
#+END_QUOTE

#+BEGIN_QUOTE
知止而后有定，定而后能静，静而后能安，安而后能虑，虑而后能得’
#+END_QUOTE


#+BEGIN_QUOTE
选士人领山农”
#+END_QUOTE


#+BEGIN_QUOTE
曾国藩并不比别人聪明，然而他做事却非常高明。曾国藩的高明，就是建立在笨拙之上，建立在绞尽脑汁、殚精竭虑之上。“笨”到极致
就是“聪明”，“拙”到极点就成了“巧”。
#+END_QUOTE


#+BEGIN_QUOTE
曾国藩一生经历千难万险，处理过无数大事，大体都很得当。其过人之处就是不怕费心费力，对事物进行不留死角的深入分析。在对事
物进行精到分析的基础上，再找出要害，把握关键。每次处理完了之后，还要总结经验教训，为下一次做参考
#+END_QUOTE


#+BEGIN_QUOTE
他这个人的做事特点一直是功虽大而不喜，过虽小而必究。他常说“悔生吉”，所谓“悔”，就是总结反省失败。在曾国藩看来，“失败”是
一个人一生的宝贵财富，每一次失败都要吃透，才能不白白付出这个代价。
#+END_QUOTE


#+BEGIN_QUOTE
所谓战略，就是基于宏观性和长远性，把各种纷繁复杂的要素按轻重缓急、先后次序进行整理排列，然后拿出最有效的行动方
#+END_QUOTE


#+BEGIN_QUOTE
自古平江南之策，必踞上游之势，建瓴而下，乃能成功。
#+END_QUOTE


#+BEGIN_QUOTE
太自傲、太急切、一味蛮干、一味刚强。
#+END_QUOTE


#+BEGIN_QUOTE
行事过于方刚者，表面上似乎是强者，实际上却是弱者。这片土地上真正的强者，是表面上看起来柔弱退让之人。所谓“天下之至柔，
驰骋天下之至坚”，“江海所以能为百谷王者，以其善下之”。所谓“大柔非柔，至刚无刚”
#+END_QUOTE


#+BEGIN_QUOTE
他认识到“不妄保举，不乱用钱”，则“人心不附”。只有诱之以“名”，笼之以“利”，才能网罗天下英才。
#+END_QUOTE


#+BEGIN_QUOTE
古今中外，具有雄才大略的用兵者，无不能够始终从战略的高度来把握问题，能够透过暂时的纷乱看到重点，在利害交织中看清本质，
牢牢把握好长远与眼前、全局与局部的关系。 曾国藩始终具有强烈的全局观念，他曾经夫子自道地说：“我对于大利大害所在，都能悉
心考究。”他还说，“用兵以审势为第一要义”(57)，“‘势’则指大计大局”(58)。还说应该从大的地方去分清界限，不要斤斤于小处去剖
析微芒。这个大利大害、大计大局，就是战略重心的所在。所以湘军虽然在局部的战斗中会吃败仗，但在战略态势上却总是处于有利位
置。而太平天国尽管在局部的战役上取得了一些胜利，但整个战略态势却越来越不利。这是湘军最终能够将太平天国镇压下去的重要原
因之一。 当然，制定了正确的战略决策，还要有排除各种干扰，将这种战略决策执行到底的决心和定力。王安定在《湘军记》中曾评
曾国藩成功在于“坚决不动摇，排众意而孤行己意，其成功亦卒以此，由学力胜也”。李瀚章曾经说，曾国藩的过人之处，在于他的定力
不是一般人所能比的。只要他认准的，他就会排除一切干扰，争取一切机会，去将胜利的可能变成胜利的现实。 他专门给咸丰上奏，
再次陈说自古平江南之贼，必须占据上游建瓴而下的道理。他说，向荣的江南大营不但不能打下南京，反而丢掉了苏州、常州，这并不
是兵力不够，而是因为从下游进攻上游，形势不利。 自咸丰三年金陵被陷，向荣、和春等皆督军由东面进攻，原欲屏蔽苏、浙，因时
制宜。而屡进屡挫，迄不能克金陵，而转失苏、常。非兵力之尚单，实形势之未得也。
#+END_QUOTE


#+BEGIN_QUOTE
古今中外，具有雄才大略的用兵者，无不能够始终从战略的高度来把握问题，能够透过暂时的纷乱看到重点，在利害交织中看清本质，
牢牢把握好长远与眼前、全局与局部的关系。
#+END_QUOTE


#+BEGIN_QUOTE
“用兵以审势为第一要义”(57)，“‘势’则指大计大局”(58)
#+END_QUOTE


#+BEGIN_QUOTE
“用兵以审势为第一要义”(57)，“‘势’则指大计大局”(58)。还说应该从大的地方去分清界限，不要斤斤于小处去剖析微芒。这个大利大害、大计大局，就是战略重心的所在。
#+END_QUOTE


#+BEGIN_QUOTE
战略上有一条基本的原则，就是致人而不致于人，也就是要迫使对方按照自己的战略安排行动，迫使对方跟着我们的步子走，而不是按照对方的战略安排行动。说白了，就是将战略的主动权掌握在自己的手中
#+END_QUOTE


#+BEGIN_QUOTE
太平天国》
#+END_QUOTE


#+BEGIN_QUOTE
李秀成自述
#+END_QUOTE


#+BEGIN_QUOTE
巴蜀书社，1998 年，第 1641 页。 (33)　沈守之：《借巢笔记》，第 25 页。转引自
#+END_QUOTE


#+BEGIN_QUOTE
古来大战争、大事业，人谋仅占十分之三，天意恒居十分之七。往往积劳之人非即成名之人，成名之人非即享福之人
#+END_QUOTE


#+BEGIN_QUOTE
在其耽于饮宴作乐的这十年中，它是否有什么业绩？什么也没有。它是否曾对人民给予了最起码的尊重或一般的同情，哪怕是淡漠的宽容？有谁敢做出肯定的回答吗？它究竟是一场抱着摆脱沉重枷锁之宗旨的民众运动，还是一种血腥的劫掠行为和蔓延全国的焚毁、破坏、杀戮一切具有生命的东西的盗贼行径？唉！答案实在是再明显不过了
#+END_QUOTE


#+BEGIN_QUOTE
中国所需要向西方学习的是西方的长处，并不是西方的缺点。洪秀全和太平天国所要学习而搬到中国来的是西方中世纪的神权政治，那正是西方的缺点。西方的近代化正是和这个缺点的斗争而生长出来的。中国所需要的是西方的现代化，并不是西方中世纪的神权政治。洪秀全和太平天国如果统一了中国，那就要使中国倒退几个世纪，这是我对洪秀全和太平天国的评价
#+END_QUOTE


#+BEGIN_QUOTE
然处大位大权而兼享大名，自古曾有几人能善其末路者？总须设法将权位二字推让少许，减去几成，则晚节渐渐可以收场耳。
#+END_QUOTE


#+BEGIN_QUOTE
善聚不如善散，善始不如善终
#+END_QUOTE


#+BEGIN_QUOTE
要求自己“以廉率属，以俭治家，誓不以军
#+END_QUOTE


#+BEGIN_QUOTE
综观曾国藩一生，他的为官风格十分独特。一方面，曾国藩确实是一个清官。他的“清”货真价实，问心无愧。在现存资料中，我们找不到曾国藩把任何一分公款装入自己腰包的记录。但另一方面，曾国藩的逸事中缺少“囊橐萧然”“贫不能殓”、在官府里种菜吃这样容易让人觉得悲情的极端化情节。在中国人眼里，真正的清官，必须清可见底，一尘不染，清到成为海瑞式的“自虐狂”或者“受虐狂”，才叫人佩服。曾国藩远没有清到这个程度。如果给清官分类的话，曾国藩应该归入“非典型类清官”。也就是说，骨子里清廉刻苦，表面上和光同尘。这是因为曾国藩的志向不是做“清官”，而是做大事。
#+END_QUOTE


#+BEGIN_QUOTE
曾国藩在天津教案中全力避免战争，然而在他死后这种战争却成为现实。1900 年 6 月 21 日，清政府向英、美、法、德、意、日、俄、
西、比、荷、奥十一国同时宣战。241 名外国人（天主教传教士 53 人，新教传教士及其子女共 188 人，其中儿童 53 人）、2万多名
中国基督徒在 1900 年夏天的战争中死亡。这是天津教案的扩大版。
#+END_QUOTE


#+BEGIN_QUOTE
“学于古，则多看书籍；学于今，则多觅榜样。
#+END_QUOTE


#+BEGIN_QUOTE
不说大话，不好虚名，不行驾空之事，不谈过高之理
#+END_QUOTE
