#+TITLE:  [笔记]曾国藩智慧精髓大合集
#+AUTHOR: Yang Yingchao
#+DATE:   2024-04-16
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:  align nodlcheck oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+LANGUAGE: en
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :tag1:zengguofan:note:ireader:



#+BEGIN_QUOTE
欲成大事，“明强”为本。
#+END_QUOTE


#+BEGIN_QUOTE
和顺而不随波逐流，保持中立而不偏不倚，政治清明时不改变志向，政治黑暗时坚持操守，宁死不变，这才是真正的强。
#+END_QUOTE


#+BEGIN_QUOTE
至于当大事，全在明强二字
#+END_QUOTE

#+BEGIN_QUOTE
凡郁怒最易伤人。
#+END_QUOTE

#+BEGIN_QUOTE
事实如此，生活中总会存在这样的一些人：他们为了自己的利益而不择手段地去挑拨离间，而且斤斤计较得理不饶人，甚至会为了一点利益
跟别人大打出手。所以，这种人是难以成就大事的。而如果这些人都能看破这些人情世故，那么就会如曾国藩所说：“知道世上道路的艰难，
那么内心就会更加抑制畏惧，心气反而会更加平和了。”
#+END_QUOTE


#+BEGIN_QUOTE
满招损，谦受益
#+END_QUOTE


#+BEGIN_QUOTE
思自进于谨言慎行之路，
#+END_QUOTE


#+BEGIN_QUOTE
但不可傲，满招损，谦受益，
#+END_QUOTE


#+BEGIN_QUOTE
大约军事之败，非傲即惰，二者必居其一。巨室之败，非傲即惰，二者必居其一。
#+END_QUOTE


#+BEGIN_QUOTE
在曾国藩看来，无论军事失败还是达官贵人家的落魄，都是因为骄傲和懒惰其中一点所造成的，所以他认为去掉傲字为第一重要。
#+END_QUOTE


#+BEGIN_QUOTE
曾国藩是把众人的智慧为己所用的典型人物。他胸怀广大，心平气和，从不居功自傲，看上去就像一位老儒。凡是有人向他进言，对的就采纳，不对的他也不予以辩驳。
#+END_QUOTE


#+BEGIN_QUOTE
骄傲自满是人生的大敌，盛气凌人是人际交往中的败笔。《
#+END_QUOTE


#+BEGIN_QUOTE
谦逊就是对自己的短处和不足有高度的自觉，永远以自己的短处和他人的长处相比较，虚心向他人学习，以不断充实和完善自己。
自满自足的人总是只见自己的长处和他人的短处，总觉得自己什么都好，而别人一无是处，于是自高自大，瞧不起任何人。
#+END_QUOTE


#+BEGIN_QUOTE
谦逊的人能发现他人的优点，虚心向他人学习，集众人之长，补己之短。
谦逊作为一种美德，既能在人际交往中体现出对他人的尊重，又表现了对自己的严格要求和积极的进取精神。
#+END_QUOTE


#+BEGIN_QUOTE
李申夫尝谓余怄气从不说出，一味忍耐，徐图自强，因引谚曰：“好汉打脱牙，和血吞”。此二语是余生平咬牙立志之诀，不料被申夫看破。
#+END_QUOTE


#+BEGIN_QUOTE
唯有一字不说，咬定牙根，徐图自强而已。
#+END_QUOTE


#+BEGIN_QUOTE
君子稳重而有威严，有坚强的忍耐性格，在困难面前不退缩，即使刀架在脖子上也不畏惧。这样才能够所向无敌。
#+END_QUOTE


#+BEGIN_QUOTE
有利的情况和主动的恢复，产生于再坚持一下的努力之中。事情的成功与否，就在于你的意志是否坚定。
#+END_QUOTE


#+BEGIN_QUOTE
当苦到极点和难到极点的时候，最需要的不是力气，更不是放弃，而是坚忍和打脱牙和血吞的精神。
#+END_QUOTE


#+BEGIN_QUOTE
凡畏人，不敢妄议论者，谦谨者也；凡好讥评人短者，骄傲者也。
#+END_QUOTE


#+BEGIN_QUOTE
若想做一个好人，做一个完人，要始终怀着敬畏的心对待别人，如果能作到不轻易对任何人进行评论，那么就能够使鬼服神钦，见识日进，
正气日刚。否则，不知不觉坠入卑污一流，必定有被别人看不起的那一天，所以不可不慎重。
#+END_QUOTE


#+BEGIN_QUOTE
凡是属于敬畏别人而不敢妄加议论别人的人都是谦和恭谨的人。凡是属于喜欢讽刺和批评别人短处的人都是骄傲的人。其意是告诫我们在修身做人上，一定要谨慎行事。
#+END_QUOTE


#+BEGIN_QUOTE
他对同僚也非常友善，主张“说人长每长一分，说人短每短一分”。
#+END_QUOTE


#+BEGIN_QUOTE
曾国藩说，要成为一个不骄傲的人，就要以不轻易议论和讥笑别人为第一要点。这是为官、做人所必须具备的品德，也是当领导的处理好同
事之间、上下级之间关系的准则。譬如说：同事之间、上下级之间，在日常工作、生活中难免会产生一些矛盾，这时就应该坦诚相见，加强
相互之间的沟通与理解，消除隔阂，化解矛盾，增进友谊。
#+END_QUOTE



#+BEGIN_QUOTE
我们一定要谨记曾国藩的告诫，不轻易议论和讥笑别人，让自己凝聚更多的人脉，被更多的人所欣赏，开创出一片新的天地。
#+END_QUOTE


#+BEGIN_QUOTE
顺境比逆境更能考验一个人。一个人战胜了逆境，那么他是一个强者，如果一个人战胜了顺境，那么他就是一个理智的强者。
#+END_QUOTE


#+BEGIN_QUOTE
“裕无咎”里的这个“裕”字有两层意思：其一，是暂缓，待时，有退一步之意，就是懂得忍耐；其二，就是宽阔、宽广，即心胸宽广。能以宽
广的胸怀对待晋升中的挫折，所谓大肚能容，能容领导的不信任，能容竞争对手的打击，能容晋升受挫的事实。
#+END_QUOTE


#+BEGIN_QUOTE
大器晚成的人很多。从这些大器晚成的伟大人物的发展历程里，我们还可以看到他们都是不断刻苦钻研，朝着自己感兴趣的山峰不断攀登。
不在乎起步迟早，无论年龄大小，只要为成功付出了相当的努力，就有希望成功。
#+END_QUOTE


#+BEGIN_QUOTE
只要将成功寄希望于长期努力上，不急于求成，一旦悟透“大器晚成”的道理，不求速度、不求数量，始终坚持把眼前的事情做得更完美，那
么就会比别人更快地获得人生的成功。
#+END_QUOTE


#+BEGIN_QUOTE
在他看来为国家做事，就该认真不能松懈，一律按规矩办理。 做事尽心尽责，一丝不苟，能够培养人坚毅的品格，它能带领人走向好的方面，
又能鼓励优秀的人成就一番大的事业。
#+END_QUOTE


#+BEGIN_QUOTE
乱世功名之际尤为难处”
#+END_QUOTE


#+BEGIN_QUOTE
至于担当大事，全在明强二
#+END_QUOTE


#+BEGIN_QUOTE
至于担当大事，全在明强二字。《
#+END_QUOTE


#+BEGIN_QUOTE
中庸》中所说的博学、审问、慎思、明辨、笃行，其要点就是要使愚蠢变为贤明，柔弱变得坚强。
#+END_QUOTE


#+BEGIN_QUOTE
要知道凡事没有倔犟的志气是做不成的，没有刚毅的性格也不能成大事，即使是修身齐家，也必须以“明强”二字作为修身的根本。
#+END_QUOTE


#+BEGIN_QUOTE
博学、审问、慎思、明辨、笃行，
#+END_QUOTE


#+BEGIN_QUOTE
要使愚蠢的变得贤明，柔弱的变得坚强。其思必明，柔必强”。
#+END_QUOTE


#+BEGIN_QUOTE
盖无故而怨天，则天必不许；无故而尤人，则人必不服。
#+END_QUOTE


#+BEGIN_QUOTE
凡遇牢骚欲发之时，则反躬自思：吾果有何不足而蓄此不平之气？猛然内省，决然去之。
#+END_QUOTE


#+BEGIN_QUOTE
毫无缘故地怨天，天一定不会允许；无缘无故地埋怨别人，人也不会服气。天人感应之理，只能顺其自然，不要过于强求。
#+END_QUOTE



#+BEGIN_QUOTE
强调了力除牢骚的重要，并且告诫他的四个弟弟不要一味发牢骚，凡要发牢骚的时候，必须躬身自问：有什么事情使你不满足？为何你心中
怀不平之气？积极反省自己的内心，心怀一团和气，养本固元，这样就没有什么事情是不能接受的。接受后，再想法去改变；能改变的改变
它，不能改变的接受它，没有什么值得埋怨的
#+END_QUOTE


#+BEGIN_QUOTE
圣人也和我们一样有时会发出感慨，但是，圣人与我们不同的是，他不会陷入苦恼之中，不会因为大道不能推行于天下而怨天尤人，更不会
牢骚满腹不付诸行动。
#+END_QUOTE


#+BEGIN_QUOTE
人处在心烦意乱的时候，很难作出正确的判断和抉择，会使事情难以成功；如果长期让自己的心情处于这种状态，也会容易生出病来。所以，
息怒、忍耐很重要，只有静心凝神才能万事可达。
#+END_QUOTE


#+BEGIN_QUOTE
长寿应止雷霆怒，求健须息霹雳火。”这样便能使身心永远健康。
#+END_QUOTE


#+BEGIN_QUOTE
必须能忍受别人不能忍受的触犯和忤逆，才能成就别人难及的事业功名。”
#+END_QUOTE


#+BEGIN_QUOTE
无人不由自立自强做出，
#+END_QUOTE


#+BEGIN_QUOTE
近来见得天地之道，刚柔互用，不可偏废，太柔则靡，太刚则折。
#+END_QUOTE


#+BEGIN_QUOTE
近来见得天地之道，刚柔互用，不可偏废，太柔则靡，太刚则折。刚非暴虐之谓也，强矫而已；柔非卑弱之谓也，谦退而已。趋事赴公，
则当强矫，争名逐利，则当谦退；开创家业，则当强矫，守成安乐，则当谦退；出与人物应接，则当强矫，入与妻孥享受，则当谦退。
#+END_QUOTE

#+BEGIN_QUOTE
他总结出柔非怯懦，而是一种以退为进的权变，一种骄敌之志而暗蓄力量的极高计谋。自己示弱，可以使敌人不注意而得保全。太“刚”
者，锋芒太盛，容易招惹是非，暴露自己之不足，为“柔”者所败，大柔非柔，至刚无刚！
#+END_QUOTE


#+BEGIN_QUOTE
凡事想要达到自己的目的，应该既柔又刚，不可推崇其中一面，否则就会让事情夭折或失去控制。真正的成事之道就在于思维方式的转
变，用柔的方法，成刚强之事，才是真谛。
#+END_QUOTE


#+BEGIN_QUOTE
古来大战争、大事业，人谋仅占十分之三，天意恒居十分之七。往往积劳之人，非即成名之人，成名之人，非即享福之人。
#+END_QUOTE


#+BEGIN_QUOTE
韩非子《说林•下篇》中说：工艺木雕的要领，首先在于鼻子要大，眼睛要小，鼻子雕刻大了，还可以改小，如果一开始便把鼻子给刻
小了，就没有办法补救了。为人做事也是一个道理，凡事要留有余地，留有后路。只有这样，才不至于遭遇失败。
#+END_QUOTE


#+BEGIN_QUOTE
在官场中有一些“规矩”，这些规矩要内心知晓，而背后遵循。这些规矩，一是忌直言说人长短；二是懂得取悦别人，也就是说与人保持和气
最重要；三是小心小人捣乱。
#+END_QUOTE


#+BEGIN_QUOTE
故吾辈在自修处求强则可，在胜人处求强则不可。福益外家若专在胜人处求强，其能强到底与
#+END_QUOTE


#+BEGIN_QUOTE
故吾辈在自修处求强则可，在胜人处求强则不可。
#+END_QUOTE


#+BEGIN_QUOTE
得志，泽加于民，不得志，修身见于世。穷则独善其身，达则兼济天下。”
#+END_QUOTE


#+BEGIN_QUOTE
大致上是以能立能达为体，以不怨不尤为用。
#+END_QUOTE


#+BEGIN_QUOTE
默存一悔字，无事不可挽回也。
#+END_QUOTE


#+BEGIN_QUOTE
心里暗自存一个“悔”字，没有什么事是不可以挽回的。
#+END_QUOTE


#+BEGIN_QUOTE
为人的气魄应该能立能达，对命运与他人的态度要不怨不尤。这是人处于不同时期对待人生、调整心态的根本大法。
#+END_QUOTE


#+BEGIN_QUOTE
立者，发愤图强，能站得住，不容易倒下。
#+END_QUOTE


#+BEGIN_QUOTE
关于达，是说办事圆融，行得通。办事要想行得通，就该懂规律，懂得怎样做得圆融。
#+END_QUOTE


#+BEGIN_QUOTE
如果说“以能立能达为体”是对自己的要求，那么“以不怨不尤为用”就是对天命和别人的态度。
#+END_QUOTE


#+BEGIN_QUOTE
人生在世，“立”要靠自己，而“达”并非一人就能如愿，这就需要学会变通方可成事。当然，现代社会并不提倡人们做两面三刀的人，而是要
掌握处事圆通的技巧。这样办事情才能顺利，人际关系才能和谐，你才能在世上立足
#+END_QUOTE


#+BEGIN_QUOTE
一定要能立能达，凡事不要怨天尤人，而要从内心深处去反省自己的行为，这样就能够找到解决问题的方法，从而取得事情的成功。
#+END_QUOTE


#+BEGIN_QUOTE
悔字如春，万物蕴蓄初发；吉字如夏，万物茂盛已极；吝字如秋，万物始落；凶字如冬，万物枯凋。”
#+END_QUOTE


#+BEGIN_QUOTE
朱子尝言：悔字如春，万物蕴蓄初发；吉字如夏，万物茂盛已极；吝字如秋，万物始落；凶字如冬，万物枯凋。”
#+END_QUOTE


#+BEGIN_QUOTE
“硬”者，对他人态度而言，是指倔犟之气。人立于世，必须有一股“浩气”支撑着，对待不同的人应该有不同的态度，对自己正确的行为应该
始终坚守，而不能随波逐流。
#+END_QUOTE


#+BEGIN_QUOTE
“悔”字启春生之机，这的确是渡过难关与危难的妙计，其奉行的是阴阳消长，刚柔相推的人生哲学。
#+END_QUOTE


#+BEGIN_QUOTE
“悔”者，是从自身角度来说，即对自己言语和行为的检点和反省。人只有知其短，才能补其过；只有知其陋，才能补其缺。自省是促使自己
继续进步的动力，不断提高聪明层次的“智慧树”。
#+END_QUOTE


#+BEGIN_QUOTE
凡仕宦之家，由俭入奢易，由奢返俭难。尔年尚幼，切不可贪爱奢华，不可惯习懒惰。无论大家小家、士农工商，勤苦俭约，未有不兴；骄奢倦怠，未有不败。
#+END_QUOTE


#+BEGIN_QUOTE
一个人一生不要因为一点成绩，就窃喜起来，要知道还有更大的目标等着你去追求。同时，也不要因为一点挫折，就怨天尤人，要知道，有
多少人都是从逆境中闯出来的，从而取得了成功。
#+END_QUOTE


#+BEGIN_QUOTE
且苟能发奋自立，则家塾可读书，即旷野之地、热闹之场亦可读书，负薪牧豕，皆可读书。苟不能发奋自立，则家塾不宜读书，即清净之乡、
神仙之境皆不能读书。何必择地？何必择时？但自问立志之真不真耳！
#+END_QUOTE


#+BEGIN_QUOTE
《大学》之纲领有三：明德、新民、止至善，皆我分内事也。若读书不能体贴到身上去，谓此三项与我身了不相涉，则读书何用？虽使能文能诗，博雅自诩，亦只算得识字之牧猪奴耳！
#+END_QUOTE


#+BEGIN_QUOTE
则《大学》之纲领，皆己身切要之事明矣。其条目有八，自我观之，其致功之处，则仅二者而已：曰格物，曰诚意。 格物，致知之事也；诚意，力行之事也。
#+END_QUOTE


#+BEGIN_QUOTE
释氏所谓降龙伏虎。龙即相火也，虎即肝气也。多少英雄豪杰，打此两关不过，亦不仅余与弟为然。要在稍稍遏抑，不令过炽。降龙以养水，
伏虎以养火。古圣所谓窒欲，即降龙也；所谓惩忿，即伏虎也。儒释之道不同，而其节制血气，未尝不同，总不使吾之嗜欲戕害吾之躯命而
已。
#+END_QUOTE


#+BEGIN_QUOTE
倔犟二字，却不可少。功业文章，皆须有此二字贯注其中，否则柔糜不能成一事。孟子所谓至刚，孔子所谓贞固，皆从倔犟二字做出。
#+END_QUOTE


#+BEGIN_QUOTE
受挫之时，正是长进之机，如果你能懂得如何去解决问题，便能关闭苦难之门了；而不能运用理智果断解决问题的人，只能永远活在痛苦之中。
#+END_QUOTE


#+BEGIN_QUOTE
古来言凶德致败者约有二端：曰长傲，曰多言。
#+END_QUOTE


#+BEGIN_QUOTE
长傲，多言两个弊端，是历来士卿大夫衰败以及官场上导致灾祸的原因，
#+END_QUOTE


#+BEGIN_QUOTE
虽极忙，亦须了本日功课，不以昨日耽搁而今日补做，不以明日有事而今日预做。
#+END_QUOTE


#+BEGIN_QUOTE
学问之道无穷，而总以有恒为主。
#+END_QUOTE


#+BEGIN_QUOTE
谈“志”“识”“恒”三者的关系。因为有志向，所以与俗不同；因为有学识，所以眼界应当开阔；因为有恒心，所以才能把事情做成。这三者缺一不可。
#+END_QUOTE


#+BEGIN_QUOTE
盖场屋之中，只有文丑而侥幸者，断无文佳而埋没者，此一定之理也。
#+END_QUOTE


#+BEGIN_QUOTE
故吾人用功，力除傲气，力戒自满，毋为人所冷笑，乃有进步也。
#+END_QUOTE


#+BEGIN_QUOTE
告诫人不能过于自满，不能去妄加评价别人和嘲笑别人，因为在他看来，只有做到超过孔子这样古人的学问，才能评判是非曲直。
#+END_QUOTE


#+BEGIN_QUOTE
尔读书记性平常，此不足虑。所虑者，第一怕无恒，第二怕随笔点过一遍，并未看得明白。此却是大病。
#+END_QUOTE


#+BEGIN_QUOTE
尔读书记性平常，此不足虑。所虑者，第一怕无恒，第二怕随笔点过一遍，并未看得明白。此却是大病。若实看明白了，久之必得些滋味，寸心若有怡悦之境，则自略记得矣。尔不必求记，却宜求个明白
#+END_QUOTE


#+BEGIN_QUOTE
读书是要讲究方法的。有兴趣，还要有激情，在读的过程中要充满兴趣和激情，但这还不够，更重要的是要细读，尽量弄懂其中的含义和道理。
#+END_QUOTE


#+BEGIN_QUOTE
至于读书的方法，唐鉴认为书不在于读得多，而在于读得精，尤其是在开始的时候，要专攻一经。一经精通之后，再旁及其他经典。
#+END_QUOTE


#+BEGIN_QUOTE
怕就怕博而不精，知之而不甚懂，似是而非，对知识的概念模糊，缺乏钻研的精神，这对做学问不利，也对自己的成长不利，因为人的精力是有限的，在一个时期内，在一个大的环境内，我们只能着重选择很少的事情去做，而且要能不厌其烦地去做，这样才能把一件事情做好，反之则做不好。
#+END_QUOTE


#+BEGIN_QUOTE
人之气质，由于天生，本难改变，唯读书则可变化气质。古之精相法者，并言读书可以变换骨相。欲求变之之法，总须先立坚卓之志。
#+END_QUOTE


#+BEGIN_QUOTE
涵泳二字，最不易识，余尝以意测之。曰：涵者，如春雨之润花，如清渠之溉稻。雨之润花，过小则难透，过大则离披，适中则涵濡而滋液；清渠之溉稻，过小则枯槁，过多则伤涝，适中则涵养而浡兴。（
#+END_QUOTE


#+BEGIN_QUOTE
善读书者，须视书如水，而视此心如花如稻如鱼如濯足，则涵泳二字，庶可得之于意言之表。
#+END_QUOTE


#+BEGIN_QUOTE
虚心涵泳，切己体察。
#+END_QUOTE


#+BEGIN_QUOTE
曾国藩视书如水，人心如花、如稻、如鱼，而虚心涵泳的道理，既是读书的意境，也是读书的趣味，其实这也是读书读到深远处，物我两忘的一种境界。
#+END_QUOTE


#+BEGIN_QUOTE
王国维在《人间词话》中说：“古今之成大事业、大学问者，必经过三种境界：‘昨夜西风凋碧树。独上高楼，望断天涯路’。此第一境也。‘衣带渐宽终不悔，为伊消得人憔悴。’此第二境也。‘众里寻他千百度，蓦然回首，那人却在灯火阑珊处’，此第三境也。” 读书是一个循序渐进的过程，只有经过前两种境界的熏陶，才能有朝一日，达到第三种境界。
#+END_QUOTE


#+BEGIN_QUOTE
唐代文学家韩愈曾说：“人之能为文，由腹有诗书。”春蚕饱食桑叶，才能吐出雪白的丝；蜜蜂广采花粉，才能酿出香甜的蜜。清人唐彪在《读书作文谱•卷五》中也说：“文章读之极熟，则与我为化，不知是人之文，我之文也。作文时，吾意所欲言，无不随吾所欲，应笔而出，如泉之涌，滔滔不绝。”熟读成诵，消化吸收，作文时则意到笔随，文如泉涌，笔底生花，称心如意。巴金也说：“读多了，读熟了，常常可以顺口背出来，也就慢慢体会到它们的好处，也就慢慢摸到文章的调子”（《
#+END_QUOTE


#+BEGIN_QUOTE
熟读成诵是积淀语感的必经之路。
#+END_QUOTE


#+BEGIN_QUOTE
一面细读，一面抄记，一面作文，以仿效之。凡奇僻之字，雅故之训，不手抄则不能记，不模仿则不惯用。
#+END_QUOTE


#+BEGIN_QUOTE
买书不可不多，而看书不可不知所择。
#+END_QUOTE


#+BEGIN_QUOTE
最重要的是看书必须懂得善加选择，这样治学才有专攻，对于学问的深刻内涵，才能真正领会的观点。
#+END_QUOTE


#+BEGIN_QUOTE
许多家训都提到读书要“由博返约”。这就告诉我们，要选择一些对工作、对事业、对未来有指导和帮助作用的书来读。
#+END_QUOTE


#+BEGIN_QUOTE
凡事不宜刻，若读书则不可不刻；凡事不宜贪，若买书则不可不贪。”
#+END_QUOTE


#+BEGIN_QUOTE
人谁不死，只求临终心无愧悔
#+END_QUOTE


#+BEGIN_QUOTE
作诗文是尔之所短，即宜从短处痛下工夫。看书写字尔之所长，即宜拓而充之。走路宜重，说话宜迟，常常记忆否？
#+END_QUOTE


#+BEGIN_QUOTE
人不怕在一方面有短处，就怕不肯在这方面下工夫。所以说，曾国藩劝诫自己的儿子读书要想读好，不应该只看到自己擅长的那方面，更应该从自己的短处方面下工夫，这样将短变为长，与长处一起用功努力，才能有所成就。
#+END_QUOTE


#+BEGIN_QUOTE
字求其训，句索其旨，未得乎前，则不敢求其后，未通乎此则不敢志乎彼，如是循序渐进，则意定理明，而无疏易凌躐之患矣。”
#+END_QUOTE


#+BEGIN_QUOTE
字求其训，句索其旨，未得乎前，则不敢求其后，未通乎此则不敢志乎彼，如是循序渐进，则意定理明，而无疏易凌躐之患矣。”也就是说要一个字一个字地弄
#+END_QUOTE


#+BEGIN_QUOTE
字求其训，句索其旨，未得乎前，则不敢求其后，未通乎此则不敢志乎彼，如是循序渐进，则意定理明，而无疏易凌躐之患矣。”
#+END_QUOTE


#+BEGIN_QUOTE
若事事勤思善问，何患不一日千里？
#+END_QUOTE


#+BEGIN_QUOTE
曾以为学四事勉儿辈：一曰看生书宜求速，不多读则太陋。一曰温旧书宜求熟，不背诵则易忘。一曰习字宜有恒，不善写则如身之无衣，山之无木。一曰作文宜苦思，不善作则如人之哑不能言，马之跛不能行。四者缺一不可，盖尽阅历一生，深知深悔之者，
#+END_QUOTE


#+BEGIN_QUOTE
对于读书的具体方法，曾国藩提倡“猛火煮”与“鸡孵卵”相结合。他时时谨记《朱子语类》“鸡孵卵”及“猛火煮”二条。看生书宜求速，即“猛火煮”的意思。他是这么解释的：“每日至少亦须看二十页，不必惑于在精不在多之说。今日半页，明日数页，又明日耽搁间断，或数年而不能毕一部，如煮饭然，歇火则冷，小火则不熟，须用大柴大火乃易成也。”因此，“凡读书有难解者，有一字不能记者，不必苦求强记，今日看几篇，明日看几篇，久久自然有益”。
#+END_QUOTE


#+BEGIN_QUOTE
曾国藩主张求学者应该大量阅读，应该高速阅读，在大量和高速阅读中，可以暂时不求甚解，这就是所谓的“猛火煮”。但如果长期不求甚解，便不能豁然贯通，甚而导致对知识的滥用、误用。因而，还必须有个对知识消化、融会的过程。“温旧书宜求熟”，正如鸡孵卵，必须慢慢催化，正如十月怀胎，一朝分娩。只有这样，才能深入地读懂书籍，才能举一反三，悟出新的“境界”来，逐渐进入创作的天地，获得真知。
#+END_QUOTE


#+BEGIN_QUOTE
文中雄奇之道。雄奇以行气为上，造句次之，选字又次之。
#+END_QUOTE


#+BEGIN_QUOTE
文中雄奇之道。雄奇以行气为上，造句次之，选字又次之。然未有字不古雅而句能古雅，句不古雅而气能古雅者；亦未有字不雄奇而句能雄奇，句不雄奇而气能雄奇者。是文章之雄奇，其精处在行气，其粗处全在造句选字也
#+END_QUOTE


#+BEGIN_QUOTE
好的文章必须以“雄奇”为主，而雄奇以行气为第一，造句为第二，选字为第三。掌握了这三点，便能让你的文章卓然而立。
#+END_QUOTE


#+BEGIN_QUOTE
处乱世而得宽闲之岁月，千难万难，尔切莫错过此等好光阴也。
#+END_QUOTE


#+BEGIN_QUOTE
为蚕养桑，非为桑也。以桑饭蚕，非为蚕也。逮蚕吐茧而丝成，不特无桑，蚕亦亡矣。取其精，弃其粗；取其神，弃其形。所谓罗万卷于胸中而不留一字者乎。
#+END_QUOTE


#+BEGIN_QUOTE
可见年无分老少，事无分难易，但行之有恒，自如种树畜养，日见其大而不觉耳。
#+END_QUOTE


#+BEGIN_QUOTE
看书不一定记得住，也不能一下子看得很多，同样在计划的执行过程中，也很有可能遇到挫折，有时候会进展缓慢，甚至停顿，那么在这个时候该怎么办呢？曾国藩说得好，“每日有常，自有进境”，要认定目标前进，咬紧牙关命令自己不许后退，每日都是这样有恒心地去坚持，自然会有进步，目标也会在一天天的坚持中实现。
#+END_QUOTE


#+BEGIN_QUOTE
夫家和则福自生。若一家之中，兄有言，弟无不从，弟有请，兄无不应，和气蒸蒸而家不兴者，未之有也；反是而不败者，亦未之有也。伏望大人察男之志，即此敬禀叔父大人，恕
#+END_QUOTE


#+BEGIN_QUOTE
夫家和则福自生。若一家之中，兄有言，弟无不从，弟有请，兄无不应，和气蒸蒸而家不兴者，未之有也；反是而不败者，亦未之有也。
#+END_QUOTE


#+BEGIN_QUOTE
一则我家气运太盛，不可不格外小心，以为持盈保泰之道。旧债尽清，则好处太全，恐盈极生亏；留债不清，则好中不足，亦处乐之法也。
#+END_QUOTE


#+BEGIN_QUOTE
怎样保持家道的兴盛呢？从上述家书中看，曾国藩认为最重要的一条，就是不给子孙留下大笔金银遗产。
#+END_QUOTE


#+BEGIN_QUOTE
银钱、田产，最易长骄气逸气，我家中断不可积钱，断不可买田。尔兄弟努力读书，决不怕没饭吃。
#+END_QUOTE


#+BEGIN_QUOTE
他将钱财看做是身外之物，如果积攒过多的金钱，那么儿孙就会因此而不再发奋读书，从此会骄傲懒惰起来。所以他力劝儿子要努力读书，通过自己的能力去创造财富才是最好的治家之法。
#+END_QUOTE


#+BEGIN_QUOTE
与其给子孙留下大笔遗产，不如教子孙走入正道。
#+END_QUOTE


#+BEGIN_QUOTE
子孙拥有自立自强的精神和能力最重要。他说，仕宦之家不蓄积银钱，使子弟自觉一日不勤则将有饥寒之患，则子弟渐渐勤劳，所以自立。
#+END_QUOTE


#+BEGIN_QUOTE
凡人皆望子孙为大官，余不愿为大官，但愿为读书明理之君子。勤俭自持，习劳习苦，可以处乐，可以处约，此君子也。”
#+END_QUOTE


#+BEGIN_QUOTE
打仗不慌不忙，先求稳当，次求变化；办事无声无息，既要精到，又要简捷。”希望
#+END_QUOTE
