#+TITLE:  [笔记]历史深处的民国
#+AUTHOR: Yang Yingchao
#+DATE:   2024-04-16
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:  align nodlcheck oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+LANGUAGE: en
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :tag1:tag2:note:ireader:



#+BEGIN_QUOTE
在鸦片战争以前，我们不肯给外国平等待遇；在以后，他们不肯给我们平等待遇。
#+END_QUOTE


#+BEGIN_QUOTE
苟利国家生死以，岂因祸福避趋之！
#+END_QUOTE


#+BEGIN_QUOTE
黄兴的妻子（徐宗汉）的妹妹（徐文）的第二个女儿（龚澎）的第二个丈夫（乔冠华）的第二个妻子（章含之）的第一个丈夫（洪君彦）的女儿（洪晃）的第二个丈夫是陈凯歌。
#+END_QUOTE


#+BEGIN_QUOTE
一般来说，领导说话要讲技巧，一定要说得高深，务必值得下属揣摩才算上乘，下属揣摩对了并且做得好那是领导有方，揣摩错了干得不好那是没有领会精神，千错万错都是下属的错就是这个意思。
#+END_QUOTE


#+BEGIN_QUOTE
简单的占有是小聪明，暂时的放弃才是大智慧
#+END_QUOTE


#+BEGIN_QUOTE
虽然贵为状元，但他没有学王文韶那样死抱着八股科举不放，而是向袁世凯等人学习，办新式教育，教化国人。二十年间，他倾尽所能创建了包括今复旦大学、今南京大学在内的三百七十多所高校，直到破产为止！ 救国救到破产，千古又有几人！
#+END_QUOTE


#+BEGIN_QUOTE
需要有人站出来为国家民族争取利益的时代，他们走出校园来到街头，为求真理，奋勇抗争；他们跋山涉水来到彩云之南，于艰难困苦中书声依旧，于烽火连天里薪继火传，缔造西南联大的传奇；他们弃笔从戎踏上抗战之路，筚路蓝缕，血洒疆场，却一往无前
#+END_QUOTE


#+BEGIN_QUOTE
在这个中华民族岌岌可危的时代，在这个需要有人站出来为国家民族争取利益的时代，他们走出校园来到街头，为求真理，奋勇抗争；他们跋山涉水来到彩云之南，于艰难困苦中书声依旧，于烽火连天里薪继火传，缔造西南联大的传奇；他们弃笔从戎踏上抗战之路，筚路蓝缕，血洒疆场，却一往无前
#+END_QUOTE


#+BEGIN_QUOTE
全书至此，关于孙中山的笔墨甚多，其中有褒有抑，这一切都是按照史料行笔，旨在还原一个真实的孙中山，一个有血有肉的孙中山
#+END_QUOTE


#+BEGIN_QUOTE
战败国德国，则身背两百六十亿美元左右的战争赔款，“一夜回到解放前”。要知道，那时的美元是很值钱的，中国近代史上所有的赔款加一块也就相当于德国赔款的十分之一，由此可见德国面临的压力之大
#+END_QUOTE


#+BEGIN_QUOTE
说到张道藩，我们正好来八卦一段他既纠结又混乱的情感往事
#+END_QUOTE


#+BEGIN_QUOTE
所以，从通车时起，滇缅公路就成了一条不折不扣的生命线。这条生命线是埋葬日本灭亡中国梦想的大道！必须保护好，不容有失。这就是后来中国组织远征军进入缅甸的真正原因。
#+END_QUOTE
