#+TITLE:  [笔记]唐诗三百首·宋词三百首·元曲三百首
#+AUTHOR: Yang Yingchao
#+DATE:   2024-04-16
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:  align nodlcheck oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+LANGUAGE: en
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :tag1:tag2:note:ireader:



#+BEGIN_QUOTE
赤壁 杜牧 折戟沉沙铁未销，自将磨洗认前朝。 东风不与周郎便，铜雀春深锁二乔。
#+END_QUOTE


#+BEGIN_QUOTE
回乡偶书 贺知章 少小离家老大回，乡音无改鬓毛衰。 儿童相见不相识，笑问客从何处来。
#+END_QUOTE


#+BEGIN_QUOTE
九月九日忆山东兄弟 王维 独在异乡为异客，每逢佳节倍思亲。 遥知兄弟登高处，遍插茱萸少一人。
#+END_QUOTE


#+BEGIN_QUOTE
芙蓉楼送辛渐 王昌龄 寒雨连江夜入吴，平明送客楚山孤。 洛阳亲友如相问，一片冰心在玉壶。
#+END_QUOTE


#+BEGIN_QUOTE
凉州词 王翰 葡萄美酒夜光杯，欲饮琵琶马上催。 醉卧沙场君莫笑，古来征战几人回。
#+END_QUOTE


#+BEGIN_QUOTE
黄鹤楼送孟浩然之广陵 李白 故人西辞黄鹤楼，烟花三月下扬州。 孤帆远影碧空尽，唯见长江天际流。
#+END_QUOTE


#+BEGIN_QUOTE
早发白帝城 李白 朝辞白帝彩云间，千里江陵一日还。
#+END_QUOTE


#+BEGIN_QUOTE
早发白帝城 李白 朝辞白帝彩云间，千里江陵一日还。 两岸猿声啼不住，轻舟已过万重山。
#+END_QUOTE


#+BEGIN_QUOTE
滁州西涧 韦应物 独怜幽草涧边生，上有黄鹂深树鸣。 春潮带雨晚来急，野渡无人舟自横。
#+END_QUOTE


#+BEGIN_QUOTE
枫桥夜泊 张继 月落乌啼霜满天，江枫渔火对愁眠。 姑苏城外寒山寺，夜半钟声到客船。
#+END_QUOTE


#+BEGIN_QUOTE
乌衣巷 刘禹锡 朱雀桥边野草花，乌衣巷口夕阳斜。 旧时王谢堂前燕，飞入寻常百姓家。
#+END_QUOTE


#+BEGIN_QUOTE
嫦娥 李商隐 云母屏风烛影深，长河渐落晓星沉。 嫦娥应悔偷灵药，碧海青天夜夜心。
#+END_QUOTE


#+BEGIN_QUOTE
送元二使安西 王维 渭城朝雨浥轻尘，客舍青青柳色新。 劝君更尽一杯酒，西出阳关无故人。
#+END_QUOTE


#+BEGIN_QUOTE
出塞 王昌龄 秦时明月汉时关，万里长征人未还。 但使龙城飞将在，不教胡马度阴山。
#+END_QUOTE


#+BEGIN_QUOTE
凉州词 王之涣 黄河远上白云间，一片孤城万仞山。 羌笛何须怨杨柳，春风不度玉门关。
#+END_QUOTE


#+BEGIN_QUOTE
赋得古原草送别 白居易 离离原上草，一岁一枯荣。 野火烧不尽，春风吹又生。 远芳侵古道，晴翠接荒城。 又送王孙去，萋萋满别情。
#+END_QUOTE


#+BEGIN_QUOTE
蜀相 杜甫 丞相祠堂何处寻，锦官城外柏森森。 映阶碧草自春色，隔叶黄鹂空好音。
#+END_QUOTE


#+BEGIN_QUOTE
蜀相 杜甫 丞相祠堂何处寻，锦官城外柏森森。 映阶碧草自春色，隔叶黄鹂空好音。 三顾频烦天下计，两朝开济老臣心。 出师未捷身先死，长使英雄泪满襟。
#+END_QUOTE


#+BEGIN_QUOTE
闻官军收河南河北 杜甫 剑外忽传收蓟北，初闻涕泪满衣裳。 却看妻子愁何在，漫卷诗书喜欲狂。 白日放歌须纵酒，青春作伴好还乡。 即从巴峡穿巫峡，便下襄阳向洛阳。
#+END_QUOTE


#+BEGIN_QUOTE
咏怀古迹五首 杜甫
#+END_QUOTE


#+BEGIN_QUOTE
阁夜 杜甫 岁暮阴阳催短景，天涯霜雪霁寒宵。 五更鼓角声悲壮，三峡星河影动摇。 野哭千家闻战伐，夷歌数处起渔樵。 卧龙跃马终黄土，人事音书漫寂寥。
#+END_QUOTE


#+BEGIN_QUOTE
咏怀古迹五首 杜甫 其一 支离东北风尘际，飘泊西南天地间。 三峡楼台淹日月，五溪衣服共云山。 羯胡事主终无赖，词客哀时且未还。 庾信平生最萧瑟，暮年诗赋动江关。 其二 摇落深知宋玉悲，风流儒雅亦吾师。 怅望千秋一洒泪，萧条异代不同时。 江山故宅空文藻，云雨荒台岂梦思。 最是楚宫俱泯灭，舟人指点到今疑。 其三 群山万壑赴荆门，生长明妃尚有村。 一去紫台连朔漠，独留青冢向黄昏。 画图省识春风面，环佩空归月夜魂。 千载琵琶作胡语，分明怨恨曲中论。 其四 蜀主窥吴幸三峡，崩年亦在永安官。 翠华想像空山里，玉殿虚无野寺中。 古庙杉松巢水鹤，岁时伏腊走村翁。 武侯祠屋常邻近，一体君臣祭祀同。 其五 诸葛大名垂宇宙，宗臣遗像肃清高。 三分割据纡筹策，万古云霄一羽毛。 伯仲之间见伊吕，指挥若定失萧曹。 运移汉祚终难复，志决身歼军务劳。 江州重别薛六柳八二员外 刘长卿 生涯岂料承忧诏，世事空知学醉歌。
#+END_QUOTE


#+BEGIN_QUOTE
咏怀古迹五首 杜甫 其一 支离东北风尘际，飘泊西南天地间。 三峡楼台淹日月，五溪衣服共云山。 羯胡事主终无赖，词客哀时且未还。 庾信平生最萧瑟，暮年诗赋动江关。 其二 摇落深知宋玉悲，风流儒雅亦吾师。 怅望千秋一洒泪，萧条异代不同时。 江山故宅空文藻，云雨荒台岂梦思。 最是楚宫俱泯灭，舟人指点到今疑。 其三 群山万壑赴荆门，生长明妃尚有村。 一去紫台连朔漠，独留青冢向黄昏。 画图省识春风面，环佩空归月夜魂。 千载琵琶作胡语，分明怨恨曲中论。 其四 蜀主窥吴幸三峡，崩年亦在永安官。 翠华想像空山里，玉殿虚无野寺中。 古庙杉松巢水鹤，岁时伏腊走村翁。 武侯祠屋常邻近，一体君臣祭祀同。 其五 诸葛大名垂宇宙，宗臣遗像肃清高。 三分割据纡筹策，万古云霄一羽毛。 伯仲之间见伊吕，指挥若定失萧曹。 运移汉祚终难复，志决身歼军务
#+END_QUOTE


#+BEGIN_QUOTE
咏怀古迹五首 杜甫 其一 支离东北风尘际，飘泊西南天地间。 三峡楼台淹日月，五溪衣服共云山。 羯胡事主终无赖，词客哀时且未还。 庾信平生最萧瑟，暮年诗赋动江关。 其二 摇落深知宋玉悲，风流儒雅亦吾师。 怅望千秋一洒泪，萧条异代不同时。 江山故宅空文藻，云雨荒台岂梦思。 最是楚宫俱泯灭，舟人指点到今疑。 其三 群山万壑赴荆门，生长明妃尚有村。 一去紫台连朔漠，独留青冢向黄昏。 画图省识春风面，环佩空归月夜魂。 千载琵琶作胡语，分明怨恨曲中论。 其四 蜀主窥吴幸三峡，崩年亦在永安官。 翠华想像空山里，玉殿虚无野寺中。 古庙杉松巢水鹤，岁时伏腊走村翁。 武侯祠屋常邻近，一体君臣祭祀同。 其五 诸葛大名垂宇宙，宗臣遗像肃清高。 三分割据纡筹策，万古云霄一羽毛。 伯仲之间见伊吕，指挥若定失萧曹。 运移汉祚终难复，志决身歼军务劳。
#+END_QUOTE


#+BEGIN_QUOTE
隋宫 李商隐 紫泉宫殿锁烟霞，欲取芜城作帝家。 玉玺不缘归日角，锦帆应是到天涯。 于今腐草无萤火，终古垂杨有暮鸦。 地下若逢陈后主，岂宜重问《后庭花》！ 无题
#+END_QUOTE


#+BEGIN_QUOTE
隋宫 李商隐 紫泉宫殿锁烟霞，欲取芜城作帝家。 玉玺不缘归日角，锦帆应是到天涯。 于今腐草无萤火，终古垂杨有暮鸦。 地下若逢陈后主，岂宜重问《后庭花》！
#+END_QUOTE


#+BEGIN_QUOTE
苏武庙 温庭筠 苏武魂销汉使前，古祠高树两茫然。 云边雁断胡天月，陇上羊归塞草烟。 回日楼台非甲帐，去时冠剑是丁年。 茂陵不见封侯印，空向秋波哭逝川。
#+END_QUOTE


#+BEGIN_QUOTE
经五丈原 温庭筠
#+END_QUOTE


#+BEGIN_QUOTE
经五丈原 温庭筠 铁马云雕共绝尘，柳营高压汉宫春。 天清杀气屯关右，夜半妖星照渭滨。 下国卧龙空寤主，中原得鹿不由人。 象床宝帐无言语，从此谯周是老臣。
#+END_QUOTE


#+BEGIN_QUOTE
蝶恋花 欧阳修 庭院深深深几许？杨柳堆烟，帘幕无重数。玉勒雕鞍游冶处，楼高不见章台路。 雨横风狂三月暮，门掩黄昏，无计留春住。泪眼问花花不语，乱红飞过秋千去。 青
#+END_QUOTE


#+BEGIN_QUOTE
蝶恋花 欧阳修 庭院深深深几许？杨柳堆烟，帘幕无重数。玉勒雕鞍游冶处，楼高不见章台路。 雨横风狂三月暮，门掩黄昏，无计留春住。泪眼问花花不语，乱红飞过秋千去。 青
#+END_QUOTE


#+BEGIN_QUOTE
蝶恋花 欧阳修 庭院深深深几许？杨柳堆烟，帘幕无重数。玉勒雕鞍游冶处，楼高不见章台路。 雨横风狂三月暮，门掩黄昏，无计留春住。泪眼问花花不语，乱红飞过秋千去。
#+END_QUOTE


#+BEGIN_QUOTE
水调歌头 苏轼 丙辰中秋，欢饮达旦，大醉，作此篇兼怀子由。 明月几时有？把酒问青天。不知天上宫阙，今夕是何年？我欲乘风归去，又恐琼楼玉宇，高处不胜寒。起舞弄清影，何似在人间。 转朱阁，低绮户，照无眠。不应有恨，何事长向别时圆？人有悲欢离合，月有阴晴圆缺，此事古难全。但愿人长久，千里共婵娟。
#+END_QUOTE


#+BEGIN_QUOTE
念奴娇 赤壁怀古 苏轼 大江东去，浪淘尽、千古风流人物。故垒西边，人道是、三国周郎赤壁。乱石穿空，惊涛拍岸，卷起千堆雪。江山如画，一时多少豪杰。 遥想公瑾当年，小乔初嫁了，雄姿英发。羽扇纶巾，谈笑间、樯橹灰飞烟灭。故国神游，多情应笑我，早生华发。人生如梦，一樽还酹江月。
#+END_QUOTE


#+BEGIN_QUOTE
踏莎行 秦观 雾失楼台，月迷津渡，桃源望断无寻处。可堪孤馆闭春寒，杜鹃声里斜阳暮。 驿寄梅花，鱼传尺素，砌成此恨无重数。郴江幸自绕郴山，为谁流下潇湘去。
#+END_QUOTE


#+BEGIN_QUOTE
苏武慢 蔡伸 雁落平沙，烟笼寒水，古垒鸣笳声断。青山隐隐，败叶萧萧，天际暝鸦零乱。楼上黄昏，片帆千里归程，年华将晚。望碧云空暮，佳人何处？梦魂俱远。 忆旧游、邃馆朱扉，小园香径，尚想桃花人面。书盈锦轴，恨满金徽，难写寸心幽怨。两地离愁，一尊芳酒凄凉，危阑倚遍。尽迟留、凭仗西风，吹干泪眼。
#+END_QUOTE


#+BEGIN_QUOTE
满江红 岳飞 怒发冲冠，凭栏处、潇潇雨歇。抬望眼、仰天长啸，壮怀激烈。三十功名尘与土，八千里路云和月。莫等闲、白了少年头，空悲切。 靖康耻，犹未雪；臣子恨，何时灭！驾长车踏破、贺兰山缺。壮志饥餐胡虏肉，笑谈渴饮匈奴血。待从头、收拾旧山河，朝天阙。
#+END_QUOTE


#+BEGIN_QUOTE
清平乐·村居 辛弃疾 村居茅檐低小，溪上青青草。醉里吴音相媚好，白发谁家翁媪？ 大儿锄豆溪东，中儿正织鸡笼。最喜小儿无赖，溪头卧剥莲蓬。
#+END_QUOTE


#+BEGIN_QUOTE
贺新郎 端午 刘克庄 深院榴花吐，画帘开、綀衣纨扇，午风清暑。儿女纷纷夸结束，新样钗符艾虎。早已有游人观渡。老大逢场慵作戏，任陌头、年少争旗鼓。溪雨急，浪花舞。 灵均标致高如许，忆生平、既纫兰佩，更怀椒糈。谁信骚魂千载后，波底垂涎角黍。又说是、蛟馋龙怒。把似而今醒到了，料当年、醉死差无苦。聊一笑，吊千古。
#+END_QUOTE


#+BEGIN_QUOTE
送杨氏女 韦应物 永日方戚戚，出行复悠悠。 女子今有行，大江溯轻舟。 尔辈苦无恃，抚念益慈柔。 幼为长所育，两别泣不休。 对此结中肠，义往难复留。 自小阙内训，事姑贻我忧。 赖兹托令门，任恤庶无尤。 贫俭诚所尚，资从岂待周。 孝恭遵妇道，容止顺其猷。 别离在今晨，见尔当何秋？ 居闲始自遣，临感忽难收。 归来视幼女，零泪缘缨流。
#+END_QUOTE


#+BEGIN_QUOTE
游子吟 孟郊 慈母手中线，游子身上衣。 临行密密缝，意恐迟迟归。 谁言寸草心，报得三春晖！
#+END_QUOTE


#+BEGIN_QUOTE
石鱼湖上醉歌并序 元结 漫叟以公田米酿酒，因休暇则载酒于湖上，时取一醉。欢醉中，据湖岸引臂向鱼取酒，使舫载之，遍饮坐者。意疑倚巴丘酌于君山之上，诸子环洞庭而坐，酒舫泛泛然触波涛而往来者，乃作歌以长之。 石鱼湖，似洞庭，夏水欲满君山青。 山为樽，水为沼，酒徒历历坐洲岛。 长风连日作大浪，不能废人运酒舫。 我持长瓢坐巴丘，酌饮四座以散愁。 山石 韩愈 山石荦确行径微，黄昏到寺蝙蝠飞。 升堂坐阶新雨足，芭蕉叶大栀子肥。 僧言古壁佛画好，以火来照所见稀。 铺床拂席置羹饭，疏粝亦足饱我饥。 夜深静卧百虫绝，清月出岭光入扉。 天明
#+END_QUOTE


#+BEGIN_QUOTE
石鱼湖上醉歌并序 元结 漫叟以公田米酿酒，因休暇则载酒于湖上，时取一醉。欢醉中，据湖岸引臂向鱼取酒，使舫载之，遍饮坐者。意疑倚巴丘酌于君山之上，诸子环洞庭而坐，酒舫泛泛然触波涛而往来者，乃作歌以长之。 石鱼湖，似洞庭，夏水欲满君山青。 山为樽，水为沼，酒徒历历坐洲岛。 长风连日作大浪，不能废人运酒舫。 我持长瓢坐巴丘，酌饮四座以散愁。
#+END_QUOTE


#+BEGIN_QUOTE
观公孙大娘弟子舞剑器行并序 杜甫 大历二年十月十九日，夔府别驾元持宅见临颖李十二娘舞剑器，壮其蔚跂。问其所师，曰：“余公孙大娘
#+END_QUOTE


#+BEGIN_QUOTE
观公孙大娘弟子舞剑器行并序 杜甫 大历二年十月十九日，夔府别驾元持宅见临颖李十二娘舞剑器，壮其蔚跂。问其所师，曰：“余公孙大娘弟子也。”
#+END_QUOTE


#+BEGIN_QUOTE
观公孙大娘弟子舞剑器行并序 杜甫 大历二年十月十九日，夔府别驾元持宅见临颖李十二娘舞剑器，壮其蔚跂。问其所师，曰：“余公孙大娘弟子也。”开元五载，余尚童稚，记于郾城观公孙氏舞剑器浑脱，浏漓顿挫，独出冠时。自高头宜春、梨园二伎坊内人洎外供奉，晓是舞者，圣文神武皇帝初，公孙一人而已。玉貌锦衣，况余白首；今兹弟子，亦匪盛颜。既辨其由来，知波澜莫二。抚事慷慨，聊为《剑器行》。昔者吴人张旭，善草书书帖，数常于邺县见公孙大娘舞西河剑器，自此草书长进，豪荡感激，即公孙可知矣。 昔有佳人公孙氏，一舞剑器动四方。 观者如山色沮丧，天地为之久低昂。 燿如羿射九日落，矫如群帝骖龙翔。 来如雷霆收震怒，罢如江海凝清光。 绛唇珠袖两寂寞，晚有弟子传芬芳。 临颍美人在白帝，妙舞此曲神扬扬。 与余问答既有以，感时抚事增惋伤。 先帝侍女八千人，公孙剑器初第一。
#+END_QUOTE


#+BEGIN_QUOTE
观公孙大娘弟子舞剑器行并序 杜甫 大历二年十月十九日，夔府别驾元持宅见临颖李十二娘舞剑器，壮其蔚跂。问其所师，曰：“余公孙大娘弟子也。”开元五载，余尚童稚，记于郾城观公孙氏舞剑器浑脱，浏漓顿挫，独出冠时。自高头宜春、梨园二伎坊内人洎外供奉，晓是舞者，圣文神武皇帝初，公孙一人而已。玉貌锦衣，况余白首；今兹弟子，亦匪盛颜。既辨其由来，知波澜莫二。抚事慷慨，聊为《剑器行》。昔者吴人张旭，善草书书帖，数常于邺县见公孙大娘舞西河剑器，自此草书长进，豪荡感激，即公孙可知矣。 昔有佳人公孙氏，一舞剑器动四方。 观者如山色沮丧，天地为之久低昂。 燿如羿射九日落，矫如群帝骖龙翔。 来如雷霆收震怒，罢如江海凝清光。 绛唇珠袖两寂寞，晚有弟子传芬芳。 临颍美人在白帝，妙舞此曲神扬扬。 与余问答既有以，感时抚事增惋伤。 先帝侍女八千人，公孙剑器初第一。 五十年间似反掌，风尘澒洞昏王室。 梨园弟子散如烟，女乐余姿映寒日。 金粟堆南木已拱，瞿唐石城草萧瑟。 玳筵急管曲复终，乐极哀来月东出。 老夫不知其所往，足茧荒山转愁疾。
#+END_QUOTE


#+BEGIN_QUOTE
鹿柴 王维 空山不见人，但闻人语响。 返景入深林，复照青苔上。
#+END_QUOTE


#+BEGIN_QUOTE
相思 王维 红豆生南国，春来发几枝？ 愿君多采撷，此物最相思。 杂诗 王维 君自故乡来，应知故乡事。 来日绮窗前，寒梅著花未？ 山中送别
#+END_QUOTE


#+BEGIN_QUOTE
相思 王维 红豆生南国，春来发几枝？ 愿君多采撷，此物最相思。
#+END_QUOTE


#+BEGIN_QUOTE
春晓 孟浩然 春眠不觉晓，处处闻啼鸟。 夜来风雨声，花落知多少？
#+END_QUOTE


#+BEGIN_QUOTE
静夜思 李白 床前明月光，疑是地上霜。 举头望明月，低头思故乡。
#+END_QUOTE


#+BEGIN_QUOTE
八阵图 杜甫 功盖三分国，名成八阵图。 江流石不转，遗恨失吞吴。
#+END_QUOTE


#+BEGIN_QUOTE
登鹳雀楼 王之涣 白日依山尽，黄河入海流。 欲穷千里目，更上一层楼。
#+END_QUOTE


#+BEGIN_QUOTE
江雪 柳宗元 千山鸟飞绝，万径人踪灭。 孤舟蓑笠翁，独钓寒江雪。
#+END_QUOTE


#+BEGIN_QUOTE
贾岛 松下问童子，言师采药去。 只在此山中，云深不知处。
#+END_QUOTE


#+BEGIN_QUOTE
塞下曲四首 卢纶 其一 鹫翎金仆姑，燕尾绣蝥弧。 独立扬新令，千营共一呼。 其二 林暗草惊风，将军夜引弓。 平明寻白羽，没在石棱中。 其三 月黑雁飞高，单于夜遁逃。 欲将轻骑逐，大雪满弓刀。 其四 野幕敞琼筵，羌戎贺劳旋。 醉和金甲舞，雷鼓动山川。 江南
#+END_QUOTE


#+BEGIN_QUOTE
塞下曲四首 卢纶 其一 鹫翎金仆姑，燕尾绣蝥弧。 独立扬新令，千营共一呼。 其二 林暗草惊风，将军夜引弓。 平明寻白羽，没在石棱中。 其三 月黑雁飞高，单于夜遁逃。 欲将轻骑逐，大雪满弓刀。 其四 野幕敞琼筵，羌戎贺劳旋。 醉和金甲舞，雷鼓动山川。 江南
#+END_QUOTE


#+BEGIN_QUOTE
塞下曲四首 卢纶 其一 鹫翎金仆姑，燕尾绣蝥弧。 独立扬新令，千营共一呼。 其二 林暗草惊风，将军夜引弓。 平明寻白羽，没在石棱中。 其三 月黑雁飞高，单于夜遁逃。 欲将轻骑逐，大雪满弓刀。 其四 野幕敞琼筵，羌戎贺劳旋。 醉和金甲舞，雷鼓动山川。
#+END_QUOTE
