#+TITLE:  [笔记]平凡的世界
#+AUTHOR: Yang Yingchao
#+DATE:   2024-04-16
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:  align nodlcheck oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+LANGUAGE: en
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :tag1:tag2:note:ireader:



#+BEGIN_QUOTE
现在他们虽然到了一个大学校，但这里的一切都常常出现在他们的睡梦中。
#+END_QUOTE


#+BEGIN_QUOTE
他们村叫个罐子村，他就是罐子村的破罐子！去他妈的，破罐子破摔，反正总是个破了！
#+END_QUOTE


#+BEGIN_QUOTE
一次又一次，使他的心脏渐渐地强有力起来，并且在一次次的磨难中也尝到了生活的另一种滋味。他觉得自己正一步步迈向了成年人的行列。他慢慢懂得，人活着，就得随时准备经受磨难。
#+END_QUOTE


#+BEGIN_QUOTE
玉厚老汉在心里时常为自己的子女而骄傲。孩子们一个个都懂事明理，长得茁茁壮壮的。 这就是他生命的全部意义。这就是他活着的全部价值。
#+END_QUOTE


#+BEGIN_QUOTE
吉普赛人只爱飘泊，不爱劳动。但河南人除过个别不务正业者之外，不论走到哪里，都用自己的劳动技能来换取报酬。
#+END_QUOTE


#+BEGIN_QUOTE
在眼前这样的社会里，又是十七、八岁，他们谁有火眼金睛望穿未来的时代？别说他们了，就是一些饱经沧桑的老革命，这时候也未必具有清醒的认识，许多人不也是一天一天混日子吗？
#+END_QUOTE


#+BEGIN_QUOTE
这是人生的一个火山活跃期，熔岩突奔，炽流横溢，在每一个感情的缝隙中，随时都可能咝咝地冒烟和喷火！
#+END_QUOTE


#+BEGIN_QUOTE
这一点自留地，他宝贵得不知种什么好，从庄稼到蔬菜，互相套作，边边畔畔，见缝插针。种什么都是精心谋划的——有些要补充口粮，有些要换成零用钱……他一年不知要在这块土地上洒多少汗水。不管他怎样劳累，一旦进了这个小小的天地，浑身的劲就来了。有时简直不是在劳动，而是在倾注一腔热情。是的，这里的每一种收获，都将全部属于自己。只要能切实地收获，劳动者就会在土地上产生一种艺术创作般的激情……
#+END_QUOTE


#+BEGIN_QUOTE
队里几乎所有的社员，都常抱怨他把他们扣得太紧，简直到了残酷的程度——山里休息往往连烟瘾都过不了就又被他赶起来干活。有人甚至背后叫他“孙阎王”。但他不管这些。他想，如果不这样下苦，秋后一分粮食，你们就要骂我是“龟孙子”了。
#+END_QUOTE


#+BEGIN_QUOTE
人啊！有时候都比不上飞禽走兽，自由自在地在天空飞，在地上走……
#+END_QUOTE


#+BEGIN_QUOTE
虽然天旱得快把庄稼晒死了，但该做的活路一点也不能少；俗话说，锄头下面有雨，多锄一遍地就大不一样啊！
#+END_QUOTE


#+BEGIN_QUOTE
太阳象火盆一样高悬在空中，山上的庄稼叶子都快晒干了，所有的绿颜色都开始变灰，阳坡上有的庄稼甚至已经枯黄了。庄稼人出于习惯和本能，依然在这些毫无收获指望的土地上辛勤地劳作着，抚哺这些快要死亡的、用他们的血汗浇灌起来的生命。整个村子已经失去了生气，任何人的脸上都再也看不出一丝的笑容来了。到处都
#+END_QUOTE


#+BEGIN_QUOTE
原西河对岸的山湾里，桃花又一次红艳艳地盛开了。河
#+END_QUOTE


#+BEGIN_QUOTE
原西河对岸的山湾里，桃花又一次红艳艳地盛开了。河两岸的缓坡上，刚出地皮的青草芽子和枯草夹杂在一起，黄黄绿绿，显出了一派盎然的生机。柳丝如同少女的秀发，在春风中摇曳。
#+END_QUOTE


#+BEGIN_QUOTE
人们现在还不能预料未来；但一个不能再让人忍受的年代已经结束，这就应该大声地欢呼！谁也不会天真地认为，积了十年的垃圾，就能在一夜之间清理干净。但是人们坚信：尽管在原轨道上刹住的车子还要在惯性中滑一段路程，但中国历史的大轮必将重新启动，进入到一个转折性的弯道上……
#+END_QUOTE


#+BEGIN_QUOTE
她感到头晕目眩，甚至不知道自己身在何地。命运啊，多么无情！这不是婚礼，而是她青春的葬礼……
#+END_QUOTE


#+BEGIN_QUOTE
在这些日子里，山乡圪崂有些不讲卫生的“懒大嫂”们，冷得不想出门，往往就让自己的娃娃把大便拉在炕席片上，然后把狗唤过来给他“打扫卫生”，因此就有了那句著名的乡谚“三九四九，隔门叫狗”……气候的确是寒冷啊！
#+END_QUOTE


#+BEGIN_QUOTE
人们在土地上付出血汗和艰辛，那是应该收获欢乐和幸福，而不是收获忧虑和苦痛的……
#+END_QUOTE


#+BEGIN_QUOTE
俗话说，人有三年旺，神鬼不敢挡。
#+END_QUOTE


#+BEGIN_QUOTE
没能耐的人还得用双手在土地上刨挖着吃。
#+END_QUOTE


#+BEGIN_QUOTE
现在这社会，即是办正事，也得走旁门拐道！
#+END_QUOTE


#+BEGIN_QUOTE
应该提醒我们不能老是用一种眼光来看待人。不要以为一个人一时正确，就认为他永远正确。也不要因为一个人犯过错误，就断定他永远不可再加入优秀者的队伍。道理
#+END_QUOTE


#+BEGIN_QUOTE
我们承认伟人在历史过程中的贡献。可人类生活的大厦从本质上说，是由无数普通人的血汗乃至生命所建造的。伟人们常常企图用纪念碑或纪念堂来使自己永世流芳。真正万古长青的却是普通人的无人纪念碑——生生不息的人类生活自身。是的，生活之树常青。
#+END_QUOTE


#+BEGIN_QUOTE
我们承认伟人在历史过程中的贡献。可人类生活的大厦从本质上说，是由无数普通人的血汗乃至生命所建造的。伟人们常常企图用纪念碑或纪念堂来使自己永世流芳。真正万古长青的却是普通人的无人纪念碑——生生不息的人类生活自身。是的，生活之树常青。 这就是我们对一个平凡世界的死者所能做的祭文。
#+END_QUOTE


#+BEGIN_QUOTE
要旨仍然应该是首先战胜自己，并将精神提升到不断发展着的生活所要求的那种高度，才有可能使自己重新走出洼地，亦步亦趋跟着生活进入新的境界。
#+END_QUOTE
