#+TITLE:  [笔记]欧洲文明十五讲
#+AUTHOR: Yang Yingchao
#+DATE:   2024-04-16
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:  align nodlcheck oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+LANGUAGE: en
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :tag1:tag2:note:ireader:



#+BEGIN_QUOTE
欧洲不只是一个地理概念，它更是一个文化的概念。它不仅仅是 geographical Europe，还是 cultural Europe。
#+END_QUOTE


#+BEGIN_QUOTE
黑格尔把中国和印度划在了世界历史之外，就是把中国和印度看做了世界历史发展规律之外的国家，是“另类”。
#+END_QUOTE


#+BEGIN_QUOTE
客观地说，中国进入世界历史的发展进程，才一百多年，
#+END_QUOTE


#+BEGIN_QUOTE
历史的长期合理性”，就是说历史是不能责怪的。
#+END_QUOTE


#+BEGIN_QUOTE
做学问，包括你们本科生的学习，没有一种“情结”，是不行的。总之要有“情结”，要有兴趣的升华，甚至升华到带有感情色彩了，你才能学得下去。
#+END_QUOTE


#+BEGIN_QUOTE
做学问这个事情，有两点很重要——现在我姑且把大家都算做做学问的人——
#+END_QUOTE


#+BEGIN_QUOTE
第一，要怀疑。没有怀疑，就没有知识，
#+END_QUOTE


#+BEGIN_QUOTE
第一，要怀疑。没有怀疑，就没有知识，大家都知道，笛卡儿的这句话：“我思，故我在。”但常常忘了他说“我思，故我在”之前的论证。前面的论证，如果我要给他概括的话，可以是五个字：“我疑，故我思”——我有怀疑，所以我思想；因为我有思想，所以我存在
#+END_QUOTE


#+BEGIN_QUOTE
假如把这两句话连在一起，确实构成了知识论的完整的东西：“我疑，故我思；我思，故我在。”就是说，一个人，要有怀疑，才有知识。
#+END_QUOTE


#+BEGIN_QUOTE
第二点，要经常感到缺憾，经常感到自己缺点什么东西，知识才能见长。
#+END_QUOTE


#+BEGIN_QUOTE
生命是有限的，知识是无穷的。
#+END_QUOTE


#+BEGIN_QUOTE
第一，要怀疑。没有怀疑，就没有知识，大家都知道，笛卡儿的这句话：“我思，故我在。”但常常忘了他说“我思，故我在”之前的论证。前面的论证，如果我要给他概括的话，可以是五个字：“我疑，故我思”——我有怀疑，所以我思想；因为我有思想，所以我存在。他这个存在主要是本体论的存在，
#+END_QUOTE


#+BEGIN_QUOTE
西方人就是这样，不断提出问题，不断假设问题；解决一个问题，提出一个问题；解决一个问题，再提出一个问题。中国不是这样。中国解决了一个问题，敲锣打鼓好几年。
#+END_QUOTE


#+BEGIN_QUOTE
得一位老师，兴一个学科。
#+END_QUOTE


#+BEGIN_QUOTE
欧洲文明的源头——大家公认的，我的书里面也是这样写的——是“两希文明”，就是希伯来和希腊。
#+END_QUOTE


#+BEGIN_QUOTE
欧洲文明的源头——大家公认的，我的书里面也是这样写的——是“两希文明”，就是希伯来和希腊。然后呢，就是罗马，再加上基督教文明，这就是欧洲文明的源头
#+END_QUOTE


#+BEGIN_QUOTE
欧洲文明的源头是希腊，希腊文明的源头是同两河流域的交流。
#+END_QUOTE


#+BEGIN_QUOTE
欧洲文明的源头是希腊，希腊文明的源头是同两河流域的交流。不是说从两河流域的文化发展出了一个希腊文化，而是说希腊文化受到了两河流域文化的影响。
#+END_QUOTE


#+BEGIN_QUOTE
黑格尔经常说只要一提到希腊，就有一种“家园之感”。那么大的欧洲把那么小的希腊当作自己的家园，这话不是偶然
#+END_QUOTE


#+BEGIN_QUOTE
我们常说现在欧洲文明的核心——我自己就经常这样说——是科学和民主，
#+END_QUOTE


#+BEGIN_QUOTE
广泛阅读对于你们国际关系学科可能看起来比较遥远，但是在文化的修养和历史文化的积淀上会给你们很大的好处。
#+END_QUOTE


#+BEGIN_QUOTE
这个地方的文化，是挽救这个地方的一个决定性的因素。
#+END_QUOTE


#+BEGIN_QUOTE
两河流域——幼发拉底和底格里斯——这两条河是贯穿着伊拉克的，下面一直流到叙利亚。
#+END_QUOTE


#+BEGIN_QUOTE
地理和人文方面的希腊和古希腊文明还有一个来源，就是两河
#+END_QUOTE


#+BEGIN_QUOTE
地理和人文方面的希腊和古希腊文明还有一个来源，就是两河流域。
#+END_QUOTE


#+BEGIN_QUOTE
悼词里边还讲到了“雅典精神”——“冒险”，我体会这个“冒险”就是“进取”的意思，不达到目的决不罢休的精神，勇敢的精神、探险的精神、不怕牺牲的精神。
#+END_QUOTE


#+BEGIN_QUOTE
希腊人是爱美的，但是绝不娇柔；希腊人是勇敢的，但是绝不蛮干。
#+END_QUOTE


#+BEGIN_QUOTE
黑格尔一再强调希腊的精神是自由，是雄伟的、美丽的，
#+END_QUOTE


#+BEGIN_QUOTE
雅典的文明进一步的发展、繁荣。在思想界里出现了“诡辩派”，有些老先生不太同意这样的译法，因为诡辩这个词给人的印象就是没理搅三分，所以他们主张把它翻译成“智术之士”。后人为什么把它叫做诡辩派呢？我想这是后人总结的，后人觉得这帮人称不上是哲学家，他们只满足于口头上的舌辩之辞。
#+END_QUOTE


#+BEGIN_QUOTE
诡辩派也是从这里出发的，去研究自然，探讨自然界的问题。那个时候雅典确实已经到了非常自由的时期，思想是自由的，街谈巷议，组织各种讨论会，很随便。逐步地，这些辩者有的就变成了无理搅三分，把真理抛在了一边，专门为了辩论而辩论，所以后来人们就叫他们诡辩者。
#+END_QUOTE


#+BEGIN_QUOTE
这些先哲们在探讨一些问题时，是可能有通感的。什么叫正当的辩论，什么叫无理搅三分，是有一个共同的标准、共同的心理的。
#+END_QUOTE


#+BEGIN_QUOTE
在这种辩论过程当中产生了哲学。在古希腊，哲学和科学是不分的，哲学就是追求知识、寻求智慧的学问，和科学在当时是不可分的。古希腊出现了各种文学和艺术、诗歌、戏剧，戏剧也是在辩论过程中产生的。
#+END_QUOTE


#+BEGIN_QUOTE
苏格拉底的死是一个悲剧，死于雅典的民主，而民主制度是欧洲文明的源泉之一，这是矛盾的，也是辩证的。
#+END_QUOTE


#+BEGIN_QUOTE
柏拉图写了很多的“对话集”，就是以苏格拉底为主，和他周围的学生、朋友一起谈话，有的是学生提问，苏格拉底回答，有的是苏格拉底请一位学生开讲。
#+END_QUOTE


#+BEGIN_QUOTE
子曰:。。。。
#+END_QUOTE


#+BEGIN_QUOTE
我们发现公元前 4 世纪的时候，希腊人已经知道中国人了，但是我们查不到很多的记载，最古老的记载是公元前 4 世纪，在古文献里提到了“seres”这个字，这个词的词根是“丝”的意思，蚕丝、丝
#+END_QUOTE


#+BEGIN_QUOTE
看到“丝之国”里面的羊毛是长在树上的！还有的说“丝之国”的人做买卖非常狡猾。
#+END_QUOTE


#+BEGIN_QUOTE
这次战争里边有很多故事，比如说马拉松（现在奥林匹克运动中的马拉松比赛），就是出在希波战争中。马拉松是一个海湾，距离雅典 40 多公里，在这个地方雅典人和波斯人会战，战争打得很惨。在胜负初决的时候，有一个雅典士兵从马拉松海滩跑回雅典去报告前方的军情。他跑得非常快，40 多公里一口气从马拉松海湾一直跑到雅典城下，大声喊：“胜利了！”这马拉松赛跑就从这儿来的，就是长跑。
#+END_QUOTE


#+BEGIN_QUOTE
这些改革的重点用两句话概括就是：一句叫主权在民；一句叫轮番为治。
#+END_QUOTE


#+BEGIN_QUOTE
文人知识分子就爱多嘴多舌，他老先生 1952 年说了一句话，说：“我们现在是一条腿粗一条腿细，马列主义腿太粗，世界史的这条腿太细。”然后就受到了批判，戴上了右派帽子，从此也就没有写什么书，非常可惜，一个大家就这么断送了。
#+END_QUOTE


#+BEGIN_QUOTE
你从我们的古圣先贤当中想要找一篇像伯里克利的悼词一样的文章出来，是找不到的。那是对人民，对普通人的尊重，让普通人参与政治生活。
#+END_QUOTE


#+BEGIN_QUOTE
但是鲁迅说：跟我结仇的人我到死一个都不宽恕他。
#+END_QUOTE


#+BEGIN_QUOTE
我觉得这是我们中国人的一个毛病，不大习惯于分析，要么黑就黑到底，要么白就白到底，听到一个新鲜的理论就跟着这个新鲜的理论跑，而不是自己动动脑筋想一想。
#+END_QUOTE


#+BEGIN_QUOTE
我觉得这是我们中国人的一个毛病，不大习惯于分析，要么黑就黑到底，要么白就白到底，听到一个新鲜的理论就跟着这个新鲜的理论跑，而不是自己动动脑筋想一想。我觉得这是学习、做研究工作的一个大忌，很大的忌讳。书不能不读，但是不能不用自己的脑子去想。孔老夫子说过：“学而不思则罔，思而不学则殆。”学和思是连在一起的，光是学而不动脑筋，白学；光是瞎动脑筋而不学习，也不行，那是瞎想。学和思是连在一块的，
#+END_QUOTE


#+BEGIN_QUOTE
到西罗马帝国灭亡的时候，中世纪开始了，这是历史的划分，
#+END_QUOTE


#+BEGIN_QUOTE
一些学术著作、一些理论著作，非要捏着鼻子看不可的，这是必要的。
#+END_QUOTE


#+BEGIN_QUOTE
自从皇帝们当政的时候起，历史就更加难写了，因为一切都变成秘密的了；行省的一切公文信件都送到皇帝的办公厅。人们能够知道的只有暴君们的愚蠢和大胆所不愿隐藏的东西，或是历史家们所能猜到的东西而已。”
#+END_QUOTE


#+BEGIN_QUOTE
没有比在法律的借口下和装出公正的姿态时所做出的事情更加残酷的暴政的了。因为在这样的情况下，可以说不幸的人们正是在他们得救的跳板上被溺死的。”
#+END_QUOTE


#+BEGIN_QUOTE
屋大维还有一个称号呢，刚才没说，叫做“奥古斯都”，奥古斯都的意思就是第一个。
#+END_QUOTE


#+BEGIN_QUOTE
秦始皇啊这是
#+END_QUOTE


#+BEGIN_QUOTE
暴君的统治固然很厉害，但是在暴君统治之下的人民的腐化，志气怠惰，沾沾自喜于这个帝国取得的所谓的成就，这是更可怕的事情。
#+END_QUOTE


#+BEGIN_QUOTE
一般认为中世纪始于日耳曼民族占领罗马，就是 476 年，西罗马帝国灭亡。
#+END_QUOTE


#+BEGIN_QUOTE
查理曼大帝有三个孙子，三个孙子合不来，然后把查理曼帝国一分为三：西部归了老三，东部归了老二，中间一部分加上意大利归了老大。这也就是后来法国、德国、意大利的来源。
#+END_QUOTE


#+BEGIN_QUOTE
其实 Re-naissance 这个词中文翻译成“文艺复兴”，我觉得翻译的不大对。在意大利那个时候 Renaissance 并不只指文艺。当然是从文艺开始的，比如达·芬奇、拉菲尔、米开朗基罗这些人从文艺开始。但它主要精神是人文精神。
#+END_QUOTE


#+BEGIN_QUOTE
的。“十字军东征”一共八次，由教皇发起，各国国君领衔。现在看来，“十字军”是凑起了一批以基督教徒为骨干的杂牌军。对社会不满的，打砸抢的，流氓无赖，全凑在一起。
#+END_QUOTE


#+BEGIN_QUOTE
民族国家的意思，就是大体上一种统一的语言，一种基本的文化，一种大体上的领土，然后一个国家主权。
#+END_QUOTE


#+BEGIN_QUOTE
中世纪对欧洲的第三大贡献是“东西交流”。
#+END_QUOTE


#+BEGIN_QUOTE
下面我来讲中世纪对欧洲的第二大贡献——基督教文明。
#+END_QUOTE


#+BEGIN_QUOTE
首先，中世纪，或者叫做欧洲的封建时代，对欧洲历史有一个大的贡献，这个贡献就是促使欧洲，特别是欧洲西部，在近代时期成为民族国家的欧洲。 欧洲原来
#+END_QUOTE


#+BEGIN_QUOTE
君主论》给美第奇家族出主意，说你要做好皇帝的话，你必须做“暴君”，什么手段都可以用，只要能成功就行，所以后人就把只要成功而不要任何道德，什么坏招都可以使用的做法，叫“马基雅维利主义”。
#+END_QUOTE


#+BEGIN_QUOTE
基督教里头又分为新教和旧教，旧教就是天主教，而新教就是基督教。新教最大的不同就是没有了那么多的清规戒律，没有一个统一宗教上的意识形态。像天主教有个教皇在统治着，而新教就没有这个东西。新教主张祈祷的方式、做弥撒的方式都要自由一些，形式可以多种多样，不一定按罗马教皇的那一套。
#+END_QUOTE


#+BEGIN_QUOTE
革命不是一个人思想改造如何如何，而是一个社会怎么样。下面他又说“这一启蒙运动除了自由而外并不需要任何别的东西。”这说到了“启蒙”的本质。“启蒙运动”是什么东西？他又重复“那就是在一切事情上，都有公开运用自己的理性的自由。”
#+END_QUOTE


#+BEGIN_QUOTE
通过一场革命或许很可以实现推翻个人专制以及贪婪心和权势欲的压迫，但却决不能实现思想方式的真正改革。而新的偏见也正如镜子一样，将会成为驾驭缺少思想的广大人群的圈套。”
#+END_QUOTE


#+BEGIN_QUOTE
通过一场革命或许很可以实现推翻个人专制以及贪婪心和权势欲的压迫，但却决不能实现思想方式的真正改革。而新的偏见也正如镜子一样，将会成为驾驭缺少思想的广大人群的圈套。”一场革命能办得到推翻个人专制或一种压迫，但是它绝对“不能实现思想方式的真正改革”。
#+END_QUOTE


#+BEGIN_QUOTE
而且新的偏见也正如镜子一样，将会成为驾驭缺少思想的广大人群的圈套。”
#+END_QUOTE


#+BEGIN_QUOTE
弗朗西斯·培根（1561—1626），英国实验哲学家、科学家，倡言：“读书使人丰富，讨论使人活跃，写作使人严谨。”
#+END_QUOTE


#+BEGIN_QUOTE
培根有三句话我觉得非常精彩，对诸位同学都有用处。第一句话是“读书使一个人丰富”，第二句话“讨论可以使一个人成熟”，第三句话叫做“写作使一个人精确”。
#+END_QUOTE


#+BEGIN_QUOTE
Reading maketh a full man;Conference,a ready man;Writing,an exact man.”
#+END_QUOTE


#+BEGIN_QUOTE
用几何学那样精确的方法去处理形而上学的神学，这就是笛卡儿提出的方法。”）
#+END_QUOTE


#+BEGIN_QUOTE
英国贵族就发起了一个“圈地运动”，凡是认为哪块农田是应该“改农为牧”的，就圈定下来改作牧场使用。
#+END_QUOTE


#+BEGIN_QUOTE
英国的工业最早起家于以羊毛为原料的手工纺织业，纺织业一发展，羊毛的供应量就得跟上去。因此，英国贵族就发起了一个“圈地运动”，凡是认为哪块农田是应该“改农为牧”的，就圈定下来改作牧场使用。
#+END_QUOTE


#+BEGIN_QUOTE
工业革命并不是某个确定的日子或一个孤立的事件就能概括得了的，它应是几个世纪以来科学技术
#+END_QUOTE


#+BEGIN_QUOTE
凡是我们做事情，都得有两个过程：一个叫做“build up”，就是把事物建起来。但如果建起来后就不管了，那也发展不了多少。因此，还得有一个“break through”，就是打破原先的事物格局，不断去撞击那层“天花板”——一旦突破那层 ceiling（天花板），就又上升到一个新境界了。——基本上欧洲的每个世纪都曾经过这两种过程，因此他们在各个领域，尤其是科学技术的发展上，都会经常有突破。
#+END_QUOTE


#+BEGIN_QUOTE
科学技术发展的前提，我觉得，应该是知识和掌握知识的人独立自主的活动。但这“独立”二字恰恰就是中国几千年来所欠缺的。
#+END_QUOTE


#+BEGIN_QUOTE
即中国缺乏独立的知识分子。它的发展，总要借助于外物的一点什么。
#+END_QUOTE


#+BEGIN_QUOTE
所以这第二点就是讲求方法，中国缺乏这种实验的实证的方法，在学术上讲就是没有“实证主义”
#+END_QUOTE


#+BEGIN_QUOTE
欧洲知识的流动是比较自由畅通的。
#+END_QUOTE


#+BEGIN_QUOTE
第二个印象不同的是我觉得欧洲实验上的发展。技术、科学的发展非常讲究方法，这方法就是实验，实验的方法，实证的方法。
#+END_QUOTE


#+BEGIN_QUOTE
西方的发明，inventions，是不断翻新的，
#+END_QUOTE


#+BEGIN_QUOTE
独立宣言”主要是针对英国的，是针对不列颠说的。所以它前一段是讲的基本人权问题，后一段完全是讲的（针对的）英王的各种各样的对美国干涉的行为、不公正的行为，等等。它是要宣布独立的。
#+END_QUOTE


#+BEGIN_QUOTE
独立宣言”主要是针对英国的，是针对不列颠说的。所以它前一段是讲的基本人权问题，后一段完全是讲的（针对的）英王的各种各样的对美国干涉的行为、不公正的行为，等等。它是要宣布独立的。一个是北美人民自己的愿望，一个是对英国的谴责，这是美国“独立宣言”的基本内容。而法
#+END_QUOTE


#+BEGIN_QUOTE
这条脉络是这样下来的：“大宪章”一洛克的思想一“权利法案”一“宗教宽容”一美国的“独立宣言”一法国的“人权宣言”。这条线我觉得代表了也反映了人类前进的方向。
#+END_QUOTE


#+BEGIN_QUOTE
本来殖民这个词没有什么贬义，比如说中国人在旧金山、洛杉矶有他的“华人区”。“华人区”当地人就管它叫 COLONY，叫做中国的“殖民地”，就是中国人在那地方住下来了，并不是中国人在那里建立了政治统治。
#+END_QUOTE


#+BEGIN_QUOTE
务实精神确实是美国精神的一个重要特点。第二就是它的开拓精神。
#+END_QUOTE


#+BEGIN_QUOTE
宗教精神并不一定是要相信上帝，而是要有利于社会。
#+END_QUOTE


#+BEGIN_QUOTE
欧美文明正在形成一个大西洋体系。随着北大西洋公约以及欧洲联盟的东扩，西方文明的影响还会扩大。但这
#+END_QUOTE


#+BEGIN_QUOTE
东方西方是比较相对的，从地理上来讲，一般来讲是东西半球，如果划界的话，欧亚大陆的西半部分，从乌拉尔山往西就是西方了。从文明上来讲，西方是希腊、罗马、基督教文明传下来的，东方却不是。
#+END_QUOTE


#+BEGIN_QUOTE
从 20 世纪初到 20 世纪末，欧洲成为各种政治理论的“实验室”。
#+END_QUOTE


#+BEGIN_QUOTE
认为原来的马克思主义在资本主义发展到一个新时代的时候应该加以修正，“修正主义”就是从这里来的，就是怎么“修正”马克思主义。
#+END_QUOTE


#+BEGIN_QUOTE
有个说法。你说他是个“说法”，我看也够了，但这个“说法”很重要，它反映了世界上一个趋同趋势，就是左和右的趋同，资本主义与社会民主主义的“趋同”。
#+END_QUOTE


#+BEGIN_QUOTE
有个说法。你说他是个“说法”，我看也够了，但这个“说法”很重要，它反映了世界上一个趋同趋势，就是左和右的趋同，资本主义与社会民主主义的“趋同”。但这个“趋同”主要是社会民主主义更加向资本主义“趋同”而不是相反。
#+END_QUOTE


#+BEGIN_QUOTE
上次讲了两个问题：苏联和东欧“社会主义阵营”的诞生、崩溃和欧洲的“社会民主主义”问题。
#+END_QUOTE


#+BEGIN_QUOTE
“了解欧洲”应当通其“三史”。一曰“欧洲通史”，“
#+END_QUOTE


#+BEGIN_QUOTE
欧洲“三史”（通史、思想史、艺文史）实际上是欧洲研究的“三科”。
#+END_QUOTE


#+BEGIN_QUOTE
我总记得贺麟先生的一句话，一方面要对中国的学问有全面系统的了解；另一方面又要对西学有全面系统的了解（原话记不得了）。这是一个非常高的要求，我自知没有能力做到，但虽不能至，心向往之。
#+END_QUOTE


#+BEGIN_QUOTE
欧洲文化传统以及这传统之通向今天的现代化、现代性，都涵盖在这“三史”、“三科”之中。
#+END_QUOTE


#+BEGIN_QUOTE
“法律限制我们的自由，只是为了使我们的自由可以和他人的自由以及全体的公共利益相一致。
#+END_QUOTE


#+BEGIN_QUOTE
“这种自由附带着这种权利，那就是把我们自由还不能处理的各种思想和疑惑公开付诸讨论，而且这样做时，不会被人污蔑为捣乱的有危害性的公民，这是人类理性原有的权利之一，
#+END_QUOTE


#+BEGIN_QUOTE
人人生而平等，他们都从他们的造物主那里被赋予了某些不可转让的权利，其中包括生命权、自由权和追求幸福的权利。为了保障这些权利，所以才在人们中间成立政府。”
#+END_QUOTE


#+BEGIN_QUOTE
我们中国的历史同西方的历史最大的不同就在于中国不变，西方总是在变。西方一个世纪一个世纪地在变，中国是一个朝代一个朝代地循环。
#+END_QUOTE


#+BEGIN_QUOTE
辛亥革命推翻了清朝，建立了民国，以皇族为统治中心的专制主义从现象上消失了。但是封建思想，它的精神并没有消灭掉，很顽强。存在了几千年的东西，沉淀成中国文化的一个部分。“
#+END_QUOTE


#+BEGIN_QUOTE
他讲这个时期是中国近代中外古今各种思潮各个学派大汇合的时期，是春秋战国以后又一次真正的“百家争鸣”。我是非常赞成他这个观点的。这个时期的文化名人很多很多，现在我们又在重印那时他们写的书，真是各种意见交汇，相同的，相反的，相互批评的，相互认同的，各种各样的思想交汇，很生动，很精彩。
#+END_QUOTE


#+BEGIN_QUOTE
大家看一看中国的近代文明史，就会发现开始了另外一个春秋战国以后几千年以来第二次真正的“百家争鸣”，就是五四以后，一直到 40 年代的二三十年这个时期。
#+END_QUOTE


#+BEGIN_QUOTE
这个局面在我看起来，很有点像欧洲 18 世纪的“启蒙运动”时期。
#+END_QUOTE


#+BEGIN_QUOTE
上个世纪的二三十年代里，我们的文化发展有些像启蒙运动，思想非常活跃，对未来的向往非常强烈，人文气息非常浓厚。但是可惜的是我们这个生动的局面夭折了，断档了。西方的启蒙运动和产业革命一起迎来的是 19 世纪的大发展；而我们那个所谓“启蒙运动”为什么夭折了呢？碰上了抗日战争，全民抗战，那些精英分子，知识分子差不多都集中
#+END_QUOTE


#+BEGIN_QUOTE
毛主席不是提倡“百花齐放，百家争鸣”吗！那些知识分子便傻乎乎地说，真的“鸣放”了，结果都很惨，更重要的是中国文化受到更惨重的摧残。到了“文革”的时候就更不要讲了。“文革”
#+END_QUOTE


#+BEGIN_QUOTE
个人遭遇不去说它，但是对中国文化来讲，“文化大革命”是大革文化的命啊，是对人的精神的戕害。这段历史，年轻人可能不太知道，因为你们相当多的人是在“文化大革命”以后出生的，现在也很少人再去讲它了。但是我们这一代人，听见“文革”这几个字，还是毛骨悚然，因为那是文化的大摧残，是对民族精神的大摧残。现在居然还有人有意让人“忘掉”它，甚至说不能全盘否定它！现在那几个“样板戏”又在唱，不但唱，而且叫它“红色经典”！王元化先生说，他一听到“样板戏”，马上就想起那时候对我们的迫害、镇压，血淋淋的事，数不胜数。
#+END_QUOTE


#+BEGIN_QUOTE
中国是古代啊，人家是近代了，所以非“赶”不可。“赶”就要把西方的东西学过来，拿过来它又不是自己的，不是在自己的土壤里生长的，因此是“稼接”的，稼接，老是稼接不准。所以就出现各种稀奇古怪的现象，各种困难，老是一步赶不上，步步赶不上，这不永远是一个“赶”的姿势吗？也幸亏我们有一个“赶”的姿势，如果没有这个姿势，我们这个民族就真没有前途
#+END_QUOTE


#+BEGIN_QUOTE
中国是古代啊，人家是近代了，所以非“赶”不可。“赶”就要把西方的东西学过来，拿过来它又不是自己的，不是在自己的土壤里生长的，因此是“稼接”的，稼接，老是稼接不准。所以就出现各种稀奇古怪的现象，各种困难，老是一步赶不上，步步赶不上，这不永远是一个“赶”的姿势吗？也幸亏我们有一个“赶”的姿势，如果没有这个姿势，我们这个民族就真没有前途了。
#+END_QUOTE


#+BEGIN_QUOTE
那么我们的“新文化”该是个什么样子的呢？我个人想不出来它该是个什么样子，但是我有一个感觉，就是我们要把西方文明里的精华的东西，而不是糟粕的东西，吸收进来，让它在我们的土壤里生根、成长，这样出来的“新文化”，不是“稼接”的，是我们中国自己的文化。我想属于中国自己的新的文化，应该既有科学，又有民主，同时保存了传统文化中的好的东西。有哪些好的东西呢？我提三条，一条是中国
#+END_QUOTE


#+BEGIN_QUOTE
那么我们的“新文化”该是个什么样子的呢？我个人想不出来它该是个什么样子，但是我有一个感觉，就是我们要把西方文明里的精华的东西，而不是糟粕的东西，吸收进来，让它在我们的土壤里生根、成长，这样出来的“新文化”，不是“稼接”的，是我们中国自己的文化。我想属于中国自己的新的文化，应该既有科学，又有民主，同时保存了传统文化中的好的东西。
#+END_QUOTE


#+BEGIN_QUOTE
现在对教育的投入太低。我有个想法，可能是无稽之谈！我觉得应该收“教育税”，让那些董事长，大公司啊，交教育税，不要去给明星送房子，要向他们征收强制性的教育税，鼓励私人办学，私人办非盈利的学校。在西方，私人学校比公立学校办得好，有特性。还应该多办成人学校、老年学校。
#+END_QUOTE


#+BEGIN_QUOTE
现在对教育的投入太低。我有个想法，可能是无稽之谈！我觉得应该收“教育税”，让那些董事长，大公司啊，交教育税，不要去给明星送房子，要向他们征收强制性的教育税，鼓励私人办学，私人办非盈利的学校。在西方，私人学校比公立学校办得好，有特性。
#+END_QUOTE


#+BEGIN_QUOTE
一句话叫，只争朝夕，要从现在起，从人人做起全民办教育，全社会办教育。第二不能性急，这是几个世纪的事情。
#+END_QUOTE


#+BEGIN_QUOTE
教育本身成了传统，无论发生了什么，教育都是第一位的大事。办教育，不要再搞形式主义，办教育需要的是“宁静致远”，不是搞热热闹闹、花花哨哨，应该恢复到蔡元培那时候的“通识教育”上去。
#+END_QUOTE


#+BEGIN_QUOTE
教育问题，我说了半天的空话，无非两句话，一句话叫，只争朝夕，要从现在起，从人人做起全民办教育，全社会办教育。第二不能性急，这是几个世纪的事情。
#+END_QUOTE


#+BEGIN_QUOTE
或许有人说读书没用，读书以后就全忘掉了。但在我看来，那实际上不是全忘掉了，而是变成了营养。你不要怕忘掉了什么，关键是看你能消化多少。多读书总是没坏处的，大家就应该趁着年轻多读一些书。
#+END_QUOTE


#+BEGIN_QUOTE
中国文化比较讲“情”，故注意人际关系、等级关系；而西方文化比较讲“理”，故求真知、提倡大胆怀疑。我常说：中国文化情重于理，西方文化理重于情。
#+END_QUOTE
