#+TITLE:  [笔记]贫穷的本质：我们为什么摆脱不了贫穷
#+AUTHOR: Yang Yingchao
#+DATE:   2024-04-16
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:  align nodlcheck oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+LANGUAGE: en
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :tag1:tag2:note:ireader:



#+BEGIN_QUOTE
自打贫穷一出现，我们就产生了某种以约定俗成的方式来贬低穷人的冲动。
#+END_QUOTE


#+BEGIN_QUOTE
我们所关注的焦点是世界上最贫穷的人，就全球穷人最多的 50 个国家来说，其平均贫穷线为每人每天 16 印度卢比。2各国政府将生活费低于这一水平的人定位为贫穷状态。根据当前的汇率标准，16 卢比相当于 36 美分，
#+END_QUOTE


#+BEGIN_QUOTE
每天 99 美分的生活意味着，你接收信息的渠道也会受限——报纸、电视和书籍都要花钱来买。因此，你常常会对世界上其他人得到的特定信息一无所知。
#+END_QUOTE


#+BEGIN_QUOTE
学生们愿意为了罗西娅而承担一点儿责任，但在面对广泛的全球性问题时，他们就不免有些
#+END_QUOTE


#+BEGIN_QUOTE
学生们愿意为了罗西娅而承担一点儿责任，但在面对广泛的全球性问题时，他们就不免有些泄气了。
#+END_QUOTE


#+BEGIN_QUOTE
贫穷并不仅仅意味着缺钱，它会使人丧失挖掘自身潜力的能力。
#+END_QUOTE


#+BEGIN_QUOTE
真正有用的方式是从实际问题的角度去思考，这样就可以有针对性地找出解决具体问题的方法，
#+END_QUOTE


#+BEGIN_QUOTE
那些自己花钱购买蚊帐的人可能都比较富有，受过良好的教育，而且知道自己为什么需要这种蚊帐；而那些免费得到蚊帐的人可能是因为贫穷，才会被某家非政府组织选中。不过，情况也可能恰恰相反：免费得到蚊帐的人社会关系优越，而穷人由于封闭只好以全价购买。无论是哪种情况，我们都无法从他们使用蚊帐的方式上得出任何结论。
#+END_QUOTE


#+BEGIN_QUOTE
对于几乎无钱可投的人来说，一旦收入或财富迅速增长的范围受限，那么他就会掉入“贫穷陷阱”；但对于有能力投入的人来说，这一范围就会极大地扩展。
#+END_QUOTE


#+BEGIN_QUOTE
如果没有大量的原始投资助其解决这些地方性问题，这些国家很难提高自己的生产力。然而，这些国家却因为贫穷，无法支付投资回报——这就是经济学家们所谓的“贫穷陷阱”。
#+END_QUOTE


#+BEGIN_QUOTE
这条 S 形曲线就是“贫穷陷阱”的来源。
#+END_QUOTE
