#+TITLE:  [笔记]中信鹦鹉螺极简科普套装
#+AUTHOR: Yang Yingchao
#+DATE:   2024-04-16
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:  align nodlcheck oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+LANGUAGE: en
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :tag1:tag2:note:ireader:



#+BEGIN_QUOTE
要搞清楚一门学科的本质，认真研究该学科的开创者的想法是一条可行的路径。
#+END_QUOTE


#+BEGIN_QUOTE
1522 年，有人提议改进法定路德（杆）的确定方法。如图 1–1 所示，当人们从教堂鱼贯而出时，将排成一列的 16 个人的脚的总长度设定为法定路德。[4]从图 1–1 可以看出，这些人的脚长度不一，但通过一群人来设定这个长度单位具有明显的平均效应，因此很多人接受了这个方法。不过，当时似乎还没有人明确提出平均数这个概念。
#+END_QUOTE


#+BEGIN_QUOTE
期望值是测算价值的正确方法。
#+END_QUOTE


#+BEGIN_QUOTE
阿布斯诺特引入了在确定的环境中如何正确认识概率的问题。他给出的答案是：概率是人类无知的产物。
#+END_QUOTE


#+BEGIN_QUOTE
抛硬币是一种有规律可循的物理现象，而不是随机的！为了证明这一点，我们请物理系为我们制造了一台抛硬币机。如图 1–3 所示，在弹簧被松开之后，停留在弹簧上的硬币一边翻转，一边弹起，然后落在一只杯子里。因为弹簧的力量是受控的，所以硬币落下后总是同一面朝上。这个结果令人发自内心地感到不安（本书的两名作者也不例外），魔术师和不诚实的赌徒（包括本书的一位作者）都具有这样的技能。
#+END_QUOTE


#+BEGIN_QUOTE
协约国对奥斯曼帝国领土的划分忽略了种族、宗派和部族差异，因此衍生了一系列严重后果。
#+END_QUOTE


#+BEGIN_QUOTE
杨振宁先生说过：物理做到极致，就会诉诸哲学；哲学做到极致，就会诉诸宗教。
#+END_QUOTE


#+BEGIN_QUOTE
“没有矛盾和佯谬，就不可能有科学的进步。绚丽的思想火花往往闪现在两个同时并存的矛盾的碰撞切磋之中。因此我们教学生、学科学，就得让学生有‘危机感’，学生才觉得自己有用武之地。否则，学生只会看见物理学是一座完美无缺的大厦，却没有问题，还研究什么呢？
#+END_QUOTE


#+BEGIN_QUOTE
量子力学也能够用于宏观世界，不过，在处理上述宏观问题时，使用量子力学方法会令计算过程极为烦琐，而运用更为简单方便的牛顿三大定律也能达到我们需要的精度。正所谓“杀鸡何须用牛刀”，所以我们刚才强调，量子力学是大多用于微观世界的物理规律。
#+END_QUOTE


#+BEGIN_QUOTE
二象性就是说，我们从不同的角度观察事物会得到不同的结果。
#+END_QUOTE


#+BEGIN_QUOTE
那是 1926 年玻恩给出的概率解释。他假设这个波函数的平方代表电子在空间某点出现的概率，也就是说，量子力学中的电子不像经典粒子那样有决定性的确定轨道，而是随机地出现于空间中某个点。不过，电子出现在特定位置的概率是一定的，是由确定性的方程解出的波函数决定的。也就是说，波函数是描述电子现身位置的“概率幅”。
#+END_QUOTE


#+BEGIN_QUOTE
而微观电子就不一样了：它在被观察之前的状态并无定论，是“既朝上又朝下”的叠加状态，直到我们去测量它，叠加状态才坍缩成一个确定的本征态。
#+END_QUOTE


#+BEGIN_QUOTE
量子理论认为：如果没有揭开盖子进行观察，薛定谔的猫的状态是“死”与“活”的叠加。
#+END_QUOTE


#+BEGIN_QUOTE
经典物理认为，宇宙中不存在真正的随机性。那些貌似随机的现象，如果从更深一层的结构和理论来看或计算，都能得到决定性的结果。关于所谓“更深一层”的详细信息，我们可以把它们统称为我们不知道的、尚未发现的“隐变量”，一旦我们找出了这些隐藏着的变量，随机性就不存在了。或者说，经典物理认为，隐变量是随机性的来源。
#+END_QUOTE


#+BEGIN_QUOTE
玻色子是自旋为整数的粒子，比如光子的自旋为 1。另一类称为费米子的粒子，自旋为半整数，
#+END_QUOTE


#+BEGIN_QUOTE
多个玻色子可以同时占据同一个量子态，而两个费米子不能同时占据同一个量子态，这是玻色子与费米子之间一个很重要的区别。
#+END_QUOTE


#+BEGIN_QUOTE
因为玻色子可以同居一室，所以有时大家会拼命挤到同一个状态。比如，光子就是一种玻色子，许多光子可以处于相同的能级，所以，在激光器中，我们才能让所有的光子都有相同频率、相位、前进方向，形成超高强度的光束。
#+END_QUOTE


#+BEGIN_QUOTE
泡利不相容原理”。
#+END_QUOTE


#+BEGIN_QUOTE
经典的玻尔兹曼统计、玻色–爱因斯坦统计和费米–狄拉克统计，分别适用于三种不同性质的微观粒子：经典粒子、玻色子和费米子。
#+END_QUOTE


#+BEGIN_QUOTE
巨磁阻效应指磁性材料的电阻率在外加磁场后会产生很大变化的现象，它来自电子的自旋，
#+END_QUOTE


#+BEGIN_QUOTE
别轻易相信理论家们构建的各种各样的漂亮理论，你要时刻记得回过头来，看看实验中的那些原始数据。”
#+END_QUOTE


#+BEGIN_QUOTE
量子系统一次计算可以得到 8 个结果，相当于 8 个经典计算器同时进行运算，从某种意义上讲，相当于把计算速度提高到 8 倍。 然而，量子计算的结果不能全部输出，因为一旦输出，量子叠加态就会坍缩成 8 个数值中的一个，再也找不回其他数值了。不过，如果我们暂时不输出，这 8 个数可以储存在计算机里，继续进行之后的运算。
#+END_QUOTE


#+BEGIN_QUOTE
哲学介于科学和神学之间，旨在运用人类的理性对一些利用现有知识尚不确定的领域进行思考。
#+END_QUOTE
