:PROPERTIES:
:ID:       a93b0a39-8289-4438-ab49-e9fd511b4457
:END:
#+TITLE: 十一月阅读总结
#+AUTHOR: Yang,Ying-chao
#+DATE:   2025-12-06
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:  oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :wechat:wexin:

* [[file:~/Work/MyNotes/org/2025/10/\[笔记\]青山-会说话的肘子.org][青山]]

看个网文放松一下。《青山》的作者是“会说话的肘子”，之前看过他的《大王饶命》和《第一序列》，《夜的命名术》
似乎是看过一部分，没看完。这个作者文笔在一众网文作者中属于靠前的，而且不同于一般作者之处在于，
也许是因为他自己存在某种信念，他笔下的人物，始终有自己的某种坚持，于黑暗中仰望光明的一种坚持，从《大王饶命》中吕树，到《第一序列》中的任小粟，
再到《青山》中的陈迹，均是如此。

《青山》故事有点庞大，有几个大坑至今没有填完，貌似不能一两句话概之。。。

啊，题外话。《第一序列》的主人公叫任小粟，任小粟的爹叫任禾。而作者本人真名就叫任禾，作者的儿子，真叫任小粟。。。

* [[file:~/Work/MyNotes/org/2025/11/\[笔记\]尘埃落定_十五周年纪念版-阿来.org][尘埃落定]]

重读了一下阿来的 《尘埃落定》。上一次读这本书的时候还在上高二，恍惚间二十四年已飘然流逝，物是人非，重读起来，
已然完全忘记了当时的感想。

这本书篇幅并不算太长，通过土司的傻儿子的视角，描写了西藏土司制度瓦解的过程，一直到最后新制度确立，“尘埃落定”：

#+BEGIN_QUOTE md5: 06a25a303217739cfbe81f8ddf1fb531
他说，好多土司都在诅咒这个镇子。 他们认为是这个镇子使他们的身体有病，并且腐烂。谁见过人活着就开始腐烂？过去，
人都是死去后，灵魂离开之后才开始腐烂的，但现在，他们还活着，身体就开始从用来传宗接代，
也用来使自己快乐的那个地方开始腐烂了。 我问过书记官，这个镇子是不是真该被诅咒。

他的回答是，并不是所有到过这个镇子的人身体都腐烂了。他说，跟这个镇子不般配的人才会腐烂。

前僧人，现在的书记官翁波意西说，凡是有东西腐烂的地方都会有新的东西生长。
#+END_QUOTE

#+BEGIN_QUOTE md5: 28a2f2445c29cf90fa81d38e5d55a5aa
我看见麦其土司的精灵已经变成一股旋风飞到天上，剩下的尘埃落下来，融入大地。我的时候就要到了。我当了一辈子傻子，
现在，我知道自己不是傻子，也不是聪明人，不过是在土司制度将要完结的时候到这片奇异的土地上来走了一遭。 是的，
上天叫我看见，叫我听见，叫我置身其中，又叫我超然物外。上天是为了这个目的，才让我看起来像个傻子的。
  #+END_QUOTE

* [[file:~/Work/MyNotes/org/2025/11/\[笔记\]横空出世_核物理与原子弹的诞生-\[美\]-理查德·罗兹;江向东;廖湘彧.org][横空出世]]

没看完，翻译的有点差，可读性不太强。但看前面的内容，也挺让人感慨的，西方的科学精神与科学传统，确实促进科学的发展。
对比中国的封闭与敝帚自珍带来的衰弱，令人扼腕叹息。
