:PROPERTIES:
:ID:       3fd3c27c-82d3-4889-bc6b-cb1eaa207da7
:END:
#+TITLE: [笔记]包法利夫人
#+AUTHOR: Yang,Ying-chao
#+DATE:   2024-05-09
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:  align nodlcheck oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+LANGUAGE: en
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :baofalifuren:note:ireader:



** 译本序

# note_md5: 79030344de51ae2b7558e7cabfd0449a
#+BEGIN_QUOTE
福楼拜不是一般意义上的小说家，他自称，他也确实是艺术家，文字的艺术家。他视文字、文学创作为生命，每一部作品，每一章，每一
节，每一句，都是呕心沥血的结果。
#+END_QUOTE


# note_md5: 27cdb7e0020fa97698c36bf6efd7d613
#+BEGIN_QUOTE
小说的形式和风格比其内容更加重要。他写得很慢，很苦，反复修改，要求每一个细节都来自仔细的观察或亲身体验，要求文字具有音乐
的节奏。（“一句好的散文应该同一句好诗一样，是不可改动的，是同样有节奏，同样响亮的。”
#+END_QUOTE


# note_md5: 65dedc1cfbae4f79ead9fa6adcd3cb84
#+BEGIN_QUOTE
城像圆剧场，一步比一步低，雾气笼罩，直到过了桥，才乱纷纷展开。再过去又是旷野，形象单调，越远越高，最后碰上灰天的模糊的基
线。全部风景，这样从高望去，平平静静，像煞一幅画。停锚的船只，堆在一个角落；河顺着绿岭弯来弯去；长方形的岛屿，如同几条大
黑鱼，停在水面，一动不动。工厂的烟筒冒出大团棕色的烟，随风飘散。教堂的尖顶突破浓雾，清越的钟声有冶铸厂的轰隆轰隆的响声伴
奏。马路的枯树，站在房屋中间，好像成堆的紫色荆棘一样。雨洗过的屋顶，由于市区有高有低，光色参差不齐。有时候，吹来一阵劲风，
浮云漂向圣·卡特琳岭，仿佛空气凝成波涛，冲击岸边绝崖，先是气势汹汹，转瞬就又销声匿迹了。
#+END_QUOTE



** 第一部

# note_md5: 5d76250b2216f3074b43aed5d957ce92
#+BEGIN_QUOTE
他什么也不懂；上课像腾云驾雾，听了也白听。但他还是很用功，一本本笔记装订成册，一堂课也不缺席，一次出诊也不拉下。他当天的
事当天了，却好似一匹拉磨的马，蒙住双眼绕着碾磨转圈，不知道磨的是什么东西。
#+END_QUOTE



** 第七章

# note_md5: 169a0002b0e502095235d290a6cb525b
#+BEGIN_QUOTE
夏尔对爱玛的恩爱，在她眼里就是对她的母爱的辜负，就是对她的尊严的亵渎；她闷不作声地看着儿子日子过得挺和美，犹如破了产的人
呆在窗口，瞧着人家在自己的老屋里围坐着吃饭。
#+END_QUOTE



** 第二部

# note_md5: 4f7e807cd734ea140d81831ac54714d9
#+BEGIN_QUOTE
屋顶的茅草往下垂，犹如皮帽翻下盖住眼睛，把低矮的窗户遮去近三分之一，窗玻璃厚厚的，中间凸起，就像酒瓶底儿。石灰墙面上，沿
斜角嵌着一根根黑色明梁，不时还有细瘦的梨树攀在上面，底层房门外加了扇矮矮的木栅门，小鸡能到门口啄食苹果酒泡过的面包屑，却
进不了屋子。
#+END_QUOTE



** 第三章

# note_md5: 4c64fc44de5a675b0db9c7a42467f21a
#+BEGIN_QUOTE
他俩沿着河岸走回永镇。一到夏季，陡峭的河岸就变宽了，看得见花园围墙的脚跟，沿墙有石阶通到水边。河水悄没声儿地流过，乍看上
去湍急而清凉；纤长的水草顺流偃伏，宛如随手扔在河里的绿发，平摊在清澈的水面上。灯心草的尖端或睡莲的叶片上，不时有个细脚伶
仃的虫子爬过或小憩。一绺绺阳光穿过水波泛起的气泡，蓝莹莹的小气泡一路躜赶一路迸碎。修过枝的老柳树在水中映出灰蒙蒙的倒影；
放眼望去，原野显得分外空旷
#+END_QUOTE



** 第五章

# note_md5: dc3629dbe750dc911c3b65236c24c00a
#+BEGIN_QUOTE
她那么忧郁，又那么宁静，那么动人，那么矜持，在她身边会让人感到一种玉洁冰清的美，犹如置身于教堂之中，透着大理石寒意的花香
叫人嗅着打颤。
#+END_QUOTE



** 第六章

# note_md5: e2568f6f5f2cee70b3c829787e4c9041
#+BEGIN_QUOTE
正是四月初的天气，报春花绽开了蓓蕾；一阵和风拂过拾掇过的花圃，各家的花园就像女眷一样，仿佛都披上了盛装来迎接夏天的节日。
透过棚架眺望四周，只见原野上的那条河，若隐若现，一路迤逦在草地上勾勒出它的身影。暮霭弥漫在没有叶片的杨树枝丫之间，给它们
的轮廓染上朦朦胧胧的紫色，即便给枝丫装点上一层薄纱，也不会比这更淡雅、更透明。远处，成群的牲畜在行走；既听不见它们的脚步
声，也听不见它们的叫声；而教堂的钟声依然在回荡，显得柔和而凄婉。
#+END_QUOTE


# note_md5: ae07fd24ed6b2997d459c19953e460a3
#+BEGIN_QUOTE
从钟楼垂下的粗绳，直拖到地面，随着粗绳振幅的减小，钟声也渐渐变弱了。嘤嘤而鸣的燕群，骤然划破天空，急速飞回檐瓦下棕黄的窝
巢。教堂深处，亮着一盏灯，也就是说有根细细的灯芯，在悬空的玻璃罩里发出黯淡的光。远远望去，亮光如豆，在灯油上方颤悠。一绺
长长的阳光射进整座中殿，那些侧道和墙角就显得更加昏暗了。
#+END_QUOTE


# note_md5: cb1b9c5885d7ade48199623abae57eb9
#+BEGIN_QUOTE
圣保罗在传道时说：“我们进入神的国，必须经历许多艰难。”
#+END_QUOTE



** 第七章

# note_md5: 9e0823feb7f060908885d2425971f875
#+BEGIN_QUOTE
周围的一切仿佛都笼罩着凄迷的雾气，它隐隐绰绰地在物件的外表上浮动；悲伤涌进她的心扉，带着哀怨的呻吟，有如冬天的风吹进废弃
的城堡。那是一种对逝去的时光怅然的梦寻，是在某事无可挽回地有了结局时感到的疲惫，总之，这就是习惯的节律一旦中断、持续的震
颤一旦停止时，您所会感到的那种痛苦。
#+END_QUOTE



** 第十章

# note_md5: cd4f1f8699be525051169ff08eb0bc12
#+BEGIN_QUOTE
她手里拿着这张糙纸，冥想了几分钟。信上拼写错误比比皆是，可爱玛感受得到那份拳拳的爱心，从字里行间流露出来，犹如母鸡在棘篱
后面探出身来咕咕地叫。信纸用炉灰吸过墨水，有些灰色粉末从纸上滑到她的裙上，她眼前浮现出父亲朝炉膛弯下身去拿火钳的情景。当
年待在他身边，坐在壁炉跟前的矮凳上，炉膛里芦苇劈劈啪啪烧得正旺，她拿根细棍搁进去看它烧，这些都是那么遥远的事了！......她
回想起那些红霞满天的夏日傍晚。小马驹一见旁边有人走过，就欢快地嘶鸣，奔到东，奔到西......她的窗前有个蜂箱，蜜蜂在阳光中嗡
嗡飞舞，有时猛不丁撞到玻璃窗上，像颗金色的弹子似的弹回去。那时候多么幸福！多么自由！那是满怀希望、沉湎在幻想中的年月！
#+END_QUOTE



** 第十一章

# note_md5: ba82863b7a84764b990e1f059204a966
#+BEGIN_QUOTE
他的脑子里乱纷纷地闪过种种假设，思绪在这些假设上颠簸晃荡，犹如一只空桶在海上随波逐流，翻来滚去。
#+END_QUOTE



** 第十二章

# note_md5: 423a98e590d75ebfd50b18db3a5fd087
#+BEGIN_QUOTE
一轮浑圆的月亮，红嫣嫣的，从草场尽头的地面上升起。它在杨树枝丫间迅速上行，不时被密枝繁叶所遮蔽，宛如在一幅剜了好些洞的黑
色幕布后穿过。随后它又现了出来，显得分外皎洁，把一片清辉洒向寥廓的天空；而后，它冉冉穿行在夜空，圆圆的光影投射在河面上，
变成无数波光粼粼的小星星，银辉宛似披满闪亮鳞片的水蛇，蜿蜒迤逦钻向河底。这又像一盏巨大的枝形烛台，千万滴熔化的钻石连绵不
断地往下流淌。
#+END_QUOTE



** 第十五章

# note_md5: d554bc33f88706794acb303f6eab28b9
#+BEGIN_QUOTE
凄哀的歌声，在低音提琴的伴奏下拖着长腔，犹如海难幸存者在风雨交加、波涛汹涌的海面上的哀号，占据了爱玛的全部身心
#+END_QUOTE



** 第十一章

# note_md5: e5d5d496a29e2cabad13aeefd3c9eff2
#+BEGIN_QUOTE
说来奇怪，包法利虽说不停地思念着爱玛，她的形象居然却想不起来了；他绝望地感到这个形象在从他的记忆中逸出，他拼命想留也留不
住。但他每夜都梦见她；总是同样的梦：他离她愈来愈近；可就在他要抱紧她的当口，她从他的怀里跌落下去，犹如化成了齑粉。
#+END_QUOTE

