:PROPERTIES:
:ID:       c0ee7700-1c7b-45cb-82a8-8ac3df5f31ad
:END:
#+TITLE: [笔记]天朝的崩溃
#+AUTHOR: Yang,Ying-chao
#+DATE:   2024-05-09
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:  align nodlcheck oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+LANGUAGE: en
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :tianzhaodebe:note:ireader:



** 绪论　由琦善卖国而想到的

# note_md5: b965fc6b249ba4db76e0f5ace963d965
#+BEGIN_QUOTE
由于文化背景的不同，英国最先进的事物，经过儒家教义的折光，顿时变为最荒谬不堪的东西。君主立宪，在皇权至上面前，有如大臣擅
权；经商贸易，在农本主义面前，显为舍本求末；追逐利润，在性理名教面前，只是小人之举；至于女王主位、男女不辨，更是牝鸡司晨
之类的“夷俗”；即便令人兴叹的西方器物（钟表、玻璃、呢羽等），享用赏玩收藏之余，仍可斥之为“坏人心术”的“奇技淫巧”。
#+END_QUOTE



** 二　琦善卖国罪名之否定

# note_md5: 85d85c22d5c851343a74250815176eb6
#+BEGIN_QUOTE
核准历史事实，有关琦善卖国的四项罪名，无一可以成立。然而，我们若放开那些对琦善的具体指责，从更宏观的角度看问题，不难看出，
琦善卖国说的根由在于：他不主张用武力对抗的方式，来制止英国的军事侵略，而企图用妥协的方式，达到中英和解。于是，“妥协”即被
目为“投降”，而“投降”又被提升至“卖国”。帽子正是如此一顶顶地戴到了琦善的头上。
#+END_QUOTE



** 三　琦善卖国说形成的原因

# note_md5: dec43e4c975ff05a5c3c2f68ec2978ab
#+BEGIN_QUOTE
在皇权至上的社会中，天子被说成至圣至明，不容许也不“应该”犯任何错误。尽管皇帝握有近乎无限的权力，因而对一切事件均应该负有
程度不一的责任；但是，当时的人们对政治的批判，最多只能到大臣一级。由此而产生了中国传统史学、哲学中的“奸臣模式”：“奸臣”欺
蒙君主，滥用职权，结党营私，施横作恶，致使国运败落；一旦除去“奸臣”，圣明重开，万众欢腾。这一类模式使皇帝避免了直接承担坏
事的责任，至多不过是用人不周不察，而让“奸臣”去承担责任，充当替罪羊。若非如此，将会直接批判到皇帝。这就冲犯了儒家的“礼”，
是士人学子们不会也不愿去做的。
#+END_QUOTE


# note_md5: 5254ef439e3374b0a20b759c0fc256cf
#+BEGIN_QUOTE
忠奸理论和“奸臣模式”，并非是鸦片战争史独有的现象，而是中国传统史学的常用方法。正是它具有掩护君主、掩护道统的特殊功能，因
而屡屡被官僚士子们用来解释那些他们不能解释或不愿解释的历史现象。这种理论和模式，经过他们长久的宣教，成为老百姓耳熟能详、
最易接受的历史分析法，并在今天仍有其影响力。
#+END_QUOTE



** 四　本书的主旨

# note_md5: a66492b177cefa2a39cbeb14a1332907
#+BEGIN_QUOTE
历史学最基本的价值，就在于提供错误，即失败的教训。所谓“以史为鉴”，正是面对错误。从这个意义上讲，一个民族从失败中学到的东
西，远远超过他们胜利时的收获。胜利使人兴奋，失败使人沉思。一个沉思着的民族往往要比兴奋中的民族更有力量。历史学本应当提供
这种力量。
#+END_QUOTE


# note_md5: 8a3b19ed5a0b385770dedd76b424e737
#+BEGIN_QUOTE
一个民族对自己历史的自我批判，正是它避免重蹈历史覆辙的坚实保证。
#+END_QUOTE



** 三　士兵与军官

# note_md5: 94e58d91aec865e1623386124bc93b11
#+BEGIN_QUOTE
威力无比的社会腐蚀剂，当军队将财神像奉为战旗时，腐败已不可逆转
#+END_QUOTE


# note_md5: f821a04f9ffe7fc117bc4a273de54b50
#+BEGIN_QUOTE
世界上可以有一万种罪恶而安然无事，唯有一种足以致命：执法犯法。
#+END_QUOTE


# note_md5: 358db25044c43d7556e3b640ab0bfd4b
#+BEGIN_QUOTE
以上的描写，颇有专门暴露黑暗之嫌。其实，我为了研究结论的公允，曾千百度地寻找光明，但光明始终远我而去。我不能不得出这样的
结论：鸦片战争时期的清军，本是一个难得见到光明的黑暗世界。
#+END_QUOTE



** 第 2 章　骤然而至的战争

# note_md5: f81dd3d06b4da61164a44ba84daa9b16
#+BEGIN_QUOTE
因此，他们主张加强查处贩烟、售烟。因为贩运、销售的行为可以解释为过境性、偶然性的，捉住一个便立下一功，捉不住也无责任可究
#+END_QUOTE


# note_md5: 8bc54b8196f906bc5f82c419bd33dd64
#+BEGIN_QUOTE
更聪明的方法，就是将禁烟的责任推向海口，内地官员自可摆脱干系：能够推到广东则更妙，禁烟就成了广东一省官员的事务，其余省份
自可乐得轻松。
#+END_QUOTE


# note_md5: 178dbe36cdfcc786f8128133027320a5
#+BEGIN_QUOTE
禁烟是禁英国等国贩运之烟，然而，各地官员在奏折中竟全然不提英国可能对此事作出的反应。这说明清朝的上下当时还未把禁烟与中英
关系联系起来看，暴露出他们对鸦片走私情况的懵懂，对国际事务的无知。
#+END_QUOTE



** 二　林则徐的禁烟活动及其评论

# note_md5: 32afff8af0214b151b6725e0543ab793
#+BEGIN_QUOTE
同样是围绕毒品案件，英国和美国的态度在相隔一个半世纪之后，却是如此的不同。不管今天的人们对这两次战争持何种看法，作何种评
价，但是，贯穿在两次战争之中始终未变的原则是，国际政治中的强权。
#+END_QUOTE



** 三　林则徐的敌情判断

# note_md5: 7ed244b98b3447452061d026442fd790
#+BEGIN_QUOTE
义律代表鸦片商人缴出鸦片，并不意味着将遵循中国的法令，而是将鸦片商人的货物变为英国政府的财产，图谋以此为由向中国发动战争。
#+END_QUOTE



** 四　林则徐的制敌方略

# note_md5: 6675756d958c4da903a4c88460e75bf8
#+BEGIN_QUOTE
处在失败中的人们，找不到胜利的迹象，最容易产生某种希望。林则徐就是这种希望。而且，局势越危急，战争越失利，这种希望之火就
越放光芒。
#+END_QUOTE



** 第 3 章　“剿”“抚”“剿”的回旋

# note_md5: 67aec7e93a8c34d06c80f2a10fe44951
#+BEGIN_QUOTE
。以贸易为本市场经济的英国，从本国的情势着眼，企图以此扼住中国经济的喉管，哪里会想到以农业为本自然经济的中国对此基本上没
有什么反应。
#+END_QUOTE


# note_md5: 6aae8477ee7545281a362a7c62b11771
#+BEGIN_QUOTE
道光帝因此不可能知道南中国的主要海口已经被英军封锁，还兴致勃勃地经常与臣下讨论是否实行封海政策。不过，英军这种以破坏对方
经济为目的的战法，未收到期望的效果后，他们也放弃了
#+END_QUOTE



** 二　“剿”“抚”之变

# note_md5: 0383b56089ff7fba3539ef41da3e4e3f
#+BEGIN_QUOTE
尽管每一次调动道光帝都有充足的理由，但毕竟缺乏通盘的考虑。他的那种头痛医头、脚痛医脚的一道道圣旨，是其目光短浅所限。他从
来就没有一种远距离、宽视野的眼光。
#+END_QUOTE



** 三　伊里布与浙江停战

# note_md5: 02612680ceb92bd6c9f3aba933152275
#+BEGIN_QUOTE
从江苏吴淞到浙江镇海，由两江总督而钦差大臣，伊里布不再表现出先前的精明、果敢和自信。在英军的肆横面前，他似乎已经看出武力
收复定海的任务不可能完成，但又不敢明言直陈。于是，举措从实在归于空虚，言词由明确变为含混。
#+END_QUOTE


# note_md5: 8e232222e9d20363d2c31bece562b625
#+BEGIN_QUOTE
我们办事，必令你们下得去，亦必令你们回得国，复得命。你们办事须教我们下得去，教我们奏得大皇帝，教我们大皇帝下得去。
#+END_QUOTE



** 四　琦善与广东谈判

# note_md5: 6f389029b0796fb2ce549dbdf183c3e0
#+BEGIN_QUOTE
他对中国的国情颇为了解，善于用曲折的手段达到目的，得寸进尺。
#+END_QUOTE



** 第 4 章　广州的“战局”

# note_md5: 6348e6377f1524aa274634ae67b8e2e7
#+BEGIN_QUOTE
大黄滘炮台守军将领在临战前一天，竟派人与英军商议：“你也不要放炮，我也不要放炮，谁都不要放炮。我可以放六次没有炮弹的炮，
给皇帝留面子，然后走掉。”[21
#+END_QUOTE


# note_md5: cbcb67f837b4a6feec1ca57157eb4b5b
#+BEGIN_QUOTE
与琦善相比，杨芳的违旨行为不知严重多少倍。琦善奉旨主“抚”，始终不肯与英人签订条约。杨芳奉旨主“剿”，却擅与英人达成停战协定。
可杨芳的结局又不知好过琦善多少倍。这里面的关键，在于如何上奏。
#+END_QUOTE

