:PROPERTIES:
:ID:       b023a3cf-7022-4bdc-9373-47d2721d9202
:END:
#+TITLE: 彼得·海斯勒;李雪顺
#+AUTHOR: Yang,Ying-chao
#+DATE:   2025-10-10
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:  oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :笔记]江城-[美:jiangcheng:note:ireader:unwashed:

* Unwashed Entries                                                  :noexport:

- 69-69, 标注, 2025 年 10 月 5 日星期日 下午 5:23:11
  #+BEGIN_QUOTE md5: e7536fa4a94959f2accf6cd5a49c1495
  我觉得那是我二十几岁时写得比较好的作品之一，但我发觉还是有点差强人意。
  #+END_QUOTE

- 257-259, 标注, 2025 年 10 月 5 日星期日 下午 6:37:52
  #+BEGIN_QUOTE md5: 3b25533603869bca5c238d15142219fe
  我经常听到类似的说法，这表明中国人对待自然环境的态度与外国人截然不同。当我看到那些呈梯状的小山包，
  注意的是人如何改变土地，把它变成了缀满令人炫目的石阶的水稻梯田；而中国人看到的是人，关注的是土地怎样改变了人。
  #+END_QUOTE

- 554-558, 标注, 2025 年 10 月 6 日星期一 上午 9:32:59
  #+BEGIN_QUOTE md5: d1585553a828bbe80492e957d49daf7b
  今天，当我们用自己的眼光去看待那段岁月时，会觉得我们父母的思想和行为都有些盲目和狂热。但是，
  如果我们客观地看待那一段时期，我想我们应该、也能够理解他们。每一代人都有他们各自的悲欢。对年轻的一代人来说，
  重要的是去理解而不是批评责备。我们的上一辈人是不幸的；他们没有好的机会和环境去实现他们的价值。但是，
  他们的精神，以及对祖国的热爱为我们树立了好榜样。
  #+END_QUOTE

- 633-635, 标注, 2025 年 10 月 7 日星期二 上午 9:43:34
  #+BEGIN_QUOTE md5: 5f2bba1d21c7719b4b11db93dcdda1c6
  这座城市与她所在的土地大不相同，差别在于，除了一小片老城区，毫无历史感。到四川的乡下游玩就是去感受历史，
  去感受那些通过劳动改造大地的岁月，去感受人类世世代代以来和土地相互较劲的过程。但是，
  四川的城市总是让人找不到时间感。
  #+END_QUOTE

- 633-636, 标注, 2025 年 10 月 7 日星期二 上午 9:43:40
  #+BEGIN_QUOTE md5: d1d43bf26dd7916c44ea52b82338296d
  这座城市与她所在的土地大不相同，差别在于，除了一小片老城区，毫无历史感。到四川的乡下游玩就是去感受历史，
  去感受那些通过劳动改造大地的岁月，去感受人类世世代代以来和土地相互较劲的过程。但是，
  四川的城市总是让人找不到时间感。它们的外壳太脏，看不出时新的样子；格调一致，十分丑陋，看不出岁月的痕迹。
  #+END_QUOTE

- 832-832, 标注, 2025 年 10 月 7 日星期二 上午 10:05:11
  #+BEGIN_QUOTE md5: 62648f6257f421761c22c755210d9c54
  那么多年，中国人处心积虑而又勤勤恳恳地摧毁了他们传统文化中一切有价值的东西。
  #+END_QUOTE

- 888-890, 标注, 2025 年 10 月 7 日星期二 下午 12:11:12
  #+BEGIN_QUOTE md5: 063026a317c2f1c3ceaa7be6e7c3d62c
  我最为烦心的却是文学在西方的政治化倾向：人们阅读文学的时候，把它当成了一种社会评论，而不是一种艺术形式；
  书本被强迫用作这样或那样的政治理论的服务工具。
  #+END_QUOTE

- 888-890, 标注, 2025 年 10 月 7 日星期二 下午 12:11:24
  #+BEGIN_QUOTE md5: da9c6452c2cdd0194c8402d83bf04999
  我最为烦心的却是文学在西方的政治化倾向：人们阅读文学的时候，把它当成了一种社会评论，而不是一种艺术形式；
  书本被强迫用作这样或那样的政治理论的服务工具。很少有文学批评针对文本本身做出反应，反而是文本被扭曲了，
  只有对评论家供奉的理论做出反应。
  #+END_QUOTE

- 888-892, 标注, 2025 年 10 月 7 日星期二 下午 12:11:39
  #+BEGIN_QUOTE md5: 3c640540e8b97b047f58d0a6c2658196
  我最为烦心的却是文学在西方的政治化倾向：人们阅读文学的时候，把它当成了一种社会评论，而不是一种艺术形式；
  书本被强迫用作这样或那样的政治理论的服务工具。很少有文学批评针对文本本身做出反应，反而是文本被扭曲了，
  只有对评论家供奉的理论做出反应。有马克思主义评论家、女权主义评论家、后殖民主义评论家。无一例外，
  他们把手中挥舞的理论作为模子，把文本填充进去，挤出一个个形状均匀的产品来。
  #+END_QUOTE

- 888-893, 标注, 2025 年 10 月 7 日星期二 下午 12:11:53
  #+BEGIN_QUOTE md5: 7b1b803b39d5ed7c913cb2489fcfcf2e
  我最为烦心的却是文学在西方的政治化倾向：人们阅读文学的时候，把它当成了一种社会评论，而不是一种艺术形式；
  书本被强迫用作这样或那样的政治理论的服务工具。很少有文学批评针对文本本身做出反应，反而是文本被扭曲了，
  只有对评论家供奉的理论做出反应。有马克思主义评论家、女权主义评论家、后殖民主义评论家。无一例外，
  他们把手中挥舞的理论作为模子，把文本填充进去，挤出一个个形状均匀的产品来。
  马克思主义评论家生产出来的是马克思主义，女权主义评论家生产出来的是女权主义，
  后现代主义评论家生产出来的是后现代主义。真像是把毫无意义的同一本书读了一遍又一遍。
  #+END_QUOTE

- 895-896, 标注, 2025 年 10 月 7 日星期二 下午 12:13:18
  #+BEGIN_QUOTE md5: c1d6abc41ae993c1041ab2a38d3a5550
  我一直认为，就文学而言，确立并尊重一种文化基础是很有价值的事情，
  #+END_QUOTE

- 923-924, 标注, 2025 年 10 月 7 日星期二 下午 12:16:13
  #+BEGIN_QUOTE md5: de0c3e55fa092ea00d8aa052d367dbc7
  当学生的时候，我就在寻找这样的东西——文学仍可欣赏的迹象、人们为愉悦而阅读、除却政治的因素，其本身就至关重要。
  #+END_QUOTE

- 932-935, 标注, 2025 年 10 月 7 日星期二 下午 12:17:11
  #+BEGIN_QUOTE md5: 1770a79f63d091fb1fdd0a1707ce30d8
  在习惯了害羞的他们之后，再来看他们在光秃秃的舞台上表演，真是一种十分奇怪的感觉。我时时在想，
  这也许跟中国古代戏剧的影响有关。在中国的古代戏剧中，动作十分夸张，十分风格化。不过，
  这也更有可能是在这个极少外露感情的社会里的一种宣泄而已。
  #+END_QUOTE

- 1097-1099, 标注, 2025 年 10 月 7 日星期二 下午 2:25:27
  #+BEGIN_QUOTE md5: 49b069fc0d6ad9e7908d8b78540dec5e
  毛泽东也缺乏有效治理国家的眼光和经验。手中的权力激励着他，在全国范围内树立起对他的极度崇拜。
  领导干部们面临着来自他们推翻的那个腐朽王朝的种种诱惑。
  #+END_QUOTE

- 1097-1099, 标注, 2025 年 10 月 7 日星期二 下午 2:25:40
  #+BEGIN_QUOTE md5: 914c4c6570e48f38c5324b8dea1b8b10
  不过，毛泽东也缺乏有效治理国家的眼光和经验。手中的权力激励着他，在全国范围内树立起对他的极度崇拜。
  领导干部们面临着来自他们推翻的那个腐朽王朝的种种诱惑。
  #+END_QUOTE

- 1193-1196, 标注, 2025 年 10 月 7 日星期二 下午 2:33:09
  #+BEGIN_QUOTE md5: 25c55465d3bfee59a5503a3258264700
  他离开的时候，我们坐了一辆出租车，从学校驶往码头。当出租车在城里高速穿行时，克莱姆，
  出于其在华尔街工作的精明的数学头脑，记下了驾驶员摁响喇叭的总次数。在十五分钟的行车过程中，
  那位驾驶员一共摁响喇叭 566 次。每分钟 37 次。
  #+END_QUOTE

- 1886-1888, 标注, 2025 年 10 月 9 日星期四 下午 12:36:15
  #+BEGIN_QUOTE md5: cd82d682dbb410af89bf88c9357998be
  正如历史上无数次发生的那样，专家的话可以忽略不听：就如毛泽东在 20 世纪五六十年代鼓励提高生育、发动大跃进和
  “文化大革命”一样。有些时候，你需要的是定论，而不是争论。没有必要因噎废食。
  #+END_QUOTE

- 1973-1977, 标注, 2025 年 10 月 9 日星期四 下午 1:33:02
  #+BEGIN_QUOTE md5: fa63ce3bb2121f66a7954aefa76122b5
  过去的五十年教导人们不要参与公共事务，可在一定程度上，共产主义建立的基础却是中国传统的集体主义思想，
  这种思想形成的社会模式维持了几百年的时间。这样的特征很难描述，尤其难以说清楚它到底产生了什么样的影响。
  我的学生们经常写道，中国人是多么具有集体意识，这鼓舞了人们在社会主义的道路上互相帮助，
  而个人主义的美国人则走上了自私自利的资本主义道路。
  #+END_QUOTE

- 1987-1989, 标注, 2025 年 10 月 9 日星期四 下午 4:33:40
  #+BEGIN_QUOTE md5: 584217827702a2bcdd5a187fbcea0576
  这个例子能够很好地说明集体主义思想，但跟我学生所说的东西又不一样。集体地来看，
  一群乌合之众都有着一个共同的目标——把票买到手——但除此之外再也没有什么东西能把他们凝聚起来，于是，
  每一个个体都会拼尽全力，以尽快地实现自己的个人目标。
  #+END_QUOTE

- 1998-2002, 标注, 2025 年 10 月 9 日星期四 下午 4:35:24
  #+BEGIN_QUOTE md5: 9ffc628a4500515b369b2e52a0dde71f
  出于同样的本能，一大群人可以围观事故的受害者而不出手相救。在涪陵，经常有人围观张望，
  但却很少看到他们出于某种群体的道义而有所行动。在个人主义盛行的美国，这样的场景倒是很多见，
  人们需要一个服务于个人的社区，因此，在看到伤亡者的时候，他们总是会这样想：我能够想象作为受害者的感受，
  所以我要出手相救。诚然，在美国也有人驻足围观，但那跟我在涪陵看到的完全没法比。涪陵人看到他人有难，可能会想：
  那又不是我的兄弟、朋友，我不认识他，看他受点罪还挺好玩的。
  #+END_QUOTE

- 2003-2006, 标注, 2025 年 10 月 9 日星期四 下午 4:35:41
  #+BEGIN_QUOTE md5: c7e3073dae2b8ef76fa2b434dda6315f
  这样一来，涪陵的“群众”和“乌合之众”这两个概念的界限就变得脆弱不已。出事了——可能是一场交通事故，
  或者是一场光天化日之下的争吵斗嘴——一大群人马上就会围过来，人群的能量逐渐蓄积，更多的人过来围观，
  纯粹出于一个十分简单的理由：出事了。
  #+END_QUOTE

- 2008-2010, 标注, 2025 年 10 月 9 日星期四 下午 4:36:07
  #+BEGIN_QUOTE md5: b2c765e5f1b2597ee6ac1832b96220f5
  假如碰到了吵架斗嘴或是其他吸引群众的公共事件，我肯定会停下脚步观看。但通常我看的是群众的脸，而不是当事人本身。
  在他们的表情里，我很难看出别的什么东西，除了那份痴痴的观望：出事了。
  #+END_QUOTE

- 2049-2053, 标注, 2025 年 10 月 9 日星期四 下午 9:24:20
  #+BEGIN_QUOTE md5: 34dbe0484c1c9188fef9c1b66a2bd21d
  不过，在河南省发生的是历史的另一面，1975 年的暴雨使得六十二座大坝如多米诺骨牌般纷纷溃决，
  死亡人数达到了二十三万。尽管那次灾难的规模非同寻常，但工程质量之低劣却并非异常：自 1949 年来，
  中国共有三千二百座大小水坝溃决。就本世纪而言〔48〕，中国的大坝溃决比例为百分之三点七，
  而世界其他地方的比例为百分之零点六。
  #+END_QUOTE

- 2153-2154, 标注, 2025 年 10 月 9 日星期四 下午 9:38:24
  #+BEGIN_QUOTE md5: dbb8de6071b8e3c4b0f8fda41487fe87
  使用。据传说，远在 9 世纪晚期，唐朝杨贵妃所钟爱的荔枝就是顺着这条路线运送到都城长安的。当时，
  涪陵荔枝是大家公认的极品——时至今日，涪陵仍然享有“荔枝城”这个别名——
  #+END_QUOTE

- 2164-2166, 标注, 2025 年 10 月 9 日星期四 下午 9:40:17
  #+BEGIN_QUOTE md5: ffb90d6fa389a13b6cf4a6873b8b78a2
  到了夏季，游客会成群结队地来到这里。全国上下、国内国外都掀起了一场盛大的广告宣传，
  动员旅游者在长江三峡被淹没之前来参观，而那些混凝土步道便是迎接客流的准备工作之一。这样的广告颇显滑稽：来呀，
  快来看呀，我们就要把这里搞没了！
  #+END_QUOTE

- 2182-2185, 标注, 2025 年 10 月 9 日星期四 下午 9:42:19
  #+BEGIN_QUOTE md5: 9c736c58c22ff4c056c1a83b82948d8c
  破坏性的艺术——唐代的船工们在那一大片无辜的砂石上留下刻痕——那么，如果人为修建的大坝破坏的是人为留下的刻痕，
  那可能也正是恰如其分的。那些凿痕因为船工而存在，正如江河为了人类的诸多用途而存在。 但是，仅仅为了这样或者那样的
  #+END_QUOTE

- 2203-2205, 标注, 2025 年 10 月 9 日星期四 下午 9:45:59
  #+BEGIN_QUOTE md5: 497f0da83b26bfc976afdeee8e215da8
  条江流泾渭分明，在今天这样的日子里，它们的交汇处形成了一条分隔，清晰明了，好似地图上的分界线。长江的水浑黄，
  乌江的水碧绿，它们的汇合犹如两片染色玻璃，被紧紧地贴在了白山坪的悬崖峭壁之下。
  #+END_QUOTE

- 2203-2205, 标注, 2025 年 10 月 9 日星期四 下午 9:46:10
  #+BEGIN_QUOTE md5: 3d07c8ebb8dfd7e28bf07bb6138fbe46
  。两条江流泾渭分明，在今天这样的日子里，它们的交汇处形成了一条分隔，清晰明了，好似地图上的分界线。
  长江的水浑黄，乌江的水碧绿，它们的汇合犹如两片染色玻璃，被紧紧地贴在了白山坪的悬崖峭壁之下。
  #+END_QUOTE

- 2288-2291, 标注, 2025 年 10 月 9 日星期四 下午 10:08:29
  #+BEGIN_QUOTE md5: 7d480b4c205dcca6f43e221f62c91e46
  “昨天。今天上午的电视上报道了。我听到这个消息的时候，很想哭。” 她说这话的时候笑了笑，但这是一种中国式的微笑，
  它仿佛是一个面具，掩藏了更深沉的情感。那些微笑可以掩藏很多情感——尴尬、愤怒、悲伤。当人们这样微笑时，
  仿佛有一种情感正在被紧紧地扭曲着、转移着。有时候，只需要瞥一下他们的眼睛、嘴角，甚或是额头上一丝凄惨的皱纹，
  你就能发现这一点。
  #+END_QUOTE

- 2288-2292, 标注, 2025 年 10 月 9 日星期四 下午 10:08:40
  #+BEGIN_QUOTE md5: e9e777f436c060ddf134e3aae51bec42
  “昨天。今天上午的电视上报道了。我听到这个消息的时候，很想哭。” 她说这话的时候笑了笑，但这是一种中国式的微笑，
  它仿佛是一个面具，掩藏了更深沉的情感。那些微笑可以掩藏很多情感——尴尬、愤怒、悲伤。当人们这样微笑时，
  仿佛有一种情感正在被紧紧地扭曲着、转移着。有时候，只需要瞥一下他们的眼睛、嘴角，甚或是额头上一丝凄惨的皱纹，
  你就能发现这一点。安妮的颧骨很高，酒窝很深。在那一天，我想我看见了她脸上时隐时现的忧伤。
  #+END_QUOTE

- 2461-2462, 标注, 2025 年 10 月 10 日星期五 上午 8:15:42
  #+BEGIN_QUOTE md5: baa3d6990f0352543daab95d7138e5bb
  跟孔老师交谈之后，我回想了一下我自己在美国的民主体系中的参与情况，才意识到自己的参与是多么的肤浅。
  我从未参加过具有决定性质的投票，今后也不会有这样的机会。
  #+END_QUOTE

- 2461-2463, 标注, 2025 年 10 月 10 日星期五 上午 8:15:47
  #+BEGIN_QUOTE md5: 8e0013002f9bb2bd5263cc8bfa8e0c25
  跟孔老师交谈之后，我回想了一下我自己在美国的民主体系中的参与情况，才意识到自己的参与是多么的肤浅。
  我从未参加过具有决定性质的投票，今后也不会有这样的机会。选举结果根本不是靠一票来定胜负的。
  #+END_QUOTE

- 2464-2466, 标注, 2025 年 10 月 10 日星期五 上午 8:16:05
  #+BEGIN_QUOTE md5: 19f55c0e0857a5db5a75ce15b9dd4296
  我在美国民主体系中的角色大致是这样的：无所谓地投票，被动地接受结果。然而，我并没有感觉到特别地渺小，
  因为我知道，这样的角色来自我自己的决定，如果有什么事情让我无法忍受，我随时可以改变我的参与度。
  #+END_QUOTE

- 2464-2466, 标注, 2025 年 10 月 10 日星期五 上午 8:16:14
  #+BEGIN_QUOTE md5: 2e401e107253f102a89f20f7d60397c2
  我在美国民主体系中的角色大致是这样的：无所谓地投票，被动地接受结果。然而，我并没有感觉到特别地渺小，
  因为我知道，这样的角色来自我自己的决定，如果有什么事情让我无法忍受，我随时可以改变我的参与度。在以往，
  我只不过选择了不参与，而这样的选择本身跟任何积极行为一样，都是一种民主。
  #+END_QUOTE

- 2527-2528, 标注, 2025 年 10 月 10 日星期五 上午 8:31:23
  #+BEGIN_QUOTE md5: b0e046e81b9a9b86082b2dd2bc2250f4
  这就是我们的鸦片战争——纯粹为了中美历史而纷争不断，悄无声息，毫无意义，话中有话，含沙射影。
  #+END_QUOTE

- 2621-2624, 标注, 2025 年 10 月 10 日星期五 上午 8:44:51
  #+BEGIN_QUOTE md5: 81a09c39b12a910f7cda0d7403b68452
  白山坪的山脚一带，泡桐树开出了紫色和白色的花朵。这些树的花期很短——一个星期后，它们就会凋谢飘落——
  而山坡上那些柔软的油菜籽也即将被收割掉。之后，眼里不再有翠绿色的稻秧，它们被移栽到了恭候已久的稻田淤泥中。
  在涪陵，春天还没到来就已经匆匆溜走，颜色变幻得令人眼花缭乱。
  #+END_QUOTE

- 2663-2666, 标注, 2025 年 10 月 10 日星期五 上午 8:50:00
  #+BEGIN_QUOTE md5: e9cc7a221a65056bbd7cbed8853efa1c
  这座山峦层次分明的风景展现在了他们眼前，有肌理有色彩：台地里种着一行行绿油油的小麦；油菜地里一片金黄；
  灰色瓦房后面的紫花泡桐树高高耸立着；滔滔的长江水在阳光里泛着银光；河对岸那座瘦长的宝塔隐约可见。
  缕缕微风吹拂着附近那一丛丛嫩绿的麦苗，阴凉处的温度刚刚合适。
  #+END_QUOTE

- 2687-2689, 标注, 2025 年 10 月 10 日星期五 上午 8:52:15
  #+BEGIN_QUOTE md5: a2a9344ff1bb94168f8a7060eb37d9e8
  这些纸钱的面额有八亿元，正面印着“冥府银行”字样，是阴界的法定货币。火苗跳跃之间，这些纸钱蜷曲、收拢，
  变成了黑色的灰烬。随着火苗蹿起，一阵阵热浪袭了过来。在长江河谷吹拂过来的微风中，蜡烛的火焰跳跃着。
  #+END_QUOTE

- 2771-2772, 标注, 2025 年 10 月 10 日星期五 下午 1:23:11
  #+BEGIN_QUOTE md5: 42e7768f0e23c5aa02bd12185b32101c
  运动会的开幕式是在一阵瓢泼大雨中举行的。跟香港回归有关的彩旗低垂着，显得有些丧气，五颜六色的氦气球拒绝升空。
  不过，开幕盛典照常进行着：
  #+END_QUOTE

- 2807-2809, 标注, 2025 年 10 月 10 日星期五 下午 1:26:28
  #+BEGIN_QUOTE md5: 5ac09e9e023a3517f232bd8731395b01
  跟英语系的干部们比起来，我越来越倾向于把这种坦诚当成一种可喜的变化，因为那些干部们笑容可掬，对我温和有加，
  但却一刻也没有放松过警惕。
  #+END_QUOTE

- 2807-2810, 标注, 2025 年 10 月 10 日星期五 下午 1:26:44
  #+BEGIN_QUOTE md5: 13570545ea10bae084abaed45d90882e
  跟英语系的干部们比起来，我越来越倾向于把这种坦诚当成一种可喜的变化，因为那些干部们笑容可掬，对我温和有加，
  但却一刻也没有放松过警惕。廖老师至少对我表示出了足够的尊重，愿意时不时地表露一下她的观点，
  而我也感觉到她对我有了同样的看法——这个外国人常常对中国充满了大不敬，但他至少还愿意说出来。
  #+END_QUOTE

- 2877-2880, 标注, 2025 年 10 月 10 日星期五 下午 1:30:33
  #+BEGIN_QUOTE md5: c0b6a94e015fb19ab794f5334113c356
  我本以为，学生们会表演得圆滑一些，以避开那一段不太光辉的历史，因为据我所知，好多学生的父母都在“文革”
  中吃过苦头。我在观看他们表演的时候，完全没有感觉到这一点。似乎没有人感到沮丧，这部短剧跟《仲夏夜之梦》
  或者其他任何喜剧一样，令人捧腹不已。这跟中国作家鲁迅的话十分相似：“记性好的，大概都被厚重的苦痛压死了；
  只有记性坏的，适者生存，还能欣然活着。”
  #+END_QUOTE

- 2887-2890, 标注, 2025 年 10 月 10 日星期五 下午 1:31:37
  #+BEGIN_QUOTE md5: 6f650f7bf120b0b1e8502c2e65afc902
  鸦片战争就没有这么简单，而且在学生头脑里的分量要沉重得多。一年到头，他们都在重温那一段历史带来的耻辱，
  而香港回归就是一种救赎，会对他们的生活形成实实在在的影响。相比之下，1989 年的学潮显得最为遥远，
  因为就我的学生而言，这些似乎根本就没有发生过。
  #+END_QUOTE

- 2904-2906, 标注, 2025 年 10 月 10 日星期五 下午 1:33:09
  #+BEGIN_QUOTE md5: 1b706822543e4f4caeefae758a20e737
  我明白了，作为一个有思想的人，他的长处正是得益于他没有受过任何正规教育。没有人教他怎么想问题，
  这样他就可以自由而清晰地思考了。 明白这个道理，无法让一个教师感到鼓舞。我越多想，
  就越对我的学生们受到的教育充满悲观情绪。
  #+END_QUOTE

- 2985-2991, 标注, 2025 年 10 月 10 日星期五 下午 1:39:39
  #+BEGIN_QUOTE md5: 9e644b2541e943b33904ec60ba0427af
  我一个人坐在那里，把他刚才说过的话想了一下。他是唯一近似异己分子的学生。我回想起来，在我来到涪陵之前，
  我曾经想象过他们都是什么样子。我一直以为，他们应该是些有头有脸的角色——有魅力、有知识、有远见、有勇气。1989
  年的时候，也许真就是那么回事；在大点的城市，现在也许仍然还像那么回事；但在涪陵，已经完全不是那么回事了。
  我最好的几个学生——索迪、琳达、阿姆斯特朗、奥莫尔，也就是有魅力、有知识、有远见、有勇气的那些人——
  很早就被吸收入了党。如果你有能力，你就可以玩转各种制度；入党对职业发展十分有利。不管怎么说，
  学生们好像全都觉得，以他们受到教育的几种有限的方式体现出爱国精神，总归是件好事情。
  我想象中的异己分子在涪陵没有现实土壤。
  #+END_QUOTE

- 2986-2991, 标注, 2025 年 10 月 10 日星期五 下午 1:39:44
  #+BEGIN_QUOTE md5: 496122600f7a6f04ee85e086205ac020
  我回想起来，在我来到涪陵之前，我曾经想象过他们都是什么样子。我一直以为，他们应该是些有头有脸的角色——有魅力、
  有知识、有远见、有勇气。1989 年的时候，也许真就是那么回事；在大点的城市，现在也许仍然还像那么回事；但在涪陵，
  已经完全不是那么回事了。我最好的几个学生——索迪、琳达、阿姆斯特朗、奥莫尔，也就是有魅力、有知识、有远见、
  有勇气的那些人——很早就被吸收入了党。如果你有能力，你就可以玩转各种制度；入党对职业发展十分有利。不管怎么说，
  学生们好像全都觉得，以他们受到教育的几种有限的方式体现出爱国精神，总归是件好事情。
  我想象中的异己分子在涪陵没有现实土壤。
  #+END_QUOTE

- 2995-2996, 标注, 2025年10月10日星期五 下午1:40:15
  #+BEGIN_QUOTE md5: dee4910f9d07a3d7966924e1e7ab19ac
  我再一次意识到，大的变化一定会首先发生在北京、上海。到了一定的时候，它们才会投射到涪陵这样的地方来，
  就像以往无数次的情形那样。
  #+END_QUOTE
