:PROPERTIES:
:ID:       15ab0ebe-0c43-4351-b447-47f78d8df5e1
:END:
#+TITLE: [笔记]李鸿章传
#+AUTHOR: Yang,Ying-chao
#+DATE:   2024-07-20
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:  align nodlcheck oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+LANGUAGE: en
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :lihongzhangc:note:ireader:


** 封面

李氏的历史局限性在于“不知今日世界之竞争，不在国家而在国民”；也不知西方国家能够化除门户之见，通过新的宪政走向富强，其改革动力来自下面而不是上面



天下只有平庸之人既不会挨骂，也不会得到赞誉。如果全天下的人都在骂一个人，那么他就可以称得上是超乎寻常的奸雄；如果全天下的
人都在赞美一个人，那么他则可以称得上是超乎寻常的豪杰。但是说这些话的人差不多都是些平常人，有见识、有才干的几乎一个也找不
到，那么让平常人评论超乎寻常的人，难道是一件可信的事？所以，誉满天下的人未必不是媚俗趋时的伪君子；谤满天下的人未必不是伟
人。



中国数千年来的历史是一部流血的历史。所谓人才，都是杀人的人才。纵观古往今来的大事，只有乱世才会出现英雄，太平盛世没有英雄。



中国几千年的史书都是用脓血写成，用肝脑点缀的，这一点没什么可以隐讳的。[[iReaderBookNoteGoto://2_0_0$##3-0-2-52181-0##$][



当时李鸿章已经三十八岁了，由于怀才不遇，学刘备拍着大腿叹息光阴流逝，已经过了半辈子，自认命运不济，实在是不好意思再谈功名。
唉！这些年是老天对李鸿章的磨难呢，还是老天对李鸿章的恩赐呢？他志向不得舒展，颠沛流离十多年，正好锻炼了他的气量，增长了他
的才干，对他日后担当大任起了作用。




** 第四章 军事家李鸿章（上）

李鸿章实在是不懂得国家事务的人。他不知道国家是什么东西，不知道国家和政府之间有什么关系，不知道政府与人民所拥有的权力的范
围，不知道大臣应当尽的责任。他对于西方国家富强的真正原因完全没有认识，认为我们中国的风俗、传统、政治制度没有一样不比外国
优秀，比不上的只有枪、炮、船、铁路、机器，我只要把这些都学来，洋务的事情就可以结束了。这也是近日全国上下研究时务的人所倡
导的论调，而李鸿章实际上是这一派人物中已有三十年资历的老前辈了。就像无盐学西施的笑容，寿陵人邯郸学步，只能越学越丑，最终
一无所得，这是必然的。



李鸿章这么忠诚，有这么敏锐的洞察力，又长时间担任重要职务，掌握大权，但成就却仅仅到了今天这个水平，这是为什么呢？这是因为他只知道有军事，却不知道还有民政；知道有外交，却不知道还有内政；知道有朝廷，却不知道有国民。[[iReaderBookNoteGoto://3_0_0$##3-0-3-72121-0##$][



庄子曾经说过：“开端往往微小，结果却相当巨大。”擅长下棋的人于看似无关紧要的几步，也不肯轻易放过。[[iReaderBookNoteGoto://3_0_0$##3-0-3-106702-0##$][



此义和团实际上是政府和民间势力的联合体，但他们的目标是不一样的：民间势力的目的都出于公心，愚蠢而没有谋略，令人感到可怜；政府则完全出于私心，做了这样狂悖而倒行逆施的事情，全天下人都恨他们。[[iReaderBookNoteGoto://3_0_0$##3-0-3-186057-0##$][




** 第十二章 结论

曾国藩深守着知足、知止的信条，常常记挂着急流勇退的道理，[[iReaderBookNoteGoto://4_0_0$##3-0-4-4363-0##$][



李鸿章怎么比得上俾斯麦呢？从军事角度来说，俾斯麦战胜的都是敌国，李鸿章所战胜的都是同胞；从内政角度来说，俾斯麦能将一些散
漫的小邦国合成一个大联邦，李鸿章却使庞大的中国变成了二等国家；从外交角度来说，俾斯麦联合奥地利、意大利，并成功地驱使它们，
李鸿章联合俄国，却反而落入俄国的圈套。将这三方面相比较，两者的差距何异于天壤之别？这并不是用成败的标准来评论人，李鸿章的
学问、智力、胆识没有一项能与俾斯麦相提并论的。他的成就不如俾斯麦，这也是由优胜劣汰的公理所决定的
