:PROPERTIES:
:ID:       37bef0b7-2334-4382-8421-d1454c3175a0
:END:
#+TITLE: [笔记]85中国大历史
#+AUTHOR: Yang,Ying-chao
#+DATE:   2024-07-20
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:  align nodlcheck oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+LANGUAGE: en
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :85zhongguoda:note:ireader:


** 第二章 亚圣与始皇

劳心者治人， 劳力者治于人


：中国古代史里的日期只在公元前 841 年之后才能确定无误。因为自此以后。
古书里提及天候星象的变化，可以和外间的纪录对照。841 年前的日期带有推算性质，
不能视作绝对的可靠


西伯被溢称“文王”。
其为“文”，则是温和谦让，有大政治家的风度。他的儿子名发，以后被溢为“武
王”，以表彰其战功


。中国政治思想家受官僚主义影响，经常重视形式，超过实
质，可算其来有自了。年久月深，当初技术上的需要，日后也就被认为是自然法规
之一部。




** 第三章 土壤、风向和雨量

历史书里提及六岁必有灾荒，12 年必有大饥谨。其实在 1911 年民
国成立前之 2117 年内，共有水灾 1621 次和旱灾 1392 次，其严重经过官方提出。亦即
无间断的平均每年有灾荒 1.392 次。



** 第五章 第一帝国：树立楷模

汉武帝继承了汉高祖以来，数十年休养生息所累积的国家资源，对内以“罢黜
百家，独尊儒术”，奠下中央集权官僚体制运作的理论与方法，对外则连年发兵征
讨匈奴，开拓四裔，使大汉声威远播，国势达于顶峰



** 第六章 名士成为军阀

中国自汉以来累积的财富，一旦达到某种程度，便无法阻止，也不能在制度
上予以集中巩固。



** 第八章 历史向侧面进出

在这种种故事中，作史者的态度，较诸他们笔下之题材还要值得考虑



** 第九章 统一的途径

从拓跋国家的全部历史看来，我们也可以看出事势的发展具有某种定型：在统
一的过程中，其决定性的力量由北至南，由西至东，亦即是从内陆经济较落后的地
区吞并接近水道交通，内中人文因素较为复杂的地区。



** 第十章 第二帝国：已有突破，但未竟事功

隋唐之重建西安以一种宏大的眼光，构成一座计划城市。东西 6 英里而南北五英
里，这座 1000 年以前建造的长安城，其面积为今日西安市的 8 倍，其南北驰道宽 500
尺


儒家基本的教条为本身的克制，对人的揖让，可是最后的裁判权出自龙椅，
则又倚靠当今天子自持的程度而定。当中互相矛盾之处足使超级政治家得有无限的
机缘，在进退之间，作攻防的决策。这也是中国政治史的中心主题。



** 第二十章 现代中国及其在世界上的地位

中国的长期革
命有如一个大隧道。需要 100 年时间才能摸索过去。当这隧道尚在被探索的时候．内
外的人物都难于详细解说当中弯曲的进程。即是革命人物也会被当前困难的途径迷
惑，而一时失去方向感。


纵使事实之衍化对我们个人不能如意，或者
在短时看来为荒谬不合理，可是把这些情事前后连贯，又从超过人身经验的角度看
去，则它们有其意义；最低限度，这些事迹使我们知道我们生命旅途之原委。



资本主义能够施行无阻，无非一种以货币管理的安排，由以下三个条 件做起。
信用广泛的展开， 经理不受人身关系限制，
和服务性质的事业全般活用


蒋介石可以被认为首先给中国制造了一
个原始型的统一政府。这政府纵有各色各样不是，它终究主持了自卫，且在图生存
的关头里获得百余年来在国际战争中的第一次胜利。

凡他力所能及，所有因素都超过限度做到极端。他力之不及，则虽必
需却令其付诸阙如。



** 第二十一章 台湾、香港与澳门

在文教方面，国民党之政策行使已逾 40 年，更不容分型运动之展开。不仅儿童
自幼受教为中国人，而且博物馆图书馆和各处之档案处尤以大陆上之根源作号召。
即使工程师与技术人员在受训时也不觉得此生事业应当全在岛上省内，教师与公务
员更无论。最近几年来已有“台湾文学”出现，可是绝大多数出版品显示一种广泛
的眼光，而且往往较大陆作家的范围尤为宽阔。
