:PROPERTIES:
:ID:       e0e6a941-f99c-47f3-9258-48f741147150
:END:
#+TITLE: 七月读书笔记
#+AUTHOR: Yang,Ying-chao
#+DATE:   2025-08-08
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:  oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :weixin:

* [[file:\[笔记\]弃长安-张明扬.org][弃长安]]

从唐明皇弃长安开始，到李亨最终收回长安，从盛世到衰败，真的不需要多长时间，让人感慨。

#+BEGIN_quote
诗人、盛唐与长安，一起凋零，失落在唐诗与历史记忆之中。 在大时代的丕变中，帝王、宠妃、储君、宰相、边将、诗人、
宦官、枭雄、叛将、贰臣……每个人都深陷于走不出的盛世困境，每个人都在寻路突围，每个人都付出了自己的代价。
每个人都回不到长安。
#+END_quote


#+BEGIN_QUOTE md5: f20f0ef9919dc4088189253c4f5f157c
我的写作激情是什么？ 大概，是大唐盛世在天宝十四载的轰然倾圮，
是长安这座世界之都在渔阳鼙鼓声中的脆弱与窘迫无计，是李隆基君臣从自负颟顸到仓皇辞庙的骤然切换，
是李林甫和杨国忠这两位宰相的逢君之恶，是杨玉环的“明眸皓齿今何在”，是太子李亨的隐忍与浮夸表演，
是安禄山的胡旋舞与曳落河，是血色残阳中的张睢阳齿与颜常山舌，是李白、杜甫、王维等人的盛世求不得与乱世离散……
#+END_QUOTE

#+BEGIN_SRC text -r
海燕何微眇，乘春亦暂来。
岂知泥滓贱，只见玉堂开。
绣户时双入，华轩日几回。
无心与物竞，鹰隼莫相猜
#+END_SRC

以这本书为引，又开启了 《长安的荔枝》、《长安十二时辰》。。。

* [[file:\[笔记\]长安的荔枝-马伯庸.org][长安的荔枝]]

这两月很火，电视、电影扎堆上了，所以把书找来看了一遍。书不长，写了李善德成为荔枝转运使、费尽心思从岭南运送荔枝到长安的故事。

个人感觉，马王爷写的书，最近看的都感觉是为改编成影视而写的似的，不太具有文学上的鉴赏价值。。。

* [[file:\[笔记\]桃花源没事儿-马伯庸.org][桃花源没事儿]]

依旧是马王爷的书，篇幅不长，但是说攒了很长的时间写成的。跟 《太白金星有点烦》 类似的风格，一般吧。

* [[file:\[笔记\]流俗地-黎紫書.org][流俗地]]

马来西亚的华语小说，以盲女银霞的视角，描写了一幅马来人的日常生活画卷。网上评分很高，写的确实也细腻，很多遣词造句出人意料。。。

#+BEGIN_QUOTE md5: abce68ea694844496c6d0bbdd7d16306
莲珠的声音，银霞听着舒服。尽管只是一般的市井口吻，莲珠说话还带着渔村的乡音，听着却像被太阳熏了一整天的海潮，
灌得人耳道里暖暖的。
#+END_QUOTE

#+BEGIN_QUOTE md5: bc27ed24ef17f7abbc7cd65c6f59833c
那一辆国产车买来已一年多，虽然车里放了气味极浓的熏香膏，仍还透着一股如胶似漆的新车味道。
#+END_QUOTE


#+BEGIN_QUOTE md5: 088449521b553241116313da57175772
或者长叹一声，一口气悠长得像是来自五脏六腑。
#+END_QUOTE


#+BEGIN_QUOTE md5: cb2308925d767cc317f826ba178a13d2
逃离陈家的那一日，马票嫂记得陈家门前的阳光撒得均匀，天空一片和颜悦色。
#+END_QUOTE

诸如此类。。。
