:PROPERTIES:
:ID:       8a3acd45-5376-4daf-bf66-5810d8a348ce
:END:
#+TITLE: 世上为什么要有图书馆（译文纪实）-杨素秋
#+AUTHOR: Yang,Ying-chao
#+DATE:   2025-09-13
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:  oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :笔记:

- 103-105, 标注, 2025 年 9 月 12 日星期五 下午 1:33:20
  #+BEGIN_QUOTE md5: 8667cd0181a2c8f6f9d653222afca3e1
  记不清从什么时候开始，启蒙无数青年学子走向文学道路的语文课变得枯索无聊，
  记不清从什么时候开始我们不再信任语文课能够帮助学子抵达文学，也记不清从什么时候开始“鲁迅”
  变成了一些有标准答案的习题。“
  #+END_QUOTE

- 260-263, 标注, 2025 年 9 月 12 日星期五 下午 10:14:43
  #+BEGIN_QUOTE md5: c1d18d7358b1eb515717687828519ede
  他似乎是不在意等级的人。在官场不在意等级，就像在家长群坚持不给孩子报补习班，在高校不重视职称名号，都比较难。
  也许一开始有锐气，久而久之，或被洗脑，或被排挤，或被利益诱惑，免不了从众。若走一条人少的路，
  在官场为群众尽力发声，在家长群里关心孩子的求知欲和快乐，在高校里专注知识和学生，那得内心笃定，才扛得住颠簸。
  #+END_QUOTE


- 589-592, 标注, 2025 年 9 月 13 日星期六 下午 12:13:31
  #+BEGIN_QUOTE md5: 0636be0d2ff60371d0d921692a3b4ad5,716454b2cb526a3ef41241240933ee16
  瑞典人林西莉曾在《汉字王国》中这样回忆碑林：“在那里散步，如同置身于森林之中。
  文字上的光仿佛是刹那间从沉重的灰色石头中散发出来的。那里有诗人和皇帝各种不同的手迹……它们离我们那么近，
  伸手就能摸到它们——这使得这个地方成为中国的知识圣地之一。”
  #+END_QUOTE


- 660-663, 标注, 2025 年 9 月 13 日星期六 下午 12:21:59
  #+BEGIN_QUOTE md5: 9d4961781a42cdd258e9c4871a14c053
  院子中央的银杏树摇动着小黄裙，漂亮是漂亮的，但那里离领导办公室太近，并没有人敢去和树拍照合影。它们兀自地绿，
  又兀自地黄，过段时间，又要兀自地落叶吧。没有人敢去捡拾那些小扇子，没有人把它们撒向空中，
  没有人轻轻地踩踏在叶子上，听那扑簌簌的声音。它们被扫进垃圾箱的时候，寂不寂寞？
  #+END_QUOTE


- 775-781, 标注, 2025 年 9 月 13 日星期六 下午 1:52:14
  #+BEGIN_QUOTE md5: 54c390728e5bc8945735609e0723e22e
  甲方大 Boss，也就是我，没有任何经验。我在忐忑中打电话问我弟媳（一个可能熬过一千个夜、
  写过一百份标书的路桥公司员工）： \\
   “我需要准备什么？” \\
   “你是甲方爸爸，什么都不用准备。” \\
   “我要严肃吗？我要笑吗？ 我要发言吗？” \\
   “你是甲方爸爸，你想怎样就怎样。”\\
   “我万一说错话怎么办？” \\
   “不可能，甲方爸爸说什么都是对的。”
  #+END_QUOTE


- 901-901, 标注, 2025 年 9 月 13 日星期六 下午 2:02:42
  #+BEGIN_QUOTE md5: 5bcc69d5a3be16659648f0624cd12a86
  秋雨如同一场病。树一夜之间秃了，老得不像个样子，满地的证据。
  #+END_QUOTE


- 954-956, 标注, 2025 年 9 月 13 日星期六 下午 2:07:18
  #+BEGIN_QUOTE md5: 48bb6f7d39ff386f0648c99c9a1dc69f
  中图网来了一对夫妻，女的穿着暗花棉麻小薄袄，声音熟悉，正是电话里那个柔和的人；男的穿得也素，不像商人，像书生。
  他和她说话都缓，互相补充着说，不打断，不抢话，像是两根织毛衣的针，一来一回，把话头轻轻给对方递过去。
  #+END_QUOTE


- 1015-1016, 标注, 2025 年 9 月 13 日星期六 下午 2:12:05
  #+BEGIN_QUOTE md5: d41932cf154b7375400dcfaf7c66112b
  朗西埃说：“任何被教的人，只是人的一半。”他鼓励个体在陌生领域自学，坚信自己能读“不能读”的书，能写“不能写”
  的东西。
  #+END_QUOTE


- 1139-1143, 标注, 2025 年 9 月 13 日星期六 下午 2:34:18
  #+BEGIN_QUOTE md5: e5ef706d7da249b7f5120fc4780e0a93
  春天来了，飞絮悠然而起。悬铃木的小伞毛茸茸，杨柳的细绒在地上打滚儿，我被这些小东西弄得喷嚏不止，
  但又觉得它们生动。白绒球遇见白绒球就牵上了，大的裹着小的做前滚翻，很快团成一团飘起来，轻盈得如同肥皂泡。
  它们聚集到停车场的角落呼朋引伴，被风鼓荡着，从一排栅栏里往外挤，像小孩放学时争着奔出校门，你推我搡叽叽喳喳，
  一涌出栅栏就嘭地炸开，庆祝一般。我站在旁边看得笑出声。
  #+END_QUOTE


- 1931-1934, 标注, 2025 年 9 月 13 日星期六 下午 11:24:43
  #+BEGIN_QUOTE md5: 146e1ecd315c9fffc33a75b0c39ca4d3
  什么样的人才能胜任选书的职位？约翰·科顿·丹纳在《图书馆入门》中为公共图书馆建构了一个理想的“选书人”形象，
  这个人首先得是个书虫，有丰厚学养，能带领孩子们阅读好书。但他又绝不应该是个书呆子，不宜过于沉湎于书籍，
  要多出来走走，以免与底层老百姓脱节，无法了解低学历人群的需求。
  #+END_QUOTE


- 2144-2146, 标注, 2025 年 9 月 14 日星期日 上午 9:23:01
  #+BEGIN_QUOTE md5: 4b111fa2942d43a34d5899283110dad2
  跟我说了好几次，他特别想念摸读盲文书的感觉。我说你每天都在听书啊，为什么还想摸书？他说，那太不一样了。听书，
  好像是怀里被人塞了一堆东西。而摸书，是自己主动走进去的，就像走进海里，感受海水一点一点地漫过脚面，
  那感觉太美妙了。
  #+END_QUOTE


- 2337-2341, 标注, 2025 年 9 月 14 日星期日 上午 9:50:15
  #+BEGIN_QUOTE md5: 37d83225dcf8bd44691d9390aa3df82f
  去感受你眼前的生活，像一个诗人那样地去感受吧。罗伯特·弗罗斯特看云时，心底那么温柔：“天空中的云低垂，蓬松，
  就像忽闪的眼前飘荡的几缕刘海。”唐纳德·霍尔将听觉折叠为视觉：“孩子的哭声响起好像一片刀刃。”而在艾略特那里，
  雾有手有脚有舌头：“黄色的雾在窗格上擦它的背，黄色的烟在窗格上擦它的口笼，它的舌头舐着黄昏的角落，
  盘旋在排水沟的水坑；从烟囱掉下的灰落在它的背上，它滑过阳台，纵身一跃，看到这个温柔的十月之夜，萦绕着房子，
  睡去了。”
  #+END_QUOTE


- 2344-2346, 标注, 2025 年 9 月 14 日星期日 上午 9:51:12
  #+BEGIN_QUOTE md5: a48fb472b73b5dffe6394ba71a6b297b
  而在一首英文诗中，同是“石头”rock 和 stone 声音的韵味不同。前一个词的末尾音节 k 是哑音字母，以它结尾，
  仿佛突然屏住了呼吸，棱角分明，沉默而确定。后一个词的末尾 ne 是鼻音，读完了还留有余波，气息柔和，荡漾着涟漪。
  #+END_QUOTE


- 2547-2550, 标注, 2025 年 9 月 14 日星期日 上午 11:47:44
  #+BEGIN_QUOTE md5: 53e49b4e214b4168436f7551deb4f23c
  豆豆四岁拿起毛笔，随便写，有时临摹碑帖，有时写自己的心里话。有个假期，豆豆写了大大的几个字“睡觉真无聊”，
  杨国庆发到朋友圈里，大家都乐了。那时候豆豆才六岁，那是他的心声，运笔支腿拉胯，收笔里弥漫着疲倦，那个“聊”
  字像是小孩子坐在墙角噘着嘴懒得搭理人。那种神韵，杨国庆自叹写不出来。
  #+END_QUOTE


- 2640-2641, 标注, 2025 年 9 月 14 日星期日 下午 5:47:01
  #+BEGIN_QUOTE md5: 9024016b3859b1016a3e55e1d1583d8b
  不送给写得最好的学生，而送给态度最认真的学生。学生习字的态度在起笔落笔里，藏不住的。有的孩子哪怕写得丑一点，
  只要认真就值得奖励。
  #+END_QUOTE


- 2644-2644, 标注, 2025 年 9 月 14 日星期日 下午 5:47:53
  #+BEGIN_QUOTE md5: 9327881b9265db3844b1f7294a3f8afa
  在穷极无聊时，在人生的至暗时刻，能写书法，就是一种寄托。
  #+END_QUOTE


- 2827-2829, 标注, 2025 年 9 月 14 日星期日 下午 7:49:58
  #+BEGIN_QUOTE md5: ebc4ed11161489af37c8213d658ce65b
  眼前这页纸上，核心要点周围簇拥着大段说辞，段落与段落之间高度相似，互相复制词汇和口号。
  空浮的意义像浓雾一般升腾起来，包裹着草木房舍，让它们面目模糊。
  #+END_QUOTE


- 2830-2834, 标注, 2025 年 9 月 14 日星期日 下午 7:50:42
  #+BEGIN_QUOTE md5: ffb047e3907bdb7f6921bbc180aefc94,4f6f5d8dfcd9efaaaa8c070a2a5931cb
  套话为什么这样流行？威廉·津瑟在《写作法宝》中说：“管理者一旦上升到一定的高度，没人再去向他指出简单陈述句之美。”我
  承认，“不懂文字之美”也许是一部分原因，但“故弄玄虚”恐怕是更深层的心理需求，越玄虚，越没有破绽，就越安全。
  有关这一点，影评人梅雪风说得很清楚：“套话的核心要义就是不负责任，所以不敢指向任何实际的问题，
  永远都只是在言语自己的迷宫里自我繁殖，用一种铿锵有力的空转作为行动的证明。”
  #+END_QUOTE


- 3271-3274, 标注, 2025 年 9 月 14 日星期日 下午 9:24:49
  #+BEGIN_QUOTE md5: 877c738504d261ac89b34ce39f2252bf
  从前逛书店方便，小书店到处都有，20 世纪 90 年代的师大路有七八家书店，每家的社科书架他都熟悉，
  上下打量一遍就知道增加了什么减少了什么。现在的师大路有着明确的口号“保护文化”，却没有一家书店。
  他也几乎不再在街头买书，很多网红书店桌椅美丽，又有绿植咖啡和手工布艺，衣着鲜亮的年轻人四处寻找背景拍照，
  但是书放得极高，人根本就够不着，叫服务员也叫不来，去一次就灰了心。
  #+END_QUOTE


- 3278-3281, 标注, 2025 年 9 月 14 日星期日 下午 9:25:29
  #+BEGIN_QUOTE md5: 087fa23c27b4034219959f65cc70c367
  网购书籍没有承载这些，它们脱离了街巷之间的气息，从一个没有生命的电子页面来到自己的书架上，有时候他会疑惑：
  “这是我买的书吗？”更让他遗憾的是，从前对书的那种渴求感也随着网购而消逝。没有网的年代，他对书朝思暮想，
  夜里惦记得睡不着，白天满街去寻。现在再也没有紧缺，便再也难有渴望。
  #+END_QUOTE


- 3292-3295, 标注, 2025 年 9 月 14 日星期日 下午 9:27:04
  #+BEGIN_QUOTE md5: 1bd4b942c47f2c0202fb6ae605416a26,1730ae01f233f9bf18e73446e0d2fee8
  阅读并不是想象中坐在漂亮台灯下品着咖啡就可以实现的精神自由，而是一件苦事和险事，也很容易被一些‘看不见的手’
  操纵。做一个真正的读书人，需要孤独，但不是一种表演的孤独，或自恋。”那么怎么才能在阅读中获得一种真正的自由呢？
  他想了想，然后说：“还是兼收并蓄，只能多读，啥事情都是见多不怪。”
  #+END_QUOTE


- 3311-3311, 标注, 2025 年 9 月 14 日星期日 下午 9:28:23
  #+BEGIN_QUOTE md5: d8063dff80388b98a6fa1a66642ebad7
  读书是私人的事，陈越有自己完整的思路，很少去追逐学界热潮。
  #+END_QUOTE


- 3691-3693, 标注, 2025 年 9 月 15 日星期一 上午 8:04:19
  #+BEGIN_QUOTE md5: c720a174dd453336b4db37299e0a1456
  宗教不是个人行为，要从社会现象中去分析它，是各种宗教仪式维持着社会或者集体存在的手段。王耘说，
  多数僧侣在宗教活动当中所获得的满足感，很大程度上并不是来自个人冥想，而是来自和他人之间的关联，
  与法师和信徒的交往构成了僧侣的存在感。
  #+END_QUOTE


- 3746-3749, 标注, 2025 年 9 月 15 日星期一 上午 8:08:24
  #+BEGIN_QUOTE md5: e6bd6b01603f1447bba65a95cab85813
  有一天，孩子问我：“孟子说，无后就是一种不孝。可是，佛教里的和尚不结婚不生孩子，还常常成为人们仰慕的高僧。
  这种矛盾怎么解释？”我说你去请教王耘吧。王耘回答说：“儒家和佛家关于生育的观念不同，但又有共通性，
  都是对生命有限性的反抗。前者通过延续生命来克服生命的有限，后者通过否定欲望来解构命运的牢笼。”
  #+END_QUOTE


- 3749-3751, 标注, 2025 年 9 月 15 日星期一 上午 8:09:59
  #+BEGIN_QUOTE md5: 03d575f80d52a578d8d734aa573d1a3e
  一个母亲，怀胎十月，早晨迎接新生命，夜晚孩子突发恶疾而亡。一个国王午时登基，子时遭遇政变。
  生命的历程就像炸药一般，顷刻尽毁。生老病死作为一个整体，猝不及防地出现在佛陀面前，这就是“苦”。
  #+END_QUOTE


- 3752-3754, 标注, 2025 年 9 月 15 日星期一 上午 8:10:28
  #+BEGIN_QUOTE md5: 09ee71367cd61b94f496744c98380540
  人们常说时间是从指缝中流过的沙子。他说，不是你的手里有一把沙子，而是你就是一粒沙子，你在时间之中，是你，
  作为一粒沙子流失了。这种流失的感觉，就是“幻”。
  #+END_QUOTE


- 3756-3758, 标注, 2025 年 9 月 15 日星期一 上午 8:10:54
  #+BEGIN_QUOTE md5: c638af0f9d86807ba20725c2cf12ea42
  他让孩子学琴，朋友问他：“是不是因为琴能带给孩子欢乐？”他说：“不，是因为，将来孩子长大了，孤单痛苦的时候，
  琴可以陪他。”
  #+END_QUOTE


- 3763-3765, 标注, 2025 年 9 月 15 日星期一 上午 8:11:38
  #+BEGIN_QUOTE md5: 48223a7cc5885c693d228d8e762a1383
  他读过许多佛经，但他总不想修菩萨道，而更想修阿罗汉道。他说：“众生实在是太闹腾了，我拯救不了。
  我更愿意做一名阿罗汉，做一个有血有肉普普通通的人，静观这个世界。”
  #+END_QUOTE


- 3782-3784, 标注, 2025 年 9 月 15 日星期一 上午 8:14:48
  #+BEGIN_QUOTE md5: 08f4eeea9ae3ffcefd7e7eacae4ebae4
  美人美景可以在社交媒体上获得大量点赞，但这不是他要拍的。光鲜堆积在一起多是同义重复，
  而他想记录平常事物中的异样。他用眼睛密切地注视背街小巷，等待内心波澜。
  #+END_QUOTE


- 3789-3790, 标注, 2025 年 9 月 15 日星期一 上午 8:16:06
  #+BEGIN_QUOTE md5: 80edd4396df62baf3af7094457a926df
  他欣赏摄影师索尔·雷特的名言——不被关注是一种豁免。
  #+END_QUOTE


- 3791-3793, 标注, 2025 年 9 月 15 日星期一 上午 8:16:21
  #+BEGIN_QUOTE md5: 1b4589de47f055d049d7161ceff57bf2
  他说，其实最吸引他的不是这些技术细节，而是索尔·雷特的状态，没有艺术野心，对于“不被关注”心安理得，
  并不处心积虑地成名，只是单纯喜欢拍照。他能看出来索尔·雷特在街头很愉快，
  #+END_QUOTE


- 3797-3800, 标注, 2025 年 9 月 15 日星期一 上午 8:17:13
  #+BEGIN_QUOTE md5: 65ce1e4fa8a8e2bb38535f2b283f7715
  他曾住在北京的二环，用忙碌差事换来丰盈物质。后来搬到东南五环外的一间公寓，面积小——
  晾晒衣服得在房间中央搭一个简易架子——但房租少了一半，每月只用接几次拍摄任务就够开支，剩下时间统统由自己安排。
  他形成规律日程：早晨静坐，半小时腹式呼吸。再到健身房练习拳击和举重，回家登上铁质阁楼读书。下午拍摄，
  晚上看电影。
  #+END_QUOTE


- 3802-3804, 标注, 2025 年 9 月 15 日星期一 上午 8:17:58
  #+BEGIN_QUOTE md5: a6d75332f2a4cc2112d86716f5604d26
  同龄友人如今都成了教授、主任、处长……别人在规则中生长，自己好像是野草。傍晚响起雷声，他去追赶暴风雨，
  拍摄雨中船只和闪电树影，一身湿透。在出租车里听到窗外有趣的玩具狗录音，念念不忘，特意走几公里去找，
  剪辑成搞笑片段。
  #+END_QUOTE


- 3874-3875, 标注, 2025 年 9 月 15 日星期一 下午 3:41:58
  #+BEGIN_QUOTE md5: c75cca6ae3f01e14681f72fc33791b2f
  “如果我的野心大过了同情心，我就失去了灵魂。”这是摄影师纳切威的名言，
  #+END_QUOTE


- 3880-3881, 标注, 2025 年 9 月 15 日星期一 下午 3:42:40
  #+BEGIN_QUOTE md5: 97c0a8544869a2b78cf80b4b6e4d4675
  这个小男孩历经重大风波，很久没有笑过。但那个下午，男孩在宋璐的陪伴下，发梢甩动着汗珠，笑个不停。
  #+END_QUOTE


- 3897-3899, 标注, 2025 年 9 月 15 日星期一 下午 3:44:12
  #+BEGIN_QUOTE md5: 0a41b20f80e1e8b49879cdcbd8b70520
  有人说他这样太清高，但他并不怕被误解。孤独、决绝、不合群，这几个关键词挺立于他的各个社交媒体中，
  是他给自己的界定。有时他觉得自己是那样地需要倾诉和陪伴，有时又觉得，唯有孤独才能获得真正的自由。
  #+END_QUOTE


- 3962-3964, 标注, 2025 年 9 月 15 日星期一 下午 6:56:43
  #+BEGIN_QUOTE md5: e73b77ff755d6d5977b72efc551ac1ee
  她忽然觉得，科学研究随时随地都会发生，对自然的这种关注就在这对老夫妇的身体里，不是要特意地进入办公室，
  打开一篇文献再进入科研状态，而是在日常生活中，处处都在。
  #+END_QUOTE


- 3970-3972, 标注, 2025 年 9 月 15 日星期一 下午 6:57:30
  #+BEGIN_QUOTE md5: 03042d1e24f166c9158281cc1594dd81
  科学不是单纯的技术，而是积淀千年的一种精神。如果没有这种精神，单纯去做研究，那就只是在表象徘徊，
  做不好是很正常的事情。
  #+END_QUOTE


- 4001-4002, 标注, 2025 年 9 月 15 日星期一 下午 6:59:13
  #+BEGIN_QUOTE md5: 4246057467b0e905060f02c17796ffd0
  真实的科研就是这样的，不是永远都能正能量地去面对困难，有时负能量会喷涌而出将人淹没。
  #+END_QUOTE


- 4031-4033, 标注, 2025 年 9 月 15 日星期一 下午 7:01:34
  #+BEGIN_QUOTE md5: 60d4ed89ee62b3a503c99dc805abc839
  回到北京，和父亲走在清华的校园里，她对父亲说：“我对科学精神有了更深的理解。它能通过日常注入我体内，
  我感受到人类在自然中探索这件事本身的魅力，不知不觉越走越远。这真的很幸福。”
  #+END_QUOTE


- 4382-4384, 标注, 2025 年 9 月 15 日星期一 下午 9:32:57
  #+BEGIN_QUOTE md5: a2d81f5a4db9b5610c5cc5ab5037e21c
  《庄子·秋水》里，惠子怕庄子与他争权，庄子给惠子讲了一个故事：鸱得到一只腐烂的老鼠，害怕鹓雏与自己相争，
  便大声吓唬鹓雏。鸱并不知道，鹓雏只吃清洁新鲜的食物。想起这个故事，我笑得厉害。我应该像庄子那样，
  向惠子做出严正声明——我不吃腐鼠。
  #+END_QUOTE


- 4636-4638, 标注, 2025 年 9 月 15 日星期一 下午 10:26:33
  #+BEGIN_QUOTE md5: d571f4b4e51a44f02b81a34776590dc4
  只有从此处到彼处，才能认识新奇之物。我频繁停驻，得闻陌生枝条的姓名——原来，是松萝如龙须悬挂，
  是网脉柳兰在摇动粉紫花束，是象南星擎着媚红的浆果。在全然不同的地貌当中，土壤湿润而沉默，孕育着我想获知的消息。
  #+END_QUOTE


- 4964-4965, 标注, 2025 年 9 月 15 日星期一 下午 10:47:05
  #+BEGIN_QUOTE md5: 63c0aa223ce19917f1b25a824716f156
  委屈孤单之时，读书依然有用，古圣先贤告诉我正确的道路为什么常常艰难，艰难之时又为什么不能动摇。
  #+END_QUOTE

* Unwashed Entries                                                  :noexport:

