:PROPERTIES:
:ID:       0b4262f0-7326-4ad1-bd20-74d831e200b2
:END:
#+TITLE: 僧侣与哲学家-让-弗朗索瓦•何维勒;马修•理查德;赖声川
#+AUTHOR: Yang,Ying-chao
#+DATE:   2025-09-21
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:  oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :笔记:senglvyuzhex:note:ireader:unwashed:


- 73-75, 标注, 2025 年 9 月 18 日星期四 下午 6:46:41
  #+BEGIN_QUOTE md5: 24fc5324ec36964b0b0240238427cd10
  《僧侣与哲学家》法文版出版后，已翻译成二十几种语言，影响甚大。它像是一座搭在东西思想落差之上的桥梁，
  用聆听的、容忍的、温和的方式疏通双方，让东西方人各自照镜子，看看自己，看看我们这个世界，这个时代。
  #+END_QUOTE


- 177-179, 标注, 2025 年 9 月 18 日星期四 下午 6:54:37
  #+BEGIN_QUOTE md5: c859e23721610ee1b28e22fda457bde1
  简而言之，科学虽然很有趣，但是不足以让我的生命有意义。到后来发现做研究就是在细节中不停打转，
  我再也无法想像整个生命要献给这样的工作。同时我越来越被心灵生活所吸引，认为可以把它当作一种“心灵科学”。
  #+END_QUOTE


- 213-214, 标注, 2025 年 9 月 18 日星期四 下午 9:09:06
  #+BEGIN_QUOTE md5: 31755d35fd033b12036f26482e6e0c31
  哲学家并不满足于教导本身，而是要有能力把所教导的反映出来，在自己的生活中以身作则。
  #+END_QUOTE


- 217-218, 标注, 2025 年 9 月 18 日星期四 下午 9:09:50
  #+BEGIN_QUOTE md5: 79c3c2293e3cbb0512487c1f2d3edce6
  西方哲学里面一向有双重的需求，需要发展理论，同时要在生活中去实践，实际地融入那个理论。
  所以说在古典哲学的时代中，西方和东方没有根本上的差距。
  #+END_QUOTE


- 222-223, 标注, 2025 年 9 月 18 日星期四 下午 9:10:52
  #+BEGIN_QUOTE md5: 2820179bf8c6cf437fe1a3c004ac731e
  可是这些美丽的物品到底带给你什么？这套理论带给你什么？随便找一个古老的教条，然后去实践它、融入它，是不够的。
  这个教条必须要有价值！
  #+END_QUOTE


- 228-231, 标注, 2025 年 9 月 18 日星期四 下午 10:53:15
  #+BEGIN_QUOTE md5: 8b5b02348e0af80418eb536af7ba95fc,1b9cab006bbd794ff002ba04606c85fc
  我一直有很多机会接触许多极有魅力的人士。可是他们虽然在自己的领域中都是天才，
  但才华未必使他们在生活中达到人性的完美。具有那么多的才华，那么多的知识和艺术性的技巧，并不能让他们成为好的人。
  一位伟大的诗人可能是一个混蛋，一位伟大的科学家可能对自己很不满，一位艺术家可能充满着自恋的骄傲。各种可能，
  好的坏的，都存在。
  #+END_QUOTE


- 251-252, 标注, 2025 年 9 月 18 日星期四 下午 10:58:08
  #+BEGIN_QUOTE md5: 639f93a4842778105f1d5b708b39325a
  单单仁波切这个人的存在就给了我很深的影响，从他体内散发出来的那种深度、力量、平静和爱，让我的心慢慢打开来。
  #+END_QUOTE


- 267-267, 标注, 2025 年 9 月 18 日星期四 下午 10:59:49
  #+BEGIN_QUOTE md5: 386bb4ce31675a348e8cba3886c3f6ac
  在那个时代，一切都被怀疑，一切都被探索，不只是通过书本，而是在现实生活中。
  #+END_QUOTE


- 274-275, 标注, 2025 年 9 月 18 日星期四 下午 11:01:08
  #+BEGIN_QUOTE md5: 51847240e4be4ae4502617668aead205
  他告诉我说：“佛法里面有许多有趣的东西，但是不要迷失在纯粹的理论研究中，这样反而会干扰你的修行，
  而修行就是佛法的心脏，是所有内在转化的基础。”
  #+END_QUOTE


- 279-281, 标注, 2025 年 9 月 18 日星期四 下午 11:02:02
  #+BEGIN_QUOTE md5: 926875674e418a63adf947141b916987
  佛法中所谓的智慧就是让现象世界的本质清晰，也就是让心的本质清晰。我们是什么？这个世界是什么？到最后，
  最重要的就是要去直接体验绝对真理，超越所有的概念，这就是智慧最根本的面貌。
  #+END_QUOTE


- 296-299, 标注, 2025 年 9 月 19 日星期五 上午 7:53:12
  #+BEGIN_QUOTE md5: 8a97cb2b28391a3d046c8f2ed5b8b5ae
  但最重要的科学就是如何认识自己，以及如何认识实相。在此，最关键的问题是：“现象界的本质是什么？心的本质是什么？
  ”在比较实际的层面，问题是：“快乐和痛苦的钥匙是什么？痛苦来自哪里？什么是无知？什么是心灵上的认识？什么是完美？
  ”如此的发现可以被称为知识，或智慧。
  #+END_QUOTE


- 300-301, 标注, 2025 年 9 月 19 日星期五 上午 7:53:48
  #+BEGIN_QUOTE md5: e773be640d2adce21ef6e07394fdbd11
  痛苦是无知的结果，所以必须要被驱除的是无知。而最根本的无知就是相信自身真正存在，相信现象界的实在性。
  #+END_QUOTE


- 331-332, 标注, 2025 年 9 月 19 日星期五 上午 8:03:10
  #+BEGIN_QUOTE md5: 85859865ab0417370591af1fcdc39d0e
  心灵的追寻，当它带来真正内在的转化时，是一种全然活生生的经验，会带来不断更新的感觉。
  像佛法这样一个形而上的体系，是永远没有办法“老化”的，因为它面对的是存在的最根本问题。
  #+END_QUOTE


- 336-339, 标注, 2025 年 9 月 19 日星期五 上午 8:05:14
  #+BEGIN_QUOTE md5: b0a0b82d484b34bc89660c4aa86ab190
  不可否认的，能够知道地球确切的形状和所有的尺寸，这算是进步。但是地球是圆的还是扁的，
  对存在的意义没有太大的差别。医学上的任何进步只能让我们治疗一些还会再来的苦痛，而这一切的苦痛最后都要走向死亡。
  我们可以终止一场冲突，或是一场战争，但是过些时候这些还会再来，除非人的心能够做一个改变。
  #+END_QUOTE


- 375-378, 标注, 2025 年 9 月 19 日星期五 上午 8:12:07
  #+BEGIN_QUOTE md5: b002c889c2f4a7b8f467633b64037101,d8b9e811ea39d533eb2cf0ebed996ccf
  我现在回想起来，十九岁的时候，为什么选择哲学而不是文学或历史作为我大学的主修科目；事实上，
  文学和历史对我来说同样具有吸引力，但是我当时感觉到，似乎只有哲学才可能带给我开启其他学问的钥匙，
  哲学不只涵盖文学和历史，甚至可以涵盖科学。而哲学这一门学问同时也是一门智慧，换句话说，
  它是一种连结伦理体系的生活艺术。
  #+END_QUOTE


- 391-396, 标注, 2025 年 9 月 19 日星期五 上午 8:15:04
  #+BEGIN_QUOTE md5: 8c192d7bea3e2e9d3e1dd53268aff7bc
  1970 年，我写了第一本泛谈政治的书（之前我已经出版了两三本关于政治的书，但是它们的焦点完全在法国）。这本书叫作
  《没有马克思，没有耶稣》。书名本身意味着双重的否定：否定政治极权主义，否定宗教极权主义。
  这本书当时引起了某种程度的惊叹，因为在书中我坚持 20 世纪的革命将会是自由主义的革命，而不是社会主义的革命。
  我说的革命是自由市场经济和自由民主的革命：私有财产对抗集体拥有、自由贸易对抗中央计划经济、
  言论自由对抗中央审查制度、民意政府对抗至高无上的极权政治。
  #+END_QUOTE


- 452-453, 标注, 2025 年 9 月 19 日星期五 下午 12:41:43
  #+BEGIN_QUOTE md5: 4e9c81dd63a16ea5cf50a3d3c4142331
  如果我们对宗教的定义是要盲目地接受一种教义，不需要自己重新发觉那个教义的真理，那佛教就不是一个宗教。
  #+END_QUOTE


- 488-489, 标注, 2025 年 9 月 19 日星期五 下午 12:45:30
  #+BEGIN_QUOTE md5: f4f938aba15a72a9ae70d978d77b5cf0
  佛陀教义的实在内容当时就被他的同辈确立清楚了。你所提到的超自然叙述与教义本身无关。那些是后来经历许多世纪之后，
  人们所写的圣人传记。
  #+END_QUOTE


- 504-505, 标注, 2025 年 9 月 19 日星期五 下午 6:30:59
  #+BEGIN_QUOTE md5: 7ebfe51b4c30451849569a2d6f44bb2c
  痛苦是一种深沉的不满状态，可能和肉体痛苦连在一起，但首先以及最重要的是一种精神的经验。
  #+END_QUOTE


- 506-507, 标注, 2025 年 9 月 19 日星期五 下午 6:31:19
  #+BEGIN_QUOTE md5: 4230f98b9c14409598719a7601484251
  当“自我”，我们一直珍惜和保护的那个“我”受到威胁，或是得不到他想要的时候，就是痛苦生起的时候。最激烈的肉体痛苦，
  可能根据我们不同的心理状态而产生非常不同的经验。
  #+END_QUOTE


- 507-510, 标注, 2025 年 9 月 19 日星期五 下午 6:31:44
  #+BEGIN_QUOTE md5: 24cdd0892d143aec7dd446e937b39940
  一般人生命中的目标，像权力、财产、名声、感官的享受，可以令人得到暂时性的满足，但是不可能永远满足，
  总有一天这些一定会成为不快乐的因，它们没有办法带来永久的满足，或者说一种不受外界状况动摇的内在和平。
  我们一辈子都在追寻这些世俗目标，我们得到真正快乐的机会如同想捕鱼的渔夫，但他却把渔网抛向干涸的河床。
  #+END_QUOTE


- 531-535, 标注, 2025 年 9 月 19 日星期五 下午 6:37:28
  #+BEGIN_QUOTE md5: 4d978b82df7d919a05fc22cffbb1a76e,86c520619379ccb6c3e0ca6fa3ab7d68
  稳定的心灵修行特质之一，就是不被外界事务所影响，不论这些事物是有利或无利的。
  修行者的心就像一座大风吹不动的山。对于他所遭遇的困难，他不受困扰；对于他的成功，他也不会欣喜若狂。
  不过这种内在的平衡既不是无感也不是不在乎。伴随的是一种内在的喜悦，一种心灵的开阔，
  这种内在喜悦对外的表现是一种不移的慈悲。
  #+END_QUOTE


- 539-540, 标注, 2025 年 9 月 19 日星期五 下午 6:38:25
  #+BEGIN_QUOTE md5: f3152ef2fd83a65efea172370b5727cf
  佛教并不是要让自己融合或消失到一种模糊、不确定的状态中，反而是要清晰地认出“自我”没有实质的存在，
  这才是你所有问题的根源。
  #+END_QUOTE


- 542-543, 标注, 2025 年 9 月 19 日星期五 下午 6:39:14
  #+BEGIN_QUOTE md5: dd9f201cbd90894bf103ec72d6c60597
  对自我的执着就是无知最基本的表现，也是所有负面情绪的根源。
  #+END_QUOTE


- 562-563, 标注, 2025 年 9 月 19 日星期五 下午 6:42:05
  #+BEGIN_QUOTE md5: 3c0cd63428f5299eba16ccd8bf25898a
  佛法号称有八万四千个法门。数字之多，为的是指出其实任何人可以从任何地方开始。
  #+END_QUOTE


- 571-572, 标注, 2025 年 9 月 19 日星期五 下午 6:44:00
  #+BEGIN_QUOTE md5: 3166591a2edff8b73bb103ff657b979a
  一种初步方法就是向负面情绪下药：我们要培养耐心来降伏愤怒，培养不执着来降伏欲望，分析因果的运作来降伏混乱，
  也可以说降伏判断力的缺乏。
  #+END_QUOTE


- 582-583, 标注, 2025 年 9 月 19 日星期五 下午 6:45:13
  #+BEGIN_QUOTE md5: 22e837b1950815ffeedfcdaafd99ecaa
  并不排除任何所需要用的方式，以及任何所需要用的力量，可是这一切绝对不能带愤怒。在内心深处，
  我们必须保持一种别人无法征服的慈悲，以及别人无法耗尽的耐性。
  #+END_QUOTE


- 592-596, 标注, 2025 年 9 月 19 日星期五 下午 6:46:51
  #+BEGIN_QUOTE md5: ead2bae384b8d328518bc3a1a98ec0b2
  夏天的云从远处看是壮观而立体的，感觉简直可以坐到上面,可是当我们真的走到它里面的时候，几乎什么都没有。
  搞了半天，完全没有任何的实质。用同样的方式，我们正眼去看一个念头，追溯它的起源，一样找不到任何具体的东西。
  当你发现这一点的那一刹那，那个念头就会消失掉。这称为“通过认识念头的本质来解放它”，意思是要认出念头的“空性”。
  我们一旦解放一个念头，就不会产生连环作用，反而像是从天空中飞过去的一只鸟，消失了，却不留痕迹。
  #+END_QUOTE


- 607-611, 标注, 2025 年 9 月 19 日星期五 下午 6:49:05
  #+BEGIN_QUOTE md5: 72db545e72f96cf65c15b8dbf909c81c
  首先，非常重要的，我们要了解在佛教里面所谓的“轮回”，绝对不是某一种“个体”附身在另外一个个体上，
  也不是一种心灵转换，因为没有所谓的“灵魂”。如果我们坚持要用“个体”来思考这件事，而不是用“功能”和“持续性”来思考，
  根本无法去了解佛教中关于轮回的概念。有句话说：“在轮回的项链之中，并没有穿过珠子的线。”
  通过许多次转世所留下来的并不是一个“人”的身份，而是一种被培养出来的意识流。
  #+END_QUOTE


- 626-630, 标注, 2025 年 9 月 19 日星期五 下午 6:53:19
  #+BEGIN_QUOTE md5: 8a6758a11ebdaeeba362344c3ff3f9fc,8e1a8aa31ef938e54f432068bff3c42b
  迷信，这只是反映佛教有各种丰富的方式，来提醒我们要一直保持对心的觉察性。在佛教中，
  四种自然元素都被用来提醒我们：风所吹动的经文旗，油灯的火，通过上升的热气转动法轮，
  刻上咒语的石头以及推动水动式法轮的溪流。这么一来，我们所作所为，自然界的每一种元素，我们视线之内的一切，
  都可以刺激我们从内在祈祷，激励我们的利他念头。当一个西藏人将印着经文的旗子挂起来，他想的是：
  “不论吹过这些祈祷文的风吹向哪儿，愿它所碰触到的所有众生，能从他们的痛苦中或是痛苦的因中得到解脱；
  愿他们能经验快乐以及快乐的因。”
  #+END_QUOTE


- 675-679, 标注, 2025 年 9 月 19 日星期五 下午 6:58:27
  #+BEGIN_QUOTE md5: 8107dd561b2cf4d0d1fb452a230cfa86
  只要我们认为自我是一个真正的个体，会不断地追逐那些好的或有利的东西，同时排斥不好或有害的东西；
  但是当我们一旦认识到自我并非真正的存在，所有被吸引或排斥的冲动都会消失，
  就像我们误以为是绳子是蛇所经历的恐惧一样。自我无始无终，在现在时刻中，它的存在完全是我们的心所给予的。所以
  “涅槃”并不是一切的毁灭，而是对一切事物本质的最终认识。
  #+END_QUOTE


- 683-685, 标注, 2025 年 9 月 19 日星期五 下午 6:59:35
  #+BEGIN_QUOTE md5: 6f84f79d2f496d78db6c071b48d801f6
  佛法接受意识有其连续状态，但在这连续状态中，佛法否认有任何具体的、永恒的，以及独立的自我存在。
  佛法修行的精华就是要抛弃这种对自我的幻觉，而这个幻觉创造出我们对世界的错误画面。
  #+END_QUOTE


- 723-727, 标注, 2025 年 9 月 19 日星期五 下午 8:01:21
  #+BEGIN_QUOTE md5: 36ac31b4671a239b7dec9836560f4d60
  这两世纪以来，西方对禅定科学的兴趣一直不大。现代心理学创始者之一，威廉·詹姆斯(William James )
  曾经写过令我印象深刻的一段话。就我的记忆，他说：“我试着让我的思想停顿几秒钟。很明显的，这是不可能的，
  思想瞬间又产生。”这样观察会令许许多多的西藏隐士感到好玩，因为他们花了这么多年的时间降伏了他们的心，
  他们可以长时间超越任何意念上的联想,保持一种觉性。
  #+END_QUOTE


- 748-752, 标注, 2025 年 9 月 19 日星期五 下午 8:04:06
  #+BEGIN_QUOTE md5: 83cdf41cc0d254be8b9ba004d20e31b9
  刚开始的时候，为了要让自己的意念慢下来、平静下来，我们做一种“单点专注”的训练。
  就是把意念集中在一个外在的物件上，好比说一尊佛像，或者一个内在的对象，好比说慈悲的概念，或是一个观想中的意象。
  到后来你会到达一种平衡的状态，透明、清晰的觉性状态，客体和主体二元对立不再存在了。
  念头偶尔还会在这种觉性中生起，但在这个时候它自动会把自己解开，不留下任何痕迹，就如同飞过天空的小鸟，
  也同样不留下任何痕迹。
  #+END_QUOTE


- 763-764, 标注, 2025 年 9 月 19 日星期五 下午 8:06:06
  #+BEGIN_QUOTE md5: 2ba5bcabcdcdff7564551dacd7a65481
  佛法中，有三种条件使一句话成立：直接经历、不可推翻的演绎以及值得信赖的论证。以上我们谈的都是属于第三类。
  #+END_QUOTE


- 817-819, 标注, 2025 年 9 月 19 日星期五 下午 8:15:00
  #+BEGIN_QUOTE md5: 5576ae914a0f22cee00d4d066df50183
  当信仰离开理性，就变成迷信，当信仰背叛理性时更甚 之。但当信仰与理性合并的 时候，就能够防止理性变成
  一种纯粹知识性的游戏。
  #+END_QUOTE


- 890-891, 标注, 2025 年 9 月 19 日星期五 下午 10:50:12
  #+BEGIN_QUOTE md5: bbff38f5171676a11d071f9780fbd05f
  我个人相信人类是有程度的自由，但是我不相信灵魂的存在，也不相信灵魂的不朽。
  #+END_QUOTE


- 926-927, 标注, 2025 年 9 月 19 日星期五 下午 10:54:42
  #+BEGIN_QUOTE md5: fcda27218f3834b69cd3dacb730327d4
  佛法不认为有任何不朽的个体，而是认为有一种不断在变化的连续状态，一种互相依赖的状态。
  #+END_QUOTE


- 970-972, 标注, 2025 年 9 月 20 日星期六 下午 2:04:33
  #+BEGIN_QUOTE md5: 23eef2617f729fe341a95cfd15284948
  初步看来，毒品所制造出来的极乐状态只不过是某一种幸福，就像是模拟智者的喜悦。其实这种极乐就是痛苦的伪装。
  它带来疏离，带来不满足，终究是痛苦，永远都感觉少了什么。它会毁灭一个人的心理，并且把他带到生理的毁灭边缘。
  #+END_QUOTE


- 972-975, 标注, 2025 年 9 月 20 日星期六 下午 2:18:31
  #+BEGIN_QUOTE md5: 617d415cda5b13833bee198bfd1f5dcb
  智者的平静和喜悦不需要通过外物，也不仰仗生命的各种状况，无论是有利或不利的。这种喜悦绝不是暂时性的，它会增长、
  会增强。它不会将人导向一个虚假的天堂中（说得更准确一点，应该是地狱），反而让人更为开放，
  这是一种可以被传达以及传递的平静。
  #+END_QUOTE


- 1015-1016, 标注, 2025 年 9 月 20 日星期六 下午 2:30:39
  #+BEGIN_QUOTE md5: dfa03aee0064a3c54022636c11c8eb3a,d6106bb95820ed292972c423a091e30d
  像这样允许形而上学寄生在科学的现象在历史中周期性地出现，事实上从公元 8 世纪就开始了。这种做法对我而言是不严谨的。
  #+END_QUOTE


- 1018-1019, 标注, 2025 年 9 月 20 日星期六 下午 2:32:31
  #+BEGIN_QUOTE md5: d4c26affa2eef37d6c6c38ca04b21af1
  根据佛法，意识和它暂时连接在一起的身体是互动的。死亡之后，这个意识河流持续着，
  在每一次生和每一次死之间经历着不同层次的存在。
  #+END_QUOTE


- 1021-1023, 标注, 2025 年 9 月 20 日星期六 下午 2:29:57
  #+BEGIN_QUOTE md5: c8ceffaf16ceab8cc6b471f27cab9ad7
  微细层面则是意识的持续状态，从一辈子持续到下一辈子，这种持续性是无始无终的，因为意识不可能无中生有，
  也不可能从无生命的物质中生起。每一刹那的意识只能从前一刹那的意识中生起，结果也只可能是下一刹那的意识。
  #+END_QUOTE


- 1059-1059, 标注, 2025 年 9 月 20 日星期六 下午 2:35:24
  #+BEGIN_QUOTE md5: 04699b5155cc7a8b7a06240611c5d7d2
  唯一真正的证据就是抛开任何主观经验的独立证据。
  #+END_QUOTE


- 1060-1062, 标注, 2025 年 9 月 20 日星期六 下午 2:36:06
  #+BEGIN_QUOTE md5: e98e838dfcc73b3e8f59a28d44381714
  安德列·米高(Andre Migot)曾在他写的《佛陀》(Le Bouddha）一书中说：“当信仰离开理性，就变成迷信，
  当信仰背叛理性时更甚之。但当信仰与理性合并的时候，就能够防止理性变成一种纯粹知识性的游戏。”
  #+END_QUOTE


- 1073-1076, 标注, 2025 年 9 月 20 日星期六 下午 4:20:14
  #+BEGIN_QUOTE md5: b2aed1d90fbd6b66bbe73939f3ac16da
  西方神秘传统也有差不多类似的情况，以十字架的圣约翰、西耶纳的圣凯萨琳，以及号称他们一生中在忘我、
  出神或狂喜状态中见过上帝的人士为例，他们非常确定自己经历了神圣的境界。绝大多数的基督徒相信他们，
  毫不怀疑他们的诚恳或谦虚。可是怎么说，他们的见证不等于理性的证据。
  #+END_QUOTE


- 1166-1167, 标注, 2025 年 9 月 20 日星期六 下午 4:34:05
  #+BEGIN_QUOTE md5: 15522e3c4d28f240ddec5c70ae13e29e
  禅定的体验是直接见到心必须接受的真相，因为这种真相在那个领域中符合事物的本性。
  #+END_QUOTE


- 1205-1206, 标注, 2025 年 9 月 20 日星期六 下午 5:50:15
  #+BEGIN_QUOTE md5: 6d3d57a6ccf6eba9ac7e036887a25113
  19 世纪某些哲学家，像叔本华，被佛教智慧吸引的理由是认为它可以提供一种方法，通过忘记自我而达到某种宁静境界。
  #+END_QUOTE


- 1211-1213, 标注, 2025 年 9 月 20 日星期六 下午 5:50:56
  #+BEGIN_QUOTE md5: eecec20ab71df863059cd1ab701f7fbb
  我们必须懂得如何让这种念头和情绪得到解脱。念头解脱的意思就是要消除它在心中的任何痕迹，让它不要再被混乱所捆绑，
  不然它非常容易创造出连锁反应。
  #+END_QUOTE


- 1218-1220, 标注, 2025 年 9 月 20 日星期六 下午 5:51:49
  #+BEGIN_QUOTE md5: d89f63494a1d013ff5e3a16e958c2891
  向自己的心下工夫的关键不只是在于辨识出自己的意念和情绪，更要让它们消融，在心的宽广空间中消失。这有很多技巧,
  最重要的就是不要专注在情绪的内容上，也不要专注在引发这些情绪的原因和状况上，而是要追踪这些情绪直到它们的根源。
  #+END_QUOTE


- 1225-1227, 标注, 2025 年 9 月 20 日星期六 下午 5:54:43
  #+BEGIN_QUOTE md5: 6b7cade3d26f4e70da912829959df8df
  如果你想看到的话，你就必须暂时斩断意念的流动，不要延长过去的念头，不要激起未来的念头，就停住在那儿，
  不管是多短的时间，停在此刻的感受中，不受任何妄念的束缚。慢慢地，你就会进步，可以在那种觉性中更持久。
  #+END_QUOTE


- 1227-1240, 标注, 2025 年 9 月 20 日星期六 下午 6:00:38
  #+BEGIN_QUOTE md5: a5d0046c4cb8ace8af65277e9803e666
  湖如果一直有波纹，它的水就永远是朦胧的。
  但如果水波平息了，泥巴沉到底部，水的清晰度就又回来了。同样地，当妄念平息下来，心越来越清晰，
  到这个时候就比较容易发觉它真正的本性。接着要开始研究妄念的本质。要这么做，
  你甚至可能要故意搅起自己内在的强烈情绪，也许可以想一想曾经伤害过你的人，反过来也可以想一想会引起你欲望的事情。
  让这个情绪出现在你意识的范围中，用你内在的辨识力把它定住——这需要轮流运用分析式的探讨和禅定两种方式。
  最开始这个情绪会控制你，令你执着，它会不断回来，可是你必须继续仔细地研究它：它的力量到底来自哪里？
  它本身并没有血肉的生命，本身不具有伤害我们的能力。情绪生起之前，它在哪里？当它出现在我们心中，有任何特质吗？
  有确定的位置、形状和颜色吗？当它离开我们意识的范围时，它会到别的地方去吗？我们越去研究它，
  这个似乎很强大的念头越是逃避着，根本不可能抓住或者指出它。我们会到达一种“找不到”的境界，
  然后在这境界下禅定一会儿.在技术上来讲，这个叫作“认识念头的空性”。是一种内在单纯的境界，一种清晰的心性和觉性，
  任何概念都被剥光。当你了解到念头只不过是这种觉性意识的显现，念头就会失去它们束缚的具体性。到后来，
  经过长期的勤劳修持，解脱的过程变得很自然。当新的念头生起,它自己就会解放自己，不再会干扰，也不再会控制你的心。
  念头生起的那一刹那，它们就自我释放，不再干扰和主宰心。念头的形成与消失一样快，像是用手指头在水上画画一样。
  #+END_QUOTE


- 1257-1258, 标注, 2025 年 9 月 20 日星期六 下午 6:02:13
  #+BEGIN_QUOTE md5: 0195bb288b0c3f1630b123add121c927
  耐性给我们力量，让我们选择正确的行动，不因愤怒或渴望报仇而变得盲目，因为那样会剥夺我们的判断能力。
  #+END_QUOTE


- 1256-1258, 标注, 2025 年 9 月 20 日星期六 下午 6:02:24
  #+BEGIN_QUOTE md5: 45ec6cc0076200a0e9b09e9bf69ffde3
  真正的耐心不是软弱的象征，反而是力量。这意思并不是让一切被动地发生。耐性给我们力量，让我们选择正确的行动，
  不因愤怒或渴望报仇而变得盲目，因为那样会剥夺我们的判断能力。
  #+END_QUOTE


- 1259-1265, 标注, 2025 年 9 月 20 日星期六 下午 6:03:54
  #+BEGIN_QUOTE md5: 6e1b2362476493c07e195388aede2a43,a416663aac308dc0677540b5e9ade4be
  如何达到真正的耐性和非暴力，就是选择最利他的解决方案。如果甜言蜜语背后的动机是欺骗，看起来是善良，
  但事实上是非常暴力的。反过来说，一个母亲责骂或鞭打她的小孩，动机是爱她的小孩，看起来是暴力行为，
  但事实上是一种善良。重要的是行为背后的动机，以及行为的最后结果。我们如何选择，就看如何运用智慧。因而在理论上，
  使用暴力来达到善良的结果或许可以接受，但实际上，这是非常困难的。暴力会引起更多暴力，通常会产生灾难性的后果。
  所以最好要避免冲突,如果无法避免，只好试图制伏正要使出暴力的人，不用超出真正需要的手法，
  也不要加入任何负面的情绪。
  #+END_QUOTE


- 1275-1277, 标注, 2025 年 9 月 20 日星期六 下午 6:12:55
  #+BEGIN_QUOTE md5: 0fdd3a06e797d74052271a72553d66f7
  我要再次强调，我不是说要切除掉所有属于人性的情绪，而是要得到一个宽广而平静的心，
  令这个心不再成为我们情绪的玩物，不再被挫折所动摇，不再被成功所陶醉。
  #+END_QUOTE


- 1287-1288, 标注, 2025 年 9 月 20 日星期六 下午 6:14:50
  #+BEGIN_QUOTE md5: 597640c54362ee059433edca44715d5e
  我们不想要的情绪就是会使我们判断力错误或瘫痪的情绪，当然不是能激励我们去完成大事业的情绪。
  #+END_QUOTE


- 1289-1291, 标注, 2025 年 9 月 20 日星期六 下午 6:15:11
  #+BEGIN_QUOTE md5: 19470187609be6669424be93fa44997d
  我们必须分辨清楚什么是负面的情绪，像是欲望、愤怒和骄傲，这些情绪会强化自我为中心的观点，而正面的情绪，
  像是利他的爱、慈悲和信心，这些情绪可以渐渐地让我们从那些负面的和自我为中心的习惯中逃脱出来。
  正面情绪不会干扰我们的心，它们会加强它，让它更稳定，更勇敢。
  #+END_QUOTE


- 1293-1295, 标注, 2025 年 9 月 20 日星期六 下午 6:16:48
  #+BEGIN_QUOTE md5: 6a21b5179d2fa885d9094c37a9b3efe9
  事实上，佛教徒无止尽地在培养一个主要的野心，那就是排除全宇宙众生的痛苦。这种野心可以防止我们掉进无为，
  让我们意志坚强，信心坚定。所以说分辨正面和负面的野心，分辨利他和自我为中心的野心，是很重要的。
  #+END_QUOTE


- 1309-1311, 标注, 2025 年 9 月 20 日星期六 下午 6:18:31
  #+BEGIN_QUOTE md5: 1018fc708ab34c1038a04aee17b096d1
  多少不快乐的人，他们的生命被嫉妒所毁灭！只要他们能够真正认识到嫉妒是多么不真实，让它在心中自动消融，
  像是一朵云消失在空中，这样一来不但能够远离嫉妒而得到平静，同时也不会让嫉妒发展到促使他们犯罪的地步。
  #+END_QUOTE


- 1313-1315, 标注, 2025 年 9 月 20 日星期六 下午 6:19:06
  #+BEGIN_QUOTE md5: ed9f08548346fc827124f09c42823600
  所有的哲学对于这一点的看法都是相同的。东西方共同拥有一种实际智慧的根基，
  就是如何针对现实的关系来管理我们心理状态的艺术，如此方能避免所有会令我们痛苦和不满的过度行为。
  #+END_QUOTE


- 1355-1357, 标注, 2025 年 9 月 20 日星期六 下午 9:47:32
  #+BEGIN_QUOTE md5: 9a82d04b5ce7a46c81d704bdc8216852
  非要限制自己只去用物理方法来测量或侦测，而不愿通过内省来探讨心的本质，这会让自己注定失败。
  佛法以及其他道路中的修行者，已经运用这种内省方法超过两千年了。
  #+END_QUOTE


- 1462-1463, 标注, 2025 年 9 月 21 日星期日 上午 10:15:46
  #+BEGIN_QUOTE md5: ecbb18860a297ec5e0f16acd6f70992b
  没有一样东西是独立自存的，一切都是通过因和条件的相互依存而显现。
  #+END_QUOTE


- 1461-1465, 标注, 2025 年 9 月 21 日星期日 上午 10:16:39
  #+BEGIN_QUOTE md5: 3da813573f30bcb886f5e09df2307aad,b9835f1090a925496a13eb2dd0861bc4
  佛法完全承认现象界不可避免地受因果定律主宰，但是定律或所主宰的现象不是永恒的、独立自存的个体。
  没有一样东西是独立自存的，一切都是通过因和条件的相互依存而显现。

  - 如果没有物体，地心引力的定律就不存在。
  - 石头由原子组成，这些原子本身等同于能量。
  - 彩虹的形成是因为一道阳光和一朵雨云之间的互动。


  它存在，但却不可捉摸。只要少了一个组成因素，现象就会消失。
  #+END_QUOTE


- 1475-1478, 标注, 2025 年 9 月 21 日星期日 上午 10:18:22
  #+BEGIN_QUOTE md5: 3d6c28befd62823c140df2662959645c
  柏拉图和亚里士多德都同意，虽然是不同的理由，数学公理不需要被证明，因为它们的真理是不容质疑的……19
  世纪许多数学家认为欧基里德的假定既不是‘是’，也不是‘非’，只不过是游戏的规则而已……
  在本世纪中才开始发现数学公理其实是直接或间接地由经验而导致的……要相信数学中包含的真理，
  属于独立于经验之外的物理现实的定律，并没有多少证据。“
  #+END_QUOTE


- 1485-1486, 标注, 2025 年 9 月 21 日星期日 上午 10:19:46
  #+BEGIN_QUOTE md5: 5613f47b0ce59a27e61117882d0b2928
  不要把物理与生物的知识和数学的假定混为一谈，因为物理和生物是一种持续来回于观察、理论和实验之中的过程，
  而数学在本质上是一种”自原”的科学。
  #+END_QUOTE


- 1500-1501, 标注, 2025 年 9 月 21 日星期日 上午 10:22:15
  #+BEGIN_QUOTE md5: 1cf1213638c2f36daebdec86d331dd9a
  因果律的基础之一是说，如果一件事情所有的因和条件没有组合好，这个事件不可能发生，而当这些组合好了，
  它不得不发生。
  #+END_QUOTE


- 1627-1628, 标注, 2025 年 9 月 21 日星期日 上午 11:09:25
  #+BEGIN_QUOTE md5: d989aa1c31fa9364ae0507fd06ce5b27
  没有测量的系统，就不可能认识初级粒子。同理，脱离任何人为概念的宇宙也不可能被人的头脑所理解。
  #+END_QUOTE


- 1633-1634, 标注, 2025 年 9 月 21 日星期日 上午 11:09:58
  #+BEGIN_QUOTE md5: 22be7e6c938ba7e014b6eb1b109af6d3
  任何科学都必须从某些假设开始,然后从经验的领域中出发，为的是用经验来证实或否定这些假设。
  #+END_QUOTE


- 1665-1667, 标注, 2025 年 9 月 21 日星期日 上午 11:19:30
  #+BEGIN_QUOTE md5: af753313acc62bbd652a4612882dabd1
  它是一个道路，一种救赎的方式，引导佛陀走向证悟。它是一个方法，一种向心灵强烈下工夫而得到解脱的方式。“所以，
  我认为用最简单的方式来定义佛教，就是首先把它视为一条道路。这个道路的目标就是要达成我们所谓的”完美”：究竟知识、
  证悟，或者，用技术性的名词来说，佛的境界。
  #+END_QUOTE


- 1686-1688, 标注, 2025 年 9 月 21 日星期日 上午 11:24:00
  #+BEGIN_QUOTE md5: 2d1a06d3b5d8f03480e3ee30f5a296a9,fb6d237f07b704f4b26b52adfc6160fd
  对苏格拉底来说，所谓学习并不是学任何东西。当我们学习的时候，我们事实上在回忆。
  所有人都拥有一种在出生之前就存在于内的知识，一种与生俱来的知识。在生命的过程中，错误的知识、
  意见和人为的心理状态,会掩盖住你刚才称为核心金块的东西。苏格拉底为了表现学习基本上就是回忆的过程，
  #+END_QUOTE


* Unwashed Entries                                                  :noexport:


- 1696-1699, 标注, 2025 年 9 月 21 日星期日 上午 11:25:54
  #+BEGIN_QUOTE md5: c63ce40ead72113f3dd8e974dc0fec8d
  一位伟大的佛教导师曾说：“不是现象把你捆绑住，而是你对现象的执着把你捆住。”所谓“娑婆世界”，也就是“
  存在世界的恶性循环”，是由无知所撑起的，是一个痛苦、散乱以及混淆的世界。我们永无止境地在娑婆世界之中游荡，
  被我们行为的力量，也就是“业”所带动。“
  #+END_QUOTE

- 1696-1699, 标注, 2025 年 9 月 21 日星期日 上午 11:25:59
  #+BEGIN_QUOTE md5: fd9647f6327b1a7170f55e702a3663d3
  世界本身并不是坏的，只是我们觉知它的方式错了。一位伟大的佛教导师曾说：”不是现象把你捆绑住，
  而是你对现象的执着把你捆住。“所谓”娑婆世界”，也就是“存在世界的恶性循环”，是由无知所撑起的，是一个痛苦、
  散乱以及混淆的世界。我们永无止境地在娑婆世界之中游荡，被我们行为的力量，也就是“业”所带动。“
  #+END_QUOTE

- 1717-1721, 标注, 2025 年 9 月 21 日星期日 上午 11:28:54
  #+BEGIN_QUOTE md5: 6c17c3267db4fe2c2e08fda1270ecc95
  除非有能力让自己解脱出来，轮回的循环几乎是无止境的。因为我们一直无法停止负面和正面行为的交替，
  所以就一直上上下下，从这一辈子到下一辈子，有时候快乐，有时候痛苦，就像一个水车上的水桶，轮流起起落落。
  整体而言，这个现象世界是无始无终，但是每一个个别生命有潜力打破这个恶性循环，
  通过净化自己意识河流的方式达到证悟，从此从轮回循环中解脱出来。换句话说，我们可以终止痛苦的原因。
  #+END_QUOTE

- 1728-1729, 标注, 2025 年 9 月 21 日星期日 下午 2:21:25
  #+BEGIN_QUOTE md5: 57bdfdbf39eef1ec4c07810d596936f8
  涅槃”在西藏翻译中是”超越痛苦“的意思。如果有任何东西会消失，绝对是痛苦以及痛苦所产生的混乱。
  #+END_QUOTE

- 1750-1752, 标注, 2025 年 9 月 21 日星期日 下午 2:26:23
  #+BEGIN_QUOTE md5: 5a0143b3f9b8c504b04114d81b2ab6da
  大乘强调的是，只让自己从痛苦中解脱是一个极为有限的目标。当我们承诺走上这条道路的同一刹那，
  动机应该是为所有众生而成佛。要转换自己，为的是得到能力来帮助其他人从痛苦中解脱自己。
  #+END_QUOTE

- 1766-1769, 标注, 2025 年 9 月 21 日星期日 下午 2:30:27
  #+BEGIN_QUOTE md5: d273511720ee4e6c2c266049a0ab65e4
  这些不幸既非天意，也不是固定的命运和机遇，而是我们自己行为的长期后果。它们像是我们自己射出去的箭，
  又回到我们身上来。我可以理解，佛法中”业“的整个概念可以令人很不安。它教我们的是，
  任何发生在我们身上的事绝不是巧合。我们现在受苦的因正是自己创造出来的。
  #+END_QUOTE

- 1773-1776, 标注, 2025 年 9 月 21 日星期日 下午 2:31:57
  #+BEGIN_QUOTE md5: 6451359cbf47b96f58a7c797d736a2d2
  我们没有理由抗拒现在的遭遇。我们的态度也不该是屈服，因为现在有机会来弥补这个状况。
  正确的概念就是要认清需要做的事，或者不该做的事，为的是建立快乐，从痛苦中逃离出来。
  如果我们了解负面行为会导引自己和他人的痛苦，正面的行为会导引快乐，那就靠行动，播下“善种”
  的行为来建立自己的未来。
  #+END_QUOTE

- 1873-1874, 标注, 2025 年 9 月 21 日星期日 下午 8:50:20
  #+BEGIN_QUOTE md5: 787cfc02ef7044ce3dae7ff256059273
  一个永恒、全知、独立的个体不可能创造任何东西，而同时不失去他永恒和全能的特质。
  世界的运作完全根据因果定律和相互依存定律。
  #+END_QUOTE

- 1944-1947, 标注, 2025 年 9 月 22 日星期一 上午 7:48:32
  #+BEGIN_QUOTE md5: 052626cac1439a5c791b498fc48b6b28
  虽然佛法不会否定进化的过程产生越来越复杂的生命形态，以及越来越精细的知识，
  它却不认为意识可以从没有生命的物质中生起。这一点我已经提过了。科学认为当细胞有更复杂的结构时，
  它会以更有效率的方式反应外在刺激。这逐渐增强的复杂性可能会产生一个神经系统，从而导向意识。对佛法而言，
  意识不可能从一个化学作用生起，不管这个化学作用多么复杂或简单。
  #+END_QUOTE

- 1948-1951, 标注, 2025 年 9 月 22 日星期一 上午 7:49:35
  #+BEGIN_QUOTE md5: bd3a6d54783a7e00bee510c38b25c390
  空性不但不是虚无，也不是现象之外或不同的空虚空间。 它是现象的本质。这就是为什么最基础的佛教经典之一说：
  “空即是色，色即是空。”从绝对观点来看，世界没有真正或实质的存在，所以说现象世界就是相对层面，空性是绝对层面。
  #+END_QUOTE

- 1966-1969, 标注, 2025 年 9 月 22 日星期一 上午 7:52:13
  #+BEGIN_QUOTE md5: 7145ec1fff4a3e86c9fd63480b20bb64
  佛法最后的立场就是“中道”：世界并不是我们心的投射，但它也不完全独立于我们的心之外，因为要谈论一个特定的、
  固定的现实,独立于任何观念、心理过程，或者观者之外是没有意义的。这之中是一种相互依存的关系。因为如此，
  佛法就免于掉入虚无主义或永恒意义。现象通过一串相互依存的原因和状况的过程而显现，但是没有任何东西是自己存在的。
  #+END_QUOTE

- 1975-1981, 标注, 2025 年 9 月 22 日星期一 上午 7:53:54
  #+BEGIN_QUOTE md5: 801104be107936adfc885d163290f293
  一些特质都不是那个物之内本自实存的，这些特质只是我们用特定的方式探索那个物所得到的结论。
  佛经中说到两位盲人的故事，他们希望有人可以向他们解释什么叫作颜色。其中一位被告知白色就是雪的颜色。
  那一位手上抓起一把雪，下结论说：“白“就是“冷”。另外一位盲人被告知白是天鹅的颜色，他听到一只天鹅从他头上飞过，
  下结论说，“白“就是”哗！哗“翅膀飞过的声音。世界无法靠世界本身来定义，如果能的话，我们应该以相同的方式觉知它。
  这并不是要否定我们所观察到的现实，也不是说我们的心之外没有现实存在，只是说“现实以它自己的身份不存在”，
  现象只有依靠其他现象才能存在。
  #+END_QUOTE

- 1975-1981, 标注, 2025 年 9 月 22 日星期一 上午 7:53:59
  #+BEGIN_QUOTE md5: aaf366f31a71206073183439731f1be0
  特质都不是那个物之内本自实存的，这些特质只是我们用特定的方式探索那个物所得到的结论。佛经中说到两位盲人的故事，
  他们希望有人可以向他们解释什么叫作颜色。其中一位被告知白色就是雪的颜色。那一位手上抓起一把雪，下结论说：“白“
  就是“冷”。另外一位盲人被告知白是天鹅的颜色，他听到一只天鹅从他头上飞过，下结论说，“白“就是”哗！哗“
  翅膀飞过的声音。世界无法靠世界本身来定义，如果能的话，我们应该以相同的方式觉知它。
  这并不是要否定我们所观察到的现实，也不是说我们的心之外没有现实存在，只是说“现实以它自己的身份不存在”，
  现象只有依靠其他现象才能存在。
  #+END_QUOTE

- 1995-1997, 标注, 2025 年 9 月 22 日星期一 上午 7:57:53
  #+BEGIN_QUOTE md5: eaf9f6dbab0db9bce1d650c05c5389b9
  我觉得对我个人而言，现在答案已经非常清楚：佛教是哲学，而不是宗教。它是一门有其特别发展的形而上层面的哲学，
  但这种形而上学怎么说呢，包含一些类似宗教仪式的行为，是从哲学导引出来的，而不是从启示来的。
  #+END_QUOTE

- 2003-2005, 标注, 2025 年 9 月 22 日星期一 上午 7:59:07
  #+BEGIN_QUOTE md5: a60bd923ddb8888856ec60a81b47505c
  这个学派和公元前第六世纪的佛陀同时期：“没有一样存在的东西可以变成存在或者消失，
  因为存在的东西必须起源于已经存在的东西，要不然必须起源于不存在的东西，而这两种过程都是不可能的。
  已存在的不能变成存在，因为它已经存在；而没有东西可以起源自什么都不是的状态。”
  #+END_QUOTE

- 2005-2005, 笔记, 2025 年 9 月 22 日星期一 上午 7:59:52
  #+BEGIN_QUOTE md5: f894116490b936ac5abf4c5bc2aa014d
  否认了量变引起质变
  #+END_QUOTE

- 2005-2009, 标注, 2025 年 9 月 22 日星期一 上午 8:00:31
  #+BEGIN_QUOTE md5: ddba0dc1f4d6efe7ac427fb4789a67e4
  一段佛经关于存在与不存在的话：“如果一个东西有真正的存在，那么何需有因？如果一个东西是完全不存在，
  它又何需有因？上亿的因也无法转换不存在的个体，因为如果不存在的个体保持它不存在的身份，那存在的个体又如何生起？
  再说，又有什么是能起的？当起没有了真实和不真实，心没有其他可以做的，只好停住在完美的平静中，摆脱所有的观念。”
  #+END_QUOTE

- 2016-2018, 标注, 2025 年 9 月 22 日星期一 上午 8:02:27
  #+BEGIN_QUOTE md5: a1085a7b60b1d4f09ce7776f2aee528b
  佛法用类似芝诺的逻辑来表现相对真理的观点，看起来像是因果互动的事情其实没有真正的存在。推算到一个绝对性的观点，
  事物不但无法生，也没有真实的存在，同样也无法泯灭。这目的并不是要否定我们所觉知的现象世界的存在——
  就是佛法所谓的一般真理——而是要表现出世界没有我们以为的那么真实。
  #+END_QUOTE

- 2019-2020, 标注, 2025 年 9 月 22 日星期一 上午 8:03:03
  #+BEGIN_QUOTE md5: da1f566460914d1ef6c4976e97635aa0
  无中生有不可能，而一样东西如果已经存在，就没有必要生起，同时它也不会”停止“，因为它从来就没有存在过。
  这就是为什么佛教会说世界”如梦如幻“。
  #+END_QUOTE

- 2019-2021, 标注, 2025 年 9 月 22 日星期一 上午 8:03:13
  #+BEGIN_QUOTE md5: 336be8561b252f9a9dfcc107889ca21f
  无中生有不可能，而一样东西如果已经存在，就没有必要生起，同时它也不会”停止“，因为它从来就没有存在过。
  这就是为什么佛教会说世界”如梦如幻“。这并不是说世界就是一场梦或者一种幻觉，因为这么说就会掉进虚无主义。
  #+END_QUOTE

- 2019-2021, 标注, 2025 年 9 月 22 日星期一 上午 8:03:35
  #+BEGIN_QUOTE md5: e78fbabe3af6515fba5723c7ada13fcb
  无中生有不可能，而一样东西如果已经存在，就没有必要生起，同时它也不会”停止“，因为它从来就没有存在过。
  这就是为什么佛教会说世界”如梦如幻“。这并不是说世界就是一场梦或者一种幻觉，因为这么说就会掉进虚无主义。
  根据佛法的“中道”，现象是空的，现象从空性中显现。
  #+END_QUOTE

- 2026-2028, 标注, 2025 年 9 月 22 日星期一 上午 8:04:39
  #+BEGIN_QUOTE md5: 1ff28fe987f8914e2a320df1821c00a4
  某些印度教哲学曾经用你刚才提出的观点来反驳佛教。如果一切如梦，如果你的受苦像一场梦，
  那从痛苦中解脱出来有什么意义呢？干吗还要努力去达成证悟？答案是，因为众生确实经历着痛苦的经验，
  所以就算是幻觉式的，要除掉这种经验也是对的。
  #+END_QUOTE

- 2043-2046, 标注, 2025 年 9 月 22 日星期一 上午 8:05:43
  #+BEGIN_QUOTE md5: 06e2d398532a9fb3b31a2a9229e276d9
  如果我的了解正确的话，佛教说平凡生活的本质就是痛苦，要从这个痛苦中解放出来，必须摆脱一种错误的感觉，
  认为自己是具实的、永恒的个体，认为我们和世界之间是明显分开的，认为我们在时间中连续存在着。
  这个幻象中的自我就是造成痛苦的欲望、野心和嫉妒的泉源，于是解脱的重点就是渐渐了解.自我的幻象性本质。
  #+END_QUOTE

- 2048-2051, 标注, 2025 年 9 月 22 日星期一 上午 8:07:29
  #+BEGIN_QUOTE md5: fbda4298384fdacb4679913c77b9f3de
  西方思想的主流建立在两个重要的相称观点上：第一就是独立自我的完成，个人特性的增强，个人判断力的增强，
  以及意志力的增强，而意志力确定是有意识的，是判断的主导中心。第二就是对世界采取行动。西方文明是一个行动的文明——
  通过政治而影响人类的行动，通过对自然法则的知识而对世界有所行动；西方充满着能够改变世界的信心，
  能够把大自然扭向人类需求的信心。
  #+END_QUOTE

- 2058-2059, 标注, 2025 年 9 月 22 日星期一 上午 8:09:46
  #+BEGIN_QUOTE md5: 9359cd17f1c8db3fb41d7bf47e3e32a6
  于是思索痛苦能鼓励我们走向智慧的道路。佛法经常被称为一种受苦的哲学，但事实上当我们越走近这条道路，
  这个痛苦越转向一种快乐，这种喜悦可以充满全身。
  #+END_QUOTE

- 2058-2061, 标注, 2025 年 9 月 22 日星期一 上午 8:10:09
  #+BEGIN_QUOTE md5: d645a317d7401d91ef0e3209a64ed8fc
  于是思索痛苦能鼓励我们走向智慧的道路。佛法经常被称为一种受苦的哲学，但事实上当我们越走近这条道路，
  这个痛苦越转向一种快乐，这种喜悦可以充满全身。从一开始就承认世界是不圆满的，
  其实在修行上反而会采取与悲观主义和冷漠相反的方向。当我们承认痛苦的事实，佛法就可以清晰地指出痛苦的起因，
  然后有力量地向它下解药。
  #+END_QUOTE

- 2065-2068, 标注, 2025 年 9 月 22 日星期一 上午 8:11:28
  #+BEGIN_QUOTE md5: 36dc6540eab5cb7c0d226b2baeac4a68
  父：佛教有没有说我们不该对世界采取行动? 子：丝毫没有。但是它认为在你还没有转换自己之前，你想对世界有所作为，
  无法创造出长久或深刻的快乐。我们可以说对世界采取行动是好的，但是内在转化是不可缺少的。
  #+END_QUOTE

- 2075-2078, 标注, 2025 年 9 月 22 日星期一 上午 8:12:48
  #+BEGIN_QUOTE md5: 227330e7737b26a91c2ba36574cbb7ac
  不要认为当自我的骗局被揭发之后，自己会在一个内在的虚无状态中，不要认为你的个性被摧毁后，
  你再也没有能力行动或沟通。其实你并不会成为一个空洞的容器。正好相反，当你再也不是一个妄想独裁者的玩物，
  如同柏拉图山洞中的影子，你的智慧、你对他人的爱和慈悲就可以自由地表达出来。这是一种自由，
  从自我执着的限制中被解放出来，绝不是一种意志的麻药。“
  #+END_QUOTE

- 2090-2091, 标注, 2025 年 9 月 22 日星期一 下午 1:18:39
  #+BEGIN_QUOTE md5: f9868d032a0c3420ba609229f6e431ac
  拥有不可改变的坚定决心，不可遏止的行动力,并不能算是一个正面的个性特质。一切都要看背后的动机是什么。
  #+END_QUOTE

- 2135-2138, 标注, 2025 年 9 月 22 日星期一 下午 6:18:12
  #+BEGIN_QUOTE md5: 8caf6f089fef54cc102b1629f53672e4
  执着于自我让一个人完全以自我为中心，让一个人认为自己比他人更重要，让一个人所有的反应都只根据自己的喜恶，
  让一个人永远想为自己的”名声”努力。这样的态度在个人行动的范围上增加了很大的限制。摆脱这种自我为中心的觉知者，
  能够对世界产生更广大的影响力。
  #+END_QUOTE

- 2165-2166, 标注, 2025 年 9 月 22 日星期一 下午 6:21:09
  #+BEGIN_QUOTE md5: 43831159aa07e3a9854f96b06512a6d3
  如果心灵价值不再成为一个社会激励人心的事，那么物质进步就变成一种面具，遮蔽了生命没有方向感的事实。
  #+END_QUOTE

- 2185-2187, 标注, 2025 年 9 月 22 日星期一 下午 6:23:57
  #+BEGIN_QUOTE md5: 272603e2d866d0ea155ef752039775a1
  一个医生不断接受佛教无私的原则，只会更增进他专业的深度。但是如果一味冲向物质享受的方向，那就走错了路。
  西方已经迷上了这种倾向，过度寻找物质性的舒适和拥有巨额财产。有一句西藏俗语说：“如果你已经有一，然后你还要二，
  就等于敞开大门请魔鬼进来。”你
  #+END_QUOTE

- 2213-2215, 标注, 2025 年 9 月 22 日星期一 下午 6:27:28
  #+BEGIN_QUOTE md5: 6dd516a4a449bf6ec312501e85ed1470
  我确定佛法的观念可以在西方文化中造成很大的回响，让我们有一种全新的方式来看待宗教。
  因为佛教是一个密切融合学习和内在经验的传统，可以帮助人们了解如何培养出爱、慈悲、容忍和耐性这些基本特质；
  也能够让人们主宰自己的心，足以降伏狂野的念头和情绪。
  #+END_QUOTE

- 2267-2269, 标注, 2025 年 9 月 22 日星期一 下午 6:33:20
  #+BEGIN_QUOTE md5: 890b9e277d0109ddf495bcd9eda06e69
  但是人不一定要出家，在放弃世俗生活和过着西方人的生活之间，还有其他的各种可能性。一个人不一定要放弃他所做的事，
  佛法的观念还是可以充满他的心，带给他许多好处。
  #+END_QUOTE

- 2272-2273, 标注, 2025 年 9 月 22 日星期一 下午 6:34:06
  #+BEGIN_QUOTE md5: de466aa1bc253b4a1f2463ce6dee6256
  所谓的“禅定”并不只是坐下来几分钟，为了要得到一种圣人式的平静。禅定是一种分析和思考的方法，
  让我们去了解心的本性和运作，让我们去辨认事情真正的面貌。
  #+END_QUOTE

- 2272-2274, 标注, 2025 年 9 月 22 日星期一 下午 6:34:15
  #+BEGIN_QUOTE md5: 1bf89901782f098de424a3909ca2d225
  所谓的“禅定”并不只是坐下来几分钟，为了要得到一种圣人式的平静。禅定是一种分析和思考的方法，
  让我们去了解心的本性和运作，让我们去辨认事情真正的面貌。所谓的“后禅定状态”
  包含的是避免原封不动回到我们先前的习惯中。“
  #+END_QUOTE

- 2272-2275, 标注, 2025 年 9 月 22 日星期一 下午 6:34:28
  #+BEGIN_QUOTE md5: abdaeb9061144e3ecda3ef67360a77ac
  所谓的”禅定”并不只是坐下来几分钟，为了要得到一种圣人式的平静。禅定是一种分析和思考的方法，
  让我们去了解心的本性和运作，让我们去辨认事情真正的面貌。所谓的“后禅定状态”
  包含的是避免原封不动回到我们先前的习惯中。“后禅定”包括如何在日常生活中运用禅定所得到的了解，
  让我们有更开放的心，加强善良和耐性。简而言之，就是让我们变成更好的人。
  #+END_QUOTE

- 2280-2281, 标注, 2025 年 9 月 22 日星期一 下午 6:35:36
  #+BEGIN_QUOTE md5: 42a4adc275717c89ec91c28156aa0f02
  如果像佛教所说，世界只不过是一个幻象，一串没有实质的意象，而自我也是如此，那一个人何必去经营事业、参与政治，
  或者做科学研究？那将是没有意义的，那样做，只会让你变成一个误导幻象的共犯。
  #+END_QUOTE

- 2293-2297, 标注, 2025 年 9 月 22 日星期一 下午 6:37:17
  #+BEGIN_QUOTE md5: 0a508ff89a08ba2e3318c6953298cd11
  佛法修行包括三种互补的层面一一 “观点”、“禅定”和“实践”。“观点”等于形而上的观点，对事物、
  现象世界和心究竟本质的探索。一旦这个观点被建立起来，“禅定”让自己更熟悉这个观点，通过心灵修行，
  让它融入意识的河流，让这个观点变成自己性格的一部分。“实践”的意义就是将”观点“和”禅定“
  所达成的内在知识表现在外在世界，也就是在任何状态下，时时运用这个知识。
  #+END_QUOTE

- 2312-2315, 标注, 2025 年 9 月 22 日星期一 下午 6:39:30
  #+BEGIN_QUOTE md5: 7eb2561ab1342806ad9ff6c5afdfe3a3
  虽然一个独立的自我，一个被视为独立存在的个体并不存在，我们现在是什么，仍然是依据过去的结果。
  行为一定会带来结果。最重要的不是身份的问题，而是连续性的问题。一个负面行为不可能转化成快乐，
  就如同一颗毒草种子不可能长成一棵柠檬树。于是，一个正面或负面的行为，有其快乐或痛苦的相对结果，
  就足以让我们拒绝去做，就算经历结果的那个人并没有一个永恒的自我。
  #+END_QUOTE

- 2337-2340, 标注, 2025 年 9 月 22 日星期一 下午 9:44:06
  #+BEGIN_QUOTE md5: 6cee6773b2fb6a72526aa3a64e327f59
  对于想走入心灵生活的人，希望心灵生活成为生命的主体，佛法不只提供一个活着的形而上和智慧系统，
  同时也提供让这智慧融到我们内在的方法。除此之外，不管你是不是信徒，佛法能提供所有人一种容忍的、开放的、无私的、
  沉静自信的视野，一种心灵的科学，让个人找到内在的平
  #+END_QUOTE

- 2337-2340, 标注, 2025 年 9 月 22 日星期一 下午 9:44:16
  #+BEGIN_QUOTE md5: 402a54f394ea27d0aa04a7b7b33e7b53
  我认为今天西方对佛法的兴趣有许多不同的原因。首先，对于想走入心灵生活的人，希望心灵生活成为生命的主体，
  佛法不只提供一个活着的形而上和智慧系统，同时也提供让这智慧融到我们内在的方法。除此之外，不管你是不是信徒，
  佛法能提供所有人一种容忍的、开放的、无私的、沉静自信的视野，一种心灵的科学，让个人找到内在的平
  #+END_QUOTE

- 2337-2340, 标注, 2025 年 9 月 22 日星期一 下午 9:44:26
  #+BEGIN_QUOTE md5: d937b5c7a1a6e6976276ee2e47d97610
  我认为今天西方对佛法的兴趣有许多不同的原因。首先，对于想走入心灵生活的人，希望心灵生活成为生命的主体，
  佛法不只提供一个活着的形而上和智慧系统，同时也提供让这智慧融到我们内在的方法。除此之外，不管你是不是信徒，
  佛法能提供所有人一种容忍的、开放的、无私的、沉静自信的视野，一种心灵的科学，让个人找到内在的平静，
  让他人的内在平静能够开花。
  #+END_QUOTE

- 2411-2413, 标注, 2025 年 9 月 22 日星期一 下午 10:02:49
  #+BEGIN_QUOTE md5: 859376124a66de209280219be209d137
  真正的目标在于不变成感官世界的奴隶，不再因它而受苦，不再像飞蛾扑火，被火吸引，最后却又要被火烧死。
  一个不受任何执着牵引的人，不但能够自由地享受世界和众生所有的美，同时还可以回到世界本身，发挥无限的慈悲，
  不再成为负面情绪的玩物。
  #+END_QUOTE

- 2460-2462, 标注, 2025 年 9 月 22 日星期一 下午 10:39:42
  #+BEGIN_QUOTE md5: 1c819131e03533951753eecbd93919ec
  但西藏文明基本上是和平的，旅行到西藏的人一直强调“佛教式的温和”。密果说：“那不只是一个空洞的名词。
  是可以在空气中呼吸到的温和，触及到所有生活在佛教国家中的人，是一种对所有众生善意的态度。“
  #+END_QUOTE

- 2463-2465, 标注, 2025 年 9 月 22 日星期一 下午 10:39:56
  #+BEGIN_QUOTE md5: 306240c7e7f9709366132dfcc1ecf1c3
  我们所熟悉的伟大宗教经常违背自己的理想。举例来说，基督教是根据非暴力而建立的。耶稣基督不是说“
  如果有人打你的右脸颊，转头让他打左边”，以及“彼此相爱” ？就算如此，
  教会花了很多时间消灭许多不愿把自己改变成基督徒的人，或者和教皇理论相左的异教分子。
  #+END_QUOTE

- 2486-2488, 标注, 2025 年 9 月 22 日星期一 下午 10:42:02
  #+BEGIN_QUOTE md5: 23bb5bf693ff29406a5905776e5e5410
  真正的爱不应该走极端，不应 该被局限于一两位特定的众生， 也不应该被偏见所污染。而且， 它应该是完全没有执着的，
  也 不期待任何回报。
  #+END_QUOTE

- 2498-2501, 标注, 2025 年 9 月 23 日星期二 上午 8:02:37
  #+BEGIN_QUOTE md5: e6bf965293c3b601a121fad559bbbcff
  在我年轻时，主导哲学、建构伟大体系，把最伟大的道德家全贬入世界文学的领域，藐视他们的作品，认为他们不连贯，
  大多只凭经验且随意的观察，完全没有办法系统化。不过现在看来，社会大众虽然对哲学书籍的兴趣有限，
  却又开始喜欢上这种回归老道德家“食谱”型的作品，因为在这些作品中，他们可以得到谦虚而实在的忠告，
  关于人类这种动物的日常运作。
  #+END_QUOTE

- 2501-2501, 笔记, 2025 年 9 月 23 日星期二 上午 8:03:05
  #+BEGIN_QUOTE md5: 2c3fbc32d74391c90a4df5bf94755166
  就是现在的鸡汤文吧
  #+END_QUOTE

- 2515-2516, 标注, 2025 年 9 月 23 日星期二 上午 8:04:56
  #+BEGIN_QUOTE md5: 09145c604d44e3d8a970992e147e6463
  今天的教育几乎已经不再讨论如何使人变得更好。现在的教育越来越世俗，主要的目的就是为了培养知性以及累积知识。
  #+END_QUOTE

- 2524-2527, 标注, 2025 年 9 月 23 日星期二 上午 8:13:36
  #+BEGIN_QUOTE md5: a39f0e49591d396b07d770b8ddd33085
  因为环境是世俗的，也就没有理由不在教育中教导道德。“世俗”意味着所教导的一切是中性的，不被任何教条所支配，
  不论是宗教性的或政治性的。但这不应该排除道德的训练，从尊重法律、尊重他人、尊重社会公约，以及正确运用自由做起——
  简而言之，就是孟德斯鸠所称的共和国美德，这一切反而更被需要。然而，最近的世俗概念已经偏离了主题。
  #+END_QUOTE

- 2528-2530, 标注, 2025 年 9 月 23 日星期二 上午 8:29:24
  #+BEGIN_QUOTE md5: beaaa738c9ac6b344a8c093336fb0e73
  真正的世俗教育未必要如此做。好的教育应该让儿童在学校学习各种不同的宗教和哲学观点——
  为何不连不可知论的物质主义一起教呢？可以让学生自己决定愿不愿意上这种课。
  这样儿童和青少年起码有机会了解开的是什么课程。
  #+END_QUOTE

- 2528-2530, 标注, 2025 年 9 月 23 日星期二 上午 8:29:28
  #+BEGIN_QUOTE md5: b8753af3da164f0f2906b668e658a37c
  好的教育应该让儿童在学校学习各种不同的宗教和哲学观点——为何不连不可知论的物质主义一起教呢？
  可以让学生自己决定愿不愿意上这种课。这样儿童和青少年起码有机会了解开的是什么课程。
  #+END_QUOTE

- 2573-2574, 标注, 2025 年 9 月 23 日星期二 上午 8:34:42
  #+BEGIN_QUOTE md5: dd6938f5b0248a3b5757f1041a7667e1
  教育的问题在于要传授给年轻人他们想听的，还是他们真正需要听的？前者是简单的做法，而后者才是负责任的态度。
  #+END_QUOTE

- 2572-2572, 标注, 2025 年 9 月 23 日星期二 上午 8:34:53
  #+BEGIN_QUOTE md5: e57f4b2dc4632e96a1e1c305cbb2d9c7
  教育需要义务性吗？ 还是根据学生自己的期望？
  #+END_QUOTE

- 2584-2586, 标注, 2025 年 9 月 23 日星期二 上午 8:39:43
  #+BEGIN_QUOTE md5: 9d9916b4b80cc8683ada312837e6ebef
  意思是并不太赞成堕胎？ 子：是。佛教定义杀生的行为是”取走生命或者正在形成中的生命“。这是轮回概念下的合理结果，
  因为在受孕之后，前世的意识就已存在，即使是在一种非常原始甚至无法察觉的状态中。
  #+END_QUOTE

- 2584-2586, 标注, 2025 年 9 月 23 日星期二 上午 8:39:51
  #+BEGIN_QUOTE md5: 2012a5ffe0dab656a79be9d30189dc52
  父：意思是并不太赞成堕胎？ 子：是。佛教定义杀生的行为是”取走生命或者正在形成中的生命“。
  这是轮回概念下的合理结果，因为在受孕之后，前世的意识就已存在，即使是在一种非常原始甚至无法察觉的状态中。
  #+END_QUOTE

- 2584-2588, 标注, 2025 年 9 月 23 日星期二 上午 8:40:00
  #+BEGIN_QUOTE md5: 722b1b5bf494386ecb5070a5f5958147
  父：意思是并不太赞成堕胎？ 子：是。佛教定义杀生的行为是“取走生命或者正在形成中的生命”。
  这是轮回概念下的合理结果，因为在受孕之后，前世的意识就已存在，即使是在一种非常原始甚至无法察觉的状态中。
  在某些个案中，当母亲的生命有危险，或者我们确定胎儿出生后会有极可怕的畸形现象，堕胎这项措施或许成立；
  但如果只是因为某些自私的想法，如父母没有采取避孕措施、有小孩会是一件非常讨厌的事等等，佛教自然不能接受
  #+END_QUOTE

- 2653-2657, 标注, 2025 年 9 月 23 日星期二 下午 1:23:14
  #+BEGIN_QUOTE md5: cd74b9c476fdd557334fd00fa2b0a9f0
  完美，本自实存于每一个众生之中，就像油本自实存于芝麻之中。事实上，它是所有众生的本性。那个完美可能被隐藏起来，
  但是只要我们去除遮蔽它的东西一一层一层的无知，以及无知影响下产生的负面情绪，它就可以显现出来。
  这些遮蔽的层面不属于佛性本身，它们遮住了佛性，但是没有以任何方式改变佛性。我们太容易忘掉这个本性，
  进入二元对立、负面的思考模式，这些又会被转换成负面的语言和行为，接而创造痛苦。
  #+END_QUOTE

- 2662-2663, 标注, 2025 年 9 月 23 日星期二 下午 1:24:01
  #+BEGIN_QUOTE md5: b29f7502aa4d425a44d88800e52ec7d4
  父：所以说佛教不像基督教一样，认为人类一开始便掉入罪恶中？ 子：没有。没有过堕落，也没有任何罪，
  只有对本性的遗忘，一种被催眠之后失去记忆的状态。
  #+END_QUOTE

- 2677-2679, 标注, 2025 年 9 月 23 日星期二 下午 1:25:26
  #+BEGIN_QUOTE md5: fd126a6ee372e72b1c114bafde891354
  当我们看不到事物真正的本性，会相信它们表面的存在模式。自我和他人、美与丑、舒服与不舒服等等之间的二元对立，
  会引爆一整串负面的心理因素，这就是无知。
  #+END_QUOTE

- 2686-2688, 标注, 2025 年 9 月 23 日星期二 下午 1:28:07
  #+BEGIN_QUOTE md5: 74f957247dab1afb0855b8e0e98c873c
  我们可以说无知是邪恶和痛苦的真正泉源，是一个意外的误解，一种突然间的遗忘，对心的真正本性是没有影响的，
  但会引发一连串痛苦的经验。一场噩梦无法改变你原来舒舒服服躺在床上的事实，但它还是能够在你心中造成极大的痛苦。
  #+END_QUOTE

- 2741-2742, 标注, 2025 年 9 月 23 日星期二 下午 1:34:05
  #+BEGIN_QUOTE md5: da3e41d371d6cf1256a38374d85af499
  使用暴力的人经常会远远超过他们初始的具体目标。
  #+END_QUOTE

- 2749-2751, 标注, 2025 年 9 月 23 日星期二 下午 1:35:20
  #+BEGIN_QUOTE md5: e8d54bf2c60f6a064f06ee1f3717e227
  当罪犯的目的在于得到某种回报时，我痛斥他，但是我还可以理解他的行为，至少我可以解释他的行为是一种贪心，
  一种权利欲望，一种现实的算计。但当邪恶没有任何意义时，当人类被大屠杀，对任何人都绝对没有好处，
  也没有增进任何人的利益时，我们被迫下一个结论，邪恶是可以自己存在的一至少存在于人之中。
  #+END_QUOTE

- 2754-2754, 标注, 2025 年 9 月 23 日星期二 下午 1:35:52
  #+BEGIN_QUOTE md5: 0f414a8106fdf6164ec7218ccb4686aa
  当一个族群完全没有任何约束的力量，无论是宗教性的原则或人性习俗，结果一定是互相残杀。
  #+END_QUOTE

- 2802-2804, 标注, 2025 年 9 月 23 日星期二 下午 6:20:14
  #+BEGIN_QUOTE md5: 73964c84523bd3380e6cf45673ed8c1b
  直到 17 世纪，哲学自始实践的两种层面都还存在，一方面是科学的层面，另一方面是智慧的层面，
  也就是如何发掘生命的意义，甚至生命之外的意义。直到笛卡儿的时代，哲学这两种层面还存在。
  #+END_QUOTE

- 2807-2809, 标注, 2025 年 9 月 23 日星期二 下午 6:20:42
  #+BEGIN_QUOTE md5: 46775d21e66c0806abab9a87b3f62d90
  子：为什么西方哲学再也没有办法提供生命的模式给我们？ 父：这三个世纪以来，哲学已经放弃了它提供智慧源泉的功能，
  把自己局限在知识上。而同时，它渐渐被科学本身剥夺了它科学性的功能。
  #+END_QUOTE

- 2807-2812, 标注, 2025 年 9 月 23 日星期二 下午 6:24:19
  #+BEGIN_QUOTE md5: b7d6304c01c1f4292ec9b839b5851c70
  子：为什么西方哲学再也没有办法提供生命的模式给我们？ 父：这三个世纪以来，哲学已经放弃了它提供智慧源泉的功能，
  把自己局限在知识上。而同时，它渐渐被科学本身剥夺了它科学性的功能。当天文学、物理学、化学和生物学先后出现、
  发展，开始遵循一些与哲学思考方式无关的条件，哲学的科学功能便一样一样地被掏空。康德在他的《纯粹理性批判》
  中已说得很清楚，即使康德之后的哲学家并不怎么讨论这件事。基本上，哲学被它自己的成功杀掉了，
  因为它当初的目的就是希望能够生出这些其他的科学。
  #+END_QUOTE

- 2816-2818, 标注, 2025 年 9 月 23 日星期二 下午 6:26:11
  #+BEGIN_QUOTE md5: eae4f8c28f19b79bbbec3ea74cd7bd26
  走到这一步，原属于哲学中伦理的一支，以政治体系的形式重生。到了 19 世纪，我们进入大乌托邦时代，
  大家希望从头到尾重新建立社会。这些乌托邦思想中，最主
  #+END_QUOTE

- 2816-2819, 标注, 2025 年 9 月 23 日星期二 下午 6:26:20
  #+BEGIN_QUOTE md5: 90dea0cc2733b94fe31b1b07a8888488
  走到这一步，原属于哲学中伦理的一支，以政治体系的形式重生。到了 19 世纪，我们进入大乌托邦时代，
  大家希望从头到尾重新建立社会。这些乌托邦思想中，最主要的就是社会主义，尤其是马克思主义；直到 20 世纪末期，
  马克思主义还驾驭着政治思想领域。从这个观点而论，哲学的伦理功能转向另外一个目标，
  就是从零开始重新建立一个完全正义的社会。第一次
  #+END_QUOTE

- 2832-2836, 标注, 2025 年 9 月 23 日星期二 下午 6:28:28
  #+BEGIN_QUOTE md5: 347c57004668be41e49c1798e05faf10
  这些伟大制度都已经失败了，它们直接撞到绝对的邪恶。在制度死亡前，剩下最后一口气的时候，
  还掀出了最不可思议的人物，像柬埔寨的布尔布特，这些人把这种制度的逻辑推向极致。为了要创造一种新的人类，
  为了要消灭过去，建立一个绝对正义的社会，第一件事就是要毁灭所有活着的人类，因为他们多多少少被过去的社会所腐化。
  这三百年来，大部分的知识分子虽然没有走向如此恐怖的极端，但都共同接受了一个观念：要让人类变得更有道德、更正义，
  唯一的方法就是创造一个更正义、更平衡、更平等的社会。
  #+END_QUOTE

- 2832-2837, 标注, 2025 年 9 月 23 日星期二 下午 6:28:52
  #+BEGIN_QUOTE md5: e6ae966cddd212893c2a250480a6e12c
  这些伟大制度都已经失败了，它们直接撞到绝对的邪恶。在制度死亡前，剩下最后一口气的时候，
  还掀出了最不可思议的人物，像柬埔寨的布尔布特，这些人把这种制度的逻辑推向极致。为了要创造一种新的人类，
  为了要消灭过去，建立一个绝对正义的社会，第一件事就是要毁灭所有活着的人类，因为他们多多少少被过去的社会所腐化。
  这三百年来，大部分的知识分子虽然没有走向如此恐怖的极端，但都共同接受了一个观念：要让人类变得更有道德、更正义，
  唯一的方法就是创造一个更正义、更平衡、更平等的社会。这些乌托邦式的政治制度，在实践上是失败的。它们的失败，
  以及道德扫地，就是 20 世纪末最主要的事件，也就是我认为西方文明在非科学领域上的失败。
  #+END_QUOTE

- 2859-2861, 标注, 2025 年 9 月 23 日星期二 下午 6:37:45
  #+BEGIN_QUOTE md5: 5cdd5d0a0cd3b5b8bffdffd1a63e0566
  科学——好的科学——变得超然时,反而会变成一种智慧的形式。有些科学家会听人家说，他们研究的领域一点用也没有，
  但是许多伟大的科学发现却由此而来。可是，研究必须首先有知的欲望，之后才想到这研究有没有实际用途。
  #+END_QUOTE

- 2859-2862, 标注, 2025 年 9 月 23 日星期二 下午 6:38:04
  #+BEGIN_QUOTE md5: 3dedbbf73948d6f43698bc1f838d687d
  科学——好的科学——变得超然时,反而会变成一种智慧的形式。有些科学家会听人家说，他们研究的领域一点用也没有，
  但是许多伟大的科学发现却由此而来。可是，研究必须首先有知的欲望，之后才想到这研究有没有实际用途。
  科学的历史告诉我们，人类单纯地跟随他们的知性好奇时，才会做出最有用的发现，
  但是他们开始的时候并没有在寻找任何有用的东西。科学研究之中存有一种超然感，这是一种智慧的形式。
  #+END_QUOTE

- 2873-2877, 标注, 2025 年 9 月 23 日星期二 下午 6:39:56
  #+BEGIN_QUOTE md5: 9a4acda6f566c856f8ab3d8acf87f9f0
  佛教谈到三种懒惰。第一种很简单，就是把所有时间用在吃饭和睡觉上。第二种就是告诉自己，
  “像我这样的人绝对不可能达到完美”。佛教的观点中，这种懒惰会让你觉得就算努力也没有意义，
  你永远无法达到任何心灵上的成就，这种懒惰让自己灰心，反而令自己试都不去试。第三种，也是在这里最切题的，
  就是把生命浪费在次等重要的工作上，永远不去面对最精要的问题，所有时间都花在解决次要问题上，一个接一个，
  在一个永无止境的顺序中，像湖上的涟漪一样。
  #+END_QUOTE

- 2906-2908, 标注, 2025 年 9 月 23 日星期二 下午 6:43:25
  #+BEGIN_QUOTE md5: 78efedb963606ddbeed2ca8c0bdec900
  真正的老师最主要的特质就是，在他倡导的完美中，他本身就是能反映出这种完美的最佳形象。
  这种完美不能只是一种概念系统的说明，它必须透明地从这个人的各个面中散发出来。
  #+END_QUOTE

- 2903-2905, 标注, 2025 年 9 月 23 日星期二 下午 6:43:41
  #+BEGIN_QUOTE md5: 5e62ea1a47bc5d5feb47ac6606533e9c
  方法。现代哲学已经切掉了实际的实践方法，放纵地让观念无限泛滥出来，玩一些极为复杂的知识游戏，实际用途非常微小。
  概念的世界和个人实际生活之间的差距，已经大到主张
  #+END_QUOTE

- 2903-2905, 标注, 2025 年 9 月 23 日星期二 下午 6:43:51
  #+BEGIN_QUOTE md5: 139f2d764b5fed8049d27c4f6917ffcb
  方法。现代哲学已经切掉了实际的实践方法，放纵地让观念无限泛滥出来，玩一些极为复杂的知识游戏，实际用途非常微小。
  概念的世界和个人实际生活之间的差距，已经大到主张这些哲学体系的人士不需要以身作则。
  #+END_QUOTE

- 2903-2906, 标注, 2025 年 9 月 23 日星期二 下午 6:44:06
  #+BEGIN_QUOTE md5: 317bbf2dd3ef04100bf3f2c9f8862233
  方法。现代哲学已经切掉了实际的实践方法，放纵地让观念无限泛滥出来，玩一些极为复杂的知识游戏，实际用途非常微小。
  概念的世界和个人实际生活之间的差距，已经大到主张这些哲学体系的人士不需要以身作则。
  今天你可以是一个伟大的哲学家，同时你的生活方式可以完全不被任何人视为榜样。
  #+END_QUOTE

- 2935-2936, 标注, 2025 年 9 月 23 日星期二 下午 6:48:57
  #+BEGIN_QUOTE md5: 041241d2b36ce2fbfc759f546bbced21
  要做一个智者，光是照自己思考的方式而活是不够的。这个思考方式必须对应上某种真正的智慧形式，
  能够让我们的心从所有混乱和痛苦中解脱出来，这种智慧必须反映在他人性的完美中，
  #+END_QUOTE

- 3058-3059, 标注, 2025 年 9 月 24 日星期三 上午 8:11:21
  #+BEGIN_QUOTE md5: b778dc27da80d1de7983f7ca3b6337e7
  所以佛教是宗教中非常稀有的例子一让我们为了方便起见称它为宗教好了一居然在它的发源地，
  在它上千年以来被实行和传播的地方被毁灭。
  #+END_QUOTE

- 3083-3084, 标注, 2025 年 9 月 24 日星期三 上午 8:15:45
  #+BEGIN_QUOTE md5: 5319b956999929d965fff16dc5f4fd9f
  基督教，尤其是天主教，当然如此，而”天主教“的名字源自希腊文“宇宙性”这个字眼，
  所以它经常认为自己有权以武力方式强迫人们变成教徒。
  #+END_QUOTE

- 3087-3088, 标注, 2025 年 9 月 24 日星期三 上午 8:16:11
  #+BEGIN_QUOTE md5: 3baf52ef68c9099fd74dc8da09477d66
  佛说：“不要因为对我的尊敬而相信我的教导。检查它，让你自己重新发掘出真理。”
  #+END_QUOTE

- 3087-3089, 标注, 2025 年 9 月 24 日星期三 上午 8:16:36
  #+BEGIN_QUOTE md5: d1b2bccf994fdd072681cf09e4a1df43
  佛说：“不要因为对我的尊敬而相信我的教导。检查它，让你自己重新发掘出真理。”他又说：“我已经为你指引出道路，
  要不要走下去是你的事。”
  #+END_QUOTE

- 3101-3101, 标注, 2025 年 9 月 24 日星期三 上午 8:18:30
  #+BEGIN_QUOTE md5: a2b0f23d970c80a5039e1b27087a56ec
  西方文明最重要的问题，就是需要知道它的文明无法满足心灵的需求，
  #+END_QUOTE

- 3106-3108, 标注, 2025 年 9 月 24 日星期三 上午 8:19:25
  #+BEGIN_QUOTE md5: 50812db17f3ac2eed62b20a911d4f881
  邪教是纯正心灵传统的假版本。一有机会，它们的面貌就会崩溃。邪教虽然能吸引许多信徒，
  但是它欺骗性的本质表现在它各种内在的矛盾、丑闻，以及不可思议的事件上，
  #+END_QUOTE

- 3113-3115, 标注, 2025 年 9 月 24 日星期三 上午 8:20:34
  #+BEGIN_QUOTE md5: 407d54d2b269e7f1607a6db8daee7e8b
  我一向对人性直觉持有怀疑，所以我只是很单纯地想指出，就因为某些人对某一种理论和倡导者有一种狂热——
  这些倡导者在弟子眼中拥有相当的地位，但同时也可能是骗子——就因为如此，我们不能说这个教义就是好的，
  必须有更进一步的证明。
  #+END_QUOTE

- 3116-3117, 标注, 2025 年 9 月 24 日星期三 上午 8:20:49
  #+BEGIN_QUOTE md5: 814a0dc64a4b306e0cfff089c8cd7b5a
  有句话说：“学习的结果是更能控制自己；修行的结果是使自己负面的情绪减少。”
  #+END_QUOTE

- 3120-3122, 标注, 2025 年 9 月 24 日星期三 上午 8:21:31
  #+BEGIN_QUOTE md5: 867b82b4e49a780774eccb89d4724aca
  所以说，不要认为人们对某一种心灵体系的诚恳奉献就可以证明这个体系的纯真度。那个体系可能是假的，
  因为有一个很悲哀的事实，人类很不幸地有一种倾向，对各式各样奇怪的事物有强烈的喜好。就因为如此，
  提供证明的责任永远必须落在教导的人身上。
  #+END_QUOTE

- 3118-3122, 标注, 2025 年 9 月 24 日星期三 上午 8:21:39
  #+BEGIN_QUOTE md5: 707d4b7f1926aad4db467d5ed316590e
  ，有时连最优秀的头脑都可以被绝对无稽的话语所欺骗。我认识几位德高望重的医生，跑去参加一个完全属于骗局的机构，
  好多年来，充满信心地为这个团体做出各种牺牲。所以说，
  不要认为人们对某一种心灵体系的诚恳奉献就可以证明这个体系的纯真度。那个体系可能是假的，因为有一个很悲哀的事实，
  人类很不幸地有一种倾向，对各式各样奇怪的事物有强烈的喜好。就因为如此，提供证明的责任永远必须落在教导的人身上。
  #+END_QUOTE

- 3122-3124, 标注, 2025 年 9 月 24 日星期三 上午 8:22:08
  #+BEGIN_QUOTE md5: 2521f7843dab77143d6b7a6810a6a7fc
  一条纯正的心灵道路当然意味着对自己有极大的要求，同时必须对其他人非常容忍。可是在大部分的邪教中，
  里面的人对其他的人要求非常多，但又猖狂地违反自己号称的理想。
  #+END_QUOTE

- 3125-3126, 标注, 2025 年 9 月 24 日星期三 上午 8:24:46
  #+BEGIN_QUOTE md5: a20757a49dcdaabce8d06ece8157c952
  邪教的基础通常是一些不同元素的拼凑，一些伪传统的垃圾，这和真正的心灵传递没有真正的关系，
  也没有根据任何真正的形而上原理。于
  #+END_QUOTE

- 3125-3129, 标注, 2025 年 9 月 24 日星期三 上午 8:24:58
  #+BEGIN_QUOTE md5: 3f867d2e28191240eda3cc4dfcf1dd14
  邪教的基础通常是一些不同元素的拼凑，一些伪传统的垃圾，这和真正的心灵传递没有真正的关系，
  也没有根据任何真正的形而上原理。于是它们无法造成长久的心灵进步，只能孕育出混乱和幻灭。
  任何真正的心灵道路必须包含两种精要的元素——让自己走向完美的方式，以及能够对他人有所贡献的方法。在各个传统之中,
  有很多不同的方式来达成这两种目标，而这两种目标确实要达成。
  #+END_QUOTE

- 3125-3128, 标注, 2025 年 9 月 24 日星期三 上午 8:25:16
  #+BEGIN_QUOTE md5: b34882e690a21b727a51bf3856e5444f
  邪教的基础通常是一些不同元素的拼凑，一些伪传统的垃圾，这和真正的心灵传递没有真正的关系，
  也没有根据任何真正的形而上原理。于是它们无法造成长久的心灵进步，只能孕育出混乱和幻灭。
  任何真正的心灵道路必须包含两种精要的元素——让自己走向完美的方式，以及能够对他人有所贡献的方法。
  #+END_QUOTE

- 3134-3135, 标注, 2025 年 9 月 24 日星期三 上午 8:25:41
  #+BEGIN_QUOTE md5: 0cce0c191f21e374783fe84c1129e2d1
  如果信仰违反理性，而且不去 了解仪式中更深层的意义，那 么就变成了迷信。
  #+END_QUOTE

- 3142-3145, 标注, 2025 年 9 月 24 日星期三 上午 8:27:03
  #+BEGIN_QUOTE md5: fae07a7ddb0b109e8e9ef94b730c5f40
  佛教确实因此而吸引了很多人，包括知识分子，而这些人可能对其他宗教中似乎太戏剧化、
  太正式或者太不理性的层面感到反感。我现在觉得这些人对佛教的印象太过理想化。
  这种印象似乎是隔着距离观看才会产生的，他们对佛教教义有知识性的了解，但从来没有参与过实际的日常运作。
  #+END_QUOTE

- 3150-3151, 标注, 2025 年 9 月 24 日星期三 上午 8:27:27
  #+BEGIN_QUOTE md5: 02d7733f48d49dd8801308d2db68fe2b
  我们首先必须在迷信和仪式之间划清界限。如果信仰违反理性，而且不去了解仪式中更深层的意义，那么就变成了迷信。
  #+END_QUOTE

- 3151-3152, 标注, 2025 年 9 月 24 日星期三 上午 8:27:59
  #+BEGIN_QUOTE md5: 51266e17d8af9bcdfe42deddc6a6fa9c
  拉丁文的“仪式”(ritus )一词事实上是“正确行动”的意思，蕴含着反省、沉思、祈祷和静思。
  #+END_QUOTE

- 3151-3152, 标注, 2025 年 9 月 24 日星期三 上午 8:29:40
  #+BEGIN_QUOTE md5: 156dc96ef1ebad852d207f6268f0bc18
  拉丁文的“仪式”(ritus )一词事实上是“正确行动”的意思，蕴含着反省、沉思、祈祷和静思。
  所有被念诵词句的意义都应该引起沉思，在藏传佛法中尤其如此。
  #+END_QUOTE

- 3156-3158, 标注, 2025 年 9 月 24 日星期三 上午 8:30:05
  #+BEGIN_QUOTE md5: ed182b1b682f1f2926e39c6931359377
  形式。有些仪式日夜持续，中间不休息，为时一个星期以上，主要的想法是希望所有参与者一起参加一段集中的集体修行。
  以“曼达拉”仪式来讲，重点在训练注意力集中的技巧，在仪式过程中引用极丰富的象征。
  #+END_QUOTE

- 3159-3161, 标注, 2025 年 9 月 24 日星期三 上午 8:31:18
  #+BEGIN_QUOTE md5: 64085cf73c29fb621eb32ba6044062d1
<<<<<<< variant A
  子：“曼达拉”是宇宙和众生的象征性图像，它的形式是一个完美的空间，展现居住在内的诸”本尊“。但”曼达拉“中的”本尊“
  不是神。我前面已经说过，佛教既不是多神论，也不是一神论。所谓的”本尊”是一些原型，是佛性的不同面貌。“
>>>>>>> variant B
  子：“曼达拉“是宇宙和众生的象征性图像，它的形式是一个完美的空间，展现居住在内的诸”本尊“。但”曼达拉“中的”本尊“
  不是神。我前面已经说过，佛教既不是多神论，也不是一神论。所谓的“本尊”是一些原型，是佛性的不同面貌。“
####### Ancestor
  子：“曼达拉“是宇宙和众生的象征性图像，它的形式是一个完美的空间，展现居住在内的诸”本尊“。但”曼达拉“中的”本尊“
  不是神。我前面已经说过，佛教既不是多神论，也不是一神论。所谓的”本尊”是一些原型，是佛性的不同面貌。“
======= end
  #+END_QUOTE

- 3159-3162, 标注, 2025 年 9 月 24 日星期三 上午 8:31:48
  #+BEGIN_QUOTE md5: b53332cbf79523b2aa73cb594424eb83
<<<<<<< variant A
  子：”曼达拉“是宇宙和众生的象征性图像，它的形式是一个完美的空间，展现居住在内的诸”本尊“。但”曼达拉“中的”本尊“
  不是神。我前面已经说过，佛教既不是多神论，也不是一神论。所谓的”本尊”是一些原型，是佛性的不同面貌。“曼达拉”
  的修行是一种“纯真觉”的训练，就是直接去感受众生中的佛性。“
>>>>>>> variant B
  子：“曼达拉“是宇宙和众生的象征性图像，它的形式是一个完美的空间，展现居住在内的诸”本尊“。但”曼达拉“中的”本尊“
  不是神。我前面已经说过，佛教既不是多神论，也不是一神论。所谓的“本尊”是一些原型，是佛性的不同面貌。“曼达拉“
  的修行是一种“纯真觉”的训练，就是直接去感受众生中的佛性。“
####### Ancestor
  子：“曼达拉“是宇宙和众生的象征性图像，它的形式是一个完美的空间，展现居住在内的诸”本尊“。但”曼达拉“中的”本尊“
  不是神。我前面已经说过，佛教既不是多神论，也不是一神论。所谓的”本尊”是一些原型，是佛性的不同面貌。“曼达拉“
  的修行是一种”纯真觉”的训练，就是直接去感受众生中的佛性。“
======= end
  #+END_QUOTE

- 3166-3167, 标注, 2025 年 9 月 24 日星期三 上午 8:33:53
  #+BEGIN_QUOTE md5: 56e7cd80783b51de7e920ee87d05f0b5
  这种仪式只有相对的重要性。有些闭关者把自己的时间完全
  #+END_QUOTE

- 3166-3167, 标注, 2025 年 9 月 24 日星期三 上午 8:33:58
  #+BEGIN_QUOTE md5: 214a2781db4d8a7a9aa2417148ab505b
  这种仪式只有相对的重要性。有些闭关者把自己的时间完全投入在禅定上，有时会放弃所有仪式。
  #+END_QUOTE

- 3178-3181, 标注, 2025 年 9 月 24 日星期三 上午 8:36:07
  #+BEGIN_QUOTE md5: 7295f9a30b43bd5156232767212c89d5
  以佛塔的例子，西藏人认为能够花一个小时绕这样的一个纪念塔，其充实的效果远超过去慢跑。佛塔象征着佛陀的心
  （经文象征他的语，佛像象征他的身）。因为身体的右边被视为荣耀的位置，
  他们绕塔的时候一直让佛塔在他们右手边的位置，以示对佛和他教义的尊敬。换句话说，就是顺时针绕转。而他们边走，
  心边转向佛陀和他所教导的一切。
  #+END_QUOTE

- 3182-3183, 标注, 2025 年 9 月 24 日星期三 上午 8:36:44
  #+BEGIN_QUOTE md5: 60e0127f05851d2a7d4e333ee5e5609a
  这些画中的本尊不是本自实存的神，他们象征证悟的不同质地。”
  #+END_QUOTE

- 3187-3187, 标注, 2025 年 9 月 24 日星期三 上午 8:37:23
  #+BEGIN_QUOTE md5: b68c8c18eada6c37ca6559a445b0261e
  达成高度觉察性的一个主要障碍就是念头的疯狂泛滥。
  #+END_QUOTE

- 3187-3188, 标注, 2025 年 9 月 24 日星期三 上午 8:37:41
  #+BEGIN_QUOTE md5: 54dcfb02113e1b18777988b06fabc831
  达成高度觉察性的一个主要障碍就是念头的疯狂泛滥。观想的技巧有一些精密的方法，可以让脑筋一直处于混乱状态的人、
  很难让自己念头静下来的人把念头导向一个单一对象。
  #+END_QUOTE

- 3187-3191, 标注, 2025 年 9 月 24 日星期三 上午 8:38:11
  #+BEGIN_QUOTE md5: 34fc12427e84f1b9979c23ee87ad5d3b
  达成高度觉察性的一个主要障碍就是念头的疯狂泛滥。观想的技巧有一些精密的方法，可以让脑筋一直处于混乱状态的人、
  很难让自己念头静下来的人把念头导向一个单一对象。观想内容可以非常复杂，但它并不会加深脑筋的散乱，
  反而会使脑筋稳定，让它更平静。正确的观想需要三种特质：第一，保持一个清晰观想意象的能力，
  意思是说必须不断地把注意力拉回到所观想的对象上；第二，了解观想对象的象征意义；第三，保持对自我原始佛性的认识。
  #+END_QUOTE

- 3192-3193, 标注, 2025 年 9 月 24 日星期三 上午 8:40:20
  #+BEGIN_QUOTE md5: a455b1b5e017dc1bb700141e6fb763dc
  礼佛是表达敬意的一种方法，不是对一个神致意，而是对究竟智慧和代表究竟智慧的人致意。
  #+END_QUOTE

- 3194-3195, 标注, 2025 年 9 月 24 日星期三 上午 8:40:47
  #+BEGIN_QUOTE md5: 863050bb0aca29c5b80850dc690a50c7
  有一句谚语说：“如同山顶上不可能积水，傲慢的顶上不可能累积真正的功德。”
  #+END_QUOTE

- 3193-3195, 标注, 2025 年 9 月 24 日星期三 上午 8:41:00
  #+BEGIN_QUOTE md5: 5ead610afbf0a8d437a0dbf2ad9ad8dd
  。向这智慧致意同时也是一种谦虚的举动，可以对抗傲慢,而傲慢形成任何深层转化的障碍。傲慢阻止智慧和慈悲的显现。
  有一句谚语说：“如同山顶上不可能积水，傲慢的顶上不可能累积真正的功德。”
  #+END_QUOTE

- 3195-3199, 标注, 2025 年 9 月 24 日星期三 上午 8:41:51
  #+BEGIN_QUOTE md5: fa52c639c846c771cbb2c3c51df17481
  跪拜不只是一种机械性动作，当我们用两手、两个膝盖和额头同时碰地，我们创造出五个点，表示我们期盼净化五毒——贪、
  嗔、痴、慢、疑——把它们转化成五种相应的智慧层面。在我们起身的过程中，当我们双手在面前滑向自己时候，我们想：
  “愿我能把所有众生的痛苦聚集在我身上，解除他们所有的痛苦。”用这种方式，
  让我们在日常生活中的所作所为能远离普通平庸，把我们带回到心灵修持的道路上。
  #+END_QUOTE

- 3216-3217, 标注, 2025 年 9 月 24 日星期三 上午 8:45:06
  #+BEGIN_QUOTE md5: 3b71e2d5e81469e74f41d6daddf3d48f
  父：那你怎么解释证悟？ 子：就是对自己和现象究竟本性的发掘。
  #+END_QUOTE

- 3217-3226, 标注, 2025 年 9 月 24 日星期三 上午 8:49:41
  #+BEGIN_QUOTE md5: ac83b2cf49f0a2e4c5d17139acf166e7
  那你可不可以说清楚佛教所谓的信仰又是什么意思？ 子：这个词在西方充满着各种联想。佛教有四种不同的信仰层面。
  第一就是当我们听到一次心灵开示，或者佛陀的生平故事，或是一位伟大老师的生平故事时，心中被激起的清晰感和灵感，
  这是一种很强烈的兴趣。第二层面多是一种期望，是一种愿望，想知道更多，想亲自去体现一个开示，
  想跟随伟大老师的榜样，然后一点一滴地达成同样的完美。第三种层面就是当信仰转化成信心，一种确定性，
  来自自我印证佛法真理和心灵道路的效果，而从这个印证中，我们得到日益增强的满足感和充实感。有点像是发现一个景观，
  我们越透视它，它越美丽。到最后，就是我们发现不管状况是什么，我们的信心都永远不会改变，也不会被证明是错的。
  我们在修行中达成一种稳定性，生活中发生的任何事，不论是有利或无利的，都可以促进我们的进步。
  我们的信心成为性格的一部分，我们的信仰不可能回头。这就是佛教信仰的四种阶段，并不是一种知性的跳跃，
  而是阶段性发觉的果实，以及一种印证，心灵道路确实会有结果。
  #+END_QUOTE

- 3250-3250, 标注, 2025 年 9 月 24 日星期三 下午 1:18:54
  #+BEGIN_QUOTE md5: 063d37dca7ba1aa0549c5d2e9b43380a
  陷阱，因为死亡随时可能会来临，毫无警告地，死亡的时刻以及造成死亡的状况是完全无法预测的。
  #+END_QUOTE

- 3248-3250, 标注, 2025 年 9 月 24 日星期三 下午 1:19:01
  #+BEGIN_QUOTE md5: ca0fcadbce3cf4ccdc4fa81b80d8b89d
  看得更清楚，就可以让自己转向心灵事务。“如果我们活着，认为面前有无限的时间，而不是活得像只剩下几分钟生命,
  这是最致命的陷阱，因为死亡随时可能会来临，毫无警告地，死亡的时刻以及造成死亡的状况是完全无法预测的。
  #+END_QUOTE

- 3249-3250, 标注, 2025 年 9 月 24 日星期三 下午 1:19:07
  #+BEGIN_QUOTE md5: 50acfe39f70d8a65da40e7d314df6c5d
  ”如果我们活着，认为面前有无限的时间，而不是活得像只剩下几分钟生命,这是最致命的陷阱，因为死亡随时可能会来临，
  毫无警告地，死亡的时刻以及造成死亡的状况是完全无法预测的。
  #+END_QUOTE

- 3321-3323, 标注, 2025 年 9 月 24 日星期三 下午 1:26:55
  #+BEGIN_QUOTE md5: ec4ad1f2784d0be7dfe4946148118c9b
  痛也可以提醒我们，无数的众生正在经历痛苦，可以帮助我们重新燃起爱和慈悲心。痛也可以作为扫除我们负面业的扫把。
  事实上，因为痛苦是我们过去负面行为的结果，最好能够用心灵修持的方式来还债。
  #+END_QUOTE

- 3323-3326, 标注, 2025 年 9 月 24 日星期三 下午 1:27:42
  #+BEGIN_QUOTE md5: 6b16db727aaf19db208b467fcc1b8b9c
  安乐死和自杀都无法被接受。但这并不意味着没有希望的时候，生命必须无意义地延长。
  如果硬性用维生系统来延长一个濒临死亡人士的生命，或者维持一个不可能从昏迷中醒过来的生命，其实害处比好处多，
  因为那个人的意识会在生命和死亡之间漂流很长一段时间。这可能对他造成很大的干扰。
  最好是让濒临死亡的人在有意识和平和的状态下度过他最后的时光。
  #+END_QUOTE

- 3347-3349, 标注, 2025 年 9 月 24 日星期三 下午 1:30:08
  #+BEGIN_QUOTE md5: 5292bfd0d518cac6079967c6c333a196
  由业力产生的作用并不是一种处罚，而是一种自然的结果。你只不过是在收成自己播下的种。如果你把石头往天上丢，
  掉下来砸到你的头，你感到惊讶也没有用。
  #+END_QUOTE

- 3352-3353, 标注, 2025 年 9 月 24 日星期三 下午 1:30:45
  #+BEGIN_QUOTE md5: 9c5a87fd35b8a87bbf8c31b38e234a2f
  佛教中善与恶的概念不是绝对的，没有人规定做这件事或那件事是好的或坏的。所有的行动、言语和意念是根据动机和结果，
  也就是所创造的快乐和痛苦，才会有好坏之分。
  #+END_QUOTE

- 3372-3375, 标注, 2025 年 9 月 24 日星期三 下午 1:34:29
  #+BEGIN_QUOTE md5: d7a06d1d2baa7228b4bf3702c5e7d9ae
  意识接着就进入“形成的中阴”，就是死亡和下一次投胎之间的中间状态。所经历的就要看个人心灵的成熟度。
  对心灵没有任何认知的人，他们这一生中一切的意念、言语和所作所为，将决定这个“中阴”会有多可怕或多不舒适的经历。
  他们像一根羽毛，被自己“业”的狂风扫走，只有相当心灵认识的人，才能够控制接下来要发生的事。
  #+END_QUOTE

- 3386-3388, 标注, 2025 年 9 月 24 日星期三 下午 1:36:11
  #+BEGIN_QUOTE md5: bd4c592820f992a39781e1773daa0331
  梵文“瑜伽”这个词的意思是“结合”，藏文(Naljor)是“与真正本性结合”的意思。也就是说我们的心和佛陀的心结合在一起，
  或是和老师的心结合在一起，把他们的心灵成就融入我们自己的经验中。
  #+END_QUOTE

- 3389-3391, 标注, 2025 年 9 月 24 日星期三 下午 1:36:28
  #+BEGIN_QUOTE md5: 6960dbe777e9868a2558daf13a0c9489
  有名的印度瑜伽叫作“哈达瑜伽”(Hatha-yoga ),用一些肢体姿势和运动，配合呼吸的控制，达到某些精神和生理效果。
  这些运动能够带来内在的平静和放松，容易用平静的态度来面对生命中发生的每一件事。
  #+END_QUOTE

- 3389-3391, 标注, 2025 年 9 月 24 日星期三 下午 1:36:36
  #+BEGIN_QUOTE md5: 7fe492e26bbee438fe816fef9a9740d1
  最有名的印度瑜伽叫作“哈达瑜伽”(Hatha-yoga ),用一些肢体姿势和运动，配合呼吸的控制，达到某些精神和生理效果。
  这些运动能够带来内在的平静和放松，容易用平静的态度来面对生命中发生的每一件事。
  #+END_QUOTE

- 3389-3392, 标注, 2025 年 9 月 24 日星期三 下午 1:38:52
  #+BEGIN_QUOTE md5: aba17c1111f14710f4423634a9f542b8
  最有名的印度瑜伽叫作“哈达瑜伽”(Hatha-yoga ),用一些肢体姿势和运动，配合呼吸的控制，达到某些精神和生理效果。
  这些运动能够带来内在的平静和放松，容易用平静的态度来面对生命中发生的每一件事。
  藏传佛法也有很多修行方法运用肢体运动和气的控制。这些都是在长期闭关中教导的，从不开放给初学者，
  或不属于某种特定心灵修行的人士。
  #+END_QUOTE

- 3392-3392, 笔记, 2025 年 9 月 24 日星期三 下午 1:39:24
  #+BEGIN_QUOTE md5: 32178cb22f758abad003deed7cc00b81
  密宗?
  #+END_QUOTE

- 3490-3493, 标注, 2025 年 9 月 24 日星期三 下午 9:10:28
  #+BEGIN_QUOTE md5: fb6ad2d6bcfbf46e7fcba0cc12125c34
  比较有心灵传统的社会，好比近代的印度和西藏，会不惜代价地把社会整体的福祉放在个人主义的前面。
  集权主义的失败和悲剧，在于他们盲目且暴力地侵犯个人主义、控制个人，用一种完全相反的方式，
  声称他们在保护人民的福祉。我认为重点不应该在约束个人的自由，而是在个人身上培养一种责任感。
  #+END_QUOTE

- 3517-3525, 标注, 2025 年 9 月 24 日星期三 下午 9:15:36
  #+BEGIN_QUOTE md5: ee23dbadc1c83bc7b9ad65f26822521c
  言论自由的概念出自三个层面：政治的、哲学-科学的和宗教的。从政治的层面而言，
  言论和表达的自由意味着在开放政体之下，所有人都有表达政治意见的权利，也有权利支持这种意见，把意见呈现给选民，
  为了维护这些意见创立政党，为了执行这些意见，让这些政党的候选人当选——只要这一切不妨碍他人的自由。
  从哲学的层面而言，言论和表达自由的树立可以对抗宗教性的审查，好比说，令基督教教会废除审查制度，
  例如烧毁与教条相左的书籍。近代在现代集权政体之下，也有非常类似的现象。这些集权政体烧毁了书籍和艺术品，
  囚禁了科学家，因为他们的研究和集权政体的哲学教条相左。从宗教的层面而言，问题和我们很接近，
  因为像伊朗之类的神权政治国家，基于极权政治意识形态的程度，其实超过真正的宗教程度。他们对其他信仰极不包容，
  会用残暴的手法强迫信仰、压制异类。今日所有的主要民主社会奠基于政治意见的自由、科学和哲学研究的自由，
  以及宗教的自由，但永远有一个条件，就是不去妨碍他人的自由。
  #+END_QUOTE

- 3526-3527, 标注, 2025 年 9 月 24 日星期三 下午 9:16:09
  #+BEGIN_QUOTE md5: affb103ddb5a03ef9ba776b48758cec4
  还有一点非常重要，就是必须限于相关领域中。举个例子，言论自由不包含鼓励别人去杀人。如果我在协和广场演讲，
  说大家都应该去杀死某某人，这不叫言论自由。
  #+END_QUOTE

- 3531-3532, 标注, 2025 年 9 月 24 日星期三 下午 9:17:13
  #+BEGIN_QUOTE md5: 0f8d2893f97585dc422fda4d0271d271
  媒体中的暴力和污蔑人性的色情，可以说是对人权的一种侵犯，而不是该被言论自由保护的东西。
  #+END_QUOTE

- 3544-3546, 标注, 2025 年 9 月 24 日星期三 下午 9:18:53
  #+BEGIN_QUOTE md5: c9d1387bd3858a66f022e86d492e60ad
  说来说去,主要动机是利润，而不是知识的增进。只要后果对人有害，还要去强辩言论自由的神圣原则，
  对我而言似乎是倡导言论自由者嘲讽的骗局，在知识分子的一方，又形成一种对新形式的迷信。
  #+END_QUOTE

- 3559-3561, 标注, 2025 年 9 月 24 日星期三 下午 10:58:41
  #+BEGIN_QUOTE md5: 0580fd73df6831bb73b2f908ca71af86
  乌托邦主义者全部都是极权主义宪法的作者。为什么呢？因为他们从一个抽象的概念出发，认为人类应该如何做，
  然后以不择手段的方式去实践他们的想法，这不是真正的政治科学。乌托邦是一种公害。
  #+END_QUOTE

- 3561-3563, 标注, 2025 年 9 月 24 日星期三 下午 10:59:00
  #+BEGIN_QUOTE md5: 8821d373475b80233ab475a2ba27d368
  真正的政治科学只能从观察人类社会如何运作得到教训,包括人类的社会学、经济、历史。到底在实践上，
  什么可以运作得好，什么运作得不好？必须从这些科学出发，绝对不能毫无前提地出发。如果我们非常小心的话，
  可以辨识出某些指导原则。
  #+END_QUOTE

- 3598-3601, 标注, 2025 年 9 月 25 日星期四 上午 7:56:33
  #+BEGIN_QUOTE md5: cb89fa97cc52f2d26f86a2dce0018361
  佛教需要研究的心理分析层面即弗洛伊德的中心理论：无论人类多么努力地让自己内在清晰，无论多么谦虚，
  无论多么希望自己诚恳，无论如何想了解自己，改变自己，总有一样东西永远留在内省范围之外，
  就是弗洛伊德所谓的潜意识。简而言之，我们心中存留着一些心理形式、直觉，以及被压抑的记忆。
  #+END_QUOTE

- 3598-3602, 标注, 2025 年 9 月 25 日星期四 上午 7:56:49
  #+BEGIN_QUOTE md5: 2af8dc0ff5e96f3041d1e63408e4541a
  佛教需要研究的心理分析层面即弗洛伊德的中心理论：无论人类多么努力地让自己内在清晰，无论多么谦虚，
  无论多么希望自己诚恳，无论如何想了解自己，改变自己，总有一样东西永远留在内省范围之外，
  就是弗洛伊德所谓的潜意识。简而言之，我们心中存留着一些心理形式、直觉，以及被压抑的记忆。
  我们并不会意识到这些东西，也无法和它们相通，但这些东西会对我们心理产生作用和影响，因而会影响我们的行为。
  #+END_QUOTE

- 3612-3614, 标注, 2025 年 9 月 25 日星期四 上午 7:58:36
  #+BEGIN_QUOTE md5: 508ee791256151459c8ffa12eaaac54c
  其实我们可以说佛法更加强调这些心理倾向的重要性，因为这些心理倾向不只源自童年，更是源自无数过去世。
  它们被比喻成在意识的河床上——也就是“基础意识”——渐渐残留下来的层面。
  #+END_QUOTE

- 3634-3637, 标注, 2025 年 9 月 25 日星期四 上午 8:01:36
  #+BEGIN_QUOTE md5: b22bce985527ef70702105dcb6e089ab
  以我个人有限的经验，当我碰到曾经经历精神分析治疗的人士时，我总有一种印象，
  觉得他们可能已经成功地去除了问题中最戏剧性的成分，因为他们已经把问题追溯到童年，
  但是一直没有办法消除压抑他们内在自由最深沉的根源。经历这么多年的努力,他们似乎没有真正发出平静和满足的光泽，
  他们仍然脆弱、紧张、多虑。
  #+END_QUOTE

- 3631-3633, 标注, 2025 年 9 月 25 日星期四 上午 8:01:48
  #+BEGIN_QUOTE md5: 3c8d621e7fa8c5d605a08cf8e95fb309
  心灵道路的根本目的就是要消除这些习性，因为所有执着和排斥的念头，都起自于过去的缘。
  对心下工夫的过程包含要找到这些习性的根，检查它们的本性，让它们消融。
  #+END_QUOTE

- 3643-3644, 标注, 2025 年 9 月 25 日星期四 上午 8:03:21
  #+BEGIN_QUOTE md5: e19c80cf7706791b8eb5dca70911975a
  光认出我们过去的问题是不够的，能够重新经历一些很久以前的事件，只是一种有限的治疗，无疑能让某些塞住的东西松动，
  但是无法消灭它们主要的起因。
  #+END_QUOTE

- 3643-3645, 标注, 2025 年 9 月 25 日星期四 上午 8:03:26
  #+BEGIN_QUOTE md5: aae15ffd3c7aef4980a99546816717f9
  光认出我们过去的问题是不够的，能够重新经历一些很久以前的事件，只是一种有限的治疗，无疑能让某些塞住的东西松动，
  但是无法消灭它们主要的起因。如果我们想净化湖水，不断地搅起湖底的泥巴是没有什么用处的。
  #+END_QUOTE

- 3653-3656, 标注, 2025 年 9 月 25 日星期四 上午 8:05:17
  #+BEGIN_QUOTE md5: bcc1640ffe3df0d8047f26e583726681
  我们的确经常发现一个人在童年的早期，有一个特别戏剧性的场景，举例说，他和母亲发生冲突。我们可以说，
  为了使她痛苦，他破坏了某一样东西，或者故意在学校考低分，为的是要报复母亲，令其收回爱的举动。
  这种缺少了什么的模式埋在潜意识深处，当这个人长大以后，这种潜意识还会继续决定他的行为。
  #+END_QUOTE

- 3665-3668, 标注, 2025 年 9 月 25 日星期四 上午 8:08:42
  #+BEGIN_QUOTE md5: ab8ea654f3934e632ddce41ea7c24e56
  根据佛法静虑的科学，我们既不需要压抑欲望，也不需要让它在一般状态之下毫无拘束地奔放，
  反而我们试图从它之中完全解放出来。为了达成这个目的，必须用一套渐进的方法：先用一些减轻欲望强度的“解药”，
  再去认识欲望本身内在的空性，最后把欲望转化成智慧。在这个过程的结尾，欲望再也无法奴役人心。它会让步，
  让一种内在的喜悦显现，这种喜悦是不变的，没有任何执着。
  #+END_QUOTE

- 3705-3705, 标注, 2025 年 9 月 25 日星期四 上午 8:12:14
  #+BEGIN_QUOTE md5: 5deacfacd725b81c60acfe78bd9e50e7
  有一句西藏谚语：“不要只顾着 梯子，要记得你要爬向哪里。”
  #+END_QUOTE

- 1879-1879, 标注, 2025 年 9 月 25 日星期四 上午 8:13:29
  #+BEGIN_QUOTE md5: c47e67669c65d0cbb04d8d9b28da8a4c
  父：那你所谓的空性是什么？是虚无吗？
  #+END_QUOTE

- 1879-1883, 标注, 2025 年 9 月 25 日星期四 上午 8:13:52
  #+BEGIN_QUOTE md5: 6955d10681560e838d54a08edd0c458f
  父：那你所谓的空性是什么？是虚无吗？ 子：很多人对”空“的概念不安，甚至害怕。他们认为不可能有东西从”空“中生起，
  任何东西在”空“中也无法正常运作。而在这样的”空虚“中，没有任何定律可以运作，包括因果律。他们想象的”空“
<<<<<<< variant A
  是没有潜能显现任何东西的。这个想法令他们不安，那是因为他们把佛教所谓的”空性“和”虚无”混在一起了。“虚无”之中，
  一无所有。而”空性“事实上是”虚无”的反义词——它是一种宇宙性的潜能，宇宙、众生、动作、意识。
>>>>>>> variant B
  是没有潜能显现任何东西的。这个想法令他们不安，那是因为他们把佛教所谓的”空性“和“虚无”混在一起了。“虚无“之中，
  一无所有。而”空性“事实上是“虚无”的反义词——它是一种宇宙性的潜能，宇宙、众生、动作、意识。
####### Ancestor
  是没有潜能显现任何东西的。这个想法令他们不安，那是因为他们把佛教所谓的”空性“和”虚无”混在一起了。“虚无“之中，
  一无所有。而”空性“事实上是”虚无”的反义词——它是一种宇宙性的潜能，宇宙、众生、动作、意识。
======= end
  #+END_QUOTE

- 1885-1887, 标注, 2025 年 9 月 25 日星期四 上午 8:14:24
  #+BEGIN_QUOTE md5: d6998fa5edf416083124183a7937f1f0
  所以经文里面说：“因为有空性，一切方能存在。”所以说，空性之中隐含了一切的可能性，
  而这一切的可能性都是互相依赖的。
  #+END_QUOTE

- 1890-1891, 标注, 2025 年 9 月 25 日星期四 上午 8:14:56
  #+BEGIN_QUOTE md5: a0521da0c9d789bea57b59d1d20dc9b2
  所以说，“空性”不像一个容器中的空白空间，而是容器本身的本质，也是它所包含的任何东西的本质。
  #+END_QUOTE

- 1898-1898, 标注, 2025 年 9 月 25 日星期四 上午 8:16:16
  #+BEGIN_QUOTE md5: fc20e1694ed5fac9836b221024133836
  空性并不是什么和现象分开的东西。它就是现象的本质。
  #+END_QUOTE

- 3721-3722, 标注, 2025 年 9 月 25 日星期四 上午 8:18:35
  #+BEGIN_QUOTE md5: 9dd18df5660a8bf39a9ce85175c584f9
  问题是，当我们自己被社会特定事物所影响时，我们通常不会察觉。偏见的特色就是我们不会视它为偏见。
  事实上偏见也有好坏之分，从哲学家的观点来看，重要的是把偏见视为特定时代的产物。
  #+END_QUOTE

- 3722-3724, 标注, 2025 年 9 月 25 日星期四 上午 8:19:41
  #+BEGIN_QUOTE md5: 2c6b757eecd1d4a6d6aa954e60e97a41
  具有宇宙性关怀的宗教或哲学企图融入它们源起或发展成当地的社会特色时，它们并没有意识到这是有局限性的，
  只限于那个特定社会或文化环境。
  #+END_QUOTE

- 3721-3724, 标注, 2025 年 9 月 25 日星期四 上午 8:19:43
  #+BEGIN_QUOTE md5: baf051db44cdef7b295867898be7eefb
  问题是，当我们自己被社会特定事物所影响时，我们通常不会察觉。偏见的特色就是我们不会视它为偏见。
  事实上偏见也有好坏之分，从哲学家的观点来看，重要的是把偏见视为特定时代的产物。
  当具有宇宙性关怀的宗教或哲学企图融入它们源起或发展成当地的社会特色时，它们并没有意识到这是有局限性的，
  只限于那个特定社会或文化环境。
  #+END_QUOTE

- 3724-3730, 标注, 2025 年 9 月 25 日星期四 上午 8:21:27
  #+BEGIN_QUOTE md5: 3be399afdd22320f2bf8061230cf3623
  一个慈善行为背后的动机必须仔细地被检验。我是出于对社会习俗的尊敬才慷慨？还是真正是一种自发的利他态度？
  如果要完美，任何付出应该完全不期待任何回报，不期望任何称赞或感谢，甚至不应该有任何“积功德”的概念。
  如果要成为真正的功德，甚至于智慧的泉源，施舍的举动必须免于三种观念：相信主体真正存在，也就是付出的一方；
  相信对象的存在，也就是接受礼物的一方；相信行为的真正存在，也就是给与本身。真正的给与是通过一种纯净的动机，
  完全没有任何执着。所以很重要的是不要被行为的外在层面吸引住，尤其是要免于特殊社会性和文化性的影响，
  因为就如同西藏人所说的：“就链子而言，金链子和铁链子是一样的。”
  #+END_QUOTE

- 3733-3735, 标注, 2025 年 9 月 25 日星期四 上午 8:23:09
  #+BEGIN_QUOTE md5: 6feedc0c9b8f29536fbc502259f7944a
  我们必须了解文化影响力和心灵传统之间的差别。心灵传统是根据深沉的、活生生的经验，不是根据任何习俗。
  而心灵传统一再强调一种危险性，就是被形式所吸引，而不是形式背后的基础。有一句西藏谚语说：“不要只顾着梯子，
  要记得你要爬向哪里。”
  #+END_QUOTE

- 3741-3742, 标注, 2025 年 9 月 25 日星期四 上午 8:23:33
  #+BEGIN_QUOTE md5: 5438e3dd8725cebab145569613736edb
  真正的创造力意味着渐渐除去 无知和自我中心所造成的遮蔽， 揭开心和现象的究竟本性。这 才是真正”新“的发现。
  #+END_QUOTE

- 3748-3750, 标注, 2025 年 9 月 25 日星期四 上午 8:24:39
  #+BEGIN_QUOTE md5: 763c812a48b6bb205aadb28fdeba5407
  整个西方文明导向历史。它相信历史的发展以及时间的生产性，换句话说——用 19 世纪最常用的名词——它相信进步。有人常说，
  如此相信进步是很幼稚的。事实上，相信进步就是相信历史能给人类处境带来改善，通过技术发明、科学、道德修养的增进，
  以及民主制度的普及。
  #+END_QUOTE

- 3763-3765, 标注, 2025 年 9 月 25 日星期四 上午 8:26:37
  #+BEGIN_QUOTE md5: a597f64018de48d72461a84f35efdcee
  对新奇喜好所带来的影响，就是不停地追寻变化，不论代价；而通常是徒劳无功充满挫折的。一般来说，
  迷上新奇和不同的事物是内在贫乏的反映。因为我们在自己之内找不到快乐，只好极度地向外找，在事物中、
  #+END_QUOTE

- 3763-3766, 标注, 2025 年 9 月 25 日星期四 上午 8:26:43
  #+BEGIN_QUOTE md5: de1156ced2d5919909cc8e0e65bd0aee
  对新奇喜好所带来的影响，就是不停地追寻变化，不论代价；而通常是徒劳无功充满挫折的。一般来说，
  迷上新奇和不同的事物是内在贫乏的反映。因为我们在自己之内找不到快乐，只好极度地向外找，在事物中、在经验中，
  在越来越奇怪的思考和行为模式中。
  #+END_QUOTE

- 3763-3766, 标注, 2025 年 9 月 25 日星期四 上午 8:26:59
  #+BEGIN_QUOTE md5: eec92537432e0f524da3c4098bdb4856
  对新奇喜好所带来的影响，就是不停地追寻变化，不论代价；而通常是徒劳无功充满挫折的。一般来说，
  迷上新奇和不同的事物是内在贫乏的反映。因为我们在自己之内找不到快乐，只好极度地向外找，在事物中、在经验中，
  在越来越奇怪的思考和行为模式中。简而言之，我们让自己离快乐越来越远，因为我们一直在不可能找到它的地方拼命找。
  #+END_QUOTE

- 3763-3768, 标注, 2025 年 9 月 25 日星期四 上午 8:27:20
  #+BEGIN_QUOTE md5: b9fe0a0cae41113b7357fc4318e7b083
  对新奇喜好所带来的影响，就是不停地追寻变化，不论代价；而通常是徒劳无功充满挫折的。一般来说，
  迷上新奇和不同的事物是内在贫乏的反映。因为我们在自己之内找不到快乐，只好极度地向外找，在事物中、在经验中，
  在越来越奇怪的思考和行为模式中。简而言之，我们让自己离快乐越来越远，因为我们一直在不可能找到它的地方拼命找。
  这其中的危险就是我们可能会完全失去快乐的踪影。在最平凡的层面，
  不必要的东西对我们的吸引力使我们对新鲜事产生欲望，这侵蚀着我们的心，干扰心
  #+END_QUOTE

- 3763-3768, 标注, 2025 年 9 月 25 日星期四 上午 8:27:29
  #+BEGIN_QUOTE md5: 45a39dbdb20f4e2ea2a7d57e3c62651e
  对新奇喜好所带来的影响，就是不停地追寻变化，不论代价；而通常是徒劳无功充满挫折的。一般来说，
  迷上新奇和不同的事物是内在贫乏的反映。因为我们在自己之内找不到快乐，只好极度地向外找，在事物中、在经验中，
  在越来越奇怪的思考和行为模式中。简而言之，我们让自己离快乐越来越远，因为我们一直在不可能找到它的地方拼命找。
  这其中的危险就是我们可能会完全失去快乐的踪影。在最平凡的层面，
  不必要的东西对我们的吸引力使我们对新鲜事产生欲望，这侵蚀着我们的心，干扰心的平静；反而在让自己的需求加倍，
  而不是在学会不要任何需求。
  #+END_QUOTE

- 3785-3788, 标注, 2025 年 9 月 25 日星期四 上午 8:30:22
  #+BEGIN_QUOTE md5: e4ef55953e87ed50d5a3b9e2513d2224
  另外一方面又认为文化应该推广给更多的人，是完全属于西方的态度。物质被利用来创造进步，日益增加的人群共享这种进步。换句话说，救赎是在时间之中，不是在时间之外。 子：在时间之中的救赎是菩萨的誓言，发誓为所有众生努力，直到他们全部从痛苦和无知中被解放出来。菩萨永远不会放弃，也永远不会遗弃他对所有众生的责任，直到每一个众生都走上智慧的道路，达成证悟。
  #+END_QUOTE

- 3814-3818, 标注, 2025 年 9 月 25 日星期四 上午 8:36:16
  #+BEGIN_QUOTE md5: 25213ded063ebe6e7fecda6017b165e4
  最重要的是要认识这些真理，更深入去体现，去”成就“。如果我们忽略这个，那用一切代价来发明新东西又有什么用？
  所以我的结论是，心灵生活跟追求新奇非常不同，它可以让我们又能够重新发现“单纯”——一种我们已经失去胃口的东西。
  它可以让我们生活单纯化，让我们不为取得一些不真正需要的东西而继续折磨自己；让我们的心单纯化，
  让我们不再追回过去，让我们不再幻想着未来。
  #+END_QUOTE

- 3818-3820, 标注, 2025 年 9 月 25 日星期四 上午 8:36:36
  #+BEGIN_QUOTE md5: 7f6547df5d4e9a0b60fadc602cc6e1e8
  西方也有很多人士，包括仔细留意艺术最新发展的人士，很清楚地知道西方艺术的一大部分就是在欺骗大众，
  让天真的观众晕头转向。幸好这不是唯一的一面。真正的创意和发明还是存在。
  #+END_QUOTE

- 3839-3841, 标注, 2025 年 9 月 25 日星期四 上午 8:42:51
  #+BEGIN_QUOTE md5: aa50a5b04ead797030f839b8e18539ca
  人类精神最大的威胁之一，就是陷入固定的模式。如果我们没有努力检视前人所留下来的观念，不满足于现成的观念，
  不接受事物的表面价值，而不去重新思考，根据理性和经验决定要保留什么、要抛弃什么，
  那么人类的思考只不过是一场懒惰的睡眠。
  #+END_QUOTE

- 3852-3853, 标注, 2025 年 9 月 25 日星期四 上午 8:44:13
  #+BEGIN_QUOTE md5: 3b871f5f5c284ddda9e5ac8e101b17f6
  转化。虽然每一样东西都需要时间才能创造出来，但时间本身却创造不出任何东西。
  #+END_QUOTE

- 3868-3871, 标注, 2025 年 9 月 25 日星期四 上午 8:49:20
  #+BEGIN_QUOTE md5: e1859f3110247c4ddf81f1d9d91c072d
  佛教徒认为：“一个人满足于自己所拥有的，手中已经持有宝藏。”不满足的心态出自一种习惯，认为多余的东西是必要的。
  这不单只是财富问题，也是舒适、享乐，以及累积“没有用的知识”的问题。只有一样东西是我们永远不应该满足的，
  就是我们自己的智慧。也只有一种努力应被视为永远不足，就是努力走向心灵进步，实现他人的福祉。
  #+END_QUOTE

- 3867-3871, 标注, 2025 年 9 月 25 日星期四 上午 8:49:28
  #+BEGIN_QUOTE md5: b66e92a56cc4d86d302a6355f82fdfbc
  。因为世界只能通过我们改变自己而改变，不断地拥有并没有太大作用。佛教徒认为：“一个人满足于自己所拥有的，
  手中已经持有宝藏。”不满足的心态出自一种习惯，认为多余的东西是必要的。这不单只是财富问题，也是舒适、享乐，
  以及累积“没有用的知识”的问题。只有一样东西是我们永远不应该满足的，就是我们自己的智慧。
  也只有一种努力应被视为永远不足，就是努力走向心灵进步，实现他人的福祉。
  #+END_QUOTE

- 3888-3889, 标注, 2025 年 9 月 25 日星期四 上午 8:52:15
  #+BEGIN_QUOTE md5: 550087b102fc2341e41753cc8f853c60
  西奥然那一段话中最令我震撼的是，他提醒西方，智慧就是受苦，至少智慧是要通过受苦才能得到。
  #+END_QUOTE

- 3897-3900, 标注, 2025 年 9 月 25 日星期四 上午 8:53:30
  #+BEGIN_QUOTE md5: 194e0f4093f8e1069ec11558a8b8f158
  根据一种说法：“心灵修持是先苦后甘，世俗事物是先甘后苦。”另外一种说法是：“开始,什么都不来；中间，什么都留不住；
  最后，什么都不会离开。”事实上.我想补充的是，严格说来，需要取得智慧的努力不是“受苦”，反而总是被定义为“
  以努力的形态所显现的喜悦”。
  #+END_QUOTE

- 3961-3963, 标注, 2025 年 9 月 25 日星期四 下午 1:26:09
  #+BEGIN_QUOTE md5: 50477c6e8ff8990d0a462b2ad6ea5860
  一个人无法反抗自己所种下的因，但是他可以建立未来，学会分辨什么事会引导他走向痛苦，什么事会使他从痛苦中解脱。
  这和宿命地去接受一个不可避免的未来是非常不同的。
  #+END_QUOTE

- 4012-4014, 标注, 2025 年 9 月 25 日星期四 下午 6:26:05
  #+BEGIN_QUOTE md5: 82e5ec8bf8cb3294080edbf82be34db3
  科学的信仰取代了对知识的信仰。那是第一步，启蒙运动的哲学。启蒙运动的“明灯”就是理性的明灯，
  让我们可以了解现实如何运作，以及驱逐所有的幻象、情欲、荒谬的信仰和迷信。从那个时候开始，
  个人如果要达到内在智慧，必须通过客观知识。
  #+END_QUOTE

- 4012-4015, 标注, 2025 年 9 月 25 日星期四 下午 6:26:11
  #+BEGIN_QUOTE md5: caa83330881d33629c339d5eafefcab3
  科学的信仰取代了对知识的信仰。那是第一步，启蒙运动的哲学。启蒙运动的“明灯”就是理性的明灯，
  让我们可以了解现实如何运作，以及驱逐所有的幻象、情欲、荒谬的信仰和迷信。从那个时候开始，
  个人如果要达到内在智慧，必须通过客观知识。借用当时的讲法,“理性的火把”照亮了人类幸福的问题。
  #+END_QUOTE

- 4038-4039, 标注, 2025 年 9 月 25 日星期四 下午 6:29:16
  #+BEGIN_QUOTE md5: 8792aaee2362b7b83c4f21359c380014
  当过度的物质发展出完全不必要的产品，所有人都被”多余“的系统缠住。如果没有心灵价值，
  物质进步只能带领我们走向灾难。
  #+END_QUOTE

- 4096-4099, 标注, 2025 年 9 月 25 日星期四 下午 6:39:32
  #+BEGIN_QUOTE md5: 585bb5f177e30c1edc8fe0cbe9dd7e55
  整体必须反映到局部上。这是所有乌托邦思想中共有的。所有这类的社会理论都是乌托邦式的，这些理论都认为人类的进步，
  或者说人类的生产，必须从头到尾改进社会，不是渐进的、不是局部的，而是突然的、全面性的。当社会整体变公正，
  它的每一个分子也会变成公正的、快乐的。
  #+END_QUOTE

- 4116-4120, 标注, 2025 年 9 月 25 日星期四 下午 6:42:03
  #+BEGIN_QUOTE md5: 28efeb2eaeca8836b072e93edca819b1
  最后就是社会乌托邦。它们的全面崩溃是二十世纪历史的主题。结论很简单：它们就是行不通，乌托邦只造成了有害的结果。
  它们的社会失败了。它们原来给大家的期望，就是能为人类引进最大的平等和快乐。所有实验的结果就是失败。
  共产社会中的生活水准比资本社会差了十到十五倍，虽然所有的不平等被掩饰了，但其中的差距还要更大。
  这些社会全然地失败了，无论是道德方面、人类自由方面，还是物质方面。
  #+END_QUOTE

- 4182-4184, 标注, 2025 年 9 月 25 日星期四 下午 6:51:24
  #+BEGIN_QUOTE md5: 04fe12966aeccd6b3ec5447dd7ce231b
  我每次看佛教大师传记的时候，最令我震撼的是他们都说死亡不造成任何差别。如同再生，死亡不会改变心灵成就。
  佛法确实相信存在连续性的概念，但真正的心灵成就也超越生和死，它是我们自身可以成就的不变真理，
  不再依赖未来而得到的满足。
  #+END_QUOTE

- 4194-4196, 标注, 2025 年 9 月 25 日星期四 下午 10:33:38
  #+BEGIN_QUOTE md5: cf86c3895a873383b36e8a9cca3da508
  我们的对话也帮助我越来越了解，为什么佛教今天在西方世界可以引起那么大的兴趣。最主要是因为佛教填满了一个缺口，
  这个缺口是西方哲学遗弃了伦理和生活艺术的范畴而造成的。
  #+END_QUOTE

- 4215-4218, 标注, 2025 年 9 月 25 日星期四 下午 10:52:27
  #+BEGIN_QUOTE md5: 9491a98d7cdda09075ff57b55dc843ab
  从 17 世纪以来,政治便成为新著作的主要焦点，这些著作中出现关键性的见识，仍然在给予现代思想营养。
  但政治同时养育了教条主义和侵略主义的精神，成为哲学中某一种暴君倾向的避难所。在这个时候,
  哲学实际上已经让出了指导良心的角色，而身为所有知识的无上君主，哲学的王位也已经被篡夺。
  #+END_QUOTE

- 4270-4273, 标注, 2025 年 9 月 25 日星期四 下午 11:00:55
  #+BEGIN_QUOTE md5: ab0ddfa28e286be211f42fd1fa3eed34
  所有人在生命中寻找的就是快乐。但是我们千万不能误会这句话表面上的简单性。在此，所谓的“快乐”
  不只是某一种舒服的感觉，而是一种满足，满足于我们的生活方式完全呼应我们最深的本性。这种快乐就是让自己知道，
  我们可以发挥每个人都具有的潜力，了解到心的真正和究竟本性。
  #+END_QUOTE
