:PROPERTIES:
:ID:       96e1baa7-605d-4419-92ac-11976beb6063
:END:
#+TITLE: 比山更高：自由攀登者的悲情与荣耀-宋明蔚
#+AUTHOR: Yang,Ying-chao
#+DATE:   2025-09-26
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:  oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :笔记:bishangengga:note:ireader:unwashed:

* Unwashed Entries                                                  :noexport:

- 22-23, 标注, 2025 年 9 月 26 日星期五 上午 7:47:31
  #+BEGIN_QUOTE md5: 94bfb79540539f69d73b70add75fe7c7
  我们常常把人生比作翻越高山，就好像攀登比人生更容易理解。事实上，大多数人对人生一知半解，对登一无所知。
  #+END_QUOTE

- 35-38, 标注, 2025 年 9 月 26 日星期五 上午 7:49:34
  #+BEGIN_QUOTE md5: a73fb9c1e1217654067d4f76bf066cb6
  这两类民间登山者的叙事也代表着过去二十年来中国社会的两极价值取向。
  攀登世界最高峰的一类人象征着当今社会的整体基调:极度渴望成功，高度以功利为导向，
  关注宏大的叙事与不断攀升的数字。而这本书里的自由攀登者们则代表着另一类极少数群体。
  他们并不想完成一座比一座高的山峰，只是想在其中一座山峰上画下一笔优美的线条，并在攀登过程中获得足够多的快乐。
  #+END_QUOTE

- 107-108, 标注, 2025 年 9 月 26 日星期五 上午 7:57:03
  #+BEGIN_QUOTE md5: d7c08745226d1ba6002f46c248653a1a
  他们只是想自由地攀登，自由地安排自己的时间，想爬哪座山就爬哪座山。对于中国民间登山者而言，“自由地攀登”
  是个高远而缥缈的目标。
  #+END_QUOTE

- 233-235, 标注, 2025 年 9 月 26 日星期五 上午 8:26:51
  #+BEGIN_QUOTE md5: 916936b6adac496e73c4dc50f045ec34
  严冬冬并非完全笃定要走登山这条路，他也感到过迷茫。一方面，他越来越痴迷于登山这件事。他多次说过，
  在过去二十年里，登山所带来的存在感是他从未感受过的。进入实验班、名列前茅无法让他感到生命的热烈。高考状元、
  清华学子的身份也无法让他感受到存在的价值。唯有登山能让他感受到自己活着。
  #+END_QUOTE

- 254-256, 标注, 2025 年 9 月 26 日星期五 上午 8:28:44
  #+BEGIN_QUOTE md5: 9c077e11af9b2d07065b2807e642e250
  在中国，对于大多数心怀理想的青年来说，自由都不是一件简单的事情。在实践自由意志的同时，
  他们还必须要摆脱外力的束缚:不用为了生计，或是基本的生存而忧愁烦恼;不被传统的家庭观念绑架;
  不被困在日常生活的琐事之中。
  #+END_QUOTE

- 282-283, 标注, 2025 年 9 月 26 日星期五 上午 8:33:42
  #+BEGIN_QUOTE md5: 659288f1532f0cdaba7a69f591deede9
  作为登山队的前站队员，
  #+END_QUOTE

- 292-295, 标注, 2025 年 9 月 26 日星期五 上午 8:35:28
  #+BEGIN_QUOTE md5: 0236e62bb194fcf1f39283fa8dcd6e9a
  在冲顶那一天，他望到前方雀儿山的顶峰拨云而出，万分激动。这种激动一直持续到他站在顶峰的那一刻。
  这是他第五次攀登，却是他第一次登顶。严冬冬曾经以为，只要真心热爱攀登这件事，登不登顶其实并不是那么重要。
  但当他站在雾蒙蒙的山顶的这一刻，一切都改变了。
  #+END_QUOTE

- 523-525, 标注, 2025 年 9 月 26 日星期五 下午 3:52:05
  #+BEGIN_QUOTE md5: 5d8c19e5c8f1d23def495071216d37e8
  中。严冬冬写道:集训只有单调的体能训练，几乎完全没有攀爬与技术训练;训练方法陈旧而不够科学，
  集训队里弥漫着功利性的竞争气氛，攀登中的关键决定完全要看领导的脸色……我觉得窒息，我想要的是真正的、自由的攀登，
  不是这些东西。
  #+END_QUOTE

- 525-526, 标注, 2025 年 9 月 26 日星期五 下午 3:52:24
  #+BEGIN_QUOTE md5: 48b93858bd1d8888defebe5405e4aac5
  《极限登山》所倡导的阿式攀登理念是自由，是灵活应变是每个人只对自己负责，
  这几乎与珠峰上的喜马拉雅式攀登风格背道而驰。
  #+END_QUOTE

- 525-529, 标注, 2025 年 9 月 26 日星期五 下午 3:53:04
  #+BEGIN_QUOTE md5: 8818c2c22c84cf1f5cedead0c01f88a2
  《极限登山》所倡导的阿式攀登理念是自由，是灵活应变是每个人只对自己负责，
  这几乎与珠峰上的喜马拉雅式攀登风格背道而驰。在珠峰火炬传递的活动中，每名队员都要严格听从攀登队长、总队长、
  总指挥的命令。这无比接近于军事化的战斗。与阿式攀登相比，喜马拉雅式攀登体现的是另一重组织艺术:行军布阵的艺术，
  把握好天气窗口的艺术，人与人之间沟通的艺术，把一个个螺丝钉与螺母调试完备从而组装出一套强大系统的艺术。
  这跟登山有关，但又与登山的本质无关。
  #+END_QUOTE

- 534-538, 标注, 2025 年 9 月 26 日星期五 下午 3:54:07
  #+BEGIN_QUOTE md5: 1e700923e51f3100ecd104e0afcae784
  什么是自由?什么是登山的自由?严冬冬后来在《登山的自由》一文中写道: 有谁不渴望自由呢?登山的人尤其如此:
  远离尘器的羁绊，在广阔雄浑的山间让生命力恣意飞扬，这样的向往，
  应该说是驱使我们中许多人开始投身登山的动力源泉之一吧。自由是登山者能够追求的终极目标。自由就是随心所欲。
  在登山这方面，理想程度的自由，应该是随便任何一座山、任何一条路线，在任何时间以任何方式都可以攀爬……”
  #+END_QUOTE

- 538-539, 标注, 2025 年 9 月 26 日星期五 下午 3:54:20
  #+BEGIN_QUOTE md5: a601c6d03bceaff7eb479926846efb05
  在自由之魂刚刚成立的那一刻，任他们的心灵恣意飞扬，
  他们的身体却被桎梏在那顶不足两平方米的小帐篷里渴望着被赐予冲顶珠峰的机会。
  #+END_QUOTE

- 525-525, 笔记, 2025 年 9 月 26 日星期五 下午 3:55:53
  #+BEGIN_QUOTE md5: 385f623dc92d99b0e40a3475a9104c01
  哪里都是江湖,有人的地方,就有江湖。
  #+END_QUOTE

- 616-619, 标注, 2025 年 9 月 26 日星期五 下午 6:24:29
  #+BEGIN_QUOTE md5: a41137ef42e2f90d060e78242622dedf
  多年以后当严冬冬回顾这两次独攀时，认为没登顶是再正常不过的事情。他当时的登山技术与理念都不算成熟。
  但是他很享受独自在山里的时光。他喜欢那种孤独感。孤独会放大登山的生命体验，而这种深刻的体验，
  让严冬冬深深地为之着迷。
  #+END_QUOTE

- 758-760, 标注, 2025 年 9 月 26 日星期五 下午 7:00:13
  #+BEGIN_QUOTE md5: 3bebfa75ab6d5602e8e5119660d2d0ac
  景区里的游客越来越多。徐老幺买了辆自行车，骑到镇上批发银手镯、项链等工艺品，拿到景区里售卖。一枚银手镯进货价 5
  元，他卖 100;一串项链进货价 10 元，他卖 200。“你要卖得越高，他就要的人越多。卖得便宜就不要。”徐老幺说。
  #+END_QUOTE

- 753-760, 标注, 2025 年 9 月 26 日星期五 下午 7:00:20
  #+BEGIN_QUOTE md5: eb57ce92a5e6dcb9ddb231fbe2bbecba
  海子，徐老幺也会鼓起勇气，慢慢地凑近，摸一下湖水就赶紧跑开。 到了上学的年纪，
  徐老幺去双桥沟里的小学念了几天书。有一次，徐老幺放羊后赶到学校。教室里已经开课。他不敢进去，怕被老师骂，
  只好趴在门边，往里瞄了一眼，就吓得立马背起书包哒哒哒地溜出学校，跑回山上放羊了。从那以后，徐老幺再没有读过书，
  也不识字。 双桥沟两侧的山峰遮挡了村民的视野，也限制着村子的交通和经济。等到了徐老幺可以摸猎枪的年纪，
  他跟着大人们上山打猎为生。几年后，国家禁止打猎，没收了枪支，徐老幺也学着村里人摆摊贩卖小商品。
  景区里的游客越来越多。徐老幺买了辆自行车，骑到镇上批发银手镯、项链等工艺品，拿到景区里售卖。一枚银手镯进货价 5
  元，他卖 100;一串项链进货价 10 元，他卖 200。“你要卖得越高，他就要的人越多。卖得便宜就不要。”徐老幺说。
  #+END_QUOTE

- 758-760, 标注, 2025 年 9 月 26 日星期五 下午 7:00:34
  #+BEGIN_QUOTE md5: 4d6ee7cca6d5563a7b544f837bcd5385
  徐老幺也学着村里人摆摊贩卖小商品。景区里的游客越来越多。徐老幺买了辆自行车，骑到镇上批发银手镯、项链等工艺品，
  拿到景区里售卖。一枚银手镯进货价 5 元，他卖 100;一串项链进货价 10 元，他卖 200。“你要卖得越高，他就要的人越多。
  卖得便宜就不要。”徐老幺说。
  #+END_QUOTE

- 1031-1034, 标注, 2025 年 9 月 26 日星期五 下午 10:08:06
  #+BEGIN_QUOTE md5: 3498a118d508c090e8a2795f0409f891
  攀登运动是一项本质上具有危险性的活动，可能导致严重受伤或死亡，参与攀登的人，必须清楚认识到这一点。
  严冬冬并不惧怕死亡。他承认登山运动会带来死亡的可能性，但并不会就此被动地接受，而是尽其所能去阻止事故的发生。
  #+END_QUOTE

- 1103-1105, 标注, 2025 年 9 月 26 日星期五 下午 10:19:50
  #+BEGIN_QUOTE md5: 8c4dba110bcd99a922c9a136b2d13856
  在《巅峰记忆》的登顶气氛中，李兰在影片中念了一段精彩的独白:“我们走进了山的内心，触摸了顶峰之上的天空，
  这空不是虚无，而是无边无际的自由，是所有攀登过的人们，都会向往的、可能付出生命代价的—自由。”
  #+END_QUOTE

- 1171-1176, 标注, 2025 年 9 月 26 日星期五 下午 10:55:17
  #+BEGIN_QUOTE md5: 1b899cc26c0f989f39639c8f19ecf107
  先后经历了冻伤、暴雪、冰雹、雷暴、狂风之后，老布等人终于站在了海拔 6422 米的雪莲西峰(白玉峰)上。登顶后，
  他们一路下撤，连夜出山，70 个小时后，火速赶回了乌鲁木齐。“就算我们刚刚抢了一家银行，也不太可能撤得比这还快了。”
  老布在攀登报告中写道。他们其实还能更快，如果他们没有把大本营附近堆积成山的垃圾运走的话—
  那些都是号称热爱户外的徒步者们丢弃在那里的。老布等人把这次史诗级的攀登路线命名为“TheGreat White Jade Heist”。
  字面意思是“白玉峰大劫案”。严冬冬在翻译这篇攀登报告时，把它翻译成一个更朴素的名字“白玉之路”。
  #+END_QUOTE

- 1291-1294, 标注, 2025 年 9 月 26 日星期五 下午 11:06:21
  #+BEGIN_QUOTE md5: 81fd32bc0734cf242f09fbb0d11830bd
  严冬冬后来回忆这划时代的一刻:“周遭的景色令人目不暇接。俯瞰四周的群山，突然间，它们显得那么低矮，那么遥远，
  犹如远方的海浪。我们才发现，我们一直都无暇顾及它们的存在。自从早上离开营地后，我们就完全沉浸在攀登的过程中。
  这是我们首次开辟的新路线，就以我们登山组合的名字，命名它为‘自由之魂’(The Free Spirits).” 这两名 25
  岁的年轻人不仅在幺妹
  #+END_QUOTE

- 1356-1357, 标注, 2025 年 9 月 27 日星期六 上午 7:25:23
  #+BEGIN_QUOTE md5: f2574ffa2d6370482469109babc7f6ff
  自由攀登者的精神世界更接近道家哲学。当你刻意追求它时，它离你越来越远。当你淡然处之时，意想不到的奖赏终究会来。
  #+END_QUOTE

- 1436-1439, 标注, 2025 年 9 月 27 日星期六 下午 2:12:39
  #+BEGIN_QUOTE md5: a51cbf56c376166be3f2da688b489cc3
  陈家慧也清醒地面对这个复杂的世界。有一次，陈家慧参加了大学的校友会，回来后对孟春表达出她的真实想
  法:“许多人在那里假装帮助学生，但是他们真实目的是编织他们的关系网，最终还是为了他们的个人利益。
  他们努力控制别人去提高自己的地位。我永远不想那样。”“在优胜美地没人会在乎我的社会地位。
  在那儿每个人只是一个攀登者。”
  #+END_QUOTE

- 1513-1516, 标注, 2025 年 9 月 27 日星期六 下午 2:25:09
  #+BEGIN_QUOTE md5: 967049d35c5b225e96d65462ef991725
  这名自由登山者胆子并不算大。他在下坡时会害怕，在悬崖高处会恐惧，半夜还会从噩梦中惊醒，
  但他从不惧怕死亡他甚至还会和搭档反复探讨死亡的可能性，死亡发生的场景，“我承认它，承认我可能会死掉,”严冬冬说，
  “但是这个可能性接受了，并不代表我不去以任何我可能做到的事情来阻止它发生。”他无法预测不可知的未来，
  更不想犹疑不定地止步当下。他唯一能做的就是在那个结局到来之前，尽可能多地攀登,
  #+END_QUOTE

- 1827-1828, 标注, 2025 年 9 月 27 日星期六 下午 7:06:34
  #+BEGIN_QUOTE md5: c8f47a120794de74f0ba6d0d8098b1b3
  自由，人类所追逐、向往的自由，本是看不见、摸不着的抽象观念。只有碰撞到坚硬的现实，
  自由才会更凸显出其意义和价值。
  #+END_QUOTE

- 1875-1875, 标注, 2025 年 9 月 27 日星期六 下午 7:10:34
  #+BEGIN_QUOTE md5: 6a304dcd4428f27cd145f3e45d0d2ba6
  2012 年 4 月 28
  #+END_QUOTE

- 1875-1875, 标注, 2025 年 9 月 27 日星期六 下午 7:10:38
  #+BEGIN_QUOTE md5: afb04f78b2a33932ec9d02d56fcc1953
  2012 年 4 月 28 日
  #+END_QUOTE

- 2059-2061, 标注, 2025 年 9 月 27 日星期六 下午 7:29:03
  #+BEGIN_QUOTE md5: 57ee7c51dbef805ae8b40a6dd0626538
  从新疆回到北京后，周鹏又回到了北京密云的房子里。如今五居室的房间里只剩他自己，更显得冷清空旷。那一晚，
  他做了个梦。梦中，他又回到了西天山的冰川。严冬冬浑身冰冷，想要和他说些什么。李爽后来跟周鹏说，
  她做了一模一样的梦。
  #+END_QUOTE

- 2137-2139, 标注, 2025 年 9 月 27 日星期六 下午 7:35:36
  #+BEGIN_QUOTE md5: f8bf282aca70bd0f07561605e004bba2
  不知怎的，后来赵哥还是没忍住。他和对方几句不和，一拳抡到对方脑袋上，手立马就肿了，在战斗中还落个下风。
  好在周鹏及时赶到，众人这才联合起来一番“说服教育”。对方被教育得够呛，在派出所报了案。周鹏和赵兴政最后交了 5000
  元的罚款。他们觉得值。
  #+END_QUOTE

- 2141-2143, 标注, 2025 年 9 月 27 日星期六 下午 7:36:08
  #+BEGIN_QUOTE md5: db974f642abe76d7c329a2f8f652e5a9
  再后来，公司黄了。他盘下北京二环边上的一家咖啡馆，再把它改成小酒馆。他蓄起胡子，研究起哲学与超验心理学，
  每天慵懒地睡到中午，再迷醉到深夜。只有当《白鸽》的音乐响起时，他才会短暂地回到过去。
  那是他前半生里最骄傲的一段时光，
  #+END_QUOTE

- 2161-2164, 标注, 2025 年 9 月 27 日星期六 下午 7:38:29
  #+BEGIN_QUOTE md5: 6322f690ce0d4894346478011ec0318a
  历史。十年就这么过去了。“自由之魂”的名字沉寂下来，逐渐被新一代的登山英雄和攀登传奇取代。
  它似乎成为周鹏心中一个遥远而陌生的词。只有当某个学生来到他的白河小院，不经意间问他这里的 wifi 密码时，
  周鹏才会微笑着重提起那个熟悉的名字:the free spirits。
  #+END_QUOTE

- 2471-2473, 标注, 2025 年 9 月 27 日星期六 下午 10:45:54
  #+BEGIN_QUOTE md5: 895239120165627a85b7effb1994a250
  徐晓东还给他送了个外号，叫“王大垮”，以取笑他这种混日子的状态。王滨却对这种生活方式颇为骄傲。
  他认为自己就像是个嬉皮士，不追求物质生活的享乐，排斥主流的传统价值观，只追求内心世界的平和与精神世界的美好。
  #+END_QUOTE

- 2470-2473, 标注, 2025 年 9 月 27 日星期六 下午 10:46:04
  #+BEGIN_QUOTE md5: 7e90bbb598b739e5c5c5e2b43a9ac5a8
  他给杂志写写稿，拍拍照片，没有任何存款，随时说走就走，过上了四处流浪的生活。徐晓东还给他送了个外号，叫“王大垮”，
  以取笑他这种混日子的状态。王滨却对这种生活方式颇为骄傲。他认为自己就像是个嬉皮士，不追求物质生活的享乐，
  排斥主流的传统价值观，只追求内心世界的平和与精神世界的美好。
  #+END_QUOTE

- 2534-2535, 标注, 2025 年 9 月 28 日星期日 上午 7:59:37
  #+BEGIN_QUOTE md5: d3c916283d957f22c7c5850f096f7442
  或许刘喜男自己都未想到，他在工厂里做钳工的八年来，竟练就了过人的指力、腕力和臂力。在人工岩壁上，
  他的手指能抠在几毫米薄的岩点上，还能用单只手臂做引体向上，在众多初学者中脱颖而出。
  #+END_QUOTE

- 2671-2675, 标注, 2025 年 9 月 28 日星期日 上午 8:23:16
  #+BEGIN_QUOTE md5: d4306b9bbb63f07a6cc7d8d0000a39a1
  从地球上空拍摄的卫星图看，到了夜里，中国东部沿海地区灯光璀璨，而在这块版图的中间地带，
  唯有成都与重庆两座都市孤独地闪耀着。成都以西，乃至整个青藏高原都是一片广阔无垠的黑暗。那是一种没有任何灯光、
  如宇宙黑洞般死寂的黑暗。这片广袤的黑暗代表着中国经济发展较为落后的地区在青藏高原与四川盆地交界处、
  横亘在第一台阶与第二台阶之间的大雪山，不仅隔绝了中原汉地与西部地区的文化交融，也扼住了川西地区的经济命脉。
  #+END_QUOTE

- 2677-2678, 标注, 2025 年 9 月 28 日星期日 上午 8:23:34
  #+BEGIN_QUOTE md5: 3bb9a8936d0f3196c3d0ad2fef0cc31b
  这黑暗也标志着地球上一片原始而纯粹的净土。对于登山者与探险家来说，
  这黑暗还喻示着无尽的攀登资源与中国最后的秘境。
  #+END_QUOTE

- 2712-2716, 标注, 2025 年 9 月 28 日星期日 上午 8:31:47
  #+BEGIN_QUOTE md5: 407bc49028dd3fe31a2c591d4ef66eb5
  三个月时间说长不长，却在他的心里留下了深深的印记。他曾带着大展拳脚的抱负来到黑水，却失望地离开这里。
  他回溯了过去几年所经历的种种不快之事:在人民大会堂请假时的唯唯诺诺，在风雨雪公司打工时的束手束脚，
  友谊峰的首登权被卖掉，雀儿山下的一地鸡毛，被登协打压，被奥索卡搪塞。此刻，马一桦只有一个念头，
  “把人生操控在自己手里”。马一桦决定成立一家只属于自己的登山探险公司，专门攀登那些带冰川的山峰。
  #+END_QUOTE
