:PROPERTIES:
:ID:       96e1baa7-605d-4419-92ac-11976beb6063
:END:
#+TITLE: 比山更高：自由攀登者的悲情与荣耀-宋明蔚
#+AUTHOR: Yang,Ying-chao
#+DATE:   2025-09-26
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:  oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :bishangengga:clip:


- 22-23, 标注, 2025 年 9 月 26 日星期五 上午 7:47:31
  #+BEGIN_QUOTE md5: 94bfb79540539f69d73b70add75fe7c7
  我们常常把人生比作翻越高山，就好像攀登比人生更容易理解。事实上，大多数人对人生一知半解，对登一无所知。
  #+END_QUOTE


- 35-38, 标注, 2025 年 9 月 26 日星期五 上午 7:49:34
  #+BEGIN_QUOTE md5: a73fb9c1e1217654067d4f76bf066cb6
  这两类民间登山者的叙事也代表着过去二十年来中国社会的两极价值取向。
  攀登世界最高峰的一类人象征着当今社会的整体基调:极度渴望成功，高度以功利为导向，
  关注宏大的叙事与不断攀升的数字。而这本书里的自由攀登者们则代表着另一类极少数群体。
  他们并不想完成一座比一座高的山峰，只是想在其中一座山峰上画下一笔优美的线条，并在攀登过程中获得足够多的快乐。
  #+END_QUOTE


- 107-108, 标注, 2025 年 9 月 26 日星期五 上午 7:57:03
  #+BEGIN_QUOTE md5: d7c08745226d1ba6002f46c248653a1a
  他们只是想自由地攀登，自由地安排自己的时间，想爬哪座山就爬哪座山。对于中国民间登山者而言，“自由地攀登”
  是个高远而缥缈的目标。
  #+END_QUOTE


- 233-235, 标注, 2025 年 9 月 26 日星期五 上午 8:26:51
  #+BEGIN_QUOTE md5: 916936b6adac496e73c4dc50f045ec34
  严冬冬并非完全笃定要走登山这条路，他也感到过迷茫。一方面，他越来越痴迷于登山这件事。他多次说过，
  在过去二十年里，登山所带来的存在感是他从未感受过的。进入实验班、名列前茅无法让他感到生命的热烈。高考状元、
  清华学子的身份也无法让他感受到存在的价值。唯有登山能让他感受到自己活着。
  #+END_QUOTE


- 254-256, 标注, 2025 年 9 月 26 日星期五 上午 8:28:44
  #+BEGIN_QUOTE md5: 9c077e11af9b2d07065b2807e642e250
  在中国，对于大多数心怀理想的青年来说，自由都不是一件简单的事情。在实践自由意志的同时，
  他们还必须要摆脱外力的束缚:不用为了生计，或是基本的生存而忧愁烦恼;不被传统的家庭观念绑架;
  不被困在日常生活的琐事之中。
  #+END_QUOTE


- 292-295, 标注, 2025 年 9 月 26 日星期五 上午 8:35:28
  #+BEGIN_QUOTE md5: 0236e62bb194fcf1f39283fa8dcd6e9a,659288f1532f0cdaba7a69f591deede9
  在冲顶那一天，他望到前方雀儿山的顶峰拨云而出，万分激动。这种激动一直持续到他站在顶峰的那一刻。
  这是他第五次攀登，却是他第一次登顶。严冬冬曾经以为，只要真心热爱攀登这件事，登不登顶其实并不是那么重要。
  但当他站在雾蒙蒙的山顶的这一刻，一切都改变了。
  #+END_QUOTE


- 523-525, 标注, 2025 年 9 月 26 日星期五 下午 3:52:05
  #+BEGIN_QUOTE md5: 5d8c19e5c8f1d23def495071216d37e8
  严冬冬写道:集训只有单调的体能训练，几乎完全没有攀爬与技术训练;训练方法陈旧而不够科学，
  集训队里弥漫着功利性的竞争气氛，攀登中的关键决定完全要看领导的脸色……我觉得窒息，我想要的是真正的、自由的攀登，
  不是这些东西。
  #+END_QUOTE


- 525-529, 标注, 2025 年 9 月 26 日星期五 下午 3:53:04
  #+BEGIN_QUOTE md5: 8818c2c22c84cf1f5cedead0c01f88a2,48b93858bd1d8888defebe5405e4aac5
  《极限登山》所倡导的阿式攀登理念是自由，是灵活应变是每个人只对自己负责，
  这几乎与珠峰上的喜马拉雅式攀登风格背道而驰。
  在珠峰火炬传递的活动中，每名队员都要严格听从攀登队长、总队长、总指挥的命令。这无比接近于军事化的战斗。
  与阿式攀登相比，喜马拉雅式攀登体现的是另一重组织艺术:行军布阵的艺术，把握好天气窗口的艺术，
  人与人之间沟通的艺术，把一个个螺丝钉与螺母调试完备从而组装出一套强大系统的艺术。
  这跟登山有关，但又与登山的本质无关。
  #+END_QUOTE


- 534-538, 标注, 2025 年 9 月 26 日星期五 下午 3:54:07
  #+BEGIN_QUOTE md5: 1e700923e51f3100ecd104e0afcae784
  什么是自由?什么是登山的自由?严冬冬后来在《登山的自由》一文中写道: 有谁不渴望自由呢?登山的人尤其如此:
  远离尘器的羁绊，在广阔雄浑的山间让生命力恣意飞扬，这样的向往，
  应该说是驱使我们中许多人开始投身登山的动力源泉之一吧。自由是登山者能够追求的终极目标。自由就是随心所欲。
  在登山这方面，理想程度的自由，应该是随便任何一座山、任何一条路线，在任何时间以任何方式都可以攀爬……”
  #+END_QUOTE


- 538-539, 标注, 2025 年 9 月 26 日星期五 下午 3:54:20
  #+BEGIN_QUOTE md5: a601c6d03bceaff7eb479926846efb05
  在自由之魂刚刚成立的那一刻，任他们的心灵恣意飞扬，
  他们的身体却被桎梏在那顶不足两平方米的小帐篷里渴望着被赐予冲顶珠峰的机会。
  #+END_QUOTE


- 525-525, 笔记, 2025 年 9 月 26 日星期五 下午 3:55:53
  #+BEGIN_QUOTE md5: 385f623dc92d99b0e40a3475a9104c01
  哪里都是江湖,有人的地方,就有江湖。
  #+END_QUOTE


- 616-619, 标注, 2025 年 9 月 26 日星期五 下午 6:24:29
  #+BEGIN_QUOTE md5: a41137ef42e2f90d060e78242622dedf
  多年以后当严冬冬回顾这两次独攀时，认为没登顶是再正常不过的事情。他当时的登山技术与理念都不算成熟。
  但是他很享受独自在山里的时光。他喜欢那种孤独感。孤独会放大登山的生命体验，而这种深刻的体验，
  让严冬冬深深地为之着迷。
  #+END_QUOTE


- 758-760, 标注, 2025 年 9 月 26 日星期五 下午 7:00:13
  #+BEGIN_QUOTE md5: 3bebfa75ab6d5602e8e5119660d2d0ac,eb57ce92a5e6dcb9ddb231fbe2bbecba,4d6ee7cca6d5563a7b544f837bcd5385
  景区里的游客越来越多。徐老幺买了辆自行车，骑到镇上批发银手镯、项链等工艺品，拿到景区里售卖。一枚银手镯进货价 5
  元，他卖 100;一串项链进货价 10 元，他卖 200。“你要卖得越高，他就要的人越多。卖得便宜就不要。”徐老幺说。
  #+END_QUOTE


- 1031-1034, 标注, 2025 年 9 月 26 日星期五 下午 10:08:06
  #+BEGIN_QUOTE md5: 3498a118d508c090e8a2795f0409f891
  攀登运动是一项本质上具有危险性的活动，可能导致严重受伤或死亡，参与攀登的人，必须清楚认识到这一点。
  严冬冬并不惧怕死亡。他承认登山运动会带来死亡的可能性，但并不会就此被动地接受，而是尽其所能去阻止事故的发生。
  #+END_QUOTE


- 1103-1105, 标注, 2025 年 9 月 26 日星期五 下午 10:19:50
  #+BEGIN_QUOTE md5: 8c4dba110bcd99a922c9a136b2d13856
  在《巅峰记忆》的登顶气氛中，李兰在影片中念了一段精彩的独白:“我们走进了山的内心，触摸了顶峰之上的天空，
  这空不是虚无，而是无边无际的自由，是所有攀登过的人们，都会向往的、可能付出生命代价的—自由。”
  #+END_QUOTE


- 1171-1176, 标注, 2025 年 9 月 26 日星期五 下午 10:55:17
  #+BEGIN_QUOTE md5: 1b899cc26c0f989f39639c8f19ecf107
  先后经历了冻伤、暴雪、冰雹、雷暴、狂风之后，老布等人终于站在了海拔 6422 米的雪莲西峰(白玉峰)上。登顶后，
  他们一路下撤，连夜出山，70 个小时后，火速赶回了乌鲁木齐。“就算我们刚刚抢了一家银行，也不太可能撤得比这还快了。”
  老布在攀登报告中写道。他们其实还能更快，如果他们没有把大本营附近堆积成山的垃圾运走的话—
  那些都是号称热爱户外的徒步者们丢弃在那里的。老布等人把这次史诗级的攀登路线命名为“TheGreat White Jade Heist”。
  字面意思是“白玉峰大劫案”。严冬冬在翻译这篇攀登报告时，把它翻译成一个更朴素的名字“白玉之路”。
  #+END_QUOTE


- 1291-1294, 标注, 2025 年 9 月 26 日星期五 下午 11:06:21
  #+BEGIN_QUOTE md5: 81fd32bc0734cf242f09fbb0d11830bd
  严冬冬后来回忆这划时代的一刻:“周遭的景色令人目不暇接。俯瞰四周的群山，突然间，它们显得那么低矮，那么遥远，
  犹如远方的海浪。我们才发现，我们一直都无暇顾及它们的存在。自从早上离开营地后，我们就完全沉浸在攀登的过程中。
  这是我们首次开辟的新路线，就以我们登山组合的名字，命名它为‘自由之魂’(The Free Spirits).”
  #+END_QUOTE


- 1356-1357, 标注, 2025 年 9 月 27 日星期六 上午 7:25:23
  #+BEGIN_QUOTE md5: f2574ffa2d6370482469109babc7f6ff
  自由攀登者的精神世界更接近道家哲学。当你刻意追求它时，它离你越来越远。当你淡然处之时，意想不到的奖赏终究会来。
  #+END_QUOTE


- 1436-1439, 标注, 2025 年 9 月 27 日星期六 下午 2:12:39
  #+BEGIN_QUOTE md5: a51cbf56c376166be3f2da688b489cc3
  陈家慧也清醒地面对这个复杂的世界。有一次，陈家慧参加了大学的校友会，回来后对孟春表达出她的真实想
  法:“许多人在那里假装帮助学生，但是他们真实目的是编织他们的关系网，最终还是为了他们的个人利益。
  他们努力控制别人去提高自己的地位。我永远不想那样。”“在优胜美地没人会在乎我的社会地位。
  在那儿每个人只是一个攀登者。”
  #+END_QUOTE


- 1513-1516, 标注, 2025 年 9 月 27 日星期六 下午 2:25:09
  #+BEGIN_QUOTE md5: 967049d35c5b225e96d65462ef991725
  这名自由登山者胆子并不算大。他在下坡时会害怕，在悬崖高处会恐惧，半夜还会从噩梦中惊醒，
  但他从不惧怕死亡他甚至还会和搭档反复探讨死亡的可能性，死亡发生的场景，“我承认它，承认我可能会死掉,”严冬冬说，
  “但是这个可能性接受了，并不代表我不去以任何我可能做到的事情来阻止它发生。”他无法预测不可知的未来，
  更不想犹疑不定地止步当下。他唯一能做的就是在那个结局到来之前，尽可能多地攀登,
  #+END_QUOTE


- 1827-1828, 标注, 2025 年 9 月 27 日星期六 下午 7:06:34
  #+BEGIN_QUOTE md5: c8f47a120794de74f0ba6d0d8098b1b3
  自由，人类所追逐、向往的自由，本是看不见、摸不着的抽象观念。只有碰撞到坚硬的现实，
  自由才会更凸显出其意义和价值。
  #+END_QUOTE


- 2059-2061, 标注, 2025 年 9 月 27 日星期六 下午 7:29:03
  #+BEGIN_QUOTE md5: 57ee7c51dbef805ae8b40a6dd0626538
  从新疆回到北京后，周鹏又回到了北京密云的房子里。如今五居室的房间里只剩他自己，更显得冷清空旷。那一晚，
  他做了个梦。梦中，他又回到了西天山的冰川。严冬冬浑身冰冷，想要和他说些什么。李爽后来跟周鹏说，
  她做了一模一样的梦。
  #+END_QUOTE


- 2137-2139, 标注, 2025 年 9 月 27 日星期六 下午 7:35:36
  #+BEGIN_QUOTE md5: f8bf282aca70bd0f07561605e004bba2
  不知怎的，后来赵哥还是没忍住。他和对方几句不和，一拳抡到对方脑袋上，手立马就肿了，在战斗中还落个下风。
  好在周鹏及时赶到，众人这才联合起来一番“说服教育”。对方被教育得够呛，在派出所报了案。周鹏和赵兴政最后交了 5000
  元的罚款。他们觉得值。
  #+END_QUOTE


- 2141-2143, 标注, 2025 年 9 月 27 日星期六 下午 7:36:08
  #+BEGIN_QUOTE md5: db974f642abe76d7c329a2f8f652e5a9
  再后来，公司黄了。他盘下北京二环边上的一家咖啡馆，再把它改成小酒馆。他蓄起胡子，研究起哲学与超验心理学，
  每天慵懒地睡到中午，再迷醉到深夜。只有当《白鸽》的音乐响起时，他才会短暂地回到过去。
  那是他前半生里最骄傲的一段时光，
  #+END_QUOTE


- 2161-2164, 标注, 2025 年 9 月 27 日星期六 下午 7:38:29
  #+BEGIN_QUOTE md5: 6322f690ce0d4894346478011ec0318a
  十年就这么过去了。“自由之魂”的名字沉寂下来，逐渐被新一代的登山英雄和攀登传奇取代。
  它似乎成为周鹏心中一个遥远而陌生的词。只有当某个学生来到他的白河小院，不经意间问他这里的 wifi 密码时，
  周鹏才会微笑着重提起那个熟悉的名字:the free spirits。
  #+END_QUOTE


- 2470-2473, 标注, 2025 年 9 月 27 日星期六 下午 10:46:04
  #+BEGIN_QUOTE md5: 7e90bbb598b739e5c5c5e2b43a9ac5a8,895239120165627a85b7effb1994a250
  他给杂志写写稿，拍拍照片，没有任何存款，随时说走就走，过上了四处流浪的生活。徐晓东还给他送了个外号，叫“王大垮”，
  以取笑他这种混日子的状态。王滨却对这种生活方式颇为骄傲。他认为自己就像是个嬉皮士，不追求物质生活的享乐，
  排斥主流的传统价值观，只追求内心世界的平和与精神世界的美好。
  #+END_QUOTE


- 2534-2535, 标注, 2025 年 9 月 28 日星期日 上午 7:59:37
  #+BEGIN_QUOTE md5: d3c916283d957f22c7c5850f096f7442
  或许刘喜男自己都未想到，他在工厂里做钳工的八年来，竟练就了过人的指力、腕力和臂力。在人工岩壁上，
  他的手指能抠在几毫米薄的岩点上，还能用单只手臂做引体向上，在众多初学者中脱颖而出。
  #+END_QUOTE


- 2671-2675, 标注, 2025 年 9 月 28 日星期日 上午 8:23:16
  #+BEGIN_QUOTE md5: d4306b9bbb63f07a6cc7d8d0000a39a1,3bb9a8936d0f3196c3d0ad2fef0cc31b
  从地球上空拍摄的卫星图看，到了夜里，中国东部沿海地区灯光璀璨，而在这块版图的中间地带，
  唯有成都与重庆两座都市孤独地闪耀着。成都以西，乃至整个青藏高原都是一片广阔无垠的黑暗。那是一种没有任何灯光、
  如宇宙黑洞般死寂的黑暗。这片广袤的黑暗代表着中国经济发展较为落后的地区在青藏高原与四川盆地交界处、
  横亘在第一台阶与第二台阶之间的大雪山，不仅隔绝了中原汉地与西部地区的文化交融，也扼住了川西地区的经济命脉。

  这黑暗也标志着地球上一片原始而纯粹的净土。
  对于登山者与探险家来说，这黑暗还喻示着无尽的攀登资源与中国最后的秘境。
  #+END_QUOTE


- 2712-2716, 标注, 2025 年 9 月 28 日星期日 上午 8:31:47
  #+BEGIN_QUOTE md5: 407bc49028dd3fe31a2c591d4ef66eb5
  三个月时间说长不长，却在他的心里留下了深深的印记。他曾带着大展拳脚的抱负来到黑水，却失望地离开这里。
  他回溯了过去几年所经历的种种不快之事:在人民大会堂请假时的唯唯诺诺，在风雨雪公司打工时的束手束脚，
  友谊峰的首登权被卖掉，雀儿山下的一地鸡毛，被登协打压，被奥索卡搪塞。此刻，马一桦只有一个念头，
  “把人生操控在自己手里”。马一桦决定成立一家只属于自己的登山探险公司，专门攀登那些带冰川的山峰。
  #+END_QUOTE


- 3330-3334, 标注, 2025 年 9 月 28 日星期日 下午 6:22:12
  #+BEGIN_QUOTE md5: 1a60b17271fdb00ac205310ed1dfe257
  等他们准备下撤的时候，大山却用一种奇异而迷幻的方式，迎接着初次与它会面的人类。太阳的光芒刺出云隙，
  就好像舞台上方突然射下的一道光束，照耀在这两名攀登者身上，再把他们的影子投射到脚下的云海幕布上。
  那云层上的人影正被一圈七色彩虹环绕着，形成了罕见的自然现象—佛光。刘喜男联想起前后两次攀登婆缪峰的过程，
  心中充满了敬畏，更笃定这-刻所预示的神圣的意义:“并不是我们登顶了神山，而是神山选择了我们。”
  #+END_QUOTE


- 3658-3660, 标注, 2025 年 9 月 28 日星期日 下午 6:49:11
  #+BEGIN_QUOTE md5: 368b60915a70151ddaa51349b0eec7ab
  为了防止老鹰或乌鸦啄破刘喜男的遗体，马一桦、张俭二人在雪地里挖了一米深的雪坑，把遗体埋了进去。
  他们在雪坑的四个角落里做好标记。“我自己是登山的人，如果是我自己的话，我会认为这是最好的归属。”马一桦写道。
  每一名登山者都希望死在山上。每一名登山者又都不希望死在山上。
  #+END_QUOTE


- 3726-3727, 标注, 2025 年 9 月 28 日星期日 下午 9:51:33
  #+BEGIN_QUOTE md5: 9b1687cc3a82beb9f80731f424a45d3b
  刘喜男死于自己的低级错误，死在了寻找自我的途中，也死在了一名理想主义者回归现实的那一刻。
  #+END_QUOTE


- 4082-4083, 标注, 2025 年 9 月 28 日星期日 下午 10:59:57
  #+BEGIN_QUOTE md5: 4aeed51472f5ceaa01e130d0c50f9b41
  他说，他喜欢爬到高处，看着大地与广袤的山脉一览无余地绵延开去，此时他会觉得之前的所有努力与付出都是值得的。
  #+END_QUOTE


- 4239-4242, 标注, 2025 年 9 月 29 日星期一 上午 8:10:51
  #+BEGIN_QUOTE md5: 9f5eafda21ae26452bc2d6166051ab32
  王茁向来是一名以严谨著称的攀登者，而最严谨的攀登者却死于一次大意。事故报告的撰写者分析王茁当时的心理过
  程:“以王茁的谨慎和经验，应该估计到有雪崩危险存在，当时只有硬着头皮上和下撤放弃两种选择。
  如下考虑是很自然就能够发生的:走了很久再有几十米就到 C2 了，来一次不容易，卢忠荣不久前还走过这条路线也说没问题，
  看起来不是那么危险，快速通过……最终还是上了。他们运气不好，雪崩了。”
  #+END_QUOTE


- 4275-4276, 标注, 2025 年 9 月 29 日星期一 上午 8:15:58
  #+BEGIN_QUOTE md5: 47f1bec09eaa1ab73d3ec7e578b30dfe
  王茁的母亲行动不便，从前王茁每次回家，都会力所能及地做些家务。不必说，自王茁出事后，他的母亲平时深居简出，
  每周出门买一次菜，窝在家里能吃个七天，心里想来想去都是儿子。
  #+END_QUOTE


- 4659-4660, 标注, 2025 年 9 月 29 日星期一 下午 1:08:49
  #+BEGIN_QUOTE md5: ec4293cda1a2df7b49ed63a11e82f87c
  “记忆中崭新的装备，现在已经变得过时而且锈迹斑斑，但那种熟悉的感觉却实实在在地透过手心传来。
  太多年轻的面孔和故事随着记忆汹涌而至，恍若隔世。”
  #+END_QUOTE


- 4710-4715, 标注, 2025 年 9 月 29 日星期一 下午 1:13:23
  #+BEGIN_QUOTE md5: 169d1a1f71fefd16daba12e775cd46c3
  等伍鹏从海拔 5413 米的顶峰下来时，天已经黑了。他们没有时间沿着来路下降，而是放下绳子，垂降下岩壁。
  他们整个身子吊在悬崖上，两只手不断地喂绳。大雪横飞，吹在身上粘在脸上，钻进脖子里。三个人在疲惫中陆续下降。
  四周一片漆黑。寒冷、饥渴、困乏、力竭、恐惧纷纷袭来，还有死亡。死亡就藏在黑夜中，藏在脚下的悬崖边，
  藏在任何一次简单的失误中。在岩壁上垂降，攀登者只要一次操作失误，就容易引发致命危险。三个人都太累了，
  总是忍不住合上双眼。为了让自己清醒一点，赵四掏出绳刀，在手指上划开一个口子。鲜血滴在白色的雪地上，
  又迅速被大雪掩盖掉。
  #+END_QUOTE


- 4826-4828, 标注, 2025 年 9 月 29 日星期一 下午 1:21:08
  #+BEGIN_QUOTE md5: d7b3ee1c390fe916bad2e561b7b3e05e
  我以为我会痛哭，但我没有。2007 年的经历告诉我，山不相信眼泪。现在我只想安全地把赵四和箩筐送到日隆。
  我出乎意料地冷静，可，我的心里却是那么刺痛，这种刺痛已经被我锁在心底某处角落很长时间了。
  甚至我曾经以为不会再刺痛了”
  #+END_QUOTE


- 4835-4837, 标注, 2025 年 9 月 29 日星期一 下午 1:22:03
  #+BEGIN_QUOTE md5: 92fd542a969be74d115816f4699cd517
  魏宇赶到了机场，等待大家过来一起会合。在机场里，她看到一个和川歌差不多大小的小孩。
  小孩与爸爸的亲昵场面让魏宇触景生情。她心想，川歌也两岁，为什么我和伍鹏真诚待人，从没有做过什么伤天害理的事，
  怎么我们的川歌就遇上这种事?
  #+END_QUOTE


- 4865-4867, 标注, 2025 年 9 月 29 日星期一 下午 1:24:49
  #+BEGIN_QUOTE md5: 2570d260c3036996676c94d58740dffb
  魏宇想起来当年她刚认识伍鹏的时候，在那顿饭局上，伍鹏说，他要是得了癌症晚期，他就去爬 K2，留在山上。是啊，
  每一名登山者都不希望死在山上，可每一名登山者又都希望死在山上。
  #+END_QUOTE


- 4881-4885, 标注, 2025 年 9 月 29 日星期一 下午 1:26:32
  #+BEGIN_QUOTE md5: 451fe5a9f9e8da31f16d0a69cf352b57
  那一阵，魏宇总感觉伍鹏还在身边似的，似乎只要等伍鹏晚上下班回家后，一家人就能团团圆圆。这种错觉越来越强烈。
  出事半个月后，她写道:“很多个像这样的傍晚，我们在操场上玩，伍鹏下班后从远处笑盈盈地走来找我们，
  而后一起回家喝一杯我们爱的英式精酿。今天那一刻有一种强烈的错觉，他仿如还会走来然后抱住小乖说，乖乖今天乖不乖?”
  每当这个时候，魏宇就“握握川歌的手，或是狠狠地抱抱她”。
  #+END_QUOTE


- 4894-4897, 标注, 2025 年 9 月 29 日星期一 下午 1:29:27
  #+BEGIN_QUOTE md5: 10a3cd25ad1a952cac843a772f24bf84
  在过往的事故案例中，相当一部分遇难者家属会把愤怒悲伤的情绪宣泄到幸存者身上。魏宇却表现出罕见的共情与同理心，
  从没有责怪赵四、箩筐和王大。她对三名幸存者提出的唯一要求是:希望他们能以各自的视角，
  写一份详细而清晰的事故报告，一五一十地讲述攀登过程中发生的每一处细节，以警示后来的攀登者，不要再犯类似的错误。
  #+END_QUOTE


- 4901-4902, 标注, 2025 年 9 月 29 日星期一 下午 1:29:49
  #+BEGIN_QUOTE md5: 409347685a73e09763d9f4357f59ceaf
  在伍鹏无私而高尚的光环之外，事故报告呈现出了一个更真实、赤裸的伍鹏。伍鹏等人所犯的错误，
  以及在极端环境中所表现的狂热、无助与惊惶，全部在事故报告中暴露出来。
  #+END_QUOTE


- 4906-4909, 标注, 2025 年 9 月 29 日星期一 下午 1:31:05
  #+BEGIN_QUOTE md5: 00b6baba11e5a3d049855024d9bea41f,c5f1815223166941bfecb94710d935d4,9cc2e239654218984fe03c7afef30f2c
  王二对这次事故做了深刻的总结，就像 2007 年那样。他将伍鹏遇难的原因归结为海拔适应不足、脱水、缺乏能量供给失温，
  以及 Bivy(露宿)点没有建立保护站。每一个错误都是错上加错，最终导致不可挽救的悲剧。
  伍鹏死于一次致命的坠落也死于坠落前的体能耗竭与严重失温。在伍鹏不顾一切冲向顶峰的那一刻，悲剧似乎已然注定。
  #+END_QUOTE


- 4913-4914, 标注, 2025 年 9 月 29 日星期一 下午 1:31:33
  #+BEGIN_QUOTE md5: cdea9e9d07de289baa19bad3b2893906
  每个攀登者的登顶狂热都因性格不同而表现方式不同,”王二在文中总结道，“但共同点是越接近顶峰，越是执着盲目，
  越是把顶看作是人生唯一的意义，忽略所有风险，忘却了所有的责任。”
  #+END_QUOTE


- 4951-4954, 标注, 2025 年 9 月 29 日星期一 下午 1:35:57
  #+BEGIN_QUOTE md5: 5d89c3dca068b7b6af305ed8a0604911
  新政策出台后，白河黑龙潭景区找到当地爬刺子的居民，以每天 700 元的价格，雇佣他们拆掉岩场里所有挂片和膨胀钉。
  他们每天在岩壁上作业六个小时，每天拆下来的挂片和铁环足有四五十斤重。一周后，
  他们毁掉了二十年来白河攀岩者开辟的数十条线路。白河攀岩来到了前所未有的危急时刻。
  #+END_QUOTE


- 4960-4961, 标注, 2025 年 9 月 29 日星期一 下午 1:36:18
  #+BEGIN_QUOTE md5: 11a92c6d47742d7c8c4bd4c42a61b180
  “不留痕迹”(LNT)是户外精神的内核之一，不乱扔垃圾只是最基本的素质。
  #+END_QUOTE


- 4977-4980, 标注, 2025 年 9 月 29 日星期一 下午 1:39:05
  #+BEGIN_QUOTE md5: 4e2b62bca280be25486eb3a4406fe722
  “这些年失去了太多重要的伙伴，有时候夜深人静，会突然觉得那些离去的人，好像都还在自己身边，
  每一个人的音容笑貌还是那么真实，甚至每一个细节都栩栩如生，生死相隔的界限十分模糊,”王大写道，
  “可再仔细回想之时，无比强烈的孤独就会随之而来，生活中缺少了那些人，使这个世界变得越来越寂寞。”
  #+END_QUOTE


- 5003-5005, 标注, 2025 年 9 月 29 日星期一 下午 6:16:56
  #+BEGIN_QUOTE md5: 50dc057acccd467db6ae7ee551a3f570
  每天，按照值班表上的固定时间，他穿着静电服坐在工位上，把流水线上的芯片装进机器，反复检查，再传到下一条流水线。
  他的工资是固定的，他的生活是固定的，他的人生似乎也是固定的，就像是家乡、学校与工厂边上的岷江河流，
  日复一日而又一成不变。
  #+END_QUOTE


- 5006-5010, 标注, 2025 年 9 月 29 日星期一 下午 6:17:36
  #+BEGIN_QUOTE md5: 1c1078f84a82bae3066045bb99757253
  他在书中窥见到了更辽阔的世界。他徜徉在《在路上》与《达摩流浪者》中的世界，跟着“垮掉的一代”
  经历了一段段公路旅行的时光。他在切·格瓦拉的传记中，游历了魔幻的拉美与壮美的安第斯山脉。
  他在瓦尔登湖边思考人生，在阿拉斯加的荒野中追寻生命的意义。这些流浪者的浪漫主义气质透过书本，
  传递到了小镇青年的精神世界中，不断积累、沉淀、发酵。直到有一天，“就觉得不行了，必须要付诸行动”。
  #+END_QUOTE


- 5259-5260, 标注, 2025 年 9 月 29 日星期一 下午 6:42:16
  #+BEGIN_QUOTE md5: 580cf556f4a5a1bc190750c6cdc2105e
  当被朋友问到独攀的感受时，小柳说，当他专注在攀登过程中的时候，忘记了暴露感与恐惧感，
  反而是攀登中带来的自由感让他更为向往。
  #+END_QUOTE


- 5333-5337, 标注, 2025 年 9 月 29 日星期一 下午 6:48:31
  #+BEGIN_QUOTE md5: b84248aae33064f079b87ebb9602b7a1
  山说，“我们怀疑他们用了一个别人留下来的老绳套。我们怀疑，它老化了，然后他们下降的过程中断了。”
  小柳在以往的攀登中曾养成了一个习惯，喜好利用前人留在山上的绳套，就像在阿妣峰下撒时那样。
  或许每次小柳利用旧绳套全身而退时，他都产生了一种虚假的安全感。曾山说，紫外线把整个绳套晒得特别脆，
  脆到无法承受一个人的体重，突然就断了。在那一瞬间，小柳和坑子可能也随着这脆弱的绳子一起坠落了。
  #+END_QUOTE


- 5340-5343, 标注, 2025 年 9 月 29 日星期一 下午 6:49:10
  #+BEGIN_QUOTE md5: a62ab919a1dd2974d0a86e3cb0fa53e3
  在那一刻，小柳终于证明了自己。 小柳曾计划过，假如他们登顶了幺妹峰，就将这条新路线命名为“勒满”。
  在四姑娘山当地的方言中，勒满是快乐的意思。也许在最后那一刻，他们真的很快乐。正如小柳的那句座右铭:
  如果什么意外发生让我丢了性命，那不是个悲剧，因为我在做我热爱的事，睡觉前想到，明天还会做自己爱的事，
  那是一种恩赐。
  #+END_QUOTE


- 5350-5353, 标注, 2025 年 9 月 29 日星期一 下午 6:50:31
  #+BEGIN_QUOTE md5: 7c866c311f5527a91752ce4736a5761f,baac277ff1805a8d5dad22d6df681ea4
  这是自由攀登者永远无法与自己和解的原罪:他们选择远离这个安逸的美丽世界，走上一条遍布悬崖与荆棘的道路。
  路上的死亡悬崖属于自己，而路边的荆棘刺伤了离他们最近的人。在他们看似坚定地寻找自由和自我的路途中，
  也会有这般彷徨怯懦、犹疑的时刻。大多数成熟的自由攀登者不会回避、视这原罪的存在，而是清醒、
  痛苦地背负着它一起攀登。
  #+END_QUOTE


- 5520-5523, 标注, 2025 年 9 月 29 日星期一 下午 10:10:41
  #+BEGIN_QUOTE md5: 8c5c1a10cac4524ef3a891cf64baa926
  不知从何时起，他们脚下的山谷中升腾出一片烟波浩渺的云海。那是一片平静无瑕的海，
  就连孤高的邛崃山主峰也藏在了深不可测的海面之下。在海的尽头，海天之间交汇出一道橙色的天际线。
  在他们化雪烧水的时候，久别重逢的太阳就像一颗破壳而出的蛋黄，慢吞吞地从海面升起。等这只蛋黄彻底滑出了蛋壳，
  并与水平的天际线形成了一个“旦”字的时候，万丈光芒在一刹那便照耀着世间万物与登山者的脸庞。
  #+END_QUOTE


- 5873-5875, 标注, 2025 年 9 月 30 日星期二 上午 8:03:50
  #+BEGIN_QUOTE md5: 36c1a0ce6eb52b3f964b3f9770c17072
  曾山认为，马科斯是一名非常强悍的攀登者，事实上，在这对搭档关系中，马科斯过于强悍了。
  也许刘兴一直在拼命跟上马科斯的节奏—或是要证明自己能跟得上。最终，他被这种“证明自己”的心态吞噬了。
  #+END_QUOTE


- 5880-5883, 标注, 2025 年 9 月 30 日星期二 上午 8:04:24
  #+BEGIN_QUOTE md5: 3e3a6e07560829046b1406d8dd309746
  从刘兴和马科斯决定搭档的那一刻起，二人都默认了一个前提。这个前提也是所有自由攀登者们的共识。严冬冬曾在
  《免责宜言》中将此清晰地表述出来:他们理解登山本质上是一项危险的运动，他们清楚在极限环境中搭档
  “无法保证总能做出恰当的反应和举动”，他们认为搭档不应为此承担任何责任。曾山说，如果决定去这样的山峰攀登，
  那么就不能有“我要依靠你，你要带我”的想法，攀登者之间完全是平等的，百分百为他们自己负责。
  #+END_QUOTE


- 5884-5884, 标注, 2025 年 9 月 30 日星期二 上午 8:04:58
  #+BEGIN_QUOTE md5: 47b2f7d9e2db84eff331b983f40225d4
  虽然登山者要为自己的选择负责，但选择的恶果却再次由登山者的家属承担。
  #+END_QUOTE


- 5888-5890, 标注, 2025 年 9 月 30 日星期二 上午 8:05:20
  #+BEGIN_QUOTE md5: c13a0ff8102c106c00d4a24f9ae52400
  “如果你放弃很喜欢的事情，我觉得这一个人身体里的某个部分就死掉了。你变成了不完整的一个人。
  我相信登山也是一样的,”曾山说，“如果一个人喜欢去登山，就让他去登山。如果父母不让他去登山，
  我觉得不让子女追逐他们热爱的事情，是非常自私的行为。”
  #+END_QUOTE


- 5891-5894, 标注, 2025 年 9 月 30 日星期二 上午 8:05:45
  #+BEGIN_QUOTE md5: 0c5baf75150a7f6ea8bfeab026f65868
  曾山热爱中国的山峰、汉语、川菜与教育方式，他唯独不认同父母以自私为名干涉子女的热爱。
  曾山的母亲贝西也像中国的父母一般担惊受怕，从来没有支持过曾山的攀登生涯，
  但她亦没有阻止过甚至都没有把这种焦虑表达出来。“她知道不应该阻止我做这件事情，因为正是热爱才让人变得更加完整,”
  曾山说，“如果我阻止了我的女儿去做她热爱的事情，我觉得这才是真正的自私。”
  #+END_QUOTE


- 5905-5906, 标注, 2025 年 9 月 30 日星期二 上午 8:06:58
  #+BEGIN_QUOTE md5: cca26b7389ede336594caf411ad26d9b
  “过去的几年间，每当有朋友志存高山，却一去无返，我心里的痛苦便淤积更盛。
  努力追逐极限的自由探险与朋友消逝山巅的短暂生命，让我在矛盾的痛苦中无法解脱。”
  #+END_QUOTE


- 5953-5955, 标注, 2025 年 9 月 30 日星期二 上午 8:11:01
  #+BEGIN_QUOTE md5: 8b67ba1b48da9556f6aafe48c7933efb
  “第一次来的时候，真的看那些山，那些冰川，那些很恐怖，你没有信心，
  但是不知道为什么那种恐惧感反过来变成我的动力。”Stanley 说。
  #+END_QUOTE


- 5981-5984, 标注, 2025 年 9 月 30 日星期二 上午 8:14:12
  #+BEGIN_QUOTE md5: 183f16ddbc439cee32185a11b6d2f999
  “父亲、母亲与高山、汪洋同样是我生命里不可或缺的元素，前者赋予我生命，后者给予我存在的意义,”Stanley 后来解释道，
  “倘若要我跟随她(算命师)写下的剧本，不再去挑战这崇山峻岭，不再去置身于那浪涛之中，要我放弃与之的交流，
  拒绝去感受它脉搏的跳动，我将会失去那份让我活着的平静。”
  #+END_QUOTE


- 5988-5990, 标注, 2025 年 9 月 30 日星期二 上午 8:14:48
  #+BEGIN_QUOTE md5: 7f7e3a2de990476244700ca454730ce0
  母亲的反对与算命师的预言，似乎给了他许多个义无反顾地去攀山的理由:逃避不可理喻的家庭，沉浸在单纯的大山，
  证明唯有自己才能掌控自己的命运。他学会了逃避。旅行是一种逃避，冒险是一种逃避，攀山也是一种逃避。
  #+END_QUOTE


- 6017-6021, 标注, 2025 年 9 月 30 日星期二 上午 8:18:17
  #+BEGIN_QUOTE md5: 51ed2e577baa21e317de31c68da468dd
  你们可曾想过我是跟随着你们的步伐吗?相信命运是靠自己双手打拼出来，而恐惧是可以克服的。当她写下我的命运，
  我的内心也曾低回在谷底中不能自拔，但我深知一切只是没有理性的恐惧，我选择去面对这个心魔。
  当她说我不能撞水的时候，我背着氧气桶潜到了海洋的深处;当她说我不能爬山的时候，
  我跟拍档一起登上了一生最艰难的高峰;当她说我不能驾车的时候，我骑着机车在山岭间愉悦地驰骋……然而
  #+END_QUOTE


- 6039-6040, 标注, 2025 年 9 月 30 日星期二 上午 8:20:38
  #+BEGIN_QUOTE md5: 730adea9ac3032de7349ae04679b93c0
  他的浪漫主义气质从他的生活渗透进心灵，进而成为他的思考原点。他的理想简简单单，甚至可以说是没有理想:
  #+END_QUOTE


- 6059-6061, 标注, 2025 年 9 月 30 日星期二 上午 8:22:33
  #+BEGIN_QUOTE md5: 8732819a1c55309ea23f1db3896448ce
  他回到了熟悉的香港。他觉得这钢筋水泥格外陌生，摩肩接踵的行人比他去过的荒漠更显冷漠。“我喘不过气，感到窒息。”
  他说。他回到阔别已久的工作室，把行李丢在地上，在沙发上疲惫地昏睡过去了。
  #+END_QUOTE


- 6062-6065, 标注, 2025 年 9 月 30 日星期二 上午 8:23:26
  #+BEGIN_QUOTE md5: 0e59538d5bd838daedaedd80be44e667,1c62937d44496026b97a61d009acbf30,1dc14410e8188f89a9020655869aba0b
  过了很久，才逐渐从旅途过后的情绪中平复下来。他开始反思过去几年的生活。
  他认为自己只不过是一个渴望自由却不懂何为自由的小屁孩，抱着满脑子的浪漫主意，误以为背起背包就可以获得真理。
  然而当一段段逃避性质的旅行结束，他只感到了虚无。唯有攀山，攀山让他发自内心地感到充实而快乐。
  #+END_QUOTE


- 6227-6230, 标注, 2025 年 9 月 30 日星期二 下午 12:33:24
  #+BEGIN_QUOTE md5: a92e18e2486b6226278d448a15a10622
  自由之巅的 90 后小教练们从李宗利那里学到了一切，唯有一样他们还没有学到 –自律。仅凭这点，
  李宗利确实有些骄傲的资本。即便他早已告别竞技运动员生涯十多年了，但还是保持着对自己严苛的要求:每天晚上 9
  点准时关掉手机睡觉，起床、吃饭、训练时间精确控制，即便是他最爱喝的酒，喝到一定量之后，说停就停。
  #+END_QUOTE


- 6317-6320, 标注, 2025 年 9 月 30 日星期二 下午 12:42:06
  #+BEGIN_QUOTE md5: b7f584ecca0d10562f9abb1cc999dce4
  他读到了《户外探险》杂志上一篇纪念刘兴的文章，文中写道:“据说人的细胞平均七年会完成一次整体的新陈代谢，
  第七年可能会因生活的平淡规律而感到乏味，进入倦息期便要经历一次危机考验。而刘兴的登山梦，从开始到结束，
  也正好七年。”
  #+END_QUOTE


- 6324-6328, 标注, 2025 年 9 月 30 日星期二 下午 12:42:55
  #+BEGIN_QUOTE md5: bb64eba0a779588c2aa20428e27f265d,dceceb0cd13a2cf5a6264bf4ab73b3f6
  《极限登山》中有一段话:“年轻人凭着一腔热血，经常能表现出毫无基础的勇敢，所谓无知者无畏。
  不过在阿尔卑斯和喜马拉雅山区，有许许多多的路线就是凭这种无知无畏开辟出来的。
  如果一位年轻的攀登者能从这样的心态中幸存下来，他/她最终会积累足够多的经验，将无知带来的狂妄转化成理性的自信，
  从而增加攀登成功的概率，减少死亡的风险。”


  现实社会中，人们对于无知与无畏的判断往往取决于最后的成败。如果一名攀登者不幸遇难了，
  无论他在登过程中展现了多少勇气，这次攀登往往被归类为“无知”。如果他九死一生地活下来了，
  无论他在这次攀登中犯了多少错误，这次经历往往被当作“无畏”。有时候，那些看似无畏的壮举也暗藏着许多危险。
  #+END_QUOTE


- 6720-6722, 标注, 2025 年 9 月 30 日星期二 下午 4:39:04
  #+BEGIN_QUOTE md5: dd67696c52e4b6e78121d2702d60a8c5
  “我知道很多非常热爱攀登的人，他们的搭档出事，第二天就不再攀登，卖掉他们所有的装备,”曾山说，“我还知道有一些人，
  如果一个好的搭档离开，还依然决定做这个事情，发自内心决定做这个事情，而且攀登越来越积极。攀登所给予他们的东西，
  完全超越了被攀登所夺走的东西。”显然，阿左属于后者。
  #+END_QUOTE


- 6864-6865, 标注, 2025 年 9 月 30 日星期二 下午 7:04:36
  #+BEGIN_QUOTE md5: 1acf3931254f66cb03ae598df080bcab
  周鹏看完这部片子后评价道:“高海拔探险是一场绝对真实的生命游戏，大多数时候被这场游戏本身的魅力所吸引，
  有时也怀疑自己以及这些志同道合的人，为何要用生命去参与如此真实的游戏?”也许
  #+END_QUOTE


- 7071-7074, 标注, 2025 年 9 月 30 日星期二 下午 10:22:46
  #+BEGIN_QUOTE md5: 2ba7dac869f9c35fab5a218330f731a3
  他格外担心好朋友在攀登中再出事，特别还是这种高难度的山峰。自从昊昕出事以来，
  在阿左内心深处一直有个情结在作祟:他把昊昕遇难的一部分原因归结为“捧杀”。当年他和吴昕登顶幺妹峰后，
  从寂寂无闻的登山爱好者，一夜之间成为大家口中的大神，被媒体报道和身边的吹捧裹挟着。
  “有时候可能别人觉得你很厉害，你就真的觉得自己很厉害。我发现好多事故都是这样子。”
  #+END_QUOTE


- 7338-7343, 标注, 2025 年 10 月 1 日星期三 下午 8:44:19
  #+BEGIN_QUOTE md5: b2bd066e5e93a39568e7b378d88f3d24
  攀向高处不需要理由。数百年来人们不停地思索、追问攀登高山的意义，直到登这一行为被赋予了战胜逆境般的人生隐喻，
  而顶峰也被塑造成了一处具象化的奋斗目标。然而在真实的世界中，山的顶峰不过是地质学上的偶发事件:在某个时间点，
  一堆石头或一条冰川恰好被抬升到了最高处，成为一组凸起的坐标。到达一处地球上比比皆是的坐标点的行为，
  本质上是无意义的。在许多人看来，为此承受人生的不稳定性与巨大的恐惧感更显荒谬而疯狂。
  为了一个没有世俗价值的目标，孤独地走向空无一人的大山，甘受生之痛苦、直面死之风险这便是自由攀登者的崇高，
  也是人之为人的美妙与独特之处。
  #+END_QUOTE


- 7451-7455, 标注, 2025 年 10 月 1 日星期三 下午 8:57:14
  #+BEGIN_QUOTE md5: 68d7c0ccfdfefebb2fc4c24b7faa56f7
  从一条山脉的千万年生命尺度来看，攀登者站在比山更高的地方雀跃、惊惶、俯瞰、呼吸，
  就和一片雪花悄无声息地落在山顶没什么区别。对于攀登者来说，一条山脉却贯穿着他们短暂的一生。
  无论是雄伟的喜马拉雅山，还是野蛮的喀喇昆仑山，无论是孕育出现代登山文化的阿尔卑斯山，
  还是保留着上百座未登峰的横断山、邛崃山，它们既是现实中的悲情与荣耀之山，也是攀登者心中的欲望与梦想之山。
  #+END_QUOTE
