:PROPERTIES:
:ID:       bf64c9a2-eb2e-43c2-a439-54d55cda9c87
:END:
#+TITLE: 我不知道该说什么，关于死亡还是爱情_来自切尔诺贝利的声音-[白俄] S·a·阿列克谢耶维奇;方祖芳;郭成业
#+AUTHOR: Yang,Ying-chao
#+DATE:   2025-11-19
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:  oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :wobuzhidaoga:clip:

- 64-64, 标注, 2025 年 11 月 18 日星期二 上午 9:07:22
  #+BEGIN_QUOTE md5: 25eb90622bfc557be4363309656bfddb
  我不知道该说什么，关于死亡还是爱情？也许两者是一样的，我该讲哪一种？
  #+END_QUOTE

- 142-144, 标注, 2025 年 11 月 18 日星期二 下午 1:29:32
  #+BEGIN_QUOTE md5: ee43d60745ff09785b4ab4b34a18c68e
  我当时遇到很多好人，有些我都忘了，不过我记得一位看门的老太太教我：“有些病是治不好的，你只能坐在旁边照顾他们。”
  #+END_QUOTE

- 146-151, 标注, 2025 年 11 月 18 日星期二 下午 1:30:21
  #+BEGIN_QUOTE md5: bde6fa93af21e970ef24899374feb3ad
  三天后，他们说我可以住进医院的员工宿舍。真是太棒了！

   “但是那里没有厨房，我怎么煮饭？”

   “你不用煮了，他们没办法消化。”

   他开始变了，每一天都判若两人。灼伤开始在外表显露，他的嘴巴、舌头、脸颊，一开始是小伤口，后来愈变愈大。
  白色薄片一层层脱落……脸的颜色……他的身体……蓝色……红色……灰褐色。那些都是我的回忆！无法用言语形容！无法以文字描述！
  甚至至今无法释怀。唯一拯救我的是一切发生得太快，根本没时间思考，没时间哭泣。
  #+END_QUOTE

- 218-219, 标注, 2025 年 11 月 18 日星期二 下午 1:35:55
  #+BEGIN_QUOTE md5: a434c9579f1eaa4afd1cfa8be3de93db
  床单只要稍微打结，他的身上就会出现伤口。我把指甲剪得短到流血，才不会不小心割伤他。没有护士接近他，
  他需要什么都会叫我。
  #+END_QUOTE


- 239-242, 标注, 2025 年 11 月 18 日星期二 下午 1:37:57
  #+BEGIN_QUOTE md5: f35851087f19f59ca47c2f3ee5a5e220
  在医院的最后两天——我抬起他的手臂，感觉骨头晃来晃去的，仿佛已经和身体分离。他的肺和肝的碎片都从嘴里跑出来，
  他被自己的内脏呛到。我用绷带包着手，伸进他的嘴里，拿出那些东西。我没办法讲这些事，没办法用文字描写，
  觉得好难熬。都是我的回忆，我的爱。
  #+END_QUOTE

- 259-260, 标注, 2025 年 11 月 18 日星期二 下午 1:39:38
  #+BEGIN_QUOTE md5: 239c2d6bbf0deff6b98213664ea1a89c
  我们支付宿舍费用。十四个晚上，那是治疗辐射中毒的医院，十四个晚上，一个人在十四天内死掉。
  #+END_QUOTE

- 332-333, 标注, 2025 年 11 月 18 日星期二 下午 7:20:34
  #+BEGIN_QUOTE md5: 4bdc265ccaa9a3a71e4b3876eaf1f2cb
  我记得小时候，野猪被宰杀时屋里弥漫的气味。你只要轻轻触碰，我就落入那个噩梦，跌进那种恐怖的感觉里。
  #+END_QUOTE

- 350-352, 标注, 2025 年 11 月 18 日星期二 下午 7:22:30
  #+BEGIN_QUOTE md5: 74510da5957211e76085096fb3757565
  死亡是世界上最公平的事，没有人逃得掉。地球带走每一个人——好人、坏人、罪人，除此之外，世界上就没有公平的事了。
  #+END_QUOTE


- 496-499, 标注, 2025 年 11 月 19 日星期三 上午 8:09:52
  #+BEGIN_QUOTE md5: 767200210f78339a231892e3232213c4
  ”我告诉你，我住儿子家的时候——他家在七楼，有一天，我用手画十字，走到窗前探头往下看，
  因为我好像听到马和公鸡的声音。我好难过。有时候我梦到我的院子，梦到我把牛绑起来，不停挤奶，然后我就醒了。
  我不想醒，只要我人没醒，就还在那里。有时我在这里，有时我在那里。” “我们白天住新房子，晚上住家里——在梦中。”
  #+END_QUOTE

- 505-506, 标注, 2025 年 11 月 19 日星期三 上午 8:10:36
  #+BEGIN_QUOTE md5: 4f600925befc983d92133fe6f4fd9ca1
  “小姐，不要哭！我们都站在最前线，我们是斯达汉诺夫工人，我们经历过斯大林时代，经历过战争！
  如果没有笑着安慰自己，我早就上吊自杀了。”
  #+END_QUOTE

- 507-509, 标注, 2025 年 11 月 19 日星期三 上午 8:11:07
  #+BEGIN_QUOTE md5: 1b1c7199e1c03234355fe447fe27c161
  “我妈妈教我拿一尊圣像，上下颠倒挂三天，这样无论你人在哪里，最后都能回家。我有两头母牛、两头小牛、五头猪、鹅、
  鸡，还有一只狗。我用手扶着头，在院子里走来走去。还有苹果，好多苹果！所有东西都消失了，就这样消失了！”
  #+END_QUOTE

- 509-510, 标注, 2025 年 11 月 19 日星期三 上午 8:11:24
  #+BEGIN_QUOTE md5: 0167ed40f308d8848875e6ff4aa79d62
  “我清洗房屋、漂白炉子。你要在餐桌上留面包、盐、小盘子和三根汤匙，屋里住多少人就放多少根汤匙，这样你才能回家。”
  #+END_QUOTE

- 522-523, 标注, 2025 年 11 月 19 日星期三 上午 8:13:16
  #+BEGIN_QUOTE md5: 8e874a335c8df220451f63e1847eb6a5
  “没有人可以蒙骗我们了，我们哪儿也不去。这里没有商店、医院，也没有电。我们坐在月光下点煤油灯，我们很喜欢这样！
  因为我们在自己的家里。”
  #+END_QUOTE

- 542-544, 标注, 2025 年 11 月 19 日星期三 上午 8:15:04
  #+BEGIN_QUOTE md5: 50211fbeffcdf4868c8594a9bf8ad2ca
  “我每天都梦到我的房子，梦到我回家，在菜园里挖土或整理床铺。我每次都能找到东西，不是一只鞋就是一只小鸡，
  每次都好棒，好开心，我马上就可以回家了……”
  #+END_QUOTE

- 557-562, 标注, 2025 年 11 月 19 日星期三 上午 8:19:06
  #+BEGIN_QUOTE md5: 918d56737fabf3e995450a3aa1bfe884
  “我有两袋盐，没有政府我们也活得很好！我们有很多木柴，周围就有一大片森林。房子很温暖，煤油灯在燃烧，
  我们过得很好！我有山羊、小羊，三只猪，十四只鸡。土地要多少有多少，草也要多少有多少，水井里有水，我们有自由！
  我们很快乐。现在不是集体农场了，而是公社，我们还要买一匹马，然后就什么也不需要了，只要再买一匹马。”
  “一个记者说：我们不只是回到家，还回到一百年前。我们用锤子收割，拿镰刀割草，在柏油路上打麦子。”
  #+END_QUOTE

- 576-579, 标注, 2025 年 11 月 19 日星期三 上午 8:20:49
  #+BEGIN_QUOTE md5: f8cbaeb376689ed69928d16b66df2c2a
  “有人带鸡蛋和面包到墓地，大家都坐在亲人旁边呼唤：‘姐姐，我来看你了，来吃午餐。’‘妈妈，亲爱的妈妈。爸爸，
  我死去的爸爸。’他们召唤在天堂的灵魂。亲人在今年过世的人会哭，之前过世的不会。人们聊天或回忆，大家都在祈祷，
  不会祷告的人也跟着祷告。”
  #+END_QUOTE

- 580-582, 标注, 2025 年 11 月 19 日星期三 上午 8:21:23
  #+BEGIN_QUOTE md5: 5cdf57c7fa40f0bd6398a2c59626a8db
  如果你不和他们一起玩，你就输了。一个乌克兰女人在市场叫卖大红苹果：‘来买苹果哟！切尔诺贝利的苹果！’
  有人劝她不要这样叫卖，没有人会买。‘别担心！’她说，‘还是有人买的，有些人要买给丈母娘，有些买给老板。’
  #+END_QUOTE

- 588-592, 标注, 2025 年 11 月 19 日星期三 上午 8:23:24
  #+BEGIN_QUOTE md5: 4bd3465b29b8bd720aa86a891215a408
  “没有电视和电影，不过有一件事可做——看窗户，当然还有祈祷。以前这里只有共产主义，没有上帝；现在这里只有上帝，
  所以我们祈祷。” “我们为国家效过力了，我参加过一年游击队，击退德国人的时候我就站在最前线。
  我把名字写在德国的国会大厦上：阿尔秋舍科。我流血流汗，建立了共产主义，现在共产主义在哪儿？”
  “我们这里有共产主义，我们就像兄弟姐妹……”
  #+END_QUOTE

- 605-606, 标注, 2025 年 11 月 19 日星期三 上午 8:24:53
  #+BEGIN_QUOTE md5: 110d89e30ae12c43fab02ce0fc405219
  “切尔诺贝利电厂为什么发生故障？有人说是科学家的错。他们抓上帝的胡子，现在他笑了，却是我们付出代价。”
  #+END_QUOTE

- 619-620, 标注, 2025 年 11 月 19 日星期三 上午 8:26:08
  #+BEGIN_QUOTE md5: 8daa7ca16f2268b153a2c4b2050b68ae
  “有一个老太太向我们保证，说我们永远不会死。我们祈祷：主啊，赐予我们力量，让我们熬过疲惫的生活。”
  #+END_QUOTE

- 616-616, 标注, 2025 年 11 月 19 日星期三 上午 8:26:14
  #+BEGIN_QUOTE md5: f99a0081426a77b154f3c22af7745d35
  世界仍然一样，但是人不一样了。
  #+END_QUOTE

- 648-654, 标注, 2025 年 11 月 19 日星期三 上午 8:38:26
  #+BEGIN_QUOTE md5: f90eb8fbc6a8f7ab78bfc9de1ddcd6de
  真正的经过是：我的爷爷养了五个蜂箱，蜜蜂整整两天没出来，一只都没有，它们在蜂窝里等。我的爷爷不知道发生了爆炸，
  他在院子里跑来跑去，说：“怎么了？发生了什么事？大自然出问题了。”我们的邻居是老师，他说蜜蜂比我们敏锐，
  因为它们听得见。广播什么也没报，报纸什么消息也没有，但是蜜蜂知道，它们过了三天才出来。黄蜂——
  我们家的门廊上有一个黄蜂巢，没有人碰它，可是那天早上黄蜂都不见了，一直到六年后才出现。人怕辐射，动物也怕，
  鸟类和树木也一样，但是它们很安静，它们不说话。这对万物来说都是可怕的浩劫，
  不过科罗拉多甲虫还是像平常一样到处出没，狼吞虎咽地吃我们的马铃薯，吃到只剩叶子，它们习惯毒物，和人一样。
  #+END_QUOTE

- 655-656, 标注, 2025 年 11 月 19 日星期三 上午 8:39:21
  #+BEGIN_QUOTE md5: 104114719c6bd62b5e65f32a07758fde
  每一家好像都有人死。河的另一头的那条街，所有女人都没有男人，男人都死光了。
  我们这条街只剩我的爷爷和另一个男人还活着。上帝为什么先带走男人？没有人知道答案。
  #+END_QUOTE

- 659-659, 标注, 2025 年 11 月 19 日星期三 上午 8:42:17
  #+BEGIN_QUOTE md5: 482145b83ff3270b4e0e02fa8326c38a
  我还能说什么？你总得活下去。
  #+END_QUOTE

- 682-684, 标注, 2025 年 11 月 19 日星期三 上午 8:47:45
  #+BEGIN_QUOTE md5: eea908f29bf0a747aba0fc92ed8f11eb
  只要告诉我们她的地址，告诉我们她在哪里生活，在哪里受苦，我们就可以接她回来，那样她才不会悲伤至死。我求求你，
  无辜的灵魂在陌生的地方受苦……
  #+END_QUOTE

- 906-908, 标注, 2025 年 11 月 19 日星期三 下午 1:18:57
  #+BEGIN_QUOTE md5: 9f18602fd893e1501d4b99e1ea9a894f
  有一个笑话很好笑：基辅蛋糕的半衰期是三十六小时，所以……那我呢？我是三年，三年后我交出党证，我的小红书。
  我在隔离区获得自由，切尔诺贝利撼动了我，也释放了我。
  #+END_QUOTE

- 948-949, 标注, 2025 年 11 月 19 日星期三 下午 1:22:19
  #+BEGIN_QUOTE md5: 8f4a7e5f86275030d69b93d8d6073bc5
  我没有告诉父母我被派到切尔诺贝利。我的弟弟在《消息报》上看到我的照片，拿去给妈妈看。“你看，”他说，“他是英雄！”
  我的母亲哭了。
  #+END_QUOTE

- 999-1000, 标注, 2025 年 11 月 19 日星期三 下午 1:26:48
  #+BEGIN_QUOTE md5: 3054ca8c1189cfd2246c0e84f1f5d996
  在那种时候，俄罗斯展现了它有多伟大，有多独特，我们永远不是荷兰或德国，不会有平整的柏油路或整齐的草坪，
  但是我们永远不缺牺牲奉献的英雄。
  #+END_QUOTE

- 1005-1006, 标注, 2025 年 11 月 19 日星期三 下午 1:27:22
  #+BEGIN_QUOTE md5: 891be0245ee65f61fb101a948bf68abd
  我听过一个笑话：男人下班回家告诉妻子：“他们说我明天不是去切尔诺贝利，就是交出党证。”
  “可是你不是党员。”“对啊，所以我在想怎么在明早之前弄到一张党证。”
  #+END_QUOTE

- 1016-1018, 标注, 2025 年 11 月 19 日星期三 下午 1:28:42
  #+BEGIN_QUOTE md5: 6b31c21872e1f594c82cb5a600419a37
  人们把所有拿得走、抬得动的东西都偷光了，隔离区的物品都被运回这里，你可以在市场、当铺或一般人的度假小屋看到。
  留在铁丝网里的只有土地和坟墓，还有我们的健康和信仰，或是我的信仰。
  #+END_QUOTE

- 1048-1049, 标注, 2025 年 11 月 19 日星期三 下午 1:30:57
  #+BEGIN_QUOTE md5: 8bf841eb1be28c3d12f307974c71efb1
  你想听另一个笑话吗？切尔诺贝利事故后你什么都可以吃，不过你得用铅把自己的排泄物埋起来。
  #+END_QUOTE

- 1058-1061, 标注, 2025 年 11 月 19 日星期三 下午 1:32:09
  #+BEGIN_QUOTE md5: 5f35aafe6b199fd9eb195f371bedf583
  我在工厂工作，老板说：“不许再生病，不然我们要裁掉你。” 后来他们真的把我裁掉了。我去找厂长说：
  “你没有权力这样做，我去过切尔诺贝利，我救了你们，保护你们！” 他说：“我们又没派你去。”
  #+END_QUOTE

- 1067-1071, 标注, 2025 年 11 月 19 日星期三 下午 1:33:16
  #+BEGIN_QUOTE md5: 4155ffb5f4b8355b892ff87bcf011208
  我从报纸上剪了一篇关于当晚在核电厂值班的操作员列昂尼德·塔普托诺夫的报道。爆炸前几分钟，他按下红色紧急按钮，
  可是无济于事。他们把他带到莫斯科的医院，医生说：“我们需要另一个身体才能治疗他。”
  他全身上下只有背上一个小点没有辐射。他们把他埋在迈汀斯卡亚的公墓，和其他人一样，先用金属薄片把棺材隔绝起来，
  再倒半米混凝土，加上铅盖。他的父亲站在那里哭，走过他身旁的人说：“都是你的王八蛋儿子害它爆炸的！”
  #+END_QUOTE

- 1115-1118, 标注, 2025 年 11 月 19 日星期三 下午 4:38:00
  #+BEGIN_QUOTE md5: fb4ecf6d2cb62e388f1727a6b4f49f5b
  很多年前，我的祖母看到《圣经》里描述说，世界上会有一段时间，万物都欣欣向荣、开花结果，河里有很多鱼，
  森林有很多动物，但是人类无法使用那些资源，无法繁衍后代，不能传宗接代。古老的预言就像可怕的童话，
  我当时不相信有那种事。
  #+END_QUOTE

- 1118-1120, 标注, 2025 年 11 月 19 日星期三 下午 4:38:19
  #+BEGIN_QUOTE md5: ee2f30d41421e4e34dc0506e940b5549
  她今年四岁，会唱歌、跳舞，还会背诗。她的智力发育很正常，和其他孩子没什么两样，可是她玩的游戏不一样，她不玩
  “商店”或“学校”，她玩“医院”。她替娃娃打针、量体温、吊点滴，娃娃死了，她帮娃娃盖上白色床单。
  #+END_QUOTE

- 1126-1129, 标注, 2025 年 11 月 19 日星期三 下午 4:39:15
  #+BEGIN_QUOTE md5: 2f887562948447f688e4354513c70e71
  我写：每半个小时，我们必须帮她从人工尿道开口处挤出尿液。世界上还有什么地方，有孩子每半个小时要把尿挤出来？
  她可以这样过多久？没有人知道低剂量的辐射对儿童的身体有什么影响，拿我的女儿做实验吧，我不要她死掉，
  她成为实验室青蛙、兔子都没关系，只要她能活下去就好。
  #+END_QUOTE

- 1156-1158, 标注, 2025 年 11 月 19 日星期三 下午 4:43:06
  #+BEGIN_QUOTE md5: 6420e58ab216ba66a771f465d0497885
  我记得事故发生后没几天，图书馆所有关于辐射、广岛或长崎，甚至关于 X 光的书都消失了。有些人说那是上级的指示，
  这样民众才不会惊慌。还有人开玩笑说，如果切尔诺贝利在巴布亚新几内亚附近爆炸，全世界的人都会很担心，
  只有巴布亚人不会害怕。
  #+END_QUOTE

- 1190-1193, 标注, 2025 年 11 月 19 日星期三 下午 4:45:22
  #+BEGIN_QUOTE md5: d6b37fd54b54cb2fe21e8a1c9c1c4ba2
  我告诉你，这里没有英雄，没什么值得书写。有时我想，这又不是战争，我为什么在这里冒生命危险，
  别人却和我的妻子睡觉？为什么是我，不是他？老实说，我在这里没有看过英雄，只有疯子，都是不在乎自己性命的人，
  我已经够疯狂了。我得到奖章和奖金，但那是因为我不怕死，我根本不在乎！对我来说那也是结束生命的方法，
  政府会出钱把我当成烈士埋葬。
  #+END_QUOTE

- 1228-1231, 标注, 2025 年 11 月 19 日星期三 下午 4:49:23
  #+BEGIN_QUOTE md5: d2835a8a1b857b313af3b05a1747fb07
  你可以用一瓶伏特加买到任何东西——奖章或病假。集体农场主席带了一箱伏特加给辐射专家，
  请他们把他的村子从疏散名单里剔除；另一个集体农场的主席也带来同样的箱子，请他们在名单里列上他的村子，
  因为有人答应在明斯克给他三套公寓。
  #+END_QUOTE

- 1238-1240, 标注, 2025 年 11 月 19 日星期三 下午 4:50:20
  #+BEGIN_QUOTE md5: fafef3c30d74da92f2999ddd7ddd299d
  官员念着报上的声明，说我们因为有“高度政治觉悟以及精心策划”，所以灾变后仅仅四天，红旗已经在四号反应炉上飘扬。
  那面红旗一个月后就被辐射吞噬，于是他们又派人插上另一面旗，一个月后又得再插一面。
  #+END_QUOTE

- 1264-1266, 标注, 2025 年 11 月 19 日星期三 下午 7:27:06
  #+BEGIN_QUOTE md5: b75f7eb0d588fcf7b2397518141b329b
  我第一次杀狐狸时还是小孩，后来我杀了一头母鹿。我发誓，后来我再也没有杀动物了，它们的眼睛里有好多感情。
  明白事理的是人类，动物只想生存，鸟也一样。
  #+END_QUOTE

- 1365-1367, 标注, 2025 年 11 月 19 日星期三 下午 7:59:23
  #+BEGIN_QUOTE md5: 23de178149843069a1b734b9505a45d9
  我没看过相关的书籍或电影，电影里描述的是战争，我的爷爷奶奶说他们没有童年，只有战争。他们的童年是战争，
  我的童年是切尔诺贝利，我就是来自那个地方。
  #+END_QUOTE

- 1450-1453, 标注, 2025 年 11 月 20 日星期四 上午 7:54:56
  #+BEGIN_QUOTE md5: 1807f4f20d7594db7e2f012ed723bd8a
  没有人明白发生了什么事，那是最可怕的部分。辐射探测仪给的数字是一组，报纸给的是另一组。所以我渐渐明白一件事：
  我家里有年幼的孩子，还有我亲爱的妻子……我怎么会笨到来这种地方？好吧，也许他们会颁一枚奖章给我，
  但是我的妻子会离开我。 在那里，唯一的救赎是幽默，所以出现了各种笑话：
  #+END_QUOTE

- 1457-1460, 标注, 2025 年 11 月 20 日星期四 上午 7:56:28
  #+BEGIN_QUOTE md5: 3b21cca087a4fe19b57add2e107395b8
  我拍摄开花的苹果树，看到大黄蜂嗡嗡作响，苹果花白得像新娘的白纱。人们还在工作，花园里花朵绽放。我拿着摄影机，
  总觉得哪里不对劲。曝光正常，画面漂亮，但就是不对劲，过了一阵子，我恍然大悟——我闻不到任何气味。花朵盛开，
  可是没有味道！ 后来我才知道，有时身体对高剂量辐射的反应是阻断某些器官的功能。
  #+END_QUOTE

- 1464-1467, 标注, 2025 年 11 月 20 日星期四 上午 7:57:42
  #+BEGIN_QUOTE md5: 7da46b116024483e03605a7b652236a8
  小时候，隔壁一个在战争期间参加过游击队的女人，告诉我他们的部队被包围，后来成功脱逃的故事。
  当时她带着一个月大的宝宝，和部队一起沿着沼泽前进，四处都是德国人。这时婴儿突然哭了起来，
  因为担心哭声泄露部队的行踪，她就把婴儿掐死了。 她告诉我这件事时很冷静，好像事情不是发生在她身上，
  孩子也不是她的。我不记得她为什么告诉我这种事，只记得我感觉很可怕……
  #+END_QUOTE

- 1476-1479, 标注, 2025 年 11 月 20 日星期四 上午 7:59:08
  #+BEGIN_QUOTE md5: 9de53037a62ba0f7a455c47ce19014c7
  我突然发现自己开始拍摄战争电影常见的场景，人们的举止也很像电影的画面，如同很多人喜欢的《雁南飞》里的场景——
  滴眼泪，简短的告别。原来我们都在寻找熟悉的行为模式，希望呈现出那个时刻该有的样子，符合我们记忆中的模样。
  女孩对妈妈挥手的方式就像在说：“一切都很好，我很勇敢，我们会胜利！”
  #+END_QUOTE

- 1489-1491, 标注, 2025 年 11 月 20 日星期四 上午 8:00:41
  #+BEGIN_QUOTE md5: 0a9eb0ee2e8b3167803630785b869bfc
  她们其实不是护士，只是军事研究部的人。他们把她们拉出来，告诉她们只需要待一个周末，但是我们到那里时，
  她们已经在隔离区待了一个月。她们说，她们被带到反应炉旁检视烧伤的人，只有她们和我们提过和烧伤有关的事。
  我仿佛还看得到那些如梦游般在宿舍走动的女孩。
  #+END_QUOTE

- 1514-1515, 标注, 2025 年 11 月 20 日星期四 上午 8:02:48
  #+BEGIN_QUOTE md5: a8c184c92ec4abec4fd9139ec378e718
  我发现世界末日时，邪恶的机制也照样运作，人们仍然说三道四，拍大官马屁，大官带着他的电视机和丑陋的皮草，
  一直到世界末日都是这样，永远是这样。
  #+END_QUOTE

- 1510-1513, 标注, 2025 年 11 月 20 日星期四 上午 8:03:03
  #+BEGIN_QUOTE md5: d9017bd612c7dca73147ba0196f71e57
  我们都是传播世界末日的人，有大有小。我的心里有一些画面：集体农场的主席要两辆车，
  因为他得运送家人和所有衣服家具，所以党部也要一辆车，这样才公平。而同时，
  他们好几天都找不到汽车运送托儿所的一群小孩。 两辆车都塞不下主席的所有家当，包括三升果酱和泡菜罐，
  我看着他们打包，却没有拍下来。（
  #+END_QUOTE

- 1620-1622, 标注, 2025 年 11 月 20 日星期四 上午 8:14:41
  #+BEGIN_QUOTE md5: 44a7a647c82d9c51a708b9a27202ae05
  之前，我们并不在意身边的环境。如同天空、空气一般，就在我们身边，像是被永久赐予我们的一样，不受人的影响，
  永远地存在着。我以前常躺在森林里仰望天空，惬意得连自己的名字都忘了。而现在呢？森林依旧美丽，长满了蓝莓，
  却再也没有人去摘了。
  #+END_QUOTE

- 1673-1675, 标注, 2025 年 11 月 20 日星期四 上午 8:25:17
  #+BEGIN_QUOTE md5: 643fef7bf3efeff5992d4275e3c400e8
  这世界已被一分为二：我们，是切尔诺贝利人；你们，是其他所有人。有人注意到了吗？在这里，没人会说自己是俄罗斯人、
  白俄罗斯人，或乌克兰人。我们都自称为切尔诺贝利人。
  #+END_QUOTE

- 1673-1676, 标注, 2025 年 11 月 20 日星期四 上午 8:25:28
  #+BEGIN_QUOTE md5: d5da7ff8345afc16d5a251de992564e0
  这世界已被一分为二：我们，是切尔诺贝利人；你们，是其他所有人。有人注意到了吗？在这里，没人会说自己是俄罗斯人、
  白俄罗斯人，或乌克兰人。我们都自称为切尔诺贝利人。 “我们是从切尔诺贝利来的。”“我是切尔诺贝利人。”
  就像另一个种族。就像一个新的国家。
  #+END_QUOTE

- 1713-1716, 标注, 2025 年 11 月 20 日星期四 上午 8:31:14
  #+BEGIN_QUOTE md5: 1af914abe31886a2f5f0bfdbe666f43e
  “中央委员会派了一些指导员前来。他们的活动范围是：从旅馆搭车到地方党部，然后再搭车回去。
  他们靠阅读地方报纸的标题来了解情况。他们从明斯克带来一大盒三明治，还用矿泉水煮茶。矿泉水当然也是带来的。
  这些是旅馆的女服务员告诉我的。人们不相信报纸、电视和广播，而是借观察官员的反应来获得信息，这样的信息较为可靠。”
  #+END_QUOTE

- 1704-1706, 标注, 2025 年 11 月 20 日星期四 上午 8:31:41
  #+BEGIN_QUOTE md5: 14bb1ed68e076122bdda6067aff2bfb9
  “斯大林时期的话语，又开始老调重弹了：‘西方的特工人员’，‘社会主义的大敌’，‘苏联人民坚固联邦的祸害’。
  大家都在谈论来这里的间谍和密探，却无人谈论服碘防护，所有非官方信息被视为西方的意识形态。”
  #+END_QUOTE

- 1703-1704, 标注, 2025 年 11 月 20 日星期四 上午 8:31:46
  #+BEGIN_QUOTE md5: b41db83f672912ad17ca39974539110b
  “同样的话已经连续广播了三个月：状况已日趋稳定，状况已日趋稳定，状况已日趋稳定……”
  #+END_QUOTE

- 1749-1751, 标注, 2025 年 11 月 20 日星期四 上午 8:40:06
  #+BEGIN_QUOTE md5: 64abd85a43f135e22c85158ccc75c8fb
  野生的猫早已集结成群，开始攻击人类。它们想要复仇。它们的记忆已经消失了，它们不记得自己的地位曾在人类之下，
  曾被人类驯养。对于我们而言，消失的是现实与虚假之间的界线。”
  #+END_QUOTE

- 1753-1754, 标注, 2025 年 11 月 20 日星期四 上午 8:40:55
  #+BEGIN_QUOTE md5: 96ad7e2f5762521c17d1096493ce9ba3
  “昨天我父亲过了八十岁生日。我们一家人聚在餐桌边。我看着父亲，想起他这一生的许多经历：古拉格集中营，
  奥斯维辛集中营，还有切尔诺贝利。
  #+END_QUOTE

- 1806-1811, 标注, 2025 年 11 月 20 日星期四 上午 8:47:27
  #+BEGIN_QUOTE md5: 33791c260a566f33fedea928c7709a0c
  亚罗舒克上校已经来日不多了。他是一个放射化学家。他以前壮得像头牛，现在却瘫痪在床。他老婆像翻枕头一样帮他翻身，
  拿汤匙给他喂食。他有肾结石，需要接受碎石治疗，但我们付不起手术费。我们一贫如洗，只能仰赖人们的救济。
  政府就像债主一样，我们这些人好像早已被政府遗忘。 当他死的时候，政府可能会用他的名字命名一条街，
  也可能是一座学校，或一项军事武器。但这些都要等他死了才会发生。亚罗舒克上校走遍了整个隔离区，
  将高辐射的地点一一标记出来。政府彻头彻尾地利用了他，把他当成机器人。上校也知道这一点，但他仍然去了。
  #+END_QUOTE

- 1821-1824, 标注, 2025 年 11 月 20 日星期四 上午 8:48:34
  #+BEGIN_QUOTE md5: bbe6e2daba56bafc3083e17b928c86ad
  现场的遥控机器时常不听使唤，因为电路会遭到高辐射的影响。最可靠的”机器”就是士兵，他们被称为“绿色机器
  人”（以军服的颜色命名）。三千六百名士兵曾在毁坏的反应炉屋顶作业。夜里，这些士兵睡在帐篷里，他们都曾跟我说过，
  刚开始时他们将麦秆铺在地上睡——这些麦秆都是从反应炉附近取来的。
  #+END_QUOTE

- 1904-1905, 标注, 2025 年 11 月 20 日星期四 下午 12:48:58
  #+BEGIN_QUOTE md5: 9196fe6588f63529fd318857ccf34906
  呢？”这场悲剧中泛滥着谎言，这些谎言就跟人们之间打招呼一样频繁！自欺欺人！（
  #+END_QUOTE

- 2077-2077, 标注, 2025 年 11 月 20 日星期四 下午 1:28:36
  #+BEGIN_QUOTE md5: 6b5bfcd413da2aac7c2d6d682d21bf53
  我感到很害怕——不是为我自己，而是为我儿子。他已无家可归了。
  #+END_QUOTE

- 2123-2125, 标注, 2025 年 11 月 20 日星期四 下午 1:31:59
  #+BEGIN_QUOTE md5: 4eff47b069fb0288865f3abcd4882877
  我母亲曾经救过我一命。她现在年事已高，好几次都变得一无所有。第一次是在二十世纪三十年代，她的牛、
  马和房子都被人夺走了。第二次是一把火，她从火场里唯一救出的就是我。现在她说：“只要我们还活着，
  这一切都会熬过去的。”
  #+END_QUOTE

- 2131-2134, 标注, 2025 年 11 月 20 日星期四 下午 1:33:04
  #+BEGIN_QUOTE md5: a1abd846a34741bee95f3af32905b1d0
  我时常梦想着，能在皮里亚特的阳光下和我儿子一同骑马。那里现在是一座空城了，但我们仍骑着马欣赏着玫瑰。
  皮里亚特有很多种玫瑰，有一大片一大片的玫瑰。我还年轻，我的孩子也还年幼。我深爱着他。在我的梦想里，
  我已经忘却了一切恐惧，从头到尾我都只是一个旁观者。
  #+END_QUOTE

- 2256-2259, 标注, 2025 年 11 月 20 日星期四 下午 10:45:08
  #+BEGIN_QUOTE md5: 25d5d3cada199fe5c50d051a27721cc7
  我们检验了牛奶。那些东西不是牛奶，是辐射的副产品。很长一段时间里，
  我们都使用罗加契夫乳制品工厂的炼乳和浓缩牛奶，来作为课堂上使用的标准辐射源。与此同时，这些产品还在市面上售卖。
  当人们开始拒绝购买罗加契夫的乳制品时，市面上忽然出现了一堆没有标识的牛奶。我不认为是他们忽然缺包装纸了。
  #+END_QUOTE

- 2377-2378, 标注, 2025 年 11 月 20 日星期四 下午 10:57:10
  #+BEGIN_QUOTE md5: a6e364464efaaf63fa1e5fe0cd84751a
  每个人都把自己的行为合理化，为自己找到借口。我自己就是最好的例子，我发现
  #+END_QUOTE

- 2377-2378, 标注, 2025 年 11 月 20 日星期四 下午 10:57:15
  #+BEGIN_QUOTE md5: 1da49c503f5dc151b1c0568cb4f98491
  每个人都把自己的行为合理化，为自己找到借口。我自己就是最好的例子，我发现可怕的事情总是悄悄发生在生活中。
  #+END_QUOTE

- 2395-2396, 标注, 2025 年 11 月 20 日星期四 下午 10:58:18
  #+BEGIN_QUOTE md5: 87194a77f9806b22565c72f6adf5ed5e
  切尔诺贝利给俄国人的思维模式带来了一场大灾难。有人说爆炸的不仅是反应炉，而是整个价值体系，我很同意这一点，
  但这样的解释还不够。
  #+END_QUOTE

- 2412-2414, 标注, 2025 年 11 月 20 日星期四 下午 11:00:35
  #+BEGIN_QUOTE md5: 6d00d0f31bfb4189b883a8e457577921
  我们要试试看，我们是否有能力重新审视过去的所有历史，就像战后的德国和日本一样。我们有足够的智识和勇气吗？
  人们很少谈论这一点，只懂得谈论开放市场、谈论票券和支票。我们再次存活了下来，耗尽了我们所有的精力。
  但我们的灵魂却被遗弃了。
  #+END_QUOTE

- 2454-2455, 标注, 2025 年 11 月 21 日星期五 下午 1:19:44
  #+BEGIN_QUOTE md5: 1caf9895bcee619d4147cbb95a6d972a
  “孩子们画着切尔诺贝利的涂鸦。画里的树是上下颠倒的。河里的水不是红色就是黄色。他们画着画着就哭了。”
  #+END_QUOTE

- 2576-2581, 标注, 2025 年 11 月 21 日星期五 下午 7:28:11
  #+BEGIN_QUOTE md5: eb210d3a2f2f01f2e5abe9cb1b11b8d4
  我们则把孩子们打扮得漂漂亮亮，去参加劳动节游行。我们可以选择去或不去，没有人强迫我们，也没有人要求我们参加。
  我们认为这是一种责任，是理所当然的！在这样的时代，这样的日子，大家都应该走到街上。我们涌入充满人潮的街上。
  地方党支部委员会的所有书记都来到看台上，就站在第一书记的身旁。他的小女儿也来了，站在台上，让大家都能看见。
  虽然是晴天，但是她穿着雨衣，戴着帽子，而第一书记则穿着军大衣。然而他们仍旧现身了，我记得很清楚。
  被污染的不只是土地，还有人心。长久以来一直如此。
  #+END_QUOTE

- 2716-2718, 标注, 2025 年 11 月 21 日星期五 下午 10:14:00
  #+BEGIN_QUOTE md5: 2cc349ba42a35d01e797aca7f150c91d
  我们都听过切尔诺贝利的传言，听说那里的火焰是不属于这个世界的，甚至不能称之为火焰。那是一道光，是闪亮的，
  不是蓝色，和天空的颜色很相近，也没有冒出烟雾。
  #+END_QUOTE

- 2790-2790, 标注, 2025 年 11 月 22 日星期六 上午 8:31:28
  #+BEGIN_QUOTE md5: 904738d68c8f299b7eb575db27882b45
  人民对他们而言就像砂土，只是历史的肥料。
  #+END_QUOTE

- 2787-2787, 标注, 2025 年 11 月 22 日星期六 上午 8:32:09
  #+BEGIN_QUOTE md5: e1f9a939f14b226c66e2ee9cebcb7d6c
  我是我们时代的产物。我深信共产主义。
  #+END_QUOTE

- 2812-2815, 标注, 2025 年 11 月 22 日星期六 上午 8:34:55
  #+BEGIN_QUOTE md5: 2f8b20e4348d65add3af06f279990ddb
  我们都是体制下的一分子。我们都坚信不疑！我们都相信崇高的理想，相信胜利！我们将战胜切尔诺贝利！
  我们都读过那些关闭失控反应炉的英勇战役。万一俄国人失去崇高的信念、失去伟大的梦想呢？这种想法很可怕。
  然而这就是正在发生的事。一切都崩解了，不再有政府、斯大林、古拉格群岛。
  #+END_QUOTE

- 2856-2857, 标注, 2025 年 11 月 22 日星期六 上午 8:41:19
  #+BEGIN_QUOTE md5: 8c163c5f729c1b96344eb26ef7cc2e09
  我是我们时代的产物。我不是罪人。
  #+END_QUOTE

- 2919-2922, 标注, 2025 年 11 月 22 日星期六 上午 8:47:43
  #+BEGIN_QUOTE md5: 63e26e88c8ebf1da99e47c38586b810b
  我们在一个村庄参观了幼儿园。小孩们跑来跑去，在沙堆里玩耍。主任告诉我们，这些沙每个月都会换新的，
  沙子是从别处运来的。你大概可以猜得到是哪里来的了。孩子们都很悲伤，我们讲笑话，他们却没有一丝笑容。
  孩子们的老师说：“别再试了，这些孩子不会笑的。”孩子们睡着时却会哭泣。
  #+END_QUOTE

- 2930-2931, 标注, 2025 年 11 月 22 日星期六 上午 8:48:52
  #+BEGIN_QUOTE md5: bbcdd7dfb38b388ca222acf7562c754b
  负责运送的驾驶员告诉我，这些小牛很古怪，它们的皮都拖到地上了，而且饿得什么都吃，包括破布和纸。它们很好养，
  全都是要卖到集体农场的。
  #+END_QUOTE

- 2969-2970, 标注, 2025 年 11 月 22 日星期六 上午 8:51:50
  #+BEGIN_QUOTE md5: c6fdb0bde02dd8e92c5a7b2c2248d292
  和平的苏联境内，原子能就和煤炭一样安全——人们是在这样的教育下长大的。我们是被恐惧和偏见束缚的人民，
  我们的信仰变成了迷信。
  #+END_QUOTE

- 3001-3004, 标注, 2025 年 11 月 22 日星期六 上午 9:00:17
  #+BEGIN_QUOTE md5: 60409bcfdb2e114007f90a6ec69b15c5
  这个国家属于当权者，国家永远摆在第一。他们大可以找出别的方法来实行预防——不需要公布，也不会造成恐慌。
  他们大可以把碘投放到水库里，或加在牛奶里。市内已备有七百公斤的浓缩碘来应付这种状况，但这些浓缩碘统统原封不动。
  人们害怕上级长官的程度，甚于害怕原子。所有人都在等待命令，等待电话，没有人行动。
  #+END_QUOTE

- 3010-3012, 标注, 2025 年 11 月 22 日星期六 上午 9:01:18
  #+BEGIN_QUOTE md5: 6e457c51fae0c4e1ec3af24666cf52bc
  与此同时，我们的斯柳尼科夫却只花了十五分钟处理这种状况：“一切都没事，我们会自行解决。” 大家都称赞他：
  “我们的白俄罗斯兄弟，这么做就对了！”想想这微不足道的赞美，是用多少生命换来的？
  #+END_QUOTE

- 3012-3016, 标注, 2025 年 11 月 22 日星期六 上午 9:02:32
  #+BEGIN_QUOTE md5: 88a2b72d3d5f225fba596391c9ef80a4
  我手里有资料，能证明那些长官都服用过碘剂。我研究所的同事帮他们检查时，他们有干净的甲状腺，不可能没服用过碘。
  他们还私下把自己的孩子送走，以防万一。当他们进到隔离区时，他们会戴上防毒面具和特制的外衣——
  这些装备是大家所没有的。他们在明斯克拥有专用的家畜，这也早已不是秘密了——每一头牛都有编号，并且严加管控。
  他们有专用的土地、专用的苗床，有专人来监督。最令人恶心的是，他们中间没人敢出来负责！
  #+END_QUOTE

- 3028-3031, 标注, 2025 年 11 月 22 日星期六 上午 9:03:58
  #+BEGIN_QUOTE md5: ea514efbb1cc52bee31bd0a5ff99b5a4
  好吧，我手里有地图和数据，而他们有什么？他们可以把我关到精神病院，我曾被他们这样威胁过。
  他们说可以保证我会发生意外车祸——我也收到过警告。他们可以让我受到法庭审判，罪名是从事反苏联活动，
  或者因为研究所里不见了一盒钉子。 然后，我被他们拉上法庭审判了。 他们达到了目的，我心脏病发作了。（
  #+END_QUOTE

- 3069-3071, 标注, 2025 年 11 月 22 日星期六 上午 9:06:34
  #+BEGIN_QUOTE md5: 1d91763fa332b9da52e8a45443d71a2a
  一打开电视，就能听到他们说：“不要听信西方世界的挑拨！” 这个时候，你才真的能确定发生事情了。
  #+END_QUOTE

- 3084-3084, 标注, 2025 年 11 月 22 日星期六 上午 9:08:11
  #+BEGIN_QUOTE md5: 828d49f7fb2c430844db1dd9b6097cf9
  但是不懂得为自身感到害怕，也算是一种未开化的习性。
  #+END_QUOTE

- 3084-3084, 标注, 2025 年 11 月 22 日星期六 上午 9:08:23
  #+BEGIN_QUOTE md5: 385919c6f74e691f7c9b8e968bebbe22
  但是不懂得为自身感到害怕，也算是一种未开化的习性。我们总是说“我们”，而不说“我”。
  #+END_QUOTE

- 3084-3087, 标注, 2025 年 11 月 22 日星期六 上午 9:08:56
  #+BEGIN_QUOTE md5: 37adfaafe4c17712c1e6ce79fce0d1b8
  但是不懂得为自身感到害怕，也算是一种未开化的习性。我们总是说“我们”，而不说“我”。
  “我们会让他们见识苏联人的勇气。” “我们要让他们瞧瞧苏联民族的厉害。” 我们要向全世界展现！但我还是我，
  我还是我自己。我不想死。我很害怕。
  #+END_QUOTE

- 3090-3092, 标注, 2025 年 11 月 22 日星期六 上午 9:09:45
  #+BEGIN_QUOTE md5: 4776eb5eca910b5a600d0d98fc3755c3
  苏联解体时，我们才发现自己孤立无依。我很不想这么说，但我们热爱切尔诺贝利。切尔诺贝利成为我们生命的意义，
  成为我们苦难的意义，如同战争一样。在切尔诺贝利事件之后，世人才得知我们的存在，我们才开启了通往欧洲的窗口。
  我们是切尔诺贝利的受害者，也是切尔诺贝利的信徒。
  #+END_QUOTE

- 3089-3092, 标注, 2025 年 11 月 22 日星期六 上午 9:09:54
  #+BEGIN_QUOTE md5: 49f4b70cade8fa0203d67c7a052a7d25
  伟大的帝国开始崩溃四散。首先是阿富汗，接着是切尔诺贝利。苏联解体时，我们才发现自己孤立无依。我很不想这么说，
  但我们热爱切尔诺贝利。切尔诺贝利成为我们生命的意义，成为我们苦难的意义，如同战争一样。在切尔诺贝利事件之后，
  世人才得知我们的存在，我们才开启了通往欧洲的窗口。我们是切尔诺贝利的受害者，也是切尔诺贝利的信徒。
  #+END_QUOTE

- 3107-3110, 标注, 2025 年 11 月 22 日星期六 上午 9:13:09
  #+BEGIN_QUOTE md5: 18fe0b8a949854ed7349e48cec0c65f4
  回程途中，夕阳西下。 我说：“看看这块土地多么美丽！” 太阳照耀着森林和田野，余晖仿佛在与我们道别。 “没错，”
  一位会说俄语的德国人说，“是很漂亮，但是被污染了。” 他手里正握着一个辐射剂量计。这时我才知道，
  只有我的眼里才看得到夕阳。这里是我的家乡，这里是我生活的地方。
  #+END_QUOTE

- 3140-3143, 标注, 2025 年 11 月 22 日星期六 上午 9:14:50
  #+BEGIN_QUOTE md5: 98318d468e7433b1f19945a1cdad0670
  医生说不能把我生下来，但我妈妈从医院逃出来，藏在外婆家里。所以我是在外婆家出生的。我听他们说过。
  我没有兄弟姐妹，我想要一个。 这位女士，你可以告诉我吗，为什么我不应该被生下来？那我该去哪里？高高地在天上吗？
  在别的星球上吗？
  #+END_QUOTE

- 3194-3195, 标注, 2025 年 11 月 22 日星期六 上午 9:19:53
  #+BEGIN_QUOTE md5: 8f749b0a1da42145b12426e6b5e14968
  我曾经伤心欲绝，曾经不知所措。我想找人谈谈，可是找凡人是不够的。我会去教堂，那里很安静，像是在丘陵上一样，
  安静得让人忘了自己。
  #+END_QUOTE

- 3225-3227, 标注, 2025 年 11 月 22 日星期六 上午 9:27:39
  #+BEGIN_QUOTE md5: bb1624746d6c599cddeb6b1e76992856
  普通工人可以在餐厅一楼吃到面和罐头食物，长官和将军则在餐厅二楼享用水果、红酒和矿泉水。二楼有干净的桌布，
  每人都有一台辐射剂量计。而一整队的普通工人却连一台辐射剂量计都没有。 噢，
  #+END_QUOTE

- 3224-3227, 标注, 2025 年 11 月 22 日星期六 上午 9:27:47
  #+BEGIN_QUOTE md5: 37856181525febb4ea3fd24936a78547
  我只从他那里知道了一件事：“在那里跟在这里没什么差别。” 普通工人可以在餐厅一楼吃到面和罐头食物，
  长官和将军则在餐厅二楼享用水果、红酒和矿泉水。二楼有干净的桌布，每人都有一台辐射剂量计。
  而一整队的普通工人却连一台辐射剂量计都没有。 噢，
  #+END_QUOTE

- 3230-3234, 标注, 2025 年 11 月 22 日星期六 上午 9:28:37
  #+BEGIN_QUOTE md5: d5aeed148a34b5c09f16f30b4a421404
  我是个为爱而生的人。学校里的女孩都梦想着上大学，或加入共青团的工读旅游，只有我梦想着结婚。我想要去爱，
  热烈地爱人，像娜塔莎·罗斯托夫一样，只为了爱。但我不敢跟别人说，因为当时你的梦想应该是参加共青团的建设旅游。
  他们就是那样教导我们
  #+END_QUOTE

- 3303-3305, 标注, 2025 年 11 月 22 日星期六 下午 3:11:22
  #+BEGIN_QUOTE md5: 42b3ffd66fe52df234f5a424d10bef56
  医生对我说：如果肿瘤在他体内蔓延，他就活不久了，但肿瘤只是慢慢向上移，从身体到脸上。他的身上长出了黑色的东西。
  他的下巴移位了，脖子不见了，舌头却跑了出来。他的血管开始破裂流血。脖子，脸颊，耳朵，到处都是。我装了冷水，
  用湿布擦拭他，却一点帮助也没有。
  #+END_QUOTE
