:PROPERTIES:
:ID:       0c97169b-9aba-438f-81cb-5aa316f9dc3d
:END:
#+TITLE: 尘埃落定_十五周年纪念版-阿来
#+AUTHOR: Yang,Ying-chao
#+DATE:   2025-11-10
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:  oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :chenailuodin:clip:tibet:xizang:


- 285-286, 标注, 2025 年 11 月 7 日星期五 下午 10:24:24
  #+BEGIN_QUOTE md5: b8ee8e2018b4f352ec3def6eeb8aea98
  总而言之，我们在那个时代订出的规矩是叫人向下而不是叫人向上的。骨头沉重高贵的人是制作这种规范的艺术家。
  #+END_QUOTE


- 290-292, 标注, 2025 年 11 月 7 日星期五 下午 10:26:19
  #+BEGIN_QUOTE md5: 9b3d1846a3d289055834f7934c6c7d64
  有个喇嘛曾经对我说：雪山栅栏中居住的藏族人，面对罪恶时是非不分就像沉默的汉族人；而在没有什么欢乐可言时，
  却显得那么欢乐又像印度人。
  #+END_QUOTE


- 294-297, 标注, 2025 年 11 月 7 日星期五 下午 10:27:31
  #+BEGIN_QUOTE md5: f4e5454d18706f91dfe5460924112a14
  关于这个问题我是这样想的：释迦牟尼之前，是先知的时代，之后，我们就再也不需要用自己的脑子来思考了。
  如果你觉得自己是杰出的人，而又不是生为贵族，那就做一个喇嘛为人们描绘来世的图景吧。如果你觉得关于现在，
  关于人生，有话不能不说，那就赶快。否则，等到没有了舌头，那就什么也说不出来了。
  #+END_QUOTE


- 475-478, 标注, 2025 年 11 月 7 日星期五 下午 11:13:01
  #+BEGIN_QUOTE md5: 8c889db3a4d265fa5cc6aa6863b18072
  这就是我们麦其土司历史上的第一张照片。现在想来，照相术进到我们的地方可真是时候，
  好像是专门要为我们的末日留下清晰的画图。而在当时我们却都把这一切看成是家族将比以前更加兴旺的开端。当时，
  我的父亲和母亲都是那样生气勃勃，可照片却把我们弄得那么呆板，好像命定了是些将很快消失的人物。你看吧，
  照片上的父亲一副不死不活
  #+END_QUOTE


- 851-853, 标注, 2025 年 11 月 8 日星期六 下午 2:03:26
  #+BEGIN_QUOTE md5: 9a15c72c871dad64d13d121ae2555c1c
  用一个傻子的脑子来回忆一个聪明人所布置的事情，真是太辛苦了。在我看来，聪明人就像是山上那些永远担惊受怕的旱獭，
  吃饱了不好好安安生生地在太阳下睡觉，偏偏这里打一个洞，那里屙一泡屎，要给猎人无数障眼的疑团。
  可到头来总是徒劳枉然。
  #+END_QUOTE


- 933-936, 标注, 2025 年 11 月 8 日星期六 下午 2:09:42
  #+BEGIN_QUOTE md5: 096256eed6b75e6276efd800d353e8bd
  查查是所有头人里最忠诚的一个。而且，这也不是一代两代的事了。他就是不该有这么漂亮的老婆，同时，
  也不该拥有那么多的银子，叫土司见了晚上睡不着觉。要是自动地把这一切主动叫土司分享一点，
  也不至于到今天这个地步了。想到这些，父亲禁不住为人性中难得满足的贪欲叹了口气。
  #+END_QUOTE


- 1076-1079, 标注, 2025 年 11 月 8 日星期六 下午 4:28:32
  #+BEGIN_QUOTE md5: 962468a0a03eedf599e9958ec7d1eacf
  我很寂寞。土司，大少爷，土司太太，他们只要没有打仗，没有节日，没有惩罚下人的机会，也都是十分寂寞的。
  我突然明白了父亲为什么要不断地制造事端。为了一个小小的反叛的寨子到内地的省政府请愿，引种鸦片，
  叫自己的士兵接受新式的操练，为一个女人杀掉忠于自己的头人，让僧人像女人们一样互相争宠斗气。
  #+END_QUOTE


- 1171-1173, 标注, 2025 年 11 月 8 日星期六 下午 5:04:55
  #+BEGIN_QUOTE md5: ca88a997f52b83f7cd687f1d2e6cb5de
  浓稠的白色，一点一滴，从一枚枚罂粟果子中渗出，汇聚，震颤，坠落。罂粟挤出它白色的乳浆，就像大地在哭泣。
  它的泪珠要落不落，将坠未坠的样子，挂在小小的光光的青青果实上无语凝咽。
  #+END_QUOTE


- 1459-1461, 标注, 2025 年 11 月 8 日星期六 下午 5:51:58
  #+BEGIN_QUOTE md5: 755ba284cc5e45ab996d75e95b1f5f53
  而我想起了翁波意西。突然觉得做传布没人接受的教义的僧人很有意思。身边一个人也没有，只有毛驴在身边吃草，
  只有雪在山洞口飘舞着，如一个漂亮的帘子。这时，我体会到一种被人，被整个世界抛弃的快感。
  #+END_QUOTE


- 3240-3243, 标注, 2025 年 11 月 8 日星期六 下午 10:41:26
  #+BEGIN_QUOTE md5: 5b2ddfb19711eefb04509363f4d796af
  我紧紧地把她抱在了怀里，像紧抱着自己的命运。就在这时，我突然明白，就是以一个傻子的眼光来看，
  这个世界也不是完美无缺的。这个世界上任何东西都是这样，你不要它，它就好好地在那里，保持着它的完整，它的纯粹，
  一旦到了手中，你就会发现，自己没有全部得到。
  #+END_QUOTE


- 3772-3774, 标注, 2025 年 11 月 9 日星期日 下午 7:11:02
  #+BEGIN_QUOTE md5: bcd1f849b720d2e9154b1d32e0f2ccc9
  塔娜这样子，使我的心隐隐作痛。我走到外面走廊上，眺望远处的青山。正是太阳初升的时候，
  青山在阳光的纱幕后若隐若显，就像突然涌上我心头的悲伤。同得到了东西时的悲伤相比，
  得不到东西时的悲伤根本算不上是悲伤。
  #+END_QUOTE


- 5256-5258, 标注, 2025 年 11 月 10 日星期一 上午 7:51:25
  #+BEGIN_QUOTE md5: 4d8da55806972e9cfc356fac433fadd8
  我确实清清楚楚地看见了结局，互相争雄的土司们一下就不见了。土司官寨分崩离析，冒起了蘑菇状的烟尘。
  腾空而起的尘埃散尽之后，大地上便什么也没有了。
  #+END_QUOTE


- 5278-5280, 标注, 2025 年 11 月 10 日星期一 上午 7:53:15
  #+BEGIN_QUOTE md5: f2ab304030db972f92caec5e824f3c7f
  师爷说，一个完整而强大的国家绝对只能有一个王。那个王者，绝对不能允许别的人自称王者，哪怕只是一个小小的土王。
  他说：“少爷是不担心变化的，因为你已经不是生活在土司时代。”
  #+END_QUOTE


- 5345-5348, 标注, 2025 年 11 月 10 日星期一 上午 8:00:33
  #+BEGIN_QUOTE md5: aafec2ddfcc6168cc352505d10365636,f7c21cc9f0d6a584b2619af9401bdf14
  高高在上的土司们其实都十分寂寞。 银子有了，要么睡不着觉，要么睡着了也梦见有人前来抢夺。女人有了，但到后来，
  好的女人要支配你，不好的女人又唤不起睡在肥胖身体深处的情欲。最后，土司们老了，那个使男人充满自信的地方，
  早就永远地死去了。麦其土司被一身肥肉包裹着，用无奈的眼睛看着曾跟自己有过云雨之欢的茸贡土司。他们都老了。
  #+END_QUOTE


- 5484-5485, 标注, 2025 年 11 月 10 日星期一 上午 8:15:34
  #+BEGIN_QUOTE md5: 458fcbb5f6b613bff0fcc8225a3e6122
  姑娘们整天闲逛，银铃样的笑声顺着街道流淌。
  #+END_QUOTE


- 5538-5540, 标注, 2025 年 11 月 10 日星期一 上午 8:19:40
  #+BEGIN_QUOTE md5: 26b6336105ee46e0c3000270c1ee6aee
  那阵，在我们这地方，老百姓中间，都在传说汉人就要来了。书记官说过，老百姓相信的事情总是要发生的，
  就算听上去没有多少道理，但那么多人都说同一个话题，就等于同时念动了同一条咒语，向上天表达了同一种意志。
  #+END_QUOTE


- 5680-5681, 标注, 2025 年 11 月 10 日星期一 上午 8:41:53
  #+BEGIN_QUOTE md5: e6fc812e15b59916bd3233f6f3287369
  银匠此行是没有希望的。但人都是一样的，银匠也罢，土司也罢，奴隶也罢，都只想自己要做什么，
  而不敢问这样做有没有希望。
  #+END_QUOTE


- 5717-5721, 标注, 2025 年 11 月 10 日星期一 上午 8:44:46
  #+BEGIN_QUOTE md5: dc0a66804e5cb46e9271c5bd666979fa
  他说，好多土司都在诅咒这个镇子。 他们认为是这个镇子使他们的身体有病，并且腐烂。谁见过人活着就开始腐烂？过去，
  人都是死去后，灵魂离开之后才开始腐烂的，但现在，他们还活着，身体就开始从用来传宗接代，
  也用来使自己快乐的那个地方开始腐烂了。

  我问过书记官，这个镇子是不是真该被诅咒。他的回答是，并不是所有到过这个镇子的人身体都腐烂了。他说，
  跟这个镇子不般配的人才会腐烂。
  #+END_QUOTE


- 5717-5722, 标注, 2025 年 11 月 10 日星期一 上午 8:44:53
  #+BEGIN_QUOTE md5: 06a25a303217739cfbe81f8ddf1fb531
  他说，好多土司都在诅咒这个镇子。 他们认为是这个镇子使他们的身体有病，并且腐烂。谁见过人活着就开始腐烂？过去，
  人都是死去后，灵魂离开之后才开始腐烂的，但现在，他们还活着，身体就开始从用来传宗接代，
  也用来使自己快乐的那个地方开始腐烂了。 我问过书记官，这个镇子是不是真该被诅咒。

  他的回答是，并不是所有到过这个镇子的人身体都腐烂了。他说，跟这个镇子不般配的人才会腐烂。

  前僧人，现在的书记官翁波意西说，
  凡是有东西腐烂的地方都会有新的东西生长。
  #+END_QUOTE


- 5744-5745, 标注, 2025 年 11 月 10 日星期一 上午 8:47:23
  #+BEGIN_QUOTE md5: 36baca8f56ee3c5601c8d58cedc2fbf9
  出发那天，下起了大雪。这是一场前所未见的大雪，雪花就像成群的鸟，密不透风地从天上扑向大地。
  #+END_QUOTE


- 5956-5961, 标注, 2025 年 11 月 10 日星期一 下午 12:56:08
  #+BEGIN_QUOTE md5: 5da2b2f09186553a4e8996d5ae92a17b
  这一晚上剩下的时间，我一直都在做梦，零零碎碎，但却把我一生经历过的事情都梦见了。当太阳晃着眼睛时，我醒来了，
  发现自己睡在小时候住的那个房间里，就睡在小时候睡的那张床上。就是在这里，那个下雪的早晨，
  我第一次把手伸进了一个叫桑吉卓玛的侍女怀里。就是在这里，那个下雪的早晨，画眉鸟在窗子外面声声叫唤，
  一个侍女的身体唤醒了沉睡在傻子脑袋里那一点点智慧。我的记忆就从那个早晨，就从这个屋子，从这张床上开始了。
  那年我十三岁，我的生命是从十三岁那年开始的，现在，我不知道自己多少岁了。
  #+END_QUOTE


- 6047-6051, 标注, 2025 年 11 月 10 日星期一 下午 1:01:46
  #+BEGIN_QUOTE md5: 28a2f2445c29cf90fa81d38e5d55a5aa
  我看见麦其土司的精灵已经变成一股旋风飞到天上，剩下的尘埃落下来，融入大地。我的时候就要到了。我当了一辈子傻子，
  现在，我知道自己不是傻子，也不是聪明人，不过是在土司制度将要完结的时候到这片奇异的土地上来走了一遭。 是的，
  上天叫我看见，叫我听见，叫我置身其中，又叫我超然物外。上天是为了这个目的，才让我看起来像个傻子的。
  #+END_QUOTE
