:PROPERTIES:
:ID:       bf64c9a2-eb2e-43c2-a439-54d55cda9c87
:END:
#+TITLE: 我不知道该说什么，关于死亡还是爱情_来自切尔诺贝利的声音-[白俄] S·a·阿列克谢耶维奇;方祖芳;郭成业
#+AUTHOR: Yang,Ying-chao
#+DATE:   2025-11-19
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:  oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :wobuzhidaoga:clip:unwashed:

* Unwashed Entries                                                  :noexport:

- 64-64, 标注, 2025 年 11 月 18 日星期二 上午 9:07:22
  #+BEGIN_QUOTE md5: 25eb90622bfc557be4363309656bfddb
  我不知道该说什么，关于死亡还是爱情？也许两者是一样的，我该讲哪一种？
  #+END_QUOTE

- 142-144, 标注, 2025 年 11 月 18 日星期二 下午 1:29:32
  #+BEGIN_QUOTE md5: ee43d60745ff09785b4ab4b34a18c68e
  我当时遇到很多好人，有些我都忘了，不过我记得一位看门的老太太教我：“有些病是治不好的，你只能坐在旁边照顾他们。”
  #+END_QUOTE

- 146-151, 标注, 2025 年 11 月 18 日星期二 下午 1:30:21
  #+BEGIN_QUOTE md5: bde6fa93af21e970ef24899374feb3ad
  三天后，他们说我可以住进医院的员工宿舍。真是太棒了！ “但是那里没有厨房，我怎么煮饭？” “你不用煮了，
  他们没办法消化。” 他开始变了，每一天都判若两人。灼伤开始在外表显露，他的嘴巴、舌头、脸颊，一开始是小伤口，
  后来愈变愈大。白色薄片一层层脱落……脸的颜色……他的身体……蓝色……红色……灰褐色。那些都是我的回忆！无法用言语形容！
  无法以文字描述！甚至至今无法释怀。唯一拯救我的是一切发生得太快，根本没时间思考，没时间哭泣。
  #+END_QUOTE

- 218-219, 标注, 2025 年 11 月 18 日星期二 下午 1:35:55
  #+BEGIN_QUOTE md5: a434c9579f1eaa4afd1cfa8be3de93db
  床单只要稍微打结，他的身上就会出现伤口。我把指甲剪得短到流血，才不会不小心割伤他。没有护士接近他，
  他需要什么都会叫我。
  #+END_QUOTE

- 239-240, 标注, 2025 年 11 月 18 日星期二 下午 1:37:40
  #+BEGIN_QUOTE md5: 2858855ab73f0326989baa21cd7e0abb
  在医院的最后两天——我抬起他的手臂，感觉骨头晃来晃去的，仿佛已经和身体分离。
  #+END_QUOTE

- 239-242, 标注, 2025 年 11 月 18 日星期二 下午 1:37:57
  #+BEGIN_QUOTE md5: f35851087f19f59ca47c2f3ee5a5e220
  在医院的最后两天——我抬起他的手臂，感觉骨头晃来晃去的，仿佛已经和身体分离。他的肺和肝的碎片都从嘴里跑出来，
  他被自己的内脏呛到。我用绷带包着手，伸进他的嘴里，拿出那些东西。我没办法讲这些事，没办法用文字描写，
  觉得好难熬。都是我的回忆，我的爱。
  #+END_QUOTE

- 259-260, 标注, 2025 年 11 月 18 日星期二 下午 1:39:38
  #+BEGIN_QUOTE md5: 239c2d6bbf0deff6b98213664ea1a89c
  我们支付宿舍费用。十四个晚上，那是治疗辐射中毒的医院，十四个晚上，一个人在十四天内死掉。
  #+END_QUOTE

- 259-260, 标注, 2025 年 11 月 18 日星期二 下午 1:39:47
  #+BEGIN_QUOTE md5: 2bf70fcf44fad5cc08220d6666c80285
  我们支付宿舍费用。十四个晚上，那是治疗辐射中毒的医院，十四个晚上，一个人在十四天内死掉。 回家后，
  我一走进屋子就跌到床上，整整睡了三天。
  #+END_QUOTE

- 332-333, 标注, 2025 年 11 月 18 日星期二 下午 7:20:34
  #+BEGIN_QUOTE md5: 4bdc265ccaa9a3a71e4b3876eaf1f2cb
  我记得小时候，野猪被宰杀时屋里弥漫的气味。你只要轻轻触碰，我就落入那个噩梦，跌进那种恐怖的感觉里。
  #+END_QUOTE

- 350-352, 标注, 2025 年 11 月 18 日星期二 下午 7:22:22
  #+BEGIN_QUOTE md5: ef7509e2933148cf6a122eba162a95ef
  死亡是世界上最公平的事，没有人逃得掉。地球带走每一个人——好人、坏人、罪人，除此之外，世界上就没有公平的事了。
  我这辈子对人都很诚实，工作也很努力，
  #+END_QUOTE

- 350-352, 标注, 2025 年 11 月 18 日星期二 下午 7:22:30
  #+BEGIN_QUOTE md5: 74510da5957211e76085096fb3757565
  死亡是世界上最公平的事，没有人逃得掉。地球带走每一个人——好人、坏人、罪人，除此之外，世界上就没有公平的事了。
  #+END_QUOTE

- 496-499, 标注, 2025 年 11 月 19 日星期三 上午 8:09:28
  #+BEGIN_QUOTE md5: 2f2817a5e6e92e781db45425a526153a
  “我告诉你，我住儿子家的时候——他家在七楼，有一天，我用手画十字，走到窗前探头往下看，
  因为我好像听到马和公鸡的声音。我好难过。有时候我梦到我的院子，梦到我把牛绑起来，不停挤奶，然后我就醒了。
  我不想醒，只要我人没醒，就还在那里。有时我在这里，有时我在那里。”
  #+END_QUOTE

- 496-499, 标注, 2025 年 11 月 19 日星期三 上午 8:09:41
  #+BEGIN_QUOTE md5: 0d7d208ebc46fda8dca9d1fbfc1e60b4
  “我告诉你，我住儿子家的时候——他家在七楼，有一天，我用手画十字，走到窗前探头往下看，
  因为我好像听到马和公鸡的声音。我好难过。有时候我梦到我的院子，梦到我把牛绑起来，不停挤奶，然后我就醒了。
  我不想醒，只要我人没醒，就还在那里。有时我在这里，有时我在那里。” “我们白天
  #+END_QUOTE

- 496-499, 标注, 2025 年 11 月 19 日星期三 上午 8:09:52
  #+BEGIN_QUOTE md5: 767200210f78339a231892e3232213c4
  ”我告诉你，我住儿子家的时候——他家在七楼，有一天，我用手画十字，走到窗前探头往下看，
  因为我好像听到马和公鸡的声音。我好难过。有时候我梦到我的院子，梦到我把牛绑起来，不停挤奶，然后我就醒了。
  我不想醒，只要我人没醒，就还在那里。有时我在这里，有时我在那里。” “我们白天住新房子，晚上住家里——在梦中。”
  #+END_QUOTE

- 505-506, 标注, 2025 年 11 月 19 日星期三 上午 8:10:36
  #+BEGIN_QUOTE md5: 4f600925befc983d92133fe6f4fd9ca1
  “小姐，不要哭！我们都站在最前线，我们是斯达汉诺夫工人，我们经历过斯大林时代，经历过战争！
  如果没有笑着安慰自己，我早就上吊自杀了。”
  #+END_QUOTE

- 507-509, 标注, 2025 年 11 月 19 日星期三 上午 8:11:07
  #+BEGIN_QUOTE md5: 1b1c7199e1c03234355fe447fe27c161
  “我妈妈教我拿一尊圣像，上下颠倒挂三天，这样无论你人在哪里，最后都能回家。我有两头母牛、两头小牛、五头猪、鹅、
  鸡，还有一只狗。我用手扶着头，在院子里走来走去。还有苹果，好多苹果！所有东西都消失了，就这样消失了！”
  #+END_QUOTE

- 509-510, 标注, 2025 年 11 月 19 日星期三 上午 8:11:24
  #+BEGIN_QUOTE md5: 0167ed40f308d8848875e6ff4aa79d62
  “我清洗房屋、漂白炉子。你要在餐桌上留面包、盐、小盘子和三根汤匙，屋里住多少人就放多少根汤匙，这样你才能回家。”
  #+END_QUOTE

- 522-523, 标注, 2025 年 11 月 19 日星期三 上午 8:13:16
  #+BEGIN_QUOTE md5: 8e874a335c8df220451f63e1847eb6a5
  “没有人可以蒙骗我们了，我们哪儿也不去。这里没有商店、医院，也没有电。我们坐在月光下点煤油灯，我们很喜欢这样！
  因为我们在自己的家里。”
  #+END_QUOTE

- 542-544, 标注, 2025 年 11 月 19 日星期三 上午 8:15:04
  #+BEGIN_QUOTE md5: 50211fbeffcdf4868c8594a9bf8ad2ca
  “我每天都梦到我的房子，梦到我回家，在菜园里挖土或整理床铺。我每次都能找到东西，不是一只鞋就是一只小鸡，
  每次都好棒，好开心，我马上就可以回家了……”
  #+END_QUOTE

- 557-562, 标注, 2025 年 11 月 19 日星期三 上午 8:19:06
  #+BEGIN_QUOTE md5: 918d56737fabf3e995450a3aa1bfe884
  “我有两袋盐，没有政府我们也活得很好！我们有很多木柴，周围就有一大片森林。房子很温暖，煤油灯在燃烧，
  我们过得很好！我有山羊、小羊，三只猪，十四只鸡。土地要多少有多少，草也要多少有多少，水井里有水，我们有自由！
  我们很快乐。现在不是集体农场了，而是公社，我们还要买一匹马，然后就什么也不需要了，只要再买一匹马。”
  “一个记者说：我们不只是回到家，还回到一百年前。我们用锤子收割，拿镰刀割草，在柏油路上打麦子。”
  #+END_QUOTE

- 576-579, 标注, 2025 年 11 月 19 日星期三 上午 8:20:49
  #+BEGIN_QUOTE md5: f8cbaeb376689ed69928d16b66df2c2a
  “有人带鸡蛋和面包到墓地，大家都坐在亲人旁边呼唤：‘姐姐，我来看你了，来吃午餐。’‘妈妈，亲爱的妈妈。爸爸，
  我死去的爸爸。’他们召唤在天堂的灵魂。亲人在今年过世的人会哭，之前过世的不会。人们聊天或回忆，大家都在祈祷，
  不会祷告的人也跟着祷告。”
  #+END_QUOTE

- 580-582, 标注, 2025 年 11 月 19 日星期三 上午 8:21:23
  #+BEGIN_QUOTE md5: 5cdf57c7fa40f0bd6398a2c59626a8db
  “如果你不和他们一起玩，你就输了。一个乌克兰女人在市场叫卖大红苹果：‘来买苹果哟！切尔诺贝利的苹果！’
  有人劝她不要这样叫卖，没有人会买。‘别担心！’她说，‘还是有人买的，有些人要买给丈母娘，有些买给老板。’”
  #+END_QUOTE

- 588-592, 标注, 2025 年 11 月 19 日星期三 上午 8:23:24
  #+BEGIN_QUOTE md5: 4bd3465b29b8bd720aa86a891215a408
  “没有电视和电影，不过有一件事可做——看窗户，当然还有祈祷。以前这里只有共产主义，没有上帝；现在这里只有上帝，
  所以我们祈祷。” “我们为国家效过力了，我参加过一年游击队，击退德国人的时候我就站在最前线。
  我把名字写在德国的国会大厦上：阿尔秋舍科。我流血流汗，建立了共产主义，现在共产主义在哪儿？”
  “我们这里有共产主义，我们就像兄弟姐妹……”
  #+END_QUOTE

- 605-606, 标注, 2025 年 11 月 19 日星期三 上午 8:24:53
  #+BEGIN_QUOTE md5: 110d89e30ae12c43fab02ce0fc405219
  “切尔诺贝利电厂为什么发生故障？有人说是科学家的错。他们抓上帝的胡子，现在他笑了，却是我们付出代价。”
  #+END_QUOTE

- 619-620, 标注, 2025 年 11 月 19 日星期三 上午 8:26:08
  #+BEGIN_QUOTE md5: 8daa7ca16f2268b153a2c4b2050b68ae
  “有一个老太太向我们保证，说我们永远不会死。我们祈祷：主啊，赐予我们力量，让我们熬过疲惫的生活。”
  #+END_QUOTE

- 616-616, 标注, 2025 年 11 月 19 日星期三 上午 8:26:14
  #+BEGIN_QUOTE md5: f99a0081426a77b154f3c22af7745d35
  世界仍然一样，但是人不一样了。
  #+END_QUOTE

- 648-654, 标注, 2025 年 11 月 19 日星期三 上午 8:38:26
  #+BEGIN_QUOTE md5: f90eb8fbc6a8f7ab78bfc9de1ddcd6de
  真正的经过是：我的爷爷养了五个蜂箱，蜜蜂整整两天没出来，一只都没有，它们在蜂窝里等。我的爷爷不知道发生了爆炸，
  他在院子里跑来跑去，说：“怎么了？发生了什么事？大自然出问题了。”我们的邻居是老师，他说蜜蜂比我们敏锐，
  因为它们听得见。广播什么也没报，报纸什么消息也没有，但是蜜蜂知道，它们过了三天才出来。黄蜂——
  我们家的门廊上有一个黄蜂巢，没有人碰它，可是那天早上黄蜂都不见了，一直到六年后才出现。人怕辐射，动物也怕，
  鸟类和树木也一样，但是它们很安静，它们不说话。这对万物来说都是可怕的浩劫，
  不过科罗拉多甲虫还是像平常一样到处出没，狼吞虎咽地吃我们的马铃薯，吃到只剩叶子，它们习惯毒物，和人一样。
  #+END_QUOTE

- 655-656, 标注, 2025 年 11 月 19 日星期三 上午 8:39:21
  #+BEGIN_QUOTE md5: 104114719c6bd62b5e65f32a07758fde
  每一家好像都有人死。河的另一头的那条街，所有女人都没有男人，男人都死光了。
  我们这条街只剩我的爷爷和另一个男人还活着。上帝为什么先带走男人？没有人知道答案。
  #+END_QUOTE

- 659-659, 标注, 2025 年 11 月 19 日星期三 上午 8:42:17
  #+BEGIN_QUOTE md5: 482145b83ff3270b4e0e02fa8326c38a
  我还能说什么？你总得活下去。
  #+END_QUOTE

- 682-684, 标注, 2025年11月19日星期三 上午8:47:45
  #+BEGIN_QUOTE md5: eea908f29bf0a747aba0fc92ed8f11eb
  只要告诉我们她的地址，告诉我们她在哪里生活，在哪里受苦，我们就可以接她回来，那样她才不会悲伤至死。我求求你，
  无辜的灵魂在陌生的地方受苦……
  #+END_QUOTE
