:PROPERTIES:
:ID:       332e063f-3c1d-40ed-9d67-85612fa6957c
:END:
#+TITLE: 莫言短篇小说精品系列
#+AUTHOR: Yang,Ying-chao
#+DATE:   2025-05-07
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:  oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :moyanduanpia:note:ireader:unwashed:

* Unwashed Entries                                                  :noexport:

- 47-48, 标注, 2025 年 4 月 21 日星期一 下午 10:27:58
  #+BEGIN_QUOTE md5: 8e020272fccb315ac4aeb0fe0794d9e0
  正是农历的九月初头，正是九月初头的一个标准的秋夜，正是一个标准的秋夜的半夜时分，肃杀的秋气虽不说冷得厉害，
  但也尽够人受的。
  #+END_QUOTE

- 52-53, 标注, 2025 年 4 月 21 日星期一 下午 10:29:23
  #+BEGIN_QUOTE md5: fbf5500cd3aa2c929428de44d7b2be69
  她的前前后后都闪烁着车老板挂在辕杆上的风雨灯发出的昏黄的光亮，骡马驴牛都在吃着草料，一片窸窸窣窣的声响，
  使这冰凉的秋夜显得更加漫长和不可捉摸。
  #+END_QUOTE

- 54-55, 标注, 2025 年 4 月 21 日星期一 下午 10:30:27
  #+BEGIN_QUOTE md5: 65810951397ac3a86ed38a859c3bb7fa
  时间仿佛凝固了，黑夜仿佛永远走不到尽头似的，杜秋妹仿佛等了几年似的。但夜色依然是那么厚重沉郁，
  绝没有半点曦光出现。
  #+END_QUOTE

- 57-61, 标注, 2025 年 4 月 21 日星期一 下午 10:32:22
  #+BEGIN_QUOTE md5: f2f444f2fcb5d08e5801f748748ce883
  这时，天忽然格外黑起来，暗蓝的天幕变成黝黑。天幕上寒星点点，空气冰冷潮湿。一会儿，黑暗渐渐褪去，天色也变淡了，
  天空也变高了。半边天空是海水般的深蓝，半边天空是鸭蛋壳般的淡青。不久，星星隐去了，
  东边地平线下仿佛燃起了一堆大火，把半个天空又染成橘红色，几条呈辐射状的长云则一直伸展到西半边天空，
  像几支横扫长天的巨笔。太阳虽然还没出来，但天已经亮了。
  #+END_QUOTE

- 64-66, 标注, 2025 年 4 月 21 日星期一 下午 10:33:47
  #+BEGIN_QUOTE md5: 9dcba1b582cb06ba86cb3883db952487
  太阳升起来了，通红的光线照耀着落在大地上的、车辆上的以及杜秋妹头上的那层薄薄的白霜，
  一切都反射出令人感到温暖的红色光辉，连杜秋妹周围的人和骡马驴牛嘴里喷出的热气也带着迷人的色彩。
  #+END_QUOTE

- 75-76, 标注, 2025 年 4 月 21 日星期一 下午 10:36:12
  #+BEGIN_QUOTE md5: e99e79443062144a28fef27fd20c8052
  他的脸平常得像一块方方正正的砖坯，浑身上下都好像带棱带角。
  #+END_QUOTE

- 177-179, 标注, 2025 年 4 月 29 日星期二 下午 10:00:40
  #+BEGIN_QUOTE md5: 8963b7b8d622a6e84e0a80ca0dd37c96
  东北风愈刮愈大，风里夹杂着潮气和泥土腥味，马路两旁收获后的庄稼地袒露着胸膛，苍茫辽远，
  风刮着焦干的豆叶在道沟里滚动，唰啦唰啦响个不停。
  #+END_QUOTE

- 197-200, 标注, 2025 年 4 月 29 日星期二 下午 10:05:48
  #+BEGIN_QUOTE md5: a0caa0ff7a81b25d52d59a349d38bac4
  大家都抬头看天，天果然有些不妙，风利飕有劲，潮气很重，东北方向的天空像有千军万马在集结待命，乌压压，黑沉沉，
  仿佛只要一声令下，就会冲过来，就会遮天盖地。没有被阴云吞噬的晴空中，还有几个星星在发抖；
  西边林梢上那一勾细眉般的新月，也好像在打着哆嗦。一会儿，神使鬼差似的，就在东北方向遥远的地方，
  一道贼亮的闪电划开了夜幕，很久，才响起了一阵沉闷的雷声。
  #+END_QUOTE

- 209-215, 标注, 2025 年 4 月 29 日星期二 下午 10:09:02
  #+BEGIN_QUOTE md5: 8de85e8df98a60dc554ccb65b98f71d6
  人无处躲藏，就一齐坐在马车上，静候着雷雨的到来。车把式的风雨灯熬干了油，不死不活地跳动了几下，熄灭了。
  风也突然停了。一只雨信鸟尖叫着从空中掠过，翅膀扇动的声音都听得清清楚楚。原先一直低唱浅吟的秋虫也歇了歌喉。
  一切都仿佛在耐心地等待；一切都仿佛进入了超生脱死的涅槃境界。就这样不知呆了多长时间，突然，一种窸窸窣窣、
  呼呼噜噜、轰轰隆隆的声音从东北方向滚滚而来，一时间天地之间仿佛有无数只春蚕在野咬桑叶，无数只家猫在打着鼾，
  无数匹野马掠过原野。紧接着，一直在东北方横劈竖砍的闪电亮到了头顶，震耳的雷声也在人们耳边响起。顷刻之间，
  风声大作，风里夹杂着稀疏但极有力的雨点横扫下来，像鞭子一样抽打着人的颜面。
  #+END_QUOTE

- 236-237, 标注, 2025 年 4 月 29 日星期二 下午 10:12:38
  #+BEGIN_QUOTE md5: 618a2ac66ee4ac2142c8017f13aba888
  她们满腹的感激话一句也说不出，只将一行行热泪挂到冰冷的腮上。
  #+END_QUOTE

- 385-393, 标注, 2025 年 5 月 8 日星期四 下午 10:36:06
  #+BEGIN_QUOTE md5: 6ecdc42b6317c014afa212174e048b17
  八隆河清脆细微的流水声从人们耳畔流过，间或有几只青蛙“嘎嘎”叫几声，然后又是寂静。突然，
  从院子里响起了一种马桑镇居民多少年没听过的声音，这是小瞎子在吹箫！
  那最初吹出的几声像是一个少妇深沉而轻软的叹息，接着，叹息声变成了委婉曲折的呜咽，
  呜咽声像八隆河水与天上的流云一样舒展从容，这声音逐渐低落，仿佛沉入了悲哀的无边大海……忽而，
  凄楚婉转一变又为悲壮苍凉，声音也愈来愈大，仿佛有滔滔洪水奔涌而来，堤上人的感情在音乐的波浪中起伏。这时，
  瘸子方六仰着脸，眼睛似闭非闭；黄眼把头低垂着，“呼哧呼哧”喘着粗气；麻子杜双手捂着眼睛；
  三斜的眼睛睁得比平时大了一倍……箫声愈加苍凉，竟有穿云裂石之声。这声音有力地拨动着最纤细最柔和的人心之弦，
  使人们沉浸在一种迷离恍惚的感觉之中。 箫声停止了，袅袅余音萦回不绝。人们怀着一种甜蜜的惆怅，悄悄地走下堤去，
  消失在小镇的四面八方。
  #+END_QUOTE
