:PROPERTIES:
:ID:       e9754c2f-ddfc-473c-94ac-0ccdc3a975cc
:END:
#+TITLE: 数学的雨伞下
#+AUTHOR: Yang,Ying-chao
#+DATE:   2025-05-07
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:  oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :shuxuedeyusa:note:ireader:unwashed:

- 19-22, 标注, 2025 年 4 月 11 日星期五 下午 1:21:01
  #+BEGIN_QUOTE md5: 5db6a86dd3514783476ec121fadb5047,381c40cec202ceefa6077cbe4f7378c5
  作为成年人，我们不会再落入孩提时代的陷阱。但认为我们从此可以免于其他窥伺在侧的偏见，那就错了。
  我们的直觉会欺骗我们，而我们认为理所当然的事情有时候是错误的。我想，我在自己 35 岁这年可以这么说，从小学开始，
  我在生命中的每一年都会意识到，我对一些事情自以为是的理解是错误的。
  #+END_QUOTE


- 35-35, 标注, 2025 年 4 月 11 日星期五 下午 1:23:40
  #+BEGIN_QUOTE md5: ee0f5005e9de54ff333cad7bfeb576a4
  理解的乐趣会让你为此付出的努力得到千百倍的回报。
  #+END_QUOTE

- 450-452, 标注, 2025 年 4 月 15 日星期二 上午 7:45:55
  #+BEGIN_QUOTE md5: 1eba727da595124606dcfffb2dcbd790
  “切中要点”总会带来一种挖掘出某些深刻而珍贵之物的兴奋感、一种揭开了神秘面纱的兴奋感。
  不变量揭示了将不同先验事物聚集在一起的东西。这是一种共同点，就像隐藏在后台的齿轮，一旦让它露出真容，
  你就会因为了解了事物的运转原理而获得这种既欢欣又从容的满足感。
  #+END_QUOTE


- 482-483, 标注, 2025 年 4 月 15 日星期二 上午 7:48:25
  #+BEGIN_QUOTE md5: 43fea0853fde5e333ac030bc232a63ac
  这是一幢方形建筑，古老的石块上布满岁月的痕迹，几扇窄而深的窗户不规则地镶嵌在上面。锯齿形的屋顶犹如一顶王冠，
  让塔楼在不知曾多少次濒临坍塌的墙壁的掩映下，露出一副自豪而高贵的身姿。
  #+END_QUOTE


- 499-501, 标注, 2025 年 4 月 15 日星期二 上午 7:49:35
  #+BEGIN_QUOTE md5: 8dbcaf7172e1f2dd272822fecbe11ea9
  有时候，你只需要改变视角就能找到解决办法。如果找到了正确的视角，最棘手的情况也会变得易如反掌。
  如果你不如鸽子灵巧，那就让鸽子变得不如你灵巧。解决重大问题并不总是得更聪明、更强大或更迅速。
  最重要的是找到窍门。
  #+END_QUOTE


- 635-636, 标注, 2025 年 4 月 15 日星期二 上午 8:01:00
  #+BEGIN_QUOTE md5: 3861fa71ba4e5115e83aeb2f58e98841
  纽科姆的文章很有启发性，值得我们为它停留片刻。文章的结论很简单：世间的数是均匀分布的，
  而且是从乘法角度来看的均匀分布！
  #+END_QUOTE


- 651-652, 标注, 2025 年 4 月 15 日星期二 上午 8:06:16
  #+BEGIN_QUOTE md5: 329d3468ced83bea48e7b0a76e84be3b
  是的，这个世界青睐乘法，但为什么？为什么现实似乎在所有的情况下都偏爱这种分布呢？
  #+END_QUOTE


- 659-661, 标注, 2025 年 4 月 15 日星期二 上午 8:06:53
  #+BEGIN_QUOTE md5: eb0b25fbbf3382ef029dcf2f8ab7ab8d
  公里和英里都是人类的发明，而大自然并不在乎我们使用哪种计量单位去测量它。从法国或英国的角度去看，
  每一条被分别丈量的河流，其长度不会有相同的首位数字，但如果我们制定出世界上河流长度的完整列表，
  则首位数字的总体分布应当会保持不变。
  #+END_QUOTE


- 669-672, 标注, 2025 年 4 月 15 日星期二 上午 8:07:47
  #+BEGIN_QUOTE md5: 1b051b9e60d895ff5baab63ae47f1f19
  计量单位改变了，乘法的差距不变。因此，在任意数据列表中，我们都会发现介于 1 和 2、2 和 4 或 4 和 8 之间的数比例是相同的。
  所以，我们需要关注的是这种乘法的差距。 这就是为什么世界是乘法的。这就是为什么对数标度如此适切。
  #+END_QUOTE


- 675-679, 标注, 2025 年 4 月 15 日星期二 上午 8:08:41
  #+BEGIN_QUOTE md5: cb40919f0e33cfcbb92480bf22721c8e
  美国经济学家哈尔·瓦里安(Hal Varian)在 1972 年提出用本福特定律来检测舞弊。原理很简单：
  当舞弊者把一份数据列表篡改成利于自己的时候，他们会露出马脚。也就是说，他们伪造的数据会有不同的首位数字分布。
  尤其是，伪造的数据会更频繁地以 5 或 6 开头，这与本福特定律不符。这或许是因为舞弊者倾向于认为，相较于以 1 或 9
  开头的数，一个中等大小的数看起来不会那么可疑，或是更正常。尽管如此，这种偏差仍会导致首位数字中的 5 和 6
  远远多于应有的数量。这种偏差的幅度可以用来估算潜在舞弊者的数量。
  #+END_QUOTE


- 682-684, 标注, 2025 年 4 月 15 日星期二 上午 8:11:43
  #+BEGIN_QUOTE md5: 2a3dcd6446964260e11501fc9fc91fca
  知道各国的人口、世界上的河流或天空中的天体都遵循这一定律，也没有太大用处。“没用处”究竟是好是坏，由你来定夺。
  但是，我们因好奇而踏足的这条道路上充满了惊喜。当然了，出于纯粹的智力挑战，出于体验
  #+END_QUOTE


- 682-686, 标注, 2025 年 4 月 15 日星期二 上午 8:11:58
  #+BEGIN_QUOTE md5: e0d6ab68ac88eccd46a70443bd98ac82,cfac982c0bed573c8505ce506cc42340
  知道各国的人口、世界上的河流或天空中的天体都遵循这一定律，也没有太大用处。“没用处”究竟是好是坏，由你来定夺。
  但是，我们因好奇而踏足的这条道路上充满了惊喜。当然了，出于纯粹的智力挑战，出于体验数学的形式之美，
  出于让我们的思维变得多姿多彩，不带任何期待地去理解一件事，未必不会让人获得极大的满足。然而，
  即便是最无用的事情，有时也会暗藏意料之外的宝藏。可不要低估了这些定理。
  #+END_QUOTE


- 687-688, 标注, 2025 年 4 月 15 日星期二 上午 8:12:14
  #+BEGIN_QUOTE md5: 58e7d9ee037255fb55930fcc92419671
  或许有一天，在你完全没有想到的那一刻，“有用之处”会不期而至。它们会像成熟而甜美的果实那样，
  自然而然地落入你的手中。
  #+END_QUOTE


- 769-772, 标注, 2025 年 4 月 15 日星期二 下午 1:21:41
  #+BEGIN_QUOTE md5: 10ccf27c129823ea3c027e5ca0d23363
  这个时候，最为微妙的时刻或许就来了。这一刻最让人感到不舒服，但也最令人陶醉。那就是超脱的时刻。
  那是当事物变得如此清晰以至于再次变得模糊的时刻。
  那是我们对事物理解得足够多以至于知道自己理解得其实没有那么多的时刻。就像一张漂亮的照片，因为看的时候凑得太近，
  变成了一个个像素块。
  #+END_QUOTE


- 904-905, 标注, 2025 年 4 月 16 日星期三 上午 7:52:37
  #+BEGIN_QUOTE md5: c084c3b04ced838d0487ea63aa2c6b05
  知道如何讨论理想对象而不必知道如何将它们与它们所源自的具体情况相联系，这就是数学的伟大力量。
  #+END_QUOTE


- 926-930, 标注, 2025 年 4 月 16 日星期三 上午 7:54:24
  #+BEGIN_QUOTE md5: d018fb7cfab0c881a1b406520e19552f,ff404e18fd2a2e28a377f70532b8a96f
  这是数学颠覆我们三观的优点之一：可以用不存在的东西去恰当地思考。实际上，
  思考不存在的东西甚至可以说是数学的特性。不存在的东西也就是抽象的东西。 数字显然是最引人注目的例子之一。
  一旦脱离了被它们模型化的现实，数字就成了纯抽象的概念。它们是想法，是我们用作思维中间环节的想象之物。
  #+END_QUOTE


- 947-950, 标注, 2025 年 4 月 16 日星期三 上午 7:55:51
  #+BEGIN_QUOTE md5: 88a5f574e7e37987d3ac324016bc2760,47fcb06f41240d0fff67a405f938e90a

  这种解决问题的模式叫作“雨伞定理”。如果你在雨天想要在不被淋湿的情况下从一个地方前往另一个地方，
  请按照以下步骤操作（图 2.9）： \\
  1. 撑开你的雨伞； \\
  2. 开始你的行程； \\
  3. 收起你的雨伞。

  步骤 =1= 和步骤 =3= 的操作是相反的，如果你能够在雨伞为你打开的特定世界中达成预期的目标，
  那么你在操作结束时就会恢复到开始时的状态。
  #+END_QUOTE


- 957-958, 标注, 2025 年 4 月 16 日星期三 上午 7:56:32
  #+BEGIN_QUOTE md5: 67fe87fd5f150cf46e8cbb4be7fcdb59
  雨伞，是观点的改变，是差异，是从另一个角度看待事物的艺术，一种更适合、更有效的角度。
  #+END_QUOTE


- 958-961, 标注, 2025 年 4 月 16 日星期三 上午 7:56:53
  #+BEGIN_QUOTE md5: 2a6111510044c4e9a388f43976ee6136
  走得更远，并不总是意味着长久而乏味的努力，而是首先要找到解决所面临的问题的正确方法。
  如果我们以正确的方式看待问题，那么最错综复杂的问题也会在一瞬间变得简单明了。伟大的智者能尽显其才，
  首先是因为他们拥有在正确的时间发明正确的雨伞的能力。
  #+END_QUOTE


- 965-967, 标注, 2025 年 4 月 16 日星期三 上午 7:57:56
  #+BEGIN_QUOTE md5: c167da329cda021cce15fa43efe679fb
  不要惧怕与众不同，这就是雨伞的智慧。让我们无所畏惧，既不感到羞耻，也不抱有偏见。
  一旦接受在头顶撑起抽象的雨伞并进入数学的世界，我们就不会再全然依赖现实。
  不必让自己陷在无用的限制或令人尴尬的既有观念之中。
  #+END_QUOTE


- 971-979, 标注, 2025 年 4 月 16 日星期三 上午 7:59:59
  #+BEGIN_QUOTE md5: c04430c3d3a9e752ee37e3a296d94d1e,d20bdd5989a16d82fc9a316eff542e30
  *选择太多，就难以做出选择了。*

  懂得如何在数学世界里自我驾驭，是一种需要实践和直觉的能力。 为此，数学家制造出很多导航工具，其中有两个指南针：
  一个名叫“实用”，一个名叫“优雅”。
  - “实用”引导我们创造出最贴近现实的抽象世界， 在这些抽象世界中进行的研究能够轻松地转化为关于我们宇宙的知识。
  - “优雅”告诉我们要完全抛开现实， 并沉醉在抽象世界的奇观中。那里有许许多多美丽的事情要做——如果一件事是无用的，那它就更美了。

  每个人都能以自己的方式使用这两个指南针。有些人偏爱其中的某一个，有些人则两个一起用，
  并不断在两个指南针指示的方向之间寻找完美的平衡。但世界充满奥秘，因此，
  探索实用之人和探索优雅之人常常会在走过不同的道路之后，在同一个地方不期而遇。
  #+END_QUOTE


- 1207-1210, 标注, 2025 年 4 月 16 日星期三 下午 9:56:59
  #+BEGIN_QUOTE md5: 93bfe71f48201e599fe59a86d67fcfc3
  并不是每一个人都会在初次接触牛顿思想的时候就接受它，而当年既有的理论在《原理》问世近一个世纪后仍然难以被撼动。
  我们应该对那些诋毁引力的学者保持宽容。事后对失败者进行评判，总是很容易，
  但针锋相对的论战绝对是知识进步的必要条件。
  #+END_QUOTE


- 1362-1369, 标注, 2025 年 4 月 17 日星期四 上午 7:50:57
  #+BEGIN_QUOTE md5: 9e15159e17e28dd17d43de8b929d9af6,bf97cd08dc9bc3932b7a1ac7ccdae0f1
  这就是问题的核心所在：细节越小，其数量就越多，而它们的累计长度值却绝不会小。 曼德博的结论毋庸置疑，
  我们越是精确地测量英国的海岸线，其长度就会越长。添加越来越小的细节只会令测量值无限度地增加（图 3.2）。
  如果我们不想做出任何让步，那么这个问题的唯一答案就是：英国的海岸线无限长。 图 3.2
  这个现象在今天被称为理查森效应，或是更常说的海岸线悖论。当一根自然线条沿着大自然划定的路线，比如河流、
  山脊或悬崖蜿蜒而行的时候，这条线就会产生理查森效应。
  #+END_QUOTE


- 1381-1382, 标注, 2025 年 4 月 17 日星期四 上午 7:52:28
  #+BEGIN_QUOTE md5: deb43eea62daf88cc01c4f56065b68ff
  曼德博认为是时候发明一个词语来指称这些既如此美丽又如此神秘的形状了。他把它们称为“分形”。
  #+END_QUOTE


- 1377-1382, 标注, 2025 年 4 月 17 日星期四 上午 7:52:46
  #+BEGIN_QUOTE md5: 2759caf10ecd6022622ef09ddc9e773d
  本华·曼德博的大部分时间专注于研究符合海岸线悖论的形状，也就是那些轮廓尺寸不一且极为零碎的几何形状。
  你想把这些形状放大多少倍都可以，它们永远不会有光滑、笔直的轮廓线。在理查森指出的奇怪现象之上，
  曼德博创建了一种全新的理论，而很多年轻的数学家都将追随后者的脚步。 1974 年，
  也就是在他关于英国海岸线的文章发表七年后，曼德博认为是时候发明一个词语来指称这些既如此美丽又如此神秘的形状了。
  他把它们称为“分形”。
  #+END_QUOTE


- 1442-1445, 标注, 2025 年 4 月 17 日星期四 下午 1:23:52
  #+BEGIN_QUOTE md5: b794c36ccae92ca3c5e67eca5cc8882b
  10100 对应所有这些宇宙加在一起所包含的基本微粒的数量！卡斯纳决定把这个数叫作“古戈尔”(googol)。这个词是他 9
  岁的外甥创造出来的，后来成了企业家谢尔盖·布林(Sergey Brin)和拉里·佩奇(Larry Page)的灵感之源。
  #+END_QUOTE


- 1541-1542, 标注, 2025 年 4 月 17 日星期四 下午 6:50:54
  #+BEGIN_QUOTE md5: 7e77347a979b6454630dcdd85a39d5e1
  面对无穷大，数数没有任何意义。所有的数都很小。它们中的任何一个被单拎出来，
  对所有跟随其后的数来说都是微不足道的。
  #+END_QUOTE


- 1775-1778, 标注, 2025 年 4 月 18 日星期五 上午 7:04:16
  #+BEGIN_QUOTE md5: ce67cad3d7a3313d5bd7f3af8ac771a8
  点，它是最小的几何元素。一个点，就是一个部分，一个空间中的位置。点就是它自己，不能分割成更小的若干块。
  点没有长度、宽度和厚度。我们常常用一个小小的圆来表示一个点，但你必须清楚，对数学世界的绝对性而言，
  这种表示方法是错误的。一个点无限小，因此无法为肉眼所见，也无法单独呈现出来。
  #+END_QUOTE


- 1822-1823, 标注, 2025 年 4 月 18 日星期五 上午 7:07:42
  #+BEGIN_QUOTE md5: 4eea0dee37356261565d2280ce52b201
  朱塞佩·佩亚诺用无限曲线成功地在欧几里得的两类图形之间建立起一种不可能的联系。
  一条一维的线可以卷曲成一个二维的正方形。
  #+END_QUOTE


- 1823-1823, 笔记, 2025 年 4 月 18 日星期五 上午 7:08:15
  #+BEGIN_QUOTE md5: 5bee7087a56a6b9bc5d561efe3179a9c
  降维展开,三体
  #+END_QUOTE


- 1942-1942, 标注, 2025 年 4 月 18 日星期五 上午 7:15:56
  #+BEGIN_QUOTE md5: b64126fc73e0b50eb0543d8cdd29c817
  维度，是倍增系数的对数。
  #+END_QUOTE


- 1986-1990, 标注, 2025 年 4 月 18 日星期五 上午 7:25:32
  #+BEGIN_QUOTE md5: 764f96c43e807ace93e9a61ee2090d29
  但本华·曼德博的观点却与这一立场完全相反：对他来说，与现实脱节的是欧几里得的几何学。山峦不是锥体，
  树木不是球体，河流不是直线。在现实中，一切都是被切割的、剁碎的、撕裂的、细碎的、揉皱的、凹凸不平的。
  粗糙才是常态，平滑只是例外。就连地球也不是溜圆的，而是布满了高低起伏的峡谷和山峰。大自然是分形的！
  这就是曼德博的主张。
  #+END_QUOTE


- 2365-2365, 标注, 2025 年 4 月 21 日星期一 下午 9:39:22
  #+BEGIN_QUOTE md5: ae2f06852b1c10adeee81615d771d106
  思考，是忘记差异，是概括、抽象。
  #+END_QUOTE


- 2384-2389, 标注, 2025 年 4 月 21 日星期一 下午 9:41:08
  #+BEGIN_QUOTE md5: 93d440d89d9de691941fb2a191bb515c
  在亚里士多德的众多著作中，我们可以特别关注一下《工具论》(Organon)。这是一本论述推理和逻辑艺术的文集，
  尤其阐述了从假设中得出结论的不同规则。这些规则被称为“三段论”。以下是最著名的三段论之一： 凡人皆有一死；
  希腊人都是人； 因此，希腊人皆有一死。
  #+END_QUOTE


- 2991-2992, 标注, 2025 年 4 月 28 日星期一 下午 10:07:03
  #+BEGIN_QUOTE md5: 177494af56e63d087060ace102a84a2d,d41717ff529bf26ac70b4b892603d150
  爱因斯坦的理论可以用一种简单而优雅的方式来表述了。就像引力理论所说的：“万物落在万物之上，一刻不停。”
  相对论现在也可以说：“万物以光速前进，一刻不停。”

  我们就以你为例。当你读到这几行文字的时候，你就正在时空中移动。即使你在空间中是静止的，
  你在时间中也必然是移动的。你目前正在朝着未来的方向移动。
  #+END_QUOTE


- 3254-3256, 标注, 2025 年 5 月 6 日星期二 上午 8:11:54
  #+BEGIN_QUOTE md5: 6a25826156eaada11c924d902f0d5d11
  爱因斯坦的想法往往相当激进。这位德国物理学家不是一个喜欢修补蹩脚理论的人。在出现问题时，他就将一切夷为平地，
  以便重建其他东西。就像光速的问题，爱因斯坦将通过改变几何来彻底改变引力。
  #+END_QUOTE


- 3277-3280, 标注, 2025 年 5 月 6 日星期二 上午 8:15:11
  #+BEGIN_QUOTE md5: 9325f9e4e750d01219012d4c040f0950
  这就是广义相对论的第一个重大启示：在爱因斯坦的几何中，行星不旋转，而是沿直线运动！这篇论文既绝妙又优雅。
  对于爱因斯坦而言，一切都在直线上运动，一刻不停。物体之间没有相互吸引，它们之间没有丝毫吸引力！
  一切都只是在继续前进，既没有改变速度，也没有改变方向。行星沿直线围绕太阳旋转。月球沿直线围绕地球旋转。
  苹果沿直线掉落在地上。
  #+END_QUOTE

- 3391-3398, 标注, 2025 年 5 月 6 日星期二 上午 8:30:38
  #+BEGIN_QUOTE md5: 3b7223c563cde0b8898c33f946f3ebd1,b23ca9937995b5df93d4c0b01093da2d
  爱因斯坦环。其原理类似于 1919 年日食的原理，但推向了极致。想象一下，一个天体的质量如此之大，
  以至于它偏转的光线足以同时从两侧到达我们这里（图 5.27）。 图 5.27 向下的光线向上偏转，向上的光线向下偏转，
  因此两者都到达了同一个位置。情况甚至更甚，因为我们必须把上图想象成三维的。从地球上看，
  这意味着我们可以多次看到同一颗星星，它的光从四面八方围绕着中心天体朝我们而来！换句话说，我们看到的是一个环（
  #+END_QUOTE


- 3442-3444, 标注, 2025 年 5 月 6 日星期二 上午 8:36:21
  #+BEGIN_QUOTE md5: d334d1248ba78b8c13c412210a1b657c
  这种时间的膨胀在黑洞附近达到了极致。黑洞的质量如此之大，以至于在你接近它们时就会出现一个无限变慢的界线。
  这个界线是黑洞周围的一片区域，我们称之为事件视界。如果你接近并越过事件视界，
  那么无限的时间在你看来就会是有限的。
  #+END_QUOTE


- 3486-3493, 标注, 2025 年 5 月 6 日星期二 下午 6:48:28
  #+BEGIN_QUOTE md5: 88aca49d18bfca2ea55d26928b22a733
  从收集到的数据可以推断出，距离地球超过 10 万亿千米的两个黑洞在被天文学家称为麦哲伦云的某个地方融合。事实上，
  这一碰撞在很久以前就已发生。引力波以光速传播，花了十多亿年才到达我们这里。
  振动的幅度和形状让我们得以计算出这两个黑洞在融合前的质量分别为 36 个和 29 个太阳质量。
  由此产生的单个黑洞的质量相当于 62 个太阳质量。你可能已经注意到，36+29 并不等于 62。少了的那 3 个太阳质量去哪儿了？
  根据方程，它们转化成了能量！这 3 个蒸发掉的太阳质量提供了足够的能量来形成强大的引力波，
  好让这些引力波能够穿越十多亿年来到我们的地球，并让我们得以在地球上探测到它们。
  #+END_QUOTE

- 3513-3515, 标注, 2025 年 5 月 6 日星期二 下午 6:50:19
  #+BEGIN_QUOTE md5: 82f7beea29adc539a7192b6f97743305
  让我们保持耐心和好奇心，让我们慢慢品味无知的快乐，让我们不带愧疚地享受欺骗人的感官，适应有时会对人撒谎，
  有时会在黑暗中投下几束火花的大脑。时间，如果它存在的话，也许会回答那些我们从未问过自己的问题。
  #+END_QUOTE

* Unwashed Entries                                                  :noexport:
