:PROPERTIES:
:ID:       d4f8cb6d-ad99-4a4e-8b87-d9fc2d1cfef8
:END:
#+TITLE: [笔记]静静的顿河-[苏] 肖洛霍夫;金人
#+AUTHOR: Yang Yingchao
#+DATE:   2024-10-31
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:  align nodlcheck oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+LANGUAGE: en
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :jingjingdedu:note:ireader:

- 1524-1526, 标注, 2024 年 10 月 28 日星期一 上午 7:57:33
  # note_md5: a82eff86989bfaad909af44253eff2bb
  #+BEGIN_QUOTE
  风吹日晒、疲惫不堪的土地散发着尘埃和太阳的气味。风沙沙地响着，翻动着向日葵的绿叶子。一堆棉絮似的白云遮住了太阳，
  天突然昏暗了，于是烟雾般的云影落到了草原上，村落上，落到了阿克西妮亚的低垂着的脑袋上，落到了菟丝的粉红色花萼上，
  然后又盘旋、翻滚飘逝。
  #+END_QUOTE

- 1543-1544, 标注, 2024 年 10 月 28 日星期一 上午 7:59:18
  # note_md5: 0134061ae7cb0f9d282bf05b762a4d2b
  #+BEGIN_QUOTE
  粘土地上和山坡上一片金黄，小麦叶子被太阳晒得都卷起来了，生命已经告终的麦茎也干枯了。
  #+END_QUOTE

- 1817-1820, 标注, 2024 年 10 月 28 日星期一 下午 1:29:42
  # note_md5: 7cefc9601ec3d7f807dc21c3ed7f134e
  #+BEGIN_QUOTE
  小麦长出了尖尖的绿芽儿，天天见长；一个半月以后，连乌鸦的脑袋都能藏进去了，麦子吮吸着土壤里的养料，抽了穗；然后
  开花，麦穗罩上了一层金黄的花粉；麦粒灌满了香喷喷、甜丝丝的乳浆。当家人来到麦地里一看，真是心花怒放，可是突然不
  知道从什么地方闯来一群牲口，在麦地里乱踩一阵：可怜那沉甸甸的麦穗全被踩烂在田垄上。凡是牲口践踏过的地方，到处是
  一片片踩坏了的麦子……
  #+END_QUOTE

- 1826-1828, 标注, 2024 年 10 月 28 日星期一 下午 1:30:20
  # note_md5: 62f2c24861d1d857d3d763522441fca3
  #+BEGIN_QUOTE
  被牲口踩倒的麦子又立起来了。雨露阳光，使踩倒在地上的麦茎又挺立起来；起初，就像一个被不能胜任的重负压得弯着身子
  的人一样，后来就挺直身子，抬起头来，白昼又照样照耀着它，风又照样吹得它摇曳多姿了……
  #+END_QUOTE

- 1898-1898, 标注, 2024 年 10 月 28 日星期一 下午 6:32:56
  # note_md5: 38fdc7a220dc511e9fef9c6fea425535
  #+BEGIN_QUOTE
  在头发上擦着油手。
  #+END_QUOTE

- 1898-1898, 笔记, 2024 年 10 月 28 日星期一 下午 6:33:16
  # note_md5: 457776e2760fa3f585b19d49d9de189a
  #+BEGIN_QUOTE
  想起我奶奶了,
  #+END_QUOTE

- 2681-2684, 标注, 2024 年 10 月 28 日星期一 下午 10:23:29
  # note_md5: 218c0f38dd768ed367270b0214bd6e22
  #+BEGIN_QUOTE
  严寒袭来，下了一场大雪；一天比一天冷得厉害，接着又下了两俄寸半厚的雪，顿河边上的菜园子里，野兔越过顶上被大雪覆
  盖着的篱笆，留下一圈圈梅花形的趾印，宛如姑娘衣服上的花边。烧牛粪的烟雾笼罩在村庄的上空，飞集到有人烟的地方来的
  乌鸦，在路旁的灰堆里徘徊觅食。爬犁压出来的冬季道路，像一条褪了色的灰带子，蜿蜒在村中。
  #+END_QUOTE

- 2971-2973, 标注, 2024 年 10 月 29 日星期二 下午 12:35:43
  # note_md5: fbfa4ace1ccdb751ea137ba2a5c549d5
  #+BEGIN_QUOTE
  在维申斯克对面，顿河像鞑靼人的弓囊似的弯成弧形，仿佛要向右转去，可是到巴兹基村附近，却又雄伟浩荡地笔直流去，闪
  着蓝光的淡绿色河水，流过右岸的白垩山崖、接连不断的村庄和左岸的稀疏的集镇，奔向大海，奔向蓝色的亚速海。
  #+END_QUOTE

- 3090-3092, 标注, 2024 年 10 月 29 日星期二 下午 12:43:14
  # note_md5: 4def15d0615566b113393fdd88333225
  #+BEGIN_QUOTE
  傍晚，葛利高里坐在风磨的旁边，在袖口里抽着烟。寒风在风车后面枯干的玉米秸中间冲撞，呼号。系在风车轮翼上的一块破
  布片在啪啦啪啦地响。葛利高里觉得好像是一只飞不动的大鸟拍打着翅膀，在他头顶盘旋。
  #+END_QUOTE

- 3090-3095, 标注, 2024 年 10 月 29 日星期二 下午 12:43:40
  # note_md5: fb7247e29762baddc8689905af9e2f35
  #+BEGIN_QUOTE
  傍晚，葛利高里坐在风磨的旁边，在袖口里抽着烟。寒风在风车后面枯干的玉米秸中间冲撞，呼号。系在风车轮翼上的一块破
  布片在啪啦啪啦地响。葛利高里觉得好像是一只飞不动的大鸟拍打着翅膀，在他头顶盘旋。阿克西妮亚还没有来。西面的半边
  天，是一片淡紫色的晚霞和金黄的夕照。从东方吹来越来越紧的刺骨寒风，黑夜追逐着挂在柳树梢上的月亮，铺天盖地袭来。
  风车顶上，红黄色的、有蓝色斑纹的夜空，像僵尸一样的阴沉；村庄上空还回荡着白昼忙碌生活喧嚣的余音。
  #+END_QUOTE

- 3092-3095, 标注, 2024 年 10 月 29 日星期二 下午 12:43:42
  # note_md5: 7a2e94cf462b00b4bf4181190d9a8c90
  #+BEGIN_QUOTE
  地响。葛利高里觉得好像是一只飞不动的大鸟拍打着翅膀，在他头顶盘旋。阿克西妮亚还没有来。西面的半边天，是一片淡紫
  色的晚霞和金黄的夕照。从东方吹来越来越紧的刺骨寒风，黑夜追逐着挂在柳树梢上的月亮，铺天盖地袭来。风车顶上，红黄
  色的、有蓝色斑纹的夜空，像僵尸一样的阴沉；村庄上空还回荡着白昼忙碌生活喧嚣的余音。
  #+END_QUOTE

- 3414-3414, 标注, 2024 年 10 月 29 日星期二 下午 6:33:30
  # note_md5: 9fbc2b6e9d4260d76905034a32c1b910
  #+BEGIN_QUOTE
  Крепыш）
  #+END_QUOTE

- 4262-4266, 标注, 2024 年 10 月 30 日星期三 上午 7:42:12
  # note_md5: 32014c6ce3580a5198134d09a320d2fa
  #+BEGIN_QUOTE
  一个干旱的夏天。村边顿河的水变浅了，那片从前是急流奔腾的地方，现在变成了浅滩，牛走到对岸去，连脊背都湿不了。夜
  里，沉闷的暑热从山岗上吹到村子里来，风把晒焦的草香味吹散到空中。牧场上的干蓬蒿在燃烧，甜藜像一层看不见的薄幕挂
  在顿河岸上。一到夜间，顿河对岸的天上就布满了黑云，雷声单调地、隆隆地响着，但是连一个雨点也没有落到炎热煎烤的大
  地上，电光在空中闪个不停，夜空被划成一些带尖角的蓝色块块。
  #+END_QUOTE

- 5048-5052, 标注, 2024 年 10 月 30 日星期三 下午 6:44:26
  # note_md5: 71407e7a47c5c772459dcba0561fa175
  #+BEGIN_QUOTE
  整齐的队列前一片窸窣声，宛如飘忽吹过成熟了的大麦田的风声。一阵阵刺耳的马嘶声。一双双睁圆的眼睛和张着的、黑洞洞
  的嘴都转向一连那边；那里的左翼上有一匹马在长嘶。 上校又讲了些话。他在斟酌字句，想激起人们的民族自豪感。可惜此
  时此刻呈现在成千的哥萨克眼前的，并不是沙沙响着倒在脚下的敌人的旗帜，而是他们日常的、熟悉的生活；大声呼叫哀号的
  老婆、孩子、情人；没有收完的庄稼，荒凉的村庄、市镇……
  #+END_QUOTE

- 5707-5708, 标注, 2024 年 10 月 31 日星期四 上午 7:46:18
  # note_md5: 2bcc33ecd3083485c6e10ee986d3c619
  #+BEGIN_QUOTE
  离他们有十步远的地方，一片没有收割、麦粒已经脱落的黑麦在随风翻滚。被风吹空的麦穗弯下头，在悲伤地沙沙哭泣。
  #+END_QUOTE

- 5783-5787, 标注, 2024 年 10 月 31 日星期四 上午 7:52:53
  # note_md5: 797a3dcfac296015d9f25c3d096f2032
  #+BEGIN_QUOTE
  哥萨克们默默地走到连队宿营的地方。暮色已深。微风从西方吹来卷层的黑云。从什么地方的沼泽地里吹来一阵阵淡淡的污泥
  和烂草的潮湿气味。鹭鸶咕咕叫着。马具的叮当声、马刀偶尔撞碰马镫的响声和马蹄踏着地上的松针发出的沙沙声划破了睡梦
  般的寂静。林中小路的上空，松树枝干上的夕阳余晖渐渐黯淡下来。“锅圈儿”不住地在吸烟。忽明忽暗的火光照亮了他那紧紧
  夹着卷烟、长着鼓起的黑指甲的大粗指头。 黑云在树林上空飘动，使大地无比忧郁的苍茫暮色更加幽暗、浓重。
  #+END_QUOTE
