:PROPERTIES:
:ID:       849c6a30-5847-4c8e-96fd-b2990d127696
:END:
#+TITLE: [笔记]包法利夫人-N/A
#+AUTHOR: Yang Yingchao
#+DATE:   2024-10-09
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:   oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+LANGUAGE: en
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :baofalifuren:clip:

- 503-607, 标注, unknown
  # note_md5: e97f5841ef6ef2d38071070dafc838ca
  #+BEGIN_QUOTE
  福楼拜不是一般意义上的小说家，他自称，他也确实是艺术家，文字的艺术家。他视文字、文学创作为生命，每一部作品，每
  一章，每一 节，每一句，都是呕心沥血的结果。
  #+END_QUOTE

- 654-785, 标注, unknown
  # note_md5: ab1a106d4dc1f7302ab003d69e7452af
  #+BEGIN_QUOTE
  小说的形式和风格比其内容更加重要。他写得很慢，很苦，反复修改，要求每一个细节都来自仔细的观察或亲身体验，要求文
  字具有音乐 的节奏。（“一句好的散文应该同一句好诗一样，是不可改动的，是同样有节奏，同样响亮的。”
  #+END_QUOTE

- 832-1148, 标注, unknown
  # note_md5: cc34115d73fe278e349adbf959207c43
  #+BEGIN_QUOTE
  城像圆剧场，一步比一步低，雾气笼罩，直到过了桥，才乱纷纷展开。再过去又是旷野，形象单调，越远越高，最后碰上灰天
  的模糊的基线。全部风景，这样从高望去，平平静静，像煞一幅画。停锚的船只，堆在一个角落；河顺着绿岭弯来弯去；长
  方形的岛屿，如同几条大 黑鱼，停在水面，一动不动。工厂的烟筒冒出大团棕色的烟，随风飘散。教堂的尖顶突破浓雾，清
  越的钟声有冶铸厂的轰隆轰隆的响声伴 奏。马路的枯树，站在房屋中间，好像成堆的紫色荆棘一样。雨洗过的屋顶，由于市
  区有高有低，光色参差不齐。有时候，吹来一阵劲风，浮云漂向圣·卡特琳岭，仿佛空气凝成波涛，冲击岸边绝崖，先是气势
  汹汹，转瞬就又销声匿迹了。
  #+END_QUOTE

- 1204-1329, 标注, unknown
  # note_md5: 7bf32da03b528e03e3ea7e110a18f941
  #+BEGIN_QUOTE
  他什么也不懂；上课像腾云驾雾，听了也白听。但他还是很用功，一本本笔记装订成册，一堂课也不缺席，一次出诊也不拉下。
  他当天的 事当天了，却好似一匹拉磨的马，蒙住双眼绕着碾磨转圈，不知道磨的是什么东西。
  #+END_QUOTE

- 1385-1495, 标注, unknown
  # note_md5: b56b31b58f9a9131ce45a34c5ba492e6
  #+BEGIN_QUOTE
  夏尔对爱玛的恩爱，在她眼里就是对她的母爱的辜负，就是对她的尊严的亵渎；她闷不作声地看着儿子日子过得挺和美，犹如
  破了产的人 呆在窗口，瞧着人家在自己的老屋里围坐着吃饭。
  #+END_QUOTE

- 1551-1706, 标注, unknown
  # note_md5: a707471a0b3d0b31e653d7c13abcd96f
  #+BEGIN_QUOTE
  屋顶的茅草往下垂，犹如皮帽翻下盖住眼睛，把低矮的窗户遮去近三分之一，窗玻璃厚厚的，中间凸起，就像酒瓶底儿。石灰
  墙面上，沿 斜角嵌着一根根黑色明梁，不时还有细瘦的梨树攀在上面，底层房门外加了扇矮矮的木栅门，小鸡能到门口啄食
  苹果酒泡过的面包屑，却 进不了屋子。
  #+END_QUOTE

- 1762-1985, 标注, unknown
  # note_md5: 292e5372036f757d7ae2b78fb62687d4
  #+BEGIN_QUOTE
  他俩沿着河岸走回永镇。一到夏季，陡峭的河岸就变宽了，看得见花园围墙的脚跟，沿墙有石阶通到水边。河水悄没声儿地流
  过，乍看上 去湍急而清凉；纤长的水草顺流偃伏，宛如随手扔在河里的绿发，平摊在清澈的水面上。灯心草的尖端或睡莲的
  叶片上，不时有个细脚伶 仃的虫子爬过或小憩。一绺绺阳光穿过水波泛起的气泡，蓝莹莹的小气泡一路躜赶一路迸碎。修过
  枝的老柳树在水中映出灰蒙蒙的倒影； 放眼望去，原野显得分外空旷
  #+END_QUOTE

- 2041-2136, 标注, unknown
  # note_md5: 30402c6a990b373472a94c833b9ad238
  #+BEGIN_QUOTE
  她那么忧郁，又那么宁静，那么动人，那么矜持，在她身边会让人感到一种玉洁冰清的美，犹如置身于教堂之中，透着大理石
  寒意的花香 叫人嗅着打颤。
  #+END_QUOTE

- 2192-2434, 标注, unknown
  # note_md5: 5e9639f8fad1a1ceab94460e8c9da3ab
  #+BEGIN_QUOTE
  正是四月初的天气，报春花绽开了蓓蕾；一阵和风拂过拾掇过的花圃，各家的花园就像女眷一样，仿佛都披上了盛装来迎接夏
  天的节日。 透过棚架眺望四周，只见原野上的那条河，若隐若现，一路迤逦在草地上勾勒出它的身影。暮霭弥漫在没有叶片
  的杨树枝丫之间，给它们 的轮廓染上朦朦胧胧的紫色，即便给枝丫装点上一层薄纱，也不会比这更淡雅、更透明。远处，成
  群的牲畜在行走；既听不见它们的脚步 声，也听不见它们的叫声；而教堂的钟声依然在回荡，显得柔和而凄婉。
  #+END_QUOTE

- 2481-2658, 标注, unknown
  # note_md5: 5e361015bd68ba15ebef20e518ecbe65
  #+BEGIN_QUOTE
  从钟楼垂下的粗绳，直拖到地面，随着粗绳振幅的减小，钟声也渐渐变弱了。嘤嘤而鸣的燕群，骤然划破天空，急速飞回檐瓦
  下棕黄的窝 巢。教堂深处，亮着一盏灯，也就是说有根细细的灯芯，在悬空的玻璃罩里发出黯淡的光。远远望去，亮光如豆，
  在灯油上方颤悠。一绺 长长的阳光射进整座中殿，那些侧道和墙角就显得更加昏暗了。
  #+END_QUOTE

- 2705-2760, 标注, unknown
  # note_md5: cb1b9c5885d7ade48199623abae57eb9
  #+BEGIN_QUOTE
  圣保罗在传道时说：“我们进入神的国，必须经历许多艰难。”
  #+END_QUOTE

- 2816-2983, 标注, unknown
  # note_md5: 9938cb33f17942b322b5aaa8e6c9e4ab
  #+BEGIN_QUOTE
  周围的一切仿佛都笼罩着凄迷的雾气，它隐隐绰绰地在物件的外表上浮动；悲伤涌进她的心扉，带着哀怨的呻吟，有如冬天的
  风吹进废弃 的城堡。那是一种对逝去的时光怅然的梦寻，是在某事无可挽回地有了结局时感到的疲惫，总之，这就是习惯的
  节律一旦中断、持续的震 颤一旦停止时，您所会感到的那种痛苦。
  #+END_QUOTE

- 3039-3375, 标注, unknown
  # note_md5: 204db784f05b632731889146ee8f21f6
  #+BEGIN_QUOTE
  她手里拿着这张糙纸，冥想了几分钟。信上拼写错误比比皆是，可爱玛感受得到那份拳拳的爱心，从字里行间流露出来，犹如
  母鸡在棘篱 后面探出身来咕咕地叫。信纸用炉灰吸过墨水，有些灰色粉末从纸上滑到她的裙上，她眼前浮现出父亲朝炉膛弯
  下身去拿火钳的情景。当 年待在他身边，坐在壁炉跟前的矮凳上，炉膛里芦苇劈劈啪啪烧得正旺，她拿根细棍搁进去看它烧，
  这些都是那么遥远的事了！......她 回想起那些红霞满天的夏日傍晚。小马驹一见旁边有人走过，就欢快地嘶鸣，奔到东，
  奔到西......她的窗前有个蜂箱，蜜蜂在阳光中嗡 嗡飞舞，有时猛不丁撞到玻璃窗上，像颗金色的弹子似的弹回去。那时候
  多么幸福！多么自由！那是满怀希望、沉湎在幻想中的年月！
  #+END_QUOTE

- 3432-3507, 标注, unknown
  # note_md5: ba82863b7a84764b990e1f059204a966
  #+BEGIN_QUOTE
  他的脑子里乱纷纷地闪过种种假设，思绪在这些假设上颠簸晃荡，犹如一只空桶在海上随波逐流，翻来滚去。
  #+END_QUOTE

- 3564-3781, 标注, unknown
  # note_md5: 5c033c4fb05b46dc21d82d8077a1bf2e
  #+BEGIN_QUOTE
  一轮浑圆的月亮，红嫣嫣的，从草场尽头的地面上升起。它在杨树枝丫间迅速上行，不时被密枝繁叶所遮蔽，宛如在一幅剜了
  好些洞的黑 色幕布后穿过。随后它又现了出来，显得分外皎洁，把一片清辉洒向寥廓的天空；而后，它冉冉穿行在夜空，圆
  圆的光影投射在河面上， 变成无数波光粼粼的小星星，银辉宛似披满闪亮鳞片的水蛇，蜿蜒迤逦钻向河底。这又像一盏巨大
  的枝形烛台，千万滴熔化的钻石连绵不 断地往下流淌。
  #+END_QUOTE

- 3838-3920, 标注, unknown
  # note_md5: d554bc33f88706794acb303f6eab28b9
  #+BEGIN_QUOTE
  凄哀的歌声，在低音提琴的伴奏下拖着长腔，犹如海难幸存者在风雨交加、波涛汹涌的海面上的哀号，占据了爱玛的全部身心
  #+END_QUOTE

- 3977-4122, 标注, unknown
  # note_md5: b99e5dae4d1e664beeea926c27f33775
  #+BEGIN_QUOTE
  说来奇怪，包法利虽说不停地思念着爱玛，她的形象居然却想不起来了；他绝望地感到这个形象在从他的记忆中逸出，他拼命
  想留也留不 住。但他每夜都梦见她；总是同样的梦：他离她愈来愈近；可就在他要抱紧她的当口，她从他的怀里跌落下去，
  犹如化成了齑粉。
  #+END_QUOTE
