:PROPERTIES:
:ID:       c7c52086-6496-4c2e-a1cd-4c49f413ad58
:END:
#+TITLE: [笔记]世界秩序-[美]亨利·基辛格
#+AUTHOR: Yang Yingchao
#+DATE:   2024-10-09
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:   oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+LANGUAGE: en
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :shijiezhixu:clip:

- 5-6, 标注, 2022 年 3 月 28 日星期一 下午 9:04:34
  # note_md5: 02b57c07992b925df41c63756f6a9546
  # note_md5: e87222234c38e7569633b0f076b50e23
  # note_md5: 1ee31b2fbe6b2e52a4e03fe0b71845e3
  #+BEGIN_QUOTE
  杜鲁门总统深知美国拥有巨大的实力，但最令他感到骄傲的是这一实力所包含的人道和民主价值。他更希望后人铭记他是因为
  美国与敌人实现了和解，而不是战胜了敌人。
  #+END_QUOTE

- 66-68, 标注, 2022 年 3 月 28 日星期一 下午 9:42:06
  # note_md5: 416ed7c525ee732b53335135f78e0dbd
  #+BEGIN_QUOTE
  他们要建立一座“山巅之城”，运用其正义的原则和榜样的力量激励整个世界。美国人的世界秩序观认为，一旦其他民族像美国
  人一样获得了自治权，和平与均势就会自然降临，昔日的宿敌也会捐弃前嫌
  #+END_QUOTE

- 66-69, 标注, 2022 年 3 月 28 日星期一 下午 9:43:08
  # note_md5: 8f6aa2b28ac0f168df7ca9b1cbcbf8cc
  #+BEGIN_QUOTE
  他们要建立一座“山巅之城”，运用其正义的原则和榜样的力量激励整个世界。美国人的世界秩序观认为，一旦其他民族像美国
  人一样获得了自治权，和平与均势就会自然降临，昔日的宿敌也会捐弃前嫌。因此，外交政策的任务不是追求美国特有的利益，
  而是培育共同的原则。
  #+END_QUOTE

- 90-93, 标注, 2022 年 3 月 28 日星期一 下午 9:56:04
  # note_md5: e18f3a6f889ca451e00040c79b82c9b1
  #+BEGIN_QUOTE
  美国仍然坚持认为，它信奉的价值观在建立一个和平的世界秩序方面具有普遍适用性，并保留在全球范围内捍卫这些价值观的
  权利。然而，在两代人的时间里从三场战争中抽身后——每一场战争都始于理想主义愿望并得到公众的广泛支持，但都以国家蒙
  受创伤而告
  #+END_QUOTE

- 97-98, 标注, 2022 年 3 月 28 日星期一 下午 10:09:40
  # note_md5: e56bf9d0c91dab22e896bc225fc1c36f
  #+BEGIN_QUOTE
  须采取一种既尊重人类社会异彩纷呈的特点，又尊重人与生俱来对自由的渴望的做法。建立此种意义上的秩序必须靠长期培育，
  而不能强加于人
  #+END_QUOTE

- 135-135, 标注, 2022 年 3 月 29 日星期二 下午 12:48:06
  # note_md5: ee39732de926f227d58e297b121c7dc7
  # note_md5: 7033616cbd70b5716a017dfb5e36d6e2
  #+BEGIN_QUOTE
  秩序源自平衡，自我认同感源自对大一统的抵抗。
  #+END_QUOTE

- 163-165, 标注, 2022 年 3 月 29 日星期二 下午 12:54:56
  # note_md5: 562a22e3c07c71a55fd1da2b87b49a71
  #+BEGIN_QUOTE
  皇帝的权威来自教皇的授权，但出于政治上和安排上的考虑，这一授权往往被撇在一边。结果是他作为“选出的皇帝”常常多年
  执掌权力。宗教和政治从未融合成为一个单一的结构。伏尔泰戏言，神圣罗马帝国“一不神圣，二非罗马，三不是帝国”
  #+END_QUOTE

- 281-285, 标注, 2022 年 3 月 29 日星期二 下午 8:57:52
  # note_md5: 11ec6e53eba4c15a2ddf6c07b301660f
  #+BEGIN_QUOTE
  塞留的一生中可以得出三点结论。第一，成功的外交政策有一项内容不可或缺：一个基于通盘分析的长期战略观。第二，政治
  家需要认真分析暧昧不清而且往往相互抵触的纷杂外力，把它们引向服务于一定目标的一致方向，并通过这一过程形成长期战
  略观。政治家必须了解这一战略的走势及其原因。第三，一位政治家必须尽最大之可能弥合本国社会的现实与所追求目标之间
  的差距。循规蹈矩会导致僵滞，因此需要敢作敢为。
  #+END_QUOTE

- 338-339, 标注, 2022 年 3 月 29 日星期二 下午 9:23:42
  # note_md5: fda5504fd6f231ec015695e254c73228
  #+BEGIN_QUOTE
  19 世纪英国政治家巴麦尊阐述了均势的要义：“我们没有永恒的盟友，也没有永恒的敌人，只有永恒的利益。我们的义务就是
  维护这些利益
  #+END_QUOTE

- 457-461, 标注, 2022 年 3 月 31 日星期四 下午 10:35:13
  # note_md5: e171f81533962a26e94a7e1fa9de647c
  #+BEGIN_QUOTE
  历史事件从来不是偶然的，而是有其内在原因。借助理性可以发现这些内因，并且要为了公众的利益塑造这些内因： 主宰世
  界的不是运气……每一个君主政体内都活跃着思想内因和自然内因，它们决定了政体的兴衰存亡。一切（看上去像是）偶发事件
  都是这些内因的结果。每当一国因一场偶然的战役——即一个特定原因——覆灭时，还存在一个导致该国因一场战役覆灭的一般原
  因。简而言之，整体局势的发展决定了具体事件的走
  #+END_QUOTE

- 457-461, 标注, 2022 年 3 月 31 日星期四 下午 10:35:17
  # note_md5: 43ca96d0f227bded30cd46c1edd3cd51
  #+BEGIN_QUOTE
  历史事件从来不是偶然的，而是有其内在原因。借助理性可以发现这些内因，并且要为了公众的利益塑造这些内因： 主宰世
  界的不是运气……每一个君主政体内都活跃着思想内因和自然内因，它们决定了政体的兴衰存亡。一切（看上去像是）偶发事件
  都是这些内因的结果。每当一国因一场偶然的战役——即一个特定原因——覆灭时，还存在一个导致该国因一场战役覆灭的一般原
  因。简而言之，整体局势的发展决定了具体事件的走向。
  #+END_QUOTE

- 486-488, 标注, 2022 年 4 月 1 日星期五 下午 8:55:50
  # note_md5: 440ad58cd36dd5a09cf6fb533da6abca
  #+BEGIN_QUOTE
  社会上的种种怨愤情绪汇聚起来冲击毫无警觉的政权之日，也是革命爆发之时。革命同盟越广泛，摧毁现政权结构的能量就越
  大。变革波及范围越广，重建权威时就越需要采取暴力的手段，否则社会就会走向解体。恐怖统治不是偶然现象，而是革命固
  有的特征
  #+END_QUOTE

- 658-663, 标注, 2022 年 4 月 1 日星期五 下午 9:44:33
  # note_md5: b57cab0c0311be8ec37c60715eac2434
  #+BEGIN_QUOTE
  如同中国的皇帝，沙皇是一位拥有神秘权力的至高无上的君主，统御广袤的疆土。但沙皇与中国的皇帝有一个重要区别。中国
  人认为，中国皇帝统治子民靠的是泰山崩于前而色不变的沉稳。俄国人则认为，沙皇维系其统治靠的是一种能力，一种以不容
  他人挑战自己权威的方式贯彻自己的意志，让所有旁观者深深感受到俄国这个国家无比强大的能力。中国的皇帝被视为优越的
  中华文明的象征，吸引他国人民“向化”。沙皇则被看作俄国抵御环伺之敌的象征。中国的皇帝因其圣明仁厚受到称赞。而 19 世
  纪的政治家尼古拉·卡拉姆津把沙皇的严酷看作是他响应内心召唤的表现
  #+END_QUOTE

- 2170-2171, 标注, 2022 年 4 月 4 日星期一 下午 12:12:50
  # note_md5: 8fbe2ae9906920855fbc6eea22136546
  #+BEGIN_QUOTE
  在仅仅一个世纪的时间内，日本从完全闭关锁国转变为广泛学习借鉴西方国家最现代化的做
  #+END_QUOTE

- 2584-2585, 标注, 2022 年 4 月 4 日星期一 下午 1:08:47
  # note_md5: 20daa9240e2ce25cf5bfc76f042b67be
  #+BEGIN_QUOTE
  沦肌浃髓。这一理念
  #+END_QUOTE

- 2593-2594, 标注, 2022 年 4 月 4 日星期一 下午 1:11:08
  # note_md5: 3862db2460fcd6ad327f1788866e9f82
  #+BEGIN_QUOTE
  在古中国，今天所谓的“外交政策”属于负责决定属国关系等级的礼部和负责管理与游牧部落关系的理藩院的职权范围
  #+END_QUOTE

- 2735-2739, 标注, 2022 年 4 月 4 日星期一 下午 1:33:02
  # note_md5: c9d3d0380fa42a6838fbb84471d51dd1
  #+BEGIN_QUOTE
  两国的文化和政治背景有着重大差异。美国的政策着眼于务实，中国则偏重概念。美国从未受过邻国威胁，中国的边境四周却
  无时无刻不强敌环伺，虎视眈眈。美国人相信每一个问题都有解决办法，中国人却认为一个问题的解决只会引起新的问题。美
  国人对眼前形势一定要拿出结果，中国人注重的则是大局的发展。美国人制定实际“可以做到的”计划，中国人只确定总的原则，
  进而分析它的走向
  #+END_QUOTE

- 2741-2742, 标注, 2022 年 4 月 4 日星期一 下午 1:33:36
  # note_md5: e64cd1eca9546cf7b4069d297c8c03dd
  #+BEGIN_QUOTE
  中国自认为与众不同，基本上自家管自家的事。美国也认为自己独一无二，也就是说它是“例外”，但它相信自己在道义上有义
  务超越国家利益，在世界上传播自己的价值观
  #+END_QUOTE

- 3017-3020, 标注, 2022 年 4 月 10 日星期日 上午 8:57:11
  # note_md5: 5b1b322f35da5465f5878c8ea2f36e2d
  #+BEGIN_QUOTE
  罗斯福至少暂时成功地重新确定了美国的国际角色。在美洲，他比反对外部干预的“门罗主义”走得更远。他承诺，美国不仅要
  抵制外国对西半球的殖民图谋（他本人威胁说，为了阻止德国对委内瑞拉的觊觎不惜一战），也可以先发制人防患于未然。因
  此，他在“门罗主义”的基础上提出了“罗斯福推论”，大意是美国有权先行干预其他西半球国家的内部事务，以纠正不能容忍的
  “恶行或无能
  #+END_QUOTE

- 3056-3056, 标注, 2022 年 4 月 10 日星期日 上午 9:05:21
  # note_md5: a6339afb27e861f3699c11a7049049d6
  #+BEGIN_QUOTE
  罗斯福最喜欢的谚语说，美国应当“说话温和，手持大棒”
  #+END_QUOTE

- 3468-3471, 标注, 2022 年 4 月 11 日星期一 下午 4:54:28
  # note_md5: 783f5ea242cc31e32448f35e76fb52c2
  #+BEGIN_QUOTE
  朝鲜战争也许能把中国拖入一场边境危机，把美国的注意力从欧洲引到亚洲，并且无论如何，都可以消耗美国的资源。如果朝
  鲜在苏联支持下获得成功，朝鲜半岛的统一会让苏联在朝鲜半岛占据支配地位，再加上这几个国家历史上相互猜疑，就会在亚
  洲对中国形成一定牵制。
  #+END_QUOTE

- 3473-3475, 标注, 2022 年 4 月 11 日星期一 下午 4:55:40
  # note_md5: 55db6484dfee77a4da342edc61fdb510
  # note_md5: 1d27111b199be1dba458acea09fad26d
  #+BEGIN_QUOTE
  有一次一位中国知名人士告诉我，跟在斯大林后面同意卷入朝鲜战争是毛泽东犯下的唯一战略错误。朝鲜战争最终把中国的统
  一推迟了一个世纪，因为它使美国更加坚定了保护台湾的承诺。

  各方都遭受了挫折。一些中国历史学家认为，中国为了支持一个不可靠的盟国，失去了统一台湾的机会。美国失去了“二战”后
  一直享有的不可战胜的光环，在一定程度上也失去了方向感。
  #+END_QUOTE
