#+TITLE:  [笔记]人类简史：从动物到上帝 yuval noah harari
#+AUTHOR: Yang Yingchao
#+DATE:   2024-10-09
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:  align nodlcheck oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+LANGUAGE: en
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :tag1:tag2:

- 130-131, 标注, 2018 年 7 月 14 日星期六 下午 10:19:10
  # note_md5: 48db4796a7fdfafb5068329845d7a4e1
  #+BEGIN_QUOTE
  讲述的就是这三大革命如何改变了人类和其他生物。
  #+END_QUOTE

- 141-141, 标注, 2018 年 7 月 14 日星期六 下午 10:21:08
  # note_md5: fc8ac21fad897fee9c719d12346e3430
  #+BEGIN_QUOTE
  所谓属于同一物种，就是它们会彼此交配，能够产出下一代。
  #+END_QUOTE

- 145-146, 标注, 2018 年 7 月 14 日星期六 下午 10:21:26
  # note_md5: b562bddeff2f602a7234fd683594fe15
  #+BEGIN_QUOTE
  从同一个祖先演化而来的不同物种，会属于同一个“属”（genus）
  #+END_QUOTE

- 150-151, 标注, 2018 年 7 月 14 日星期六 下午 10:22:30
  # note_md5: 9afd04b924ba60c797ccb0a89f66190e
  #+BEGIN_QUOTE
  许多属还能再归类为同一科（family），例如猫科（狮子、猎豹、家猫）、犬科（狼、狐狸、豺）、象科（大象、长毛象、乳
  齿象）。同一科的所有成员，都能追溯到某个最早的雄性或雌性祖先。
  #+END_QUOTE

- 235-236, 标注, 2018 年 7 月 15 日星期日 上午 6:49:49
  # note_md5: 8f332c9e9436b01c1f731af45e065270
  #+BEGIN_QUOTE
  有比较大的大脑、会使用工具、有超凡的学习能力还有复杂的社会结构，都可说是人类巨大的优势
  #+END_QUOTE

- 254-255, 标注, 2018 年 7 月 15 日星期日 上午 6:51:05
  # note_md5: fc906204f82cdd109ae052cf115bfbc5
  #+BEGIN_QUOTE
  人类历史上众多的灾难，不论是生灵涂炭的战乱还是生态遭逢的浩劫，其实都是源自这场过于仓促的地位跳
  #+END_QUOTE

- 254-255, 标注, 2018 年 7 月 15 日星期日 上午 6:51:09
  # note_md5: 8e35692bc4d242fc8412a1e40f05cf22
  #+BEGIN_QUOTE
  人类历史上众多的灾难，不论是生灵涂炭的战乱还是生态遭逢的浩劫，其实都是源自这场过于仓促的地位跳跃。
  #+END_QUOTE

- 269-269, 标注, 2018 年 7 月 15 日星期日 上午 6:52:42
  # note_md5: b1486d289b8225e320c069719b5a3114
  #+BEGIN_QUOTE
  不经意之间，烹调让尼安德特人与智人走上了让大脑更大的道路。
  #+END_QUOTE

- 387-388, 标注, 2018 年 7 月 15 日星期日 上午 7:15:53
  # note_md5: 7d536a8cdb3d3dfd858c4789eb94d932
  #+BEGIN_QUOTE
  大约就是在距今 7 万到 3 万年前，出现了新的思维和沟通方式，这也正是所谓的认知革命
  #+END_QUOTE

- 474-475, 标注, 2018 年 7 月 15 日星期日 下午 2:32:45
  # note_md5: fc9ac24decde28fa844cf151bafc8779
  #+BEGIN_QUOTE
  任何大规模人类合作的根基，都在于某种只存在于集体想象中的虚构故事
  #+END_QUOTE

- 477-477, 标注, 2018 年 7 月 15 日星期日 下午 2:34:15
  # note_md5: 3977504b79f306c7608d092ffd19da23
  #+BEGIN_QUOTE
  所谓的国家，也是立基于国家故事。
  #+END_QUOTE

- 478-478, 标注, 2018 年 7 月 15 日星期日 下午 2:34:25
  # note_md5: aa78682f2e19ecf0fe1a9efd82fbc4f1
  #+BEGIN_QUOTE
  至于司法制度，也是立基于法律故事
  #+END_QUOTE

- 534-535, 标注, 2018 年 7 月 15 日星期日 下午 2:40:17
  # note_md5: 7e84f0c800ee088a8b1e2ad90327dd0d
  #+BEGIN_QUOTE
  历史上也就不断围绕着这个问题打转：究竟某个人是如何说服数百万人去相信神、民族或是有限公司这些故事
  #+END_QUOTE

- 589-591, 标注, 2018 年 7 月 15 日星期日 下午 2:56:49
  # note_md5: d65c9577cf7e2aa6cb1359f42b5827c1
  #+BEGIN_QUOTE
  爱尔兰岛曾经住着一些智人，他们会使用一种叫作黑曜石的火山晶体，制造出特别坚硬且尖锐的工具。然而，新爱尔兰岛其实
  并不产黑曜石。化验结果显示，他们用的黑曜石来自超过 400 公里远的新不列颠岛。
  #+END_QUOTE

- 591-591, 笔记, 2018 年 7 月 15 日星期日 下午 2:57:28
  # note_md5: d155996afae961fc6c0e19ce329cd61c
  #+BEGIN_QUOTE
  冰与火之歌的原型吗？
  #+END_QUOTE

- 1335-1338, 标注, 2018 年 7 月 22 日星期日 上午 11:17:45
  # note_md5: a22356a739aaabb382961dedacd9006c
  #+BEGIN_QUOTE
  人类一心追求更轻松的生活，于是释放出一股巨大的力量，改变了世界的面貌，但结果并没有任何人料想得到，甚至也不是任
  何人所乐见的。并没有人在背后操纵农业革命发生，或是意图让人依赖谷类维生。一开始只是各种小事，主要就是希望吃饱一
  点、生活安全一点，但最后累积引起的效应，就是让远古的采集者开始
  #+END_QUOTE

- 1335-1338, 标注, 2018 年 7 月 22 日星期日 上午 11:17:58
  # note_md5: 63456295ee9500e7835439c7167ff81c
  #+BEGIN_QUOTE
  人类一心追求更轻松的生活，于是释放出一股巨大的力量，改变了世界的面貌，但结果并没有任何人料想得到，甚至也不是任
  何人所乐见的。并没有人在背后操纵农业革命发生，或是意图让人依赖谷类维生。一开始只是各种小事，主要就是希望吃饱一
  点、生活安全一点，但最后累积引起的效应，就是让远古的采集者开始花上整天的时间，在烈日之下挑水务农。
  #+END_QUOTE

- 1261-1264, 标注, 2018 年 7 月 22 日星期日 上午 11:18:43
  # note_md5: ca3f9eca3906300a08be2065180961ba
  #+BEGIN_QUOTE
  人类就像许多哺乳动物一样，自然有荷尔蒙和遗传机制来控制生育数。营养充足的时候，女性比较早进入青春期，成功怀孕的
  概率也比较高。而在土地贫瘠、营养不足的时候，女性进入青春期要来得晚，生育能力也下降。 人口管制除
  #+END_QUOTE

- 1261-1263, 标注, 2018 年 7 月 22 日星期日 上午 11:18:51
  # note_md5: e8feec6a7bdcc0435eee681bf0d7248e
  #+BEGIN_QUOTE
  人类就像许多哺乳动物一样，自然有荷尔蒙和遗传机制来控制生育数。营养充足的时候，女性比较早进入青春期，成功怀孕的
  概率也比较高。而在土地贫瘠、营养不足的
  #+END_QUOTE

- 1261-1263, 标注, 2018 年 7 月 22 日星期日 上午 11:19:07
  # note_md5: 7f8d763c51d77e5c4dba1b2f75f19cbe
  #+BEGIN_QUOTE
  人类就像许多哺乳动物一样，自然有荷尔蒙和遗传机制来控制生育数。营养充足的时候，女性比较早进入青春期，成功怀孕的
  概率也比较高。而在土地贫瘠、营养不足的时候，女性进入青春期要来得晚，生育能力也下降。
  #+END_QUOTE

- 1499-1499, 标注, 2019 年 2 月 22 日星期五 下午 10:49:34
  # note_md5: d2b40614770809a82a78624f05147277
  #+BEGIN_QUOTE
  正是这些征收来的多余食粮，养活了政治、战争、艺
  #+END_QUOTE

- 1499-1502, 标注, 2019 年 2 月 22 日星期五 下午 10:49:44
  # note_md5: 69b8c9436026c0eca67f5bfd498d1027
  #+BEGIN_QUOTE
  正是这些征收来的多余食粮，养活了政治、战争、艺术和哲学，建起了宫殿、堡垒、纪念碑和庙宇。在现代晚期之前，总人口
  有九成以上都是农民，日出而作、胼手胝足。他们生产出来的多余食粮养活了一小撮的精英分子：国王、官员、战士、牧师、
  艺术家和思想家，但历史写的几乎全是这些人的故事。于是，历史只告诉了我们极少数的人在做些什么，而其他绝大多数人的
  生活就是不停挑水耕田。
  #+END_QUOTE

- 1554-1554, 笔记, 2019 年 2 月 23 日星期六 上午 8:10:18
  # note_md5: d8a0f0045363ede8a0daac907279e215
  #+BEGIN_QUOTE
  就是真命天子的意思呗
  #+END_QUOTE

- 1553-1554, 标注, 2019 年 2 月 23 日星期六 上午 8:10:18
  # note_md5: 20040019d93cc94817bf02f86d1921e4
  #+BEGIN_QUOTE
  法典开头指出，美索不达米亚的几位大神安努（Anu）、恩利尔（Enlil）和马杜克（Marduk）任命汉谟拉比“在这片土地伸张
  正义，驱除不义罪恶，阻绝恃强凌弱”36
  #+END_QUOTE

- 1574-1576, 标注, 2019 年 2 月 23 日星期六 上午 8:12:03
  # note_md5: 480df33ed3cfa0843d47073b40ccb761
  #+BEGIN_QUOTE
  小孩并不是独立的人，而是父母的财产。因此，如果一个上等人杀了另一个上等人的女儿，惩罚就是把凶手的女儿给杀了。这
  对我们看来可能荒谬至极，凶手本人逍遥自在，但他无辜的女儿却得赔上一命。
  #+END_QUOTE

- 1580-1581, 标注, 2019 年 2 月 23 日星期六 上午 8:12:26
  # note_md5: a278beac43687183eca7214266ef0b5f
  #+BEGIN_QUOTE
  美国的《独立宣言》宣告自己是普遍和永恒的正
  #+END_QUOTE

- 1580-1584, 标注, 2019 年 2 月 23 日星期六 上午 8:12:38
  # note_md5: 0a9c8b7d1d525379c11b3a71dfff3618
  #+BEGIN_QUOTE
  美国的《独立宣言》宣告自己是普遍和永恒的正义原则，而这则宣言也像《汉谟拉比法典》一样找了神祇来背书。然而，美国
  神指示的至高原则，却似乎和巴比伦神指示的有所出入？美国《独立宣言》主张： 我们认为下面这些真理是不言而喻的：人
  人生而平等，造物者赋予他们若干不可剥夺的权利，其中包括生命权、自由权和追求幸福的权利。
  #+END_QUOTE

- 1598-1602, 标注, 2019 年 2 月 23 日星期六 上午 8:15:25
  # note_md5: b0f0eba61756c65014714c8166ea4276
  #+BEGIN_QUOTE
  演化铁定没有“平等”这回事，所谓平等的概念，是与“创造”的概念紧密相关。美国人的“平等”观念来自基督教，基督教认为每
  个人的灵魂都是由上帝创造，而所有灵魂在上帝面前一律平等。但是，如果我们不相信基督教那一套关于上帝、创造和灵魂的
  神话故事，那所谓人人“平等”究竟是什么意思？演化的基础是差异，而不是平等。每个人身上带的基因码都有些许不同，而且
  从出生以后就接受着不同的环境影响，发展出不同的特质，导致不同的生存概率。“生而平等”其实该是“演化各有不同”。
  #+END_QUOTE

- 1614-1616, 标注, 2019 年 2 月 23 日星期六 上午 8:41:25
  # note_md5: 00cdb16baefbd01338bf77a0b91e7991
  #+BEGIN_QUOTE
  学、科学的角度来写该是如何： 我们认为下面这些真理是不言而喻的：人人演化各有不同，出生就有某些可变的特性，其中
  包括生命和追求快感。 上面这段推
  #+END_QUOTE

- 1615-1616, 标注, 2019 年 2 月 23 日星期六 上午 8:41:33
  # note_md5: 2802604a52581bb3de96582fcbe1ed4d
  #+BEGIN_QUOTE
  我们认为下面这些真理是不言而喻的：人人演化各有不同，出生就有某些可变的特性，其中包括生命和追求快感。 上面这段推
  #+END_QUOTE

- 1615-1616, 标注, 2019 年 2 月 23 日星期六 上午 8:41:38
  # note_md5: 70ffe9440849e57b64663dcbc2fd9c26
  #+BEGIN_QUOTE
  我们认为下面这些真理是不言而喻的：人人演化各有不同，出生就有某些可变的特性，其中包括生命和追求快感。
  #+END_QUOTE

- 1614-1616, 标注, 2019 年 2 月 23 日星期六 上午 8:41:52
  # note_md5: 713baa72767bcefe378c6d626a8cbc40
  #+BEGIN_QUOTE
  因此，我们来看看美国《独立宣言》改用生物学、科学的角度来写该是如何： 我们认为下面这些真理是不言而喻的：人人演
  化各有不同，出生就有某些可变的特性，其中包括生命和追求快感。
  #+END_QUOTE

- 1618-1620, 标注, 2019 年 2 月 23 日星期六 上午 8:42:46
  # note_md5: be57ee97818217ef3c778993a8832175
  #+BEGIN_QUOTE
  我们相信某种秩序，并非因为它是客观的现实，而是因为相信它可以让人提升合作效率、打造更美好的社会。这种由想象所建
  构的秩序绝非邪恶的阴谋或是无用的空谈，而是唯一能让大群人类合作的救命仙丹。
  #+END_QUOTE

- 1643-1646, 标注, 2019 年 2 月 23 日星期六 上午 8:46:44
  # note_md5: 4ebc386aba065ec35509896f85047785
  #+BEGIN_QUOTE
  关于那些站在社会金字塔顶端的人。如果他们并不相信这些想象的秩序，他们又为什么要推动这种秩序呢？常有人说这些人其
  实什么都不信，只是贪婪而已。但这种说法有问题。如果真的是什么都不信（像是犬儒学派），就很难是个贪婪的人，毕竟客
  观来说，只是单纯要满足智人的基本生理需求并不难。
  #+END_QUOTE

- 1647-1650, 标注, 2019 年 2 月 23 日星期六 上午 8:48:08
  # note_md5: 4f4de565fb8d016e868f86ca45339bd7
  #+BEGIN_QUOTE
  但对真正的犬儒主义者来说，这一切贪婪的事都毫无意义。创立犬儒学派的希腊哲学家第欧根尼（Diogenes），就住在一个桶
  里。据说有一天他正在做日光浴，当时权倾天下的征服者亚历山大大帝来找他，想知道他是否需要些什么，而且保证自己会尽
  力协助。第欧根尼回答：“确实，有件事可以请你帮个忙。麻烦你移动一下，别再挡住我的阳光。”
  #+END_QUOTE

- 1672-1674, 标注, 2019 年 2 月 23 日星期六 上午 8:52:39
  # note_md5: d60b4fa88975c58030678194fb3bb865
  #+BEGIN_QUOTE
  受到同学嘲笑并不用太在意，因为只有他们自己知道自己的真正价值，别人不见得了解。 除此之外，这种
  #+END_QUOTE

- 1672-1674, 标注, 2019 年 2 月 23 日星期六 上午 8:52:44
  # note_md5: 0d448d28029024a0f4b43098007e7363
  #+BEGIN_QUOTE
  在现代西方学校里，老师和家长会告诉小孩，受到同学嘲笑并不用太在意，因为只有他们自己知道自己的真正价值，别人不见
  得了解。 除此之外，这种
  #+END_QUOTE

- 1672-1673, 标注, 2019 年 2 月 23 日星期六 上午 8:52:48
  # note_md5: d01eb839a94588656a1e74b19b2b2b8e
  #+BEGIN_QUOTE
  在现代西方学校里，老师和家长会告诉小孩，受到同学嘲笑并不用太在意，因为只有他们自己知道自己的真正价值，别人不见
  得了解。
  #+END_QUOTE

- 1689-1690, 标注, 2019 年 2 月 23 日星期六 上午 8:56:48
  # note_md5: c50e9d751a56b1ff693a9b689b3204fb
  #+BEGIN_QUOTE
  现代西方人最重视的那些欲望，都是建构在已经为时数百年的虚构故事上，包括浪漫主义、民族主义、资本主义以及人文主义。
  #+END_QUOTE

- 1697-1701, 标注, 2019 年 2 月 23 日星期六 上午 8:58:26
  # note_md5: e7374ebd3416e516696d6b4752c2fabc
  #+BEGIN_QUOTE
  浪漫主义告诉我们，为了要尽量发挥潜力，就必须尽量累积不同的经验。必须体会不同的情感，尝试不同的关系，品尝不同的
  美食，还必须学会欣赏不同风格的音乐。而其中最好的一种办法，就是摆脱日常生活及工作，远离熟悉的环境，前往遥远的国
  度，好亲身“体验”不同的文化、气味、美食和规范。我们总会不断听到浪漫主义的神话，告诉我们“那次的经验让我眼界大开，
  从此整个生活都不一样了”。
  #+END_QUOTE

- 1701-1704, 标注, 2019 年 2 月 23 日星期六 上午 8:59:04
  # note_md5: b92b8825fc070b6ce8412bf33a068b78
  #+BEGIN_QUOTE
  消费主义告诉我们，想要快乐，就该去买更多的产品、更多的服务。如果觉得少了什么，或是有什么不够舒服的地方，那很可
  能是该买些什么商品（新车、新衣服、有机食品），或是买点什么服务（清洁工、心理咨询、瑜伽课）。就连每一则电视广告，
  也都是个小小的虚构故事，告诉你买了什么产品或服务可以让日子更
  #+END_QUOTE

- 1701-1705, 标注, 2019 年 2 月 23 日星期六 上午 8:59:12
  # note_md5: 0b86e4598f4cfd7115a2d2e9dc30a55f
  #+BEGIN_QUOTE
  消费主义告诉我们，想要快乐，就该去买更多的产品、更多的服务。如果觉得少了什么，或是有什么不够舒服的地方，那很可
  能是该买些什么商品（新车、新衣服、有机食品），或是买点什么服务（清洁工、心理咨询、瑜伽课）。就连每一则电视广告，
  也都是个小小的虚构故事，告诉你买了什么产品或服务可以让日子更好。 鼓励多元多样的浪漫主义又与消费主义
  #+END_QUOTE

- 1701-1704, 标注, 2019 年 2 月 23 日星期六 上午 8:59:18
  # note_md5: cd972af2be940487626f7c35a2abad2a
  #+BEGIN_QUOTE
  消费主义告诉我们，想要快乐，就该去买更多的产品、更多的服务。如果觉得少了什么，或是有什么不够舒服的地方，那很可
  能是该买些什么商品（新车、新衣服、有机食品），或是买点什么服务（清洁工、心理咨询、瑜伽课）。就连每一则电视广告，
  也都是个小小的虚构故事，告诉你买了什么产品或服务可以让日子更好。
  #+END_QUOTE

- 1705-1705, 标注, 2019 年 2 月 23 日星期六 上午 8:59:40
  # note_md5: 80692ebbfb71bc5ca0ac4684e4d0c9b1
  #+BEGIN_QUOTE
  浪漫主义又与消费主义一拍即合，两者携手前行，催生了贩卖各种“体验”
  #+END_QUOTE

- 1706-1708, 标注, 2019 年 2 月 23 日星期六 上午 9:00:48
  # note_md5: 1c5536a4214a60065cc58f5348ba61ef
  #+BEGIN_QUOTE
  游业真正卖的可不是机票和饭店房间，而是旅游中的经验。所以这样说来，巴黎的重点不是城市，印度的重点也不是国家，而
  是它能提供的经验；之所以要买经验，是因为据说这样就能拓展我们的视野、发挥我们的潜力，并且让我们更快乐
  #+END_QUOTE

- 1706-1708, 标注, 2019 年 2 月 23 日星期六 上午 9:00:58
  # note_md5: 8fd45d844a849743bf3bf469d10bcd4b
  #+BEGIN_QUOTE
  旅游业真正卖的可不是机票和饭店房间，而是旅游中的经验。所以这样说来，巴黎的重点不是城市，印度的重点也不是国家，
  而是它能提供的经验；之所以要买经验，是因为据说这样就能拓展我们的视野、发挥我们的潜力，并且让我们更快乐
  #+END_QUOTE

- 1711-1714, 标注, 2019 年 2 月 23 日星期六 上午 9:01:40
  # note_md5: a0590db2c72c314ba8a2c84c81d88315
  #+BEGIN_QUOTE
  一如古埃及精英分子，现在大多数人一生汲汲营营，也都是想盖起某种金字塔，只不过这些金字塔在不同文化里会有不同的名
  字、形体和规模罢了。举例来说，可能是一栋近郊的独栋透天别墅，有游泳池和大庭院，也可能是一个闪闪发光的高楼公寓，
  有着令人屏息的美景。但很少人会真的去问，究竟为什么我们会开始想建这些金字塔？
  #+END_QUOTE

- 1758-1758, 标注, 2019 年 2 月 23 日星期六 上午 10:03:24
  # note_md5: 3bebd749eca452692e356cb3c442c211
  #+BEGIN_QUOTE
  演化并没有让人有踢足球赛的能力。
  #+END_QUOTE

- 1770-1771, 标注, 2019 年 2 月 23 日星期六 下午 12:50:33
  # note_md5: 8b44d9dfac9eb4b141f3c75ed1072987
  #+BEGIN_QUOTE
  蜜蜂的未受精卵会发育成雄蜂，受精卵则发育成雌蜂，但雌蜂幼虫依据被喂食的食物不同，长大后可能成为蜂后，也可能成为
  一般的工蜂。
  #+END_QUOTE

- 1809-1810, 标注, 2019 年 2 月 23 日星期六 下午 2:10:48
  # note_md5: 2dff764ae42cbaee0bb26c444a71d167
  #+BEGIN_QUOTE
  文字是采用实体符号来储存信息的方式。苏美尔文字
  #+END_QUOTE

- 1809-1810, 标注, 2019 年 2 月 23 日星期六 下午 2:10:59
  # note_md5: 39023bf2b85c0caa6c523a83a1c685a3
  #+BEGIN_QUOTE
  文字是采用实体符号来储存信息的方式。
  #+END_QUOTE

- 1867-1871, 标注, 2019 年 2 月 23 日星期六 下午 2:43:27
  # note_md5: 8903799b0c1c877f8c0214edbdc9a158
  #+BEGIN_QUOTE
  记在人脑里的信息找起来非常方便。以我自己为例，虽然我的大脑里藏着几千兆位的数据，但我可以几乎是立刻想起意大利首
  都的名字，再想起我在 2001 年“9·11”事件那天做了什么，还能马上想出从我家到耶路撒冷希伯来大学的路线。至今，大脑为何
  能做到这样仍然是一个谜，但我们都知道它的检索系统效率惊人。（只不过，找钥匙这件事可能是个例外。）
  #+END_QUOTE

- 1909-1911, 标注, 2019 年 2 月 23 日星期六 下午 2:48:08
  # note_md5: 8f50513971ac19cbb5d310e3b34b008a
  #+BEGIN_QUOTE
  从古至今，我们都知道文书和会计的想法就是有点没人性，像个文件柜一样。但这不是他们的错。如果他们不这样想，他们的
  抽屉就会一片混乱，也就无法为政府、公司或组织提供所需的服务。
  #+END_QUOTE

- 1915-1918, 标注, 2019 年 2 月 23 日星期六 下午 2:48:59
  # note_md5: 6818158a4fd749871b862c84ded6f140
  #+BEGIN_QUOTE
  很容易让人搞错的一点在于，虽然这些符号现在被称为“阿拉伯数字”，但其实是印度人发明的。而且现代阿拉伯人自己还用了
  一组和西方颇不相同的数字符号系统，就更叫人一头雾水。之所以现在我们会称“阿拉伯数字”，是因为阿拉伯人攻打印度时发
  现了这套实用的系统，再加以改良传到中东，进而传入欧洲。等到
  #+END_QUOTE

- 1915-1918, 标注, 2019 年 2 月 23 日星期六 下午 2:49:07
  # note_md5: 25ad3c275a8c68b77914b3e165fc27e5
  #+BEGIN_QUOTE
  这种文字是由 10 个符号组成，代表从 0 到 9 的数字。很容易让人搞错的一点在于，虽然这些符号现在被称为“阿拉伯数字”，但其
  实是印度人发明的。而且现代阿拉伯人自己还用了一组和西方颇不相同的数字符号系统，就更叫人一头雾水。之所以现在我们
  会称“阿拉伯数字”，是因为阿拉伯人攻打印度时发现了这套实用的系统，再加以改良传到中东，进而传入欧洲。等到
  #+END_QUOTE

- 1915-1918, 标注, 2019 年 2 月 23 日星期六 下午 2:49:11
  # note_md5: 6fe5942007701e30b5039c16a218436f
  #+BEGIN_QUOTE
  这种文字是由 10 个符号组成，代表从 0 到 9 的数字。很容易让人搞错的一点在于，虽然这些符号现在被称为“阿拉伯数字”，但其
  实是印度人发明的。而且现代阿拉伯人自己还用了一组和西方颇不相同的数字符号系统，就更叫人一头雾水。之所以现在我们
  会称“阿拉伯数字”，是因为阿拉伯人攻打印度时发现了这套实用的系统，再加以改良传到中东，进而传入欧洲。
  #+END_QUOTE

- 1922-1923, 标注, 2019 年 2 月 23 日星期六 下午 2:49:49
  # note_md5: 35371b9fa6c3399ce1e5abab1fd99f33
  #+BEGIN_QUOTE
  如果哪个人想打动政府、组织和企业，就必须学会“用数字说话”。
  #+END_QUOTE

- 1961-1962, 标注, 2019 年 2 月 23 日星期六 下午 2:56:31
  # note_md5: db0b0798fc3b4d749b43a6ad223f0bd4
  #+BEGIN_QUOTE
  然而历史的铁则告诉我们，每一种由想象建构出来的秩序，都绝不会承认自己出于想象和虚构，而会大谈自己是自然、必然的
  结果。
  #+END_QUOTE

- 2002-2003, 标注, 2019 年 2 月 23 日星期六 下午 3:48:42
  # note_md5: c8073f25499cfa130463ac49d3ca9121
  #+BEGIN_QUOTE
  一点，就是大多数的能力也需要培养和发展。
  #+END_QUOTE

- 2002-2003, 标注, 2019 年 2 月 23 日星期六 下午 3:48:46
  # note_md5: 5b70a72a65e6d2e836ca18df7843cf04
  #+BEGIN_QUOTE
  。第一，也是最重要的一点，就是大多数的能力也需要培养和发展。
  #+END_QUOTE

- 2002-2004, 标注, 2019 年 2 月 23 日星期六 下午 3:48:51
  # note_md5: 0c0fddc423b7f97b5511888e73552b8f
  #+BEGIN_QUOTE
  。第一，也是最重要的一点，就是大多数的能力也需要培养和发展。就算某个人天生就有某种才能，如果不经过积极培养、磨
  炼和运用，常常也就没什么表现的机会。
  #+END_QUOTE

- 2013-2014, 标注, 2019 年 2 月 23 日星期六 下午 3:49:55
  # note_md5: 1f7b39819741cafc2af85be56a864bdd
  #+BEGIN_QUOTE
  这些阶级制度开始时多半只是因为历史上的偶发意外，但部分群体取得既得利益之后，世世代代不断加以延续改良，才形成现
  在的样子。
  #+END_QUOTE

- 2094-2097, 标注, 2019 年 2 月 23 日星期六 下午 3:59:01
  # note_md5: 7a58ae77d4863ecddd29828f37eb429e
  #+BEGIN_QUOTE
  这样的恶性循环可能持续几百年甚至几千年，让原本只是历史偶发事件形成的阶级制度变得根深柢固。随着时间流逝，不公不
  义的歧视常常只是加剧而不是改善。富者越富，而贫者越贫。教育带来进一步的教育，而无知只会造成进一步的无知。历史上
  过去的受害者，很可能会再次受害。而历史上过去的特权分子，他们的特权也很可能依然存在。
  #+END_QUOTE

- 2098-2099, 标注, 2019 年 2 月 23 日星期六 下午 3:59:14
  # note_md5: ac1fabc3bef833a98ce0b24425dc11fe
  #+BEGIN_QUOTE
  大多数社会政治阶级制度其实都没有逻辑或生物学的基础，不过就是由历史的偶然事件引起，再用虚构的故事延续壮大。
  #+END_QUOTE

- 2147-2148, 标注, 2019 年 2 月 23 日星期六 下午 4:04:05
  # note_md5: 379f82091e0f33bd9daa2bd3f33ae251
  #+BEGIN_QUOTE
  天生带来允许，文化造成封闭”。天生自然的生物学，可能性几乎无穷无尽。然而，文化却要求必须实现某些可能性，而又封
  闭了其他可能性。
  #+END_QUOTE

- 2154-2155, 标注, 2019 年 2 月 23 日星期六 下午 4:05:51
  # note_md5: 1e570ae4843e479abe9437ac6805acaf
  #+BEGIN_QUOTE
  许多人认知的“自然”和“不自然”并不是生物学的概念，而是基督教神学的概念。神学上所谓的“自然”，指的是“符合创造自然
  的神的旨意”。
  #+END_QUOTE

- 2255-2255, 标注, 2019 年 2 月 23 日星期六 下午 8:54:45
  # note_md5: 821b67c34aa69e6829297b2cf0e776a3
  #+BEGIN_QUOTE
  人类历史显示，肌肉的力量和社会的权力还往往是呈反比。
  #+END_QUOTE

- 2340-2341, 标注, 2019 年 2 月 23 日星期六 下午 9:53:42
  # note_md5: 1a2566db2267fcf151e66a78553dfcea
  #+BEGIN_QUOTE
  虽然每种文化都有代表性的信仰、规范和价值，但会不断流动改变。只要环境或邻近的文化改变，文化就会有所改变及因应。
  #+END_QUOTE

- 2357-2358, 标注, 2019 年 2 月 23 日星期六 下午 9:56:26
  # note_md5: c282e0de74697fb2372a92f7ee1b1016
  #+BEGIN_QUOTE
  全球人民逐渐同意“自由”和“平等”都是基本的价值观。然而这两者根本就互相抵触！想要确保“平等”，就得限制住那些较突出
  的人；而要人人都能“自由”，也就必然影响所有人的平等。
  #+END_QUOTE

- 2381-2382, 标注, 2019 年 2 月 23 日星期六 下午 10:01:25
  # note_md5: 497a0c185253c31efaf5c4e6bf4158cb
  #+BEGIN_QUOTE
  合久必分只是一时，分久必合才是不变的大趋势。
  #+END_QUOTE

- 2384-2386, 标注, 2019 年 2 月 23 日星期六 下午 10:02:27
  # note_md5: 587d34a880661a47f563103273dade33
  #+BEGIN_QUOTE
  必须拉高到类似太空间谍卫星的高度，看的不是几世纪，而是几千年的跨度。这种高度能够让我们一目了然，知道历史趋势就
  是走向分久必合。至于前面基督教分裂或蒙古帝国崩溃的例子，就像是历史大道上的小小颠簸罢了。
  #+END_QUOTE

- 2437-2438, 标注, 2019 年 2 月 24 日星期日 上午 7:51:01
  # note_md5: f7adf7e91ad1955e656fb37e0a12cc67
  #+BEGIN_QUOTE
  从实际观点看，全球融合最关键的阶段就是过去这几个世纪。
  #+END_QUOTE

- 2439-2440, 标注, 2019 年 2 月 24 日星期日 上午 7:51:08
  # note_md5: 67958308f738ba201c4e8578a72c2132
  #+BEGIN_QUOTE
  但从意识形态观点，公元前的 1000 年间慢慢发展出“世界一家”的观念，这点的重要性也绝对不在其
  #+END_QUOTE

- 2439-2440, 标注, 2019 年 2 月 24 日星期日 上午 7:51:15
  # note_md5: 6c60abd83e985b92d68746ad7a6687e1
  #+BEGIN_QUOTE
  但从意识形态观点，公元前的 1000 年间慢慢发展出“世界一家”的观念，这点的重要性也绝对不在其下。
  #+END_QUOTE

- 2452-2453, 标注, 2019 年 2 月 24 日星期日 上午 7:52:53
  # note_md5: f09e60853746900dbcd0b15fc1303c9c
  #+BEGIN_QUOTE
  这三种全球秩序，首先第一种是经济上的货币秩序，第二种是政治上的帝国秩序，而第三种则是宗教上的全球性宗教，像是佛
  教、基督教和伊斯兰教。
  #+END_QUOTE

- 2451-2453, 标注, 2019 年 2 月 24 日星期日 上午 7:52:58
  # note_md5: c13b945c004f5e1f46a75a135c9eb771
  #+BEGIN_QUOTE
  相信这些秩序，就有可能相信全球的人类都“在一起”，都由同一套规则管辖，让所有人类都成了“我们”（至少有这个可能），
  “他们”也就不复存在。这三种全球秩序，首先第一种是经济上的货币秩序，第二种是政治上的帝国秩序，而第三种则是宗教上
  的全球性宗教，像是佛教、基督教和伊斯兰教。
  #+END_QUOTE

- 2462-2462, 标注, 2019 年 2 月 24 日星期日 上午 7:53:47
  # note_md5: c11243c6c21738ac3a56fbac33e31781
  #+BEGIN_QUOTE
  究竟金钱有什么魔力，竟然能完成连神和君王都做不到的
  #+END_QUOTE

- 2462-2462, 标注, 2019 年 2 月 24 日星期日 上午 7:53:51
  # note_md5: 5192beef3748a8c7ad4e3f6937427f5e
  #+BEGIN_QUOTE
  究竟金钱有什么魔力，竟然能完成连神和君王都做不到的事？
  #+END_QUOTE

- 2466-2472, 标注, 2019 年 2 月 24 日星期日 上午 7:55:14
  # note_md5: bc9752b2f1b9d058f393e9121ca2cf45
  #+BEGIN_QUOTE
  1519 年，墨西哥原本还是个遗世独立的人类社会，但来自西班牙的殖民者荷南·科尔特斯（Hernán Cortés）一行人大举入侵。
  这里的人自称阿兹特克人，很快就发现这些外来的西班牙人看到某种黄色金属就眼睛为之一亮，思思念念，三句不离。阿兹特
  克人也不是不懂黄金。黄金色泽美丽，又容易加工，所以他们常用来制作首饰和雕像。阿兹特克人偶尔也用金粉来交易，但一
  般想买东西的时候，通常还是用可可豆或布料来付账。所以，看到西班牙人对黄金如此痴迷，他们实在是一头雾水。毕竟，黄
  金不能吃、不能喝、不能织，想当作工具或武器，质地又太软，究竟为什么西班牙人为之如此疯狂？面对当地人的疑惑，科尔
  特斯表示：“我们这群人有种心病，
  #+END_QUOTE

- 2466-2472, 标注, 2019 年 2 月 24 日星期日 上午 7:55:22
  # note_md5: 7e97a234174c11b1a44944bd9c3344e4
  #+BEGIN_QUOTE
  1519 年，墨西哥原本还是个遗世独立的人类社会，但来自西班牙的殖民者荷南·科尔特斯（Hernán Cortés）一行人大举入侵。
  这里的人自称阿兹特克人，很快就发现这些外来的西班牙人看到某种黄色金属就眼睛为之一亮，思思念念，三句不离。阿兹特
  克人也不是不懂黄金。黄金色泽美丽，又容易加工，所以他们常用来制作首饰和雕像。阿兹特克人偶尔也用金粉来交易，但一
  般想买东西的时候，通常还是用可可豆或布料来付账。所以，看到西班牙人对黄金如此痴迷，他们实在是一头雾水。毕竟，黄
  金不能吃、不能喝、不能织，想当作工具或武器，质地又太软，究竟为什么西班牙人为之如此疯狂？面对当地人的疑惑，科尔
  特斯表示：“我们这群人有种心病，只有金子能医。”51
  #+END_QUOTE

- 2522-2523, 标注, 2019 年 2 月 24 日星期日 上午 11:18:41
  # note_md5: cc0ecdf0b488122e8c3cadda136c72a7
  #+BEGIN_QUOTE
  原本声称要让人人“各尽所能、各取所需”，但结果是“各尽所能的最小值，各抢所需的最大值”。
  #+END_QUOTE

- 2539-2541, 标注, 2019 年 2 月 24 日星期日 上午 11:21:22
  # note_md5: 6086b4e30451b91c63cce16c7abc4192
  #+BEGIN_QUOTE
  全球金钱总和为 60 兆美元，但所有硬币和钞票的金额加起来还不到 6 兆美元。57 换句话说，所有的钱有超过九成（超过 50 兆美
  元！）都只是显示在计算机上的数字而已。正因如此，大多数的商业交易其实只是把某台计算机里的电子数据搬到另一台去，
  而完全没有任何实体金钱的交换。
  #+END_QUOTE

- 2548-2548, 标注, 2019 年 2 月 24 日星期日 上午 11:21:59
  # note_md5: 4bfda12d8c7b3a110289a0a86e50937d
  #+BEGIN_QUOTE
  金钱就成了共通的交易媒介，几乎任何东西之间都能完成交换。
  #+END_QUOTE

- 2572-2572, 标注, 2019 年 2 月 24 日星期日 上午 11:24:53
  # note_md5: 9d527f75f0da3aa4395421db0b9f0b25
  #+BEGIN_QUOTE
  金钱正是有史以来最普遍也最有效的互信系统。
  #+END_QUOTE

- 2611-2612, 标注, 2019 年 2 月 24 日星期日 上午 11:32:12
  # note_md5: a053cd5effe835962b1f2ed341668b45
  #+BEGIN_QUOTE
  正因如此，铸造伪币的罪行一直比其他诈欺行为判得更重。因为造伪币不只是单纯的诈欺，更是对主权的挑战，直接冒犯了国
  王的权力、特权和他本人。
  #+END_QUOTE

- 2652-2655, 标注, 2019 年 2 月 24 日星期日 上午 11:44:34
  # note_md5: 3b59134ad3c471b62f05649b39fc7eef
  #+BEGIN_QUOTE
  金钱制度有两大原则： 1. 万物可换：钱就像是炼金术，可以让你把土地转为手下的忠诚，把正义转为健康，把暴力转为知识。
  2. 万众相信：有了金钱作为媒介，任何两个人都能合作各种计划。
  #+END_QUOTE

- 2702-2703, 标注, 2019 年 2 月 24 日星期日 下午 3:03:58
  # note_md5: a9514a70ccdc1ce3facee2f3a107a65f
  #+BEGIN_QUOTE
  这种情节不太符合我们的品位，我们爱看的是反败为胜，是小人物的胜利。然而，历史就是没有正义。
  #+END_QUOTE

- 2702-2703, 标注, 2019 年 2 月 24 日星期日 下午 3:04:05
  # note_md5: 52da8dad5ba3bd578ba3357481d71930
  #+BEGIN_QUOTE
  然而，历史就是没有正义。
  #+END_QUOTE

- 2705-2706, 标注, 2019 年 2 月 24 日星期日 下午 4:01:45
  # note_md5: f21f770f5d05bc3719681cc3168dd062
  #+BEGIN_QUOTE
  帝国是一种政治秩序，有两项重要特征。第一，帝国必须统治着许多不同的民族，各自拥有不同的文化认同和独立的领土。
  #+END_QUOTE

- 2708-2708, 标注, 2019 年 2 月 24 日星期日 下午 4:01:56
  # note_md5: 49bd76efa404df98cc2b000ab0b060cc
  #+BEGIN_QUOTE
  第二，帝国的特征是疆域可以灵活调整，而且可以几乎无限扩张。
  #+END_QUOTE

- 2708-2709, 标注, 2019 年 2 月 24 日星期日 下午 4:02:04
  # note_md5: 17fabdfd29bacfa7d25ce18f59cbddb4
  #+BEGIN_QUOTE
  第二，帝国的特征是疆域可以灵活调整，而且可以几乎无限扩张。帝国不需要改变基本架构和认同，就能够纳入更多其他国家
  和领土。
  #+END_QUOTE

- 2712-2714, 标注, 2019 年 2 月 24 日星期日 下午 4:02:40
  # note_md5: 549cd0a58cf9cfe0acfbeffc7813db9b
  #+BEGIN_QUOTE
  这里要特别强调，帝国的定义就只在于文化多元性和疆界灵活性两项，至于起源、政府形式、领土范围或人口规模则并非重点。
  #+END_QUOTE

- 2828-2830, 标注, 2019 年 2 月 24 日星期日 下午 4:14:20
  # note_md5: 401c23cf4932e711f7b188ec32e0c8d2
  #+BEGIN_QUOTE
  至于现代许多的美国人，他们也认为美国必须负起道义责任，让第三世界国家同样享有民主和人权，就算这得靠巡航导弹和
  F-16 战机，也是在所不惜。 帝国所传播的文化理念很少只来自那一小群的统治精英。
  #+END_QUOTE

- 2828-2829, 标注, 2019 年 2 月 24 日星期日 下午 4:14:45
  # note_md5: a53814bad40e4db04b7f3cb24ebbceb0
  #+BEGIN_QUOTE
  现代许多的美国人，他们也认为美国必须负起道义责任，让第三世界国家同样享有民主和人权，就算这得靠巡航导弹和 F-16 战
  机，也是在所不惜。
  #+END_QUOTE

- 2957-2959, 标注, 2019 年 2 月 24 日星期日 下午 4:25:32
  # note_md5: 5be72941e9fb5a55471296b648aa13ea
  #+BEGIN_QUOTE
  各国也得遵守全球在财政、环保和法律上的标准。资金、劳动力和信息构成一股无比强大的潮流，翻转并形塑着现在的世界，
  国家本身的疆域和意见已经逐渐失势。 我们眼下正在形成的全球帝国，并不受任何
  #+END_QUOTE

- 2957-2959, 标注, 2019 年 2 月 24 日星期日 下午 4:25:41
  # note_md5: 21738ee65fb2cbb4ac180d12ea7e7fe1
  #+BEGIN_QUOTE
  各国也得遵守全球在财政、环保和法律上的标准。资金、劳动力和信息构成一股无比强大的潮流，翻转并形塑着现在的世界，
  国家本身的疆域和意见已经逐渐失势。
  #+END_QUOTE

- 2978-2979, 标注, 2019 年 2 月 24 日星期日 下午 4:27:30
  # note_md5: cbb2ac51d8ad9ac79e51eec3ca1eb800
  #+BEGIN_QUOTE
  金钱和帝国之外，宗教正是第三种让人类统一的力量。
  #+END_QUOTE

- 2978-2979, 标注, 2019 年 2 月 24 日星期日 下午 4:27:36
  # note_md5: 25f21990792e657c14dfd9cc4c2fba4f
  #+BEGIN_QUOTE
  但在金钱和帝国之外，宗教正是第三种让人类统一的力量。
  #+END_QUOTE

- 3067-3070, 标注, 2019 年 2 月 24 日星期日 下午 4:39:09
  # note_md5: 2835db4801a7d51c3fcb0eaa5d567b00
  #+BEGIN_QUOTE
  然而事实证明，就算把这些迫害的所有受害者全部加起来，在这 3 个世纪间，多神教古罗马处决基督徒的人数不超过几千人。
  64 但相对的是，在接下来的 1500 年间，虽然基督教号称主张爱与怜悯，但仅仅对信仰的诠释有些许差异，就引发基督徒自相残
  杀，死亡人数达到数百万。
  #+END_QUOTE

- 3070-3070, 笔记, 2019 年 2 月 24 日星期日 下午 4:39:54
  # note_md5: 68c33da710a7dfab99ce2cd21860c14f
  #+BEGIN_QUOTE
  多神教比一神教更宽容
  #+END_QUOTE

- 3090-3090, 标注, 2019 年 2 月 24 日星期日 下午 4:44:16
  # note_md5: 4c12451c981960042602f07abe6e18c1
  #+BEGIN_QUOTE
  犹太教
  #+END_QUOTE

- 3093-3093, 标注, 2019 年 2 月 24 日星期日 下午 4:44:58
  # note_md5: 8d37824fc0803142f7e063928de6e02e
  #+BEGIN_QUOTE
  基督教，
  #+END_QUOTE

- 3099-3099, 标注, 2019 年 2 月 24 日星期日 下午 4:46:06
  # note_md5: 6bb5883f4b3cfa8687607ee9b84283de
  #+BEGIN_QUOTE
  伊斯兰教
  #+END_QUOTE

- 3119-3120, 标注, 2019 年 2 月 24 日星期日 下午 4:49:09
  # note_md5: 3fd95e45c61a8497035605d8f6a26b93
  #+BEGIN_QUOTE
  一神论宗教大张旗鼓把其他神祇从大门赶了出去，但又从旁边的小窗把他们迎了回来。
  #+END_QUOTE

- 3152-3152, 标注, 2019 年 2 月 24 日星期日 下午 5:04:39
  # note_md5: f29f9decda92e2632cf23796b948879c
  #+BEGIN_QUOTE
  拜火教）。
  #+END_QUOTE

- 3152-3152, 笔记, 2019 年 2 月 24 日星期日 下午 5:05:17
  # note_md5: 1055f30bd8573ec61a25c474bbb91974
  #+BEGIN_QUOTE
  难道是无忌?
  #+END_QUOTE

- 3175-3177, 标注, 2019 年 2 月 24 日星期日 下午 5:08:37
  # note_md5: ef6e5e0c6ddf7388a6273a705e18111c
  #+BEGIN_QUOTE
  一神论就像是个万花筒，承继了一神论、二元论、多神论和泛神论，收纳在同一个神圣论述之下。结果就是，基督徒大致上是
  信奉一神论的上帝，相信二元论的魔鬼，崇拜多神论的圣人，还相信泛神论的鬼魂。
  #+END_QUOTE

- 3175-3178, 标注, 2019 年 2 月 24 日星期日 下午 5:08:50
  # note_md5: d65e7823f9a3d1ab04c11a57ced2fb4e
  #+BEGIN_QUOTE
  一神论就像是个万花筒，承继了一神论、二元论、多神论和泛神论，收纳在同一个神圣论述之下。结果就是，基督徒大致上是
  信奉一神论的上帝，相信二元论的魔鬼，崇拜多神论的圣人，还相信泛神论的鬼魂。像这样同时有着不同甚至矛盾的思想，而
  又结合各种不同来源的仪式和做法，宗教学上有一个特别的名称：综摄（syncretism）。很有可能，综摄才是全球最大的单一
  宗教。
  #+END_QUOTE

- 3179-3180, 标注, 2019 年 2 月 24 日星期日 下午 5:10:10
  # note_md5: fc1bbb869f88727ae553022d23f4132e
  #+BEGIN_QUOTE
  我们目前为止讨论到的所有宗教，都有一个共同的重要特征：相信的都是神灵或是其他超自然对象。然而，世界宗教史并不只
  是神的历史。
  #+END_QUOTE

- 3182-3183, 标注, 2019 年 2 月 24 日星期日 下午 5:10:43
  # note_md5: 6a46321d9cf4c2afac7918e17d5ae52a
  #+BEGIN_QUOTE
  这些信仰也认为有某种超人类秩序控制着这个世界，但它们所崇拜的这个秩序是自然法则，而不是什么神圣的意志。
  #+END_QUOTE

- 3182-3184, 标注, 2019 年 2 月 24 日星期日 下午 5:10:52
  # note_md5: 66e406148cf3a323e0b2dffbfce23bf5
  #+BEGIN_QUOTE
  这些信仰也认为有某种超人类秩序控制着这个世界，但它们所崇拜的这个秩序是自然法则，而不是什么神圣的意志。这些自然
  法则的宗教信仰虽然某些也相信有神祇存在，但认为神祇就和人类、动物和植物一样会受到自然法则的限制。
  #+END_QUOTE

- 3197-3204, 标注, 2019 年 2 月 24 日星期日 下午 5:12:17
  # note_md5: 66a1ee2c107a6abdafbd9dd22ae518ee
  #+BEGIN_QUOTE
  他入禅六年，思索各种人类苦痛的本质、原因和解决方式。最后他体会到，一切苦难并非来自噩运、社会不公或是神祇的任性，
  而是出于每个人自己心中的思想模式。 释迦牟尼认为，人遇到事情通常就会产生欲念，而欲念总是会造成不满。遇到不喜欢
  的事，就想躲开；遇到喜欢的事，就想维持并增加这份愉快。但正因如此，人心就永远不满、永远不安。这点在碰上不悦的时
  候格外明显，像是感觉疼痛的时候，只要疼痛持续，我们就一直感到不满，用尽办法想要解决。然而，就算是遇上欢乐的事，
  我们也从不会真正满足，而是一直担心这种欢乐终将结束或是无法再持续或增强。有些人多年来一直在寻找爱情，但等到真的
  找着了爱情，却还是不满足。有的开始整天担心对方可能会离开；有的又觉得自己太过屈就，应该再找更好的人。（而且，我
  们也都认识某些人，又担心别人离开，又觉得自己屈就）。
  #+END_QUOTE

- 3207-3208, 标注, 2019 年 2 月 24 日星期日 下午 5:13:06
  # note_md5: 4e66c108ea4f0b44bf6a4f2a60ad44e3
  #+BEGIN_QUOTE
  释迦牟尼找到一种方法可以跳出这种恶性循环。在事物带来快乐或痛苦的时候，重点是要看清事物的本质，而不是着重在它带
  来的感受，于是就能不再为此所困。
  #+END_QUOTE

- 3210-3212, 标注, 2019 年 2 月 24 日星期日 下午 5:13:43
  # note_md5: ddb29a2c0da91ce5947b59a5cfc309bf
  #+BEGIN_QUOTE
  要怎样才能让心里接受事物的本质，而放下种种欲求，知道苦即为苦、乐即为乐？释迦牟尼制定一套冥想的技巧，能够训练心
  灵感受事物的本质而排除种种欲求。
  #+END_QUOTE

- 3219-3220, 标注, 2019 年 2 月 24 日星期日 下午 5:14:21
  # note_md5: 31c80158a62513ce60488bb231be08eb
  #+BEGIN_QUOTE
  佛陀的教诲一言以蔽之：痛苦来自欲望；要从痛苦中解脱，就要放下欲望；而要放下欲望，就必须训练心智，体验事物的本质。
  #+END_QUOTE

- 3242-3244, 标注, 2019 年 2 月 24 日星期日 下午 7:37:28
  # note_md5: f810c9623d1b3f1cccc3e3ee25fe6ee4
  #+BEGIN_QUOTE
  有神论的宗教，重点在神的崇拜；至于人文主义宗教，重点就是对人的崇拜，或者讲得更明确，是对智人的崇拜。人文主义的
  基本信念，就是认为智人是独特的、神圣的，从本质上就与其他所有现代动物有所不同。
  #+END_QUOTE

- 3248-3249, 标注, 2019 年 2 月 24 日星期日 下午 7:44:19
  # note_md5: 05845784d70a315f5290ae7dda97638f
  #+BEGIN_QUOTE
  今天最重要的人文主义学派就是自由人文主义，它认为人性就在于每个个人的自我特质，因此个人自由也就变得神圣不可侵犯。
  #+END_QUOTE

- 3261-3263, 标注, 2019 年 2 月 24 日星期日 下午 7:44:40
  # note_md5: 88fcb0c7e38a482b5a3720876993b0e4
  #+BEGIN_QUOTE
  人文主义的另一个重要教派就是社会人文主义。社会主义者认为所谓“人性”是个集体而非个人的概念。因此，他们认为神圣的
  不是每个个人心中的声音，而是由所有智人这种物种构成的整体。自由人文主义追求的，是尽可能为个人争取更多自由；而社
  会人文主义追求的，则是让所有人都能平等。
  #+END_QUOTE

- 3261-3262, 标注, 2019 年 2 月 24 日星期日 下午 7:44:58
  # note_md5: e4db15d5d1a4a361aca0cec8c984fced
  #+BEGIN_QUOTE
  人文主义的另一个重要教派就是社会人文主义。社会主义者认为所谓“人性”是个集体而非个人的概念。因此，他们认为神圣的
  不是每个个人心中的声音，而是由所有智人这种物种构成的整体。自
  #+END_QUOTE

- 3261-3262, 标注, 2019 年 2 月 24 日星期日 下午 7:45:06
  # note_md5: d964ebfa174346a1b8b7f48ebc26cc3c
  #+BEGIN_QUOTE
  人文主义的另一个重要教派就是社会人文主义。社会主义者认为所谓“人性”是个集体而非个人的概念。因此，他们认为神圣的
  不是每个个人心中的声音，而是由所有智人这种物种构成的整体。
  #+END_QUOTE

- 3263-3263, 标注, 2019 年 2 月 24 日星期日 下午 7:45:12
  # note_md5: b7971d5c4e72f7e4751bab0e7c2493d3
  #+BEGIN_QUOTE
  社会人文主义追求的，则是让所有人都能平等。
  #+END_QUOTE

- 3269-3270, 标注, 2019 年 2 月 24 日星期日 下午 7:46:21
  # note_md5: 23ce2f10f22782331a3e29c04b0a6685
  #+BEGIN_QUOTE
  相对于其他人文主义者，纳粹相信人类并非处处相同，也不是永恒不变，而是一个会进化或退化的物种。人可以进化成超人，
  也可以退化成非人。
  #+END_QUOTE

- 3267-3269, 标注, 2019 年 2 月 24 日星期日 下午 7:46:45
  # note_md5: 3c94b0cb4ba1eba32786934b50df1b63
  #+BEGIN_QUOTE
  平等。唯一不是来自传统一神论的人文主义教派，就是演化人文主义，以纳粹为最著名的代表。真正让纳粹与其他人文主义教
  派不同的地方，在于他们深受演化论影响，对“人性”有不同
  #+END_QUOTE

- 3281-3282, 标注, 2019 年 2 月 24 日星期日 下午 7:49:07
  # note_md5: cf3fff8689bc42eed55406d9346f6dda
  #+BEGIN_QUOTE
  纳粹才会主张应该要保护、好好养育雅利安人（Aryan，他们认为这是最进步的智人类型），至于犹太人、吉卜赛人、同性恋
  者和精神病患这些被认为是退化的智人类型，则必须隔离甚至灭绝。
  #+END_QUOTE

- 3302-3306, 标注, 2019 年 2 月 24 日星期日 下午 7:53:50
  # note_md5: d2f8cf2ce4dd2bca7016e6ec7ae541bb
  #+BEGIN_QUOTE
  纳粹并不是反人性。他们之所以同自由人文主义、人权和共产主义站在对立面，反而正是因为他们推崇人性，相信人类有巨大
  的潜力。他们顺着达尔文演化论的逻辑，认为必须要通过自然选择淘汰不适合的个人，只留下适者，才能让人类继续生存繁殖。
  但自由主义和共产主义要保护弱者，不仅让不适者生存了下来，还给了他们繁殖的机会，这样就破坏了自然选择的秩序。
  #+END_QUOTE

- 3320-3322, 标注, 2019 年 2 月 24 日星期日 下午 7:55:29
  # note_md5: 3b8c759ae3e90559e5f90ca551abe07a
  #+BEGIN_QUOTE
  这种想法已经死灰复燃。虽然已经没有人说要淘汰劣等种族或民族，但许多人正思考着如何利用更先进的人类生物学知识来创
  造完美的人类。
  #+END_QUOTE

- 3333-3333, 标注, 2019 年 2 月 24 日星期日 下午 7:57:31
  # note_md5: ee6d8425a1da5728e7b37ed649a9592a
  #+BEGIN_QUOTE
  商业、帝国和全球性的宗教，最后终于将几乎每个智人都纳入了我们今天的全球世界。
  #+END_QUOTE

- 3334-3335, 标注, 2019 年 2 月 24 日星期日 下午 7:57:43
  # note_md5: 5175290f425a689eab012f8da046bdfe
  #+BEGIN_QUOTE
  观大局，可以看到从许多小文化到少数大文化再到最后的全球单一文化，应该是人类历史无法避免的结果。
  #+END_QUOTE

- 3333-3335, 标注, 2019 年 2 月 24 日星期日 下午 7:57:50
  # note_md5: 3dee0c6c05bfe96735161d29530cf253
  #+BEGIN_QUOTE
  统一的过程并不是完全直线发展、一帆风顺。但纵观大局，可以看到从许多小文化到少数大文化再到最后的全球单一文化，应
  该是人类历史无法避免的结果。
  #+END_QUOTE

- 3334-3335, 标注, 2019 年 2 月 24 日星期日 下午 7:58:02
  # note_md5: 458072e1ab9436a97a5f86f2dcb63236
  #+BEGIN_QUOTE
  纵观大局，可以看到从许多小文化到少数大文化再到最后的全球单一文化，应该是人类历史无法避免的结果。
  #+END_QUOTE

- 3355-3356, 标注, 2019 年 2 月 24 日星期日 下午 8:00:15
  # note_md5: 81fb61e431c95646b74ff54b0946a8d5
  #+BEGIN_QUOTE
  正是历史成为学科的特点之一：对某个时代的了解越透彻，反而就越难解释为什么发生了这个事件而不是那个事件。但如果对
  某个时期只是一知半解，就很容易受到结果影响，只看到那些最后成真的可能性。
  #+END_QUOTE

- 3356-3356, 笔记, 2019 年 2 月 24 日星期日 下午 8:00:44
  # note_md5: 829b53ff8a3f74a5ff2ef88aeafe8f31
  #+BEGIN_QUOTE
  不只是历史...
  #+END_QUOTE

- 3359-3360, 标注, 2019 年 2 月 24 日星期日 下午 8:01:40
  # note_md5: 809a803637deaa433fae9bc81460d5df
  #+BEGIN_QUOTE
  历史的铁则就是：事后看来无可避免的事，在当时看来总是毫不明显。
  #+END_QUOTE

- 3396-3397, 标注, 2019 年 2 月 24 日星期日 下午 8:06:07
  # note_md5: fa97376d25be4e1ddf8d270bdd4d7f6d
  #+BEGIN_QUOTE
  历史不像是物理学或经济学，目的不在于做出准确预测。我们之所以研究历史，不是为了要知道未来，而是要拓展视野，要了
  解现在的种种绝非“自然”，也并非无可避免。未来
  #+END_QUOTE

- 3396-3397, 标注, 2019 年 2 月 24 日星期日 下午 8:06:13
  # note_md5: f66ccc11cb1072bc9e04169d1a0c8984
  #+BEGIN_QUOTE
  历史不像是物理学或经济学，目的不在于做出准确预测。我们之所以研究历史，不是为了要知道未来，而是要拓展视野，要了
  解现在的种种绝非“自然”，也并非无可避免。
  #+END_QUOTE

- 3408-3412, 标注, 2019 年 2 月 24 日星期日 下午 8:08:16
  # note_md5: dadde0f5008b6ac4ec039bcec948ddfe
  #+BEGIN_QUOTE
  文化就像是精神感染或寄生虫，而人类就是毫不知情的宿主。寄生虫或病毒就是这样住在宿主体内，繁殖、传播，从一个宿主
  到另一个宿主，夺取养分，让宿主衰弱，有时甚至丧命。只要宿主能够活着让寄生虫继续繁衍，寄生虫就很少关心宿主的情形。
  至于文化，其实也是以这种方式寄生在人类的心中。它们从一个宿主传播到另一个宿主，有时候让宿主变得衰弱，有时候甚至
  让宿主丧命。
  #+END_QUOTE

- 3484-3486, 标注, 2019 年 2 月 24 日星期日 下午 8:59:01
  # note_md5: cb87655b2f6a7544c631ac1434f9c251
  #+BEGIN_QUOTE
  如果要在过去 500 年间挑出一个最重大、具代表性的一刻，一定就是 1945 年 7 月 16 日上午 5 点 29 分 45 秒。就在这一秒，美国科学
  家在新墨西哥的阿拉莫戈多引爆了第一颗原子弹。从这时开始，人类不仅有了改变历史进程的能力，更有了结束历史进程的能
  力。
  #+END_QUOTE

- 3554-3555, 标注, 2019 年 2 月 24 日星期日 下午 10:29:58
  # note_md5: d6d5fc2cb573ad0e1806479fa4aa7034
  #+BEGIN_QUOTE
  现代社会之所以还能够维系，原因之一就在于对科技和科学研究方法的信任，这几乎成了类似宗教的信仰，甚至在一定程度上
  也取代了对绝对真理的信念。
  #+END_QUOTE

- 3641-3642, 标注, 2019 年 2 月 24 日星期日 下午 10:38:20
  # note_md5: 435a2837125227b5afddfba8579e1803
  #+BEGIN_QUOTE
  虽然在过去也常有人发展出新科技，但通常是些未受过教育的工匠不断尝试错误而产生，而不是学者经由系统化的科学研究而
  得。
  #+END_QUOTE

- 3819-3822, 标注, 2019 年 2 月 25 日星期一 上午 8:22:21
  # note_md5: 48c4c3e635a6f66aa53c584c7aa7cfd1
  #+BEGIN_QUOTE
  我们希望能够赞助纯科学，不要受到政治、经济或宗教利益干扰，很有可能还是无法成功。毕竟，人类的资源有限。如果要求
  美国国会议员为美国国家科学基金会多拨 100 万美元来从事基础研究，他一定会理直气壮地问，如果这笔钱拿来做教师培训或
  是补助他选区某个陷入困境的工厂，不是更能把钱花在刀刃上吗？正因为资源有限，我们就必须回答像是“什么更重要”和“怎
  样才算花得适当”这种问题。
  #+END_QUOTE

- 3831-3834, 标注, 2019 年 2 月 25 日星期一 上午 8:23:19
  # note_md5: b67ea2fc6ba15ae80622f36b100319b7
  #+BEGIN_QUOTE
  如果他所在的社会更重视的是牛奶的商业潜力及人民的健康安全，而不那么重视奶牛的情感需求，他最好还是改写一下研究计
  划，以迎合那些心态。举例来说，计划书可以写道：“奶牛忧郁将导致产奶量下降。若能了解奶牛的心理状态，便可开发精神
  疾病药物，改善其心情，进而提高一成的产奶量。本人估计，全球奶牛精神疾病药物的市场可达每年 2.5 亿美元。”
  #+END_QUOTE

- 3843-3844, 标注, 2019 年 2 月 25 日星期一 上午 8:24:28
  # note_md5: 7dbc5192e49065c6885fdd208f05206f
  #+BEGIN_QUOTE
  过去 500 年间，科学、帝国和资本之间的回馈循环无疑正是推动历史演进的主要引擎。
  #+END_QUOTE

- 3902-3903, 标注, 2019 年 2 月 25 日星期一 下午 12:57:38
  # note_md5: 39768e2f8abd487f5a2add8e0de537a4
  #+BEGIN_QUOTE
  科学革命与现代帝国主义的关系密不可分。
  #+END_QUOTE

- 3900-3903, 标注, 2019 年 2 月 25 日星期一 下午 12:59:29
  # note_md5: 7fd486aa2987d7f6102de456947947a7
  #+BEGIN_QUOTE
  本。 所以这样说来，库克的船队究竟是有武力保护的科学远征队，还是有几个科学家随行的武力远征军？这个问题就像是问
  车子的油箱该说是半满还是半空一样，其实两者皆是。科学革命与现代帝国主义的关系密不可分。
  #+END_QUOTE

- 3901-3903, 标注, 2019 年 2 月 25 日星期一 下午 12:59:34
  # note_md5: 3c1444d349e4f125e01b9b9c87455f11
  #+BEGIN_QUOTE
  ，库克的船队究竟是有武力保护的科学远征队，还是有几个科学家随行的武力远征军？这个问题就像是问车子的油箱该说是半
  满还是半空一样，其实两者皆是。科学革命与现代帝国主义的关系密不可分。
  #+END_QUOTE

- 3944-3948, 标注, 2019 年 2 月 25 日星期一 下午 1:04:17
  # note_md5: 7bf60e4097492ca775ca0a68785dbfe3
  #+BEGIN_QUOTE
  中国和波斯其实并不缺乏制作蒸汽机的科技（当时要照抄或是购买都完全不成问题），他们缺少的是西方的价值观、故事、司
  法系统和社会政治结构，这些在西方花了数个世纪才形成及成熟，就算想要照抄，也无法在一夕之间内化。之所以法国和美国
  能够很快跟上英国的脚步，是因为他们本来就和英国共享一套最重要的故事和社会结构。而中国和波斯总是追赶不及，则是因
  为整个关于社会的想法和组织就是不同。
  #+END_QUOTE

- 3948-3950, 标注, 2019 年 2 月 25 日星期一 下午 1:04:36
  # note_md5: 05a64747cda806419f039a09b947054e
  #+BEGIN_QUOTE
  虽然这段时期欧洲面对亚洲在科技、政治、军事、经济上并不具有什么明显的优势，但却是在厚植累积独特的潜力，直到 1850
  年左右才终于爆发。
  #+END_QUOTE

- 3948-3953, 标注, 2019 年 2 月 25 日星期一 下午 1:04:58
  # note_md5: 288ab852b7fa058068213df4c00a6560
  #+BEGIN_QUOTE
  虽然这段时期欧洲面对亚洲在科技、政治、军事、经济上并不具有什么明显的优势，但却是在厚植累积独特的潜力，直到 1850
  年左右才终于爆发。虽然欧洲、中国和穆斯林世界在 1750 年看起来还没什么差异，但这其实只是假象。这就像是有两家建筑商
  同时开始兴建高楼，一家使用的是木材和泥砖，另一家则是使用钢筋和混凝土。一开始，两个工地无论兴建速度或是建筑高度
  都相去无几，看起来这两种建法也就没什么差别。但等到一过了某个门槛，木材和泥砖盖的高楼就再也无力支撑，于是颓然倾
  塌，而钢筋和混凝土却还是能屹立不摇，继续向上伸展到人类目光的极限。
  #+END_QUOTE

- 4244-4246, 标注, 2019 年 2 月 25 日星期一 下午 9:49:44
  # note_md5: 132f3e1ccbee27e11f58a38c993834cb
  #+BEGIN_QUOTE
  英、法、德各国学者开始把对雅利安人的语言学理论与达尔文的自然选择理论结合，认为所谓的“雅利安人”不只是语言族群，
  而是某种生物族群，也就是一个种族。
  #+END_QUOTE

- 4253-4255, 标注, 2019 年 2 月 25 日星期一 下午 9:51:45
  # note_md5: 296662fa5fddbaac518e9e14ec50ff26
  #+BEGIN_QUOTE
  今日许多精英分子而言，要比较判断不同人群的优劣，几乎讲的总是历史上的文化差异，而不再是种族上的生物差异。我们不
  再说“这就存在于他们的血液里”，而是说“这就存在于他们的文化里”。
  #+END_QUOTE

- 4253-4255, 标注, 2019 年 2 月 25 日星期一 下午 9:51:49
  # note_md5: 55b1578a2eedbae537794d1743b631e2
  #+BEGIN_QUOTE
  对今日许多精英分子而言，要比较判断不同人群的优劣，几乎讲的总是历史上的文化差异，而不再是种族上的生物差异。我们
  不再说“这就存在于他们的血液里”，而是说“这就存在于他们的文化里”。
  #+END_QUOTE

- 4306-4307, 标注, 2019 年 2 月 26 日星期二 上午 8:27:15
  # note_md5: 54d5c673b6ca3df21717c0ef6f41f58d
  #+BEGIN_QUOTE
  代表我们银行户头上看到的那些金钱，有超过九成其实只是数字，而没有实体的硬币或钞票。
  #+END_QUOTE

- 4311-4312, 标注, 2019 年 2 月 26 日星期二 上午 8:28:12
  # note_md5: 81b31447bd6f26b686563cacfda49b0d
  #+BEGIN_QUOTE
  真正让银行（以及整个经济）得以存活甚至大发利市的，其实是我们对未来的信任。“信任”就是世上绝大多数金钱的唯一后盾。
  #+END_QUOTE

- 4371-4372, 标注, 2019 年 2 月 26 日星期二 下午 8:18:01
  # note_md5: f7303d68a88750cf6da14e8e8fa5cf3f
  #+BEGIN_QUOTE
  人类全体财富的基础，就在于希望增加个人利润的自私心理。
  #+END_QUOTE

- 4383-4384, 标注, 2019 年 2 月 26 日星期二 下午 8:20:19
  # note_md5: b21e44968fc5222318e9f19d3bbb4c8d
  #+BEGIN_QUOTE
  现代资本主义经济的一大重点，就在于出现了一种新的道德标准：应该把利润拿出来，继续投资生产。这样一来，才能带来更
  多的利润再重新投入生产，再带来更多的利润，如此不断循环。
  #+END_QUOTE

- 4414-4415, 标注, 2019 年 2 月 26 日星期二 下午 9:20:39
  # note_md5: 342d6f94712856ca0d999b0a4905e35b
  #+BEGIN_QUOTE
  资本主义的基本原则在于，因为不论是正义、自由甚至快乐都必须依赖于经济成长，所以可说经济成长就是至善（或至少十分
  接近）。
  #+END_QUOTE

- 4422-4422, 标注, 2019 年 2 月 26 日星期二 下午 9:22:36
  # note_md5: 08ffa5ddeb704e8c19729ad668447055
  #+BEGIN_QUOTE
  资本主义认为经济可以无穷无尽地发展下去，但这和我们日常生活观察到的宇宙现象完全背道而驰。
  #+END_QUOTE

- 4423-4425, 标注, 2019 年 2 月 26 日星期二 下午 9:23:17
  # note_md5: f767f632c8cf6cf7124954d23ebbe0ec
  #+BEGIN_QUOTE
  人类的经济在整个现代时期就是这样不可思议地持续指数成长。唯一的原因，就在于科学家总是能每隔几年就取得另一项发现，
  提出另一项发明，像是美洲大陆、内燃机引擎，或是运用基因工程的羊。印钞票的是银行和政府，但最后埋单的是科学家。
  #+END_QUOTE

- 4456-4458, 标注, 2019 年 2 月 26 日星期二 下午 9:54:52
  # note_md5: 92de8c59f5f67a3969087441ef4f2858
  #+BEGIN_QUOTE
  这就是帝国资本主义的奇妙循环：信贷资助新发现，新发现带来殖民地，殖民地带来利润，利润建立起信任，信任转化为更多
  的信贷。不管是努尔哈赤还是纳迪尔沙国王，帝国扩张几千公里之后就后继无力。但对资本主义的创业者来说，一次一次的征
  服，都让经济的动力更加强大。
  #+END_QUOTE

- 4533-4537, 标注, 2019 年 2 月 26 日星期二 下午 10:03:09
  # note_md5: 969aa1b9ee54110522dacd8e1884afe4
  #+BEGIN_QUOTE
  西印度公司在河口的一座小岛上开拓了一个殖民地，名为“新阿姆斯特丹”（New Amsterdam）。这个殖民地不断遭受美国原住
  民威胁，英国人也多次入侵，最后在 1664 年落入英国手中。英国人将这个城市改名“纽约”（New York，即“新约克”，约克为英
  国郡名）。当时西印度公司曾在殖民地筑起一道墙，用来抵御英国人和美国原住民，这道墙的位置现在成了世界上最著名的街
  道：华尔街（Wall Street，直译为“墙街”）。
  #+END_QUOTE

- 4514-4517, 标注, 2019 年 2 月 26 日星期二 下午 10:03:25
  # note_md5: a29099d752248a1b05ef5ad062401541
  #+BEGIN_QUOTE
  如果你觉得投资某家公司能赚大钱，但当时所有股份都已经卖完了，你还可以从其他的股份持有人那里去买，只是可能付的价
  钱会比当初他们买的时候高。至于如果你买了股份，却发现公司前景堪虑，也可以试着用较低的价格卖出股份。这些买卖大行
  其道，最后的结果就是在欧洲各大主要城市几乎都设立了证券交易所，进行股票交易。
  #+END_QUOTE

- 4560-4562, 标注, 2019 年 2 月 26 日星期二 下午 10:43:41
  # note_md5: 038289892dbcd74bab8dab3ec8bc8bf1
  #+BEGIN_QUOTE
  密西西比泡沫可以说是史上最惨烈的一次金融崩溃。法国王室的金融体系一直没能真正走出这场重大的打击。密西西比公司利
  用其政治影响力操纵股价、推动购买热潮，结果让法国人民对法国金融系统和国王的金融智慧都失去信心。
  #+END_QUOTE

- 4564-4566, 标注, 2019 年 2 月 26 日星期二 下午 10:45:25
  # note_md5: a7a541a246f611335814e8ace965498b
  #+BEGIN_QUOTE
  最后来到路易十六，他在祖父驾崩后继位，但在 18 世纪 80 年代却发现年度预算有一半都得拿来支付利息，财政已濒临破产。到
  了 1789 年，他迫于无奈，不得不召开已经长达一个半世纪未曾召开的三级会议，希望能解决这项危机。就这样，法国大革命揭
  开了序幕。
  #+END_QUOTE

- 4574-4574, 标注, 2019 年 2 月 26 日星期二 下午 10:47:12
  # note_md5: 54cd2287264e5eebcb9dc44ebdb6bd86
  #+BEGIN_QUOTE
  店小二的民族”（
  #+END_QUOTE

- 4579-4580, 标注, 2019 年 2 月 26 日星期二 下午 10:49:13
  # note_md5: a5be8dbc72e4df8143284e09fc977ad9
  #+BEGIN_QUOTE
  讲到国家如何为资本家服务，最恶名昭彰的例子就是中英第一次鸦片战争（1840~1842）。
  #+END_QUOTE

- 4601-4602, 标注, 2019 年 2 月 26 日星期二 下午 10:51:06
  # note_md5: bf90125873cf6a228e419bb4abe8439b
  #+BEGIN_QUOTE
  资本和政治这两者的紧密相拥，对信贷市场有深远的影响。
  #+END_QUOTE

- 4605-4607, 标注, 2019 年 2 月 26 日星期二 下午 10:52:18
  # note_md5: 4b919993f98e7d86a64dc5a9c023294c
  #+BEGIN_QUOTE
  正因如此，今天在判断某个国家的信用评级时，经济体系是否健全远比天然资源的多寡更为重要。信用评级代表的是国家清偿
  债务的可能性。除了纯粹的经济数据外，也会考虑政治、社会甚至文化因素。
  #+END_QUOTE

- 4622-4625, 标注, 2019 年 2 月 26 日星期二 下午 10:54:41
  # note_md5: 8d759a4ca42e0c50c25ab252f12fd465
  #+BEGIN_QUOTE
  这世界上根本不可能有完全不受政治影响的市场。毕竟，经济最重要的资源就是“信任”，而信任这种东西总是得面对种种的坑
  蒙拐骗。光靠着市场本身，并无法避免诈欺、窃盗和暴力的行为。这些事得由政治系统下手，立法禁止欺诈，并用警察、法庭
  和监狱来执行法律。
  #+END_QUOTE

- 4638-4639, 标注, 2019 年 2 月 26 日星期二 下午 10:56:31
  # note_md5: d76683b2be94b20fd1fde3beffb5c6b0
  #+BEGIN_QUOTE
  奴隶贸易这场灾难的罪魁祸首并不是暴君或是种族主义者，而是不受限制的市场力量。
  #+END_QUOTE

- 4648-4651, 标注, 2019 年 2 月 26 日星期二 下午 10:58:07
  # note_md5: 4a5406fd6587b8c17cfe6a708b7b10f4
  #+BEGIN_QUOTE
  16 世纪到 19 世纪，大约有 1000 万非洲奴隶被运到美洲，其中有大约七成都在甘蔗园里工作。奴隶的劳动条件极度恶劣，大多数
  奴隶生活悲惨、英年早逝。而且欧洲人发动战争俘虏非洲人，再从非洲内陆千里迢迢运至美洲，数百万非洲人就这样在战乱或
  运送过程中丧命。而这一切，不过就是为了让欧洲人能够在茶里加糖、能吃到甜点，让人能够靠着贩糖而获取暴利。
  #+END_QUOTE

- 4651-4652, 标注, 2019 年 2 月 26 日星期二 下午 10:58:23
  # note_md5: e200f4702310daf9e6fe8ea80c6b60f2
  #+BEGIN_QUOTE
  奴隶贸易背后的黑手并不是国家或政府。
  #+END_QUOTE

- 4659-4660, 标注, 2019 年 2 月 26 日星期二 下午 10:59:45
  # note_md5: 8119a74c0d928945b1058edd086a890e
  #+BEGIN_QUOTE
  因为人类有追求利润和经济成长的渴望，就会决定盲目扫除一切可能的阻挠。等到“
  #+END_QUOTE

- 4659-4660, 标注, 2019 年 2 月 26 日星期二 下午 10:59:51
  # note_md5: 71e64872249b1c5d148f5abc535b4eeb
  #+BEGIN_QUOTE
  因为人类有追求利润和经济成长的渴望，就会决定盲目扫除一切可能的阻挠。等到“成长”成了无上的目标、不受其他道德伦理
  考虑的制衡，就很容易衍生成一场灾难
  #+END_QUOTE

- 4665-4665, 标注, 2019 年 2 月 26 日星期二 下午 11:00:55
  # note_md5: 279db9b05523cf59527b665282a3b9bb
  #+BEGIN_QUOTE
  人类的历史从来不是洁白无邪，大西洋奴隶贸易这件事绝非特例。
  #+END_QUOTE

- 4766-4767, 标注, 2019 年 2 月 26 日星期二 下午 11:12:48
  # note_md5: d18639a6ec98a079db1a69ba79533ebf
  #+BEGIN_QUOTE
  工业革命的核心，其实就是能源转换的革命。
  #+END_QUOTE

- 4767-4769, 标注, 2019 年 2 月 26 日星期二 下午 11:13:05
  # note_md5: 114fdd08030bf9d0e8563be07745a05d
  #+BEGIN_QUOTE
  我们能使用的能源其实无穷无尽。讲得更精确，唯一的限制只在于我们的无知。每隔几十年，我们就能找到新的能源来源，所
  以人类能用的能源总量其实在不断增加。
  #+END_QUOTE

- 4771-4773, 标注, 2019 年 2 月 26 日星期二 下午 11:14:06
  # note_md5: a4e1bc1fca58e67b7d74a32a22ae8dc9
  #+BEGIN_QUOTE
  太阳的能量只有一小部分会到达地球，但即使是这一小部分，就已经高达每年 3766800 艾焦（焦耳是能量单位，在地心引力下
  将一颗小苹果抬升一米，所需的能量就是一焦耳；至于艾焦则是 1018 焦耳，这可是很多很多颗苹果。）
  #+END_QUOTE

- 4784-4787, 标注, 2019 年 2 月 26 日星期二 下午 11:15:30
  # note_md5: 5589b74e59a3107e2be4c937b3780f0b
  #+BEGIN_QUOTE
  化学家一直要到 19 世纪 20 年代才发现铝这种金属，但当时要从矿石中分离出铝非常困难，而且昂贵。于是，有几十年间，铝的
  价值甚至比黄金还要高得多。在 19 世纪 60 年代，法国皇帝拿破仑三世还会用铝质餐具来宴请最尊贵的客人，至于那些二等的客
  人，就只能用黄金的刀叉来凑合凑合。
  #+END_QUOTE

- 4813-4814, 标注, 2019 年 2 月 26 日星期二 下午 11:17:41
  # note_md5: 9d8e85506b66b3ab3df2fb3b498671a1
  #+BEGIN_QUOTE
  这些动物的一生就像是巨大生产线的齿轮，决定它们生命长短及质量的，就只是各种商业组织的利润和亏损。
  #+END_QUOTE

- 4819-4820, 标注, 2019 年 2 月 26 日星期二 下午 11:18:25
  # note_md5: f0430d8b4789426b26306c65691f5362
  #+BEGIN_QUOTE
  猪的智商和好奇心在哺乳动物里数一数二，可能只低于巨猿。
  #+END_QUOTE

- 4830-4831, 标注, 2019 年 2 月 26 日星期二 下午 11:19:46
  # note_md5: 9fc59d8f2ceccfaedb3be4e3466ed834
  #+BEGIN_QUOTE
  大西洋奴隶贸易并非出于对非洲人的仇恨，而现代畜牧业也同样不是出于对动物的仇恨。这两者背后共同的推手，就是冷漠。
  #+END_QUOTE

- 4833-4834, 标注, 2019 年 2 月 27 日星期三 上午 7:59:30
  # note_md5: 5ac22362be9c0218ec5e22dff44d68f4
  #+BEGIN_QUOTE
  最近也赤裸裸指出这些哺乳动物和鸟类同样有复杂的感觉和情绪。它们不仅能感受到生理上的痛苦，也同样能感受到心理情绪
  上的痛苦。
  #+END_QUOTE

- 4834-4834, 笔记, 2019 年 2 月 27 日星期三 上午 7:59:57
  # note_md5: 711586c8817eb2a18158e9d02efdc2f6
  #+BEGIN_QUOTE
  猩球崛起吧
  #+END_QUOTE

- 4842-4844, 标注, 2019 年 2 月 27 日星期三 上午 8:01:33
  # note_md5: 7cf498bc998ab9998b9780321b5b35eb
  #+BEGIN_QUOTE
  这是演化心理学的基本道理：过去在野外形成的种种需求，就算现在已经不是生存和繁殖所必要，仍然会持续造成主观的感受。
  工业化农业的悲剧在于，它一味强调动物的客观需求，却忽略了它们的主观需要。
  #+END_QUOTE

- 4871-4872, 标注, 2019 年 2 月 27 日星期三 上午 8:06:19
  # note_md5: a9bb8e4461e44cca4eb2f85df6ffab3c
  #+BEGIN_QUOTE
  现代资本主义经济如果想要存活，就得不断提高产量，很像是鲨鱼，如果不一直游动就会窒息。然而，
  #+END_QUOTE

- 4871-4872, 标注, 2019 年 2 月 27 日星期三 上午 8:06:28
  # note_md5: ff447c2a1d85d2427b7515a0df662364
  #+BEGIN_QUOTE
  现代资本主义经济如果想要存活，就得不断提高产量，很像是鲨鱼，如果不一直游动就会窒息。
  #+END_QUOTE

- 4872-4873, 标注, 2019 年 2 月 27 日星期三 上午 8:07:07
  # note_md5: 2a2074544efa6e56c7e28cb42db17222
  #+BEGIN_QUOTE
  大吉。为了避免这种灾难，确保不管什么新产品都有人买账，就出现了一种新的伦理观：消费主义。
  #+END_QUOTE

- 4871-4873, 标注, 2019 年 2 月 27 日星期三 上午 8:07:11
  # note_md5: 14d8aefc2db0176d63f4afcfc2d2e67f
  #+BEGIN_QUOTE
  现代资本主义经济如果想要存活，就得不断提高产量，很像是鲨鱼，如果不一直游动就会窒息。然而，光是生产还不够。生产
  出来之后，还得有人买，否则业者或投资人都得关门大吉。为了避免这种灾难，确保不管什么新产品都有人买账，就出现了一
  种新的伦理观：消费主义。
  #+END_QUOTE

- 4877-4878, 标注, 2019 年 2 月 27 日星期三 上午 8:07:18
  # note_md5: 89b4cadfc0bde20e7bbd8f3cb2717fa1
  #+BEGIN_QUOTE
  消费主义的美德就是消费更多的产品和服务，鼓励所有人应该善待自己、宠爱自己，就算因为过度消费而慢慢走上绝路，也是
  在所不惜。
  #+END_QUOTE

- 4889-4891, 标注, 2019 年 2 月 27 日星期三 上午 8:08:23
  # note_md5: 6a1a6e9affa6ed0a7211de036a1d199b
  #+BEGIN_QUOTE
  制造商设计产品的时候，刻意让它在一段短时间后就被淘汰；而且就算旧型号明明就足以满足各种需求，厂商还是会不断推出
  新型号，我们如果不跟进，就仿佛显得落伍。
  #+END_QUOTE

- 4888-4891, 标注, 2019 年 2 月 27 日星期三 上午 8:08:34
  # note_md5: 4f55388b70cc182321ccacbcb2818085
  #+BEGIN_QUOTE
  我们都成了乖巧的消费者，买了无数种我们并不真正需要的产品，而且有的根本就是昨天才知道的。制造商设计产品的时候，
  刻意让它在一段短时间后就被淘汰；而且就算旧型号明明就足以满足各种需求，厂商还是会不断推出新型号，我们如果不跟进，
  就仿佛显得落伍。
  #+END_QUOTE

- 4901-4903, 标注, 2019 年 2 月 27 日星期三 上午 8:09:58
  # note_md5: 0fa496ad5fb73c8060c6fbda82b0a098
  #+BEGIN_QUOTE
  在中世纪欧洲，贵族浪掷千金、尽享奢华，而农民则是省吃俭用、锱铢必较。但今天情况正相反。大富豪管理资产和投资非常
  谨慎，反而是没那么有钱的人，买起没那么需要的汽车和电视机却毫不手软。
  #+END_QUOTE

- 4903-4904, 标注, 2019 年 2 月 27 日星期三 上午 8:10:20
  # note_md5: c3ca0d0d27d97cff7d27bb217d805f5b
  #+BEGIN_QUOTE
  资本主义和消费主义的伦理可以说是一枚硬币的正反两面，将这两种秩序合而为一。有钱人的最高指导原则是——“投资！”而我
  们这些其他人的最高指导原则则是——“购买！”
  #+END_QUOTE

- 4931-4933, 标注, 2019 年 2 月 27 日星期三 下午 12:55:56
  # note_md5: a30e1228db27eda321866464ee8bbdab
  #+BEGIN_QUOTE
  随着人类试图用自己的力量来对抗自然，压制整个生态系统来满足自己的需求和冲动，就可能引发越来越多无法预期的危险副
  作用。到了那个时候，可能就得用更激烈的手法才能操控生态系统，但也就会引起更大的混乱。
  #+END_QUOTE

- 4935-4938, 标注, 2019 年 2 月 27 日星期三 下午 12:56:31
  # note_md5: 11638a9b29f69a2448dc1150ebf752dd
  #+BEGIN_QUOTE
  老鼠和蟑螂可说是正在全盛时期。如果今天发生核灾而让世界末日降临，这些顽强的动物很有可能就会从闷烧的废墟里爬出来，
  准备好继续将自己的 DNA 传给千代万代。或许，现在的 6500 万年后，会有一群高智商的老鼠心怀感激地回顾人类造成的这场灾
  难，就像我们现在感谢那颗杀死恐龙的陨石一般。
  #+END_QUOTE

- 5093-5094, 标注, 2019 年 2 月 27 日星期三 下午 9:23:46
  # note_md5: d9ac23acf56d107cdadd94cf0aed2e31
  #+BEGIN_QUOTE
  不论是民族还是消费大众，其实都和钱、有限公司和人权相同，是一种“主体间”的现实，虽然只存在于我们的集体想象之中，
  但力量却无比巨大。
  #+END_QUOTE

- 5112-5113, 标注, 2019 年 2 月 27 日星期三 下午 9:25:28
  # note_md5: 721e6caba1b701eccbac2bc71d8c032c
  #+BEGIN_QUOTE
  所谓民族的社群概念不断被一群又一群的消费者削弱。这些消费者彼此并不认识，但都有同样的消费习惯和兴趣，因此不但相
  信还定义大家就是同一伙的。
  #+END_QUOTE

- 5139-5141, 标注, 2019 年 2 月 27 日星期三 下午 10:08:50
  # note_md5: 2fbf3d3f705bb343f5b9b08efc452269
  #+BEGIN_QUOTE
  狄更斯写到法国大革命，就说“这是最好的年代，也是最坏的年代”。这句话不只适用于法国大革命，很可能也适用着由法国大
  革命揭开的整个时期。
  #+END_QUOTE

- 5148-5149, 标注, 2019 年 2 月 27 日星期三 下午 10:10:42
  # note_md5: c53a2a3fb914bd428114a7a718de423a
  #+BEGIN_QUOTE
  因为战争变成少见的事，也让战争吸引了更多关注。许多人紧盯着阿富汗和伊拉克战争肆虐，但没什么
  #+END_QUOTE

- 5148-5149, 标注, 2019 年 2 月 27 日星期三 下午 10:10:49
  # note_md5: 90bae91a6eedb96df09f747c6d9117f9
  #+BEGIN_QUOTE
  因为战争变成少见的事，也让战争吸引了更多关注。许多人紧盯着阿富汗和伊拉克战争肆虐，但没什么人特别想到巴西和印度
  一片安详。
  #+END_QUOTE

- 5253-5254, 标注, 2019 年 2 月 28 日星期四 上午 7:44:45
  # note_md5: 89620f06f07da360efb98b0805809401
  #+BEGIN_QUOTE
  现在有四大因素形成了一个良性循环。核子末日的威胁促进了和平主义；和平主义大行其道，于是战争退散、贸易兴旺；贸易
  成长，也就让和平的利润更高，而战争的成本也更高。
  #+END_QUOTE

- 5258-5258, 标注, 2019 年 2 月 28 日星期四 上午 7:45:46
  # note_md5: 3d101baff82410546b9c16a28a82872d
  #+BEGIN_QUOTE
  全面性的战争也不可能独自发动。
  #+END_QUOTE

- 5267-5268, 标注, 2019 年 2 月 28 日星期四 上午 7:48:58
  # note_md5: 48eb2519e5e9b51d8d7e8283614047ce
  #+BEGIN_QUOTE
  可以说我们正在天堂和地狱的岔路口，而我们还不知道自己会朝向哪一个方向。历史还没告诉我们该挑哪边，而只要发生某些
  巧合，往哪边走都不算意外。
  #+END_QUOTE

- 5300-5301, 标注, 2019 年 2 月 28 日星期四 上午 7:58:20
  # note_md5: 840ce1529b90b4bc4079b960b411d99a
  #+BEGIN_QUOTE
  历史一再证实，人类有了权力或能力就可能滥用，所以要说能力越高就越幸福，看来实在有些天真。
  #+END_QUOTE

- 5328-5329, 标注, 2019 年 2 月 28 日星期四 上午 8:03:23
  # note_md5: 19363dd9c8a515523e57f193301f8834
  #+BEGIN_QUOTE
  要评估全球幸福程度的时候，只看上层阶级、只看欧洲人、只看男性，都是巨大的错误。而且，或许只看人类也同样有失公允。
  #+END_QUOTE

- 5363-5365, 标注, 2019 年 2 月 28 日星期四 下午 12:47:29
  # note_md5: 6b4ce53b6da56fb877f459767bf7de79
  #+BEGIN_QUOTE
  对快乐与否的影响，家庭和社群要比金钱和健康来得重要。那些家庭关系紧密良好、社群互相扶持帮助的人，明显比较快乐。
  而那些家庭机能失调、一直无法融入某个社群的人则明显比较不快乐。
  #+END_QUOTE

- 5375-5376, 标注, 2019 年 2 月 28 日星期四 下午 12:48:33
  # note_md5: e1a778b67d2a9ec48ea869cb8a2bff28
  #+BEGIN_QUOTE
  在于：快乐并不在于任何像是财富、健康甚至社群之类的客观条件，而在于客观条件和主观期望之间是否相符。
  #+END_QUOTE

- 5408-5410, 标注, 2019 年 2 月 28 日星期四 下午 1:20:14
  # note_md5: 6ff5b2e6482dc5e56911e6eeb16f29a4
  #+BEGIN_QUOTE
  就算是长生不老也可能会导致不满。假设科学找出了能够医治所有疾疾的万灵丹，加上有效抗老疗程和再生治疗，能够让人永
  葆青春，那么，最可能发生的事，就是整个世界感到空前的愤怒和焦虑。
  #+END_QUOTE

- 5431-5434, 标注, 2019 年 2 月 28 日星期四 下午 1:22:25
  # note_md5: 85d5fa0c76dd29fe4d3472d034fe55c2
  #+BEGIN_QUOTE
  演化就把快感当成奖赏，鼓励男性和女性发生性行为、将自己的基因传下去。如果性交没有高潮，大概很多男性就不会那么热
  衷。但同时，演化也确保高潮得迅速退去。如果性高潮永续不退，可以想象男性会非常开心，但连觅食的动力都没了，最后死
  于饥饿，而且也不会有兴趣再去找下一位能够繁衍后代的女性。
  #+END_QUOTE

- 5437-5443, 标注, 2019 年 2 月 28 日星期四 下午 1:24:13
  # note_md5: 1910e3f534687b52b9d484b0001cb4b7
  #+BEGIN_QUOTE
  如果说快乐的程度是由 1 到 10 分，有些人的生化机制天生开朗，就会允许自己的情绪在 6 到 10 分之间来回，大约稳定在 8 分附近。
  像这样的人，就算住在一个冷漠的大城市，碰上金融市场崩溃而丧失了所有积蓄，还被诊断患有糖尿病，还是会相当愉快乐观。
  也有些人，就是倒霉有着天生阴郁的生化机制，情绪在 3 到 7 分之间来回，大约稳定在 5 分附近。像这样的人，就算得到了密切
  社群的支持，中了几千万的乐透，健康得可以当奥运选手，还是会相当忧郁悲观。事实上，如果是这位天生忧郁的朋友，就算
  她早上中了几十亿的乐透，中午又同时找到了治愈艾滋病和癌症的方法，下午帮忙让以色列和巴勒斯坦达成和平，晚上又终于
  和失散多年的孩子团聚，她感受到的快乐程度仍然顶多就是 7 分而已。不论如何，她的大脑就是没办法让她乐不可支。
  #+END_QUOTE

- 5467-5468, 标注, 2019 年 2 月 28 日星期四 下午 8:07:16
  # note_md5: 57a45b034f51c21afecefd2ebba2d456
  #+BEGIN_QUOTE
  对大脑来说，它完全不知道豪宅要比土屋舒适太多，它只知道现在的血清素浓度是 X。所以，这位企业家快乐的程度，并不会
  比那位足以当他高高高高高祖父的农夫来得高。
  #+END_QUOTE

- 5520-5521, 标注, 2019 年 2 月 28 日星期四 下午 8:12:40
  # note_md5: e82f7cfb754f79f6fb79d9374ca5231d
  #+BEGIN_QUOTE
  如果快乐是在于感受快感，想要更快乐，就得操纵我们的生化系统。如果快乐是在于觉得生命有意义，想要更快乐，就得要骗
  自己骗得更彻底。
  #+END_QUOTE

- 5520-5523, 标注, 2019 年 2 月 28 日星期四 下午 8:19:12
  # note_md5: 780178a462d93769416478759c92913e
  #+BEGIN_QUOTE
  如果快乐是在于感受快感，想要更快乐，就得操纵我们的生化系统。如果快乐是在于觉得生命有意义，想要更快乐，就得要骗
  自己骗得更彻底。还有没有第三种可能呢？ 以上两种论点都有一个共同假设：快乐是一种主观感受（不管是感官的快感还是
  生命有意义），而想要判断快不快乐，靠的就是直接问他们的感受
  #+END_QUOTE

- 5520-5523, 标注, 2019 年 2 月 28 日星期四 下午 8:19:20
  # note_md5: b0c60daf1d2e426f83d08e8bd5841791
  #+BEGIN_QUOTE
  如果快乐是在于感受快感，想要更快乐，就得操纵我们的生化系统。如果快乐是在于觉得生命有意义，想要更快乐，就得要骗
  自己骗得更彻底。还有没有第三种可能呢？ 以上两种论点都有一个共同假设：快乐是一种主观感受（不管是感官的快感还是
  生命有意义），而想要判断快不快乐，靠的就是直接问他们的感受。很多人可
  #+END_QUOTE

- 5520-5523, 标注, 2019 年 2 月 28 日星期四 下午 8:19:24
  # note_md5: 8695af0e2940a1b774f945a8b1fa86f9
  #+BEGIN_QUOTE
  如果快乐是在于感受快感，想要更快乐，就得操纵我们的生化系统。如果快乐是在于觉得生命有意义，想要更快乐，就得要骗
  自己骗得更彻底。还有没有第三种可能呢？ 以上两种论点都有一个共同假设：快乐是一种主观感受（不管是感官的快感还是
  生命有意义），而想要判断快不快乐，靠的就是直接问他们的感受。
  #+END_QUOTE

- 5601-5603, 标注, 2019 年 2 月 28 日星期四 下午 9:15:02
  # note_md5: ef07b694bba387538795c7f38c0e423a
  #+BEGIN_QUOTE
  一直到相对不久之前，微生物都是地球上唯一的生物，而且能够完成某些神奇的任务。属于某个物种的微生物，可以从完全不
  同的物种中取得基因码、加入自己的细胞中，从而取得新的能力，例如对抗生素产生抗药性。
  #+END_QUOTE

- 5608-5611, 标注, 2019 年 2 月 28 日星期四 下午 9:18:08
  # note_md5: 617bb159ce492bfe7aa6ff94babdb01c
  #+BEGIN_QUOTE
  大约 1 万年前，因为出现了农业革命，让古老的系统首次有了突破。那些还是希望鸡能够又肥又慢的智人，发现如果找出长得
  最肥的母鸡，再把它与动得最慢的公鸡交配，生出来的后代就会又肥又慢。这些生下来的后代再继续互相交配，后代的鸡就都
  具有又肥又慢的特点。这是一种原本不存在于自然界的鸡，之所以经过这样的智慧设计而出现，是因为人而不是神。
  #+END_QUOTE

- 5611-5611, 笔记, 2019 年 2 月 28 日星期四 下午 9:18:36
  # note_md5: 03557759cd817692d168be9773fdc4b7
  #+BEGIN_QUOTE
  本来不会出现的组合
  #+END_QUOTE

- 5629-5630, 标注, 2019 年 2 月 28 日星期四 下午 9:25:48
  # note_md5: 5367fd59a946d94a8c5c764bcb156a25
  #+BEGIN_QUOTE
  有三种方式可能让智慧设计取代自然选择：生物工程（biological engineering）、仿生工程（cyborg engineering）与无机
  生命（inorganic life）工程。
  #+END_QUOTE

- 5634-5635, 标注, 2019 年 2 月 28 日星期四 下午 9:26:16
  # note_md5: 152136848828895fff99cde57af498f9
  #+BEGIN_QUOTE
  英文里，未阉割的公牛称为“bull”，阉割后的称为“ox”，
  #+END_QUOTE

- 5699-5700, 标注, 2019 年 2 月 28 日星期四 下午 9:50:02
  # note_md5: 6d308656e24ce6dc32235f24d809731b
  #+BEGIN_QUOTE
  操纵基因并不一定会让智人大批死亡而绝种，但很可能会让智人这个物种大幅改变，到最后就成了另一个物种，而不宜再使用
  智人这个名称。
  #+END_QUOTE

- 5798-5801, 标注, 2019 年 2 月 28 日星期四 下午 9:58:48
  # note_md5: c4bf4f3ac57a859572881ac6479b8a0f
  #+BEGIN_QUOTE
  未来科技的真正潜力并不在于改变什么车辆或武器，而在于改变智人本身，包括我们的情感、我们的欲望。宇宙飞船其实只是
  小事，真正会惊天动地的，可能是能够永远年轻的生化人，既不繁衍后代，也没有性欲，能够直接和其他生物共享记忆，而且
  专注力和记性是现代人类的一千倍以上，不会愤怒、不会悲伤，而他们的情感和欲望完全是我们所无法想象的。
  #+END_QUOTE

- 5846-5847, 标注, 2019 年 2 月 28 日星期四 下午 10:03:59
  # note_md5: 5dc05070664d2b5edc56029ed17b353d
  #+BEGIN_QUOTE
  吉尔伽美什
  #+END_QUOTE

- 957-1027, 标注, unknown
  # note_md5: 2cca84392fb4e14a098f60ec9506a740
  #+BEGIN_QUOTE
  大约就是在距今 7 万到 3 万年前，出现了新的思维和沟通方式，这也正是所谓的认知革命
  #+END_QUOTE

- 1334-1456, 标注, unknown
  # note_md5: f31f994e3a550c9cc8ee6068d7abbbab
  #+BEGIN_QUOTE
  爱尔兰岛曾经住着一些智人，他们会使用一种叫作黑曜石的火山晶体，制造出特别坚硬且尖锐的工具。然而，新爱尔兰岛其实
  并不产黑曜石。化验结果显示，他们用的黑曜石来自超过 400 公里远的新不列颠岛。
  #+END_QUOTE

- 6193-6385, 标注, unknown
  # note_md5: 45adc9fe1cfcb76aa039671c1379603a
  #+BEGIN_QUOTE
  记在人脑里的信息找起来非常方便。以我自己为例，虽然我的大脑里藏着几千兆位的数据，但我可以几乎是立刻想起意大利首
  都的名字，再想起我在 2001 年“9·11”事件那天做了什么，还能马上想出从我家到耶路撒冷希伯来大学的路线。至今，大脑为
  何能做到这样仍然是一个谜，但我们都知道它的检索系统效率惊人。（只不过，找钥匙这件事可能是个例外。）
  #+END_QUOTE

- 6671-6869, 标注, unknown
  # note_md5: 4f547451195ef864a257b6f6c12bdd1e
  #+BEGIN_QUOTE
  这种文字是由 10 个符号组成，代表从 0 到 9 的数字。很容易让人搞错的一点在于，虽然这些符号现在被称为“阿拉伯数字”，
  但其实是印度人发明的。而且现代阿拉伯人自己还用了一组和西方颇不相同的数字符号系统，就更叫人一头雾水。之所以现在
  我们会称“阿拉伯数字”，是因为阿拉伯人攻打印度时发现了这套实用的系统，再加以改良传到中东，进而传入欧洲。等到
  #+END_QUOTE

- 6871-7067, 标注, unknown
  # note_md5: 620b4ad81b5588e9e1e2574b1dad2510
  #+BEGIN_QUOTE
  这种文字是由 10 个符号组成，代表从 0 到 9 的数字。很容易让人搞错的一点在于，虽然这些符号现在被称为“阿拉伯数字”，
  但其实是印度人发明的。而且现代阿拉伯人自己还用了一组和西方颇不相同的数字符号系统，就更叫人一头雾水。之所以现在
  我们会称“阿拉伯数字”，是因为阿拉伯人攻打印度时发现了这套实用的系统，再加以改良传到中东，进而传入欧洲。
  #+END_QUOTE

- 8451-8526, 标注, unknown
  # note_md5: 93314c22f3f2cd0ef99a11f7c25d8806
  #+BEGIN_QUOTE
  但从意识形态观点，公元前的 1000 年间慢慢发展出“世界一家”的观念，这点的重要性也绝对不在其
  #+END_QUOTE

- 8528-8605, 标注, unknown
  # note_md5: ddf91dedb3e69a3d577c56f6f5250ac1
  #+BEGIN_QUOTE
  但从意识形态观点，公元前的 1000 年间慢慢发展出“世界一家”的观念，这点的重要性也绝对不在其下。
  #+END_QUOTE

- 8975-9303, 标注, unknown
  # note_md5: 896de2849ea7ba2255e1f039b953db4a
  #+BEGIN_QUOTE
  1519 年，墨西哥原本还是个遗世独立的人类社会，但来自西班牙的殖民者荷南·科尔特斯（Hernán Cortés）一行人大举入侵。
  这里的人自称阿兹特克人，很快就发现这些外来的西班牙人看到某种黄色金属就眼睛为之一亮，思思念念，三句不离。阿兹特
  克人也不是不懂黄金。黄金色泽美丽，又容易加工，所以他们常用来制作首饰和雕像。阿兹特克人偶尔也用金粉来交易，但一
  般想买东西的时候，通常还是用可可豆或布料来付账。所以，看到西班牙人对黄金如此痴迷，他们实在是一头雾水。毕竟，黄
  金不能吃、不能喝、不能织，想当作工具或武器，质地又太软，究竟为什么西班牙人为之如此疯狂？面对当地人的疑惑，科尔
  特斯表示：“我们这群人有种心病，
  #+END_QUOTE

- 9305-9643, 标注, unknown
  # note_md5: 987f0319a3566d86a2bb663ac7f7fd34
  #+BEGIN_QUOTE
  1519 年，墨西哥原本还是个遗世独立的人类社会，但来自西班牙的殖民者荷南·科尔特斯（Hernán Cortés）一行人大举入侵。
  这里的人自称阿兹特克人，很快就发现这些外来的西班牙人看到某种黄色金属就眼睛为之一亮，思思念念，三句不离。阿兹特
  克人也不是不懂黄金。黄金色泽美丽，又容易加工，所以他们常用来制作首饰和雕像。阿兹特克人偶尔也用金粉来交易，但一
  般想买东西的时候，通常还是用可可豆或布料来付账。所以，看到西班牙人对黄金如此痴迷，他们实在是一头雾水。毕竟，黄
  金不能吃、不能喝、不能织，想当作工具或武器，质地又太软，究竟为什么西班牙人为之如此疯狂？面对当地人的疑惑，科尔
  特斯表示：“我们这群人有种心病，只有金子能医。”51
  #+END_QUOTE

- 9718-9880, 标注, unknown
  # note_md5: 80d7016749aec219071040c13ac3cd4d
  #+BEGIN_QUOTE
  全球金钱总和为 60 兆美元，但所有硬币和钞票的金额加起来还不到 6 兆美元。57 换句话说，所有的钱有超过九成（超过
  50 兆美元！）都只是显示在计算机上的数字而已。正因如此，大多数的商业交易其实只是把某台计算机里的电子数据搬到另
  一台去，而完全没有任何实体金钱的交换。
  #+END_QUOTE

- 10633-10756, 标注, unknown
  # note_md5: 29b484045671ee01d6ef28ed060e78df
  #+BEGIN_QUOTE
  至于现代许多的美国人，他们也认为美国必须负起道义责任，让第三世界国家同样享有民主和人权，就算这得靠巡航导弹和
  F-16 战机，也是在所不惜。 帝国所传播的文化理念很少只来自那一小群的统治精英。
  #+END_QUOTE

- 10758-10853, 标注, unknown
  # note_md5: f8f53d54b4180ba06bf76768a14753eb
  #+BEGIN_QUOTE
  现代许多的美国人，他们也认为美国必须负起道义责任，让第三世界国家同样享有民主和人权，就算这得靠巡航导弹和 F-16
  战机，也是在所不惜。
  #+END_QUOTE

- 11185-11342, 标注, unknown
  # note_md5: 07d9098c0a53243a5a8208933feea02e
  #+BEGIN_QUOTE
  然而事实证明，就算把这些迫害的所有受害者全部加起来，在这 3 个世纪间，多神教古罗马处决基督徒的人数不超过几千人。
  64 但相对的是，在接下来的 1500 年间，虽然基督教号称主张爱与怜悯，但仅仅对信仰的诠释有些许差异，就引发基督徒自
  相残杀，死亡人数达到数百万。
  #+END_QUOTE

- 15272-15432, 标注, unknown
  # note_md5: ede478b43400f8edf3e2ceb289c7a855
  #+BEGIN_QUOTE
  如果要在过去 500 年间挑出一个最重大、具代表性的一刻，一定就是 1945 年 7 月 16 日上午 5 点 29 分 45 秒。就在这
  一秒，美国科学家在新墨西哥的阿拉莫戈多引爆了第一颗原子弹。从这时开始，人类不仅有了改变历史进程的能力，更有了结
  束历史进程的能力。
  #+END_QUOTE

- 15617-15826, 标注, unknown
  # note_md5: 5624b80065b2387754f69b187277360a
  #+BEGIN_QUOTE
  我们希望能够赞助纯科学，不要受到政治、经济或宗教利益干扰，很有可能还是无法成功。毕竟，人类的资源有限。如果要求
  美国国会议员为美国国家科学基金会多拨 100 万美元来从事基础研究，他一定会理直气壮地问，如果这笔钱拿来做教师培训
  或是补助他选区某个陷入困境的工厂，不是更能把钱花在刀刃上吗？正因为资源有限，我们就必须回答像是“什么更重要”和
  “怎样才算花得适当”这种问题。
  #+END_QUOTE

- 15828-16019, 标注, unknown
  # note_md5: d507bc9001e89dc2ca1649f2fc978f67
  #+BEGIN_QUOTE
  如果他所在的社会更重视的是牛奶的商业潜力及人民的健康安全，而不那么重视奶牛的情感需求，他最好还是改写一下研究计
  划，以迎合那些心态。举例来说，计划书可以写道：“奶牛忧郁将导致产奶量下降。若能了解奶牛的心理状态，便可开发精神
  疾病药物，改善其心情，进而提高一成的产奶量。本人估计，全球奶牛精神疾病药物的市场可达每年 2.5 亿美元。”
  #+END_QUOTE

- 16021-16089, 标注, unknown
  # note_md5: 90024d3f45cecb06a1f0e784fa77b9e9
  #+BEGIN_QUOTE
  过去 500 年间，科学、帝国和资本之间的回馈循环无疑正是推动历史演进的主要引擎。
  #+END_QUOTE

- 16596-16691, 标注, unknown
  # note_md5: 1f4c38dbb62dc62d954f7429ab5930f7
  #+BEGIN_QUOTE
  虽然这段时期欧洲面对亚洲在科技、政治、军事、经济上并不具有什么明显的优势，但却是在厚植累积独特的潜力，直到
  1850 年左右才终于爆发。
  #+END_QUOTE

- 16693-16981, 标注, unknown
  # note_md5: 704adb1f0aac6602bb9d48c8daaee437
  #+BEGIN_QUOTE
  虽然这段时期欧洲面对亚洲在科技、政治、军事、经济上并不具有什么明显的优势，但却是在厚植累积独特的潜力，直到
  1850 年左右才终于爆发。虽然欧洲、中国和穆斯林世界在 1750 年看起来还没什么差异，但这其实只是假象。这就像是有两
  家建筑商同时开始兴建高楼，一家使用的是木材和泥砖，另一家则是使用钢筋和混凝土。一开始，两个工地无论兴建速度或是
  建筑高度都相去无几，看起来这两种建法也就没什么差别。但等到一过了某个门槛，木材和泥砖盖的高楼就再也无力支撑，于
  是颓然倾塌，而钢筋和混凝土却还是能屹立不摇，继续向上伸展到人类目光的极限。
  #+END_QUOTE

- 18097-18333, 标注, unknown
  # note_md5: a9f8586b5d29169ee9955f84ba792ef9
  #+BEGIN_QUOTE
  西印度公司在河口的一座小岛上开拓了一个殖民地，名为“新阿姆斯特丹”（New Amsterdam）。这个殖民地不断遭受美国原住
  民威胁，英国人也多次入侵，最后在 1664 年落入英国手中。英国人将这个城市改名“纽约”（New York，即“新约克”，约克为
  英国郡名）。当时西印度公司曾在殖民地筑起一道墙，用来抵御英国人和美国原住民，这道墙的位置现在成了世界上最著名的
  街道：华尔街（Wall Street，直译为“墙街”）。
  #+END_QUOTE

- 18643-18795, 标注, unknown
  # note_md5: ae3a89304bd699c98fd756d66ed923c7
  #+BEGIN_QUOTE
  最后来到路易十六，他在祖父驾崩后继位，但在 18 世纪 80 年代却发现年度预算有一半都得拿来支付利息，财政已濒临破产。
  到了 1789 年，他迫于无奈，不得不召开已经长达一个半世纪未曾召开的三级会议，希望能解决这项危机。就这样，法国大革
  命揭开了序幕。
  #+END_QUOTE

- 19296-19493, 标注, unknown
  # note_md5: 2f86251492bb20315e559d99495f4875
  #+BEGIN_QUOTE
  16 世纪到 19 世纪，大约有 1000 万非洲奴隶被运到美洲，其中有大约七成都在甘蔗园里工作。奴隶的劳动条件极度恶劣，
  大多数奴隶生活悲惨、英年早逝。而且欧洲人发动战争俘虏非洲人，再从非洲内陆千里迢迢运至美洲，数百万非洲人就这样在
  战乱或运送过程中丧命。而这一切，不过就是为了让欧洲人能够在茶里加糖、能吃到甜点，让人能够靠着贩糖而获取暴利。
  #+END_QUOTE

- 19919-20055, 标注, unknown
  # note_md5: 3f2783e66f6e8adcac585daf008a1a98
  #+BEGIN_QUOTE
  太阳的能量只有一小部分会到达地球，但即使是这一小部分，就已经高达每年 3766800 艾焦（焦耳是能量单位，在地心引力
  下将一颗小苹果抬升一米，所需的能量就是一焦耳；至于艾焦则是 1018 焦耳，这可是很多很多颗苹果。）
  #+END_QUOTE

- 20057-20223, 标注, unknown
  # note_md5: f764ba252dc20ac5c4b91ca394d5f7f6
  #+BEGIN_QUOTE
  化学家一直要到 19 世纪 20 年代才发现铝这种金属，但当时要从矿石中分离出铝非常困难，而且昂贵。于是，有几十年间，
  铝的价值甚至比黄金还要高得多。在 19 世纪 60 年代，法国皇帝拿破仑三世还会用铝质餐具来宴请最尊贵的客人，至于那些
  二等的客人，就只能用黄金的刀叉来凑合凑合。
  #+END_QUOTE

- 21748-21915, 标注, unknown
  # note_md5: ce5a27524caf3a0b037e0b01f9ff759e
  #+BEGIN_QUOTE
  老鼠和蟑螂可说是正在全盛时期。如果今天发生核灾而让世界末日降临，这些顽强的动物很有可能就会从闷烧的废墟里爬出来，
  准备好继续将自己的 DNA 传给千代万代。或许，现在的 6500 万年后，会有一群高智商的老鼠心怀感激地回顾人类造成的这
  场灾难，就像我们现在感谢那颗杀死恐龙的陨石一般。
  #+END_QUOTE

- 23249-23627, 标注, unknown
  # note_md5: 5bd0659f92635002c674066ef7de6b7b
  #+BEGIN_QUOTE
  如果说快乐的程度是由 1 到 10 分，有些人的生化机制天生开朗，就会允许自己的情绪在 6 到 10 分之间来回，大约稳定在
  8 分附近。像这样的人，就算住在一个冷漠的大城市，碰上金融市场崩溃而丧失了所有积蓄，还被诊断患有糖尿病，还是会相
  当愉快乐观。也有些人，就是倒霉有着天生阴郁的生化机制，情绪在 3 到 7 分之间来回，大约稳定在 5 分附近。像这样的
  人，就算得到了密切社群的支持，中了几千万的乐透，健康得可以当奥运选手，还是会相当忧郁悲观。事实上，如果是这位天
  生忧郁的朋友，就算她早上中了几十亿的乐透，中午又同时找到了治愈艾滋病和癌症的方法，下午帮忙让以色列和巴勒斯坦达
  成和平，晚上又终于和失散多年的孩子团聚，她感受到的快乐程度仍然顶多就是 7 分而已。不论如何，她的大脑就是没办法
  让她乐不可支。
  #+END_QUOTE

- 23629-23733, 标注, unknown
  # note_md5: 61e365416f5f5821e4cf0e5d6547e5f4
  #+BEGIN_QUOTE
  对大脑来说，它完全不知道豪宅要比土屋舒适太多，它只知道现在的血清素浓度是 X。所以，这位企业家快乐的程度，并不会
  比那位足以当他高高高高高祖父的农夫来得高。
  #+END_QUOTE

- 24462-24652, 标注, unknown
  # note_md5: 9c07ab284a9f41e0faaff65928dcdb6c
  #+BEGIN_QUOTE
  大约 1 万年前，因为出现了农业革命，让古老的系统首次有了突破。那些还是希望鸡能够又肥又慢的智人，发现如果找出长
  得最肥的母鸡，再把它与动得最慢的公鸡交配，生出来的后代就会又肥又慢。这些生下来的后代再继续互相交配，后代的鸡就
  都具有又肥又慢的特点。这是一种原本不存在于自然界的鸡，之所以经过这样的智慧设计而出现，是因为人而不是神。
  #+END_QUOTE
