:PROPERTIES:
:ID:       32c4b757-3d4c-46c0-a025-16e6991c1bbf
:END:
#+TITLE: [笔记]明亮的夜晚-崔恩荣
#+AUTHOR: Yang,Ying-chao
#+DATE:   2024-10-16
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:   oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+LANGUAGE: en
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :mingliangdey:note:ireader:

- 474-476, 标注, 2024 年 10 月 14 日星期一 下午 6:57:20
  # note_md5: ee2324667fc361df0900498452715095
  #+BEGIN_QUOTE
  “这条铁路有几里长呀？”那个时候，奇怪的是，他感觉自己以前好像经历过这个瞬间。分明就是在那里，那个样子。自己和一
  个脸晒得黑红的女孩站在那里，接着传来了汽笛声，好像还有一只喜鹊往西飞走了……
  #+END_QUOTE

- 637-640, 标注, 2024 年 10 月 14 日星期一 下午 7:08:29
  # note_md5: 158538ed81be9d06418c498c36928f56
  #+BEGIN_QUOTE
  祖母说，以前她一直觉得曾祖母对高祖母的感情是一种负罪感。但后来她才知道，曾祖母对高祖母只有深深的思念。想撒撒娇、
  想要抱抱、想耍赖皮、想得到很多爱、想喊“妈妈，妈妈”，但她只能一一锁起这些心情生活。曾祖母看着祖母喊出妈妈的时候，
  想起了高祖母说过的话。“好吧，你走吧。下辈子我就做你的女儿。到时候我们再见。到时候再见。”
  #+END_QUOTE

- 1151-1153, 标注, 2024 年 10 月 14 日星期一 下午 10:09:46
  # note_md5: 1a497537d251d99596f8fd5ab011e071
  #+BEGIN_QUOTE
  当地球的寿命结束，再过一段更长的时间，到熵值最大的那一瞬间，时间也会消失。那时，人类会成为连自己曾经在宇宙停留
  过的事实都不记得的种族，宇宙会变成再也没有一颗心记得他们的地方。这便是我们的最终结局。
  #+END_QUOTE

- 1163-1164, 标注, 2024 年 10 月 15 日星期二 上午 7:35:48
  # note_md5: 65922525b529b47ebd5040c6f2399232
  #+BEGIN_QUOTE
  所以我只能对它们保持沉默——在不肯倾听自己声音的父母身边长大的孤独，以及和对我没有感情的配偶一起生活的孤独。
  #+END_QUOTE

- 1338-1340, 标注, 2024 年 10 月 15 日星期二 上午 7:46:10
  # note_md5: fa51edc1e37c42dae68967ce221a6141
  #+BEGIN_QUOTE
  新雨大婶把丝线套在祖母的双手上，然后往绕线板上缠线。祖母轻轻晃动着双手，同时望着新雨大婶整齐地将线缠到线板上。
  偶尔两人对视一下，新雨大婶的脸上就会露出灿烂的笑容。有时干完活她们就玩挑花线游戏，两个人用线可以挑出许多好看的
  花样，年幼的祖母觉得神奇极了。
  #+END_QUOTE

- 2319-2321, 标注, 2024 年 10 月 15 日星期二 下午 6:53:54
  # note_md5: a0cb1f4864f28e35c962b1a6e5b0078d
  #+BEGIN_QUOTE
  曾祖母的话音刚落，阿春就从地上站了起来，逐个闻了一下每个人身上的味道，然后便往家的方向走去，直到走出很远才回头
  看了一眼。祖母担心阿春再返回来，不敢叫它的名字。看着阿春远去的背影，祖母无声地哭了，脖子上的围巾都湿透了。从那
  以后再也没有人提起过阿春。
  #+END_QUOTE

- 2467-2467, 标注, 2024 年 10 月 15 日星期二 下午 7:31:51
  # note_md5: ba2a3f1b65729fc9dc516d89b5303ea7
  #+BEGIN_QUOTE
  吃了感冒药睡觉就会做一些彩色的梦。
  #+END_QUOTE

- 2550-2552, 标注, 2024 年 10 月 15 日星期二 下午 7:40:22
  # note_md5: f84823f2331690081519243d533552bc
  #+BEGIN_QUOTE
  她尽量不去想，但还是想起了留在开城的阿春。一路上避难看到的那些情景在眼前一一掠过，她尽量不让自己去想，但站在屋
  檐下看着雨的时候，深藏在内心的思绪就像一直都在等待一个出口那样，接踵而至。那些不可能变出一粒米，也不可能变出一
  片柴的毫无用处的思绪。
  #+END_QUOTE

- 2550-2552, 标注, 2024 年 10 月 15 日星期二 下午 7:40:48
  # note_md5: 0bf471c5ed67856e283481613e1b4a92
  #+BEGIN_QUOTE
  一路上避难看到的那些情景在眼前一一掠过，她尽量不让自己去想，但站在屋檐下看着雨的时候，深藏在内心的思绪就像一直
  都在等待一个出口那样，接踵而至。那些不可能变出一粒米，也不可能变出一片柴的毫无用处的思绪。
  #+END_QUOTE


- 2866-2869, 标注, 2024 年 10 月 15 日星期二 下午 9:08:27
  # note_md5: 710b222297796b88e5a0caf176f0ac25
  # note_md5: c993d4b67c74dcd58a8059b865188005
  #+BEGIN_QUOTE
  但是那天祖母感到了不安。一种在放松警惕的时候、缺乏紧张的时候、以为不会有什么事的时候、摆脱悲观想法的时候、享受
  某个瞬间的时候，就会担心不好的事情再次降临的不安。祖母总觉得，因为即将发生的事情而战战兢兢的时候，即使暂时风平
  浪静，可只要稍微放松一些，就会挨一记闷棍，这就是生活。
  #+END_QUOTE

- 3621-3622, 标注, 2024 年 10 月 16 日星期三 上午 7:48:53
  # note_md5: 597ec26e43957f0968d339b1a0995835
  #+BEGIN_QUOTE
  我说着自己以前从未说过的恶言恶语，却感觉自己受到了这些话的暴击，可是他并没有因为我的话而受伤或内疚。我说出的那
  些话从他那不接纳任何事物的光滑表面被弹回来，打到了我自己的身上。
  #+END_QUOTE

- 3918-3922, 标注, 2024 年 10 月 16 日星期三 上午 8:06:03
  # note_md5: dd39aa22456bde47639f404e8463f2fa
  #+BEGIN_QUOTE
  妈妈说过，平凡的生活就是最好的生活。还说因为和爸爸结婚，自己也组建了平凡的家庭，因此她很高兴。以前我不太理解总
  是把这些话挂在嘴边的妈妈。我在脑海里画了一个圈，在里面写下“平凡”这个词。与其他人没什么不同的人生、不突出的人生、
  不显眼的人生，因此是不会成为任何话题、不会受到任何评价或审判、不会被排挤的人生。不管那个圆圈有多么狭小和令人感
  到痛苦，都不能从里面出来。也许这就是妈妈的信仰吧。
  #+END_QUOTE

- 4248-4249, 标注, 2024 年 10 月 16 日星期三 下午 1:25:12
  # note_md5: a978a8cf856b0a4496a5e169fba0b5d5
  #+BEGIN_QUOTE
  你的朋友三川为了活着，一辈子都在寻找生路。像野兽一样，像以泥土和尘芥为食的虫子一样，一辈子都在寻找生路。
  #+END_QUOTE

- 4305-4307, 标注, 2024 年 10 月 16 日星期三 下午 1:28:33
  # note_md5: 2821c4325777a664f5fcec7570cdfc71
  #+BEGIN_QUOTE
  我想，就是这种看似微不足道的心意，有时也会给人以活下去的力量。不管是对于靠在别人肩膀上的人，还是把肩膀借给别人
  的人。就像一缕阳光从云缝里照出来，这种心意也再次降临到了我的身上。我很欣慰。
  #+END_QUOTE

- 4320-4321, 标注, 2024 年 10 月 16 日星期三 下午 1:30:12
  # note_md5: 5dd5ecd67a2bb7dacb36fe0a821468c5
  #+BEGIN_QUOTE
  她和喜子已经十年没见过面了，她几乎无法想象喜子的生活。喜子也一样，她们之间没有现实的公分母。
  #+END_QUOTE

- 4493-4495, 标注, 2024 年 10 月 16 日星期三 下午 4:19:55
  # note_md5: ea6653c97db696a07493159932480905
  #+BEGIN_QUOTE
  不知从什么时候起，妈妈开始对祖母说敬语。祖母看到别的孩子惹是生非、闯了祸以后，一边喊着“妈妈，妈妈”一边挂到自己
  妈妈身上时，总是感到很羡慕。
  #+END_QUOTE

- 4510-4513, 标注, 2024 年 10 月 16 日星期三 下午 4:24:37
  # note_md5: f8ac87747e7ae2fc2f44ac752c93029d
  #+BEGIN_QUOTE
  “反抗的话会挨两拳、三拳，而且不会赢。不反抗的话，挨一拳就可以结束。”我想起了说这话时的妈妈的脸。“输也是
  赢。”“如果因为别人欺负你，就跟他们一样使坏的话，你也会变成和他们一样的人。”“扼杀自己就可以活下去。”这些话充满
  了失败感，因为认定了就算反抗也不可能赢，于是早早地缴械投降。
  #+END_QUOTE

- 4550-4551, 标注, 2024 年 10 月 16 日星期三 下午 6:33:56
  # note_md5: 761968c00dba831bbbf7173f2b894b49
  #+BEGIN_QUOTE
  她对微不足道的事情也喜欢感叹，我常常想，她以后的人生该有多丰富啊。今后的日子里每当有好事发生，她就会说‘哇’。那
  曾是我的希望。”
  #+END_QUOTE

- 4595-4596, 标注, 2024 年 10 月 16 日星期三 下午 6:37:03
  # note_md5: f0206f1d2093487358ce1ec8006e7645
  #+BEGIN_QUOTE
  她行动比较慢，但没有问题，请不要一直催促，孩子会有压力的；
  #+END_QUOTE

- 4732-4738, 标注, 2024 年 10 月 16 日星期三 下午 6:45:12
  # note_md5: f5cc79acc4cd56438dca6f9340349600
  #+BEGIN_QUOTE
  在梦中，曾祖母深夜里坐在老家的屋顶上仰望月亮。“祖母！”妈妈大声叫着，曾祖母却不看妈妈，只望着月亮。妈妈跺着脚又
  说：“祖母！我是美仙啊！”然后又叫了一声曾祖母。妈妈发现，自己又变成了对曾祖母说平语的小孩子。“你看看我啊，祖
  母！”妈妈哀求着，这时曾祖母才回过头来。曾祖母的脸在月光下面闪着光辉。“祖母讨厌我吗？”母亲问。曾祖母似乎觉得这
  句话很有趣，脸上露出微笑。“祖母很讨厌我吧？”妈妈哽咽着再次问道，这时曾祖母开口了。妈妈一下醒了过来。
  #+END_QUOTE

- 4742-4746, 标注, 2024 年 10 月 16 日星期三 下午 6:46:11
  # note_md5: 6f5c8c3105cad6174474ef4958735bbc
  #+BEGIN_QUOTE
  每当妈妈想到为了不被折磨，每一刻都要拼尽全力坚持下去的时候，总觉得自己是孤身一人。心里想着“该回家了，该回家了”，
  脚步却总是不由自主，经常去海边。每当这时，曾祖母就会去找妈妈。妈妈还记得曾祖母在天黑的海边一边喊着“美仙啊，美
  仙啊”，一边走过来时的样子。妈妈记住了当时的喜悦，以及受到压抑的心情变得轻松起来的感觉。最重要的是，还有那种“我
  也有人牵挂”的心声。
  #+END_QUOTE

- 4780-4783, 标注, 2024 年 10 月 16 日星期三 下午 6:48:21
  # note_md5: 807169d0aa71bed2741422111eecf44f
  #+BEGIN_QUOTE
  晚秋时节妈妈带我去大邱避难，她浑身瑟瑟发抖，还一直开着玩笑。我知道妈妈不是因为冷，而是因为害怕而发抖。她一生
  都是这样，即便浑身颤抖着，也要牵着我的手往前走。妈妈是我一生中最爱的人，即使她怕得发抖，还是步履不停。我想变得
  像妈妈那样。
  #+END_QUOTE

- 4823-4825, 标注, 2024 年 10 月 16 日星期三 下午 6:50:53
  # note_md5: c7715341f9e34a999fa39f0bb49f2668
  #+BEGIN_QUOTE
  我经常想起新雨大婶对金喜子博士说过的话——尽可能地走远一些。这句话指的绝不仅仅是物理上的距离，大婶一定是希望自己
  的女儿能去另一个维度的世界。她希望在自己所感受到的现实重力无法起作用的地方，女儿能够变得更加轻松，更加自由。
  #+END_QUOTE

- 4839-4845, 标注, 2024 年 10 月 16 日星期三 下午 6:52:51
  # note_md5: 76f1be8b5b05c03285ff4112de26a13a
  #+BEGIN_QUOTE
  我既是现在的自己，也是三岁时的自己，同时还是十七岁时的自己。我轻易便抛弃了自己，但被我抛弃的自己并没有消失，而
  是一直留在我的心里。她在等着我，希望得到我的而不是其他人的关心；期望得到我的而不是别人的安慰。我常常闭上眼睛，
  寻找年幼的姐姐和自己。有时我会牵起她们的手，有时会坐在日落的游乐场的长椅上和她们聊天。我走近在空荡荡的家里准备
  独自上学的十岁的我、吊在单杠上忍住眼泪的上中学时的我、和伤害自己身体的冲动做斗争的二十岁的我、原谅了随意对待我
  的配偶的我，以及无法原谅这样的自己而忍不住自我攻击的我，倾听着她们的声音。是我，我在听。把你长久以来想说的话都
  告诉我吧。
  #+END_QUOTE

- 4871-4873, 标注, 2024 年 10 月 16 日星期三 下午 6:54:41
  # note_md5: d60e98bdb69b5414bffe919ac7d754e0
  # note_md5: ad446b68378a96028f2c2a60197d6a9b
  # note_md5: 6c15159a13dd30b7b8a069b9c0c33123
  #+BEGIN_QUOTE
  对我来说，过去的两年是我长大成人后最艰难的一段时光。那段日子里，我有一半的时间没能写作，剩下的时间则都在写《明
  亮的夜晚》。那个时期的我好像不是人，而是像个被打一下就会倾泻而出的水袋。写这部小说的过程，也是我重新获得自己的
  身体，接纳自己的内心，成为一个人的过程。
  #+END_QUOTE

- 4981-4981, 标注, 2024 年 10 月 16 日星期三 下午 7:44:20
  # note_md5: bd4079df7e8d664211bdc47d91e99c69
  #+BEGIN_QUOTE
  让日常阅读成为砍向我们内心冰封大海的斧头。
  #+END_QUOTE
