:PROPERTIES:
:ID:       2fe211e7-5175-4824-aaf1-1e436ce50326
:END:
#+TITLE: [笔记]邓小平时代（无删节完整版）-高华
#+AUTHOR: Yang Yingchao
#+DATE:   2024-10-09
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:   oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+LANGUAGE: en
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport

- 523-525, 标注, 2024 年 9 月 26 日星期四 上午 8:04:45
  # note_md5: 0aff9ab56e71c149d557eccf175e27ac
  #+BEGIN_QUOTE
  有些西方人对邓小平的直率和务实留有深刻印象，这使他们误以为他骨子里是个资本主义分子，他会将中国引向西方式的民主。
  他一向乐于学习，但他最终认为，自己要比他们更清楚什么对中国有利，而那不应该是资本主义和西方式的民主。
  #+END_QUOTE

- 582-584, 标注, 2024 年 9 月 26 日星期四 上午 8:11:16
  # note_md5: fd5b11552e7ea4763c7ae9ae3068b265
  #+BEGIN_QUOTE
  邓小平养成了一种刚毅的品格，能够做到不论愤怒还是受挫都不形于色，不让情绪左右自己的决策，而是把它创建在对党和国
  家需要的认真分析之上。毛泽东曾经
  #+END_QUOTE

- 582-583, 标注, 2024 年 9 月 26 日星期四 上午 8:11:21
  # note_md5: f0132cbb2b19dbb9873ad4cf68382820
  #+BEGIN_QUOTE
  邓小平养成了一种刚毅的品格，能够做到不论愤怒还是受挫都不形于色，不让情绪左右自己的决策，而是把它创建在对党和国
  家需要的认真分析之上。
  #+END_QUOTE

- 605-608, 标注, 2024 年 9 月 26 日星期四 上午 8:18:20
  # note_md5: 4d535deac2d62062a31cfde1a8396466
  #+BEGIN_QUOTE
  他对内战和文革的混乱记忆犹新，因此认为中国的社会秩序很脆弱；如果他断定它受到威胁，就会作出强硬的反应。
  作为最高领导人，他准备按自己的日程表大胆实行改革开放。简言之，当他成为中国最高领导人时，他是个严守纪律、
  经验丰富的干部，决心为党和国家的需要而服务。
  #+END_QUOTE

- 687-688, 标注, 2024 年 9 月 26 日星期四 上午 8:30:58
  # note_md5: 0202411047e690caee106335593f0da3
  #+BEGIN_QUOTE
  邓小平 1974 年会见一个美国的大学代表团时说：“我没有上过大学，但我一向认为，从我出生那天起，
  就在上着人生这所大学。它没有毕业的一天，直到去见上帝。”
  #+END_QUOTE

- 978-980, 标注, 2024 年 9 月 26 日星期四 下午 12:29:55
  # note_md5: 0f6594b52cbfba1b6f3be66561c0b04e
  #+BEGIN_QUOTE
  当时他还无从知道，从长远看，他因被指为“毛派头子”而受到惩罚其实是他的运气，
  因为这使毛泽东长期相信邓小平是忠实于自己的。在后来的岁月里，即便在毛泽东让激进派批邓时，
  也绝不同意把邓小平开除出党。
  #+END_QUOTE

- 1145-1146, 标注, 2024 年 9 月 26 日星期四 下午 6:33:38
  # note_md5: 3798066af60e169d2626dc5062df47b7
  #+BEGIN_QUOTE
  邓小平很快就意识到，对斯大林的全面批判将殃及那些和斯大林一起工作的人，削弱苏共的权威。
  #+END_QUOTE

- 1146-1146, 笔记, 2024 年 9 月 26 日星期四 下午 6:34:28
  # note_md5: 51a9ab1bde7ffc681ee3c5fe1ed8a29c
  #+BEGIN_QUOTE
  所以日后对毛的功过评论很保守
  #+END_QUOTE

- 1170-1171, 标注, 2024 年 9 月 26 日星期四 下午 6:37:21
  # note_md5: c64ec4ea86dfa6f3bb06cdee00811873
  #+BEGIN_QUOTE
  反右运动毁掉了中国大批最优秀的科技人才，也使很多人疏远了中共。
  本来有可能阻止毛泽东发动大跃进的批评者变得噤若寒蝉。
  #+END_QUOTE

- 1184-1186, 标注, 2024 年 9 月 26 日星期四 下午 6:39:05
  # note_md5: cb70f9e1f0b76493d84d35aabfe2ccb8
  #+BEGIN_QUOTE
  虽然难以估算在最糟糕的三年——从 1959 年到 1961 年——到底饿死了多少人，但按大陆官方统计，估计有 1,600 万到 1,700 万人死于
  非正常原因，外国分析家的估计则高达 4,500 万。
  #+END_QUOTE

- 1365-1367, 标注, 2024 年 9 月 26 日星期四 下午 6:48:45
  # note_md5: eed59955c22820575d4e2a74207b13a4
  #+BEGIN_QUOTE
  文革对国家、对邓小平本人和家庭的影响让他感到痛心。但是，据在江西最后两年的大多数时间跟父母住在一起的邓榕说：
  “他没有意气用事，没有情绪消沉，没有放弃哪怕是最后的一线希望。”
  #+END_QUOTE

- 1380-1384, 标注, 2024 年 9 月 26 日星期四 下午 6:50:12
  # note_md5: 04ab1a0a291be9f63d7b46de46c7db5d
  #+BEGIN_QUOTE
  ，邓小平发现，这一段退出日常政治的在野岁月使他能够对国家的重大和长远目标形成清晰的认识。倘若邓小平没有对中国需
  要进行的改革的性质以及如何加以落实作过长期思考，很难想像他在 1977 年以后能够采取那些熟练而有力的措施。毛泽东曾经
  利用他在延安那段被封锁隔绝的时间思考中共夺取政权后全国的整体战略，邓小平也利用了他在江西的时光，思考着他所要进
  行的改革的大方向
  #+END_QUOTE

- 1497-1499, 标注, 2024 年 9 月 26 日星期四 下午 7:10:27
  # note_md5: 4b220c3cd0286e0afc37aff6b04e2b8f
  #+BEGIN_QUOTE
  一些了解邓小平的人说，他在权衡如何惩罚人时，绝大多数情况下都不会让个人感情影响决定，然而他特别严厉地坚持要判聂
  元梓十年徒刑，因为正是聂在北京大学发动的政治批斗导致了邓朴方的瘫痪和大约 60 名教职工的死亡。
  #+END_QUOTE

- 4461-4464, 标注, 2024 年 9 月 27 日星期五 下午 8:54:02
  # note_md5: 894426911d4beec76c56d8ed34011a25
  #+BEGIN_QUOTE
  华国锋与“四人帮”的斗争后来被一再说成善恶之间的伟大斗争，是追求正确路线的党与“四人帮”反党集团的斗争。就像中国历
  史文献中记录的很多故事一样，这其实属于成王败寇的老生常谈。不过，这一次就像 1949 年一样，获胜者确实得到了真诚而普
  遍的拥护。
  #+END_QUOTE

- 4731-4734, 标注, 2024 年 9 月 27 日星期五 下午 9:17:18
  # note_md5: dd10e75e564a30d3fe83d2c6ee0508e5
  #+BEGIN_QUOTE
  ，一些宣传家和毛泽东的坚定追随者，却不断批评他偏离了毛泽东为党制定的路线。为了回应这些批评，华国锋授意他的拥护
  者写一篇理论文章，以证明他忠实于毛的遗志。由此而出笼的文章，便是 1977 年 2 月 7 日的《人民日报》、《红旗》杂志和《解
  放军报》社论。这篇社论宣佈，凡是毛主席作出的决策都要执行，凡是毛主席的指示都要照办，此即后来著名的“两个凡是”，
  它成了华国锋表明自己完全忠实于毛主席遗志的标志。
  #+END_QUOTE

- 4766-4769, 标注, 2024 年 9 月 27 日星期五 下午 9:20:19
  # note_md5: 353c8e9fb18b10d0d8a542bfc38d614d
  #+BEGIN_QUOTE
  时常有人说，中国的对外开放政策——包括愿意学习国外经验和急迫地想要引进外国技术——源于 1978 年 12 月邓小平领导下的三中
  全会。其实这些做法始于 1977–1978 年华国锋的领导，而华国锋提出的政策也并非由他首创。华国锋和邓小平所推行的，是被
  很多中共干部视为中国必由之新路的政策。
  #+END_QUOTE

- 4914-4916, 标注, 2024 年 9 月 28 日星期六 上午 8:27:09
  # note_md5: 6195f1f586d2fdf91639ac249aee2c2c
  #+BEGIN_QUOTE
  邓力群带来了邓小平写作班子前负责人胡乔木的一封检讨信，胡为自己参与批邓表示道歉。邓小平没有看那封信，而是让邓力
  群把它退了回去。他说，胡乔木的批评我不介意，胡乔木只是讲了一些套话，这可以理解；没有必要为这种装样子的事道歉。
  #+END_QUOTE

- 5177-5181, 标注, 2024 年 9 月 28 日星期六 上午 9:03:06
  # note_md5: 6b7c000df7837340964a5a8b81d61593
  #+BEGIN_QUOTE
  《理论动态》在 1978 年 5 月 10 日出了第 60 期简报，标题是“实践是检验真理的唯一标准”。 [6-71] 该文已经酝酿了数月，是由
  南京大学哲学系青年教师胡福明、中央党校理论教研室孙长江和《光明日报》总编杨西光——他是中央党校 1977 年秋季入学的学
  员——数易其稿而完成。
  #+END_QUOTE

- 5391-5394, 标注, 2024 年 9 月 28 日星期六 上午 9:17:57
  # note_md5: d8ab1c6e2c97a2a6c67341354db77f8b
  #+BEGIN_QUOTE
  1978 年 12 月 2 日，他告诉那些为他起草启动改革开放政策讲稿的人：“基本的要点是，必须承认自己落后，我们的很多做法都不
  对头，需要加以改变。 [7-4] 出国考察使很多高层干部更加相信邓小平的看法是正确的：中国必须改弦易辙。
  #+END_QUOTE

- 5408-5410, 标注, 2024 年 9 月 28 日星期六 上午 9:20:22
  # note_md5: 9da4762c3a327cd00048ffb32aa1de15
  #+BEGIN_QUOTE
  当时广东存在着实际的治安问题：每年都有成千上万的年轻人逃往香港。邓小平 1977 年视察广东时有人向他谈到这个问题，邓
  小平说，出路不是用更多的铁丝网和边境哨所强化治安，而是集中精力发展广东经济，这样年轻人就会觉得没有必要再逃到香
  港谋生了。
  #+END_QUOTE

- 5830-5831, 标注, 2024 年 9 月 28 日星期六 上午 9:54:21
  # note_md5: 8bfd721937501f40ca519527e10e6264
  #+BEGIN_QUOTE
  。就像他过去多次讲过的那样，他再次建议首先看大局，然后再想局部；先讲大道理，再讲小道理。
  #+END_QUOTE

- 5856-5861, 标注, 2024 年 9 月 28 日星期六 上午 10:00:13
  # note_md5: 1c60287902c7c734d5b4f5651b978053
  #+BEGIN_QUOTE
  在 12 月 13 日下午中央工作会议的闭幕会上，邓小平一开口就直奔主题：“今天我主要讲一个问题，就是解放思想，开动脑筋，
  实事求是，团结一致向前看。”邓小平称赞这次工作会议是 1957 年以来党内最好、最开放的一次讨论会。他说，要允许大家说
  出对真实情况的看法。“必须有充分的民主，才能做到正确的集中。当前这个时期，特别需要强调民主。因为在过去一个相当
  长的时间内⋯⋯民主太少。⋯⋯应当允许群众提一些意见，即使有个别心怀不满的人，想利用民主闹一点事，也没有什么可怕⋯⋯最
  可怕的是鸦雀无声。”
  #+END_QUOTE

- 5865-5869, 标注, 2024 年 9 月 28 日星期六 上午 10:03:54
  # note_md5: f5b0d6a9b9a8e852a965252a9f2daebe
  #+BEGIN_QUOTE
  他再次重复了自己的观点，认为毛泽东犯过错误，他本人也犯过错误，任何想做事的领导人都会犯错误。他表达了党内高层的
  一种主流观点：中国的两次大灾难——大跃进和文革，是由于制度造成的，这种制度允许一人统治，容不下不同的声音。因此中
  国需要创建法制，这样的话一个人不管能力有多大，都不能由他一个人说了算。法制一开始可能不健全、不完善，但可以逐步
  使其变得公正合理。
  #+END_QUOTE

- 6131-6131, 标注, 2024 年 9 月 28 日星期六 上午 10:21:45
  # note_md5: cc233c0a5b55ae91d6147a6ff786d21e
  #+BEGIN_QUOTE
  文化大革命其实是一场“反文化的革命”，它攻击了旧文化，却并没有创造出新文化。
  #+END_QUOTE

- 6230-6233, 标注, 2024 年 9 月 28 日星期六 上午 10:29:23
  # note_md5: 346b27bffa38438cae160b02184d49af
  #+BEGIN_QUOTE
  尽管《人民日报》没有报道西单的事情，但报社里支持“民主墙”的人在 1979 年 1 月 3 日发表了一篇大胆的社论〈发扬民主和实现
  四化〉，其中说：“让人说话，天不会塌下来。⋯⋯真正可怕的倒是听不到不同的声音。⋯⋯害怕人民讲话，实际是软弱和神经衰
  弱的表现。⋯⋯安定团结和发扬民主并不是对立的。”
  #+END_QUOTE

- 8654-8656, 标注, 2024 年 9 月 28 日星期六 上午 11:15:38
  # note_md5: 456fb38bb4d0935c9a706aaaac9891f6
  #+BEGIN_QUOTE
  除了为数不多的人事和军队职位外，他在选择领导人时，首先不是看他们是否对自己忠诚（对军队的任命见第 18 章）。他需要
  的是最称职的人，他坚信，只要他们素质高，忠于党，他就能与他们共事。邓小平不跟他任命的人搞私人关系，即使对提拔到
  高层的人也是如此。他
  #+END_QUOTE

- 9184-9185, 标注, 2024 年 9 月 28 日星期六 上午 11:30:55
  # note_md5: d422a02ece03403ce2d988cefd02c129
  #+BEGIN_QUOTE
  邓小平自早年起就享有一种声誉——他善于区分大事小事，将精力集中在能给中国带来最大变化的事情上：制定长期战略、评价
  可能决定长期目标成败的政策、争取下级干部和群众的支持、宣传能体现他想实行的政策的典型
  #+END_QUOTE

- 9433-9435, 标注, 2024 年 9 月 28 日星期六 上午 11:40:16
  # note_md5: 6db4be7f52c269cfd3fc8d435749cb19
  #+BEGIN_QUOTE
  说到底，民主集中制要求每个人必须加入合唱，表态支持具体的政策。对于他们认为适当的政策，他们会给予认可，因为跟得
  不紧有可能吃亏。在邓小平看来，成功的领导人不仅要决定正确的长期战略方向，还应当知道如何去营造“气氛”，如何选准时
  机采取大胆的步骤，在干部群众都愿意支持时迅速采取行动。
  #+END_QUOTE

- 15283-15284, 标注, 2024 年 9 月 28 日星期六 下午 12:06:02
  # note_md5: 1065d767aef808e98241fdc62055aef2
  #+BEGIN_QUOTE
  了。很多学生逐渐相信，只有通过缓慢地创建基础，通过改善更多人的经济生活，通过加深人们对公共事务的理解，逐渐形成
  对民主和自由的经验，才能取得进步。
  #+END_QUOTE

- 15287-15288, 标注, 2024 年 9 月 28 日星期六 下午 12:06:29
  # note_md5: 4c336c4ac1387597333162d165a2d30c
  #+BEGIN_QUOTE
  绝大多数学生运动活跃分子都放弃了集体行动，专注于追求个人前程。
  #+END_QUOTE

- 15484-15485, 标注, 2024 年 9 月 28 日星期六 下午 1:23:06
  # note_md5: 5670d830cf13681b7dc12ba2dfbb2361
  #+BEGIN_QUOTE
  在西方人看来，在北京发生的杀害那些进行自由民主抗议的无辜学生的行为，是比他们自己国家那些导致越南、柬埔寨等地大
  量平民死亡的决定更加恶劣的罪行。西方
  #+END_QUOTE

- 15587-15589, 标注, 2024 年 9 月 28 日星期六 下午 1:38:55
  # note_md5: ba49915be3ed2d002afce1f709fcd15e
  #+BEGIN_QUOTE
  概括起来就是三句话：第一句话，冷静观察；第二句话，稳住阵脚；第三句话，沉着应付。不要急，也急不得。要冷静、冷静、
  再冷静，埋头实干，做好一件事，我们自己的事。”
  #+END_QUOTE

- 15848-15850, 标注, 2024 年 9 月 28 日星期六 下午 5:27:38
  # note_md5: 00f5c1f1687750596d71e301133142dd
  #+BEGIN_QUOTE
  在天安门悲剧之后的困难时期和苏联解体的时期，邓小平不断重复着一句口头禅：“冷静观察，稳住阵脚，沉着应付，有所作
  为。”
  #+END_QUOTE

- 16191-16193, 标注, 2024 年 9 月 28 日星期六 下午 6:14:30
  # note_md5: 3cfc814c978206dde1bd10405ebbd825
  #+BEGIN_QUOTE
  邓小平一向反对空话、长篇报告和不作认真准备的会议，他曾说过：“没有话把嘴巴一闭⋯⋯会议和讲话是为了解决问题的。
  #+END_QUOTE

- 16466-16468, 标注, 2024 年 9 月 28 日星期六 下午 6:56:52
  # note_md5: 037292cfb340b2cd5030db2a6164ce8b
  #+BEGIN_QUOTE
  关于统治和自由的问题，邓小平说，“民主集中制”仍是“最合理的制度”，要作为治国的基本原则加以坚持。领导人要想办法鼓
  励人们表达自己的观点，但是决定一旦作出，就应当服从集体决定。
  #+END_QUOTE

- 17226-17226, 标注, 2024 年 9 月 28 日星期六 下午 8:35:20
  # note_md5: 12241a548aae1197aa49a0cb133b9a3b
  #+BEGIN_QUOTE
  毛泽东曾说，陈云太胆小，一片树叶落下来也怕砸到自己头上。
  #+END_QUOTE

- 17344-17346, 标注, 2024 年 9 月 28 日星期六 下午 8:38:02
  # note_md5: 66fa757912cb2553f2a0c388e8df3f8a
  #+BEGIN_QUOTE
  就连一些崇拜胡耀邦的人也承认，他缺少最高领导人所应有的沉稳与庄重。他讲话时手舞足蹈，让人觉得他是个没经验的青年
  人。批评他的人蔑称他为“蟋蟀”。
  #+END_QUOTE
