:PROPERTIES:
:ID:       3832d581-ed92-4c70-8b0a-766f206b40b2
:END:
#+TITLE: [笔记]芯片战争_世界最关键技术的争夺战-N/A
#+AUTHOR: Yang Yingchao
#+DATE:   2024-10-09
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:   oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+LANGUAGE: en
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :xinpianzhanz:clip:

- 520-851, 标注, unknown
  # note_md5: 51ad4985a7cbd1e41ebe3139cc62b6aa
  #+BEGIN_QUOTE
  客观地说，当今中国的经济和科技发展水平，不但比不了美国，而且连 20 世纪 80 年代正在崛起中的日本都比不了。当时日
  本已经有索尼、 夏普、丰田、本田、东芝、佳能、尼康等一系列拥有自己的核心技术、自己的设计、自己的品牌，且受到全
  世界消费者追捧的公司。日本 曾经在芯片上把美国打到近乎绝望。就连韩国，早在一二十年前，也已经有了三星、LG、现代
  这样的全球知名企业。而当今中国除了华为 和字节跳动，全球品牌还很少，独家技术也很少。中国排在前列的大公司都是像
  石油、银行、电网和电信这些国有企业，一些国产品牌只 在中国能做到家喻户晓。中国经济体量大、数字好看，而我们的真
  实经济实力，特别是创新能力，距离发达国家还很远。
  #+END_QUOTE

- 898-1085, 标注, unknown
  # note_md5: d244af3f301ac98bdb333ac899a8fff5
  #+BEGIN_QUOTE
  如果让政府主导创新，那就不是创新。政府就不是一个创新部门。创新，首先是有风险的事情，需要奇思妙想，需要你在各个
  方向自由探 索。创新意味着浪费，意味着对现有格局的颠覆，意味着无情的破产和淘汰......这些都不是政府喜欢的。政府
  做事总是求稳、求保守、 不冒险。我们整天说创新，殊不知谈创新不谈风险、不谈颠覆的，都是伪创新。
  #+END_QUOTE

- 1132-1235, 标注, unknown
  # note_md5: 8c639a21d0dfa0a856faa9355e2b069f
  #+BEGIN_QUOTE
  不被卡脖子的正确做法不是独立自主，而是让自己变得更值得依赖，让包括美国在内的全世界不得不依赖我们，以此跟美国讨
  价还价，若 你要再敢卡我脖子我就卡你脖子。
  #+END_QUOTE

- 1282-1342, 标注, unknown
  # note_md5: 3816af610ab78a7ad5d326a43d24e1fc
  #+BEGIN_QUOTE
  所以要做好本手，等待妙手，而且还得注意少用那些光花钱不办事的俗手。
  #+END_QUOTE

- 1406-1514, 标注, unknown
  # note_md5: 2c55722cd386d0a9fbe71692c739f63c
  #+BEGIN_QUOTE
  1969 年，桑德斯成立了自己的芯片公司 AMD。此后 30 年的大部分时间里，他都在与英特尔就知识产权纠纷进行法律斗争。
  他向一名记者承认：“我不能逃避战斗。”
  #+END_QUOTE

- 1561-1760, 标注, unknown
  # note_md5: e26224bcda876b2f9f8ee9f47884dbb9
  #+BEGIN_QUOTE
  日本的社会结构倾向于产生大量储蓄，因为战后的婴儿潮和向独生子女家庭的迅速转变，造成了大量中年家庭专注于为退休储
  蓄。日本不 健全的社会安全网进一步刺激了储蓄。与此同时，对股票市场和其他投资的严格限制让人们别无选择，只能将储
  蓄存入银行账户。结果， 银行存款充裕，以低利率发放贷款，因为人们手头有太多现金。日本公司的债务比美国同行多，但
  借贷利率较低。
  #+END_QUOTE

- 1824-2199, 标注, unknown
  # note_md5: 6e17b452c44979c4449c9ef6bbeac598
  #+BEGIN_QUOTE
  盛田昭夫起初发现他的美国朋友所代表的权力和财富很诱人。但随着美国从一场危机走向另一场危机，基辛格和彼得森等人周
  围的气场开始减弱。他们国家的制度不起作用，但日本的制度起了作用。到了 20 世纪 80 年代，盛田昭夫意识到了美国经济
  和社会的深层次问题。长期以来，美国一直把自己视为日本的老师，但盛田昭夫认为，美国在应对不断增长的贸易逆差和高科
  技行业的危机时，应该吸取教训。盛田昭夫讲道，美国在“忙着培养律师”，日本则在“忙着培养工程师”。相比美国的企业高管
  们过于关注“今年的利润”，日本企业管理层更关注“长期”的利润。美国的劳资关系等级分明，并且“老派”，企业没有对车间员
  工进行足够的培训或激励。盛田昭夫认为，美国人应该停止抱怨日本的成功。他认为是时候告诉自己的美国朋友们了：日本的
  体制运行得更好。
  #+END_QUOTE

- 2244-2614, 标注, unknown
  # note_md5: 45031dc7afb428614d9c2e2b5d454288
  #+BEGIN_QUOTE
  眼熟不？！ ** 22 颠覆英特尔 <<chapter_3.html_zybooknote_summary>>格鲁夫在他的畅销书《只有偏执狂才能生存》中，
  描述了他的管理哲学：“担心竞争、担心破产、 担心被人误解、担心丢掉工作，这些担忧都是强大的动力。” #+END_QUOTE **
  35 “真正的男人要有晶圆厂” # note_md5: 4ae5c52e194667166232c6688b3a2cee #+BEGIN_QUOTE 戴劳力士表、开劳斯莱斯车、
  创立 AMD 的杰瑞·桑德斯喜欢把拥有一家半导体晶圆厂比作在游泳池里养一条宠物鲨鱼。鲨鱼的饲养成本很高， 需要时间和
  精力来维持，最终还可能会害死你。即便如此，桑德斯仍然确信一件事：他永远不会放弃自己的晶圆厂。
  #+END_QUOTE

- 2677-2790, 标注, unknown
  # note_md5: a99fa8d3fcad6249c4ead32ad4285509
  #+BEGIN_QUOTE
  一个对不可能实现的技术疯狂下注的时代正被更有组织、专业化和合理化的东西取代。抵押房子式的赌博被经过仔细计算的风
  险管理取代。 在这一过程中，人们很难摆脱失去了一些东西的感觉。
  #+END_QUOTE

- 2856-3259, 标注, unknown
  # note_md5: 86a1482ba9f3119a220c2eec96529e97
  #+BEGIN_QUOTE
  对于中国来说，从机械到软件，在供应链的许多部分缺乏竞争性企业，技术独立更为困难。为了实现技术完全独立，中国需要
  获得尖端的 设计软件、设计能力、先进材料和制造技术等。毫无疑问，中国将在其中一些领域取得进展，但有些领域的成本
  太高，难以复制。设想一 下复制一台阿斯麦的 EUV 光刻机需要什么，这台机器花了近 30 年的时间来开发和商业化。EUV 光
  刻机具有多个部件，这些部件本身构成了极 其复杂的工程挑战。在 EUV 光刻机系统中，复制光源需要完美识别和组装
  457329 个零件。一个单一的缺陷可能会导致严重的延迟或可靠性 问题。即使已经获得了阿斯麦的设计规范，这种复杂的机器
  也不能像文件一样简单地复制和粘贴。即使有接触专业信息的机会，也需要一 位熟悉科学的光学或激光博士。即使有这样的
  人才，可能仍然缺乏开发 EUV 光刻机的工程师们 30 年来积累的经验。
  #+END_QUOTE
