:PROPERTIES:
:ID:       473e9a95-d407-496a-a13c-7724c65d9662
:END:
#+TITLE: [笔记]1984:反乌托邦三部曲-[英] 乔治·奥威尔;孙仲旭
#+AUTHOR: Yang,Ying-chao
#+DATE:   2025-02-28
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:  align nodlcheck oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+LANGUAGE: en
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :1984:fanwutu:note:ireader:

- 54-55, 标注, 2025年2月28日星期五 上午7:56:15
  # note_md5: 4957c36d4593161fb59c53831810cb56
  #+BEGIN_QUOTE
  他表达的是一种对于人类未来近乎绝望的情绪，同时也预兆，除非历史的进程改变，否则全世界的人都会在不知不觉中失去大部分人类的特质，变成没有灵魂的机器人。
  #+END_QUOTE

- 59-61, 标注, 2025年2月28日星期五 上午7:57:17
  # note_md5: bc4baa2fe2a2bafbb3ae40af23dbee32
  #+BEGIN_QUOTE
  普遍的和平和正义是人类的目标，先知们坚信错误和罪恶即使有得势之时，“末日审判”最终还是会到来，救世主便是这种信念的象征。
  #+END_QUOTE

- 72-74, 标注, 2025年2月28日星期五 上午7:58:55
  # note_md5: a7715d15acb6732163e953f9d8518741
  #+BEGIN_QUOTE
  紧随托马斯·莫尔的《乌托邦》之后，还有两部同类作品，分别是修道士康帕内拉的《太阳城》和德国人文主义者安德里亚的《基督城》。后者是三者之中最具现代性的作品。乌托邦三部曲之间
  #+END_QUOTE

- 72-74, 标注, 2025年2月28日星期五 上午7:59:02
  # note_md5: 766285b73299450e2a5e518afba0fed0
  #+BEGIN_QUOTE
  紧随托马斯·莫尔的《乌托邦》之后，还有两部同类作品，分别是修道士康帕内拉的《太阳城》和德国人文主义者安德里亚的《基督城》。后者是三者之中最具现代性的作品。乌托邦三部曲之间有着不同的观点和创意，但是与它们的共同点相比起来，这些差异就显得十分渺小。
  #+END_QUOTE

- 91-95, 标注, 2025年2月28日星期五 上午8:02:10
  # note_md5: f20e78376a1f033da32a456fb0b8a35e
  #+BEGIN_QUOTE
  奥威尔并不是做这种尝试的唯一一人。另外两个作家，俄国的扎米亚京在他的书《我们》和阿道斯·赫胥黎在他的《美妙的新世界》中，都用跟奥威尔作品非常相似的方式表达了当时的这种情绪并对未来提出警示。这三部写于20世纪中叶的作品被我们称为“反乌托邦”三部曲，这是为了和上文提到的写于16、17世纪的“乌托邦”进行对应[
  #+END_QUOTE

- 95-96, 标注, 2025年2月28日星期五 上午8:03:03
  # note_md5: 101787e2f5e42e9a833cc980ea0873bd
  #+BEGIN_QUOTE
  早期乌托邦作品描述充满自信的情绪和充满希望的后中世纪的人一样，反乌托邦描述的是一种无能为力的情绪和绝望的现代人。
  #+END_QUOTE

- 100-102, 标注, 2025年2月28日星期五 上午8:03:42
  # note_md5: 5e143310dd5f93c6fb9a45398fd2ff59
  #+BEGIN_QUOTE
  就在人们感受到所有的希望即将实现的这一刻，他们开始失去了它。这就是反乌托邦三部曲的核心，它们不仅仅描述了我们的未来走向，同时也解释了历史的悖论。
  #+END_QUOTE

- 145-149, 标注, 2025年2月28日星期五 上午8:12:14
  # note_md5: 0b9481b558836a73e30cafbf93e30bca
  #+BEGIN_QUOTE
  党的领袖甚至都不去假装他们的体系是为了使人们快乐，因为人是脆弱和怯懦的的生物，他们都想逃避自由而不敢去面对真理。领袖们都清醒地意识到，他们事实上只有一个目标，那就是权力。对他们来说“权力不是手段，而是目的，权力意味着他们有能力制造无限的痛苦和去折磨他人”[2]。权力，可以为他们创造事实，创造真理。在这里，奥威尔对于权利精英的态度可以说是唯心主义的极端形式，
  #+END_QUOTE

- 145-149, 标注, 2025年2月28日星期五 上午8:12:23
  # note_md5: 1d7bb9d27c252751e1d138b054edaf44
  #+BEGIN_QUOTE
  领袖甚至都不去假装他们的体系是为了使人们快乐，因为人是脆弱和怯懦的的生物，他们都想逃避自由而不敢去面对真理。领袖们都清醒地意识到，他们事实上只有一个目标，那就是权力。对他们来说“权力不是手段，而是目的，权力意味着他们有能力制造无限的痛苦和去折磨他人”[2]。权力，可以为他们创造事实，创造真理。在这里，奥威尔对于权利精英的态度可以说是唯心主义的极端形式，
  #+END_QUOTE

- 156-157, 标注, 2025年2月28日星期五 上午8:13:28
  # note_md5: 8437df3456999a20a9f63350e5e50271
  #+BEGIN_QUOTE
  只要经过大多数人的认可就是真理，口号在“几百万人怎么可能犯错”的基础上增加了“一个人怎么可能正确”。
  #+END_QUOTE

- 156-159, 标注, 2025年2月28日星期五 上午8:13:49
  # note_md5: 1096783703d0be6be5aa779caa0b13b8
  #+BEGIN_QUOTE
  只要经过大多数人的认可就是真理，口号在“几百万人怎么可能犯错”的基础上增加了“一个人怎么可能正确”。奥威尔已经明确指出，在一个团体中，已经彻底废除真理作为一个有关现实的客观判断这个概念，任何一个在这个团体中的异端都会被视为精神错乱。
  #+END_QUOTE

- 184-187, 标注, 2025年2月28日星期五 上午8:19:34
  # note_md5: 84a7bf5521e199e55f357e679f6205d4
  #+BEGIN_QUOTE
  在成功的思想控制之下，一个人再也不会有他想法的对立面，而只知道什么才是“真理”的对立面。因此，举个例子说，如果他已经丧失了他自身的独立性和完整性，如果他把自身当作是一个从属于国家、政党或者公司的物体，那么二加二就是五，或者认为“奴役即自由”，他之所以感到自由，是因为他再也不会意识到真理与谬误之间的矛盾。这特别适用于意识形态领域。
  #+END_QUOTE

- 189-192, 标注, 2025年2月28日星期五 上午8:20:58
  # note_md5: a2646f0c9bbe18b7687ae7973619eab9
  #+BEGIN_QUOTE
  奥威尔在这方面，很明显是指当局所伪造的社会主义，但是必须指出，西方社会也犯了同样的错误。我们说我们的社会就是一个行动自由、个人主义和理想主义的社会，然而事实上这些大部分是一些托词。我们处于一个中央集权的工业社会，本质上是官僚主义，由唯物主义提供动力，轻微的精神和宗教关怀仅仅是起缓和作用。
  #+END_QUOTE

- 201-203, 标注, 2025年2月28日星期五 上午8:23:30
  # note_md5: 43199e1a08d7bf18acb39d678d9dea49
  #+BEGIN_QUOTE
  我确信奥威尔、赫胥黎和扎米亚京三个都不想坚持认为这样的世界必定会到来。正相反，他们指出我们正在向着危险的方向走去，除非我们可以成功地让西方文化的根源中那些人道主义精神和个人尊严重新复苏。
  #+END_QUOTE

- 206-207, 标注, 2025年2月28日星期五 上午8:23:51
  # note_md5: 2e61e0f115b0cae1499eb4717b04edd7
  #+BEGIN_QUOTE
  个作者都暗示这种危险并不仅仅存在于像苏联那样的社会主义国家，这种危险是现代生产和组织模式所固有的，它完全独立于各种各样的意识形态之外。
  #+END_QUOTE

- 203-207, 标注, 2025年2月28日星期五 上午8:24:05
  # note_md5: c636adf8ac2691f6756eb6d3ae6d5e40
  #+BEGIN_QUOTE
  威尔和其他两位作者，暗示着在我们新的工业管理制度下，人制造出像人一样的机器，而人却发展得像越来越像机器，这将是一个人性丧失、全面异化的时代，人变成了物品，变成了生产和消费过程之中的一个附件[6]。三个作者都暗示这种危险并不仅仅存在于像苏联那样的社会主义国家，这种危险是现代生产和组织模式所固有的，它完全独立于各种各样的意识形态之外。
  #+END_QUOTE
