:PROPERTIES:
:ID:       63319cd4-ed04-452d-9c1a-ec5685d8521c
:END:
#+TITLE: [笔记]不能承受的生命之轻-[捷克] 米兰·昆德拉;许钧
#+AUTHOR: Yang,Ying-chao
#+DATE:   2025-03-28
#+OPTIONS:  ^:nil H:5 num:t toc:2 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:  oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :bunengchengs:note:ireader:

- 30-31, 标注, 2025 年 3 月 26 日星期三 下午 1:09:56
  #+BEGIN_QUOTE md5: cc5e0c53d1212ca43dc874319cd72ade
  那些转瞬即逝的事物，我们能去谴责吗？橘黄色的落日余晖给一切都带上一丝怀旧的温情，哪怕是断头台。
  #+END_QUOTE

- 37-38, 标注, 2025 年 3 月 26 日星期三 下午 1:11:32
  #+BEGIN_QUOTE md5: 695c4109f286787bd74fe4e081a35dc1
  在永恒轮回的世界里，一举一动都承受着不能承受的责任重负。这就是尼采说永恒轮回的想法是最沉重的负担（das
  schwerste Gewicht）的缘故吧。
  #+END_QUOTE

- 39-40, 标注, 2025 年 3 月 26 日星期三 下午 1:11:40
  #+BEGIN_QUOTE md5: 25cbb34f6199d121574e093ef2164c37
  如果永恒轮回是最沉重的负担，那么我们的生活，在这一背景下，却可在其整个的灿烂轻盈之中得以展现。
  #+END_QUOTE


- 40-45, 标注, 2025 年 3 月 26 日星期三 下午 1:12:28
  #+BEGIN_QUOTE md5: a5c24cd0ee5f48b3b9a0370f6fac87f5,57734a2d9da4563ebb24055e4180b0cd
  最沉重的负担压迫着我们，让我们屈服于它，把我们压到地上。但在历代的爱情诗中，女人总渴望承受一个男性身体的重量。
  于是，最沉重的负担同时也成了最强盛的生命力的影像。负担越重，我们的生命越贴近大地，它就越真切实在。 相反，
  当负担完全缺失，人就会变得比空气还轻，就会飘起来，就会远离大地和地上的生命，人也就只是一个半真的存在，
  其运动也会变得自由而没有意义。 那么，到底选择什么？是重还是轻？
  #+END_QUOTE

- 320-321, 标注, 2025 年 3 月 26 日星期三 下午 6:42:20
  #+BEGIN_QUOTE md5: 1a2ecd2ac4c4ba634342a552fc1d9de6,b240c25ab3166526aee14eaf2cb4f6fb
  他自言自语，带着一种幸福感，说他这种生活方式是走到哪儿带到哪儿，就像蜗牛驮着整个家。
  #+END_QUOTE

- 345-347, 标注, 2025 年 3 月 26 日星期三 下午 6:45:47
  #+BEGIN_QUOTE md5: bd026170da89de6784736143c0b59008
  他跟特蕾莎捆在一起生活了七年，七年里，他每走一步，她都在盯着。仿佛她在他的脚踝上套了铁球。现在，
  他的脚步突然间变得轻盈了许多。他几乎都要飞起来了。此时此刻，他置身于巴门尼德的神奇空间：
  他在品尝着温馨的生命之轻。
  #+END_QUOTE

- 351-353, 标注, 2025 年 3 月 26 日星期三 下午 6:46:36
  #+BEGIN_QUOTE md5: cf1b97510b8b3b946d6d14b39c29613c,c655b6be8e4b887a178800e6e181bd2c
  特蕾莎突然闯入他的脑海：他感受到她在写告别信时的那种感觉；他感到她的手在颤抖；他看见了她，
  一只手拖着沉重的行李箱，另一只手用皮带牵着卡列宁；他想象着她把钥匙插进了布拉格的那套公寓的锁眼里转动，
  当门打开的那一刹那，扑面而来的是废弃的凄凉气息，而此时，这气息直钻他的心扉。
  #+END_QUOTE

- 378-379, 标注, 2025 年 3 月 26 日星期三 下午 6:49:29
  #+BEGIN_QUOTE md5: dd9619227d73ce1874014a7ecc137759
  对于我们所有人来说，人的伟大在于他扛起命运，就像用肩膀顶住天穹的巨神阿特拉斯一样。贝多芬的英雄，
  是托起形而上之重担的健将。
  #+END_QUOTE

- 397-399, 标注, 2025 年 3 月 26 日星期三 下午 6:51:22
  #+BEGIN_QUOTE md5: cb9668958e01146cdb63635067fe31f8
  我们都觉得，我们生命中的爱情若没有分量、无足轻重，那简直不可思议；我们总是想象我们的爱情是它应该存在的那种，
  没有了爱情，我们的生命将不再是我们应有的生命。我们都坚信，满腹忧郁、留着吓人的长发的贝多芬本人，
  是在为我们伟大的爱情演奏《Es muss sein！》。 (Es muss sein , 非要如此)
  #+END_QUOTE

- 409-410, 标注, 2025 年 3 月 26 日星期三 下午 6:52:23
  #+BEGIN_QUOTE md5: ae71b97d9d23d24b1a1e2c3631fc67ac
  托马斯感到自己的胃开始痛起来，每逢绝望的时刻，他都会胃痛。
  #+END_QUOTE

- 426-428, 标注, 2025 年 3 月 26 日星期三 下午 6:53:03
  #+BEGIN_QUOTE md5: 9dcfc598d3c90cec0fecc276da3f67c7
  作者要想让读者相信他笔下的人物确实存在，无疑是愚蠢的。这些人物并非脱胎于母体，
  而是源于一些让人浮想联翩的句子或者某个关键情景。
  #+END_QUOTE

- 436-438, 标注, 2025 年 3 月 27 日星期四 下午 12:53:02
  #+BEGIN_QUOTE md5: 7ae6d04e79072006d945e45e31ded4bd
  传出有节奏的咚咚声，想知道到底是什么。人当然不会把自己完全等同于像肉体那样奇异、陌生的东西。肉体是囚笼，
  里面有个东西在看、在听，在害怕，在思索，在惊奇；这东西在肉体消失之后还在，还残存，它就是灵魂。
  #+END_QUOTE

- 520-522, 标注, 2025 年 3 月 27 日星期四 下午 1:12:12
  #+BEGIN_QUOTE md5: f4dd68978c3ef25d5e3cb03fd6592416
  这些书为她提供了一个机会，在虚幻中逃避，摆脱那种毫无快乐可言的生活。作为一种物品，这些书对于她还有一种意义：
  她喜欢抱着书在大街上行走。它们对她来说，就像上个世纪花花公子的漂亮手杖，使她显得与众不同。
  #+END_QUOTE

- 572-576, 标注, 2025 年 3 月 27 日星期四 下午 1:16:09
  #+BEGIN_QUOTE md5: bfb309225adce005dafb67df989e4cd9
  人生如同谱写乐章。人在美感的引导下，把偶然的事件（贝多芬的一首乐曲、车站的一次死亡）变成一个主题，
  然后记录在生命的乐章中。犹如作曲家谱写奏鸣曲的主旋律，人生的主题也在反复出现、重演、修正、延展。
  安娜可以用任何一种别的方式结束生命，但是车站、死亡这个难忘的主题和爱情的萌生结合在一起，在她绝望的一刹那，
  以凄凉之美诱惑着她。人就是根据美的法则在谱写生命乐章，直至深深的绝望时刻的到来，然而自己却一无所知。
  #+END_QUOTE

- 669-669, 标注, 2025 年 3 月 27 日星期四 下午 6:43:20
  #+BEGIN_QUOTE md5: d3491f1a8bcf8b06bcab8e65636aae89
  这份无助的感觉，让她感到发晕，产生了一种强烈的往下坠落的愿望。
  #+END_QUOTE

- 700-702, 标注, 2025 年 3 月 27 日星期四 下午 6:47:48
  #+BEGIN_QUOTE md5: 44ef00563f88b9f1bdbbd3d6b267dd98
  那些画表面总是一个完美无瑕的现实主义世界，而背后呢，就像是舞台背景的那块破布后面，人们看到的是不同的东西，
  某种神秘的或者抽象的东西。” 她停顿了一下，然后接着说：“表面是清晰明了的谎言，背后却是晦涩难懂的真相。”
  #+END_QUOTE

- 703-706, 标注, 2025 年 3 月 27 日星期四 下午 6:48:16
  #+BEGIN_QUOTE md5: ae4f1635f4f853ad4ad0d2e5b8e906d4
  她注意到萨比娜所有的画，无论以前的还是现在的，实际上都在传达着某种同样的东西，是两个主题、两个世界的即时融合，
  就像一些经过两次曝光制作出来的照片。表面是一幅风景画，可深处却是一盏点亮的床头灯，隐隐约约。一幅画着苹果、
  胡桃和灯火闪烁的圣诞树，牧歌般的静物画，背后却是一只痛苦挣扎的手。
  #+END_QUOTE

- 740-742, 标注, 2025 年 3 月 27 日星期四 下午 6:51:50
  #+BEGIN_QUOTE md5: 91416ad54e953a047eddceb5bafa2e44
  沙俄帝国过去所犯下的罪行都隐藏在秘密的阴影中。五十万立陶宛人被放逐，成千上万的波兰人被杀戮，
  对克里米亚的鞑靼人进行灭绝种族的屠杀，所有这一切只留在记忆里，却没有留下任何图片作为证据，
  就像一件无法论证的事情，迟早会被说成是骗人的谎言。
  #+END_QUOTE

- 851-853, 标注, 2025 年 3 月 27 日星期四 下午 6:58:39
  #+BEGIN_QUOTE md5: 9f9a658d2b23c705d4d910813139e334
  眩晕是沉醉于自身的软弱之中。意识到自己的软弱，却并不去抗争，反而自暴自弃。人一旦迷醉于自身的软弱，
  便会一味软弱下去，会在众人的目光下倒在街头，倒在地上，倒在比地面更低的地方。
  #+END_QUOTE

- 972-974, 标注, 2025 年 3 月 27 日星期四 下午 9:50:53
  #+BEGIN_QUOTE md5: a8a572923436f7633fb85bcaf71ce08b
  也许现在更容易理解萨比娜与弗兰茨之间相隔的鸿沟了：他热切地聆听她讲述自己的人生，她也怀着同样的热望听他倾诉。
  他们完全明白彼此所说的话语在逻辑上的意思，却听不到话语间流淌着的那条语义之河的低声密语。
  #+END_QUOTE

- 1004-1005, 标注, 2025 年 3 月 27 日星期四 下午 9:59:04
  #+BEGIN_QUOTE md5: acf47865c7cdde7904f157974d1bc323
  他坚持这样一个信念：忠诚是第一美德，它使我们的生命完整统一。若没有忠诚，人生就会分散成千万个转瞬即逝的印迹。
  #+END_QUOTE

- 1037-1038, 标注, 2025 年 3 月 28 日星期五 上午 7:37:28
  #+BEGIN_QUOTE md5: 940f86f1f6d0acbbe0c41c7b03cb7351
  从早上五点到晚上九点，高音喇叭里不断喀啦喀啦地放出尖厉的音乐。她想哭，但那音乐是欢闹的，无处可逃，
  躲在厕所里不行，蒙在床上的被子里也不行，到处都是高音喇叭。音乐仿佛是一群放出来扑向她的猎犬。
  #+END_QUOTE

- 1043-1047, 标注, 2025 年 3 月 28 日星期五 上午 7:38:31
  #+BEGIN_QUOTE md5: 0ea3fe88e8dd2b48c9c3c2749d31f6eb,346601474c549efb1020541258bcafe9
  噪声有一个好处，让人听不清词语。”从青年时代开始，他所做的一切，就是说话，写字，讲课，编句子，找说法，
  不断修正，改到最后，每个词都弄得不再准确，意义模糊，内涵尽失，只余下碎片、杂屑和尘埃，
  像沙砾一样在他的脑子里翻飞，令他偏头痛，睡不着觉，最终得了失眠的痼疾。
  他朦朦胧胧而又不可遏制地渴望着一种巨大的乐声，一种绝对的噪音，一片美妙欢腾的喧嚣，将所有的一切吞噬，淹没，
  窒息，令话语带来的苦痛、虚幻和空洞永远消失。音乐是对词句的否定，音乐是反话语。
  #+END_QUOTE

- 1051-1052, 标注, 2025 年 3 月 28 日星期五 上午 7:39:24
  #+BEGIN_QUOTE md5: 0349f6ef204d68920d6a3c0ff647a51c
  极端标志着生命的终极之界，极端主义的激情，不论是政治上的，还是艺术上的，都是一种改头换面的对死的渴望。
  #+END_QUOTE

- 1055-1056, 标注, 2025 年 3 月 28 日星期五 上午 8:01:32
  #+BEGIN_QUOTE md5: 7ea12398e2d58bd45e17e528a6bdb5bb
  但在进入萨比娜身体的那一瞬，他还是闭上了双眼。吞噬着他的极度快感企求的是黑暗。那黑暗是彻底的，绝对的，
  没有形象也没有幻影，无穷无尽，无边无际。那黑暗是我们每个人内心所在的无限。
  #+END_QUOTE

- 1075-1077, 标注, 2025 年 3 月 28 日星期五 上午 8:03:39
  #+BEGIN_QUOTE md5: 11e2d6d2c57c28a242d1207e25b28dfe
  身为画家，她精于观察人的脸部。自从到了布拉格，对热衷于监察及评判他人的那类人的长相，她已经相当熟悉。
  这类人全都长着比中指稍长的食指，说话时专用来指戳对方。
  #+END_QUOTE

- 1096-1098, 标注, 2025 年 3 月 28 日星期五 上午 8:07:14
  #+BEGIN_QUOTE md5: 54da02a1806a563f2580af4f594203e1,cb83c8cd55ea0809de170966c02f054e
  当初背叛父亲，她脚下展开的人生就如同一条漫长的背叛之路，每一次新的背叛，既像一桩罪恶又似一场胜利，
  时刻在诱惑着她。她不愿固定在自己的位置上，决不！
  #+END_QUOTE

- 1118-1121, 标注, 2025 年 3 月 28 日星期五 上午 8:09:25
  #+BEGIN_QUOTE md5: b4038d446a8c04e7b0157a36649fe522
  弗兰茨认为限于书本之间的生活是不现实的。他渴望真实的生活，渴望与同他并肩行进的男女接触，渴望听到他们的呼喊。
  他没有觉悟到，他以为不现实的（图书馆里离群的工作），其实是他的现实生活，而被他视作现实的游行不过只是一场戏，
  一支舞，一个节日，或者换句话说：一个梦。
  #+END_QUOTE


* Unwashed Entries                                                  :noexport:
