#+TITLE:  [笔记]翦商:殷周之变与华夏新生 李硕
#+AUTHOR: Yang,Ying-chao
#+DATE:   2025-03-11
#+OPTIONS:  ^:nil H:5 num:t toc:1 \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:  align nodlcheck oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:     noexport(n)
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :jianshang:yi:note:ireader:

- 93-94, 标注, 2025 年 3 月 9 日星期日 下午 8:35:46
 # note_md5: 2649dd82efb896899c7448a04663d714
 #+BEGIN_QUOTE
 也许，我们至今也还难以完全了解我们自己。考古，就犹如一面深埋地下的镜子，倒映出我们陌生的形象
 #+END_QUOTE

- 301-301, 标注, 2025 年 3 月 10 日星期一 上午 7:56:27
 # note_md5: 2d5d3852b06bc9514f28b773681bb0e2
 #+BEGIN_QUOTE
 中国古文明的重要特征是实用和低成本，不重视公共参与性。
 #+END_QUOTE

- 306-308, 标注, 2025 年 3 月 10 日星期一 上午 7:58:13
 # note_md5: 338afb0e44c7fff21d8361bd60ab4fb1
 #+BEGIN_QUOTE
 周灭商后，人祭被周人消除，但周人并未开创一种新的宗教，而是采用世俗的人文主义立场，与极端宗教行为保持距离，不允
 许其干预现实生活，所谓“敬鬼神而远之”。这奠定了后世中国的文化基础。
 #+END_QUOTE

- 317-318, 标注, 2025 年 3 月 10 日星期一 上午 7:59:35
 # note_md5: 7a34fa6fb029a331760214b8a186aacb
 #+BEGIN_QUOTE
 故而，《易经》的内容多是文王的翦商谋略，也正因此，这部分内容最为隐晦。
 #+END_QUOTE

- 346-347, 标注, 2025 年 3 月 10 日星期一 上午 8:03:24
 # note_md5: 2c27e1833b428bd6b28004f7bda82e9f
 #+BEGIN_QUOTE
 也许，我们至今也还难以完全了解我们自己。考古，就犹如一面深埋地下的镜子，倒映出我们陌生的形象。
 #+END_QUOTE

- 349-351, 标注, 2025 年 3 月 10 日星期一 上午 8:03:47
 # note_md5: 68cf5749efd783aaf4df3180bfb14619
 #+BEGIN_QUOTE
 广义的人祭，可以界定为出于宗教理念而杀人奉献给神灵的行为。这里的神灵包含上帝（帝和上帝在商人甲骨文中多次出现）、
 各种自然神以及尊贵的死者亡灵。
 #+END_QUOTE

- 389-390, 标注, 2025 年 3 月 10 日星期一 上午 8:05:57
 # note_md5: 871922a9ace993beef3b807b258bc2c4
 #+BEGIN_QUOTE
 商代甲骨卜辞中的“羌「主要是山西、陕西地区的土著居民，这些人在周代逐渐汇聚成为华夏族。在后世的汉语中，“羌”字又
 演变成汉人对位居西方的少数族群的称谓，这和商代的“羌”已经不是同一种人。
 #+END_QUOTE

- 431-432, 标注, 2025 年 3 月 10 日星期一 上午 8:08:09
 # note_md5: a28dae366daa80082d4229b0c43c5232
 #+BEGIN_QUOTE
 六千多年前的仰韶半坡文化新石器时代，比如陕西临潼的姜寨遗址，
 #+END_QUOTE

- 487-489, 标注, 2025 年 3 月 10 日星期一 上午 8:15:02
 # note_md5: 4b782093aee22500bc2ef45e48e242c4
 #+BEGIN_QUOTE
 以上两千年历程，是新石器中晚期到文明（青铜）时代前夜的变化大趋势：从村落到部落再到早期国家。通俗一点说，就是从
 村级到乡级、县级的递增升级。
 #+END_QUOTE

- 551-554, 标注, 2025 年 3 月 10 日星期一 上午 8:29:25
 # note_md5: 79e6de2bc3ff1ada228b27c2b6832cdc
 #+BEGIN_QUOTE
 在新石器时代，华北地区之所以动辄爆发冲突或战争，人祭兴盛，可能和旱作农业不需要水利设施 11、人群之间没有协作的动
 因有关。而伴随着征服的，是人群共同体规模的不断扩大，从而催生了众多古城和早期国家。
 #+END_QUOTE

- 976-979, 标注, 2025 年 3 月 10 日星期一 下午 7:03:24
 # note_md5: 6ac407bba0eeeeac8c6490637bdb53d0
 #+BEGIN_QUOTE
 石器时代和青铜时代都是常用的词，但这两个词的含义并不对等。青铜器从未完全淘汰石器，它更多体现的是上层人生活的改
 变，就像 古人发明文字后，社会上的多数人仍是文盲。社会的发展水平往往是被占人口少数的精英阶层代表的。但我们不能
 因其数量少而低估青铜，正是它铸造了华夏的最初文明和第一王朝。
 #+END_QUOTE

- 988-990, 标注, 2025 年 3 月 10 日星期一 下午 7:04:39
 # note_md5: 3b0ec3915ec5653ec39692674f5acd2a
 #+BEGIN_QUOTE
 学术界以往对“文明”的界定比较严格，其中有三个关键要素： 城市、冶金技术和文字。按这种标准，商代晚期的殷商阶段属
 于文明，因为有可以释读的甲骨文；后来也发现过早商阶段的甲骨文材料，但极为稀少。总体来说，商代符合严格的文明标准，
 争议不大。
 #+END_QUOTE

- 988-992, 标注, 2025 年 3 月 10 日星期一 下午 7:04:52
 # note_md5: 7edf1098d3ac1c63726e5245106d9d38
 #+BEGIN_QUOTE
 学术界以往对“文明”的界定比较严格，其中有三个关键要素： 城市、冶金技术和文字。按这种标准，商代晚期的殷商阶段属
 于文明，因为有可以释读的甲骨文；后来也发现过早商阶段的甲骨文材料，但极为稀少。总体来说，商代符合严格的文明标准，
 争议不大。 但商代之前的夏-二里头，缺少文字要素；再早的新石器末期古国，如石御、陶寺和良渚等，有万人聚居的大型聚
 落及明显的阶级分层和宏大建筑，却没有或极少有铜器。这些都不符合严格的文明标准。
 #+END_QUOTE

- 1066-1067, 标注, 2025 年 3 月 10 日星期一 下午 7:11:46
 # note_md5: acab695249c74e3478fb10cd1e373672
 #+BEGIN_QUOTE
 二里头-夏朝建成了一个大型聚落和复杂社会，而且依靠青铜技术保持着长期稳定；由此，一千多年来古国兴废无常的难题终
 于被破解。
 #+END_QUOTE

- 1080-1084, 标注, 2025 年 3 月 10 日星期一 下午 7:13:21
 # note_md5: 660308a3916900f5aef1392ce0ff8293
 #+BEGIN_QUOTE
 石器时代通往青铜时代的大门看似很宽，实则很窄。这些困难和偶然性，又催生了关于金属冶炼的神秘玄学观念，认为某些神
 灵会影 响冶炼的成效，所以人们会用不同的形式进行祈福，请神赐予高质量的产品——从夏到商，冶铜区的人祭遗存都比较密
 集，直到钢铁时代，冶炼仍是充满着不确定性和神秘色彩的活动，甚至有工匠舍身投入炼炉、获得高质量金属的传说。
 #+END_QUOTE

- 1362-1364, 标注, 2025 年 3 月 11 日星期二 上午 7:54:41
 # note_md5: 69ffe2fea28284babc2779d5ac6fdbb1
 #+BEGIN_QUOTE
 据说，商人始祖是一名叫简狄的女子，有次在野外洗澡时，她见到玄鸟产下一枚卵，就吞了下去，结果生下儿子契，繁衍出后
 来的商族。上古时代，常有女子未婚生育的神话，据说这是母系时代“知其母， 不知其父”的特征。
 #+END_QUOTE

- 1375-1376, 标注, 2025 年 3 月 11 日星期二 上午 7:56:04
 # note_md5: d24603f3277b2bcc05315a18365db092
 #+BEGIN_QUOTE
 杜甫诗云：“人生不相见，动如参与商
 #+END_QUOTE

- 1375-1377, 标注, 2025 年 3 月 11 日星期二 上午 7:56:24
 # note_md5: ee82b222989920f70ddf7ce10682c344
 #+BEGIN_QUOTE
 杜甫诗云：“人生不相见，动如参与商商星都是黎明时在东方出现，参星总是黄昏时在西方出现，永远一东一西，所以人生分
 离难聚也被称为“参商”。
 #+END_QUOTE

- 1403-1405, 标注, 2025 年 3 月 11 日星期二 上午 8:00:26
 # note_md5: fc7d79f53ad821f08483a0423d2a2303
 #+BEGIN_QUOTE
 对商族来说，王亥遇难和上甲微复仇是生死攸关的事件，也是商族历史上的重要分水岭。 在殷墟甲骨卜辞中，后世商王称王
 亥为“高祖王亥”，经常单独祭祀他；而上甲微多是和之后的历代先君、先王一起接受祭祀，卜辞写作“自上甲”或者“自上甲至
 （某先王）
 #+END_QUOTE

- 1412-1415, 标注, 2025 年 3 月 11 日星期二 上午 8:01:30
 # note_md5: 2d93775d4929954ac78ae90e0b23bbd7
 #+BEGIN_QUOTE
 史书中并没有王亥牧羊的记载。周族人原本在西部高地放牧羊和黄牛，所以，周文王可能是用自己熟悉的生活来想象王亥时代，
 错误地增加了一条“丧羊于易”：羊不适应潮湿环境，不适合王亥时代的商族人。这也说明，《易经》卦爻辞中的商代史事并不
 完全可信，周文王可能会基于西土周人的环境错误地理解商人历史。
 #+END_QUOTE

- 1452-1456, 标注, 2025 年 3 月 11 日星期二 上午 8:07:20
 # note_md5: 9e3119cc113baf459e83acea8c5b2725
 #+BEGIN_QUOTE
 在灭夏之前，商族人很可能已经发明了最初的文字。商业贸易需要记账和远程传递信息，而这都会刺激数字和文字的发明。在
 商人创造文字之前，很多部落已经有了初步的记事符号，比如，对良渚文化和龙山文化的考古，就曾发掘出一些刻划符号的陶
 片。而商族人在迁徙和贸易中与较多部族打过交道，有机会见到各种记事符号的用法，所以，在此基础上进行汇总是完全有可
 能积累起完整记录语言的字符体系的。
 #+END_QUOTE

- 1480-1484, 标注, 2025 年 3 月 11 日星期二 上午 8:09:58
 # note_md5: 6199d9f563c48311fc7c91bcc56cfcb7
 #+BEGIN_QUOTE
 《易经》中也多次出现过鸟。周人和商族起源不同，并不崇拜鸟，但在创作《易经》时，周文王引用了一些与鸟有关的商人的
 历史掌故，如《旅》卦上九爻辞： 鸟焚其巢，旅人先笑后号啖。丧牛于易。凶。 这条爻辞涉及王亥在有易氏丧牛和被杀之事。
 “旅人先笑后号眺”是关于王亥旅行在外的遭遇；而鸟巢被焚毁，则象征王亥的命运。长期以来，人们都没有发现《易经》里隐
 藏的这段掌故，直到民国时期才被顾颉刚破解：“丧牛于易”是说王亥在有易氏部落遇难，牛 群被夺走。
 #+END_QUOTE

- 1548-1549, 标注, 2025 年 3 月 11 日星期二 上午 8:23:39
 # note_md5: 77d1d953e5fa721413270da8d76d0e38
 #+BEGIN_QUOTE
 但其实，早商的奇迹更多，它在二百年左右的时间里创造的成就，其后一千年都难以再现。那是一种几乎抵达秦汉大一统王朝
 的气象。
 #+END_QUOTE

- 1548-1551, 标注, 2025 年 3 月 11 日星期二 上午 8:23:56
 # note_md5: d97af631c7ded2c2c1173069ee5e6f05
 #+BEGIN_QUOTE
 但其实，早商的奇迹更多，它在二百年左右的时间里创造的成就，其后一千年都难以再现。那是一种几乎抵达秦汉大一统王朝
 的气象。比如，它拥有地跨千里的遥远殖民城邑，有规模庞大到脱离当时人口总量和经济水平的大型仓储设施。 可以这么说，
 在早期青铜时代，早商堪称一场“现代化”奇迹。
 #+END_QUOTE

- 1589-1591, 标注, 2025 年 3 月 11 日星期二 上午 8:29:48
  # note_md5: 8107d4ad5be154460d0ff811db54efeb
  #+BEGIN_QUOTE
  灭夏时，商人已有了初步的文字。这是建立真正王朝统治的必要工具。商人应当也会利用宗教的神秘感和威慑力，虽然我们目
  前对于商初宗教的了解还很少，但从后来其在商朝的重要地位看，早期的商王们肯定在宗教上投入过相当大的精力。
  #+END_QUOTE

* Unwashed Entries                                                  :noexport:

- 2349-2352, 标注, 2025 年 3 月 12 日星期三 上午 7:52:56
  #+BEGIN_QUOTE md5: d98d0671b1b34040cead6c3221331481
  到这里，一切似乎都很自然，但考古发掘揭开了惊悚的一幕。 一座两间连体的房子（F2）西墙的基槽里，埋着一件陶罐，里
  面是一具不满三岁的幼儿尸骨。显然，这是给新房奠基的巫术，用幼儿向土地之神献祭，以保佑家宅平安。献祭的死者不止幼
  儿，朝东的屋前还有四座祭祀坑，其中三座各埋入一只猪、牛、羊，第四座坑（H104）埋的则是人。
  #+END_QUOTE

- 2371-2373, 标注, 2025 年 3 月 12 日星期三 上午 7:56:39
  #+BEGIN_QUOTE md5: dd6645d5e2c39b52a4693ac6282abf29
  屋檐下悬挂人头的不止 F2，紧挨着的 F6 亦是如此：F6 由两间北屋和四间西屋构成，西墙内夯筑了一颗人头，是一名大约十八岁
  的女性的；在房子坍塌的泥土中散落着五枚人头骨，之前应当也是悬挂在屋檐之下的。
  #+END_QUOTE

- 2947-2948, 标注, 2025 年 3 月 12 日星期三 下午 10:54:49
  #+BEGIN_QUOTE md5: 8afcd9857c3e34f5acd611e51d93c6f5
  后来的周人史诗把他们的灭商事业称为“翦商”，也是取其宏大之意。
  #+END_QUOTE

- 3082-3084, 标注, 2025 年 3 月 13 日星期四 上午 7:52:53
  #+BEGIN_QUOTE md5: 0c2844d76d94e18d4b66cd21616c19c7
  这种规则之下，商王需要直接管理的王朝事务比较少，其最重要的事务是组织祭祀和战争，而商人各宗族则承担提供祭祀贡品
  和战争兵员（自带装备）的任务。所谓：“国之大事，在祀与戎。”这正是家族
  #+END_QUOTE

- 3082-3084, 标注, 2025 年 3 月 13 日星期四 上午 7:52:59
  #+BEGIN_QUOTE md5: 4aba7445af6fc25d37bd277d0a494bc7
  这种规则之下，商王需要直接管理的王朝事务比较少，其最重要的事务是组织祭祀和战争，而商人各宗族则承担提供祭祀贡品
  和战争兵员（自带装备）的任务。所谓：“国之大事，在祀与戎。”这正是家族分封制而非官僚帝制时代的规则。
  #+END_QUOTE

- 3124-3125, 标注, 2025 年 3 月 13 日星期四 上午 7:58:15
  #+BEGIN_QUOTE md5: cb4487eb016139cb1202d7a5acd09ad7
  商王有一种军事征伐的仪式，名“步”，甲骨文写作□或□，字面意思是步行，可能是指商王全副武装带领部队行军。甲骨卜辞中
  有大量王“步”的记载。
  #+END_QUOTE

- 3124-3126, 标注, 2025 年 3 月 13 日星期四 上午 7:58:20
  #+BEGIN_QUOTE md5: 172ed87e75e5f8a19e23e8c8959c4c38
  商王有一种军事征伐的仪式，名“步”，甲骨文写作□或□，字面意思是步行，可能是指商王全副武装带领部队行军。甲骨卜辞中
  有大量王“步”的记载。在殷都时代，商王行猎或出征一般会乘坐马车， 但“步”这种古老而威严的仪式一直存在
  #+END_QUOTE

- 3128-3129, 标注, 2025 年 3 月 13 日星期四 上午 7:58:25
  #+BEGIN_QUOTE md5: 6877c5fe6ff7f5634a8b53518f92171c
  周人也学习了“步”的仪式，比如，有些文献就记载过周武王“步”而行军，和甲骨卜辞很相似：“王乃步自于周，征伐商王纣。”
  （《
  #+END_QUOTE

- 3136-3137, 标注, 2025 年 3 月 13 日星期四 上午 7:59:28
  #+BEGIN_QUOTE md5: 580d63064e98bbd2efa68970bf133eec
  商朝不可能被武力摧毁，却可能会因异族熏染而堕落。如何维持地跨千里的广域王朝，让商族保持自己的高贵特性，是早商时
  代留下的命题。
  #+END_QUOTE

- 3145-3147, 标注, 2025 年 3 月 13 日星期四 上午 8:00:47
  #+BEGIN_QUOTE md5: 383e7b8cb00d04a0f56aae5b06c7da0d
  幸运的是，郑州最发达的铸铜和制骨作坊都在城外，它们所代表的群体才是商人传统的保存者，并在内战中挫败了城内欲废人
  祭的“改革派”。商族传统精神离不开那些分散而自治的商人族邑，就像美国的白人精神离不开南方种植园的“红脖子”
  #+END_QUOTE

- 3145-3147, 标注, 2025 年 3 月 13 日星期四 上午 8:00:51
  #+BEGIN_QUOTE md5: 0ac794fdfda64c07360266461e095c41
  幸运的是，郑州最发达的铸铜和制骨作坊都在城外，它们所代表的群体才是商人传统的保存者，并在内战中挫败了城内欲废人
  祭的“改革派”。商族传统精神离不开那些分散而自治的商人族邑，就像美国的白人精神离不开南方种植园的“红脖子”一样。
  #+END_QUOTE

- 3192-3193, 标注, 2025 年 3 月 13 日星期四 上午 8:04:25
  #+BEGIN_QUOTE md5: 2c9700b1962888ec7a68376b62e8e9bb
  铭文“后母辛”：“辛”是妇好的出生日，用天干日起名是商人的习俗；“后母”，则是她为商王生育过子女后获得的尊称。
  #+END_QUOTE

- 3306-3307, 标注, 2025 年 3 月 13 日星期四 上午 8:18:01
  #+BEGIN_QUOTE md5: bae4d487ba80289d92570137bd354c79
  有卜辞显示，妇妌被后世商王尊称为“妣戊妌”。（《屯南》4023）这说明她出生日的天干是戊，也是著名的“后母戊鼎”和王陵
  区 M160 墓的主人。
  #+END_QUOTE

- 3309-3309, 标注, 2025 年 3 月 13 日星期四 上午 8:18:18
  #+BEGIN_QUOTE md5: b1dbab7cb7f120870346ce8ace13c1a5
  武丁是商朝历史上一位很重要的王，奠定了殷都的格局以及商朝 后期的疆域，遂被后世称为“高宗”。
  #+END_QUOTE

- 3326-3328, 标注, 2025 年 3 月 13 日星期四 上午 8:19:50
  #+BEGIN_QUOTE md5: ee336ae7d2a0e8a0682e7fbb126b5731
  《帝王世纪》的信息来源也是一个谜。这本书写作于 4 世纪初，比司马迁晚了四百年左右，没人知道它为什么能提供司马迁没
  有记载的史事。看来，有些历史碎片虽然没有进入儒家的“六经”，也没载入《史记》，但从商周到秦汉三国，它们一直在阴影
  中流传。
  #+END_QUOTE

- 3431-3433, 标注, 2025 年 3 月 13 日星期四 上午 8:24:58
  #+BEGIN_QUOTE md5: 7f8dea0ea14ba793851db9579f90d05a
  “子”自少年时代“入学”，在王室大学里学习各种贵族技能，比如“舞戊”。商人的“舞”并非后世意义上的表演性舞蹈，而是团体
  实兵演练，甚至有伤亡的可能。
  #+END_QUOTE

- 3433-3433, 笔记, 2025 年 3 月 13 日星期四 上午 8:25:33
  #+BEGIN_QUOTE md5: f6e5b97a627c00446ff324af460db35e
  质子团,上!
  #+END_QUOTE

- 3446-3448, 标注, 2025 年 3 月 13 日星期四 上午 8:26:36
  #+BEGIN_QUOTE md5: 0e304ae535a91f394a119dac7bf7c4d7
  甲骨文中的“疫”字，字形是一个人躺在床上，身下正在出汗，有人手拿锤子打击其腹部，象征病痛的状态。另有一种解释则为
  手拿廷石为患者做按摩治疗。无论哪种，它反映的都是卧床生病。
  #+END_QUOTE

- 3572-3576, 标注, 2025 年 3 月 13 日星期四 上午 8:33:49
  #+BEGIN_QUOTE md5: 91b73d3a7d0d6f9db55b18d6240e23bb
  由于从未被盗掘者发现，坑内甲骨保存得非常完整。许多整版的龟甲虽然遍布裂纹，非常脆弱，但经过技术处理，基本保持了
  原貌。倘若是被非法盗掘，绝大部分甲骨都将变成碎片，无法识别。历代商王留下的甲骨卜辞虽然数量多，但大都是盗掘出土，
  非常凌乱，很多同属一王或同一批次的卜辞都丧失了联系。考古学者们希望通过字体和占卜师的名字对零散的卜辞进行分组、
  划分年代，但结论往往充满争议。这是盗掘带来的无法挽回的信息损失。
  #+END_QUOTE

- 3703-3705, 标注, 2025 年 3 月 13 日星期四 下午 6:30:24
  #+BEGIN_QUOTE md5: 61e864264f7516a50187e7fd43434552
  这是上古时代的常态：并非所有的人类社群都会自动进化成更大的共同体和国家；事实是，多数会一直停滞无为，直到被强大
  的古国或王朝吞并，被强行裹挟进人类的“发展”大潮中。
  #+END_QUOTE

- 3787-3788, 标注, 2025 年 3 月 13 日星期四 下午 6:37:51
  #+BEGIN_QUOTE md5: 22b150f5c9649279d8495b4171157c49
  商朝授予周文王的封号则是“周方伯”。6伯是异族酋长，商朝是不会给异族头领“侯”的称号的。
  #+END_QUOTE

- 3789-3791, 标注, 2025 年 3 月 13 日星期四 下午 6:37:58
  #+BEGIN_QUOTE md5: 68113a39d4ad96092414d3eb4b84eb7e
  妇某”的称呼专用于商族血统的后妃，比如著名的妇好。倘若是异族女子，哪怕成为商王宠妃，也不会享有这种称呼，比如末
  代商纣王宠爱的妲己，她来自“己”姓的苏国，而非“子”姓的商族，所以不能称“妇妲”。
  #+END_QUOTE

- 3938-3939, 标注, 2025 年 3 月 13 日星期四 下午 6:47:33
  #+BEGIN_QUOTE md5: 9a3b3b559022debf8147c52a18d3eaf0
  西周之后，人们还创造了那些更古老的半神帝王的“创世记”，比如黄帝和炎帝，嫁接和混淆了很多周族早期传说，造成了很多
  混乱。
  #+END_QUOTE

- 3969-3973, 标注, 2025 年 3 月 13 日星期四 下午 6:50:09
  #+BEGIN_QUOTE md5: 3aee695096728b1a76c0aa439ddee6b3
  同样是未婚生子，简狄繁衍出商族，姜嫄繁衍出周族。有学者认为，这是人类早期母系家族的表现：女子不出嫁，男子到外部
  落约会临时性伴侣，所谓生子“知其母，不知其父”。不过要注意，在《生民》里，姜嫄发现自己未婚先孕后，还是会感到恐惧。
  而这是父系家族时代的观念。所以，《生民》反映的应该是母系家族和父系家族正交替的时代，在当时，两种家族观念还杂糅
  并存。这也正是男性始祖领袖产生的背景：从母系家族诞生，然后建立起自己的父系家族与国族。
  #+END_QUOTE

- 4175-4183, 标注, 2025 年 3 月 13 日星期四 下午 10:56:53
  #+BEGIN_QUOTE md5: ba786a54df826a927540b6b3195ef3f0
  关于周人更古老的始祖，或者说商、周等各民族的始祖，春秋时还出现了黄帝和炎帝的说法。有一种说法是：“黄帝以姬水成，
  炎帝以姜水成。”意思是说，黄帝住在“姬水”旁边，所以用“姬”姓；炎帝住在“姜水”旁边，所以用“姜”姓。7这其实是把羌人和
  周人曾经的共生关系推到了更古老的时代：炎帝成了羌人的始祖，黄帝则成了周人、商人以及其他各族群的始祖。 史学大家
  顾颉刚称这种现象为“层累地造成的中国古史”，意思是说，越晚产生的传说，反倒在神谱里面越古老，就像人们堆柴堆，“后
  来者居上”。因为时代越晚，各族群的祖先传说就越是逐渐汇总到一起，这时，各自的先祖孰先孰后以及谁比谁厉害就成了问
  题。因此，为了制造更大范围的身份认同，就只能创作更古老的先祖，给各族群增添一位共同的始祖。先祖诸神的关系和谐了，
  世间各族群的关 系才能和谐。
  #+END_QUOTE

- 4231-4232, 标注, 2025 年 3 月 13 日星期四 下午 11:03:21
  #+BEGIN_QUOTE md5: 4cc0c0b101af2537a08779511556cedb
  “周”字的甲骨文写作图或用，古文字学家认为，这是耕作的农田的形状，因后稷以来的周人擅长耕作，所以便用农田的造型来
  表示周。
  #+END_QUOTE

- 4247-4250, 标注, 2025 年 3 月 14 日星期五 上午 7:55:19
  #+BEGIN_QUOTE md5: 055369b10a937c7c02ee0c18b0c83f16
  姜嫄生的这一对儿子，不仅分化成为两支周族，也被后世创造为黄帝和炎帝，成为整个华夏世界的共同祖先。这背后的原理是，
  自西周以来，姬周文化成为正统，他们的族源故事自然成为重新创作古史的首选素材。当然，其他东方部族的族源传说也会是
  素材，但地位远不如周族始祖化身那样处于核心地位。
  #+END_QUOTE

- 4378-4381, 标注, 2025 年 3 月 14 日星期五 上午 8:06:27
  #+BEGIN_QUOTE md5: f70d174c1a5365ddc623cbdb40888715
  夯土版筑需要密集的协作劳动，周人便唱起节奏明快的歌谣来协调动作。周人史诗的四字句，很可能就源自集体劳作时的“夯
  歌”。当上百堵土墙同时动工，轰隆隆的夯筑声比鳄鱼皮鼓还响亮：“揉之膜膜，度之薨薨。筑之登登，削屡冯冯。百堵皆兴，
  暮鼓弗胜。”
  #+END_QUOTE

- 4381-4381, 笔记, 2025 年 3 月 14 日星期五 上午 8:07:05
  #+BEGIN_QUOTE md5: 7066f53894dbd810f0a09a38da4f87f9
  封神电影中类似的场景
  #+END_QUOTE

- 4389-4391, 标注, 2025 年 3 月 14 日星期五 上午 8:08:03
  #+BEGIN_QUOTE md5: b2f4c59fdfcf210afc864865a976d9d3
  在后世周人的史诗里，亶父被尊为“大王”（太王，古老的王）， 他迁居岐山之阳的周原，也被描述成周人“翦商”事业的开端：
  后稷之孙，实维大王。居岐之阳，实始翦商。（《诗经·鲁颂·宫》）
  #+END_QUOTE

- 4420-4421, 标注, 2025 年 3 月 14 日星期五 上午 8:10:33
  #+BEGIN_QUOTE md5: 52720d355cdcf78f304e47d00e8b80a8
  但武乙王却在此次巡视和亲征中离奇地死亡，据《史记·殷本纪》：“武乙猎于河渭之间，暴雷，武乙震死。”“震死”，就是被
  雷电劈死。未济卦九四爻辞中的“震”似乎也与此有关。
  #+END_QUOTE

- 4444-4447, 标注, 2025 年 3 月 14 日星期五 上午 8:15:35
  #+BEGIN_QUOTE md5: 30d584fcd3428c5652b27ea60efb3750
  季历时代的周族尚未脱离野蛮色彩，因此，从相对繁华开化的中原远嫁荒僻西土，这让大任一直难以适应。后世经过改造的历
  史说，大任在怀胎（周昌）之后，“目不视恶色，耳不听淫声，口不出敖（傲）言”，全面符合儒家的妇道礼仪，是胎教的创始
  人。其 实，这很可能是和丈夫疏远而造成的家庭生活冷淡所致。
  #+END_QUOTE

- 4519-4519, 标注, 2025 年 3 月 14 日星期五 上午 8:25:44
  #+BEGIN_QUOTE md5: 5ed31f7c0e7e6829ca4fca9a6a80d1a0
  渭河上喧嚣了起来，很多条小木船被系在河中，上面铺有木板，一座浮桥就这样搭了起来。
  #+END_QUOTE

- 4535-4535, 标注, 2025 年 3 月 14 日星期五 上午 8:28:07
  #+BEGIN_QUOTE md5: c01e51ed4afe27f894e464cb09985a02
  他的头衔是“太保”，意为“国君的监护人”。
  #+END_QUOTE

- 4553-4554, 标注, 2025 年 3 月 14 日星期五 上午 8:30:01
  #+BEGIN_QUOTE md5: fb55888c571364b0d3c98f06ac1114f5
  商王帝乙可能在位二十六年，6然后由儿子帝辛继任，这便是末代商王纣。他名为“受”，也称“辛受”。“纣”可能是后世周人给
  他的贬义称呼。
  #+END_QUOTE

- 4555-4557, 标注, 2025 年 3 月 14 日星期五 上午 8:31:02
  #+BEGIN_QUOTE md5: 6246fdd9d6ab060499851a8c514f7010
  从《易经》的一些内容来看，周昌年轻时经常带领族人远征羌戎部落，积累了很多捕俘经验。不过随着儿子们逐渐长大，周昌
  开始脱离征战厮杀，由长子伯邑考和次子周发（后来的武王）更多地承担军事工作。
  #+END_QUOTE

- 4569-4570, 标注, 2025 年 3 月 14 日星期五 上午 8:33:19
  #+BEGIN_QUOTE md5: 93ab51b673a50dfd1e15a46f4ff08f2d
  甲骨占卜的表面原理是观察骨头或龟甲上烧烫出的裂纹（兆纹），解读吉凶；但其深层原理却是通灵，即向某些特定的神灵询
  问神意。
  #+END_QUOTE

- 4575-4577, 标注, 2025 年 3 月 14 日星期五 上午 8:34:43
  #+BEGIN_QUOTE md5: 25075959db4bface5fbedee2a9ed8636
  周昌还想尽办法搜罗来自商朝境内的人，以获取和利用商朝上层的占卜通神技术。《史记·周本纪》说，文王礼贤下士，为了
  接待外来的有才之人，经常到中午还顾不上吃饭，所以从商朝投奔他的人逐渐多了起来，
  #+END_QUOTE

- 4642-4646, 标注, 2025 年 3 月 14 日星期五 下午 6:37:23
  #+BEGIN_QUOTE md5: 5b0675abdc6b4dd67b5afcbe682ecd63
  沉迷占卜算命的人，大都信仰各种超自然能力和现象，包括那些神异的传说。根据商人传说，玄鸟（燕子）是商王的祖先。在
  《易经》里，有“飞鸟以凶”和“飞鸟遗之音”之类的说法。也就是说，周昌已经注意到飞鸟会给敌人传递信息，他应该是认为，
  倘若燕子发现自己的秘密，就会报告给商纣王。而燕子喜欢在屋檐下或屋梁上做巢。所以，为了躲开这些随时飞来的耳目，周
  昌只能躲进地窖，盖严木板，点起油灯。
  #+END_QUOTE

- 4717-4718, 标注, 2025 年 3 月 14 日星期五 下午 6:41:19
  #+BEGIN_QUOTE md5: 8b1b4d3618cc86b3e201c3ba686620a0
  和这段历史一起被遗忘的，是商朝的鬼神血祭文化。自周朝建立，人们的记忆里便再也没有了那个血腥、恐怖而漫长的年代，
  “历史”成为一连串古代圣王哺育和教化群氓的温情往事。
  #+END_QUOTE

- 4718-4718, 笔记, 2025 年 3 月 14 日星期五 下午 6:41:48
  #+BEGIN_QUOTE md5: 4aaa2bc839e8b1f0523dec07061f6083
  我们生活在故事之中
  #+END_QUOTE

- 4733-4734, 标注, 2025 年 3 月 14 日星期五 下午 6:45:53
  #+BEGIN_QUOTE md5: 32645099a86e6e28d4c3d1bdd3d82038
  《易经》是商朝末年的产物，释读其中的文字，需要参照商人的甲骨文。甲骨文的“孚”，写作□，字形是一只手抓住一个儿童，
  乃俘获之意，且特指捉来献祭的人牲。
  #+END_QUOTE

- 4791-4793, 标注, 2025 年 3 月 14 日星期五 下午 6:52:55
  #+BEGIN_QUOTE md5: e11a338a212165f02c32a8e0ccac19ee
  大壮卦为何要用公羊代表羌人，还写得这么隐晦？本书认为，这可能是因为周人和羌人有古老的同宗亲缘，对周族来说，替商
  朝捕猎羌人在道义上是一种耻辱。所以，即便创作《易经》时，周昌已经比较商化，使用的也是商人的语言和思维，但他还是
  表达得非常隐晦，甚至不愿写出“羌”字。
  #+END_QUOTE

- 5007-5009, 标注, 2025 年 3 月 15 日星期六 下午 12:03:33
  #+BEGIN_QUOTE md5: 7a48175fbf0b2dc57f8fffdbd3bdb6d5
  《易经》的坎卦是关于牢狱生活的。坎，古人注解为“坎陷”，即挖掘的壕沟或地洞。六十四卦中的坎，是两个八卦的坎卦□相
  重叠，所以卦名叫“习坎”。习是两重之意，《彖辞传》解释为“重险”，即 两重险阻，7可能是指监狱外还有两道壕沟起隔离作
  用。
  #+END_QUOTE

- 5042-5044, 标注, 2025 年 3 月 15 日星期六 下午 12:05:35
  #+BEGIN_QUOTE md5: b2059719b5c900dbafd3c9c179edd626
  “胏”是骨头上的干肉；“得金矢”，是说居然吃出了铜箭头。这很可能说的是被射死的人牲的主要部位被烹饪献祭，下脚料（肉
  皮和筋骨等）则被送到监所充作犯人的食物，而且给犯人（候补人牲）吃的都是干肉，没有经过烹饪。“
  #+END_QUOTE

- 5045-5046, 标注, 2025 年 3 月 15 日星期六 下午 12:05:53
  #+BEGIN_QUOTE md5: b731bfec5c4a5c0e0e26bcabc2078723
  到六五爻，内容还是吃干肉：“噬干肉，得黄金。”黄金指黄色的铜，应是被杀者身上佩戴的某种小铜饰。
  #+END_QUOTE

- 5047-5047, 标注, 2025 年 3 月 15 日星期六 下午 12:06:08
  #+BEGIN_QUOTE md5: e39bc85a1a2c99e2812b585029c17e32
  《易经》的困卦也是关于牢狱生活的。
  #+END_QUOTE

- 5115-5118, 标注, 2025 年 3 月 15 日星期六 下午 3:56:09
  #+BEGIN_QUOTE md5: 4a038da1d34dac070efcfe101708826d
  史记·殷本纪》有载：“帝纣资辨捷疾，闻见甚敏，材力过人，手格猛兽。”然而，他的缺点可能也正在于此：过于自信，认为
  世人能力皆不如己，从不听取别人的意见，哪怕做错的事情，他也有给自己辩解的才能，正所谓：“知（智）足以距（拒）谏，
  言足以饰非；矜人臣以能，高天下以声，以为皆出己之下。”
  #+END_QUOTE

- 5135-5138, 标注, 2025 年 3 月 15 日星期六 下午 3:58:53
  #+BEGIN_QUOTE md5: 4b8d6cf348eea8076b62c24563830885
  如前文所述，剥卦六五爻曾说：“贯鱼以宫人宠，无不利。”这里说的宫内宦官贯鱼到牢狱探访文王可能就是苏妲己授意的。在
  后世的演义文学中，苏妲己是可怕的狐狸精，一心谋害周昌，而真实的历史很可能是，苏妲己才是让周昌获释出狱的关键因素。
  #+END_QUOTE

- 5135-5139, 标注, 2025 年 3 月 15 日星期六 下午 3:59:07
  #+BEGIN_QUOTE md5: 6ea3bb89ac25438e67b3b7415d9f366c
  如前文所述，剥卦六五爻曾说：“贯鱼以宫人宠，无不利。”这里说的宫内宦官贯鱼到牢狱探访文王可能就是苏妲己授意的。在
  后世的演义文学中，苏妲己是可怕的狐狸精，一心谋害周昌，而真实的历史很可能是，苏妲己才是让周昌获释出狱的关键因素。
  这段恩情对于周族非常重要，妲己虽背负诸多恶名而死，但周人夺取天下之后，武王还是重用了她的家人。
  #+END_QUOTE

- 5150-5153, 标注, 2025 年 3 月 15 日星期六 下午 4:01:30
  #+BEGIN_QUOTE md5: b4eb16a597bf4f0ffac3fe4073a9ff00
  周昌这次似乎因祸得福，伯邑考受到了纣王青睐，在殷都宫廷里担任质子，并给纣王驾驶马车：“质于殷，为纣御。”（《太平
  御览》卷 八四引《帝王世纪》）要知道在商周时期，凡为王驾车的人，地位都很高。作战之前，统帅经常占卜选择御者，因
  为这个职务能决定王的安危生死。周人在豳地-碾子坡时期就熟悉养马，迁居周原后又从商朝引进了马车，所以伯邑考擅长驾
  驭马车是很自然的。
  #+END_QUOTE

- 5320-5325, 标注, 2025 年 3 月 15 日星期六 下午 10:56:20
  #+BEGIN_QUOTE md5: 39da5f96763fbc2fc24dcaf888851ec7
  但六十四卦则与此不同，它的原理更复杂。它认为，世间的一切并不都是由神直接决定的，而是各种事物会发生互相影响并形
  成一种因果发展的链条，其对应的就是卦里六个爻的阴阳顺序。换句话说，对于每一个主题的卦，周文王都需要找出与之相关
  的六个事件或现象作为六条爻辞，从而构成一个完整的因果发展链。而且，事物的因果关系不会只有一种模式。在某种环境下，
  甲是乙的原因，而在另一种环境下，则可能变成乙是甲的原因，甚至原本没有因果关系的两个孤立事件，在另一种时空环境下
  也可能会发生联系。
  #+END_QUOTE

- 5320-5325, 标注, 2025 年 3 月 15 日星期六 下午 10:56:32
  #+BEGIN_QUOTE md5: fc61c8ec573cb9db302e08598d893278
  六十四卦则与此不同，它的原理更复杂。它认为，世间的一切并不都是由神直接决定的，而是各种事物会发生互相影响并形成
  一种因果发展的链条，其对应的就是卦里六个爻的阴阳顺序。换句话说，对于每一个主题的卦，周文王都需要找出与之相关的
  六个事件或现象作为六条爻辞，从而构成一个完整的因果发展链。而且，事物的因果关系不会只有一种模式。在某种环境下，
  甲是乙的原因，而在另一种环境下，则可能变成乙是甲的原因，甚至原本没有因果关系的两个孤立事件，在另一种时空环境下
  也可能会发生联系。
  #+END_QUOTE

- 5317-5320, 标注, 2025 年 3 月 15 日星期六 下午 10:56:44
  #+BEGIN_QUOTE md5: 63156d6dce005632e4b19f675ddd1353
  甲骨文的这些刻辞不太复杂，背后的原理也很简单，基本不涉及事物的因果关系：先是给诸神献祭并询问问题；然后，诸神的
  回答就会传递到甲骨的烫纹上；最后，占卜者将其解读出来。也就是说，这是一种单一的因果叙事：诸神的决定是因，表现到
  人间就是果，甲骨占卜是读取这种因果关系的工具。至于人类有时候占卜错了，那也是误读了神的旨意，错在人而不在神。
  #+END_QUOTE

- 5363-5366, 标注, 2025 年 3 月 16 日星期日 上午 10:46:40
  #+BEGIN_QUOTE md5: 7c7bab60ad43cf4616df13e0f12b82ad
  本书认为，它是文王发现的 世间规律，或者说，一种被称为“易”的思维方式：世间的一切都不是永恒和持续不变的，它们都
  可以有另一种相反的存在形式，一切也都可以颠倒重来一遍。 否，颠倒重来就是泰；损，颠倒重来就是益……一切事件的发展
  过程，都可以“倒放”一遍，从终点回到起点。这意味着，一切皆有可能。
  #+END_QUOTE

- 6332-6334, 标注, 2025 年 3 月 17 日星期一 上午 8:20:40
  #+BEGIN_QUOTE md5: 81a043e127513537f9b4b66bd8872771
  不要背叛我的援助，不要羡慕我施与别人的恩惠，（只要你一心虔诚）就能先上岸…… 帝谓文王：无然畔援，无然歆羡，诞先
  登于岸。
  #+END_QUOTE

- 6352-6353, 标注, 2025 年 3 月 17 日星期一 上午 8:22:32
  #+BEGIN_QUOTE md5: cfb412926a9d25d97222b44785748649
  上帝是天，天也是上帝；上帝的命令是“天命”，上帝的关注就是“天监”。
  #+END_QUOTE

- 6353-6353, 笔记, 2025 年 3 月 17 日星期一 上午 8:23:09
  #+BEGIN_QUOTE md5: 77e36dd896e2ad7f98fc4ca62e599bbd
  司天监
  #+END_QUOTE

- 6376-6380, 标注, 2025 年 3 月 17 日星期一 上午 8:29:37
  #+BEGIN_QUOTE md5: 50ac3d607e2a98d3796f4d8cecb8164e
  《易经》的蹇卦和解卦成对，内容皆与派使者联络西南的盟友有关。蹇卦的卦辞有“利西南，不利东北”，解卦的卦辞则有“利
  西南”。以周原为坐标，殷都在东北方，而西南方（今陕西汉中、甘肃陇西及四川地区）则有大量土著部族，是文王重点争取
  的目标。所以，坤卦的卦辞曰：“西南得朋，东北丧朋。”到后来周武王灭商时，盟军中确 实有蜀、鬃、微、卢、彭和濮等西
  南部族。
  #+END_QUOTE

- 6404-6406, 标注, 2025 年 3 月 17 日星期一 上午 8:32:42
  #+BEGIN_QUOTE md5: 7cddef84cd5308b350632a7b4070e0a1
  “天命玄鸟，降而生商。”商人认为，鸟是商族的保护神，为上帝传递消息的信使，所以在甲骨卜辞的记载中，商王经常用牲畜
  及人牲向“鸟”献祭。而这显然会让心存翦商之念的文王产生疑心和恐慌，把飞鸟视作凶险的信号，所谓“飞鸟遗之音”，即是担
  心鸟类会察觉到自己的谋逆行为，并用某种方式传递给商纣王。
  #+END_QUOTE

- 6443-6445, 标注, 2025 年 3 月 17 日星期一 上午 8:37:28
  #+BEGIN_QUOTE md5: c463394c2cfca32d6a8679e00285cf17
  总体来说，明夷卦各爻辞非常晦涩，越是和翦商事业密切相关的，就越是隐约其词。 在商朝上层，文王的内线应该不止箕子，
  如前文所述，可能还有苏妲己和王子武庚，但《易经》中并没有出现他们的名字，至少没有公然出现。
  #+END_QUOTE

- 6456-6458, 标注, 2025 年 3 月 17 日星期一 上午 8:39:10
  #+BEGIN_QUOTE md5: f8f2edbc91207459cac163cf6d5b7507
  在那个时代，人们制造鬼神，被鬼神主宰拨弄，但又逐渐心有不甘。这已不全然是神话时代，已经具有“文明”的一切要素，虽
  然这“文明”仍在血污与恐怖中挣扎。
  #+END_QUOTE

- 6454-6458, 标注, 2025 年 3 月 17 日星期一 上午 8:39:17
  #+BEGIN_QUOTE md5: 1bd862e120f25685211f5a88477cf5d9
  程度还要超过周人。 同样，对于甲骨卜辞，无论殷墟的还是周原的，我们或许能够识别出多数常用字，甚至能够大体判断每
  个句子的意思，但无法确知他们为什么要那么做，为什么要那么想。毕竟，我们很难有设身处地的感受和理解。 在那个时代，
  人们制造鬼神，被鬼神主宰拨弄，但又逐渐心有不甘。这已不全然是神话时代，已经具有“文明”的一切要素，虽然这“文明”仍
  在血污与恐怖中挣扎。
  #+END_QUOTE

- 6454-6458, 标注, 2025 年 3 月 17 日星期一 上午 8:39:26
  #+BEGIN_QUOTE md5: accaad549585bbf0eccd5149532c8542
  ，我们或许能够识别出多数常用字，甚至能够大体判断每个句子的意思，但无法确知他们为什么要那么做，为什么要那么想。
  毕竟，我们很难有设身处地的感受和理解。 在那个时代，人们制造鬼神，被鬼神主宰拨弄，但又逐渐心有不甘。这已不全然
  是神话时代，已经具有“文明”的一切要素，虽然这“文明”仍在血污与恐怖中挣扎。
  #+END_QUOTE

- 6454-6458, 标注, 2025 年 3 月 17 日星期一 上午 8:39:37
  #+BEGIN_QUOTE md5: 10a96da781d61cd1441dbd9c0ca6cbe8
  对于甲骨卜辞，无论殷墟的还是周原的，我们或许能够识别出多数常用字，甚至能够大体判断每个句子的意思，但无法确知他
  们为什么要那么做，为什么要那么想。毕竟，我们很难有设身处地的感受和理解。 在那个时代，人们制造鬼神，被鬼神主宰
  拨弄，但又逐渐心有不甘。这已不全然是神话时代，已经具有“文明”的一切要素，虽然这“文明”仍在血污与恐怖中挣扎。
  #+END_QUOTE

- 6500-6501, 标注, 2025 年 3 月 17 日星期一 下午 12:53:57
  #+BEGIN_QUOTE md5: 2af7af76ac7cc8e49a53c7b9048a6ab3
  纣王的回答则注定会成为后世的经典:“我生不有命在天乎！”翻译为白话就是，不是只有天才能决定我的命运吗？
  #+END_QUOTE

- 6501-6501, 笔记, 2025 年 3 月 17 日星期一 下午 12:54:23
  #+BEGIN_QUOTE md5: e6a1889728d0a8a10bb1f48fafc07b58
  哪吒何在
  #+END_QUOTE

- 6506-6510, 标注, 2025 年 3 月 17 日星期一 下午 12:55:22
  #+BEGIN_QUOTE md5: 936a95e52d6a5fef0a40c6d408a9b901
  后人实在难以理解，在商朝的最后几年，纣王到底处于何种状态，他为何会对周人如此咄咄逼人的扩张态势毫无反应。这似乎
  是个千古之谜，尤其我们试图复原这段历史时，会愈发感到其中的荒谬和不近情理。 《帝王世纪》中有一则野史式的记录，
  说是纣王和妲己都喜欢饮酒，有一次，宫廷内连续数日纵酒狂欢，结果纣王醒来后竟然不知道当天的干支，已经忘记过去了几
  天，只好派人去问箕子。
  #+END_QUOTE

- 6510-6510, 笔记, 2025 年 3 月 17 日星期一 下午 12:55:47
  #+BEGIN_QUOTE md5: 7aae8511cd249d622d468a30f7815639
  内应?
  #+END_QUOTE

- 6685-6685, 标注, 2025 年 3 月 17 日星期一 下午 6:27:19
  #+BEGIN_QUOTE md5: 4b47d10af403f4ca39af48be767e6d2c
  牧野鹰扬
  #+END_QUOTE

- 6733-6735, 标注, 2025 年 3 月 17 日星期一 下午 6:31:41
  #+BEGIN_QUOTE md5: 251e877f491b6cfebac5b48b5a326870
  周文化和商文化很不同，族群性格也差别很大。商人直率冲动，思维灵活跳跃，有强者的自信和麻木；周人则隐忍含蓄，对外
  界更加关注和警觉，总担心尚未出现的危机和忧患。
  #+END_QUOTE

- 6790-6790, 标注, 2025 年 3 月 17 日星期一 下午 6:37:00
  #+BEGIN_QUOTE md5: 95e030c5da7608774fa2353ffc3bec25
  对现代人而言，剖腹取胎是极为残忍的行为，但它可能是商人献祭的常态。
  #+END_QUOTE

- 6859-6859, 标注, 2025 年 3 月 17 日星期一 下午 6:42:33
  #+BEGIN_QUOTE md5: 20883bb14e31ade33922fe156022eb5f
  后世的周人史诗说，“商庶若化”，即是说，商军队伍就像滚水冲 刷的油脂，瞬间溃散，融化。
  #+END_QUOTE

- 6860-6864, 标注, 2025 年 3 月 17 日星期一 下午 6:43:00
  #+BEGIN_QUOTE md5: de7f3040b0758a51a12416e49f50f40f
  喧嚣逐渐沉寂，雨停了，沟壑的积水被血染红，尸体与兵戈和盾牌沉浮其间。在后人的记忆里，那个清晨的牧野，“血流漂杵”。
  当淡淡的阳光穿透晨雾洒向原野间的纵横尸骸，近六百年的商王朝已经终结。太公则在那个黎明变成一只鹰盘旋在牧野上空，
  而积云散去的清晨，自此被周人称作“清明”。 维师尚父，时维鹰扬。凉彼武王，肆伐大商，会朝清明。（《诗经·大雅·大明》）
  #+END_QUOTE

- 6879-6881, 标注, 2025 年 3 月 17 日星期一 下午 6:46:39
  #+BEGIN_QUOTE md5: a218e458f91dda66cb0950cb488dadc1
  纣王焚身而死，后世人大都将其理解为一种走投无路的自绝。其实，按照商人的宗教理念，这是一场最高级的献祭——王把自己
  奉献给了上帝和祖宗诸神。商朝开国之王成汤（天乙）曾经试图这样做，而商纣王则首次实践了它。
  #+END_QUOTE

- 6879-6882, 标注, 2025 年 3 月 17 日星期一 下午 6:46:55
  #+BEGIN_QUOTE md5: cfa5b6087760baf129f21a9ea6a653ee
  纣王焚身而死，后世人大都将其理解为一种走投无路的自绝。其实，按照商人的宗教理念，这是一场最高级的献祭——王把自己
  奉献给了上帝和祖宗诸神。商朝开国之王成汤（天乙）曾经试图这样做，而商纣王则首次实践了它。 纣王曾给诸神贡献过王
  族和方伯，现在他贡献了自己，带着人间最珍贵的宝玉升往天界，成为具有上帝神性的“帝辛”，然后，他自然要给叛逆的周人
  降下灭顶之灾。
  #+END_QUOTE

- 7122-7124, 标注, 2025 年 3 月 18 日星期二 上午 7:58:41
  #+BEGIN_QUOTE md5: b34815f4d0d6be044de413a1a176e0c6
  辅政期间，周公平定了叛乱，还实行了一系列重要举措来巩固新生的周王朝，比如，拆解商人社会，分封周人诸侯，等等。其
  中，有一项非常重要但后世已经完全忘却的举措，就是废止商朝的人祭文化。
  #+END_QUOTE

- 7259-7261, 标注, 2025 年 3 月 18 日星期二 上午 8:08:48
  #+BEGIN_QUOTE md5: 6ca7deaecd411732547a4c85decdb7e8
  所以，真实的周公，个性颇为复杂。其一，他经历过商朝统治和商周易代，深刻了解商人的文化和个性，能在殷都存活下来，
  自然有世俗的生存智慧。其二，过于惨痛的经历也让他对上帝等宗教理念非常警觉，敬而远之，而对“德”则有着近乎“病态”的
  追求。
  #+END_QUOTE

- 7326-7330, 标注, 2025 年 3 月 18 日星期二 上午 8:12:22
  #+BEGIN_QUOTE md5: 851a096958b6463919604fda89d72615
  这次周公与召公的谈话，有些被收入了《尚书·君爽》，其中周公说得最多的是王朝兴亡更替的教训。他认为，这背后虽都有
  天-上帝意志的改变，但唯一能影响天命的因素，是人的“德”，也就是人处理现实问题的准则。所以，周公说，“天不可信”，
  14 人不能奢望去 揣摩天帝的意旨，只需要把世间的义务履行好。
  #+END_QUOTE

- 7354-7357, 标注, 2025 年 3 月 18 日星期二 上午 8:14:31
  #+BEGIN_QUOTE md5: cf3eae497497921ede7387da14068187
  新增了一个“小民”概念，指的是构成王朝主体的普通农夫和贵族封邑里的农奴。按照周公和召公新发展的理论，王应当关注小
  民的生活，听取他们的意见，不要（让贵族）虐待和过度剥夺他们，小民才是王永远获得天命眷顾的基础，所谓：“欲王以小
  民受天永命。”
  #+END_QUOTE

- 7376-7378, 标注, 2025 年 3 月 18 日星期二 上午 8:16:43
  #+BEGIN_QUOTE md5: 2de3a510f5975b77b09c569fc96bd5dc
  其次，自古公亶父以来，周人曾经为商朝捕猎羌俘，这段不光彩的历史也应当被永久埋葬；再次，长兄伯邑考在殷都死于献祭，
  他的父亲和弟弟们还参与并分享了肉食，这段惨痛的经历也必须被遗忘。
  #+END_QUOTE

- 7378-7378, 笔记, 2025 年 3 月 18 日星期二 上午 8:19:45
  #+BEGIN_QUOTE md5: ea0db4cd9711a301143a78992c200673
  和他对德的痴迷有无 guanxine,道德洁癖也会促成此事吧
  #+END_QUOTE

- 7385-7387, 标注, 2025 年 3 月 18 日星期二 上午 8:20:30
  #+BEGIN_QUOTE md5: 07b387e3d57e59657d9c2067ed9e8a61
  或者也可以这么说，在周公辅政时期，周人中已经形成某种明确的“政治正确”：不能批评商人的宗教文化，更不能记录商人曾
  经的血祭行为。
  #+END_QUOTE

- 7385-7388, 标注, 2025 年 3 月 18 日星期二 上午 8:20:43
  #+BEGIN_QUOTE md5: c06cf7b663edc5fe4b296414358a3c37
  或者也可以这么说，在周公辅政时期，周人中已经形成某种明确的“政治正确”：不能批评商人的宗教文化，更不能记录商人曾
  经的血祭行为。在文王和武王期间，周人应该还没有这种忌讳，不然，文王不会在《诗经·荡》中极度愤怒地控诉殷商王朝的
  残暴和堕落；而另一方面，这首诗应该也经过了周公一代人的改造，去掉了关于血祭的那些最为敏感的内容。
  #+END_QUOTE

- 7449-7451, 标注, 2025 年 3 月 18 日星期二 上午 8:25:11
  #+BEGIN_QUOTE md5: a07ac0a0d0cbc9836038b4c79f974043
  在真正的现场发言中，叔侄二人也许会对“殷多士”直言必须禁止人祭行为，但在整理笔录文献的时候，人祭却被替换成了“惟
  虐”“殄戮”等相对含糊的字眼，似乎殷商贵族们只是喜欢滥施刑罚而已。
  #+END_QUOTE

- 7513-7516, 标注, 2025 年 3 月 18 日星期二 上午 8:33:22
  #+BEGIN_QUOTE md5: eb41a1896629882e0730e29c2f3e19c5
  这就是西周初年的“大分封”，周人称之为“封建”：“建”是建立国家；“封”字的来历有些曲折，它的本意是人工筑起土堆，但当
  时尚属草昧时代，诸侯国之间并没有明晰完整的疆界，只是在交通要道筑起一座大土堆代表国界，所以“封”就是给诸侯划定统
  治疆域。
  #+END_QUOTE

- 7517-7517, 标注, 2025 年 3 月 18 日星期二 上午 8:34:01
  #+BEGIN_QUOTE md5: 34ddffb573460a1b6618b57caeb95c2f
  昔周公吊二叔之不咸，故封建亲戚，以蕃屏周。
  #+END_QUOTE

- 7518-7518, 标注, 2025 年 3 月 18 日星期二 上午 8:34:07
  #+BEGIN_QUOTE md5: 7c4953ae716970c84452b8a758cbf7ef
  这是“封建”一词最早的出处，封邦建国之意。
  #+END_QUOTE

- 7542-7543, 标注, 2025 年 3 月 18 日星期二 上午 8:37:08
  #+BEGIN_QUOTE md5: 15ed6f0d7447bd9d3f6590d193b4ff44
  周公等贵族都有不只一个儿子，但幼子一般不会被分封到外地，而是在京畿获得一块封邑，继承父亲在朝廷的职位。
  #+END_QUOTE

- 7551-7560, 标注, 2025 年 3 月 18 日星期二 上午 8:39:36
  #+BEGIN_QUOTE md5: 1166bc9d166a14973890eaba0fa3dc42
  陈、蔡和蒋。它们控制了东南方的部分夷人地区，为周人继续向东南和西南扩张埋下了伏笔。 跨族婚姻与民族融合 伴随着周
  人大分封运动的，是广泛而持续的民族融合。由此，新的华夏族逐渐成形。 这和周人传统的“同姓不婚”（族外婚）习俗有直
  接关系。周人的“姓”是区别种族血缘的概念，它承认不同的族群血缘有区别，但又认为各族群是平等的，不仅可以，而且必须
  互相通婚。 那些被分封到远方的周族姬姓诸侯国的国君和高级贵族，都要从外国寻找异姓配偶，而低级贵族则多与本国内的
  异姓贵族通婚。各族群的贵族由此进入了一张巨大的联姻之网，异姓侯国的上层逐渐被周人同化，逐渐融入了周朝的政治同盟
  和文化共同体。他们追求的成功是获得周天子的册命，与姬姓诸侯嫁娶通婚，甚至在周王朝廷获得一个官职。由此，以今河南
  省为中心，环以陕、晋、冀、鲁部分地区，形成了一个跨地域的贵族阶级-周文化共同体。
  #+END_QUOTE

- 7555-7560, 标注, 2025 年 3 月 18 日星期二 上午 8:39:45
  #+BEGIN_QUOTE md5: e33f565cf6de7a7f4771cc26d597a3f9
  周人的“姓”是区别种族血缘的概念，它承认不同的族群血缘有区别，但又认为各族群是平等的，不仅可以，而且必须互相通婚。
  那些被分封到远方的周族姬姓诸侯国的国君和高级贵族，都要从外国寻找异姓配偶，而低级贵族则多与本国内的异姓贵族通婚。
  各族群的贵族由此进入了一张巨大的联姻之网，异姓侯国的上层逐渐被周人同化，逐渐融入了周朝的政治同盟和文化共同体。
  他们追求的成功是获得周天子的册命，与姬姓诸侯嫁娶通婚，甚至在周王朝廷获得一个官职。由此，以今河南省为中心，环以
  陕、晋、冀、鲁部分地区，形成了一个跨地域的贵族阶级-周文化共同体。
  #+END_QUOTE

- 7567-7571, 标注, 2025 年 3 月 18 日星期二 上午 8:40:54
  #+BEGIN_QUOTE md5: 18188ca0ddaac8ba3a34257c92e93639
  新兴的周文化，是西土周族传统文化和商文化的融合：一，它继承了商人的文字体系，但部分语言习惯来自周族；二，它继承
  了商人的“上帝”观念，但又逐渐将其淡化为含义模糊的“天”；三，它严厉禁止商人的人祭宗教，拉远人和神界的距离，拒绝诸
  神直接干预人间事务；四，周人谨慎，谦恭，重集体，富于忧患意识，这些都成了新华夏族的样板品格。
  #+END_QUOTE

- 7611-7614, 标注, 2025 年 3 月 18 日星期二 下午 12:11:39
  #+BEGIN_QUOTE md5: a74fba12ef17781e40e63921bb44d473
  随着统治阶层的繁衍，周朝特色的贵族制度逐渐得以形成，其中，最首要的是“宗法”家族制，
  核心则是嫡长子一系的独尊地位。 一，周朝各姬姓诸侯（被分封的王室亲属）对周王的效忠服从，是家族兄弟（及其后人）
  对嫡长兄（及其嫡系后人）的服从。 二，在各诸侯国内部，太子之外的公子被分封为世袭大夫，大夫再繁衍和分封出“士”。
  #+END_QUOTE

- 7611-7615, 标注, 2025 年 3 月 18 日星期二 下午 12:11:48
  #+BEGIN_QUOTE md5: 23fe06922ebd2380ebc90739f34f0287
  随着统治阶层的繁衍，周朝特色的贵族制度逐渐得以形成，其中，最首要的是“宗法”家族制，
  核心则是嫡长子一系的独尊地位。 一，周朝各姬姓诸侯（被分封的王室亲属）对周王的效忠服从，是家族兄弟（及其后人）
  对嫡长兄（及其嫡系后人）的服从。 二，在各诸侯国内部，太子之外的公子被分封为世袭大夫，大夫再繁衍和分封出“士”。
  三，非周族的异姓诸侯和贵族则通过婚姻关系被纳入家族结构中
  #+END_QUOTE

- 7627-7629, 标注, 2025 年 3 月 18 日星期二 下午 12:13:09
  #+BEGIN_QUOTE md5: ee7e94a60c93edf5a9d3dda88117e453
  到周幽王时期，贵族诸侯间的派系之争则更为激化。周幽王试图疏远那些长期得势的姬姓和姜姓诸侯，
  利用另外一些诸侯国的力量废 黜了来自姜姓申国的王后以及王后生的太子宜臼，引发了周朝的激烈内战。随后，
  北方犬戎部落受邀介入，结果关中和镐京在混战中沦为废墟，幽王被杀。
  #+END_QUOTE

- 7685-7685, 标注, 2025 年 3 月 18 日星期二 下午 12:14:00
  #+BEGIN_QUOTE md5: da014661355f927e949fa2101a78ced9
  诸神远去之后
  #+END_QUOTE

- 7688-7689, 标注, 2025 年 3 月 18 日星期二 下午 12:14:22
  #+BEGIN_QUOTE md5: ff9c20f8d27bde349884574c791125b4
  曾经漫游黄河南北的水牛、犀牛和亚洲象也迅速消失了，亚热带风情永远地离开了华北。全新世大暖期的顶峰已过，
  地球正进入下一轮冰期的旅程。
  #+END_QUOTE

- 7689-7693, 标注, 2025 年 3 月 18 日星期二 下午 12:15:18
  #+BEGIN_QUOTE md5: 41194e9fd9d6c55cb51c1e7f23cb1b5b
  周公的“改制”恭敬地解除了上帝和诸神对世间的掌控，把他们奉送到距离尘世极为遥远的彼岸世界。
  诸神远行似乎也带走了一切奇伟莫测，留给人间的只有平庸的平和，以及残留着种种传说的巨大废墟。不过，
  诸神及其神迹并未消失，只是它们不再返回东亚，而在此后的美洲大陆上，玛雅和阿兹特克等文明将相继繁荣，
  且伴随着盛大的人祭仪式以及精美的图画文字、石雕和巍峨的金字塔神庙。
  #+END_QUOTE

- 7704-7705, 标注, 2025 年 3 月 18 日星期二 下午 12:16:27
  #+BEGIN_QUOTE md5: 8b65073bf7fb5cb6c5a7497caf9ee266
  在周朝的控制范围之外，人祭行为还有星星点点的存在，比如，有东夷血统的恶来的后人秦族，虽然被周朝几度迁徙，
  但秦族首领仍一直顽固地保留着人祭、人殉和人奠基的风习。
  #+END_QUOTE

- 7705-7705, 笔记, 2025 年 3 月 18 日星期二 下午 12:17:04
  #+BEGIN_QUOTE md5: 81c393f9aa72499f1417ee47b76a3c17
  秦皇陵和这个有关系吗
  #+END_QUOTE

- 7768-7770, 标注, 2025 年 3 月 18 日星期二 下午 12:18:44
  #+BEGIN_QUOTE md5: f997a92a412e93005dc87cfcf7e6f11f
  周公执政时期不仅禁止人祭、人奠基和人殉行为，同时还禁止在书面文献中提及商人的这些风俗，结果，
  铲除人祭的记录也和人祭行为一起消失了，只剩下了地层中那些无法销毁的遗迹。
  #+END_QUOTE

- 7793-7794, 标注, 2025 年 3 月 18 日星期二 下午 1:14:22
  #+BEGIN_QUOTE md5: 3281890ea1f3062f7dfc155a5a505b91
  这几次人祭事件显示，在春秋中晚期，人祭活动曾在官方层面有过局部复活。
  #+END_QUOTE

- 7807-7808, 标注, 2025 年 3 月 18 日星期二 下午 1:15:38
  #+BEGIN_QUOTE md5: 7f542aa6c6141f82416707287efb468d
  当时还有制作陶人俑随葬和埋入祭祀坑的习俗，结果遭到孔子诅咒：“始作俑者，其无后乎！”
  #+END_QUOTE

- 7853-7855, 标注, 2025 年 3 月 18 日星期二 下午 1:17:53
  #+BEGIN_QUOTE md5: 7ba2e46ab8f840f419d62914cc64c423
  周灭商后，以杀戮和人祭为特色的华夏旧文明戛然而止，取代它的，是周公营造的新华夏文明。
  周公消灭了旧华夏文明及其相关记忆，打破了族群血缘壁垒，让尘世生活远离宗教和鬼神世界，
  不再把人类族群的差异看作神创的贵贱之别。这是华夏文明最彻底的一次自我否定与重生。
  #+END_QUOTE

- 7901-7902, 标注, 2025 年 3 月 18 日星期二 下午 1:22:12
  #+BEGIN_QUOTE md5: 7866c93a40ba5b7b150f5935e5c7a35e
  周人尊礼尚施，事鬼敬神而远之，近人而忠焉，其赏罚，用爵列，亲而不尊。
  #+END_QUOTE

- 7900-7901, 标注, 2025 年 3 月 18 日星期二 下午 1:22:20
  #+BEGIN_QUOTE md5: 139692898d5db77093254d3c4eaf28e8
  殷人尊神，率民以事神，先鬼而后礼，先罚而后赏，尊而不亲。其民之敝，荡而不静，胜而无耻。
  #+END_QUOTE

- 7901-7902, 标注, 2025 年 3 月 18 日星期二 下午 1:22:30
  #+BEGIN_QUOTE md5: c1bdb8316c1a9a1243380767545e4728
  周人尊礼尚施，事鬼敬神而远之，近人而忠焉，其赏罚，用爵列，亲而不尊。其民之敝，利而巧，文而不惭，贼而蔽。
  #+END_QUOTE

- 7914-7916, 标注, 2025 年 3 月 18 日星期二 下午 1:24:20
  #+BEGIN_QUOTE md5: 5a1d919a70d79911644d039aff959208
  春秋晚期，孔子则用了一个字来定义人和人之间的道德标准，这便是“仁他的学生樊迟问他仁的含义，孔子曰：“爱
  人。”（《论语·颜渊》）而实现仁爱的方法，则是“恕”：“己所不欲，勿施于人。”（《
  #+END_QUOTE

- 7928-7932, 标注, 2025 年 3 月 18 日星期二 下午 1:25:49
  #+BEGIN_QUOTE md5: e2359fdbf0f26693c69916fd16a710c3
  周公销毁了商朝诸多甲骨文记录，也禁止殷周贵族书写真实的历史。但周公唯一不敢销毁的，是文王留下的《易经》。
  这不仅是出于对父亲的尊重，也因为《易经》是周人对翦商事业（起步）的记录，里面很可能包含着父亲获得的天机，
  销毁它也就是对父亲和诸神的不敬。 周公的办法是对《易经》进行再解释，
  具体方法则是在文王创作的卦爻辞后面加上一段象传进行说明。
  #+END_QUOTE

- 7972-7975, 标注, 2025 年 3 月 18 日星期二 下午 1:30:33
  #+BEGIN_QUOTE md5: a1a6a9ef6933c16acba676271bcef2b5
  孔子的学生子贡却试图为纣王“翻案”： 纣之不善，不如是之甚也。是以君子恶居下流，天下之恶皆归焉。（《论语·子张》）
  大意是说，纣王的恶行并不像人们传说的那样过分，这就像是一个地方被当成了垃圾场，人们就专门往那里丢垃圾，
  纣王的形象也是被这样堆积出来的。
  #+END_QUOTE

- 7971-7975, 标注, 2025 年 3 月 18 日星期二 下午 1:30:37
  #+BEGIN_QUOTE md5: 0359d1d5ea63a255b7e23b60e1fe28a8
  在周公版的历史中，商人从没有过残忍的人祭宗教，商朝的灭亡只是因为纣王-帝辛个人的道德堕落，
  但孔子的学生子贡却试图为纣王“翻案”： 纣之不善，不如是之甚也。是以君子恶居下流，天下之恶皆归焉。（《论语·子张》）
  大意是说，纣王的恶行并不像人们传说的那样过分，这就像是一个地方被当成了垃圾场，人们就专门往那里丢垃圾，
  纣王的形象也是被这样堆积出来的。
  #+END_QUOTE

- 7986-7987, 标注, 2025 年 3 月 18 日星期二 下午 1:31:48
  #+BEGIN_QUOTE md5: 9344108b5a4ca79ec2fb9867dd198b7f
  这都是孔子晚年才会有的感慨。《史记》与此相关的记载是，孔子晚年频繁地研读《易经》，结果编竹简的皮条磨损严重，
  经常断裂，所谓“韦编三绝”。
  #+END_QUOTE

- 7988-7989, 标注, 2025 年 3 月 18 日星期二 下午 1:32:04
  #+BEGIN_QUOTE md5: a5e619a329dad1a75a7a5b7a8796ec68
  孔子晚而喜易，序彖、系、象、说卦、文言。读易，韦编三绝。日：“假我数年，若是，我于易则彬彬矣。”（《史记·
  孔子世家》）
  #+END_QUOTE

- 8002-8006, 标注, 2025 年 3 月 18 日星期二 下午 1:34:16
  #+BEGIN_QUOTE md5: 368ba453cd8edef9fba6eadfec688e5a
  此外，《系辞》还认为《易经》的作者充满了忧患之情： 作《易》者，其有忧患乎？ 这种理解已经很接近真实的文王时期，
  而和周公的《象辞》很不一致，说明五十七岁之后的孔子已发掘出越来越多当年被周公隐藏的真相（商朝的血祭文化）。
  但是，孔子没有继续点破真相，而是频繁地翻检《易经》，以至“韦编三绝”。或许，
  孔子正是想从隐晦而杂乱的文王卦爻辞中复原出尽可能多的内容。
  #+END_QUOTE

- 8020-8023, 标注, 2025 年 3 月 18 日星期二 下午 6:36:00
  #+BEGIN_QUOTE md5: 8c5c99954081d1d37325875012b8af53
  孔子晚年最重大的工作，是编辑儒家经典“六经”。 这是按照周公精神对历史文献进行的一次前所未有的系统整理。“六经”
  成书后，从上古到孔子时代的历史叙事的权威版本就此诞生，也标志着周公开创新华夏、埋葬旧华夏的工作得以正式完成。
  而孔子则以此向周公致敬，并参与、发展了周公的事业。
  #+END_QUOTE

- 8069-8073, 标注, 2025 年 3 月 18 日星期二 下午 6:39:18
  #+BEGIN_QUOTE md5: 278c6262353caf96a9f02cbca9c28199
  概而言之，周公时代变革的最大结果，是神权退场，这让中国的文化过于“早熟”；战国时代变革的最大结果，是贵族退场，
  这让中国的政治过于“早熟”。而在其他诸人类文明中，神权和贵族政治的退场，都发生在公元 1500 年之后的所谓近现代时期。
  周公和孔子的努力维持了两三千年，直到考古学家的铲子挖出夏、商遗址，被“六经”等古文献掩盖和误读的历史真实，
  才得到重新诠释与复原。 我们被考古学改变的认知，不只是夏商。
  #+END_QUOTE

- 8172-8173, 标注, 2025年3月18日星期二 下午6:45:43
  #+BEGIN_QUOTE md5: c8fbdbd0c03942ffb4f80db01e845db1
  让我意识到除了祭祀坑里的尸骨，这世界 上还有别的东西。 也许，人不应当凝视深渊；虽然深渊就在那里。
  #+END_QUOTE
